### ISSUE TITLE
Failed to reset password on Beta site

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#1067]
@pkdash I found out that when I use the "reset password" page to reset my password https://beta.hydroshare.org/accounts/password/reset/?next=/accounts/update/ , I got the following error. 

I didn't change the Username and just want to change a new password. The error info is misleading and the system makes the user unable to set a new password if the username is not changed at the same time.

The password reset works fine on WWW site. But  it doesn't work on Beta. Please retest it to make sure this issue exists. Thanks

![image](https://cloud.githubusercontent.com/assets/5016511/13995523/23e3534c-f0ef-11e5-842a-aa308fd2fcff.png)

**Comment by hyi** [comment]
@gantian127 @dtarb @mjstealey I pulled in the latest develop and tested it out in my local development environment but cannot reproduce this issue. Everything works as it should in my local dev env. According to @gantian127, it works as expected on www as well. Not sure why this issue happens on beta only, but I think rather than spending time to dig through the code to figure out why it happens on beta only, we should probably just close it since it only happens on beta deployment this time. Of course if it crops up again and reveals some underlying problem, we should look at it again. But at this point, it does not look like so since I cannot reproduce it locally and it works as expected on www. I'll defer this to @mjstealey in case @mjstealey wants to look into beta deployment or have ideas on what could be causing this beta-only issue.

**Comment by hyi** [comment]
@gantian127 Could you try this on the newly deployed www to see if the issue exists or not? If not, could you close this issue?

**Comment by gantian127** [comment]
@hyi I just tested on the www site and it works as expected now. I will close the issue. Thanks for working on this issue.
