### ISSUE TITLE
General UI style/grammar changes from issue [#106]

### ISSUE THREAD

**Issue by mauriel133** [hydroshare/hydroshare#110]
I will be addressing some of the suggestions addressed in #106

**Comment by mjstealey** [comment]
@mauriel133 - Could you please update the checkbox items in issue #106 to reflect the items that you will be working on in this branch? We can then divide the remaining items into other developers branches that will also be looking at these.

As an example, adding your branch number to the checkbox item that will be addressed.

- [ ] \(Next Release) [#110] Select latitude and longitude from a map instead of typing it in

**Comment by mauriel133** [comment]
Understood. Could you please add me to the repository so I can make those changes?

**Comment by mjstealey** [comment]
Will need to modify the production database directly in order to accommodate any fixes that were submit as part of pg.hs_init_db.sql as that database only resides in the development environment.
