### ISSUE TITLE
Obsolete res (res has newer versions) should be immutable to prevent unexpected change through api

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#1116]
Obsolete res (res has newer versions) should be set immutable on backend to prevent unexpected change through api

**Comment by hyi** [comment]
@horsburgh @dtarb Currently we allow users to share obsoleted resources. Want to make sure this is indeed what we want while I set immutable to True for obsoleted resources so that obsoleted resources cannot be modified via REST API. Otherwise, if we want to disable sharing of obsoleted resources, I can address it as part of this issue by setting sharable attribute on the resource to False and update Sharing status and disable manage access from landing page for obsoleted resources.

**Comment by dtarb** [comment]
I am going to defer to @horsburgh on this.  I do not want to micromanage or take the time to work through the edge cases involved in the versioning model that was already worked out to respond substantively.

**Comment by hyi** [comment]
@horsburgh After giving this a bit of more thought, I think current implementation makes sense that allows users to manage access control for obsoleted resources. Since we set immutable flag to True for obsoleted resources, all users with edit and owner privileges are downgraded to VIEW privilege by access control policy, so they cannot really modify obsoleted/immutable resources any way, but they can still add other people access privileges if they want to allow them to view obsoleted resources. This appears to be consistent with our current access control policy. So I will just create a PR for this specific issue to set immutable flag to True for obsoleted resources without touching sharable and manage access control part. We can always create another issue as needed if we decide to change current behavior for managing access control for obsoleted resources.

**Comment by horsburgh** [comment]
Ok. I think this may be one of those things where we have to see what users want - or see if we have conflicts and issues. I'm OK with your current plan.

**Comment by hyi** [comment]
immutable has been set for obsoleted resources, so I am closing this issue.
