### ISSUE TITLE
Unable to comment

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1137]
I tried to comment on the resource https://www.hydroshare.org/resource/0f3bcaee15b747308ceb74dde755e6d9/ and get the message, sorry an error occurred.

I wanted to ask @danames to delete the resource in the spirit of spring cleaning and to address #1132.

**Comment by hyi** [comment]
@dtarb This is an issue I am aware of since it happened once in a while in a new deployment with www existing resources. The issue was primary key conflict when adding a comment to a resource. Somehow a new comment being added to a resource will have the same primary key with an existing comment with the same primary key ID. When you try to add comment again, the primary key will increase by 1. After a few tries (depending on which number the conflict primary key starts with), eventually there will be no conflict, and from then on, everything runs as expected. Since we are using Mezzanine commenting system, I have not got time to dig into Mezzanine's codebase to track it down, so I am assigning this to myself for bookkeeping and will look into it when I have time. For now, the workaround is to keep trying the same thing for a few times until you don't see error any more, and then everything will run as expected.

**Comment by hyi** [comment]
@jbradberry I am putting this issue on your plate for an initial investigation to see whether it is something you can resolve quickly as @dtarb suggested. I have never got a chance to look into this due to other priorities, but know this issue would be a difficult non-traditional one, and could potentially be time-consuming to get to the bottom of it. See my comment above for a bit of detail regarding Mezzanine we are using for commenting. It is also the same issue we chatted a little bit that you suggested a possible cause could be database sequence-related.

**Comment by hyi** [comment]
Adding description from the issue #1342 to this one since they have the same root cause and hence can be treated as duplicate: I just tried to reply to a comment on the following resource https://www.hydroshare.org/resource/93f49ab913fd4c639c98ab4a070d20e0/. Clicking on reply below the comment does nothing, so I had to respond with a new comment.

**Comment by dtarb** [comment]
@hyi can you test this out on https://www.hydroshare.org/resource/7ca4a9c95d344825b68e868ec446c8ca/.  I do not want to clutter up comments on the resource first mentioned, which is public and cited, with testing.  If you write a comment on the Logan Outlet resource, I will try write a reply.  Once we are done I will delete the resource.

**Comment by hyi** [comment]
@dtarb Done. You can try to reply my comment and see whether it works.

**Comment by dtarb** [comment]
It appears to be working, at least for today.  Has anything changed to increase the reliability. @jbradberry suggested something related to persisting the database.  Has this been done.  If we think this issues has been fixed, I would be happy to close this, but I would like @jbradberry and @mjstealey to weigh in.

**Comment by jbradberry** [comment]
I believe that this is fixed by persisting the database.  +1 to close.

**Comment by dtarb** [comment]
@mjstealey is the database now persisted.

**Comment by mjstealey** [comment]
> @mjstealey is the database now persisted

yes

**Comment by dtarb** [comment]
Tested - seems OK, so closing.
