### ISSUE TITLE
HydroShare GIS to support VRT raster resources

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1158]
HydroShare GIS needs to support the VRT raster model that has multiple .tif files representing a logical raster.  See https://www.hydroshare.org/resource/e3291fe5d437485d8376c9a08fb6bced/ for an example of a .vrt raster and https://www.hydroshare.org/resource/019ada01c9b04c66aa1d9194d6149e40/ for a map app that attempts to load this but only shows part of the resource (though after having created this I am not having success reloading it).

**Comment by shawncrawley** [comment]
I could not find anything in GeoServer's documentation about VRT files, but most google searches with keywords: "geoserver" and "vrt" did return documentation regarding an ImageMosaic. I have implemented uploading VRT raster resources as an ImageMosaic, and it appears to work. However, since I could not find any mention of VRT files by GeoServer, I am skeptical that their upload algorithm is actually reading the VRT file. 

Could I have someone (likely @dtarb) upload a couple of VRT raster resources for testing? @zhiyuli was telling me that there are certain cases where the VRT file actually specifies some sort of subset (or sub-bounds) of the raster mosaic. Those are the cases that I'd be afraid GeoServer is not handling, since it seems likely that GeoServer is just pulling in each of the TIF files that are part of the ZIP upload as is. I hope that makes sense.

**Comment by gantian127** [comment]
@shawncrawley Here is one example VRT dataset in HydroShare: http://www.hydroshare.org/resource/9439e7b98d334d7eaf9601a1a5bfa6c1

If you want know more about the VRT raster data you can have a look at this site. http://www.gdal.org/gdal_vrttut.html

**Comment by dtarb** [comment]
Here is a resource formatted as a raster that uses VRT.  https://www.hydroshare.org/resource/e3291fe5d437485d8376c9a08fb6bced/

**Comment by shawncrawley** [comment]
@dtarb As I already let you know, it appears that GeoServer does not recognize or do anything with .vrt files. They do, however, allow for multiple rasters to be uploaded as one composite raster with an ImageMosaic option (see http://docs.geoserver.org/2.7.0/user/data/raster/imagemosaic.html). The image mosaic will work great for the most basic VRT case (where the .vrt file really only specifies which .tif files should be gathered and displayed together). In the case that a .vrt file indicates that a subset of a .tif file (or group of .tif files) should be displayed, the ImageMosaic option will be deficient.

So I am wondering if this issue should be closed for now until we find it possible to fully implement .vrt files through GeoServer, or if we just keep it open until the issue can be resolved more fully and completely.

**Comment by dtarb** [comment]
Lets use the image mosaic option and when this is working (which it is not now for the resource https://www.hydroshare.org/resource/317c2643c0c84512b9b32492c08ec7d5/) then we can close this.  Lets limit our raster data model to only tiff files that comprise a mosaic (i.e. do not overlap).  @gantian127 please document this as part of the raster data model.

**Comment by shawncrawley** [comment]
This issue likely could have been closed a while back. If there have been no recent recurrences of the issue, then let's close it.

**Comment by danames** [comment]
I just tested this fix using the resource @dtarb posted on July 12. It works as advertised so I am closing this issue.

**Comment by danames** [comment]
Works as advertised with @dtarb's test data. I'm closing this issue.
