### ISSUE TITLE
Map search doesn't show all the List search results

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#1189]
I got 14 items in the List and Map only shows 5 of them.But if this issue has been reported or this is working as expected, please close this issue.

![image](https://cloud.githubusercontent.com/assets/5016511/14960933/7e3ab8ba-1054-11e6-9afd-ce096f27776a.png)
![image](https://cloud.githubusercontent.com/assets/5016511/14960950/8e910124-1054-11e6-872d-e63df6fee33d.png)

**Comment by xuezhaokun** [comment]
@gantian127 Because not all resources have "box_coverage" or "point_coverage" fields. We create markers only for resources with "coverage" feature.

**Comment by gantian127** [comment]
@xuezhaokun the 13 of the 14 items should have coverage information. Most of them are raster or netcdf resources.

**Comment by xuezhaokun** [comment]
@gantian127 How did you generate these results? I will take a look at it.

**Comment by mjstealey** [comment]
@xuezhaokun - I suspect she typed her last name "Gan" as the search criteria. The results may actually be correct, though somewhat misleading. It seems that for some of these, but coverages are identical and stack the results.

![screen shot 2016-05-02 at 1 10 03 pm](https://cloud.githubusercontent.com/assets/5332509/14961394/3740426e-1067-11e6-8399-df4240971ab9.png)

And a couple of the resources are dead links from the resource landing page point of view (do not exist in the iRODS copy this server is pointing to).

**Comment by xuezhaokun** [comment]
@mjstealey @gantian127 Yes. Some resources have identical coverages, they are listed in the same marker. The numbers on the map just show the number of markers in that cluster. I am not sure about the iRODS issue. I remember we had this problem before. I though it has been fixed. @mjstealey Do you have any idea about it?

**Comment by mjstealey** [comment]
> I am not sure about the iRODS issue

This is an irsync error in that the request to copy a resource fails when reading from www. Unsure why this is the case. The resources are all intact and viable on www, but the copies which are used by development deployments like alpha and beta are not 100% complete.
Hoping the v4.1.8 upgrade makes debugging this particular issue a bit easier.

**Comment by xuezhaokun** [comment]
@mjstealey I see. Thanks for updating.

**Comment by gantian127** [comment]
@xuezhaokun @mjstealey  sorry for the late reply. I typed my full name to get the results.

**Comment by dtarb** [comment]
@xuezhaokun @alvacouch, @gantian127 and I discussed this following the call today.  The following is what seems misleading to us. To a user the concept of the number of resources is meaningful, but the number of unique coverages is not.  Here is the example.  

This suggests 5 resources at one spot and 2 at another.
![p1](https://cloud.githubusercontent.com/assets/3456833/15021950/a7022baa-11e6-11e6-9d5b-f1c7dbb6bddb.PNG)

Now we zoom in on the 2 and they split.
![p2](https://cloud.githubusercontent.com/assets/3456833/15021996/ca0de328-11e6-11e6-9307-1c3c23ee643f.png)

However if we click on one of the symbols we get multiple resources underneath.  A user has no way to know that there are really 5 resources here and may have been mislead even getting here because they saw the 2 in the aggregated plot before.
![p3](https://cloud.githubusercontent.com/assets/3456833/15022049/02676a14-11e7-11e6-8200-72dd370ff6d4.png)

So my suggestion is that for the aggregated symbols (first figure above) that the numbers show the total number of resources, not unique coverages.

Then when it comes to individual points such as the second figure above, if there are multiple resources a separate symbol that gives the number of resources with the same coverage should be shown.  Then when a user clicks on it they can see the list.  

An alternative (or extension) might be to allow a user to right click on the blue aggregate symbol at any level of zooming and see all the resources under the symbol.

A complication exists in that you may have point resources and box resources of different dimensions that have the same center point.  There is no good way then to show the boxes for individual resources.  A selection symbol next to the expanded list such as the 3rd figure above could be used to select and indicate the resources where the box coverage is to be shown.

The concept of selection (and even selecting multiple resources) may be useful later if we want to add functionality to act on selected resources (such as add to my resources, or tag).

**Comment by horsburgh** [comment]
Just to throw another option out there:  I've seen sites that use a "spiderfier" to explode multiple markers out of a single google map marker when clicked.  There's a demo here:

http://codepen.io/hellokatili/pen/BopYya

It starts as a cluster, but then as you zoom in it turns to a marker and then if you click on the marker it pops out multiple markers.

**Comment by xuezhaokun** [comment]
@dtarb @horsburgh Thanks for the suggestions! This "spiderifer" method is really impressive. I will discuss about it with Alva.

**Comment by alvacouch** [comment]
@dtarb @horsburgh 

We have implemented spiderify and it would seem to address your concerns. Will do PR.

**Comment by horsburgh** [comment]
Cool - could this get deployed to one of the testing environments so we could try it out?

**Comment by xuezhaokun** [comment]
@mjstealey Can you help us to deploy PR #1208 to one testing environment?

**Comment by hyi** [comment]
@gantian127 Can you verify to see whether this issue has been resolved and close if yes?

**Comment by dtarb** [comment]
Map discovery is being worked over as noted in #1361 and I think these comments are obsolete, so I am closing.
