### ISSUE TITLE
Implement River Geometry Phase 1 functionality

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#12]
This involves
1. Settle the resource content model. This implies specification of the name for the resource type and documentation of the storage format.  Specify the scientific metadata.  Initial implementation should focus only on the river geometry aspects of the HY_features model, with links to other elements to be done later. 
2. Add capability to upload and download resource files that are already in the specified storage format through web interface. Edit metadata through web interface. Serialize metadata.
The step 2 capability handles raw files required by this model and may parse metadata out of them but does not support loading of entire resources in the bagit packaging format.

Phase 2 and beyond are not part of this step and include the following that should be incrementally added later
3. Add capability to upload and download resource files already in specified storage format through API. Set and get metadata through API.
4. Visualization tool
5. Tools for establishing a web service endpoint to serve this resource content (RiverML)
6. Tool to import resource packages as a complete resource data model bag. This involves a reflector function to generate the metadata in Django from the XML format metadata and will support direct exchange of this resource type with iRODS and with other clients.
7.  Establishing a more general digital watershed functionality that is a composite resource that may be a collection of river geometry, river network (as geographic feature), land surface layers (as geographic raster) and others.

**Comment by valentinedwv** [comment]
Geometry Examples
* NFIE examples are being uploaded by Tim Whiteacker
* Map of resources on arcGIS online (link TBD)

Identifiers:
* need to develop a pattern so that when data is extracted, identifiers are transfered

Cross Sections and ratings from NFIE
* Loading cross sections will initially use a simple CSV files
* DM suggests
 * ratings and guagings standard for exposing the cross sections and ratings
 * the exposing using Ratings and Gaugings API http://waterml2.csiro.au/rgs-api/v1/docs/ (swagger doc: http://waterml2.csiro.au/rgs-api/v1/?format=api )

**Comment by twhiteaker** [comment]
# File Format -- why CSV
My first thought was to look at a HEC-RAS file as a starting point, to see how hydraulic software might store cross sections. With x-y pairs appearing in two columns, it didn’t seem like a very interoperable solution to me. On 2015-01-08, Dave Valentine suggested initially using comma separated values (CSV) files for cross sections, and I now agree with that approach. It’s human readable, can be parsed by many programs, and seems like a low barrier for users to overcome if they want to share their cross sections in HydroShare. 
# The Three Files that Comprise a Cross Section
A cross section resource includes three CSV files. 
* __cross_section.csv__ - Station-elevation tuples along the cross section
* __rating_curve.csv__ - Stage-elevation-discharge-frequency relationship
* __transect_vertices.csv__ - Locations of vertices of cut line, for plan-view display in a map

Each file includes a header at the top, indicated by a hash symbol `#` as the first character in the line. The header for all files includes the following metadata. I am currently not suggesting any controlled vocabularies for these terms. I’m also not specifying what is required and what is optional at this point. There may be merit in storing this metadata in a single rather so that it does not become out of sync across three files.

* __River Name__ - The name of the river. I took this attribute from HEC-RAS. I suppose it’s up to the application or use to decide what river name should be.
* __Reach Code__ - Unique identifier for the river reach. HEC-RAS calls this Reach Name, but I am using Reach Code to be more in line with NHD, since we’re using NHD for NFIE. See my NFIE bias here?
* __Measure__ - Distance measure along the reach at which the cross section is located. HEC-RAS calls this River Station. I’m using Measure to be more in line with NHD terminology.
* __Measure Units__ - Units of measure associated with the Measure attribute.

Additional metadata pertinent to a given file is also provided. Following the header is the data in CSV format.

## cross_section.csv
Stores station-elevation tuples along the cross section. Here we assume the common convention of stations starting on the left side of the cross section when looking downstream. Elevation is with respect to a datum. I had originally thought to include latitude, longitude, and z coordinates for each point along the cross section. However, I found that HEC-RAS doesn’t readily give you this information. Furthermore, coordinates in this file could become out of sync with coordinates in the transect_vertices file.

Additional metadata includes station units, elevation units, and vertical datum.
```
# River Name: ONION
# Reach Code: OC-1
# Measure: 99400
# Measure Units: ft
# Cross Section Station Units: ft
# Elevation Units: ft
# Vertical Datum: NAVD 88
Station,Elevation
570,590
610,580
867,570
1610,560
2800,555.2
2900,555.6
```
## rating_curve.csv
Stores stage-elevation-discharge-frequency relationship. Rating curves commonly just include stage (height above river channel bottom) and discharge. Elevation is important when you want compare the water surface to elevations in the surrounding landscape for estimating inundation. Frequency is flood frequency, e.g., the 50-year-event. Frequency is in units of years. Perhaps frequency should be optional.

Additional metadata includes stage units, elevation units, vertical datum, and discharge units.
```
# River Name: ONION
# Reach Code: OC-1
# Measure: 99400
# Measure Units: ft
# Stage Units: ft
# Elevation Units: ft
# Vertical Datum: unknown (assumed MSL)
# Discharge Units: cfs
Stage,Elevation,Discharge,Frequency
0,524.4,0,0
27.0983,551.4983,31700,10
35.1634,559.5634,87500,20
37.299,561.699,114600,100
```
## transect_vertices.csv
Stores locations of vertices of cut line, for plan-view display in a map. Coordinates must be latitude and longitude in decimal degrees. Additional metadata includes horizontal datum.
```
# River Name: ONION
# Reach Code: OC-1
# Measure: 99400
# Measure Units: ft
# Horizontal Datum: WGS84
Latitude,Longitude
30.16659841,-97.77386238
30.16372008,-97.76760224
30.15857716,-97.76628611
30.15807218,-97.76588227
```
# Other Considerations
As our team has discussed this resource type, there was talk of creating separate resources types for the station-elevation tuples and rating curve. There is already a geospatial resource type in the works that we could use for the transect vertices. You would then create a composite cross section resource linking the three parts of a cross section together.   Another debate is whether a cross section resource should include only a single cross section, or multiple cross sections. My use case driving this design is for the National Flood Interoperability Experiment (NFIE), and since David Maidment wants these three components (station-elevation, rating curve, transect vertices) together as a single resource per cross section for the NFIE, I am suggesting that a cross section resource include the files as I have described above.

The neat freak in me wants to store cross section data in a SQLite database. This seems to be where Dan Ames is going with storing geospatial data. It would also be more convenient, perhaps, for storing more than one cross section in a given resource if we decide that’s what we want to do.

I suggest we consider RiverML, Hy_Features, WaterML Part 2 (ratings and gaugings), Arc River, and Arc Hydro in the future. These specs offer data formats, data models, or even just nomenclature that we might adopt.

**Comment by twhiteaker** [comment]
Example files: http://beta.hydroshare.org/r/7f6b50d620ae4ee3b405cdf4fb08e80a/

**Comment by dtarb** [comment]
I suggest starting initial implementation based on this model, with a recognition that there may need to be adjustments as use practices and issues arise.  

Some questions and comments:
1. Each resource is intended to be complete in some sense so it can stand alone as a published entity, with title, abstract, list of creators, coverage and eventually DOI.  Single cross sections are quite fine grained for doing this.  For entry who will type in all the abstracts, or will you devise a way to automatically input a generic abstract.

2. There may be ambiguity related to orientation as when a cross section is standing alone the left side looking downstream may not be specified.
Is measure from the upstream or downstream end of a reach. 

3. What information is required.  Can you have a river cross section resource without a rating curve (I think the answer should be yes).  There are different levels of required for data and metadata and a decision is needed on each for this resource type.  These are
* For resource to exist
* For resource to be "sufficient to make public"
* For resource to be formally published
* Optional metadata that can be added but is not required
For each data or metadata item you need to decide which category it belongs to.  My suggestion in this case is
For resource to exist
* the type of the resource has to be indicated (river geometry cross section in this case)
* the resource has a permanent identifier (automatically assigned)
For resource to be "sufficient to make public" a suggestion may be
* Title
* Abstract
* Creator
* Keywords
* Cross section csv file
* transect vertices csv file
* …
Optional metadata/files that this resource may hold
* Rating curve csv file
* …
For resource to be formally published
* No additional requirements beyond generic resource publication requirements and sufficient to be made public.

**Comment by twhiteaker** [comment]
I reviewed Arc River, Arc Hydro, RiverML, and Hy_Features to see how the information in the XS resource relates to those information models. I discussed with Maidment how the resource structure fits the NFIE use case. Maidment desires a more geographic approach, storing geospatial coordinates of each station along the cross section. Whereas the initial XS resource is more tailored to modeling, specifically HEC-RAS, Maidment’s approach is more information-centric. Arc River handles the geometry for the new approach well, so I’ll adapt the XS resource to use this data model. Regarding granularity, I think it’s better to store a set of cross sections in a resource rather than make a separate resource for each cross section.

**Comment by twhiteaker** [comment]
# File Format - Shapefiles

Shapefiles would include CrossSectionLine and CrossSection2DPoint which must have their coordinate system defined. CrossSectionLine and CrossSection2DPoint are based on the definition from the Arc River GIS data model, but with fewer required attributes, and picking up the CSCode attribute from the Arc Hydro GIS data model (upon which Arc River is largely based).

**CrossSectionLine** is a line shapefile and represents the cut line for displaying cross section location in plan view and includes these required attributes:
* CSCode - Identifier for the cross section

**CrossSection2DPoint** is a point shapefile and represents a point along a cross section, i.e., a station with which an elevation value is associated. CrossSection2DPoint includes these required attributes:
* CSCode - Identifier for the cross section
* CrossM - Measure of the point along the cut line
* Elevation - Elevation of the point above some datum.

Example file: http://beta.hydroshare.org/resource/53b228ef0c9741a3b43c3932d718e59e/

Anyone know of a good way to populate CrossM? This kind of data is usually included in a cross section table, but I didn't see this information in the example data from Maidment. It could be populated in GIS, but I don't know of a very simple way to do it. You have to get into linear referencing, and while the steps aren't arduous, basic GIS users may not have been exposed to it before.  Workflows:
http://gis.stackexchange.com/questions/6476/finding-distance-of-point-along-polyline
http://mappingcenter.esri.com/index.cfm?fa=ask.answers&q=1943

**Comment by twhiteaker** [comment]
Need to figure out how to indicate vertical datum and units for Elevation. Maybe those will be required metadata elements for cross section resource.  

I left out some attributes like ReachCode which were included in the CSV version of the resource. My motivation was to keep things simpler. Users could include ReachCode if they have it. The Mississippi example data that I used did not.

**Comment by twhiteaker** [comment]
I read the WaterML ratings and gaugings spec. Aside from the stage-discharge tuples, it seems to me that these are the only required elements for the simplest case:
* vertical datum (Conversions/datums-for-stage requirement)
* start date of period of application (Conversions/start-periods requirement)
* link to a monitoring point (Conversions/keys requirement)

The inputProperty and outputProperty are also required, but it seems to me that we could hard-code these to stage and discharge. 

For the NFIE use case, stage-discharge tuples, which are called Conversions in WaterML, are going to be associated with a cross section but no monitoring point, and will be created by a model. Since they're tied to a cross section, I would include conversions as part of a HydroShare cross section resource. I would make vertical datum a custom required metadata item for the resource. I'm less comfortable requiring start date, because sometimes that hasn't been decided. But I'm game for requiring it for now since WaterML does. 

What I don't understand is how we can tie modeled cross sections to monitoring points when there is no monitoring point.

**Comment by twhiteaker** [comment]
As Dave V. pointed out to me, if we publish a profile of WaterML that relaxes the monitoring point constraint, then we can associate each rating with a cross section instead of a monitoring point.

**Comment by twhiteaker** [comment]
# Cross Section Resource Type
Here's my current thinking, using shapefile and an optional CSV file to implement. The resource includes up to three files.
* **Cross section points, i.e., stations (required)**
* **Cross section cut lines (required)**
* Stage-discharge conversions

Each file may include data for more than cross section. A CSCode attribute relates each feature or row in a table to a cross section.

# Resource metadata
* **Vertical units, e.g., feet - (required) applies to measurements like elevation and stage**
* **Vertical datum, e.g., NAVD88 - (required) applies to station elevations**
* **Start date of period of application - (required) when cross sections in this resource are valid**
* Horizontal units, e.g., feet - applies to measurements like river measure
* Discharge units, e.g., cfs - useful if rating curve is included. Required if conversion is included in resource

# Cross section points, i.e., stations

Extension: .zip
Contents must be point shapefile.
Projection must be defined.
Attributes:
* **CSCode (text) - (required) uniquely identifies cross section to which the point belongs**
* **Elevation (double) - (required) elevation of point**
* CrossM (double) - measure along the cross section, starting at zero from left side when looking in predominant downstream direction

# Cross section cut lines

Extension: .zip
Contents must be line shapefile.
Projection must be defined.
Attributes:
* **CSCode (text) - (required) uniquely identifies cross section**
* ProfileM (double) - measure along the river, starting at zero from most downstream point in river
* RiverCode (text) - code or name of river

# Stage-discharge conversions

This is the kind of information represented by a rating curve.

Extension: .csv
Columns:
* **CSCode - (required) identifies cross section to which conversion belongs**
* **Elevation - (required) elevation above datum**
* **Discharge - (required) flowrate**
* Stage - height above river bed
* Frequency - flood return period in years, e.g., 100

**Comment by vmmerwade** [comment]
I wonder if you need a field for cross-section points to indicate whether the elevations are actually measured or extracted from another resource (eg. DEM, TIN or topographic map). How about information on the accuracy of the elevations. Should this be part of metadata?

Do you also want to define the polyline type or point type for these features? is cross-section cut line always going to be polyline or can it be PolylineM or polylineMZ. 

I wonder if ProfileM is a better way to relate cutlines to cross section points. This is how it is done in HEC-RAS. It is easier to create ProfileM than to come up with new codes for cross-sections.

**Comment by twhiteaker** [comment]
I could see elevation source and accuracy as optional metadata elements. Horizontal and vertical accuracy are required if applicable according to CSDGM. I think the best CSDGM fit for elevation source is "Lineage." I suggest seeing if equivalent terms already exist for other HydroShare resource types, and then reusing them, and/or adding them for cross sections.

Do hydraulic models and typical GIS users know how to work with M and Z on GIS features? I think having M and Z explicitly in a table as CrossM and Elevation attributes is lower hanging fruit. It's true that in a purely GIS implementation, all you need is a cut line as PolylineZM and you can leave out the cross section points, but I'm suggesting we forgo that elegance in favor of interoperability, i.e., put everything in a (attribute) table.  So, HydroShare users may upload PolylineZM if they want, but I'm not suggesting HydroShare do anything with the Z and M values.

If all you have is ProfileM from HEC-RAS, then you can use those values as CSCode, so you're not really coming up with new codes. One of the example datasets I'm working with already had CSCodes. It also had measure values in the cut lines, but strangely the measure values didn't match up with the measure values in HEC-RAS, so I found CSCode to be more reliable in that case.

**Comment by twhiteaker** [comment]
Revised based on comments from vmmerwade.

# Cross Section Resource Type

Here's my current thinking, using shapefile and an optional CSV file to implement. The resource includes up to three files.
* **Cross section points, i.e., stations (required)**
* **Cross section cut lines (required)**
* Stage-discharge conversions

Each file may include data for more than cross section. A CSCode attribute relates each feature or row in a table to a cross section.

# Resource metadata

* **Start date of period of application - (required) when cross sections in this resource are valid**
* **Vertical units, e.g., feet - (required) applies to measurements like elevation and stage**
* **Vertical datum, e.g., NAVD88 - (required) applies to station elevations**
* Vertical accuracy
* Horizontal units, e.g., feet - applies to measurements like river measure
* Horizontal accuracy
* Discharge units, e.g., cfs - useful if rating curve is included. Required if conversion is included in resource
* Lineage - details about the source of the data, such as whether elevation values were measured or extracted from a DEM

# Cross section points, i.e., stations

Extension: .zip
Contents must be point shapefile.
Projection must be defined.
Attributes:
* **CSCode (text) - (required) uniquely identifies cross section to which the point belongs**
* **Elevation (double) - (required) elevation of point**
* CrossM (double) - measure along the cross section, starting at zero from left side when looking in predominant downstream direction

# Cross section cut lines

Extension: .zip
Contents must be line shapefile.
Projection must be defined.
Attributes:
* **CSCode (text) - (required) uniquely identifies cross section**
* ProfileM (double) - measure along the river, starting at zero from most downstream point in river
* RiverCode (text) - code or name of river

# Stage-discharge conversions

This is the kind of information represented by a rating curve.

Extension: .csv
Columns:
* **CSCode - (required) identifies cross section to which conversion belongs**
* **Elevation - (required) elevation above datum**
* **Discharge - (required) flowrate**
* Stage - height above river bed
* Frequency - flood return period in years, e.g., 100

**Comment by dtarb** [comment]
Here are some further things to think about.  

This resource will inherit metadata attributes from the generic resource that include temporal coverage start date and end date.  If you add start date of period of application to this you will need to work to make sure that users know the differences between all these dates.  I suspect that the start date of period of application concept is intended to apply to stage discharge conversions (ratings) that may be adjusted over time, and perhaps reflecting cross sections that may change over time.  If this is considered do you want to admit multiple stage discharge conversions (and corresponding cross section points and cut lines) with different periods of application (presumably enforced to be non overlapping).  I do not want to add complexity, but some consideration of these possibilities may be needed.  Also with multiple cross sections and stage discharge conversions in the same resource (which is the way I am reading this) will they all have the same period of application date.

The term lineage in resource metadata is a bit cryptic.  The Raster Resource Type has terms "Method" and "Comments" as extended (resource specific metadata) associated with each resource.  Consider that and see if there is a clear term to use.  There are actually multiple concepts involved here.  "source of the data", implies "source", i.e. where you got it. "measured or extracted from DEM" implies method.  It may be worth separating these along the lines of ODM or ODM2.

I am concerned whether ProfileM and RiverCode in Cross section cut lines is sufficient to precisely address the location of the cross section on a river reach.  A more specific form of reach addressing that gives the specific reach may be needed.  Perhaps this is implied by RiverCode, but it did not come across to me that way.  This does open the question as to how the river network that these cross sections attach to will be represented (presumably as a geographic feature resource type).  This seems to require geographic feature resources with unique identifiers for reaches that you can reference.

Will there be points from multiple cross sections in the same shapefile, separated by CSCode?  (Presumably yes).

Will there be multiple cross section cut lines in the same cut lines shapefile? (Presumably also yes). 

Will there be multiple stage-discharge conversions in the same csv file, separated by CSCode?  (Presumable also yes).

Also see #171.  Each resource type should have a web page to describe the resource type.  This would be a good place to put this description when you implement this.

**Comment by twhiteaker** [comment]
Start date of period of application concept is intended to apply to stage discharge conversions (ratings) that may be adjusted over time. I included it because I think WaterML Part 2 requires it. I think using the generic resource Start and End Date for this is fine. Yes, it will apply to the whole dataset. 

I reused the term "lineage" from CSDGM. I try to reuse before inventing. Since the raster resource already has Method, I'm fine with using Method instead and perhaps adding Source from Dublin Core.

I intended RiverCode intended to be the unique ID for a river feature. So with that, and the measure along the river, you can locate the cross section. I got RiverCode from Arc River. Arc River also has ReachCode, and after reading Arc River again, I think that is the better choice. So let's use ReachCode instead of RiverCode. Does that make the intent to use this as a unique river feature ID clear?

The answer to your last three questions is yes.

**Comment by dtarb** [comment]
I like "ReachCode".  Date semantics are a bit more troublesome.  "Start date of period of application" and temporal coverage "Start Date" do not immediately mean the same thing to me, suggesting that we likely need additional words explaining things which may take away from rather than add to clarity so a bit more thought is needed here, I think.

**Comment by twhiteaker** [comment]
@valentinedwv can start date of period of application be left out of a valid ratings and gaugings response? The only reason I'm requiring it or even including it for this resource type is because it's my understanding that ratings and gaugings requires it, and we're trying to support ratings and gaugings. 

If it's not required, I'm inclined to leave it out of the resource level metadata. It should really apply at the individual conversion level anyway.

**Comment by valentinedwv** [comment]
Go ahead and leave it out.
Really creating a model results profile/extension

**Comment by dtarb** [comment]
Also, being curious about CSDGM and lineage I looked it up and see that Lineage has two elements, Source_information and Process_Step, that seem to correspond to source and method.  I agree about avoiding inventing terms so use your judgment as to what is best here.

**Comment by twhiteaker** [comment]
Xing Zheng, Maidment's masters student, independently created a data model for river geometry in GIS for his work in NFIE. I uploaded it as a HydroShare resource. It's similar to the design in this GitHub issue, but with some differences arising from specific use of NHD in NFIE and attribute names desired by David Maidment. http://beta.hydroshare.org/resource/15b72b4a857c425497c8de54382a608b

**Comment by twhiteaker** [comment]
# Cross Section Resource Type

Here's my current thinking, using shapefile and an optional CSV file to implement. I changed the resource level metadata Lineage to Source and Method. I added a flowline feature class, since cross section river measures are arbitrary without the spatial domain onto which those measures have meaning.  This means we can't simply parse the resource files by geometry type, since now we'll have two line feature classes: flowlines and cut lines.  I'm also unsure about flowline attributes.

The resource includes up to four files.
* **Flowlines, i.e., rivers on which cross sections are referenced (required)**
* **Cross section cut lines (required)**
* **Cross section points, i.e., stations (required)**
* Stage-discharge conversions

Each file may include data for more than cross section. A CSCode attribute relates each feature or row in a table to a cross section.

# Resource metadata

* **Vertical units, e.g., feet - (required) applies to measurements like elevation and stage**
* **Vertical datum, e.g., NAVD88 - (required) applies to station elevations**
* Vertical accuracy
* Horizontal units, e.g., feet - applies to measurements like river measure
* Horizontal accuracy
* Discharge units, e.g., cfs - useful if rating curve is included. Required if conversion is included in resource
* Source - where you got the data, maps to CSDGM Source_Information
* Method - how data were derived, such as whether elevation values were measured or extracted from a DEM; maps to CSDGM Process_Step

# Rivers, e.g., NHD Flowlines

These are polylines representing rivers. These are needed to provide the domain upon which the measure attribute of a cross section line is based.

Extension: .zip
Contents must be polyline shapefile or geodatabase feature class.
Projection must be defined.
Attributes:
* **ReachCode (text) - (required) Identifier for the river reach containing this feature, pertinent to measure values.** 
* FromNode and ToNode? Or next down ID?
* FromMeas and ToMeas? Or store measure values as PolylineM?
* COMID? NHD assigns COMID as unique ID to features. But measure values are with respect to reaches, which maps to ReachCode. There could be several features per reach. Are we going to carry 

two identifies, one for the feature and one for the measure system?

# Cross section cut lines

There can be multiple cross section cut lines in the same shapefile, distinguished by CSCode.

Extension: .zip
Contents must be line shapefile or geodatabase feature class.
Projection must be defined.
Attributes:
* **CSCode (text) - (required) uniquely identifies cross section**
* ProfileM (double) - measure along the river, starting at zero from most downstream point in river
* ReachCode (text) - code or name of river
* NextCS (text) - CSCode of next downstream cross section
* LengthDsCS (double) - Length along river to next downtream cross section
* SlopeDsCS (double) - Slope along river to next downstream cross section

# Cross section points, i.e., stations

There can be points from multiple cross sections in the same shapefile, grouped by CSCode.

Extension: .zip
Contents must be point shapefile or geodatabase feature class.
Projection must be defined.
Attributes:
* **CSCode (text) - (required) uniquely identifies cross section to which the point belongs**
* **Elevation (double) - (required) elevation of point**
* CrossM (double) - measure along the cross section, starting at zero from left side when looking in predominant downstream direction
* Position (text) - Left Bank | Right Bank | Centerline | (blank)

# Stage-discharge conversions

This is the kind of information represented by a rating curve.

There can be multiple stage-discharge conversions in the same CSV file, grouped by CSCode.

Extension: .csv
Columns:
* **CSCode - (required) identifies cross section to which conversion belongs**
* **Elevation - (required) elevation above datum**
* **Discharge - (required) flowrate**
* Stage - height above river bed
* Frequency - flood return period in years, e.g., 100

**Comment by hyi** [comment]
@dtarb Reassign to you for re-delegate this issue.

**Comment by dtarb** [comment]
Closing.  Current plans are not to implement a specific River Geometry Resource type.  River hydraulic properties will be represented by adding a hydraulic properties table to a river network as a geographic feature.  River geometry beyond this will be accommodated as files that are part of a generic resource and/or specific model files such as HEC-RAS cross sections as part of a Model Instance Resource containing HEC-RAS files.
