### ISSUE TITLE
Empty Bag

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1218]
If I download all content as a zipped file for the following resource I get an empty zip file.

https://www.hydroshare.org/resource/27a7553d7b9f4d08a8d055c258cf6efa/

**Comment by hyi** [comment]
@dtarb It is fixed. You should be able to download the bag now. What I did is to set bag_modified to true so that the bag can be regenerated since the existing bag zip file is empty with 0 byte in size. I did not know how this happened in the first place, but this specific issue is resolved. I suggest to close this issue for now if bag download for this resource works now.

**Comment by dtarb** [comment]
OK. Closing for now.  We need to be vigilant as to why this happened and whether there is a systemic problem to address.
