### ISSUE TITLE
Groups:  Issues with Phase 1 Implementation

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#1233]
I'm creating this issue to document problems with phase 1 of the Groups implementation:

 - [x] Table listing resources shared with a group does not spread the full width of the page using Firefox on Windows
![image](https://cloud.githubusercontent.com/assets/3485902/15625269/7764f0ce-245d-11e6-90b0-64c8d684e33d.png)

 - [x] Clicking on a member's name in the members part of the group page does not go anywhere. It seems like it should go to the users profile page.

 - [x] Testing in Chrome on Mac - When I make my window narrow, the group photo crowds the text until you make the window narrow enough that they go to the vertical orientation.
![image](https://cloud.githubusercontent.com/assets/3485902/15625266/6d792df0-245d-11e6-8c27-e6b22905780e.png)

 - [x] There's some spacing issues with the icons in the shared resources table. Testing with Chrome on a Mac. Clearing my cache brought both the private and shareable icons under the main resource type icon.  Did you intend for them to be below the resource type icon, or to the right as on the My Resource page?
![image](https://cloud.githubusercontent.com/assets/3485902/15625263/6563bcc0-245d-11e6-8136-d0676f58ffa7.png)

 - [x] In the manage access panel, when I'm sharing one of my resources with a group, the group shows up without its photo, even though I have added a photo to the group.
![image](https://cloud.githubusercontent.com/assets/3485902/15625260/5bb9bbca-245d-11e6-8ee4-036eff232697.png)

 - [x]  Standardize spacing for the group tiles on the Find Groups page. Right now there's a bunch of empty space if the descriptions of the groups on one line are different lengths.
![image](https://cloud.githubusercontent.com/assets/3485902/15625259/51c7fbf4-245d-11e6-8978-6205b28e17b7.png)

 - [x] The Edit group description form (when a user chooses to edit the group's details) should be titled "Edit Group Details" instead of "Create New Group"

**Comment by mauriel133** [comment]
@horsburgh, please verify if the issues checked above have been resolved as they appear at https://testservices.hydroshare.org/

Note: still working on #6

**Comment by pkdash** [comment]
The 'purpose' field has been implemented as ```TextField``` which allows large amount of text.

**Comment by ChristinaB** [comment]
Hi Jeff/All,
I made a new group called Landlab Test Group.

I tried to invite someone, and when i put in the email, and clicked on invite, nothing happened.   I should be able to find Jeff or someone who is not currently a HydroShare user. Right?

I created a new resource, but it took too long to figure out how to share the resource with the group. Either I need a spend time asking someone how to do it, or it's not obvious, but working with the impatient busy user timeframe of 30-60 sec, I suggest it needs to be more obvious.   I think the Collaborate page could use a 'Share my Resources' button that takes me back to the start of the workflow.  This may be redundent, since I could use the dashboard, but if you keep the lock as the workflow to sharing, you may need a more obvious pathway via the Collaborate page. 

Eventually I searched through each of the icons from my resource page and found the lock, which led to the Groups radio button.  I think the lock for user access control is not as intuitive. I expected to share with the group with the arrow escaping the box icon (which is publish HydroShare, but is typically used to share). I suggest this be reconsidered.  

Nice job!!!   
Groups are great.
Christina

**Comment by gantian127** [comment]
@pkdash The field actually now only allows user to enter a limited number of words. If the "purpose" field is expected to accept unlimited words, it may be better to fix the problem. Otherwise, it may be better to inform the user that the field requires a limited number of words. Thanks

**Comment by horsburgh** [comment]
@ChristinaB - I'm going to create separate issues for the following:

1. Issuing invites to join a HydroShare group to someone that is not a HydroShare user
2. Make it easier to share resources with a group via the collaborate page
3. Consider changing the icon for "manage access" to something more intuitive

**Comment by ChristinaB** [comment]
I uploaded a picture and it looked OK at first, but now it is displaying as below.  I don't know the design details on fussing with this kind of thing. Maybe tell the user what the picture size should be or just auto fix it?
![image](https://cloud.githubusercontent.com/assets/4108369/15794729/0930951e-29a2-11e6-86b9-e044fbe07c04.png)

**Comment by pkdash** [comment]
@horsburgh Should this be closed?

**Comment by horsburgh** [comment]
This issue is old and a bit stale. It got hijacked with a number of related issues. I verified as much as I could has been fixed, so any remaining issues should be added as new issues - if they haven't been already. Closing.
