### ISSUE TITLE
HydroShare GIS App unable to display new raster resource

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1264]
I created the following raster resource https://www.hydroshare.org/resource/b2595adde0fd46cc969b8e86117018e5/.  The HydroShare GIS app appears unable to display it.  Loading wheel has spun for 30+ minutes.  It is only 73 MB so should be well within capability.  It is unclear whether the problem is related to the fact that this is a new resource and the app may be pointing to an old irods collection, or it is in geographic coordinates.

**Comment by shawncrawley** [comment]
@dtarb I finally was able to figure out what was going on. You can see it working now on appsdev:
https://appsdev.hydroshare.org/apps/hydroshare-gis/?res_id=b2595adde0fd46cc969b8e86117018e5

The problem was that it appeared that this particular resource had both incomplete and unknown coordinate system info with regard to what GeoServer recognizes/requires. This was brought to my attention through a post I made to the GeoServer community. I'll spell out what was going on, though you can view the thread yourself here:
https://sourceforge.net/p/geoserver/mailman/message/35190761/

In the case of the resource in question, it appears at face value that the coordinate system info is valid, yet both GeoServer and this prj2epsg API I found (http://prj2epsg.org/apidocs.html) rejected it as is. Running gdalinfo on the file showed this as the coordinate system wkt:

GEOGCS["GCS_North_American_1983",
     DATUM["D_North_American_1983",
         SPHEROID["GRS_1980",6378137.0,298.257222101]],
     PRIMEM["Greenwich",0.0],
     UNIT["Degree",0.0174532925199433],
     VERTCS["Unknown VCS",
         VDATUM["Unknown"],
         PARAMETER["Vertical_Shift",0.0],
         PARAMETER["Direction",1.0],
         UNIT["Meter",1.0]]]

But sending that to the prj2epsg API like so...
http://prj2epsg.org/search.json?mode=wkt&terms=GEOGCS[%22GCS_North_American_1983%22,%20DATUM[%22D_North_American_1983%22,%20SPHEROID[%22GRS_1980%22,6378137.0,298.257222101]],%20PRIMEM[%22Greenwich%22,0.0],%20UNIT[%22Degree%22,0.0174532925199433],%20VERTCS[%22UnknownVCS%22,%20VDATUM[%22Unknown%22],%20PARAMETER[%22Vertical_Shift%22,0.0],%20PARAMETER[%22Direction%22,1.0],%20UNIT[%22Meter%22,1.0]]]

Yielded the following error:
"Invalid WKT syntax: Error in \"GEOGCS\": Parameter \"VERTCS\" was not expected."

After removing the "unexpected" paramter, VERTCS, and issuing a subsequent request like so...
http://prj2epsg.org/search.json?mode=wkt&terms=GEOGCS[%22GCS_North_American_1983%22,%20DATUM[%22D_North_American_1983%22,%20SPHEROID[%22GRS_1980%22,6378137.0,298.257222101]],%20PRIMEM[%22Greenwich%22,0.0],%20UNIT[%22Degree%22,0.0174532925199433]]

It yields a successful match:
{"name":"GCS_North_American_1983","code":"4269","url":"http://prj2epsg.org/epsg/4269.html"}

The fact that this file's coordinate system seemed to match EPSG:4269 is what was brought to my attention through the GeoServer community mailing list. Thus, I ran "gdal_translate -a_srs EPSG:4269 Onion.tif Onion_mod.tif" to produce a modified .tif file (Onion_mod.tif), which was then successfully uploaded to GeoServer.

Since this could happen again in the future, I added a script to HydroShare GIS that will do the following for every resource before attempting to add it to geoserver:
1. Extract the coordinate system info using the 'gdalinfo' shell command
2. Sending this raw info (the wkt projection string) in a request to the prj2epsg API to check its validity
3. If the raw info matches an EPSG code, nothing is done and an attempt is made to upload the resource to GeoServer
4. If the raw wkt yields an error (e.g. an unrecognized parameter in the wkt), then the raw wkt is modified (e.g. the unrecognized parameter is removed) and then a new request is made with the modified wkt
5. This is done until the request succeeds in matching an EPSG code, or fails indefinitely
6. In this case that the initial request failed, but a modified request yielded a valid EPSG code, this EPSG code is then used with gdal_translate to rectify file (i.e. "gdal_translate -a_srs EPSG:4269")
7. This modified resource file is then uploaded to GeoServer

As said, this check is successful in the case of the resource in question, and the resource is now successfully added to GeoServer and viewed in HydroShare GIS. However, I am wondering if it would be more efficient for this sort of check to happen on the HydroShare side when validating a file before resource creation. What do you think? What about you, @gantian127?

**Comment by gantian127** [comment]
@shawncrawley @dtarb  I found out that VDATUM refers to vertical datum and VERTCS refers to vertical coordinate system. It seems these tags are valid in the coordinate system wkt string but are not recognized in geoserver. So I suggest either find a version of geoserver to recognize these elements (not sure if there is one ) or have a way to show the detailed error info to the users to let them know why their data can't be visualized in GIS APP.

There will be other raster resources that can't be correctly visualized in this app for different reasons. To modify the original raster datasets to fix different issues may not be the best way to solve the problem. (e.g. If ArcGIS can't visualize some data, it will just show error info rather modify the data files). Sometimes the data uploader should be responsible to make their data valid for visualization in the APP. The app can let them know the reason why the data can't be visualized.

**Comment by dtarb** [comment]
Unless we are very sure that the dataset is somehow deficient and that the change we make to its projection through the gdal_translate mentioned by @shawncrawley is 100% correct we should not be changing the users file.  (I do not think we understand these issues well enough to be sure).  Also showing this sort of error to users and saying their data can't be visualized is not acceptable in this case, as this is a file that was created using ArcGIS, GDAL or R (these are the tools I use, I do not recall exactly the sequence of merging and clipping that produced this file) and does visualize in ArcGIS.  These are mainstream so we should be able to display it without user intervention.  It will be quite common for raster data not to have a vertical coordinate system/datum.  The only time we should report an error to a user is if the file is really broken, and by this I mean not displayable in other mainstream systems.

**Comment by shawncrawley** [comment]
This issue should be resolved. Let me know if otherwise.

**Comment by danames** [comment]
I'd like to test the original resource to verify this fix but unfortunately
it seems the resources is gone or broken or not public (403 Forbidden
error). Dave can you please post it again? - Dan

**Comment by dtarb** [comment]
@danames @shawncrawley I have now given you access to this resource https://www.hydroshare.org/resource/b2595adde0fd46cc969b8e86117018e5/.  It displays correctly for me, so if it does for you, then close the issue.

**Comment by danames** [comment]
Confirmed fixed.
