### ISSUE TITLE
GIS App issues

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1269]
Based on testing of the GIS app following are outstanding issues

- [x] Unable to modify symbology
- [x] When a raster resource is opened it does not automatically zoom to (resulting in a big white screen with impression of no data)
- [x] Loading an exsiting map saved (as a generic resource) seems to result in an indefinitely spinning loading symbol.

**Comment by shawncrawley** [comment]
@dtarb Unfortunately there are a few things that do not behave the same on appsdev as they do on apps. In those cases, I have to do a bit more "testing" on apps, rather than on appsdev. It looks like you just happened to be using the app at the exact same time as I was doing a bit of testing on apps. It should all be resolved now.

**Comment by dtarb** [comment]
Thanks.  It is working now.
