### ISSUE TITLE
Group Creator/Contributor Functionality

### ISSUE THREAD

**Issue by AmberSJones** [hydroshare/hydroshare#1310]
We need the functionality to enable Hydroshare groups to be creators or contributors of resources (but not owners- ownership should be retained by an individual).

**Comment by pkdash** [comment]
@horsburgh Here are my assumptions related to making a group as creator/contributor:

- The science metadata document needs to list all members of that group as creators/contributors. Also anytime group membership changes we have to update the xml document.

- If group 'A' is made creator of a resource then group 'A' can't be made contributor of that same resource.

- There is no need to check for group's access permission on a resource before a group can be made creator/contributor.

- The user who makes a group as creator/contributor must have access to that group.

**Comment by horsburgh** [comment]
@pkdash - I think it's even more simple:

* False - Groups should be treated exactly the same as people when it comes to being a Creator or Contributor.  A "Group" may be a HydroShare group, or potentially a group outside of HydroShare. The Science Metadata document need only list the group name as the creator or contributor and the group URL if the group is an actual HydroShare group or if an external group has a URL. You should not copy the names of individuals within the group into the metadata.  

**NOTE**:  Since a group name is not like a person's name, you will not want to shorten or reorder the group name in the citation.

* True - A group should not be both a creator and a contributor.

* True - I can assert that a person is a creator or contributor of a resource, even if that person is not a HydroShare user.  The same should be true of groups.

* False - This makes logical sense, but fails for the case where a group may be external to HydroShare (there would be no way to check to see if the user was a member of the group).

**Comment by hyi** [comment]
I believe this is covered by issue https://github.com/hydroshare/hydroshare/issues/1360. @pkdash I'll leave it to you whether you want to consolidate them into one or leave them open and linked as reference.

**Comment by pkdash** [comment]
@AmberSJones I think this has been addressed. Can you check?

**Comment by AmberSJones** [comment]
Currently, there is functionality to add an Organization as an author. I have been using this- it's great. The original issue states that a HydroShare group should be able to be added as an author. I don't think this is implemented.

**Comment by danames** [comment]
We can use organizations instead of groups. So, given limited funding and time. I'm closing this. Let's reopen for HydroShare  2.0.
