### ISSUE TITLE
Large file download - files greater than 1 GB

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#1311]
Once release 1.7.2 goes into production, the 1 GB upload/download enforcement will be in place.
Reference in [django_irods](https://github.com/hydroshare/django_irods/blob/7af184bb7f26425a457a23a1c0c42df0ae843e2b/views.py#L105)

With the advent of collections, and just big files in general, we need to be able to enable large file download via more than just iRODS clients... 

For example, how are large public files held in hydroshareZone supposed to be accessed? 
- Doable by copying the resource to user iRODS space in hydroshareuserZone, but this feels wasteful.
- Presently iRODS doesn't enforce the concept of public / private / shareable / etc. as this logic is on the Django/hs_access side of the fence, so there isn't an easy read-only iRODS account answer to this without doing some rule/microservice customization work.

Consulting @jbradberry for some advice on enabling large file download, in particular using asynchronous methods that don't lock up a worker process if the job is very long lived.

**Comment by hyi** [comment]
@mjstealey @jbradberry I am putting this issue on my plate for now, but feel like since we have issue https://github.com/hydroshare/hydroshare/issues/1343 created (which I will work on when I have time) to delegate large file download to a celery task, there is no additional work needed to tackle this at least for the short term. Delegating to iRODS client for large file downloading is enabled by allowing users to replicate the resource bag they have access to their irods user space (access control is enabled there since  that replicate resource bag button will not be displayed/enabled if a user does not have access control to that resource), then use iRODS client to download large resources from their irods user space. @mjstealey @jbradberry Let me know if there are additional issues to be addressed for this. Otherwise, can we close this issue but only leave the issue https://github.com/hydroshare/hydroshare/issues/1343 to be addressed to tackle large file download issue?

**Comment by jbradberry** [comment]
@hyi I had some ideas that I haven't really been able to follow up on recently, that would result in something like bittorrent in the browser.

**Comment by hyi** [comment]
@jbradberry Can you elaborate a bit on your ideas? I have not heard anything about bittorrent, and currently we just delegate download and upload of files larger than 1GB to iRODS clients (which are not web-based).

**Comment by hyi** [comment]
@mjstealey Not sure what is left to do regarding this large file download issue now that we have async bag creation and download in place. Could you evaluate whether there is more to be done regarding this issue, and if not, close this issue after verifying async bag creation and download works as expected without blocking web worker process?

**Comment by mjstealey** [comment]
Deferring to iRODS for large file (> 1GB) download. 
May resurface as a new issue if a better solution is proposed in addition to iRODS.
