### ISSUE TITLE
HydroShare GIS unable to display certain raster resources

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1335]
Shale CZO LIDAR DEM. https://www.hydroshare.org/resource/211fae34ae7b4d51a9b441fcdd1405ac/.   It has the following problems displaying in HydroShare apps

- HydroShare GIS.  Just does not load.
- Raster viewer.  Is displayed at a location in the middle of Lake Ontario.

This raster displays correctly when loaded into ArcGIS.

Shaver Creek DEM.  https://www.hydroshare.org/resource/af6d865598fd41a6942bc3c5798a2090/.  

- HydroShare GIS.  This reports an unexpected error occurs.
- Raster Viewer.  This reports an invalid tiff file or tiff file without projection information.
- This raster also fails to get a spatial coverage box in HydroShare.  I had to estimate one to make it public.

This raster displays correctly when loaded into ArcGIS.

**Comment by gantian127** [comment]
The reason that the spatial coverage box is not created is because the wkt info from the Shaver Creek DEM file is esri wkt. This esri wkt can't be recognized by the Proj4 library for projection transformation. The solution is to first convert the esri wkt to ogc wkt and then do the transformation.

**Comment by shawncrawley** [comment]
@dtarb This issue should be resolved. Let me know if you find otherwise.

**Comment by shawncrawley** [comment]
@dtarb Actually, my claim to issue resolution was a bit premature. I did not realize that the Shale Hills Lidar is displayed at a location in the middle of Lake Ontario, just like the Raster Viewer is doing. I'll look into this aspect of the issue.

**Comment by shawncrawley** [comment]
@dtarb The issue with Shale Hills Lidar is that the EPSG code is not recognized by GeoServer. The reason it doesn't fail load completely is because it does not lack an EPSG code. I'm currently looking into how to fix this. The suggested reference made in the past by @gantian127 (http://geoserver.geo-solutions.it/edu/en/adv_gsconfig/crs_handling.html) seemed like the best option, but I cannot get it to work as hoped. I opened up an issue to the GeoServer forum weeks ago (https://sourceforge.net/p/geoserver/mailman/message/35267363/) to try to get more help. I still haven't heard back. 

I'll try a few more things in the meantime. If worst comes to worst, I can just manually assign the correct EPSG code using the GeoServer GUI. This isn't as ideal as having it more automated, but hopefully these issues are few and far in between.

**Comment by danames** [comment]
If a file doesn't have a needed projection code to display it properly in
HydroShare GIS, the best thing to do would be to have the HS GIS GUI ask
for a projection. code. If the user doesn't provide one then we can't
display the data.

The real question is...once we have received the code through the GUI, how
can we make it a permanent part of the resource. I don't think we can do
that for published resources but for unpublished resources maybe we can add
the projection code to the resource.

**Comment by dtarb** [comment]
This is a gnarly problem.  The root cause seems to be geoserver not recognizing the spatial reference information that is there, whereas ArcGIS does (not sure what QGIS or Mapwindow GIS does, but if either of those get it write looking at the code that they use may help us).

One thing to check is that the problem is not due to the VRT wrapping that HS has done.  See of geoserver will properly display just the geotiff file, not the vrt file that points to the geotiff file.  If geoserver does display the geotiff file correctly, then we need to re-evaluate the VRT approach.

@danames if you take a look at the details of the Shale Lidar DEM geographic raster resource mentioned above, it does appear to have spatial reference information, so I do not think asking the user to provide spatial reference information is the right answer in this case, and as a user I would not know what information to provide that is better or different than the spatial reference information that came with the Geotiff file.  Gdalinfo on the tiff file if you download it results in:

Driver: GTiff/GeoTIFF
Files: lidarDem.tif
Size is 3125, 3125
Coordinate System is:
PROJCS["NAD_1983_StatePlane_Pennsylvania_South_FIPS_3702_Feet",
    GEOGCS["NAD83",
        DATUM["North_American_Datum_1983",
            SPHEROID["GRS 1980",6378137,298.2572221010002,
                AUTHORITY["EPSG","7019"]],
            AUTHORITY["EPSG","6269"]],
        PRIMEM["Greenwich",0],
        UNIT["degree",0.0174532925199433],
        AUTHORITY["EPSG","4269"]],
    PROJECTION["Lambert_Conformal_Conic_2SP"],
    PARAMETER["standard_parallel_1",39.93333333333333],
    PARAMETER["standard_parallel_2",40.96666666666667],
    PARAMETER["latitude_of_origin",39.33333333333334],
    PARAMETER["central_meridian",-77.75],
    PARAMETER["false_easting",1968500],
    PARAMETER["false_northing",0],
    UNIT["US survey foot",0.3048006096012192,
        AUTHORITY["EPSG","9003"]]]
Origin = (1920000.000000000000000,490000.000000000000000)
Pixel Size = (3.200000000000000,-3.200000000000000)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  ( 1920000.000,  490000.000) ( 77d55'29.50"W, 40d40'41.81"N)
Lower Left  ( 1920000.000,  480000.000) ( 77d55'29.25"W, 40d39' 2.99"N)
Upper Right ( 1930000.000,  490000.000) ( 77d53'19.71"W, 40d40'41.98"N)
Lower Right ( 1930000.000,  480000.000) ( 77d53'19.50"W, 40d39' 3.17"N)
Center      ( 1925000.000,  485000.000) ( 77d54'24.49"W, 40d39'52.49"N)
Band 1 Block=128x128 Type=Float32, ColorInterp=Gray
  NoData Value=-3.4028229999999999e+038

@gantian127 made some changes that got merged and deployed in www (I think with deploy 1.7.4).  She could clarify the details of the changes, but the current resource landing page displays coverage in the correct location and gives spatial reference information as part of Resource specific metadata.  However, HydroShare GIS puts this resource in the middle of Lake Ontario, so is not interpreting this information the same way as @gantian127 s code which mostly uses GDAL.  I suggest discussing with @gantian127 and taking a look at the code changes she did, in case they help (you may have done this already).   

While I do not think it is the problem for this resource, I do think that we do need functionality for a user to add missing spatial reference information or to correct incorrect spatial reference information.  Functionality for a user with edit or higher permissions on a resource should be established for them to add or correct incorrect spatial reference information. Ideally this should be an edit option on the resource landing page.  It could also be done by HS GIS as an attempt to display this in HS GIS is a likely place a user will first find out the spatial reference information is missing.  I would prefer that edits or additions to the spatial reference be written back to the geotiff file, to avoid having inconsistencies between the metadata that HS holds, and the metadata in the file (the database principle of storing the information in one place only).

**Comment by danames** [comment]
OK so there is definitely a problem with Geoserver not extracting this info
correctly. Shawn, let's discuss early this week.

**Comment by shawncrawley** [comment]
So this issue has actually been resolved. The EPSG code that gdalinfo identifies for the tif file is 9003. That code is not part of GeoServer's standard codes. However, I found about three other codes that declare an essentially identical wkt projection info: 102729, 2272, and 6874.

http://www.spatialreference.org/ref/esri/nad-1983-stateplane-pennsylvania-south-fips-3702-feet/html/
http://spatialreference.org/ref/epsg/2272/html/
http://www.spatialreference.org/ref/sr-org/nad_1983_stateplane_pennsylvania_south_fips_3702_feet/html/

Of these codes, one and only one is actually one of the standard GeoServer codes. Long story short, I programmed the app to identify the EPSG code that GeoServer does store and then "reproject" the file to this code. It is a little clunky since a gdal_transform (reprojection) does have to take place. But if the different EPSG code really is essentially identical, then the data should not actually be changing, just the CRS projection wkt string.

There could come in the near future another case in which this work-around is insufficient. But for now, as we are taking things case by case, the problem is solved.

**Comment by dtarb** [comment]
Thanks for hounding this down.  I'll close then as I verified that it does display in what at least visually is near to the right place.

I wonder of a define projection rather than reproject would be better.  Reproject can be expensive for large datasets.  Define projection essentially changes the projection metadata rather than changing the data.  See http://gis.stackexchange.com/questions/146322/gdal-translate-or-gdalwarp-to-define-projection.  

I also wonder if there is an option to have the projection used for display based on WKT rather than EPSG code.  If you see such a thing in Geoserver consider it.
