### ISSUE TITLE
Allow formatting in group description field

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1350]
The description of a group should allow line endings and text indenting to permit basic formatting.  Better yet, allow rich text.  See https://www.hydroshare.org/group/9 for where this is needed.

**Comment by hyi** [comment]
@mauriel133 I am reassigning this issue to you since although I found a way to fix it, but think you are at a better position to apply the fix just to make sure it does not cause regression issues to other relevant pages/tables. Here is what I found how to resolve this issue. First, due to this code snippet https://github.com/hydroshare/hydroshare/blob/develop/theme/static/js/hs_resource_table.js#L46...L51, the enter key in the "About the group" textarea input is ignored. We need to enable the enter key in the "About the group" textarea input so that the user can enter multiple paragraphs separated by ```enter```/linefeed. Then change this line https://github.com/hydroshare/hydroshare/blob/develop/hs_core/templates/pages/collaborate.html#L48 to use ```linebreaks``` filter like ```{{ group.gaccess.description|linebreaks}}``` to honor the line breaks when displaying group descriptions. This should at least allow users to enter multiple paragraphs in group description field.

**Comment by mauriel133** [comment]
@dtarb I have added basic text formatting to these inputs. 

@hyi, any ideas how we can support rich text formatting as well?

**Comment by hyi** [comment]
@mauriel133 supporting rich text formatting needs more work, which probably needs to bring in additional package such as https://github.com/aljosa/django-tinymce. Mezzanine supports tinymce and already has tinymce integrated into admin interface  and its page editing, and I remember I got Mezzanine's tinymce-based rich text editing box in for abstract field editing a long time ago, but it requires staff/admin privilege to be able to use the out-of-box rich text editing from Mezzanine which is not what we want. I remember I spent some time investigating and the conclusion was that there was no easy workaround to leverage Mezzanine's rich text editing feature. I am looping in @jbradberry in case he has some suggestions/ideas. I suggest if there is no easy way to add rich text editing in, these basic text formatting should suffice for now. @dtarb can chime in on necessity of rich text formatting in this case, which I think is a really-nice-to-have feature, but not a must-to-have.

**Comment by mauriel133** [comment]
I see. I have created a PR with the basic formatting which should fix the current problem. In the future we can look into implementing rich text formatting as an improvement.

**Comment by hyi** [comment]
@mauriel133 Agreed.

**Comment by jbradberry** [comment]
@hyi It should be quite possible to reuse Mezzanine's rich-text editing without privilege limitations.  Generally such constraints are in the view logic, and a quick look at the model field and form widget classes seem to confirm.

https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/core/fields.py#L40
https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/core/forms.py#L40

**Comment by pkdash** [comment]
@dtarb Should this be closed?

**Comment by dtarb** [comment]
Good enough.
