### ISSUE TITLE
"http" or "https" in the url of "How to cite"?

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#1374]
A random question raised from one of our students who just started learning to use HydroShare.
Why the landing page url in browser address bar shows http**_s_**://www.hydroshare.org/resource/97add6638f7841278c73519e7192b252/, 
while in "How to cite" the url starts with "http" instead of "https"
![image](https://cloud.githubusercontent.com/assets/10070599/17336759/d59cf1e6-589c-11e6-8af5-2c739b9ad6af.png)

I am not sure this is a issue as I tried clicking that url link in "How to cite" and the correct landing page shows up with "https" in the browser address bar.

**Comment by hyi** [comment]
@zhiyuli @mjstealey @pkdash @jbradberry @dtarb The citation url protocol is retrieved here: https://github.com/hydroshare/hydroshare/blob/develop/hs_core/hydroshare/utils.py#L475. Since we don't set MY_SITE_PROTOCOL variable in our settings, the default http is used. Our hydroshare website is set up to redirect http automatically to https (@mjstealey can confirm if needed), so both http and https urls will resolve to the right page. If we set MY_SITE_PROTOCOL variable is settings.py to https, the new resources being generated will use https in the resource citation, but the old resources have to be migrated/updated to https in their Identifier metadata element if we want to go that route. I am not sure whether we need to spend time and effort for this, though, given that http can automatically resolve to https, but it is probably a question for @dtarb to decide.

**Comment by jbradberry** [comment]
Is the full citation url being rendered and then stored?  We ought to be relying on the MY_SITE_PROTOCOL setting instead in the citation card shown above.

**Comment by hyi** [comment]
@jbradberry Agreed we should be relying on the MY_SITE_PROTOCOL setting instead. The code does so with a fallback default to ```http```, so we should add MY_SITE_PROTOCOL in production environment to set it to ```https``` which can then be picked up by code to form an url identifier for new resources being created. Yes, the resource url is stored in Identifier metadata element for each resource although the whole citation is dynamically generated by assembling the metadata elements together. I believe to address this, we need to do the following two things:
1. add ```MY_SITE_PROTOCOL = 'https'``` into local_settings.py
2. do data migration to migrate database so that all Identifier elements for all existing resources have https site protocol rather than http.

**Comment by dtarb** [comment]
Since @hyi asked, I do not think that much time and effort should be spent on this.  This ambiguity is all over the internet.  We are sometimes advertising the site as www.hydroshare.org which does not say which of http or https is valid.  As long as any references with http get redirected to https then I am OK with things as they are.  That said, we should be following industry website development best practices and gradually transition to them where we deviate.

**Comment by hyi** [comment]
@dtarb Agreed. I added Backburner label to this issue without assigning anyone with no milestone at this point as I don't think anyone would have time to devote effort on this by end of next June given that http gets redirected to https anyway.

**Comment by mjstealey** [comment]
auto redirect to https should handle both cases
