### ISSUE TITLE
Collections mapping and viewing resource relationships

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#1387]
When viewing a resource that is in a collection, it would be helpful to know the relationships. Is this part of a collection? How many collections is a part of?

**Comment by zhiyuli** [comment]
@horsburgh @ChristinaB @pkdash  
The relationships between collections and resources are stored in django db. Bi-directional look-up can be performed: "collections -> resources" and "resources --> collections"
  
However, users can only see one-directional relationship in the resourcemap.xml file of Collection bags that can answer: which resources are collected by this specific collection?

An "ideal approach" would be having this relationship stored in the resourcemap.xml of each resource bag as well, so that user can see "is this resource part of any collection?". But this may cause the performance and permission issues we discussed before: auto-changing the bags of contained resources when collection changes.

I would suggest a simplified approach trying to meet the requirements from @ChristinaB :
Hong has implemented the "versioning" feature, in which the resource landing page can inform users if  an older/newer version of this resource exisits.
![image](https://cloud.githubusercontent.com/assets/10070599/17599188/15eac71c-5fbb-11e6-891e-7fc90359c4d5.png)

We could do similar thing: if the resource is part of any collection, we could display something like "This resource is collected by XXX" on the landing page, where "XXX" is a link to that collection landing page.

Will this meet your requirement? @ChristinaB

**Comment by zhiyuli** [comment]
this issue was replaced by #1403

**Comment by dtarb** [comment]
@ChristinaB please check if this is still an issue.  Right now under related resources tab there is an implementation of a list that says "This resource belongs to the following collections".  Please close this if you are satisified.  If you would like further enhancements, please put them in a separate issue then close this.

**Comment by ChristinaB** [comment]
@jphuong   
Do we still want to think about visualizations for Collections? Or close this issue for now?
C

**Comment by aphelionz** [comment]
@dtarb @ChristinaB Closing this for now, feel free to re-open or make a new issue
