### ISSUE TITLE
Change Contact to Authorship

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1406]
The term Contact on resource landing pages has long bothered me as it suggests entities to contact related to the resource which is not really the right connotation.  The sub entries are Author and Contributor, which are concepts related to intellectual ownership.  Here is a suggestion for a fix to this semantic presentation issue

1. Change the tab "Contact" to "Authorship"
2. After Authors that appears below the tab and is the header for the list put in parentheses "(People or Organizations credited for creation of the intellectual content of the resource at a level that warrants authorship.  This is synonymous with Creator in Dublin Core Metadata)"
3. After Contributors put in parentheses "(People or Organizations credited for making contributions to the resource at a lesser level than justifies authorship)"

I am assigning to @horsburgh for vetting of the words, then when vetted to @mauriel133 for implementation.

**Comment by horsburgh** [comment]
@dtarb - perhaps there has been some confusion. The Authors' names are listed near the very top of the resource landing page along with the Owner. Indeed, the section at the bottom lists contact information for both authors and contributors, which is why we created that section and called it "Contact". 

If someone wanted to contact a person about the content of a resource, wouldn't they want to contact the Authors or the Contributors? 

I realize that this may be a little confusing because the user creates Authors and Contributors in the "Contact" section rather than at the top where the Authors' names are first listed.  If you think changing the name of the tab from "Contact" to "Authorship" solves this, then its a simple fix.

With respect to the text you suggest in parentheses, I would prefer to do these as simple paragraph text without parentheses under the main "Authors" and "Contributors" headings.  Here is the text I think should be added:

Under the Authors Heading:

`The people or organizations that created the intellectual content of the resource.`

Under the Contributors heading:

`People or organizations that contributed technically, materially, financially, or provided general support for the creation of the resource's content but are not considered authors.`

**Comment by horsburgh** [comment]
@dtarb - I just reassigned this to @mauriel133 because I think it would take him him just a couple of minutes to do these changes.

**Comment by dtarb** [comment]
I agree with @horsburgh suggestions.  Let's get it implemented.
