### ISSUE TITLE
REST API to retrieve resourcemap xml document

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#1425]

**Comment by alvacouch** [comment]
@pkdash @dtarb @danames @shawncrawley 

Believe it or not, this seems to have been already implemented, though I don't know if it works properly. The REST endpoint to use is: 
/hsapi/resource/{resource-id}/data/resourcemap.xml
Please see if this works! 

To understand this code, see:

* hs_core/resourcemap_urls.py for the endpoint.  
* views/resource_rest_api.py for the implementation.
* hs_core/views/__init__.py for the private routines used in the implementation.
 
If this doesn't work, I have another simpler implementation. I discovered this implementation **after** hacking it up.

**Comment by alvacouch** [comment]
@dtarb @danames @shawncrawley @pkdash 
There is a lot more stuff in hs_core/resourcemap_urls.py that might not work. 
See the url 
```
resource/{server-key}/home/{proxy-user-key}/{resource-key}/data/resourcemap.xml
```
(at least, this is the best interpretation I can make of it; not sure exactly what it is doing). This is implemented via:
```
url(r'^resource/([A-z0-9]+)/home/{}/(?P<shortkey>[A-z0-9]+)/data/([^/]+)/$'.format(settings.HS_LOCAL_PROXY_USER_IN_FED_ZONE),
        views.file_download_url_mapper, name='get_resourcemap_or_metadata_file'),
```
There is a name conflict with the prior version so I think this is the one that gets looked up when you reverse-lookup `get_resourcemap_or_metadata_file`.

**Comment by alvacouch** [comment]
@dtarb @danames @shawncrawley @pkdash The former code is in the develop branch. 

There seems to be an inconsistent implementation of iRODS federation, in the sense that some links use it properly and others just use local links. It looks like the first URL I mailed you is broken, because it does not use federation, but it was neither deleted nor updated. 

One question for you: I know how to put this link into the resource description list so that apps will have it available easily. Should I do this?

**Comment by alvacouch** [comment]
@pkdash @hyi Can you shed any light on the URLS in hs_core/resource_map_urls.py?
One involves federation and I don't know how to interpret it. The other doesn't. Are both active? 
Or is anyone using either one?

**Comment by alvacouch** [comment]
@pkdash @hyi (cc @dtarb) Here is a general question: **when advertising URLS to apps, should I use the federated form, or should I shorten the form if the resource is local?** Since this is shared only with the app, and not with the user, I think I should be consistently advertising the longer federated form of the address.... any objections? .

**Comment by pkdash** [comment]
@alvacouch I won't be able to comment on the federation side. I think @hyi  can. The urls in resourcemap_urls.py are created to make the links in resourcemap.xml xml active (no broken links) and those are all mapped to single view function in views/__int__.py. These are not part of the REST API though. That's why I did not realize there is this end point for downloading the respurcemap.xml document. There is no implementation in resource_rest_api.py for downloading resouremap.xml document.

**Comment by alvacouch** [comment]
@pkdash That this is implemented in `resourcemap_urls.py` and not in `resource_rest_api.py` confused me, too!

**Comment by alvacouch** [comment]
@hyi @pkdash (cc @dtarb) It would seem to me on second thought that embedding the federation information into the URL is actually overkill, because -- in principle -- this url is being interpreted by the core engine, which knows about federation and can construct the federated URL to feed to iRODS from its knowledge of the actual location.....

**Comment by alvacouch** [comment]
@hyi @pkdash (cc @dtarb) Perhaps I should explain further. We have two uses of a federated URL: one for an invocation to iRODS REST, and another for a request to hs_core. It would seem to me that the proper thing to do is to advertise the direct iRODS link for federated data to apps, but to respond -- as hs_core -- to the unfederated link. This simplifies hs_core interaction and -- at the same time -- allows apps to intelligently download things. Thus, hs_core never responds to a federated URL, but apps know the iRODS URL and can use them.

**Comment by pkdash** [comment]
@alvacouch I am not sure we are using iRODS REST at all. As far as I know every file access call needs to go through hs_core.

**Comment by hyi** [comment]
@alvacouch @pkdash The URL mapping in this resourcemap_urls.py is used to map the urls stored in resourcemap.xml file to the django_irods download urls so that these urls stored in resourcemap.xml are resolvable to the real download of the corresponding file stored in irods, by default, in hydroshareZone. However, if the resource is stored in a federated zone, either hydroshareuserZone or a third party irods zone that is federated with hydroshareZone, this federation zone name has to be in the url in order for the download view function to know where (i.e., which iRODS zone) to download file from, which is why I added that url mapping related to federation zone that allows to download file directly from a federated zone. Without this info, download function does not know which iRODS zone to download file from.

**Comment by pkdash** [comment]
@hyi Is the zone name then part of  the url in resourcemap.xml for a file that is on a federated zone?

**Comment by hyi** [comment]
@pkdash Yes, otherwise, download view function does not know which irods zone to download file from.

**Comment by pkdash** [comment]
@hyi The problem is how to get the correct url for the resouremap.xml.

**Comment by hyi** [comment]
@pkdash @alvacouch The urls encoded in resourcemap.xml are generated automatically when resource is created, however, to retrieve resorucemap.xml itself, a REST API needs to be added to check resource object to retrieve federation zone info, then form url properly to allow download of this resourcemap.xml file itself, which I think is part of your work that adds REST API end points for federation zone work.

**Comment by pkdash** [comment]
@hyi Agreed, We need a new REST endpoint to download resourcemap.xml which should be similar to what we have for resourcemetadata.xml.

**Comment by alvacouch** [comment]
See branch 1034-file-metadata for a clone of the /resource/{id}/scimeta/ pattern to implement 
/resource/{id}/resmap/. Make a quick check that this makes sense.

**Comment by alvacouch** [comment]
(This relates to #1034 as well)

**Comment by pkdash** [comment]
@alvacouch It looks OK to me addressing this issue( #1425).

**Comment by pkdash** [comment]
@alvacouch This would require changes to rest client which I can do after this work gets merged.

**Comment by hyi** [comment]
@alvacouch I cannot see the changes you made to 1034-file-metadata related to /resource/{id}/scimeta/ pattern. Could you let me know where the changes are?

**Comment by alvacouch** [comment]
I copied the scimeta routines and created resmap routines from them. The new routines include 
* `resource_rest_api.ResourceMapRetrieve `(class) 
* `hs_core.AbstractResource.resmap_url`

and an entry in `hs_core.urls`...

**Comment by alvacouch** [comment]
@hyi @pkdash Oops. Wrong branch. See branch 1034-expose-file-types-in-REST....!

**Comment by hyi** [comment]
@alvacouch It looks good to me as well. @pkdash When implementing hs rest client, when retrieving resourcemap.xml, just remember to pass in a path string that includes federated zone name if the resource is hosted in a federated zone rather than the default iRODS hydroshareZone.

**Comment by alvacouch** [comment]
@hyi @pkdash Darn. Changes are in the other branch, along with lotsa other confusing changes. I'll move the files.

**Comment by pkdash** [comment]
@hyi 

> When implementing hs rest client, when retrieving resourcemap.xml, just remember to pass in a path string that includes federated zone name if the resource is hosted in a federated zone rather than the default iRODS hydroshareZone

I assume the rest client already takes care of the federated zone param for getting the resourcemetadata.xml. Otherwise, we have do this for some other similar apis in the client too.

**Comment by alvacouch** [comment]
@hyi @pkdash Lots of changes in 1034-expose-file-metadata-in-REST are part of another subproject, and there is a conflict with other changes to resource_rest_api.py .... will rebaseline and get back to you ...

**Comment by hyi** [comment]
@pkdash I am not sure whether rest client needs any changes to take care of federated zone parameter, it will be good to check this when you work on the issue for adding REST support for federation zones https://github.com/hydroshare/hydroshare/issues/1276

**Comment by alvacouch** [comment]
@hyi @pkdash Sorted out. Current code is in branch 1425-REST-API.... matching this issue. 

@pkdash we have a bit of a chicken and egg problem. We now need to test this, which requires the Python REST API...!  Could you create the new method? Or should I?

**Comment by pkdash** [comment]
@alvacouch If you can add the unit test similar to what we have for science metadata (https://github.com/hydroshare/hydroshare/blob/develop/hs_core/tests/api/rest/test_scimeta.py), I will make the necessary changes in the hs_restclient.

**Comment by hyi** [comment]
@alvacouch @pkdash @dtarb @horsburgh @rayi113 @mjstealey  I was thinking about this during our team call, and think there may be a way to remove federation zone info from internal url pattern for downloading files from a federated zone. I will have to look into this later after I get folders work done. @alvacouch You may hold off on this until I get a chance to look into it and see if I can just remove federation zone info from any url patterns, internal or external.

**Comment by pkdash** [comment]
@alvacouch Any update on this.

**Comment by alvacouch** [comment]
@pkdash @hyi (cc @dtarb) 
I have nearly got tests working, but I am concerned by some of the behaviors I am seeing. 

Part of the reason for me seeing this behavior is that I am working with the actual REST calls rather than just the routines. So, in essence, I'm seeing what python-restclient sees rather than just testing the code. I am not satisfied with just testing the routines because so much of this depends upon how the built-in Django REST reacts to my code. 

But -- for better or worse -- I'm using the Django REST client rather than the python rest client, and that is leading to some confusion for me: 

* The /hsapi/resmap/{id} call for grabbing resourcemap.xml gets redirected to an iRODS call (which I expect), but then 
* The iRODS REST call returns a Django ResponseFile (a file stream, in the content_stream object) rather than a file (which I don't expect).

My guess is that this is partly a side effect of using the Django REST client rather than a raw REST client. 

@hyi Should the redirection calls to iRODS generate a streaming file object? Not absolutely sure I'm not messing up somewhere. 

The buggy code is in branch 1425-*

**Comment by hyi** [comment]
@alvacouch Yes, iRODS returns a streaming file response as shown here: https://github.com/hydroshare/django_irods/blob/master/views.py#L125..L129. I expect you can just save this FileResponse object to file, but have never really done so. Perhaps @pkdash knows more on how hydroshare rest client does when downloading a file.

**Comment by alvacouch** [comment]
@hyi OK, that makes me more confident. I know how to save it to a file.

**Comment by alvacouch** [comment]
See PR #1478

**Comment by alvacouch** [comment]
@pkdash does this work? Has the python restclient been updated to access it ? When that is true, feel free to close it.

**Comment by pkdash** [comment]
This has been implemented. Closing.
