### ISSUE TITLE
Federation scheme problems

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1449]
@dtarb @hyi @rayi113 
I have been forced to study federation in order to get REST working and have some concerns. 

1. I believe that we should not be referencing federated resources directly via iRODS REST, but should instead redirect to iRODS as needed in www.hydroshare.org. Specifically, I want the pathnames of resource files to point to www.hydroshare.org and then get redirected. This would mean, in turn, that _each file URL in the resource map_ would point to www.hydroshare.org and then get redirected, so that all of these would be consistent and independent of federation. This would use the same algorithm by which we refer to science metadata and resource map. Rationale: 
    
    a. We can keep statistics on references inside HydroShare. 
    b. We can easily move federated zones around -- and resources from zone to zone -- without editing resourcemap.xml. 

2. I am concerned about security of the iRODS federation. It seems like the proxy user on the federated site has full access, and that the iRODS REST path utilizes that full access. Thus **anyone with the iRODS federated REST path can do more or less anything to the federated repository.**

**Comment by hyi** [comment]
@alvacouch This statement "anyone with the iRODS federated REST path can do more or less anything to the federated repository" is not true since only power proxy iRODS user can used this federated REST path or federated zone name to access files which requires the whole set of credential of the power proxy iRODS user which is protected strictly. That being said, I think we can create REST API end point with resource id input without any federation zone on the url so that REST API end point implementation will retrieve resource object from the id and figure out which federation zone the resource file should be retrieved from. However, the directly url download needs the federation zone name in the url path since the url path is the only information for file downloading, but the REST API function can encapsulate this and not require federation zone name in the path. cophing @dtarb @pkdash and @rayi113 to keep them in the loop.

**Comment by pkdash** [comment]
A agree that the REST endpoints for retrieving resource or resource files should not require federation information. From the resource id the API can detect that information.

**Comment by dtarb** [comment]
I'll weigh in after proposal is in next week.

**Comment by alvacouch** [comment]
> only power proxy iRODS user can use this federated REST path or federated zone name to access files which requires the whole set of credential of the power proxy iRODS user which is protected strictly

The current redirection strategy does redirection to the iRODS path for requests from the end-user. How does that work? The end user does not have the credentials for the proxy account.

**Comment by hyi** [comment]
@alvacouch REST API endpoint url can only include resource id and optionally file to be returned, and the REST API function will retrieve resource federation info and redirect url to iRODS download url properly to download the file. The proxy account's credentials are protected in local_settings.py, and are used internally to create iRODS user session for iRODS operations.

**Comment by hyi** [comment]
@alvacouch Now that the federation zone path has been removed from any internal and external urls, I think this issue can be closed. Can you close this issue if you agree?

**Comment by alvacouch** [comment]
@hyi This is fixed.
