### ISSUE TITLE
Auto-create WMS/WFS/WCS layer for Raster and GeographicFeature resources

### ISSUE THREAD

**Issue by shawncrawley** [hydroshare/hydroshare#1450]
When a user creates a Raster or GeographicFeature resource, a nice feature would be the automatic creation of a GeoServer layer with WMS and corresponding WFS or WCS endpoints of a standard, defined pattern. The endpoint(s) would then become a part of the resource's metadata shown on the resource's landing page.

This feature would benefit both the general HydroShare community and the subset of HydroShare app developers by allowing applicable resources to be used in any relevant external applications or scripts. A common user may want to connect to the resource's WMS endpoint through ArcGIS. For app developers working with geospatial visualization of resource, these endpoints could unify and simplify the visualization design and coding, while also yielding a more optimized app-user experience.  For example, HydroShare GIS currently creates a GeoServer layer for each geo-spatial resource that it visualizes. Although this is done only once (the first time each resource is ever opened in the app), it can add minutes to the loading time. Also, each distinct app that visualizes resources using GeoServer are currently creating their own distinct GeoServer layers, cluttering up the GeoServer with unnecessary duplicate data. If each resource's GeoServer layer has already been created (with a standardized endpoint) by HydroShare at the resource's own creation, then any and all apps built to visualize resources can point to the same WMS endpoint and expect optimized layer load time.

I have been tasked by Dr. Ames to tackle this feature. I am capable of doing much of it, however I am not sure how we would want to implement the "HydroShare GeoServer." Since an apps.hydroshare GeoServer already exists, that one could be used. However, it would likely be better to implement a new GeoServer on HydroShare's own server. This could be done with a Docker-ized GeoServer container, similar to Tethys Platform's implementation (see http://docs.tethysplatform.org/en/latest/production/distributed.html#geoserver-docker-deployment and https://github.com/tethysplatform/tethys_docker/tree/master/geoserver). What are your thoughts on this, @mjstealey?

Once we figure out how to implement the GeoServer I will get to work on the code to create the GeoServer layers at resource creation.

**Comment by dtarb** [comment]
Similar functionality, but with different file type is already implemented for multidimensional resources using Hyrax.  @hyi set this up so I suggest confer with her.  Some things you need to consider are

- Access control.  Unless the geoserver can integrate with HydroShare access control, then you should only set up an end point when a resource is made public (not when created).
- Even if access control is possible, I think that publishing through a web service may need to be deliberately chosen after the resource is created and not automatic, because resources may be created without files, or with incomplete files.
- Try avoid duplication of the resources, so a direct file mount to iRODS content, e.g. using iRODS NFS would be preferable.
- A separate server for this seems logical (e.g. geoserver.hydroshare.org, just like we have http://hyrax.hydroshare.org/ for multidimensional).

**Comment by hyi** [comment]
@shawncrawley @dtarb @mjstealey If we want to use this geoserver for automatic creation of a GeoServer layer with WMS and corresponding WFS or WCS endpoints which would then become a part of the resource's metadata shown on the resource's landing page, a geoserver container on hydroshare server seems to be most appropriate since it can directly add the GeoServer layer endpoint into the resource's metadata in hydroshare container on the same server without using REST API call. A separate server like hyrax may not work as well since we need bi-directional interaction between hydroshare server and this separate geoserver. Our current hyrax server setup only needs to read hydroshare resource data as input, then expose OpeNDAP service urls (in a fixed pattern specific to the resource id) so hydroshare netCDF resource type app can just use this url (fixed pattern coded with no need to talk to hyrax server) to redirect to on the resource landing page. However, for this geoserver case, after the corresponding layer is created, it needs to be written to the resource's metadata, which is the main reason I think having a geoserver on the same hydroshare server would have advantage. An alternative @shawncrawley brought up to leverage the geoserver on apps.hydroshare.org may also be a good option which saves us from getting another geoserver into our server stack. We may just set up iRODS NFS to expose public feature and raster resources to apps.hydroshare.org, which can retrieve HS resource data directly (similar to what we did on hyrax server) for geoserver to automatically create proper layers, and then add created layer endpoint into the resource's metadata on hydroshare server.

**Comment by shawncrawley** [comment]
Here is a schematic I created after talking things over with Dr. Ames. I've attached it here. 
![hydroshare_geoserver_schematic](https://cloud.githubusercontent.com/assets/12499203/18731344/a004876c-8018-11e6-9acf-bbfe006e80ea.png)

I'm going to start coding this on a new branch. We can plug in the correct GeoServer endpoint when we've decided what we're doing. For testing, I'll just use appsdev.hydroshare.org:8181/geoserver. I'll also look into GeoServer's authentication implementations.

**Comment by danames** [comment]
Thanks for drawing this Shawn.

Others: please indicate if you have any questions about our proposal for
adding WMS/WFS/WCS services on to HydroShare resources.

**Comment by hyi** [comment]
@danames @shawncrawley @zhiyuli The only question I have is whether we should consolidate this new geoserver.hydroshare.org and the geoserver currently hosted on apps.hydroshare.org into one. Is there value to use the geoserver currently hosted on apps to achieve this rather than creating a new geoserver.hydroshare.org?

**Comment by shawncrawley** [comment]
@hyi I believe there is value in having two separate geoservers. This new hydroshare geoserver will only store the layers that directly represent a hydrosahre resource. However, some apps are still generating random and temporary layers on the fly, and thus the apps geoserver could remain a good "scratch space" for those cases.

**Comment by hyi** [comment]
@shawncrawley OK. That makes sense to me. Thanks for the clarification. Do you plan to have geoserver.hydroshare.org on a separate VM host or together with www.hydroshare.org VM host as a separate container in the similar way as done for apps.hydroshare.org?

**Comment by danames** [comment]
Right now we're thinking about hosting geoserver.hydroshare.org on a
separate server but we could go either way. I'm interested in Michael and
Ray's thoughts...

**Comment by horsburgh** [comment]
I am closing this issue because I'm assuming that the automated creation of WMS/WFS/WCS services for geographic feature and raster content types within composite resources is working correctly. I just created issue #3825 for adding the URLs to these automated endpoints to the content level metadata on the resource landing page.
