### ISSUE TITLE
WebApp should be launchable from its own landing page

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#1465]
Upon request from @danames and Dr Nelson, a webapp should be launchable from its own landing page.

Currently, a webapp can only be launched from landing pages of other resources that the webapp works with. The reason is that the "webapp url" is not a real url. Rather, it is a url template that can carry dynamic parameters (like resource id) to info the webapp which resource it should open and what action it should perform. 

We plan to keep the existing 'url template' unchanged and add a new field called "webapp homepage url" , which is a real url allowing users to open homepage of that webapp.  This approach will meet the new requirement and retain the flexibility of having 'url template'.

**Comment by gantian127** [comment]
@zhiyuli would you please test and close this issue if this has been fixed? Thanks

**Comment by zhiyuli** [comment]
merged and tested

**Comment by dtarb** [comment]
@zhiyuli I am looking at Document Viewer App on beta.hydroshare.org and cannot see where to launch the app https://beta.hydroshare.org/resource/326a0c2d1e804057993458f4f96d6e51/

Same for SWATShare https://beta.hydroshare.org/resource/7dcb29a77e1d4ab1a9ec07ae2d4d1cea/

But on HydroSHare GIS I do see the button.  

Can you please get the word out to App Instance Maintainers as to how to set up their App so that it works.

**Comment by zhiyuli** [comment]
@dtarb 
I just added "app home page url" metadata to 
1) the two resources on beta you mentioned (I did not change other webapp on beta as changes will not persist on beta)
2) all public webapp resources on www that I have edit permission
they have "Open Web App" button on their landing pages now.

I will leave a message to the owners of the rest public webapp resources to remind them this "Open Web App" button feature is ready.
