### ISSUE TITLE
Resource Publication: Publish Resource with Assigned DOIs

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#15]
Implement the capability to have HydroShare resources permanently published with DOIs once their metadata meets the requirements in the Formal Publication Specification Document https://my.alfresco.com/share/s/wqJISdf_TQS5lJs32OoYZw.  This should be coordinated with CUAHSI working with Rick Hooper

**Comment by horsburgh** [comment]
Details of the process and workflow for formally publishing a resource are available in the Google Doc at:

https://docs.google.com/document/d/1tNFStpEmbB_AC2ICppVSw-024-iTrnqGK9Np7Elw2OM/edit

The following are needed to complete formal publication of a resource:
- [ ] Add a "publish" button to the resource landing page
- [ ] Add code to validate that the required metadata elements are present and that the resource has content files for resource types that require them. If they are incomplete, notify the user and boot them out of the process.
- [ ] Display a message notifying the user that the resource will be permanently published and that they will no longer be able to edit the resources. The message will also state that the user will be able to create new versions of the resource after it has been published. The user must agree to continue.
- [ ] Display the text of a data publication agreement that the user must agree to before proceeding.
- [ ] Automatically assign a DOI to the resource
    - [ ] Construct the DOI for the resource using the CUAHSI prefix (see Google Doc)
    - [ ] Construct the deposit XML for Crossref from the resource's science metadata
    - [ ] Upload the deposit XML into Crossref for registration
    - [ ] Display a message that alerts the user that the DOI has been requested and that the resource will be updated when the DOI has been registered.
    - [ ] Monitor the status of the deposited DOI until it has been registered. This may be instantaneous and contained in the response from the Crossref web services. However, need to make sure that the DOI actually gets registered.
- [ ] Set the properties of the resource to make it immutable (disable the edit button on the resource landing page) and set the status of the resource to "published".  Display a status of "Published" on the landing page.
- [ ] When the DOI is available, update the resource's science metadata to include the DOI as an identifier element. Update the display of the landing page to use the URL-encoded DOI in the citation instead of the HydroShare URL.
- [ ] Send a notification to the user that the resource has been published and that the DOI is available

**Comment by horsburgh** [comment]
CUAHSI's prefix for DOI's is set:  10.42111/<unique suffix>
Sample of an existing CUAHSI DOI:  http://dx.doi.org/10.4211/his-data-shalenetwork

It is up to HydroShare to generate a unique suffix for each DOI. One simple option for the suffix will be to simply use the HydroShare resource identifier, but I think we want a node in the suffix to uniquely identify HydroShare resources given that the prefix is for anything CUAHSI creates.  This would effectively place HydroShare resources within a DOI namespace of sorts within CUAHSI's unique prefix:

Example:  

    http://dx.doi.org/10.4211/hs.<resource identifier>

Where:      
"hs" is a unique DOI node for HydroShare
\<resource identifier\> is the HydroShare resource identifier

**Comment by hyi** [comment]
@dtarb @horsburgh Just to confirm: we don't require resource to be public or discoverable before the resource can be published, right? In other words, as long as the same requirements are met for making a resource public, the owner of the resource can publish a private resource, right?

**Comment by horsburgh** [comment]
@hyi - Correct.

**Comment by dtarb** [comment]
Yes, but the act of publishing should result in the resource ending up discoverable or public (with public the default).  Also in some discussions with Rick Hooper there has been suggestion of additional resource metadata completeness rules that may need to be met for publish over and above public and discoverable, so while we do not have such rules now, please recognize that we may need this in the future.

**Comment by horsburgh** [comment]
Public and Published are effectively 2 different states.  A resource can be Public without being Published.
Both Public and Published are discoverable.

**Comment by hyi** [comment]
@dtarb @dtarb @alvacouch So once a resource is published, the resource should be set as Public by default as its sharing status? If so, I would assume it means the owner of the resource can modify the sharing status even after a resource is published. Then I guess the published resource is immutable only in terms of its content files and metadata since we still allow users to change its sharing status after the resource is published. Is this intended? It makes more sense to me NOT to allow users to change sharing status after a resource is published and made immutable, but there might be use cases I am not aware of that requires changing sharing status even after the resource is published. Need explanation or confirmation to make sure I implement it correctly.

**Comment by horsburgh** [comment]
I think "Published" should be a sharing status. "Public" and "Published" are not exactly the same. 

And yes, permissions for "Published" would be the same as "Public" but should not be revocable (or really editable except that ownership may change?).

**Comment by hyi** [comment]
@horsburgh @dtarb @alvacouch Making "Published" a sharing status is more complicated from implementation standpoint since access control code has to be modified to consider this additional "Published" sharing status. We can enforce more requirements for publishing a resource on top of requirements for making a resource public, and it seems simpler to make "Published" as a flag on the resource object without making it a separate sharing status. Since we don't allow a resource to be editable after the resource is published (i.e., disabling resource edit button), it makes more sense to me not to allow users to make any edit on a published resource including the resource's ownership and sharing status. To make published resource discoverable, we can add a requirement to only allow a resource to be published after it is made public or discoverable. This means we don't allow users to publish a private resource. This makes sense to me since we need to make published resource discoverable, so why do we allow users to publish a private resource. We can just require owners to make resource public or discoverable before they can see the publish button. What do you all think?

**Comment by horsburgh** [comment]
Published resources need to show up in the "Sharing Status" column in the My Resources page with a sharing status of "Published". Also, on the call this week we discussed being able to filter by SharingStatus = "Published".  Also - it would be better if it weren't a two step process to make something public and then have to take a separate step to publish.  Seems like private, public, and published are mutually exclusive states for a resource. 

Publishing a private resource would effectively make it publicly viewable and discoverable (there is no such thing as a "private" Published resource).

**Comment by hyi** [comment]
@horsburgh @dtarb OK. I think I've got the point. I was confused by the comment that publishing a resource makes it public or discoverable (public by default) which made me think public or discoverable sharing status in HydroShare. Thinking "Published" as a mutually exclusive sharing status with Public, Discoverable, and Private makes sense to me now. Basically, we allow to publish a resource with any sharing status (private, discoverable, or public) as long as the resource meets the publishing requirements, and after a resource is published, the resource becomes viewable/discoverable/searchable to anybody, and of course is immutable and not-editable. Since a published resource is not-editable, should we remove uses with editing privileges from access control point of view? Should we allow owners of a published resource change ownership? Adding @alvacouch in the loop for access control related questions for a published resource.

**Comment by dtarb** [comment]
See my response in #889.

While formally publishing a resource, which includes setting the immutable flag, makes having change permissions moot, I do not think that the act of publishing should remove all change and view permissions. If we did this it would then result in removing a resource from a MyResources page for a user that had change permissions (i.e. it disappears from their page).  I prefer to leave the change and view permissions as declared privileges and have these declared privileges serve to support the filtering functionality on the MyResources page. 

As to the question about changing declared privileges for published and immutable resources, I think it should be allowed.  This means that the setting and revoking of declared privilege parts of access control for a resource are not frozen, by a resource becoming immutable. So I suggest interpreting immutable as applying to the content, not the ownership and permissions.  I think that all access control changing functionality as currently stated in policy (and implemented notwithstanding bugs still to be resolved) should still apply for published and immutable resources.  This includes

- an owner can add or delete owners where there are multiple (not removing the last one).  This enables ownership transfer for these resources should the responsibility for "keeping" change.
- a user with change permissions can add or remove change and view permissions.  The effect of this will be leaving control over what appears on MyResources pages with the users, in a similar manner to unpublished resources.  
- A user with view permissions could remove their view permission.  This would effectively drop the resource from their MyResources page.
- We could extend the model a bit to allow any user to claim view permission on a published resource.  This could be the device whereby they add it to their MyResources page rather than tracking separately whether they have added to MyResources.

The rationale behind this is consistency of application, behavior and interface.  A resource becoming published and immutable should not change the behavior users will get accustomed to in sharing of resources (and we simplify the code by reusing what exists).

**Comment by pkdash** [comment]
@horsburgh Question related the 'Publisher' metadata element. As per the current code base the Publisher name sub-element is set to "HydroShare" and the the url sub-element is set to 'https://hydroshare.org". It seems this needs to change. Now it seems the publisher name attribute needs to be set to "Consortium of Universities for the Advancement of Hydrologic Science, Inc. (CUAHSI)" and the url needs to be set to "https://www.cuahsi.org". Is this correct? 

Also, CUAHSI becomes the publisher only when the resource has content files. For resources, that does not require content files, the user should be able to set the publisher to something other than "CUAHSI". Is this assumption correct?

**Comment by horsburgh** [comment]
@dtarb - Leaving all of the access control open for editing on Published resources seems unnecessary and potentially confusing. It doesn't make sense to me that we would allow users to keep granting "edit" access to something that can't be edited. Also, why do we need to grant "view" access?  If it's published, anyone can view it and add it to their list of resources.  Also - if we disable the edit button for Published resources (which is part of the workflow we laid out), users wouldn't be able to get to the access control dialog anyway to change any of those rules because it's on the edit page.

With respect to owners - the responsibility for "Keeping" published resources resorts to the publication system once something is published.  When I publish a research paper, I don't have any responsibility to to do any "Keeping". So, I'm not sure what "keeping" means in this context.

Published resources should not behave the same as other resources. Buy formally Publishing something, the user has made a **final** sharing choice. 

I think we need some other way to keep published resources in people's lists without allowing modification of permissions after publication.

**Comment by horsburgh** [comment]
@pkdash - I made the suggestion that only resources with content files stored in HydroShare can effectively be "published" by HydroShare. The only way HydroShare can guarantee that content to which a registered DOI points does not go away is for that content to be stored in HydroShare and not elsewhere. Plus, for some types of referenced resources, the content to which they point may already be published elsewhere.

There was some discussion on the phone this week about whether referenced resources should be formally publishable in HydroShare.  They would effectively be metadata-only records (pointing at data stored in another system) to which DOIs would be assigned.  I think the BYU team was in favor of this.  I think we need a pow-wow to make some final decisions about this.

**Comment by horsburgh** [comment]
@dtarb - @alvacouch 's suggestion in #889 of what to do with permissions for immutable resources seems reasonable. Since the edit page will be disabled for immutable resources, the following changes would be made to access control when resources become immutable:

real privilege   |   not immutable    | immutable
  ------------------  |  -----------------------  | ---------------
   OWNER         |  OWNER             | OWNER
   CHANGE       |  CHANGE            | VIEW
   VIEW             |  VIEW                  | VIEW

**Comment by hyi** [comment]
@dtarb @horsburgh @alvacouch @mauriel133 @pkdash I have implemented resource publication in the way that after a resource is published, it is made immutable with ownership retained and edit permissions downgraded to view permissions for all edit users. The published resources appear on my resources page since it is public and discoverable with sharing status as "Published". Filters on my resources page still apply but published resources will not show up on "editable by me." After clicking on a published resource from my resources page to get to published resource landing page, it shows its sharing status as "Published and Immutable" with no edit and delete buttons. For a discovered published resource, "Add to my resources" button will still show up to allow users to add a published resource to my resources list, but no edit and delete button will show up preventing users from doing any edit to published resources. This means ownership and permissions are frozen for published resources retaining values at the time when the resource was published although edit permission is downgraded to view permissions automatically when a resource is published. Will deploy the resource publication work to a VM after the DOI assignment work with crossref is done for testing and comments.

**Comment by horsburgh** [comment]
@hyi - Awesome!  I'll look forward to testing!

**Comment by alvacouch** [comment]
See issue #893 for changes in access control that will benefit this -- forthcoming.

**Comment by hyi** [comment]
@alvacouch If you can get this done by end of next week, that would be great. I can then integrate my resource publication work on top of your work for issue #893 without doing duplicate work to get user interface working as expected. Thanks.

**Comment by hyi** [comment]
@alvacouch Based on my testing, what I have done already regarding permissions and access control for published and immutable resources worked well for resource publication purposes, so there is no rush for you to get issue #893 done for resource publication work. You can take your time to get system-wide change worked out as documented in this issue without rushing. We can always integrate our respective overlapping work on top of each other as needed. @dtarb @horsburgh @pkdash @mauriel133

**Comment by hyi** [comment]
@alvacouch @dtarb @horsburgh @pkdash @mauriel133 I noticed the following potential "issue" based on testing on my resource publication branch:
* Although non-owner users with edit permissions can be safely downgraded to VIEW permissions for published immutable resources, retaining ownership of a published resource means all owners have edit permissions in our current access control implementation, so if we retain the owners, we cannot remove owners' edit permissions. This results in published resources ending up in "editable by me" filter in my resources page for owners of published resources. 
@alvacouch Do you intend to fix this in access control system as part of work to address issue #893 or we retain the current behavior with assumption that owners have edit permissions but for published resources, the "editable by me" is just a declared privilege, not an effective privilege since they will not be able to edit or delete a published resource from the resource landing page anyway. What do you all think? In any case, this needs to be handled system-wide in access control level, so I will not do any further work for resource publication regarding this specific issue.

**Comment by hyi** [comment]
@horsburgh Looks like http://test.crossref.org requires login to be able to do anything. Do I really need a login credential on test.crossref.org for testing purpose? I cannot find any user registration info on the site, so not sure how to obtain login account. Need to dig deeper into crossref help system to understand the process, in the meantime, asking you in case you have information handy regarding this. I need to work on creating deposit xml file first, so don't need to use crossref test system now. Just happen to come across this which prompted the question.

**Comment by horsburgh** [comment]
@hyi - I don't know if the test site requires it, but we will eventually need CUAHSI's login information.  @dtarb - can you help get the necessary details from Rick Hooper?

**Comment by hyi** [comment]
@dtarb @horsburgh I have successfully uploaded deposit xml metadata to crossref test system programmatically using crossref https request POST API. After about 10 minutes, I received email notification from crossref indicating success. According to crossref documentation, how long requested DOI can be processed and activated depends on how many requests are in the queue at the time. Although the basic resource publication workflow has been implemented as outlined in the design spec, we need to decide what to do with the resource during the time after the DOI request has been successfully deposited in crossref system and before the DOI has been activated by crossref to take effect (i.e., after we receive email notification from crossref indicating success). In the worst scenario, human intervention may be needed, to contact crossref support if we don't receive email notification for successful DOI activation in a long time or resolve some unforeseen issues. I am currently implementing the workflow as follows: after I receive response from crossref indicating metadata deposit submission is successful, I just set resource status as published and immutable and change science metadata accordingly treating the resource as published. The citation of the resource automatically changes to resource DOI after it is published. If a user happens to click the resource's DOI link before the DOI is activated, the user will see a crossref page indicating DOI is not found with possible reasons including DOI is not yet activated, a sample page can be found here:  http://dx.doi.org/10.4211/hs.a312a8bffd334462b68e732752acdfac. After DOI is activated, crossref should take the user to the published resource landing page if the DOI link is clicked. Is this acceptable? If not, what do you suggest we should do with the resource during the period after we successfully submitted DOI registration to crossref and before the DOI is actually activated?

**Comment by horsburgh** [comment]
@hyi - I've had this happen with journal papers before.  The publisher sent me the DOI, which hadn't been registered/activated yet, and when I tried to use the dx.doi.org resolver to access the landing page for the paper, I got the page you sent us the example for.  One option is to just notify the user at the end of the publication process that their DOI will not be available until it has been registered and activated (which can take up to X amount of time).  But we will need some sort of automated process that verifies that the DOI does, in fact, eventually get activated.  If not, human follow up may be needed.

**Comment by horsburgh** [comment]
Another option is to disable editing on the resource at the time of publication but have an offline process that monitors the DOI until it is active and then have that offline process update the metadata for the resource to use the DOI.  So, the resource landing page would show the HydroShare URL until the offline process verifies the DOI is active.

**Comment by hyi** [comment]
@horsburgh I thought about this option as well, specifically using celery worker to query crossref API to check the status of DOI activation in the background thread. However, I am not sure how often we should run this background worker to achieve our purpose without impacting performance too much especially in the cases when human intervention is needed to contact crossref support if DOI activation for a specific resource has issues. I am bringing @ironfroggy in the loop to get his input. @ironfroggy Check info above for some background info on my specific questions.

**Comment by hyi** [comment]
@horsburgh @dtarb @ironfroggy @mjstealey After giving this some thoughts, I'd like to go with the option @horsburgh proposed above, i.e., notify the user at the end of the publication process that their DOI will not be available until it has been processed and activated (which can take up to X amount of time). I can write a monitoring script to run every midnight as a cron job to check all pending published resources by querying crossref API to see whether the pending published resources have been activated successfully, and compile a list of pending published resources that have not yet been activated as well as x amount of time the resources have been pending since submission and email support@hydroshare.org the info as needed. This way, hydroshare support team will get notified each day the pending resources to be published and x amount of pending time if any, and follow up as needed. Let me know whether this approach is acceptable.

**Comment by dtarb** [comment]
I agree with this approach.

**Comment by ironfroggy** [comment]
I agree with the approach as long as this is not a CRON job but a Celery task as originally proposed.

**Comment by horsburgh** [comment]
@hyi - some issues based on testing on dev.hydroshare.org today. Many of these would need to modified in the data publication agreement page since you are displaying that in the pop-up in the publication workflow.

* [ ] When I click on the “Terms of use” link in the data publication agreement, it puts the terms of use in the text box, but I can’t go back to the publication agreement.  I think it should open the terms of use in a new page (like it does with the link to NSF’s data sharing policy).
* [ ] Same issue with the statement of privacy link.
* [ ] In the data publication agreement, change “Tufts” to “Tufts University” and “Purdue” to “Purdue University”
* [ ] In what is now the first item in the numbered list – make the word data plural in all cases - “in-situ data were collected”, “ex-situ data were analyzed”, “data are published"
* [ ]  In the Disclaimer, change the following text “Resources accessed through the HydroShare…” to “Resources accessed through HydroShare…” (get rid of “the”)
* [ ] Change the last statement to “CUAHSI will not accept liability for damages of any kind that result from using HydroShare or its content resources."
* [ ] Number one in the numbered list of items should be something like "I hereby grant to CUAHSI and the HydroShare Team a non-exclusive publishing and distribution license for the content of this resource in all forms and media (whether now known or hereafter developed) effective when I accept this publication agreement."

**Comment by dtarb** [comment]
@horsburgh please also make these changes on the Google Doc publication agreement as that is what Rick Hooper has been asked to have CUAHSI approve.

**Comment by horsburgh** [comment]
@dtarb - I made the modifications to the Google doc.

**Comment by hyi** [comment]
@horsburgh @dtarb I have addressed all your comments and redeployed beta.hydroshare.org for your further testing. Please test it out on beta.hydroshare.org and let me know if there are any further comments to be addressed.

**Comment by horsburgh** [comment]
@hyi - I just published another resource on beta.hydroshare.org and things looked good to me. See my comments about the DOI registration stuff inline with your code. I'm excited to have this capability in HydroShare!!

**Comment by hyi** [comment]
Closing this issue since this feature has been deployed.
