### ISSUE TITLE
User name issues

### ISSUE THREAD

**Issue by sno036** [hydroshare/hydroshare#1514]
Users can create a user name at the sign up stage that is later determined to be invalid when the profile is edited.  Specifically in my case this was using a "." in the user name.

**Comment by dtarb** [comment]
See also #973

**Comment by hyi** [comment]
@dtarb @mjstealey @rayi113 I will address this issue by restricting user names from containing special symbols such as ., @, etc. since linux does not allow such special symbols in user names. This will allow us to align django user names with iRODS user names for quota management and user zone iRODS user management. Let me know if you disagree.

**Comment by hyi** [comment]
@dtarb @alvacouch @mjstealey @rayi113 Since user name validation rules appear to vary with specific linux distributions and operation systems, there does not appear to be a uniform hard constraints for user names, but only a general recommendation such as specified here: http://www.unix.com/man-page/linux/8/useradd/ with relevant recommendations shown below: 
```
It is usually recommended to only use usernames that begin with a lower case letter or an
       underscore, followed by lower case letters, digits, underscores, or dashes. They can end
       with a dollar sign. In regular expression terms: [a-z_][a-z0-9_-]*[$]?

       On Debian, the only constraints are that usernames must neither start with a dash ('-')
       nor contain a colon (':') or a whitespace (space: ' ', end of line: '\n', tabulation:
       '\t', etc.). Note that using a slash ('/') may break the default algorithm for the
       definition of the user's home directory.

       Usernames may only be up to 32 characters long.
```
In Django, user name can be 150 characters or fewer and may contain  alphanumeric, _, @, +, . and - characters. This is why user names with some special symbols such as @ and . are allowed in django. I am thinking it is probably better to make user names more restrictive than what Django allows. Any ideas on validation rules for user names? I need to have a consensus on user name validation rules before implementing it. If we want to be more non-restrictive to delegate user name validation to django as we currently do, I need to verify iRODS needs to support such non-restrictive user name as well and if so, I can then address this issue by checking into user profile implementation to make sure user names with supported symbols are deemed as valid when editing profiles. Let me know what you think.

**Comment by hyi** [comment]
@dtarb @alvacouch @mjstealey @rayi113 Have just tested on iRODS side to create iRODS users with special characters ```.``` and ```@``` and they all succeeded without issues. So I am going to go with delegating user name validation to Django to be more not-restrictive as we currently do, and address this issue by checking profile editing to regard such user names with special symbols as valid rather than raising errors.

**Comment by hyi** [comment]
@dtarb @alvacouch @mjstealey @rayi113 Have changed user profile editing user name validation rules to conform to Django user name validation rules to allow a few more special symbols, ```.```, ```+```, ```@``` which are allowed by Django. This will ensure user names created successfully by Django will not raise errors when editing profiles. A PR has been created for this.

**Comment by dtarb** [comment]
Checked in beta.  Closing.
