### ISSUE TITLE
Direct file downloads in folder interface upgrade

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1522]
On the pre-folder interface deployment it was possible to hover over a file download button and see the URL at the bottom of the browser and right click to  copy link location to build direct URL's to files in resources.  This functionality I used in building a web page for my class that used direct links to students work - see http://hydrology.usu.edu/dtarb/giswr/2016/students.html.  In the new folder interface currently deployed on beta (and scheduled for roll out next week) this functionality is no longer there.  One has to right click on a file to download, but cannot see what the direct download link is or copy the link location using browser functionality.  The links to direct fiels still work.  There is just no way to discover this capability.  I would prefer a simpler download button or link to click that retained this standard browser copy link and showing the URL functionality.

**Comment by mauriel133** [comment]
@dtarb, how about a right click menu item "Copy file URL"

**Comment by dtarb** [comment]
I am OK with that, but it does seem that there used to be a more common web approach that handled things naturally as html links the way browsers commonly work.  Now you are rewriting some of this to work differently.  If either the icon used to show the file, or its name was just made into html hyperlink text with the URL linked you would not have to do the work of building a new right click item.

**Comment by horsburgh** [comment]
@dtarb - If there is a right click required already to get the URL, I'm not sure how this is really different. When I hover over the download link in the pre-folder version (the little circle with the down arrow), I do see the URL at the bottom of my browser. That would be the only thing that has been lost. You have to right click on the download button to get the link anyway. 

I think if we added a "Copy Link" or "Copy file URL" on the right click on a file it would actually be better on the new interface because the right click would be on the file icon rather than the download button.

**Comment by dtarb** [comment]
I am OK with either of these as a solution.  I do worry though that this is functionality that the browser used to do and now we are taking on the burden of having to do it ourselves for all browsers we support.

**Comment by dtarb** [comment]
Checked on beta.
