### ISSUE TITLE
Folder interface hangs if there are file name clashes 

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1529]
If I load some files into a resource, then put them in a folder, then out of a zip file get a file name with the same name as a file in the folder and try drag that into the folder the interface results in an indefinite spinning wheel.  I would like it to say that I am not allowed to do that due to overwriting, or give me a warning that I am about to overwrite.  It should not just hang.

**Comment by mauriel133** [comment]
@dtarb, what should be the behavior to resolve name conflicts? Here are a few options I can think of:
- Appending a differentiation to the new file name. For example:

> SomeFile (1)

- Replacing the previous file / ignoring the new file
- Canceling the operation and showing an error message

@hyi, I think we need to work on error handling and error notifications with this interface. Can we catch this error, and others like this, in the back end and have it return an error that can be shown in the front end?

**Comment by hyi** [comment]
@mauriel133 I am working on this and we are on the same page regarding returning the error messages from back end to front end to show error messages to users. I will let you know if I need help on front end to show error messages, which may already have been taken care of.

**Comment by hyi** [comment]
@mauriel133 I have fixed this issue and the front end can show the error message now. However, the spin wheel keeps spinning even after the error is displayed. What I did on front end is to show error messages in this error handler: https://github.com/hydroshare/hydroshare/blob/develop/theme/static/js/resourceLandingAjax.js#L642. This ajax call is pushed to the stack here: https://github.com/hydroshare/hydroshare/blob/develop/theme/static/js/hs_file_browser.js#L191, and I am not sure how to stop the spinning wheel if that ajax call on the stack raised an error. Any quick idea to stop spinning wheel upon error? Otherwise, I may just check in what I have and then you can work on top of my branch to fix the spinner wheel issue on the front end. Let me know.

**Comment by hyi** [comment]
@mauriel133 I created a PR for this. You can work on top of that to address the remaining spinner wheel and interface hanging after errors are displayed.

**Comment by mauriel133** [comment]
I added the necessary events to listen for these errors and set the proper state of the file browser. However, I think the error messages are not very user friendly at the moment.

See error when trying to rename a file to a name that already exists:
![image](https://cloud.githubusercontent.com/assets/2448568/20077715/bd4956ac-a4fa-11e6-8184-02b4acd4f756.png)

I think this could be reworded to something simpler and more accurate.

**Comment by mjstealey** [comment]
> I think this could be reworded to something simpler and more accurate

That error is bubbled up directly from iRODS and basically states that the iCAT database already has a record for a file of the same name in the same location. Standard POSIX enforcement stuff.

We could potentially encounter a whole mess of these kinds of errors as soon as we allow arbitrary renaming and moving of files/folder/etc.

**Suggestion**: For a first pass we may want to keep the bubbled up messages as is and simply enforce them from the UI standpoint. Follow on work would be to determine the lexicon of iRODS error IDs that we'll run into and remap them to something more human speech friendly.

**Comment by hyi** [comment]
@mauriel133 I agree with @mjstealey. This error message directly comes from iRODS. The top line indicates it failed, the bottom line indicates the exact error message we get from iRODS. I suggest we leave it as is for now, and deal with user-friendlier informative messages later as needed. Alternatively, we may hide this iRODS specific message by default, but add a link worded something like ```error details``` following ```File Moving/Renaming Failed``` on the first line, and once clicked, expand to the whole iRODS-specific detailed error message. That can be handled from front end client side.

**Comment by dtarb** [comment]
While testing this issue I found the following problems.  Some of these are this issue.  Some may be separate issues.  I am putting them all here, but feel free to break out into separate issues if that is better to manage this.

Note I did this for the following resource

https://beta.hydroshare.org/resource/3927b13e68ae46188f620b0e7f331993/

The file zipFromPC.zip was loaded into the resource
Unzip here places the two text files in the resource.
Both files and zip file are then placed in FirstFolder
text1.txt is deleted and text2.txt is renamed to text1.txt.  (They are different sizes so I can tell which is which).
Unzip here of zipFromPc.zip overwrites text1.txt in the folder without any warning or error message (I can tell this from file sizes).  Thus the name clash issue is not fully resolved.

I also discovered that the right click to Download a file does not work (I am using Firefox latest version 49.0.2 on a Windows 10 PC).

I also discovered that after delete operations in a folder the "state" seems to be forgotten and the display reverts back to the top of the resource page in grid mode (changes from list mode if was in list mode).

I found it not natural to have to cut a file and then paste at a higher level folder to move a file out of a folder.  Drag onto the higher level folder in the bar where the folder path is indicated would have been more natural to me.

The unzip here button does not work with a zip file selected.  The only way I can get unzip to work is through the right click.

The unzip here button appears to be enabled when there are two zip files selected in a folder.  Would this unzip both?  Since unzip button does not work, it is unclear what is intended here.

**Comment by hyi** [comment]
@dtarb Regarding ```unzipping zipFromPc.zip overwrites text1.txt```, it is working as expected at least from the perspective of iRODS since we passed in a "force-overwrite" flag when doing unzipping. This may sounds inconsistent when we move a file to a folder which contains the same file in which case an error was raised which prevented the move from happening, but that is expected behavior in iRODS world. If you think we should not allow unzipping to overwrite the existing files, I can remove the "force-overwrite" flag when doing unzipping, which would raise an exception from iRODS. The ideal solution would be to give users a warning about overwriting existing files when unzipping, then either overwrite or bail out according to user's input, but that would take more work mainly on client-server handshaking, will not be addressed for this first phase implementation. If you think it is worth the effort to do the warning for subsequent enhancement, you can create a separate issue for subsequent enhancement after 1.8 deploy. This will not be done for 1.8 in any case since it takes a lot of work. 

Regarding "the state after deletion" issue, we intentionally did it the way it is because the whole resource landing page has to be refreshed after a file deletion due to metadata changes that could result from a file deletion. I am not sure about list mode vs grid mode changes and @mauriel133 can chime in here.

I will defer the rest of issues described here to @mauriel133 for him to see what can be addressed here for 1.8 deploy since they all appear to be related to front end.

**Comment by horsburgh** [comment]
@dtarb - the cut and paste of files within the hierarchy is necessary now because we only have a simple list view and an icon view. I think this is sufficient for the first round of functionality.

For the next round, should we consider an expandable tree-like list view to better enable this? For example, something like:

![image](https://cloud.githubusercontent.com/assets/3485902/20145956/39f025e0-a65f-11e6-9962-df204325c744.png)

**Comment by dtarb** [comment]
Tested on beta.  Good!
