### ISSUE TITLE
HydroShare Landing Page Update before AGU

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#1554]
The HydroShare home page (www.hydroshare.org) needs to have more visibility for the Sign Up, What you can do, and How it Works so they can be seen from a mobile phone/small screens without scrolling.

@mauriel133 @horsburgh @dtarb 
At AGU - the laptops and mobile phones will be the main entryway for new users to HydroShare. 

More specific details or ideas to approach this:
Smaller picture
More prominent headers
Accordion style so that we can see the content without having to scroll.

**Comment by horsburgh** [comment]
@ChristinaB - I don't disagree with you, but this is quite difficult to accomplish. Most mobile responsive site layouts use scrolling. I don't think there's any way we are going to get all of that information (sign up, what you can do, and how it works) on one screen in your mobile device without making things very small (and by very small I mean unreadable and unusable). HydroShare looks and works great on my laptop, so we will see what we can do with the mobile layout.

**Comment by ChristinaB** [comment]
I want to follow up with the phone call points on this: 
We discussed

- [ ] Moving How it works up in the vertical layout

- [ ] Keeping Sign up always visible

- [ ] Keeping the picture as non-useful aesthetic.

Jon has more specific ideas as well.

**Comment by jtpollak** [comment]
I suggest the following:

- [ ] Hide My Resources link unless someone is logged in
- [ ] Create a new page for How It Works and remove current How it Works from home page
- [ ] Remove Sign Up button in the middle of the page --> Move this to top right so that it is Login/Sign Up
- [ ] Remove "Available on all your devices"
- [ ] Keep "What you can do with HydroShare" and some sort of image like the current carousel

**Comment by horsburgh** [comment]
@ChristinaB and @jtpollak - the following list is where I thought we ended up on the phone today after the main HydrsoShare call. I am reluctant to remove the "My Resources" link from the front page as we discussed this at length a long time ago and decided to keep it. Also, your recommendations about the "How it Works" are conflicting, so I would prefer to keep it on the main page and not have it be a separate page. See below for how we decided on the phone today to reorganize.

Some stuff that people want done on the HydroShare front page to address comments from users and CUAHSI. This is to make it so that the really important stuff shows up closer to the top of the page to minimize required scrolling to access it - especially on mobile devices.

 * [ ] 1. Move the "Join the community to start sharing" with the sign up button up on top of the rotating images (front, top, and center)
 * [ ] 2. Move the text messages that are now on the rotating images to below the images where the "Join the Community to start sharing" text and sign up button are now
 * [ ] 3. Swap the position of "How it works" and "What you can do with HydroShare"

**Comment by mauriel133** [comment]
@horsburgh, I have deployed the changes we discussed at http://testservices.hydroshare.org/

**Comment by horsburgh** [comment]
@ChristinaB and @jtpollak - @mauriel133 made changes to the HydroShare home page to address this issue. He deployed them at https://testservices.hydroshare.org/. Please have a look. If you are OK with these, @mauriel133 could get them reviewed and merged pretty quickly.

@ChristinaB - we can discuss when we chat on Friday morning if necessary.

**Comment by ChristinaB** [comment]
Reviewing it from a mobile phone I think it looks great. Nice work @mauiel133!!! However, I would weight Jons input more than mine because I don't qualify as a new user or a have as good of an eye for what new users may glitch on. I can say that it looks almost identical to the github mobile site, so you've succeeded at having an equally awesome design as them. @jtpkllak has a list of users text or "who uses HydroShare" text that could be refined to be similar to that element of the Github layout (as an example). I think this is what he was going for on the design element.

**Comment by ChristinaB** [comment]
Request-- I don't know the name of it, thumbnail? But the image used in the upper left that says "HydroShare" in block letters with the cuahsi logo is blurry. Is it possible to get. A higher resolution image? Or do I need glasses ?!!

**Comment by mauriel133** [comment]
I agree it looks blurry. I've been wanting to replace letters. Perhaps this is a good time to do it.

**Comment by ChristinaB** [comment]
Another note-when I search Github it autofills with the tag line 
GitHub- where software is built 
When I search HydroShare, it autofills 
HydroShare -- HydroShare 

Do we have a tag line? If not, can we find 4 words we like? What about 
HydroShare - where water research happens
HydroShare - where water research builds
Those aren't quite right. But after the cuahsi phone calls the past two weeks, I know it would be helpful, possibly critical for simple messaging at the booth and beyond.

**Comment by horsburgh** [comment]
@ChristinaB - a tagline we were using early on was simply "Share and collaborate"

**Comment by horsburgh** [comment]
@ChristinaB and @jtpollak - Muriel implemented a set of changes to address this issue. It is deployed as I showed @ChristinaB on the phone at http://testservices.hydroshare.org.  I'm going to have him submit a pull request to get these changes integrated.

**Comment by ChristinaB** [comment]
1. I like the landing page update. 
2. I'm good with 'Share and Collaborate'  for a tagline.
3. For the autofill- Google tagline, it still just says HydroShare   HydroShare


![image](https://cloud.githubusercontent.com/assets/4108369/20684721/10523e24-b566-11e6-939a-edbbb2089ce7.png)

**Comment by mauriel133** [comment]
I can update the autofill. Is 'Share and Collaborate' what should show up?

**Comment by horsburgh** [comment]
@ChristinaB - For Number 2 and 3, Google uses the "Title" element from the HTML page. Right now, this is set to " | HydroShare"

@mauriel133 is it possible to change the title element to " | Share and Collaborate"?

**Comment by mauriel133** [comment]
@horsburgh, yes. I can change the title accordingly to what we decide.
