### ISSUE TITLE
Implement file quota

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1566]
State the following policy on a policies page in pages.hydroshare.org, and implement it on the backend.

Each user receives automatically an allocation of 20 GB of space for their resources when they sign up.  Users who need more space should contact one support@hydroshare.org and explain who they are and why they need more space.  This request can be quite short and all reasonable requests will be approved subject to system capacity limitations, with preference given to users from CUAHSI member institutions and NSF funded hydrology research projects.  Large requests for space may lead to negotiation over an appropriate contribution towards the costs of providing the space requested, or configuration of capability for use of space at your own institutions server for your HydroShare resources.

Implementation.  An admin page is needed where an admin can go in and set the quota for a user.

**Comment by alvacouch** [comment]
@dtarb @mjstealey FYI: This is related to the ResourceFile reorganization #1687 , in the sense that it allows us to measure -- in Django -- the size of all resource files owned by a user.

**Comment by pkdash** [comment]
@hyi and @mjstealey I assume you both are working on this.

**Comment by hyi** [comment]
@dtarb @horsburgh @alvacouch Can one of you draft an email message for sending to users who have used up 90% or above of their allocated quota? I am close to get the first pass of quota implementation done on Django side. Then @mjstealey and I can work together to integrate @mjstealey's nightly script run with Django. I am writing an email_users management command to be called by @mjstealey's script, so it'd be great if you can draft an email message I can use to put into code before opening a PR for code review.

**Comment by dtarb** [comment]
I will write some text below.  But, I think we need an admin interface that allows administrators to change the texts of these emails.  The text should be pulled from a field in a database that is editable by an administrator, rather than in the code.  That way as policies and messaging changes, the text can be easily updated.

Message to be transmitted by email to user when their quota crosses the 90% threshold.  Send this email once triggered by the action that put them over quota.  Unless they go under quota and then over again, in which case they should get the message again.  The message should also appear at the top of any HydroShare page when they are logged in as long as they are over quota, similar to the way other messages from Django appear.  

Your quota for HydroShare resources is X GB.  You currently have resources that consume Y GB, Z% of your quota.  Once your quota reaches 100% you will no longer be able to create new resources in HydroShare.  To request additional quota please contact support@hydroshare.org.  We will try accommodate reasonable requests for additional quota.  If you have a large quota request you may need to contribute towards the costs of providing the additional space you need.  See https://pages.hydroshare.org/about-hydroshare/policies/quota/ for more information about the quota policy. 

Message to be transmitted by email and put at the top of the page in Django following an action that is refused due to being over quota.

Your action to add content to HydroShare was refused due to being over your HydroShare quota.  Your quota for HydroShare resources is X GB.  You currently have resources that consume Y GB, Z% of your quota.  To request additional quota please contact support@hydroshare.org.  We will try accommodate reasonable requests for additional quota.  If you have a large quota request you may need to contribute towards the costs of providing the additional space you need.  See https://pages.hydroshare.org/about-hydroshare/policies/quota/ for more information about the quota policy.

**Comment by alvacouch** [comment]
@dtarb @hyi We had a detailed discussion on the issue of quotas on the developer call. 

1. Other current practical quotas (e.g., how Linux does things) leverage a "soft limit" above which one can create files for a short time, which is usually 7 days. This is called a "grace period". At the end of the 7 days, the soft limit becomes hard and one cannot create any more files until one goes beneath the soft limit, which resets the grace period clock. 

2. The hard limit stops everything, even if the grace period has not expired. 

3. At Tufts, my soft limit is 75% of my hard limit. We were thinking that for HydroShare, the soft limit should be about 80% of the hard limit. 

4. The function of the soft limit is that it starts quota warnings. At Tufts, I receive two kinds: 
    a. email warnings for things to which I don't have direct access, e.g., my email inbox. 
    b. Per-login warnings for things to which I do have access, e.g., logging into a Tufts server. 

5. Analogously, this means that we should have:
    a. An email reminder -- per day -- whenever someone is over the soft quota, and an email warning when the soft quota becomes hard. 
    b. Warnings when logging in, on the initial landing page, that one is over the soft limit and what one's grace period is. 

Soft limits are a really good idea for several reasons: 
1. They warn the user ahead of time that a problem will occur. 
2. They give ample time to recover and clean up before shutting off service. 

There was also significant discussion on how quotas should interact with federated resources. It is the feeling of CUAHSI that these can potentially represent an unacceptable management burden if the only way to change quotas for a federated site is through our admin interface. This is especially true if a third party comes to us with much more storage than we own and wants it to be managed aggressively by giving people quotas incrementally according to need. We don't want to administer those. 

So, this means that we either need: 
1. An administrative interface specifically for federated sites or 
2. A REST call that can set quotas for federated users. 
(These are essentially the same amount of trouble.) 

CUAHSI doesn't have the staff to handle quotas for federated resources, and we would rather not advertise the service until there is a self-service option for this.

**Comment by hyi** [comment]
@alvacouch @dtarb I believe I have implemented everything @alvacouch mentioned above except for grace period in that PR. The underlying database schema takes into account the third party federated zone by making UserQuota class a foreignkey relationship to User class rather than OneToOne relationship so that more UserQuota records/instances can be added for a single User instance with each UserQuota instance corresponding to hydroshare_internal zone vs. external third party federated zone. @alvacouch You will know how I implemented this after you are done with code review. My implementation allows the hydroshare admin to manage third party federated zone if desired, but not enforce this, so if you don't add a separate UserQuota instance from admin interface to manage a separate federated zone, the quota management will only apply to the one single hydroshare_internal zone (i.e., hydroshareZone and hydroshareuserZone). My current implementation set the soft limit percent value to be 90% as @dtarb indicated above, but can be changed to 80% or any other value from admin interface. However, enforcement only happens for the hard limit as indicated by @dtarb above. If a decision is made to implement grace period clock and use soft limit for enforcement after grace period is over, it can be implemented but definitely introduce complexity especially with grace period count down. I will work with @mjstealey to integrate current implementation with Michael's script to close the loop and deploy it to alpha for you to test and get a feel on how it works, and then go from there.

**Comment by dtarb** [comment]
I agree with @alvacouch suggestions on softquotas and grace period.  With respect to resources stored on a federated zone I do not see a way to avoid some administrative burden, but agree we need to keep it practical and manageable.  Here are some suggestions

1. All resources and initial quota is by default in the HydroShare zone.
2. When an organization creates a federated resource they designate a user or set of users who can set quotas for other HydroShare users on their zone
3. Quotas on each zone (federated zones and the HydroShare zone) be managed through a table that for each user holds Quota (GB), Soft limit % (default 75 or 80%), Grace period (days, default 7).
4. The quota table for each zone be held in a HydroShare resource.  That way the sharing of it and management of who can access or edit it can be managed by HydroShare access control mechanisms, and the administrator of a federated zone does not have to be a special user.
5. The HydroShare resource that holds the quota table could also hold messages to be used inform users about quota exceedances.
6.  For owners that have quota on multiple zones the landing page on each resource should have a link giving an owner the option to move to different zone (this is something only an owner can do)
7.  For resources with multiple owners, the first owner that creates the resource is set as the initial quota holder when the resource is created, but any owner can change the quota holder to any other owner (a friendly owner trusts owner model, with quota only charged to one owner).
8.  The profile page of each user should summarize the quota status for each zone on which they have any quota.

There are probably other details to work out that I'd be happy to discuss and elaborate on if going in this direction seems a good idea.

**Comment by hyi** [comment]
@dtarb @alvacouch It appears grace period is desired, so I will try to implement grace period, which means we have to keep track of when the used quota starts reaching the soft limit so count down can be achieved. Also the user may clean up their storage so count down needs to be reset if the used quota falls below the soft limit after count down starts. It definitely introduces a lot of complexity, but I will try to implement it. @dtarb On your points No. 4 and No. 5, I am not sure I understand your point, but I don't want to make quota table subject to access control, currently it is only editable by admin. Quota warning and enforcement messages are already editable by admin. For your point No. 6, since we don't have external federated zone yet, I don't think it is worth the trouble to implement the option that allows users to move resources between zones, not at this point at least. For your point No. 7, I am not sure whether it is a good idea to allow any owner to change quota holder to any other owner, but if we decide it is a good idea to do so, it can be implemented. point No. 8 can be implemented. So in short, I will work on No. 8, and grace period implementation with No. 7 on hold until a decision is reached. This is enough functionality for the first pass implementation given the short time we have left.

**Comment by dtarb** [comment]
Points 4 and 5 deal with where the information about what quota's are are stored and managed.  I am suggesting that instead of setting up separate mechanisms that only administrators can access, which seems complex to me and requires us to designate administrators who do this, and manage these administrators when we get to federated zones, that we instead just use what we have already developed with HydroShare.  HydroShare resources can be shared, or not shared with users according to the access control system we have and like.  I am suggesting we keep the quota table in a HydroShare resource, and then we can just use what we already work with to manage any changes.

While we do not have external federated zones yet, the whole reason federated zones are being set up is to allow external expansion.  Perhaps 6 can be deferred for initial implementation, but not too long, and lets keep this in mind in the design.

On 7, we want a system that is easy to use.  We have a model where owners are empowered.  Owners have to be people you trust.  If you make another user an owner of your resource it is like giving them the keys to your house or your car.  They can do anything.  I think changing the quota holder is quite consistent with this model.

**Comment by hyi** [comment]
@dtarb Thanks for your clarification on points 4 and 5. I think my current implementation with UserQuota table with many-to-one relations with User table works well without much administrative burden. You can test it out when we have alpha ready for testing. I agree your point No. 6 is useful, but let's defer it to the next phase and keep this in mind in the design. On 7, I see your point, but also see some quota-specific subtle differences. For example, the primary owner who is also a quota holder for a resource added owner A, then the primary owner changed quota holder to owner A. Does the primary owner needs to get approval from owner A before changing quota holder to owner A? Owner A may not want to be the owner of that resource if he gets changed to quota holder since he is pretty tight on quota already. I think this introduces a major risk factor for people so they may be reluctant to be put as owner of a resource. However, we don't have invitation, notification, and acceptance feedback mechanism implemented for adding owners, so I think we should be very cautious on introducing this extra risk factor, which may not be what we want.

**Comment by dtarb** [comment]
Owners have to work it out among themselves socially, not programmatically.  I would like the system to be simple.  An owner can delete a resource if they need to get it off their quota so if another owner forces it on to them against their will, they just delete it.  This has to be sorted out by owners talking among themselves, not us building complicated checks in the system.  You should not make someone an owner of a resource you care about if you do not trust them.  The biggest risk factor is us building too complicated a system that it never gets built and confuses users so it never gets used.

**Comment by hyi** [comment]
@dtarb @alvacouch I am currently adding grace period into quota implementation and will have to modify the default warning and enforcement messages. Note these messages can be edited from admin interface, so getting them right initially is not critically important, but it'd be nice to get the default messages approved by you initially. Below are the modified messages. Let me know if you want to make any edits. 
Warning message:
```
Your quota for HydroShare resources is X GB in A zone. You currently have resources that consume 
Y GB, B% of your quota which has reached the soft quota limit. You have a grace period of 7 days to take actions to get your quota below the soft quota limit (80%). Otherwise, when your grace period is over, you will no longer be able to create new resources in HydroShare. To request additional quota, please contact support@hydroshare.org. We will try to accommodate reasonable requests for additional quota. If you have a large quota request, you may need to contribute towards the costs of providing the additional space you need. See https://pages.hydroshare.org/about-hydroshare/policies/quota/ for more information about the quota policy.
```
The enforcement message:
```
Your action to add content to HydroShare was refused because you are over 80% of your quota and your grace period of 7 days have passed. Your quota for HydroShare resources is X GB. You currently have resources that consume Y GB, Z% of your quota. To request additional quota, please contact support@hydroshare.org. We will try accommodate reasonable requests for additional quota. If you have a large quota request, you may need to contribute towards the costs of providing the additional space you need. See https://pages.hydroshare.org/about-hydroshare/policies/quota/ for more information about the quota policy.
```

**Comment by dtarb** [comment]
@hyi, I think there needs to be a warning before the soft limit, a soft limit (that we call the quota) and a hard limit that is 125% of the quota.  I suggest the following messages.

Warning (when over 80% of quota)
> Your quota for HydroShare resources is X GB in A zone. You currently have resources that consume 
Y GB, B% of your quota. Once your quota reaches 100% you will no longer be able to create new resources in HydroShare. To request additional quota, please contact support@hydroshare.org. We will try to accommodate reasonable requests for additional quota. If you have a large quota request, you may need to contribute towards the costs of providing the additional space you need. See https://pages.hydroshare.org/about-hydroshare/policies/quota/ for more information about the quota policy.


Grace period over quota (when over quota within grace period and less than 125% of quota)
> You have exceeded your HydroShare quota of X GB in A zone.  Your quota for HydroShare resources is X GB. You currently have resources that consume Y GB, Z% of your quota. You have a grace period until (insert date) to reduce your use to below your quota, or to acquire additional quota, after which you will no longer be able to create new resources in HydroShare.  To request additional quota, please contact support@hydroshare.org. We will try to accommodate reasonable requests for additional quota. If you have a large quota request, you may need to contribute towards the costs of providing the additional space you need. See https://pages.hydroshare.org/about-hydroshare/policies/quota/ for more information about the quota policy.

After grace period or more than 125%
> Your action to add content to HydroShare was refused because you have exceeded your quota. Your quota for HydroShare resources is X GB. You currently have resources that consume Y GB, Z% of your quota. To request additional quota, please contact support@hydroshare.org. We will try accommodate reasonable requests for additional quota. If you have a large quota request, you may need to contribute towards the costs of providing the additional space you need. See https://pages.hydroshare.org/about-hydroshare/policies/quota/ for more information about the quota policy.

**Comment by hyi** [comment]
@dtarb OK. I like your suggestions and will implement as such. The used percentage of quota (i.e., 80%) is editable from admin interface, but the 125% hard limit will be hard-coded (i.e., not editable from admin interface). Let me know whether this is OK with you. @alvacouch See if @dtarb's suggestion is in line with your thought.

**Comment by hyi** [comment]
@dtarb @alvacouch I decide to make hard limit 125% editable from admin interface in the similar way as the soft limit 80% as there may be needs to adjust these percentages over time.

**Comment by hyi** [comment]
@dtarb @alvacouch I have implemented allowing quota holder to change quota holder to another owner from resource landing page. However, if this quota holder owner is removed from access control by another owner, I assume the only reasonable action is to transfer the quota holder to this owner who is removing the quota holder owner. Do you agree?

**Comment by hyi** [comment]
@dtarb @alvacouch I took my suggestion above back. I think it'd be more reasonable just to disallow owners to delete a quota holder owner from manage access panel, in the same way as the only remaining owner cannot be removed. This makes more sense to me, so I will go with that for implementation.

**Comment by dtarb** [comment]
I am OK with all of this and look forward to a demo.

**Comment by alvacouch** [comment]
@hyi @dtarb @pkdash @mseul @aphelionz 

There is a generally better way to handle invitation/response than we are doing now. If we look at how Google Drive and DropBox do things, it should inspire us toward a different approach: 

1. An invitation is emailed to the user. There is no automatic UI generated for responding to the invitation. The email is the only notification. 
2. The email contains `accept` and `reject` links that link to REST calls. 
3. These links tell the user that the action has been accomplished. 
4. The links have a set timeout, e.g., one week. After that the invitation is deleted. It can of course be re-issued. 
5. Re-issuing a current invitation does nothing except email the user again. 
6. There's no "retract invitation" function. Invitations simply time out. 

It strikes me that: 
1. This is much lower commitment than building a UI for accept/reject. **This UI does not exist for DropBox or Google Drive**. Only the email invite exists. 
2. All we need is a UI for "invite" and for "request access". These are just buttons.  
3. This is in general a superior and faster way to manage group invitations as well and -- for that matter -- any kind of invitation.  Much less UI work is involved, and much faster notification of the user results.

**Comment by pkdash** [comment]
@alvacouch 

> All we need is a UI for "invite" and for "request access". These are just buttons.

For group the above UI is what we have (buttons) currently.

**Comment by alvacouch** [comment]
@pkdash As I understand things, the responding user has to deal with a list of invitations. That is what I suggest we might do away with.

**Comment by hyi** [comment]
@alvacouch @dtarb I think invite/response model for changing quota holders introduces delayed action and thus may involve a lot of more work than it appears for our current quota implementation. Specifically, we allow any owner to change quota holder to another owner which is based on "owners should trust each other and can do anything" principle. If we introduce invite/response for changing quota holder, consider this scenario: owner A tries to transfer quota holder to owner B, before owner B approves this, owner C tries to transfer quota holder to owner D, and owner D approves it before owner B, so the quota holder is transferred to D, then owner B approves it also, then owner B gets the quota holder status. We can add in more constraints such as not allowing changing quota holders when a invite request is pending, but as you can see, implementing this invite/response model is more involved in order to accommodate more potential scenarios to make it work. Given that, I'd go with simple email notification at least for now given the time constraint. 
@dtarb Can you draft email notifications for adding owners and changing quota holders, especially for changing quota holders. I think we should tell the user in the notification email that owner A has transferred quota holder to you for a resource, and if you don't approve, you can contact the owner A, or  ...  I'll add email notifications after I see your draft.

**Comment by hyi** [comment]
@dtarb @alvacouch I decided to only send email notification when a user has been changed to a quota holder for a resource, but not to send email notification when a user is added as an owner of the resource for the first pass for the sake of consistency. I think the notification for access control needs to be thought out as a whole including add an owner to a resource, demoting an owner, adding a user as editor, demoting an editor, etc. It does not make sense to me to only send email notification for adding an owner, but not for other access control changes. So I think for the first pass, I'll just implement email notification for quota holder change, but leave other email notifications to a separate work that needs to handle access control notifications as a whole including adding authors and contributors which has already been detailed in this issue: https://github.com/hydroshare/hydroshare/issues/975

**Comment by alvacouch** [comment]
@hyi @pkdash I would rather that all of the logic for quota were inside hs_access_control rather than depending on fields in *Resource.  So far, there are no dependencies in access control upon fields in other places. This would allow me to continue to debug access control without having to load the resource model to do so, and will keep access control a plug-in module that can be reused in other places the same way.  I estimate that debugging access control in this way is 100 time faster than debugging it in situ inside HydroShare. 

The way it's written now, with policy logic references to BaseResource.creator, hs_access_control is now inextricably coupled to the resource model ... which is exactly what I wanted to avoid.  

Fixing this would mean adding a field quota_user that is a Foreign key to User inside the ResourceAccess class.  Then the logic for maintaining this field could be embedded inside access control without having to know the details of *Resource. Then, the logic for all of this -- including email notifications, REST responders, etc -- could be embedded in access control where it seems to belong, without coupling data from access control with data from other places. User.email would be the only coupling....

I can assist with this if you wish. 

In general, I have tried to keep access control "orthogonal" to the other systems, in the sense that there is no coupling except through the API. This makes it much, much easier to update it without messing up other things. This is part of why access control is implemented through an external class system rather than being embedded inside BaseResource.

**Comment by hyi** [comment]
@alvacouch I understand your point trying to keep access control "orthogonal" to the other systems, however, in this special quota case, accessing resource to retrieve quota holder is needed since the quota holder information is only kept as an AVU pair on the resource collection in iRODS, not in Django, which is intended to avoid duplicate information on Django and iRODS side. Since this quota holder info is needed by @mjstealey's script, it needs to reside in AVU pair in iRODS for the resource collection, and the method get_quota_holder() and set_quota_holder() on BaseResource instance are just convenience methods to get/set AVU pairs in iRODS. Since access control system is for applying access control to some target, in our case, HydroShare resources, attaching quota holder to the access control target may be an acceptable model. For example, if access control system is used for other system target, that new target just need to provide two convenience methods, get_quota_holder() and set_quota_holder(), which encapsulate the internal implementation details from access control system. In our case, we use iRODS AVU, but for another target, whatever implementation can be used without depending on iRODS, access control system just depends on the two API convenience methods. That said, if you want to improve it further, you are welcome to do so in the next iteration after this quota implementation is deployed. Hope this makes sense to you.

**Comment by pkdash** [comment]
@alvacouch and @hyi 

> Fixing this would mean adding a field quota_user that is a Foreign key to User inside the ResourceAccess class. Then the logic for maintaining this field could be embedded inside access control without having to know the details of *Resource. Then, the logic for all of this -- including email notifications, REST responders, etc -- could be embedded in access control where it seems to belong, without coupling data from access control with data from other places. User.email would be the only coupling....

I agree there may be some value using ```quota_user``` field in ResourceAccess class. However, if we move the responsibility of maintaining this field to access control that would create more coupling between access control and hs_core in particular unnecessary dependency  related to iRODS. I am also not sure about access control being responsible for email notification - more coupling. I would prefer hs_core to maintain the ```quota_user``` field in ResourceAccess class and access control to only act (allow or disallow certain actions) depending on the status of this field.

**Comment by alvacouch** [comment]
@hyi @pkdash I am willing to settle for changes to the quota_user from outside, because that does indeed satisfy my concerns. My main concern is that the deep logic of access control needs to be based upon fields contained inside access control. It's difficult to debug future features if that control reaches outside the module. 

However, there is an argument for having the state machines for various invite-accept protocols -- especially those that involve email/REST exchanges -- inside access control, because it actually has the knowledge to implement these transactions completely and in isolation from the rest of the system. Thus these state transitions are easier to write and debug :) Tests take a few seconds rather than up to 40 minutes, because I don't have to fire up and populate the resource models in order to test them!

**Comment by alvacouch** [comment]
@hyi it is going to be quite difficult for me to move the quota_user from Resource to ResourceAccess after the fact. This will require a data migration involving a live iRODS.

**Comment by hyi** [comment]
@alvacouch The current implementation does not have quota_user field on Resource model in Django, so there will not be data migration involved on Django side. I prefer to have quota user stored as AVU metadata on iRODS side, and retrieve quota user on Django side when needed to avoid duplication and to have single point of truth.

**Comment by ChristinaB** [comment]
Suggesting an update:  What about something shorter and more direct.

Development Update: User storage is 20 GB. Visit our Quota Policy Help page to learn more.

**Comment by cuahsimarko** [comment]
@phuongdm Please close or comment.

**Comment by phuongdm** [comment]
Yes, it's done
