### ISSUE TITLE
Square up app icon layout

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1569]
Make icon height/width more consistent.

**Comment by danames** [comment]
The simple solution to this is to use a consistent name and icon size for each app so that they naturally are the same size. Forcing irregular sized boxes into a grid layout would require a negotiation with the Tethys team which is resistant to the idea, citing other web apps and sites that allow sizes of icons to vary.

**Comment by danames** [comment]
@zhiyuli Drew, can we easily change the names and icons of our apps to a standard size so that the apps in the portal are laid out more consistently? Can we assign this to Tylor who is just joining our lab now? Will you please talk to him about it?

**Comment by dtarb** [comment]
This is no longer needed with new apps landing page
