### ISSUE TITLE
Include current python-irodsclient in dev build configuration 

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1590]
Two years after python-irodsclient became usable, we are still using an iCommands interface to iRODs. The python-irodsclient used in iPlant is now usable and the python-irodsclient methods work roughly **twice as fast** as using iCommands wrappers. 

We should include the current python-irodsclient in the build and gradually migrate to using it where practical. 

Not absolutely everything can be handled through python-irodsclient, but the things that can be handled are better handled by it. **Using iCommands requires substantial operating system overhead** to fork commands that is not required by python-irodsclient.

**Comment by mjstealey** [comment]
> The python-irodsclient used in iPlant is now usable

We've been using the older [iPlant python-irodsclient](https://github.com/iPlantCollaborativeOpenSource/python-irodsclient) in our stack for quite some time for various aspects of the project. The version we've referenced has been in play since [Sept 17, 2014](https://github.com/iPlantCollaborativeOpenSource/python-irodsclient/commit/dcd234c166c06bdfc40fa2ef135c2511e0a4e7ac)

iPlant has since become CyVerse and the development of the python-irodsclient has been removed from the CyVerse side and handed back over to the iRODS team at: [https://github.com/irods/python-irodsclient/](https://github.com/irods/python-irodsclient/) 

I've looked into updating the version we point to and have hit some errors along the way. Will need to consult with others regarding what's been found with the hopes of having a resolution to the updated pointer by the 1.9.0 AGU release.

**Comment by hyi** [comment]
@alvacouch @mjstealey I had consulted with Antoine in iRODS team who is in charge of python irods client when I brought in python irods client into HydroShare and he advised me to use that older version from iplant rather than the iRODS team version due to many upcoming changes being involved in which could result in API changes along the way. In fact, I only used python irods client for listing files and folders for iRODS file browser. Antoine also advised me not to use python iRODS client for file transfer since parallel transfer is not supported in python iRODS client. In short, Antoine approved the way we are doing right now, i.e., use python irods client for iRODS file browser without involving any file transfer operations, but use icommands for all file related operations which supports parallel file transfer, hence has fast performance. Unless there are specific reasons we need to change the current implementation, I think we don't need to change what we are currently doing.

**Comment by cuahsimarko** [comment]
@phuongdm Please close or comment.

**Comment by phuongdm** [comment]
Not sure about this issue, need confirm from @hyi or @alvacouch

**Comment by martinseul** [comment]
@hyi is this still relevant or can it be closed?

**Comment by hyi** [comment]
Already addressed. Closing.
