### ISSUE TITLE
Versioning Problem with SWAT and MODFLOW MI's

### ISSUE THREAD

**Issue by jsadler2** [hydroshare/hydroshare#1601]
When a multi-choice checkbox is selected in either SWAT or MODFLOW Model Instance resource, if the user tries to create a new version of the resource, it fails with "Failed to create a new version of this resource: argument of type 'int' is not iterable" (see screenshot)
![image](https://cloud.githubusercontent.com/assets/6943441/20402192/b88ee718-acc9-11e6-9d87-d797eec28e82.png)

**Comment by jsadler2** [comment]
@hyi, from your work on the versioning, do you have any idea why this error is happening?

**Comment by hyi** [comment]
@jsadler2 It looks like this error happens when trying to copy MI-specific metadata elements from the old resource to the new versioned resource. You can debug and see where the error occurs, and I am positive the error is caused by some MI-specific metadata element related method since it does not happen for other resource types. Let me know if you find any issue with versioning code, though.

**Comment by jsadler2** [comment]
@hyi @zhiyuli we discovered that this is a problem in the 'apps' resource too (see below)
![image](https://cloud.githubusercontent.com/assets/6943441/20404102/73b838ee-acd1-11e6-8aa7-adc3cc83b82c.png)

I think that any resource using a multi-choice checklist (i.e. a many-to-many relation in the model) will have this problem making a new version of a resource.

**Comment by hyi** [comment]
@jsadler2 OK. I will look into this when I get a chance. Since this is not a regression issue, it is not a blocker for release 1.8. I will try to see if I can resolve this issue for the AGU release.

**Comment by jsadler2** [comment]
@hyi we were able to fix a bug that was unique to the modflow model instance in commit c94be87. We will do a pull request for this which shouldn't take long and should be merged before you work on this. Based on our investigation, the more generally problem is happening in line here: https://github.com/hydroshare/hydroshare/blob/develop/hs_core/models.py#L1851 and more specifially in the "model_to_dict" function which seems to be returning an integer representing the term instead of the term itself which is a string.

**Comment by hyi** [comment]
@jsadler2 @mohamedmorsy I started to work on this issue and confirmed Django's ```model_to_dict``` returns a list of pks (primary keys) for ManyToManyField.  Here is the comment coming directly from Django's ```model_to_dict``` function: ```# MultipleChoiceWidget needs a list of pks, not object instances.```. So Django ```model_to_dict``` function actually returns this list of pks intentionally for easy of handling in MultipleChoiceWidget. Any idea on whether you can change modflow model instance ManyToManyField widget to use pk integer rather than a string value to set the boundary condition ManyToManyField choice?

**Comment by hyi** [comment]
@jsadler2 @mohamedmorsy I'll leave this issue for you two to investigate first to see if you can use list of pks in your boundary condition ManyToManyField choices when creating such metadata elements since it appears Django ```model_to_dict``` intentionally returns this list of pks for easy of handling in MultipleChoiceWidget form. So it appears to me using list of pks may be best practice we need to go for. Hopefully you can get this issue worked out.

**Comment by jsadler2** [comment]
@hyi I found a way to append the descriptions instead of the primary keys by making a modified version of the ```model_to_dict``` method. Please review this and comment whether you think this is a good resolution to the problem

**Comment by jsadler2** [comment]
the solution to this bug has been merged to develop
