### ISSUE TITLE
Need a right click menu on files to launch apps

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#1609]
This is probably a task for @mauriel133. When a user right clicks a file, any apps that have been registered to that file type should appear in a right click "Open With" menu. This should follow the same approach as the current resource level "Open With" menu in terms of formatting a URL string that launches the app with any customized URL string parameters. The only difference is that instead of passing the resource ID only, you will pass the resource ID AND the file ID. We already have a working ability to RECEIVE such an app launch in HydroShare GIS. @shawncrawley will post a note to this issue indicating the specific format of the URL string.

**Comment by shawncrawley** [comment]
Here is an example URL endpoint for HydroShare GIS that will launch a specific file from within a resource:

https://apps.hydroshare.org/apps/hydroshare-gis/?res_id=74a0ffbcff494cb985b061b3fc14f2f2&res_type=GenericResource&res_fname=UtahLake.jpg

It uses the res_fname parameter. However, I'm leaning more towards changing that parameter to just res_file, instead of res_fname... But for now it is res_fname. Any thoughts on that?

**Comment by danames** [comment]
Actually in our current model, the app developer can use any variable name they want in the URL string (res_file or res_fname, etc). That is specified by the app developer. The only thing that matters is the variables that are specified in the URL which can include:

${HS_RES_ID}
${HS_RES_TYPE}
now we need to add
${HS_RES_FILE}

For example for SWAT Share the URL is specified like this:
https://mygeohub.org/groups/water-hub/swatshare?src=hs&res_id=${HS_RES_ID}&op=run

at run time, the "Open With" button replaces ${HS_RES_ID} with the resource id of the resource that launched the app. 

For HydroShare GIS it is like this:
https://apps.hydroshare.org/apps/hydroshare-gis/?res_id=${HS_RES_ID}&res_type=${HS_RES_TYPE}

at run time the "Open With" button replaces both ${HS_RES_ID} and ${HS_RES_TYPE} with the resource ID and type. 
 
So to specify a specific file within a resource one would simply embed the ${HS_RES_FILE} variable in the app definition. 

Shawn's example file launcher URL would then look like this:

https://apps.hydroshare.org/apps/hydroshare-gis/?res_id=${HS_RES_ID}&res_type=${HS_RS_TYPE}&res_fname=${HS_RS_FILE}

So... @mauriel133  and @horsburgh. If you guys were to make this small change in the file explorer all you would need to do is 

1) When user right clicks a file, check which apps are associated with that file's file extension and list them in an "Open With" menu
 2) When a user clicks one of the apps to launch it, you replace ${HS_RS_ID}, ${HS_RS_TYPE} and ${HS_RS_FILE} with the appropriate values and launch the URL. 

@mauriel133 and @horsburgh we could try to add this code here at BYU @zhiyuli  could do it. But I'm afraid to mess around in your file/folder viewer. What do you suggest?

**Comment by pkdash** [comment]
@danames 

> When user right clicks a file, check which apps are associated with that file's file extension and list them in an "Open With" menu

Does our current implementation has the ability to associate a web app with a file type? If not then that needs to be implemented first before @mauriel133 can work on the front-end changes as needed by this issue.

**Comment by Maurier** [comment]
@aphelionz could you guide me through the work on this. Do we have a way to associate file types and web apps now? If so, where can I find the URL syntax?

**Comment by aphelionz** [comment]
Also a question for @alva and @pkdash

**Comment by dtarb** [comment]
This is a question for @danames @zhiyuli and the data model for the app resource type.  This is a bit of a chicken and egg situation as the URL pattern needs to use information from new fields in the app resource.  Issues #1609, #1161 and this need to be coordinated.

**Comment by zhiyuli** [comment]
@dtarb @danames 
I just got my HS dev environment working again (have been working on NWM Tethys apps in the past months) and I am learning Pabitra's implementations of "file-type" and "composite res". Should be able to pick up WebApp Res work very soon.

**Comment by pkdash** [comment]
@zhiyuli Let me know if you have any question related to file type as you try to link file types to web apps.

**Comment by dtarb** [comment]
@danames @zhiyuli, @pkdash is available to help with this so please coordinate what is best for him to do versus @Maurier and @zhiyuli

**Comment by danames** [comment]
Hi all, thanks for all the discussion on 1609. At the moment we're going to
have @zhiyuli take the lead on this. He will coordinate with @pkdash.
Ultimately we'll pass our UI design through @Maurier for input and
improvement. Hope this will work... - @danames

**Comment by dtarb** [comment]
Email from @danames 10/25/17

From: Dan Ames [mailto:dan.ames@byu.edu] 
Sent: Wednesday, October 25, 2017 2:27 PM
To: dev@hydroshare.org; Pabitra Dash <pabitra.dash@usu.edu>
Subject: [HydroShare-Dev] Following up on open with discussion

The file-based open with click, launches an app using a URL pattern the app developer specifies.

There is an option to include variables in the app launching URL pattern:

Existing Variables:

1) HS_RES_ID this is the resource ID of the resource the file is part of.
2) HS_RES_TYPE this is the type of the resource
3) HS_USER_NAME this is the user name, but should not be avoided

New Variables for file based app launching:

4) HS_FILE_TYPE this is the type of the file the user clicked
5) HS_FT_FID this is the ID to the file type instance - the topic of a lot of our conversation today. Here's more explanation of it

Pabitra implemented file types such that he has a global counter in HydroShare that increments every time someone makes a new file of a certain type. Each file type has its own global counter. In Drew's demo, his netcdf file came up with ID =1. That is because he was working on his local instance of HydroShare. However in HydroShare proper there are likely to be many NetCDF instances. It doesn't matter who created it, or what resource it lives in, they all have a unique identifier. In other words, David may own NetCDF files 1-100. Drew owns 101, I own 102 through 150, etc. These unique identifiers are the most efficient method to quickly find a file instance in HydroShare and they don't every change once they are assigned. Because of this, we'll probably continue to use these numbers to identify file instances in HydroShare during an app launch.

The real problem here: we need to have file instance based access via API. This does not exist yet. Also when it is implemented, we need to have a means to confirm the ownership of the file that is requested by an app via API.

Sorry of this is a bit too detailed or esoteric for many of you, but I just wanted to clarify a bit about these ID's. Having said that, perhaps, Pabitra would want to change how he identifies file instances in HydroShare, or perhaps he could give us a function call that we could use to convert Local File Path/Name to his Global ID. Then it would make sense to change the App launching pattern to include File/Path name....

Thoughts?

**Comment by dtarb** [comment]
I am not supportive of a new unique file type numbering system.  Also, as you note, it needs a new API.  I suggest instead just using the API we already have.  For example you can access a file in a file type in a composite resource like
http://www.hydroshare.org/resource/64fb0a478974411caea3335e2d07975c/data/contents/logan/logan.tif

The system already delivers files like this.

**Comment by zhiyuli** [comment]
One FileType instance includes all required "component files" to compose a
specific FileType, and is assigned with one Logical FileType ID.
Do we want apps to able to download one FileType instance (say
GeoFeatureFileType: *.shp, *shx, *dbf) from a composite resource instead of
the whole resource bag?
If yes, we should use this Logical FileType ID as it refers to all
"component files".

**Comment by horsburgh** [comment]
It would be great to hear from Pabitra. As we discussed on the call today, it seems like it would be better to reference files by name. We already have API functionality for this, including access control and authorization. But we do have the challenge that referencing an individual file may not reference all of the needed files that make up  a “logical file” like a geographic feature dataset (shapefile).
 
In our current implementation, the files making up a “logical file” are grouped within an element within the science metadata called a “dataset”, so we are storing the association among the files in a “logical file”. However, I don’t know if we have any REST API functionality for exposing this in a way that one can retrieve a list of all of the files contained within a “logical file” through the REST API. The global counter described by Dan is only stored in Django and isn’t part of the resource map or science metadata (that I know of) - so I'm doubting it would be part of our API. One could likely achieve the same functionality to get a list of all of the files contained within a "logical file" by passing in one of the file names within that "logical file" versus passing the global counter for the "logical file".
 
Pabitra – do you have thoughts on the best way to access a “logical file's” content (i.e., all of it's files) from a composite resource via the REST API so it can be launched into an APP?
 
I could see it happening this way:
 
1. A user right clicks on a file within a composite resource (e.g., a .shp file or a .nc file) to launch it into an appropriate app
2. A URL is constructed according to the pattern that Dan highlighted – except that instead of using the HS_FT_FID the URL would pass the file name.
3. When fielding the request in the URL, the APP can determine the type of file based on the HS_FILE_TYPE so it knows whether it needs to retrieve only the file in the URL or all files that participate with the file in the URL as part of its “Logical File”
4. The APP sends a request to the HydroShare REST API to retrieve a list of files associated with the file in the URL (e.g., the list of all files in the “Logical File”) – not sure if this exists yet in our API
5. The App then retrieves each of the files in “logical file’s” list of files via the existing REST API.
 
Not sure about 4 and 5.

**Comment by pkdash** [comment]
@horsburgh 

A web app can either pass the logical file type and its ID, or the full path of one of the files in the logical file group to get a list of files in that file type. We need to decide which one we prefer. We don't have at this point a REST endpoint (#4 of the user step) for the web app to make that call. We have the REST API for item#5 which is retrieving any file from HydroShare and that has nothing to do with file type.

The other REST API I think we need soon is to retrieve all metadata (in json format) for a given file type instance.

**Comment by horsburgh** [comment]
Given that the logical file IDs are only stored in Django, my vote would be to use the full path of one of the files in the logical file group. But, whether we use the file path or logical file ID (or potentially both?), it looks like we would need to have at least one new REST API endpoint to get the list files in a logical file by passing in a logical file ID or the full path of one of the files in the logical file. The existing file retrieval endpoint could then be used to retrieve the individual files (which I think is preferred because it already exists and already implements access control and authorization).

I agree that it would be useful at some point to have a REST endpoint to retrieve the metadata for a logical file.

**Comment by danames** [comment]
I still am a bit uncomfortable with automatically moving my files into a folder. I can't think of any other operating system that would do this. All other OS's leave the files where the user puts them. Likewise, I can't think of any other OS that would require the right-click-set-as-geographic-feature step. Other OS's just see the files there and know that they are of a certain type based on file extension(s). Even ArcGIS doesn't require you to mark a shape file as such before you can use it. It just sees the shp/shx/dbf together and logically groups them and only shows one file. 

Can we implement this approach instead?

**Comment by horsburgh** [comment]
@danames - there's a whole bunch of discussion here about launching files within a composite resource into an app (and a bunch of other stuff). I believe that this discussion is superseded by the new composite resource functionality and issue #2576 which hasn't been implemented yet. Can we close this older issue and instead focus on #2576?

**Comment by aphelionz** [comment]
@danames @horsburgh is this close-able as a duplicate or part of 1.16?

**Comment by horsburgh** [comment]
I think we need to @sblack-usu to comment here because I believe he's been working on this. I hope the answer is yes, this will be addressed by the new composite resource functionality for 1.16.

**Comment by dtarb** [comment]
@sblack-usu is addressing this in PR #2767
