### ISSUE TITLE
Resource type specific restrictions for file and folder operations need to be implemented at the back-end level

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#1618]
Presently these restrictions are implemented at the front-end level only.

**Comment by alvacouch** [comment]
@pkdash Please be more specific. Obviously, the REST API will have to embody these restrictions. Are you saying that the primitive API requests upon which the REST API is based should understand the limitations, or should the REST API understand the limitations?

**Comment by pkdash** [comment]
@alvacouch The primitive APIs should understand these limitations.

**Comment by alvacouch** [comment]
@pkdash Please note that some of my REST code intentionally bypasses the primitive APIs -- because it can -- and this limits the amount of coding I have to do, sometimes substantively. Limitations are instead coded directly into REST as overrides of generic Django REST class methods. This is especially true when the primitive API deals with a Django object instead of a file... but it is also potentially true in parts of the file/folder API, especially when manipulating the `ResourceFile` object. 

In those cases, **using the primitive API is a waste of time** and I have -- accordingly -- not done that. 

So, the fact that the REST API honors restrictions is not sufficient evidence that the primitive routines honor them as well. 

In like manner, I have given some thought to solving this problem the other way, by replacing selected primitive API routines with their REST equivalents through the internal "Client" library, which for me would be an **easier way to enforce these restrictions than by hard-coding them into the primitive routines...!** This has virtually no performance penalty because the REST request is never made. Instead, the equivalent software is called directly without making a request at all. This is a Django recommended practice. 

Ostensibly, the reason for this practice is that **internal and external methods are prevented from disagreeing on limitations,** which removes one potential point of failure.

**Comment by pkdash** [comment]
@alvacouch 

> In like manner, I have given some thought to solving this problem the other way, by replacing selected primitive API routines with their REST equivalents through the internal "Client" library, which for me would be an easier way to enforce these restrictions than by hard-coding them into the primitive routines...! This has virtually no performance penalty because the REST request is never made. Instead, the equivalent software is called directly without making a request at all. This is a Django recommended practice. 

Can you point me to some Django documentation to the above?

**Comment by hyi** [comment]
@alvacouch Here is the link you can refer to when implementing the rule enforcement in backend in the same way as done for the UI: https://docs.google.com/spreadsheets/d/1tc-6tIq_YkJpa2CGj5tAEHMaLOZV2i3W10lokBCJAn0/edit#gid=0

**Comment by pkdash** [comment]
@hyi and @alvacouch 

The folder operations should not be checked whether it is allowed or not at the backend the way the UI checks. I am guessing it has to be done using signals. For composite resource type, I am using a signal to validate what folder/file move/rename is allowed. This signal is fired from the move_or_rename_file_or_folder() prior to taking the actual action. Remember this also needs quite a bit of unit tests that need to be added to each resource type.

**Comment by alvacouch** [comment]
I am for making the actual limits as explicit as possible in the proxy classes. E.g., 

@property 
def supports_folders(self): 
    return True 

The default would be False.

**Comment by pkdash** [comment]
@alvacouch 
This is the way I am doing in file type (LogicalFile) by defining these type of properties.

**Comment by alvacouch** [comment]
@pkdash See the documentation on the Django "Client" library, which invokes a REST call without REST overhead. This is the call that is used to replace internal functions with REST functions, among other things. It completely bypasses the actual REST mechanics, and is thus suitably fast.

**Comment by alvacouch** [comment]
@pkdash @dtarb @mauriel133 @horsburgh 
This is going to be a general theme in all REST programming in hs_core. Much of the application logic is encoded at the UI level. This is not limited to folders. The key problem is that **the resource models have no concept of capabilities of each kind of resource**, in the sense that things that should not be possible -- or should be possible -- are documented only in code and not in the data structure.

Somehow, I need a map of the UI logic and what it allows and does not allow. Otherwise there will be chaos.  A set of flags like the above -- edited into the various resource types -- would be a beginning.

**Comment by alvacouch** [comment]
@hyi In the [referenced spreadsheet](https://docs.google.com/spreadsheets/d/1tc-6tIq_YkJpa2CGj5tAEHMaLOZV2i3W10lokBCJAn0/edit#gid=0), what do YES(*) and YES(1) mean in the last column?

**Comment by hyi** [comment]
@alvacouch I believe YES(*) means the specific resource type allow one or multiple file upload with multiple file upload not in a normal sense. Specifically, raster and feature resource types allows to upload one zip file that contains multiple geotiff files for raster and multiple files for feature, respectively, in which the zip file is unzipped locally and extracted multiple files are added to the resource as appropriate. This is just my understanding, I am looping @horsburgh and @mauriel133 in to get definitive answer since they created that spreadsheet when doing UI work for folders.

**Comment by alvacouch** [comment]
@hyi @horsburgh @mauriel133 Another question about the spreadsheet: why would not keeping an extension be allowed?

**Comment by alvacouch** [comment]
@hyi @horsburgh @mauriel133 At first glance, preventing a resource from being zipped doesn't seem necessary. Why is this done?

**Comment by hyi** [comment]
@alvacouch @horsburgh @dtarb The spreadsheet was decided by the whole team. As I remembered, for some specific resource types, zipping is not preferable and they want to disable zipping. For extension renaming, I agree it is risky and probably better not to allow it, but apparently renaming file names are desirable, and it is hard to set up all the rules to determine which extension changes should not happen and which ones are legitimate, so the decision was, as I remembered, leave it to the user's discretion, as what is done by operation systems - extensions are allowed to be changes, but a warning will be presented to the user when extensions are changed.

**Comment by horsburgh** [comment]
@alvacouch, @hyi, and @dtarb - the functionality matrix is one of the biggest reasons why the folder interface took so long to implement.  Yep - there's a lot of resource specific logic there. We discussed that table as a group on the call and that's what @mauriel133 implemented. If use tells us we didn't get it right the first time, we can reconsider some of what is in that matrix.

**Comment by pkdash** [comment]
@alvacouch and @hyi Wondering if this issue has been addressed?

**Comment by hyi** [comment]
@pkdash I think it has been addressed, but I may be wrong, so will leave it to @alvacouch to see whether it has indeed been addressed and can be closed.

**Comment by alvacouch** [comment]
This is a very complex issue that is only partly addressed. It is addressed enough for the purposes of release 1.10. It is not generally addressed quite yet. The main pain points have been coded, but there remain subtle differences between frontend and backend coding that have not been addressed. 

* The part that has been addressed is that there are now capability flags in the resource template that code part of the front-end logic that should be coded on the back end. 
* There are also other (small and subtle) states that are not addressed by these flags. This occur inside specific resource types.

**Comment by alvacouch** [comment]
I think I'll close this issue, as the main things are being handled, and open other issues for the subtleties, as needed.
