### ISSUE TITLE
Transfer of group privilege to user that persists if group privilege is revoked 

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1622]
@dtarb @pkdash @mauriel133 There remains after PR #1576 a confusing behavior in the access control system that showed up in tests. Access granting at the User level is tempered by existing access privilege at both Group and User levels. Thus the following curious behavior is possible: 

1. Another user puts user Garfield in group Cats. 
2. Another user shares resource CatFood with Cats at CHANGE privilege. 
3. (now Garfield has CHANGE privilege over CatFood.) 
4. Garfield requests VIEW privilege for self over CatFood. This is granted because: 

    a. Garfield holds CHANGE privilege (via the group). 
    b. The new privilege is VIEW. 
    c. Thus this request is interpreted (incorrectly) as a self-downgrade. It is actually a self-**upgrade**. 

5. Another user unshares group Cats with Garfield (e.g., due to eating too much lasagna :) 
6. Garfield retains the self-granted individual privilege VIEW over resource CatFood. 

This is the only case that actually works curiously. Other cases are prevented by access control rules. 

* Garfield cannot grant CHANGE privilege to self due to the non-idempotence rule.
* Likewise, Garfield cannot hold OWNER via group permissions. 
The quandary comes because this is inconsistent with sharing with other users that are not in the group. One can share with these users without restriction. So, curiously enough, the user cannot do something for self that the user can do for others.  

As an example, while in the group Cats, Garfield is allowed to share CatFood with Sylvester at privilege CHANGE, because Sylvester is not in the group Cats. This is an individual share. 

This has been possible in the access control system for a while. I am unwilling to change this behavior without coordination with the UI. I am not aware of what a change will do to the UI. 

Preventing this subtle breach of sharing semantics is actually tricky. Here are the options:  

1. If we base individual sharing only on user privilege -- without group privilege -- the user will become unable to share a group-accessible document with an individual other than by adding that individual to the group. This seems counter-productive. 
2. If we prevent individual sharing for things that have already been shared via group, then this prohibits differential privileges for specific members, e.g., assigning OWNER for a member of a CHANGE group. 
3. We could prohibit sharing with a member of a group at a privilege greater than or equal to group privilege. This would allow the use case of increasing someone's individual privilege but would not allow redundant grants to individual members. 
4. If we base individual sharing on unrestricted user and group privilege, we must base the ability to self-share upon cumulative privilege of grantor and self privilege of grantee, consistent with what would happen if sharing with other users outside the group. Thus, Garfield would be able to share CatFood with self at CHANGE privilege, regardless of the fact that Garfield is already in the group and already has CHANGE privilege due to the group. And that share would persist even if Garfield is thrown out of the group. 

I advocate the last option (4). It's easy to implement, doesn't force more states into the system, and I think it promotes sharing and makes things easier, that users can already otherwise accomplish via copy-and-reshare. 

Your thoughts?

**Comment by pkdash** [comment]
@alvacouch The access control policies are too complicated for me. After reading all your examples above few times I am not sure I understand the issue that you want to resolve. Probably I need a whiteboard.

**Comment by alvacouch** [comment]
@pkdash Let me make it simpler. 

1. Should a user who is granted a group privilege be able to set individual privileges for others based upon that privilege? In other words, can one set individual privileges that persist even if group privilege is revoked?  
2. If the answer to that is "yes" -- and it is currently "yes" -- then should that same policy apply to self-privilege? Should I be able to give myself a privilege that is equivalent with my group privilege and persists even if I am removed from the group?

**Comment by alvacouch** [comment]
@pkdash (I already implemented a version of the revised semantics in the previous comment, but threw it away because I didn't know what it would do to the UI. Then I realized that it was symptomatic of a deeper problem. I still have the code in a local branch.)

**Comment by alvacouch** [comment]
As an aside, provenance-based revocation is a bit more extreme. Suppose that I am a "Bad Person" and grant all kinds of inappropriate privileges to people -- essentially turning any local privilege into a global privilege -- sort of like a HydroShare version of WikiLeaks. The system remembers what I have done, and could potentially revoke all privileges that I granted by reference to the Grantor field. 

As a more subtle option, it is possible to record enough information in the provenance to allow me to revoke privilege based upon a specific revocation, e.g., the fact that I was a member of a group and am a member no more. This would require recording a bit more provenance in order to accomplish that, e.g., what group(s) contributed to my ability to share. Then one could -- in principle -- revoke all sharing I had done in the group's name when I was removed from a group. 

I think this description is sufficient proof that this is messy and should be avoided.

**Comment by pkdash** [comment]
@alvacouch I would not use 'provenance' information in code logic if possible. Provenance should be used only for historical information tracking. Otherwise, I fear the access control code is going to be more complex.

I was wondering if the following would resolve the issue above (and probably make access control system much simpler) and without too much of policy changes as it relates to access control.

1. Group level privilege should not be used for granting individual level permission. Group level access should be viewed as what a member of the group can do with the resource and not with the access permission for the resource.
2. Granting of individual permission on resource should be based on the individual permission of the grantor on the resource. 
3. Revoking of group level permission should not affect individual level permission and vice-versa.

**Comment by alvacouch** [comment]
@pkdash @dtarb This is trivial to accomplish (< 1 day, including revising tests). It does not require any migration; just a minor rewrite of the logic in `(can_)?_share_*_with_user`. I've already essentially written the logic for the other possibilities; a small tweak is all that is required.  

My question is whether it is flexible and powerful enough, and whether it is **socially** robust. The ability of a group member to delegate is a powerful thing (and unique to HydroShare AFAIK). It has some rather unique social properties:

1. If group members can share outside a group, then they can delegate subtasks that they couldn't otherwise delegate and would have to be accomplished by copy-and-reshare. 
2. If group members can't share outside a group, then **they can still copy-and-reshare.**
 
Thus, the option of sharing group privilege with users at view level **potentially reduces storage footprint by supporting individual delegation as an alternative to copy-and-reshare**. 

_If this were not true, I would agree with you._

There is, however, another way of resolving the same use case with similarly low storage footprint, by evolving groups to accomplish the same ends. Doing so requires that we be able to share the set of resources held by one group with another **group**.

A simple use case: we want group A to be able to CHANGE a set of resources, while group B should be able to VIEW them -- same resources. We have one set of resources and two groups of users, where **B inherits A's resources**. However, B has its privileges set to VIEW instead of CHANGE. We accomplish this by filtering privileges for B so that its privileges are reduced. 

As a more complex use case, consider temporary delegation. A user wants to add a subgroup that can do something temporary. They might not be part of the main group, but one could use the same mechanism as above to temporarily share CHANGE privilege for resources with them.  In this case, we reverse the picture and the subgroup B has resources that are shared with the main group A but not vice versa. 

If you look at our old pictures of sharing, we did conceive in the beginning that this kind of thing would be possible. 

Not as difficult as it sounds, because the group sharing mechanism is completely separate from the user sharing mechanism if we proceed this way. Requires some sneaky tricks with queries and one major limitation. 
* There would be one new table `GroupGroupPrivilege` that is the authority on what one group can receive from others. This can be a general graph; there is no contradiction in having two groups that always share resources with each other, e.g.  Or even a star diagram where 5 groups share resources with each other at different levels. 
* The key to making this easy to implement is that **there is no transitive closure**, in the sense that if group A shares its resources with B and B shares its resources with C, then **C does not inherit A's resources. ** Making each share local is fairly straightforward. Every share means "what I have, you can also see" but does not implicitly allow you to grant that privilege of seeing "their stuff" to other groups. Transitive closure would be hell to implement.  And there isn't a use case for it.

**Comment by alvacouch** [comment]
@dtarb @pkdash @mauriel133  If everyone agrees that group-to-group sharing is a reasonable social trajectory, I am prepared to resolve the current issue according to @pkdash 's recommendations in PR #1576 (in an hour or two) and then proceed with implementing the Group-to-Group sharing on the backend after AGU (< 1 week for fully tested back-end). 

The only downside of the above proposal is that it **requires a set of very sophisticated Django queries**. At this point I can write them "in my sleep" but others will likely have trouble understanding them. This is a problem of understanding, and not performance. Performance should be acceptable.

**Comment by alvacouch** [comment]
I have implemented the changes in PR #1576 to limit user sharing to user privileges over a resource, as discussed above by @pkdash . I think this is the best option.

**Comment by dtarb** [comment]
@alvacouch  asked me to comment on the questions here.

I am not in the camp of turning off capability based on whether access is directly or via a group.

I think we should hold to the following concepts

1.  The capability to do something should not be different if one has a privilege through a group. 

2.  Group and user permissions when a user belongs to a group do not interfere.  

3.  An action is always by a user and is allowed based on the permissions they hold at the time they make it regardless if they have permission for that action by virtue of being a member of a group (related to point 1.)

Expanding on 2, if a user has change permission on a resource by being a member of a group that has change permission, then they can still be given view or change permission as an individual.  I do not know how permissions are being written to work in code, but logically we should think of permissions as a table associated with each resource that lists who can do what on the resource.  A user can appear on the table only once (at either owner, change or view level).  A group can appear on the table only once (at either change or view level).  The functional permission a user has at any point in time on a resource is the highest of what they have been given as an individual, and as a member of groups that have permissions.  If their group membership changes (e.g. expelled from group) or the group permission is revoked then I am OK with them losing access.  If while they had access they granted permissions to themselves or others as users, those permissions still persist.  If there are social problems, an owner can always see who has what permissions and revoke them if necessary.  

I agree with @pkdash that we should not use provenance in the access control system, except that the granter of a privilege has capability to revoke it even though others may not.  For example Garfield can give Sylvester a permission.  Garfield or an owner can take that permission away.  Another user cannot take that permission away.  If Garfield uses this capability to give a permission to themselves then only Garfield and an owner can take it away. If a user gives themselves permissions on resources they gain access to by virtue of being in a group, so they can secure persistent access, that is OK.  This is like Garfield wanting to ensure access to Catfood, because Catfood is critical to Garfield.  If an owner does not like Garfield having the individual permission they can always revoke it.  

Records of who assigns what permissions should be retained for auditing purposes, but I think this is separate from the access control functioning.  System administrators should be able to see these records.  Eventually it would be good for owners to be able to see these records in case they need to fix permissions on their resources.  The recording of an action by a user (and an action is always by a user) should record that users full permissions status on the resource at the time of the action (so it can be seen if it was by virtue of being in a group or not).

I believe the above statements are in agreement with points 1 to 6 in the original post.  I believe that point 2, separation of group and user permissions and allowing a user to have multiple functional permissions through groups should resolve the idempotency questions in the discussion (though I have to admit that I do not fully understand this word as used here).  

I also believe this is consistent with point 4 at the bottom of the original post that @alvacouch advocated.

I believe that this is consistent with saying yes to both questions in @alvacouch's second comment.

I do not think that re-sharing based on group privilege should only be at the view level. I think this would add an unnecessary complexity.  If you only want groups to be able to share view permissions, just give them view permission.  There was discussion in the development of the access control rules about whether sharing should be a permission granted to specific users or groups, but we decided to retain it as a resource property, something that is simple, and I think we should stick with.  I think that the case for only allowing extending view if access is through a group violates the concept 1 above that we should stick to for simplicity.

I am not too worried about the wiki leaks provenance problem.  An owner can always see who has access to a resource and can remove that access at any point.  If someone made a copy while they had access, so be it, they were granted access.  We do eventually need functionality to allow an owner to better see permission histories, but that should not change access control functionality.

**Comment by alvacouch** [comment]
@dtarb @pkdash I think there is sufficient evidence from this that I should not limit group function that I am going to undo the changes to PR #1576 related to this matter. It's too close to AGU and I don't want to break the UI at this late date. After all, **I intended PR #1576 as a semantics-preserving update.** It just happened that I discovered inconsistencies based upon looking at the code again. 

More generally, there is a basic question as to whether groups are "forever" or "ephemeral". Should kicking someone out of a group remove privilege on the objects in that group? At present, this is not true; kicking someone out of a group doesn't undo any individual privileges that person may have accumulated for self **using that group privilege**, and those individual privileges may be cleverly set by self using the algorithms documented above. I could write functions that dissociate a user from those resources, but for now, individual privileges set by self will remain when someone is removed from a group.

**Comment by alvacouch** [comment]
OK, so here's what I think we should do based upon this discussion, in total. There is one anomaly in the present sharing system: one cannot currently reshare something individually that was shared already via a group, at the same privilege. 

Example of this anomaly: 

* Morris shares CatFood with group Cats as CHANGE. 
* Morris puts Sylvester into group Cats. 

In the current implementation, this fails: 

* Trying to share CatFood with Sylvester **individually** at privilege VIEW or CHANGE;  

Sylvester already holds privilege CHANGE over CatFood via group Cats. 

But this succeeds: 

* Trying to share CatFood with Sylvester at privilege OWNER; Sylvester doesn't already have that privilege via the group.  

Resolution is to make the former one succeed as well. This is pretty much the opposite of the change to PR #1576 that I just undid in `share_resource_with_user`.

* In the current logic, grantor privilege and pre-existing grantee privilege are based upon combined individual and group privilege. 
* Grantor privilege should be based upon combined privilege, but in the case of individual sharing, **pre-existing grantee privilege should be based upon individual privilege**, to allow upgrading of individual privilege even if grantee holds group privilege.  

This is literally a one-line change in PR #1576, but is better left until after AGU because it would need to be tested in the UI. 

As far as idempotence goes, this is mainly a matter of provenance preservation. "It would be nice" if the first person to grant a privilege is recorded in provenance as having granted it. This is the reason that trying to grant a privilege that is already present is refused; "someone else" already granted it and the time of granting is also a matter of record.

**Comment by pkdash** [comment]
@alvacouch Is this still an issue?
