### ISSUE TITLE
Clarify versioning wording

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1625]
Right now when a user creates a new version of a resource, the message says:

> Creating  a new version will obsolete this resource. This resource will be still available in HydroShare, but only the newer version will be discoverable via the HydroShare search interface. A link to this resource will be created on the landing page of the new version. Only one newer version is allowed for each resource. 

I think the statement "Only one newer version ..." is confusing.  A user can create a new version, then create a new version of the new version and so on as many times as they want.  Technically I know we are thinking of only one version of a specific resource because the new version is technically a different resource.  However this subtlety is not clear to users.

I suggest:

> Creating  a new version will obsolete this resource. This resource will be still available in HydroShare, but only the newer version will be discoverable via the HydroShare search interface.  The new version is a complete new resource with new identifier.  It will contain a link back to the previous version and the previous version will have a link to the next version.  This can be repeated resulting in a sequence of multiple versions each linked to next and previous versions.  Only the most recent version can be edited or deleted.  If you delete the most recent version, the previous version becomes the most recent and editable.  

I recognize that this adds additional wording so welcome ideas to improve this.

**Comment by horsburgh** [comment]
@dtarb - clarifying text is good. Given our most recent experience, however, I have little confidence that users will read a block of text this long. I suggest shortening the text on this dialog and then adding a link to the help page that describes the details of versioning.

**Comment by horsburgh** [comment]
@dtarb - I enhanced the text on the Help page describing resource versioning with a modified version of your above text.

**Comment by dtarb** [comment]
I think it is good to have this text on the help page and in full on the interface message where a user sees it.  Unless someone wants to suggest wording improvements, lets go with the text I wrote.

**Comment by hyi** [comment]
@dtarb The new/updated versioning dialog looks like the following:
![res_pub](https://cloud.githubusercontent.com/assets/476302/20682590/95f45886-b576-11e6-9cc8-6a3e0429edd9.png)
Let me know if this looks good to you or not. If it looks good, I will create a PR and then merge it without code review since the only change is the wording change on the dialog.

**Comment by hyi** [comment]
@horsburgh @dtarb I have made corresponding changes for versioning changes and deployed it to riverdev.hydroshare.org for you to take a look. Both versioning wording change and publication message change are included and deployed on riverdev for you to take a look. If you think it looks good, I will create a PR and merge it. Let me know.

**Comment by horsburgh** [comment]
@hyi - the new wording on the create new version dialog looks good to me.

**Comment by horsburgh** [comment]
@hyi - by the way, when I created a new version for a resource at riverdev.hydroshare.org, the link to the previous version uses www.hydroshare.org, so that was really confusing to me. When I clicked on it I wanted to see the older version of the resource I just created the newer version for on riverdev.hydroshare.org, but it actually took me to the original resource in www.hydroshare.org instead. It took me a little bit to figure out that I had actually jumped from one server to the other and that's why the link back to the newer version wasn't there.

**Comment by hyi** [comment]
@horsburgh Thanks for testing. Since we are using www database on a development VM like riverdev, when you create a new version of an existing resource which was initially created on www, the url identifier metadata element in the database points to www.hydroshare.org site which is used to create the link. This explains why you see this behavior when you traverse back to the older version of the resource which was pointed to www.hydroshare.org. If you create a new resource on riverdev, then create a new version of this resource, then the traversal links will all point to riverdev.hydroshare.org rather than jumping back to www. This is just a side effect of setting up a development VM to use www database and it will not happen in www production.

**Comment by horsburgh** [comment]
@hyi - thanks for the explanation. I was a bit perplexed for a minute or two last night.

**Comment by hyi** [comment]
@dtarb The PR that changed the wordings has been merged into develop and has been tested by @horsburgh on riverdev. I think you can close this issue now.

**Comment by dtarb** [comment]
Thanks.  Closing.
