### ISSUE TITLE
National Water Model Upload to HydroShare: Broken

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#1626]
@danames 
We need a NWM demo for AGU that launches from the App page.  The final step of uploading the work back to HydroShare needs testing.  Here is an example of how I broke it on a first attempt to make it work:
![image](https://cloud.githubusercontent.com/assets/4108369/20574281/8dc996e2-b168-11e6-8ca4-ee97e46fb7f6.png)

**Comment by ChristinaB** [comment]
here's the setup.  It hangs when you click on 'Add to Hydroshare'

**Comment by ChristinaB** [comment]
Hi @danames  and @dtarb  -  this issue relates to the email that needs to go out to the group on testing Apps so they can be successfully demoed at AGU.  Who and how do these issues get assigned?   Thanks!!

**Comment by ChristinaB** [comment]
@zhiyuli  and @Lizabrazil   Do we want a checkbox here?

**Comment by ChristinaB** [comment]
- [ ] Add instructions pop up

- [ ] Fix broken Upload to HydroShare - see USGS AHPS viewer, that code works

**Comment by ChristinaB** [comment]
List of issues that came up in Onion Creek demo 11/30/16
- [ ] Change error message so that we have an idea how to avoid the error, for example, select a different date.

**Comment by ChristinaB** [comment]
@danames and @zhiyuli   we need to know how you want to handle uploading to HydroShare.  We need your feedback here.   Thanks!!!

**Comment by danames** [comment]
At this point, Our intention is simply to remove the button for uploading.
This will give us time to improve that functionality and deploy it later
after the current crisis deadlines are past. The idea of uploading the
resulting time series file to a resource is really powerful, but I want to
make sure it works well. One of the issues here is we need to make sure
that the time series resource type can handle input of a water ml file. -
Dan

On Wed, Nov 30, 2016 at 11:51 AM Christina Bandaragoda <
notifications@github.com> wrote:

@danames <https://github.com/danames> and @zhiyuli
<https://github.com/zhiyuli> we need to know how you want to handle
uploading to HydroShare. We need your feedback here. Thanks!!!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/hydroshare/hydroshare/issues/1626#issuecomment-263959414>,
or mute the thread

**Comment by horsburgh** [comment]
@danames - The HydroShare time series resource currently supports upload of an ODM2 SQLite file or a CSV file. We've not added WaterML import yet.

**Comment by dtarb** [comment]
I suggest either load it to generic, or to time series as CSV.

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/nwm-forecast-viewer#26
