### ISSUE TITLE
Can't create netCDF resource using iRODS user zone file

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#1628]
I tried to create the netCDF resource on www site using the file from iRODS user zone and got the following error. Different files are tried and have the same error. @hyi would you please help to have look at this issue? Thanks

![image](https://cloud.githubusercontent.com/assets/5016511/20574977/75aa62ce-b174-11e6-84fa-969081c6fd89.png)

**Comment by hyi** [comment]
@gantian127 I discovered this issue while writing and testing federated user zone unit tests and have fixed this issue along with several other issues related to federated user zone in that branch. This PR https://github.com/hydroshare/hydroshare/pull/1623 will fix this bug along with several other bugs. It'd be great if you, @pkdash and @zhiyuli can code review that PR whenever you have a chance so that it can be merged sooner rather than later since it includes several bug fixes discovered by the new unit tests I wrote. With that PR merged, the user zone-related functionalities will be unit tested to make sure they work as expected.

**Comment by gantian127** [comment]
@hyi Thanks for your information. I will look at the code of branch #1623.

**Comment by hyi** [comment]
@gantian127 The fix to this issue has been deployed to beta as part of the addition of federation unit tests. Can you verify on beta and close this issue if it works now?

**Comment by gantian127** [comment]
@hyi I tested on Beta and it works now. I will close this issue. Thanks
