### ISSUE TITLE
folder deletion code does not delete type-specific resource metadata from Django

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1629]
@hyi @pkdash @dtarb

I noticed a difference between the delete file routine (`hs_core.hydroshare.resource.delete_file`) and the delete folder routine ('hs_core.views.utils.remove_folder`) because the former contains a call to send the pre_delete_file_from_resource signal to Django: 

https://github.com/hydroshare/hydroshare/blob/develop/hs_core/hydroshare/resource.py#L1013

I did some research and there are several receivers for the pre_delete signal among non-generic resources. These do cleanup specific to those resource types. These are not being called by the `remove_irods_folder_in_django` method. It's too late to call them at that time because they are pre-delete methods. These methods include: 

```
hs_app_netCDF/receivers.py:@receiver(pre_delete_file_from_resource, sender=NetcdfResource)
hs_app_timeseries/receivers.py:@receiver(pre_delete_file_from_resource, sender=TimeSeriesResource)
hs_geographic_feature_resource/receivers.py:@receiver(pre_delete_file_from_resource, sender=GeographicFeatureResource)
hs_geo_raster_resource/receivers.py:@receiver(pre_delete_file_from_resource, sender=RasterResource)
```
Some of these delete Django metadata objects whose **deletion does not cascade**, due to underspecified database constraints. Thus, for these types, **`remove_irods_folder_in_django` leaves cruft in the Django database that is never cleaned up.**

This is a general and systemic problem in the resource data model that is just the tip of the iceberg: extra values for single-valued fields (title, abstract) are never detected if they are inserted after the first one.

**Comment by hyi** [comment]
@alvacouch @pkdash @dtarb This ```remove_irods_folder_in_django``` method is an internal method (i.e., not an API and not intended to be used externally) which is only used by ```remove_folder``` in ```hs_core/views/utils.py```. This ```remove_folder``` method is intended for use by internal API as well as external REST API. Currently, the resource types that respond to pre_delete_file_from_resource signal don't support folder operations, so they should not be affected at least for this first phase of implementation. In the future when needed, we can add pre_delete_file_from_resource signal emitters in ```remove_irods_folder_in_django``` internal method for each file inside the folder being deleted as a result of the folder deletion, or we just send one signal like pre_delete_folder_from_resource depending on the use case. But for now, since there is no action that are needed as a result of folder deletion, I suggest we don't send pre-delete signals for folder deletion until we have a real use case so that we can send signal(s) that exactly meet the use case. What do you all think?

**Comment by pkdash** [comment]
@hyi 

> Currently, the resource types that respond to pre_delete_file_from_resource signal don't support folder operations, so they should not be affected at least for this first phase of implementation.

I don't see in the backend any resource type preventing folder operations.

**Comment by hyi** [comment]
@pkdash I believe it is enforced in the front end only by @mauriel133 according to the list for all resource types for the folder-related operations as decided by the team. There is no back-end code added to prevent this right now, and probably should be added in the view functions. I think for REST API functions that call these folder-related functions, the enforcement to prevent folder operations for specific resource types also need to be added. If this is the case, it'd be better to add these backend enforcement in REST API implementation for folders so that they can be enforced consistently. @alvacouch What do you think? Do you think you can add the backend enforcement in the same way as current UI in preventing folder-related operations for specific resource types when you work on REST API for folders? If not, let me know, I can work on adding these enforcement. Thanks.

**Comment by alvacouch** [comment]
@hyi @pkdash This is to be resolved temporarily by prohibiting the folder deletion code for all but the supported resource types, and by assuring that pre-delete signals that clean up local metadata are **not registered for types containing folders**. However, I feel that a more elegant long-term resolution would be to simply **recursively delete contained files before folders, activating pre-delete signals for each file as necessary.**

**Comment by alvacouch** [comment]
I also note here -- and I have mentioned this already to @pkdash -- that some of the existing pre-delete signal handlers are deleting other files that are considered subsidiary to others, thus violating the logical file scheme that @pkdash is implementing for composite resources.

**Comment by hyi** [comment]
@alvacouch I was thinking about whether to do it as you mentioned, i.e., recursively delete contained files before folders, activating pre-delete signals for each file as necessary, when I was initially implementing this delete folder routine, and did not go ahead to do it that way eventually mainly because (1) it would have performance penalties to do it that way (much slower) as opposed to deleting the whole folder at once; (2) folder deletion does not apply to those specific resource type such as time series resources that need to response to this pre-delete signal; (3) just for performance concerns, perhaps it is better to emit a pre-delete folder signal rather than pre-delete a file signal recursively for each file in the folder, since listener to pre-delete folder is a very special case rather than widespread and we don't want to accommodate this special case by slowing down folder deletion operation in majority of cases which don't require pre-delete folder processing. 

So it is something to keep in mind and may be improved in the future driven by specific use cases, but for now, I think we can leave it the way it is now.

**Comment by Castronova** [comment]
Stale
