### ISSUE TITLE
R script resource shows open with Hydroshare GIS app as option

### ISSUE THREAD

**Issue by Lizabrazil** [hydroshare/hydroshare#1637]
HydroShare GIS is showing as an app option for an R script resource. When i chose open with Hydroshare GIS app, the app has no functionality for an R script. 
Need to make the distinction of whether the app can handle the resource type. 
Tested with resource: http://www.hydroshare.org/resource/de66f7c5b0e3470eb3423070e72d9959

**Comment by shawncrawley** [comment]
@Lizabrazil Can I get access to that resource for some further testing? As far as I have tested, other Script Resources can, in fact, be opened with HydroShare GIS. Do you mean that HydroShare GIS gives an error when opening it, or that once added as a layer it has no useful functionality? Or do you mean something else entirely?

**Comment by horsburgh** [comment]
What exactly would the HydroShare GIS App do when it opens an R Script? 

If there isn't any useful functionality, then the HydroShare GIS App shouldn't show up in the list of Apps that can open this type of resource.

**Comment by shawncrawley** [comment]
Consider this resource as a prime example of why we wanted Script Resources to be "openable" with HydroShare GIS (choose "Open with.. HydroShare GIS" to see):
https://www.hydroshare.org/resource/56f68cb560df4f65a44fd0d732b6432f/
This is a map project demonstrates the case where there many different resources (of many different types, including a Script resource) that all relate to one main "project" that are intended to be lumped/viewed together. In the case that a Script resource has coverage metadata associated with it (which has to be added manually by the resource owner), the associated coverage info (i.e. the lat-lon point) will be drawn on the map and a layer item will be added to the current layers list. If there is no coverage metadata, only the layer list item will be created. The layer list item will have a dropdown which includes a "View file" option, which triggers the opening of another app, the Script Viewer, to actually view/edit the contents of the associated script file.

This does bring up two points. First, the Script Viewer app is only currently functional on appsdev, and thus will not work in conjunction with HydroShare GIS on apps.hydroshare. So either the Script Viewer should be moved to apps soon, or that feature should be removed from HydroShare GIS until the Script Viewer is on apps.

The second point is more of an idea. Maybe it would be best that "HydroShare GIS" does not appear in the "Open with..." dropdown for Script Resources themselves, but still allow HydroShare GIS to add a Script Resource from within its own "Add Resource" dialog. Because it is true that if someone truly just wants to view their script, going through HydroShare GIS is a roundabout way of doing it. They could just open it with the Script Viewer directly. Again, opening a Script resource from within HydroShare GIS is mainly for adding it to a "project" containing other related resources (whether they are all intrinsically spatial or not).

**Comment by Lizabrazil** [comment]
If you do "View File"- you get redirected to a broken page

**Comment by horsburgh** [comment]
@shawncrawley - thanks for the useful explanation. I agree with your assessment that HydroShare GIS should not appear in the "Open With" dropdown for script resources, but that the HydroShare GIS could be capable of adding a Script Resource from within it's own "Add Resource" dialog in the context of a project that contains related resources.

**Comment by dtarb** [comment]
@shawncrawley I too agree with your assessment.  The view file problem that Liza points out should be fixed.  Perhaps view file should be hidden for now and its role revisited.  In the example you provided it is broken for the .py file, results in a blank screen for the PDF, is not present for the .shp files, but works for the mp4 and jpg files.  Viewing of jpg, pdf and mp4 is not really Hydro value added so perhaps we should provide download links and rely on standard browser viewing of these files rather than doing a lot of work to embed functionality.

**Comment by danames** [comment]
I agree with this as well. At present the gis app is only associated with
generic, shape, and raster resources. However if you open a generic and it
has a text file or script file in it, it should be able to launch the
script viewer. I'm following up with Matthew on the script viewer. It is a
very simple app that we can deploy soon, though  we probably don't have
time to thoroughly tested before AGU.

**Comment by shawncrawley** [comment]
@Lizabrazil This issue should be resolved. Let me know if it appears not to be.
