### ISSUE TITLE
National Water Model Data Explorer...is not technically an app

### ISSUE THREAD

**Issue by Lizabrazil** [hydroshare/hydroshare#1640]
If we are trying to stay consistent with the idea that apps are tools that operate on resources, the National Water Model Data Explorer should be moved to dev before AGU. As far as I can tell, this is a data access tool..?

**Comment by Lizabrazil** [comment]
Should not be accessible through an individual resource page. Drew and Dan will take care of this.

**Comment by dtarb** [comment]
Part of HydroShare's purpose is to enhance access to data that may otherwise be hard to access.  This data should, where possible, be a HydroShare resource or referenced resource, but this is not possible in all cases and one of the modalities for providing enhanced access to data is through an app that acts with the data at its original source location and makes it available in a consumable format.  Ideally this consumable format should be able to be saved by a user in HydroShare as part of one of their resources for their further work.  The NWM data explorer app fits into this category.  The NWM data is not readily accessible by the community, so HydroShare is hosting it in an iRODS server and supporting this App that makes it available.  Work is in progress to improve and streamline these apps, but things can always be improved.  However we should appreciate the value that they provide now.  Without this app the community cannot access this data at all.  With this app they can access it, somewhat awkwardly, but better than nothing.  This will get better, I do not think it should be removed, but it should be presented for what it is (and any disfunctional parts removed from the interface).

**Comment by aphelionz** [comment]
@dtarb @Lizabrazil Closing this unless you think we should continue this discussion in terms of the new apps page
