### ISSUE TITLE
Apps: Simple Styling Modifications

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#1642]
@danames @dtarb 
We are big fans of these super awesome Apps, but...
@jphuong and I were looking through the Apps page while making a plan for Help and noticed that there is some CRAP issues.  
Contrast:  Too many colors and cognitive load
Repetition:  repeated icons but not clear how they are related
Alignment:  misalignment needs to be squared up
Proximity:  Some grouping is needed.

**Comment by ChristinaB** [comment]
Do we want Apps to be something like the landing page and help icon styling? @horsburgh and @mauriel133 have done a lot of thinking on that.

**Comment by jphuong** [comment]
While each app is very much unique, is it possible to group up similar apps, like those that have similar model equations/calculations, output variable, or output file format? Is metadata of this sort captured somewhere?

**Comment by ChristinaB** [comment]
@danames and @zhiyuli 
The names of the Apps should be curated so that it is super clear to users.

**Comment by danames** [comment]
We can try to simplify the HydroShare team apps, but we won't have control
over other peoples apps beyond providing some styling suggestions.

**Comment by ChristinaB** [comment]
Let's think of a simple way to include suggestions, guidelines, and requests for developers as part of the process of getting their App from dev to the main page.

**Comment by ChristinaB** [comment]
Hi @danames 
Reviewing the open issues in preparation for meetings tomorrow, I wanted to alert you that this issue is not quite resolved.  We are currently committed to polishing up and testing 12 apps that are pre-existing, but do not have a plan for any new Apps, or for communicating expectations to developers of new Apps. Do you want to discuss in the developer meeting?
C

**Comment by danames** [comment]
I propose we create a new app and add it to the HydroShare app page called "App Builder Tutorial" or something like that. When a user clicks it it opens an app that teaches them how to create a HydroShare app in tethys, how to document it, what the expectations are for apps, ALSO how to simply link your app using the Web App resource type, so that they can use apps created outside Tethys, etc. This new app would also instruct developers on how to use the HydroShare API etc. 

@ChristinaB - another option would be to just write help pages for all this. But the nice thing about building this instruction within an actual app is that we can have buttons and widgets that they can click on to test behavior. 

@dtarb this app would be out of the ordinary since it would be specifically for future web app developers, but I think that it would get a lot of usage as various people want to start using the HydroShare API and connecting their own apps, etc.

**Comment by ChristinaB** [comment]
If you have a student who wants to work on a Help App, we are happy to work with them to develop content that we can use on the flat help pages as a starter place to publish it.   Could this student meet with E&O regularly to get used to the Help issues and priorities?    A new mini-team is emerging with @jphuong supervising a UW intern, CUASHI intern and your  BYU undergrad?? to help with testing and Help content development.

**Comment by aphelionz** [comment]
@ChristinaB I am going to close this as we have a new apps page now, but do give me similar feedback on the new apps page!
