### ISSUE TITLE
UI and REST API need a shared ground truth for application logic 

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1644]
@pkdash @dtarb @mauriel133 @horsburgh 
Issue #1618 demonstrates a design issue that is going to come up repeatedly as we try to complete the REST API. Much of the application logic of HydroShare -- including what can be done to each kind of resource -- is only implemented at the UI level. Though there is a [spreadsheet](https://docs.google.com/spreadsheets/d/1tc-6tIq_YkJpa2CGj5tAEHMaLOZV2i3W10lokBCJAn0/edit#gid=0) defining some what this logic is, it covers only file/folder issues and is not comprehensive. A systematic approach needs to be developed that serves as "ground truth" for both the UI and the REST API as to how to implement this application logic. 

* A common approach -- though I am not yet recommending this -- is to make the REST API definitive and have the UI refer to it as to what is allowed. Thus, the application logic is implemented as a set of external and internal REST endpoints. The reason people do this is that REST helps one code this easily. 

* The other way to approach this is to create application middleware that both the UI and REST interface refer to in determining application logic. This is what the access control system is, but it is only a subsystem of application logic and does not document the limits of what can be done in editing each kind of resource. We would need a different logic engine to determine what one "can" do to each kind of resource, separate from the UI. This would not be an authorization logic like access control, but rather, a **validation logic** for edits that determines what kinds of edits can be performed without violating resource type limitations.  Our existing validators are not comprehensive enough to serve this function -- yet.

**Comment by pkdash** [comment]
@alvacouch I think having a validation app/module for various actions on resource that both the REST and internal view functions can use would be better.

**Comment by alvacouch** [comment]
@aphelionz I would like you to think about this issue.

**Comment by aphelionz** [comment]
@alvacouch @pkdash 

I think you're both right. We need to start steering towards the idea that the UI and the REST API are separate, that the REST API is the one and only source of truth in the application, AND that middleware modules are going to save us from ourselves.

We need to stop putting application logic in the views starting now and only use them to render templates, and then only access the REST API via AJAX calls in the UI layer. That will be a huge step in the right direction.

**Comment by hyi** [comment]
@alvacouch @pkdash @aphelionz Totally agree REST API and UI need to share the ground truth for application logic. I believe we have been trying to achieve this by putting application logic into utility functions/methods that are called by both views for UI and REST API end points. We definitely want UI and REST API to behave similarly that utilize the same ground truth application logic so we only need to maintain application logic in one place without duplication.

**Comment by aphelionz** [comment]
@hyi @alvacouch @pkdash 

I want to be careful in how we talk about this so we're clear about what our objectives are.

When we say the UI and REST API behave similarly, my concern is that there are two code paths that the application execution can take - one through the UI layer from a user clicking through the site, and another through the API layer from applications and AJAX calls.

My proposal is that they should be one and the same, and all logic should live within and ONLY within the REST API. This can be achieved with short term and long term implementations.
1. Stop putting application logic in the views, only use views to render HTML scaffolding and require the templates to fire AJAX requests to the REST API moving forward. We can start doing this today.
2. Incrementally refactor out (over the following weeks/months) application logic that exists within the views to middleware that the REST API can consume to fulfill any requests made to it.

An easy win would just be to pick a single page or section of the application to do this with. I can't suggest one right now because I'm part way through auditing the code, but I will make a proposal when I'm done. In the meantime I'm open to suggestions! Is there a module or section of the app that's compartmentalized enough to do easily as a proof of concept?

**Comment by hyi** [comment]
@aphelionz This may be a naive question, but by ```require the templates to fire AJAX requests to the REST API moving forward```, how are views are used then? Currently, templates fire all requests to internal APIs which are mapped to view functions. These view functions pretty much retrieve parameters from requests and then call common utility functions (which can be put into a middleware layer) that are called by corresponding REST API end points as well, then return a HTML scaffolding page. Yeah, it'd be good if you can pick a single page to do this to illustrate your proposal so I can understand it better. I suggest the My Resource page as a candidate to start with since it only involves one view function create_resource() once the ```Create new``` button is clicked, so thought that might be a good place to start as a proof of concept.

**Comment by aphelionz** [comment]
@hyi

Not a naive question at all! My proposal is very opinionated and dogmatic, but I think it's necessary in order to keep our code and architecture clean. Maybe a better way to say what I said would be "For application logic, we need to incrementally start replacing django.Views with django_rest_framework.Views"

This is a utopian vision, so bear with me: In the end, I'd like to see one single django view that renders HTML to the browser: `url('^$', 'views.index')` or something like it. From that index we would build out a Polymer/React/ Much like what Mezzanine does. Then, before that in urls.py we consolidate all application logic. Thus our Django app becomes a large-scale REST API that also happens to render an index.html file, which contains the front-end app.

Now that I've said that and probably horrified everybody reading it, do know that my proposal is much less a one-time overhaul of everything and much more steering the ship slowly toward a new bearing. I'm very sensitive to the concerns of user-facing functionality, the horrors of refactoring, and the risk of losing funding if things go wrong.

**Comment by aphelionz** [comment]
Also @hyi great suggestion in regards to the My Resource page. That's perfect - essentially one AJAX call to retrieve the list of resources, and another AJAX call to create new.

**Comment by aphelionz** [comment]
@alvacouch @pkdash @hyi 

SEO Concerns about having a primarily AJAX driven front end can be mitigated with three approaches
1. Google and other crawlers are showing an increasing aptitude in crawling JS-rendered data
2. We can explicitly submit a sitemap.xml telling Google/Bing/etc exactly where every single resource is located
3. We can use the `history.pushState` api, or a routing library to generate proper urls and not have to rely on "hash" urls like `/#/my-resources` anymore

**Comment by hyi** [comment]
@aphelionz Thanks for the elaboration on your proposal. Now I understand what you are proposing here and I'd be looking forward to seeing your proof-of-concept.

**Comment by aphelionz** [comment]
@hyi I will aim to not disappoint :)

**Comment by pkdash** [comment]
@aphelionz I like this architecture you are proposing which seems to be a standard way of doing things in modern web applications. Though I have little background in UI frameworks and UI programming, I think we are not using any of the available JavaScript reactive frameworks to our advantage. I feel like we have lot of logic built into template code. Some of the templates are huge too.

**Comment by alvacouch** [comment]
Inviting in @dtarb @mseul @danames @horsburgh with a little high-level background on this issue. This issue came about when I was assigned to take over the REST API. My goals in this are to: 

1. Make it possible to do more or less anything in a Tethys app that one can do in the UI. Thus
2. The Tethys apps can "extend" the UI in ways that help users, more easily than we can extend the core UI. 

The main vehicle for this is the REST API. 

However, I quickly discovered that this involves an "arms race" between the REST API and the UI: 
3. Anything that one does in one, one has to duplicate in the other. 
4. Both embody complex application logic. 
5. This logic is difficult to keep in sync. 
**This makes keeping the REST API and the UI in sync an ongoing management nightmare.** 

The most complex piece of this determining _"What is one allowed to do to a resource of a specific type?"_ This is currently hard-coded into the views of the various kinds of resources. Clearly, this logic needs to be in one place, rather than two. But more importantly, _the Tethys apps should also be able to utilize this logic._ The only place that one can put the logic that makes total sense, therefore, is the REST API: it is the glue between Tethys and the UI.  

So, this is **not** a proposal for changing the UI. It is instead a proposal for adopting a different set of practices for **constructing** the UI. There are many ways we could build the UI. All of them result in more or less the same look and feel to a user. The technique we pick depends upon other requirements. The technique we picked initially was from the Django tutorials. This is fine for simple sites, but we have an extra requirement: a facile interface to apps.hydroshare.org. That changes the picture substantively, as well as the appropriate practices. 

The new set of practices is just as expressive as the way we've been making the UI so far, but it has the added advantage of eventually enabling one to do more or less anything with a Tethys app that one can do with the UI, with a guaranteed consistent response regardless of which way one interacts with the system. It also allows independent programmatic control by programs that are not Tethys apps, at the same level of expression. 

The Tethys apps are the future of the UI, and I want to enable them to the extent possible. But this also -- automagically -- enables automatic population of resources from external means.

**Comment by aphelionz** [comment]
Copy that, @alvacouch. Thanks for the context My proposal stands.
