### ISSUE TITLE
Provide an embargo/rescission period for publication actions

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#1649]
The idea of permanently publishing a resources is going to be somewhat new to many of our community, including students, who generally think of everything online as malleable. Our notice on the publish button is quite strong and does clearly say that it can't be undone. However, we are still going to have people "trying" a publish action and then having publishers remorse afterwards when they discover an error in the abstract or such. 

So I propose providing an embargo/rescission period for new publication actions. In other words, when I accept the publication agreement, I get 2 days to change my mind and undo the action. It may be that we just don't give the DOI for 2 days. 

I'm open to alternative and counter-arguments.

**Comment by horsburgh** [comment]
@danames: see #1608 where we've already started a discussion about this. @hyi already implemented the "are you sure you are sure" dialog, but the waiting period is described. Can we combine these issues?

**Comment by horsburgh** [comment]
I closed #1608, so I'm moving the leftover discussion from that issue here:

- Implement notifications to send email notifications to Authors and contributors when a resource they have authored or contributed to is published.
- Implement a period between when a user requests to publish a resource and when it is actually made immutable (perhaps one week).
- Develop messaging that states something like - "You just requested that we publish your resource. HydroShare will now request a permanent DOI for your resource. You have one week to verify that your files and metadata are correct and that all authors and contributors are in agreement. After this period, your resource will be permanently published and you will no longer be able to modify it."

**Comment by dtarb** [comment]
Closing as this is superceded by manual review process outlined in #2298 and CUAHSI policy decisions for a manual review process.
