### ISSUE TITLE
Resource edit page

### ISSUE THREAD

**Issue by mauriel133** [hydroshare/hydroshare#165]
I will be restyling the resource edit page. The goal is to make it look more compact and organized.

**Comment by dtarb** [comment]
@mauriel133 @horsburgh is this still viable for 1.4 or does it have to be put to 1.5

**Comment by mauriel133** [comment]
This is not quite ready yet and should be put to 1.5

**Comment by dtarb** [comment]
I generally like the resource editing improvements as deployed on dev.hydroshare.org.  

Please move Keywords to below Abstract and above How to Cite so that the required metadata is together at the top.

I would prefer the term Subject rather than keywords as I think that is what is used in Dublin Core.  I suggest this for internal consistency.  Subject is what appears in resourcemetadata.xml and is what I suggested in filtering #376, but this is not a strong preference so could be persuaded if others object

**Comment by dtarb** [comment]
Closing.  New issues need to be created for metadata editing enhancements beyond 1.5.1
