### ISSUE TITLE
Automatically populate Creator information on resource creation

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#168]
When creating a new resource, the current user is automatically set as the first creator.  All of the user's available profile information should be copied into the metadata editing form, but isn't currently.  For example, the HydroShare User Identifier (URL) field is left blank as is the Organization and Address.  

Where they have not been set by the user, they cannot be copied, but where they have been set, they should be automatically populated.

**Comment by hyi** [comment]
Briefly looked at this issue hoping for a simple fix, but looks like not so since those profile information is not available in the page content model currently. It takes some investigation on retrieving these needed profile information managed by Mezzanine to populate into page content model for the landing page to use. Suggest to move the milestone for this issue to 1.6 since I will need to work on new bagit workflow slated for 1.5 and will most likely not have time to work on this issue in time for 1.5.

**Comment by pkdash** [comment]
This has been addressed in resolving issue #293.

**Comment by pkdash** [comment]
@horsburgh Close this issue if you think this has been fixed.

**Comment by horsburgh** [comment]
I will close for now.  All of the information that can be copied from the profile into the creator is being copied.   The Address and Homepage elements are not copied in, but you can't actually put that information in on the Profile editing page yet either.  So, we may want to revisit when the profile creation and editing is complete.
