### ISSUE TITLE
Correct URIs in resourcemap.xml

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#169]
The URIs in the resourcemap.xml are created incorrectly.  I tested both generic resource and time series resource and both had problems. 

Testing on dev.hydroshare.org.  See this generic resource for reference:

 http://dev.hydroshare.org/resource/26973647d27d46b58be3dcd1d889f6bb/

The URI to the content file was created with what looks like a relative path:

/tmp/hydroshare/26973647d27d46b58be3dcd1d889f6bb/2015.02.24.18.03.01/contents/TWDaniels_Temperature.csv

Instead, this should be:

http://dev.hydroshare.org/resource/26973647d27d46b58be3dcd1d889f6bb/2015.02.24.18.03.01/contents/TWDaniels_Temperature.csv

The URI to the science metadata file was created with the name of the resource in the path AND refers to a JSON file that doesn't exist:

http://hydroshare.org/resources/Air Temperature at the TW Daniels Experimental Forest/resourcemetadata.json

Instead, this should be: 

http://dev.hydroshare.org/resource/26973647d27d46b58be3dcd1d889f6bb/2015.02.24.18.03.01/data/resourcemetadata.xml

The URI to the resource map file has the same problem as the URI to the science metadata document.

Final Note:  When I looked at the resource map for the time series resource that I created (http://dev.hydroshare.org/resource/f5e4c6083e8d4e91be216295f7b6282e/), it did not have the issue with referencing a JSON file as the resource metadata, but the URIs had all of the other problems described above.

**Comment by pkdash** [comment]
@horsburgh Should the URL for the content file be (added 'data' sub path):

http://dev.hydroshare.org/resource/26973647d27d46b58be3dcd1d889f6bb/2015.02.24.18.03.01/data /contents/TWDaniels_Temperature.csv

**Comment by horsburgh** [comment]
Yes, because that URI should resolve directly to the file. I am assuming we have resolved for sure that we are versioning via a timestamp in the URL?

**Comment by pkdash** [comment]
You mean we need the timestamp as shown above for the content file URI?

**Comment by dtarb** [comment]
I think that having the time stamp in the URL may be awkward and I am not sure how feasible it is.  @mjstealey please comment on how you suggest we resolve this.  At present a URL like @pkdash wrote above resolves to a 404 error and the pattern for retrieving a single file from a resource is different.

**Comment by horsburgh** [comment]
I think the timestamp in the URL is a hold-over from when HydroShare was creating a new bag every time an edit was made to the metadata.  Our documentation about identifiers and formal publication of HydroShare resources states that HydroShare will create a new unique identifier (and hence a new resource) for all subsequent versions of a resource.  So, if we stick with that, versioning shouldn't be done using timestamps in the URL.

This is also related to #170.

**Comment by pkdash** [comment]
In addition to URI issues (as described above) there are many other issues with the generation of the resourcemap.xml document. I think I have fixed all the URI issues now. The other issues may take a while as I have to learn how the tool used for creating this xml document works.

**Comment by pkdash** [comment]
Will be implementing these additional changes as suggested by Jeff.

Pabitra,

What you have now as 'ore:isDocumentedBy' should be 'citoterms:isDocumentedBy'.  This just needs to be relabeled.

Also, perhaps we should bag the hsterms xmlns.  We are only using one term in the resource maps – "hydroshareResourceType" and I'm not sure it warrants using a separate namespace for one term.  As it turns out (and after studying Dublin Core a bit more, there is a "dcterms:type" term that we could use instead.  There is a suggested vocabulary for that element here (http://dublincore.org/documents/2000/07/11/dcmi-type-vocabulary/). But we don't necessarily have to use it.  I think the reason I didn't suggest this in the first place is the fact that Dublin Core has this vocabulary already and the HydroShare resource types are not in the list.  But, the definition of the "dcterms:type" element works for our needs.  It is as follows:

http://purl.org/dc/terms/type - The nature or genre of the resource.

So, my proposal is to change the element "hsterms:hydroShareResourceType" to just "dcterms:type".

Other than those two things, I think the resource map looks good given that I think you have already removed the timestamps from the URIs.

I noted in testing alpha that the URL to a resource landing page is like this:

http://alpha.hydroshare.org/resource/21eebbe42eaa423da197edf74f4a289e/

Notice the singular "resource" in the URL.  I just reviewed this issue that has already been closed and that deals with URL patterns for HydroShare:

https://github.com/hydroshare/hydroshare/issues/63

So, it looks like we need to make the URIs in the Resource Map Documents to have "resource" instead of "resources" to match what has already been implemented.  Do you want me to post this to GitHub or do you want to just fix it when you make the other fixes you will make today?

**Comment by dtarb** [comment]
There is still repetition between dc and dcterms.  Perhaps this is OK.  @horsburgh if you are happy with this you can close.  I've written a new issue #258 for migration of old resources to be consistent with this, and a new issue #259 to make URL's work.
