### ISSUE TITLE
HydroShare GIS features that depend on hs_restclient functionality

### ISSUE THREAD

**Issue by shawncrawley** [hydroshare/hydroshare#1692]
These are a few features for HydroShare GIS that are not very urgent and depend on hs_restclient functionality that is does not yet exist (as far as I know).

- [ ] At project creation/save time, dynamically fill out the spatial coverage metadata associated with the Map Project Resource. 
- [ ] At project creation/save time, dynamically fill out the related resources metadata associated with the Map Project Resource to include the relationship "has part" (see http://dublincore.org/documents/2000/07/11/dcmes-qualifiers/) for each resource/file that is part of the map project.  This will require extending the relations that hydroshare supports to include "has part".  @hyi or @pkdash could do this when you get to it.
- [ ] Provide an option for users  to add the relation "Part of" to resources included in the map project.  This has to be an option as you may not have write privileges on the resource being included, and may also not want to change the resource being included if the map project is temporary. (@dtarb I'm not exactly sure what you mean by this one)

@alvacouch @pkdash Is it possible to update a resource's metadata through the REST API? Also, it seems we would need to handle assigning these relationships (such as "has part") to a resource through the REST API... ?

**Comment by dtarb** [comment]
Explaining what is intended with the Part of.  Metadata for each resource may include relationships.  On a resource landing page in edit mode you can see a related resources tab.  There is a button to add relation.  There is then an option to choose "Part of" or other choices and fill in the URL of another resource.  For a resource that is added to a GIS map project, we should fill in the "Part of" relation ship to point to the map project resource so that anyone accessing the resource can find a map project that it is part of.  However there are management considerations involved.  I suggested that adding this relationship should be optional because you may not have permission to change the resource being added to the map, or even if you do have permission, may not want to add the relationship.

**Comment by pkdash** [comment]
@shawncrawley There is currently work in progress for a new REST endpoint to support metadata update for GenericResource. @alvacouch can provide more details on this. The `relation` metadata should meet your requirements which this new REST endpoint I assume will be supporting as this element is part of the core metadata elements. Once this endpoint in implemented I can update the restclient to use it.

**Comment by pkdash** [comment]
@shawncrawley The hs_restclient latest version (1.2.6) should support the above metadata update requirements. @shawncrawley or @zhiyuli Can one of you test it and then close this issue?

**Comment by danames** [comment]
It has been several months since this list of requested updates to the rest client was posted by @shawncrawley. Who is in charge of the REST client at the moment? Is it still @pkdash ?

**Comment by dtarb** [comment]
@aphelionz is now in charge of the REST client.

**Comment by danames** [comment]
@pkdash on Feb 1 said that the metadata update via REST client is working now. So if that is the case, then the only part missing might be the "Is Part Of" relationship management that @dtarb described on Dec 6, 2016. @aphelionz  can you tell us if this has been implemented? @dtarb if "parts" has not been implemented yet, do you still see it as a priority?

**Comment by pkdash** [comment]
@danames @dtarb @aphelionz "Is Part Of" is stored as a 'relation' core metadata element. It has been implemented.

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/tethysapp-hydroshare_gis#15
