### ISSUE TITLE
Should groups have UUIDs?

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1695]
@aphelionz @dtarb @horsburgh  In the original design docs, group names were not unique and groups were identified by UUIDs. This allowed us to provide an opaquely defined "landing page" for a group as well as powering REST functions on groups. At present, there are no UUIDs for groups and the group name is unique. This provides some encoding challenges in identifying a group in a REST request, and the option of using the record ID is rather ugly. This also means that the choice of a group name -- unlike a resource name -- is globally constrained, which is not particularly user-friendly. 

Are UUIDs for groups (and non-unique group names) desirable?

**Comment by alvacouch** [comment]
(This is separate from the other issue I found, which is that groups and access control are conflated. These really should be separated into a group profile object and an access control object.)

**Comment by pkdash** [comment]
I assume we are using record ID for users so I am wondering why it can't be used groups.

**Comment by dtarb** [comment]
I agree that we should use an ID that is not the name for groups, so that the name does not have to be unique and can be changed without breaking things.  I am not convinced that it has to be a UUID.  I could be quite satisfied (perhaps more satisfied) with the simple numbering system we now seem to have for groups.  The first group was number 2 and we are up to about 21.  A number like 20 or even 4284 is easier to work with than a UUID.  There are two reasons for considering a UUID (that I know of)

1. The social reason of having group identifiers opaque so people can not guess at and search for non public groups.  This is not a strong need in my mind, and to me is outweighed by the simplicity of a number.
2.  Separating group unique identifiers from the index used for them in a database table.  This is a technical reason that may make coding easier, or more robust, but how compelling this is I do not know.

**Comment by horsburgh** [comment]
There may also be implications if we have an API for group functions. I suppose an integer identifier is as arbitrary as a UUID.

**Comment by alvacouch** [comment]
Resolved: groups should not have UUIDs. Original design is no longer desirable.
