### ISSUE TITLE
Need to address versioning in resources

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#170]
Right now, the structure of a resource bag that I download from HydroShare contains a folder that I am assuming is named to represent the version.  For example, the file I just downloaded for this resource (http://dev.hydroshare.org/resource/f5e4c6083e8d4e91be216295f7b6282e/) was named f5e4c6083e8d4e91be216295f7b6282e.zip.  So, the zip file is named with the GUID for the resource.  This is fine.  But, when I unzip the file, I get the following directory structure:

2015.02.24.18.03.01 (folder)
.....data (folder)
..........contents (folder)
...............TWDaniels_Temperature.csv (file)
..........visualization (folder)
..........resourcemap.xml (file)
..........resourcemetadata.xml (file)
.....bag-info.txt (file)
.....bagit.txt (file)
.....manifest-md5.txt (file)
.....tagmanifest-md5.txt (file)

This is all as expected, except for the base folder of the resource, which I would have expected to be named using the GUID for the resource rather than a date tag (which I am assuming HydroShare is using as a versioning mechanism).  There are a couple of implications here:

1. When I unzip 2 resources on my computer to the same folder, they are no longer identified by their GUID unless I dig into the content files.
2. Our "Formal Publication of HydroShare Resources" document states that new versions of a resource will receive a new, unique HydroShare identifier rather than being stored as a dated folder under a single identifier for all versions.

Resolution of this issue will affect the URI patterns in all HydroShare resource map documents (see #169).

**Comment by horsburgh** [comment]
@hyi - we had an email discussion about resource versioning, so I'm going to assign this one to you.

**Comment by hyi** [comment]
@horsburgh sounds good. Will work on this after I get other priority issues worked out.

**Comment by hyi** [comment]
@horsburgh I believe the new bagit workflow implementation had already resolved this issue. I checked on both www and dev and made sure the downloaded bag, once unzipped, had the base folder named with resource uuid rather than a date. Could you check (either on www or dev) and see whether this issue is resolved already?

**Comment by horsburgh** [comment]
@hyi - I think we have addressed the technical elements of this issue, but not necessarily the title.  Versioning of resources is still an issue that I think we need to work through.  Should we close this issue and open a new one that more appropriately describes what is left to do with versioning?

**Comment by hyi** [comment]
@horsburgh Yes, that is what I thought exactly. In fact, I am in the middle of picking up and replying an old email thread on bag versioning to layout breakdown of tasks for initial bag versioning implementation. It'd be great if you can create an issue on bag versioning adding/modifying my breakdown of tasks - email forthcoming shortly.

**Comment by hyi** [comment]
@horsburgh Should we close this issue since the technical elements of this issue has been addressed by the new bagit workflow implementation, and then recreate an issue specifically for resource versioning according to your design document? Alternatively, we can reuse this issue by adding specifics from your design document, whichever you think is more appropriate. Since resource publication implementation has prerequisite issues to be addressed first, I am planning to work on resource versioning after I get on-demand solr search index update done first, so it'd be great if you can transfer resource versioning specifics from your design document to either this issue or a new issue (after closing this one) for my upcoming resource versioning work.

**Comment by horsburgh** [comment]
@hyi - I'm closing this one as the technical part of it is resolved. I will create a new issue to deal specifically with resource versioning according to our latest thinking in the document.
