### ISSUE TITLE
Terms of use - Page revamp

### ISSUE THREAD

**Issue by Maurier** [hydroshare/hydroshare#1714]
I will be restyling this page to match the style of the rest of the site.

![image](https://cloud.githubusercontent.com/assets/2448568/21119808/72b46954-c081-11e6-847b-9d4b4f0d91a6.png)

**Comment by dtarb** [comment]
I'd like @rayi113 to weigh in here.  Perhaps we should put all our legal and fine print documents in pages.hydroshare.org so that they can be more easily edited (without working with code).  I would be in favor of such a decision.  Are there any drawbacks.  If we do this then no restyling is necessary just resetting the links to pages.

**Comment by horsburgh** [comment]
If it's already a separate page anyway, I vote for putting them in pages.hydroshare.org.

**Comment by pkdash** [comment]
@mauriel133 What's the status of this issue?

**Comment by mauriel133** [comment]
This is pending discussion. I like Jeff's idea of moving them to the Help pages. However, I could fix the layout on this current pages in a very short time if needed.

**Comment by horsburgh** [comment]
I still vote for moving this to pages.hydroshare.org

**Comment by aphelionz** [comment]
I can take this as part of my pages revamp
