### ISSUE TITLE
Science metadata XML document for publicly shared resource missing Publisher element

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#172]
Our science metadata specification document states that the Publisher element is required for publicly shared or formally published resources.  Neither of the resources that I just publicly shared in dev.hydroshare.org have a Publisher element in the science metadata XML document.

**Comment by dtarb** [comment]
I do not think that Publisher should be required for a resource to be made public.  Publisher should only be required for formally published resources (i.e. ones that are assigned a DOI).

**Comment by horsburgh** [comment]
@dtarb - so, should we assume that this will be implemented when we have the capability to formally publish resources and close this issue?

**Comment by dtarb** [comment]
While I said that publisher should only be required for a resource to be formally published, this should not preclude the publisher field being filled in earlier.   

There are also some choices that may still need to be made.

1.  Publisher is always HydroShare.
2.  Publisher is some other organization using HydroShare to publish its resources.

If it is 2, then a user editing a resource needs the capability to fill in the publisher information, and publisher should appear in the XML as soon as it is filled in.

I suggest the following (simple) solution that accommodates both.  Have the publisher field be filled in as "HydroShare" by default when a resource is created, but then editable by a user with change permissions in case they want to change it.  Then since it is filled in, it will be in the XML document.

**Comment by pkdash** [comment]
If we want the existing resources to have the 'publisher' element in xml document, we need to implement creation of the element as part of resource creation before the manual resource migration. I guess if we make the publisher element editable we can always add this data anytime.

**Comment by dtarb** [comment]
We should avoid the reaction to want to do any change that we ever want before the manual migration.  There will be changes in the future as the system evolves that come after the manual migration and we'll need to figure out how to include them.  That said, if this one is simple enough and we want to do it now, that's fine.

**Comment by horsburgh** [comment]
@dtarb - as a policy decision, I'm not sure we want to allow users to just override the "Publisher" element with whatever text they want to specify. This is a policy decision that we need to be clear on before we implement. The HydroShare data publisher's agreement should probably ask the user to assert that they have the right to publish the content they are publishing when they push the button to publish it. I see some of that on the terms of use page, but I'm guessing not very may people have read that page.  

I understand the use case of referenced resources that may be published/hosted elsewhere. We should support creation and sharing of resources of that type, but I'm not sure we want/need to assert anything about the publisher of those resources. And, I think we shouldn't allow users to formally "publish" referenced resources because they are, in effect, already published in another system.

I suggest the following:

1. "Sharing" a resource is not the same as formally "publishing" a resource.
2. For a resource to become formally "published" within HydroShare, it's content files must reside in HydroShare. The implication of "publishing" is that a DOI would be created and we want that to point at immutable content under HydroShare's control.
3. Resources formally "published" within HydroShare are published by HydroShare - e.g., HydroShare is the publisher. Users would never see an option to specify the publisher.  It would be automatic.
4. When a resource is formally "published" within HydroShare a "Publisher" element gets added to that resource's metadata.

**Comment by dtarb** [comment]
@horsburgh I agree on your points 1 and 2.  However on 3 and 4 I differ.  I think that there is a case for an organization to use HydroShare as its website for publication.  HydroShare is then not the publisher.  It is the resource hosting system that facilitates an organization doing the publishing.  The organization using HydroShare in this way would then be the publisher.  I think we should facilitate this use case.  It allows organizations to take greater responsibility for their data.  I think that there are precedents for this sort of arrangement.

I agree that our data publication agreement needs to be reviewed.  We should create separate issues to do and track this, and that we need a positive affirmation of adhering to the agreement to be built into the coding of publication functionality.  Please help with this.

**Comment by pkdash** [comment]
@hyi I think this issue should be resolved as part of issue #15

**Comment by hyi** [comment]
@pkdash I am not sure whether issue https://github.com/hydroshare/hydroshare/issues/15 would resolve this issue completely. Resource publication will add a Publisher metadata element, but it may not address the user case as @dtarb stated above. @horsburgh @dtarb what do you think? Should we keep this issue as separate from the issue https://github.com/hydroshare/hydroshare/issues/15 that addresses resource publication?

**Comment by horsburgh** [comment]
@hyi - I think we can resolve this issue with a policy decision.  The technical implementation of publication is described in #15 and we should stick with that issue. One of the following needs to be chosen and then we need to implement it:

* HydroShare is listed as the publisher for all formally published resources for which content exists in HydroShare
**OR**
* HydroShare also allows other organizations to publish content in HydroShare and be listed as the publisher (instead of HydroShare).

For simplicity's sake, I vote for the first option.  Also, I'm not sure why we would want to make arrangements that would seemingly reduce the role of HydroShare in publication.  Why would we make a deal with another organization to let them be the "publisher" when we are on the line to provide all of the "publication" functionality?  I suppose if they were to pay for this right, that would be awesome, but without people lined up to do so, I hesitate to recommend implementing it.  Plus, I'm not sure we couldn't add the functionality to do the second one later on.  And, I don't think we would want to enable that to happen unless the other organization was in some way partnered with us, in which case the setting of the "Publisher" element would likely be automated as part of that agreement anyway.

What I don't think we should do is allow individual users to override or set the "Publisher" element.

**Comment by hyi** [comment]
@horsburgh @pkdash @dtarb I agree with @horsburgh's comment above. @dtarb What do you think?  Should we resolve and close this issue and go with the first option as listed by @horsburgh above which is to be addressed when resource publication will be implemented?

**Comment by dtarb** [comment]
@hyi please go ahead and implement this with HydroShare as the publisher.  However please have this be a metadata element that could be flexible, changed in the future, and not necessarily be the same for all resources in HydroShare.  Also I think this element should be specified before the resource is published, so that the full resource with publisher metadata element can be reviewed and seen to be complete/correct before the resource is published.

I am working on and seeking advice on the following policy issues
1.  Should the publisher be HydroShare or CUAHSI.  I hope to have an answer soon.
2.  Should HydroShare be a platform that can host resources published on behalf of another organization.  This may take a bit longer to sort out.

So, while in the implementation the default right now should be HydroShare, please make the implementation flexible enough so that if we decide to have other publishers in the publisher field that it is not hard to implement.

**Comment by hyi** [comment]
@dtarb @horsburgh @pkdash Can this issue be closed?

**Comment by pkdash** [comment]
@hyi, @horsburgh and @dtarb I think this issue can be closed. When there is a need to allow the user to update the publisher element, we can make that change.
