### ISSUE TITLE
SWAT REST API fails test in federated mode

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1724]
When in "local irods federated mode" as invoked through `irods/use_local_irods.sh --persist`, an error occurs in the SWAT REST API tests as follows: 
```
Traceback (most recent call last):
  File "/hydroshare/hs_core/tests/api/rest/test_scimeta_swat.py", line 52, in test_put_scimeta_swat_model_instance
    self.updateScimeta(pid, sci_meta_new)
  File "/hydroshare/hs_core/tests/api/rest/base.py", line 195, in updateScimeta
    msg=str(json.loads(response.content)))
AssertionError: [u'Resource metadata does not contain a resource ID that matches resource map resource ID f67d159730934003838df113981b4d7e.']
``

**Comment by hyi** [comment]
@alvacouch Hmm, this test failure has nothing to do with iRODS federation. I only executed those federation-specific unit tests I added one by one locally and they all passed, and Michael run all tests including federation-specific unit tests on dev through Jenkins via local irods containers and they all pass, so I am not sure whether this one fails. If you can quickly figure out the reason why this one fails, it'd be great; otherwise, I'd suggest just to disregard this local test failure since it is not irods federation related.

**Comment by alvacouch** [comment]
@hyi I am running the same test on develop in federated mode to see if it repeats. If it does, then I will disregard. If not, I will conclude that there is something about my solution that is not being tested properly, and that somehow I broke federation.

**Comment by hyi** [comment]
@alvacouch Sounds good.

**Comment by mjstealey** [comment]
@alvacouch - Believe there are 5 federated, or **user_zone** related tests run nightly.
Reference: http://ci.hydroshare.org:8080/job/nightly-build-test/155/testReport/ 
- search term "user_zone" in the above list of tests

The trigger for this is to set the `REMOTE_USE_IRODS` variable to be True in local_settings.py

Excerpt from the Jenkins build script for nightly build.
```
# Remote iRODS proxy user configuration
sed -i "/\<REMOTE_USE_IRODS\>/c\REMOTE_USE_IRODS = True" ${SETTINGS_FILE}
```

**Comment by hyi** [comment]
@mjstealey Setting ```REMOTE_USE_IRODS``` to True alone is not sufficient to run federation zone tests. Refer to https://github.com/hydroshare/hydroshare/blob/develop/hs_core/testing.py#L41..L45 for the conditions needed to run federation zone tests. Specifically, in addition to having ```REMOTE_USE_IRODS``` set to True, settings.HS_USER_ZONE_HOST needs to equal to 'users.local.org' and settings.IRODS_HOST needs to equal to 'data.local.org' as well, which means local irods containers need to run. Otherwise, all test scenarios would exit out without really being executed even though the test results show success. The conditions used ```NOT``` logic which is a bit confusing. Most likely you have already started irods containers on dev for federation zone tests to run through, but want to clarify here just in case.

**Comment by mjstealey** [comment]
> Setting REMOTE_USE_IRODS to True alone is not sufficient to run federation zone tests.

@hyi - Yes, very true, and thank you for pointing that out. There was an implicit assumption in my comment that @alvacouch was already running the [use-local-irods.sh](https://github.com/hydroshare/hydroshare/blob/develop/irods/use-local-irods.sh) script in his local environment which sets much of what is needed.

**Comment by hyi** [comment]
@mjstealey Great! In fact, your nice script use-local-irods.sh script already takes care of all these needed settings in local_settings.py including this ```REMOTE_USE_IRODS``` as shown here: https://github.com/hydroshare/hydroshare/blob/develop/irods/env-files/use-local-irods.env#L18. So as long as that use-local-irods.sh script is run, there is no need for users to do anything extra, federation just works out of the box which is really nice.

**Comment by alvacouch** [comment]
@hyi @mjstealey **The swatshare test succeeds in develop in federated mode in my environment.** Investigating what is different about my particular branch that could cause problems. Will start clean, reset all, delete icat* persistence containers, and try a global test on my branch to see if accumulated state is a problem.

**Comment by alvacouch** [comment]
@mjstealey @hyi **Starting clean, all tests passed on my PR.** There seems to be some kind of state problem that accumulates as the iRODS instance is used. When I say clean, I mean a total reset: delete icat* state, reset all, kill all running containers, etc.

**Comment by alvacouch** [comment]
@mjstealey @hyi The state problem continues; repeating the swatshare test causes a failure.

**Comment by Castronova** [comment]
@hyi @alvacouch Has this issue been resolved?

**Comment by hyi** [comment]
@Castronova It looks to me this issue can be closed, but will defer to @alvacouch on whether this can be closed or not.

**Comment by alvacouch** [comment]
Can be closed.
