### ISSUE TITLE
URGENT - develop branch requires investigation regarding my-resources and bag download

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#1730]
@all - Existing develop branch passes all tests however it is not functional.

1. Resources not appearing in my-resources page
2. Bag download fails with `<django_irods.storage.IrodsStorage object at 0x7f8fb43dd250> is not JSON serializable`

Please refrain from new merges until this is resolved.

**Comment by mauriel133** [comment]
Resources not appearing in My Resources page is most likely caused by conficts with the UI unit test PR. I will investigate this morning and push a fix.

**Comment by mjstealey** [comment]
@hyi - hoping you might have some intuition regarding the **django_storage** error. 

From this side I'll try the following
- roll back the dango_irods submodule reference
- roll back the hs_docker_base image build
- combination of the above

**Comment by mjstealey** [comment]
> I will investigate this morning and push a fix

Much appreciated!

**Comment by aphelionz** [comment]
@mauriel133 and @hyi Thank you both - is it possible to write a couple extra functional automated tests will cover this case in the future in case a similar regression happens?

**Comment by hyi** [comment]
@mjstealey I have no idea on the IrodsStorage error - never saw it before. I tried to create a resource on dev just now, but it appears I cannot even create a resource, so I cannot see a more detailed error message on this myself. I tried to look into the logs on dev, but cannot find any relevant error messages in the logs. I did pull the latest develop in my local environment yesterday, but I did not rebuild, instead I only did docker-compose stop then start, so it may not pick up all the changes in my local run time environment, but I did not run into any issues because of that. If you can paste the detailed error message including stacktrace if possible, I'll see if I can have more clues, but at this point, I am clueless on the bag download issue.

**Comment by aphelionz** [comment]
Paging @alvacouch because that looks like a Django Rest Framework serializer error

**Comment by mjstealey** [comment]
@hyi - You should be able to create a resource now. **NOTE** you will not see it in your my-resources page, so you'll want to make it public so that you can find it later on.

The reason you were not able to create a new resource was that the **Hydroshare Author** group had not yet been updated. You will need to do this locally as well since our development database does not already capture all of the required permissions for this group.

The nightly builds are generic, so you'd be able to check things in the admin panel as you would locally.

<img width="1161" alt="screen shot 2016-12-16 at 11 01 04 am" src="https://cloud.githubusercontent.com/assets/5332509/21269093/59527810-c37f-11e6-8553-211c8954664d.png">

**Comment by mauriel133** [comment]
I've made the following PR which should fix the resource listing issue. It needs follow up concerning UI unit tests.

https://github.com/hydroshare/hydroshare/pull/1731

**Comment by mjstealey** [comment]
PR: #1732 looks to resolve the bag download issue.  It reverts the hs_docker_base image back to 1.7.5 + external Dockerfile additions. Will need to revise the proposed hs_docker_base:1.10.0 image to avoid future issues.

**Comment by mjstealey** [comment]
@mauriel133, @hyi, @pkdash, @aphelionz - Have manually modified https://dev.hydroshare.org to be equivalent to the result of merging both PR #1731 and PR #1732 into develop. 

Issues look to be resolved, can you verify?

1. That my-resources page renders resources
2. That bag download works

**Comment by mauriel133** [comment]
Listing resources in My Resources page is fixed at https://dev.hydroshare.org

**Comment by hyi** [comment]
@mjstealey I have just tested on dev and can verify both issues does get resolved on dev now. I'd suggest just to merge both PRs so we can move forward with development. As @mauriel133 commented on my resource page PR, we need to follow up with Alex on UI testing since those couple of JavaScript calls added by Alex for UI testing purposes are commented out to fix this my resources page issue. As for reverting docker base image, I have no idea on how the newer docker image caused this bag download issue, but since it fixed the issue and you are on top of it, a +1 from me on getting it merged.

**Comment by mjstealey** [comment]
Resolved
