### ISSUE TITLE
My resources filter facet counts

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#1759]
I think these counts are not correct. I own 7 resources. I assume the counts for "Editable by me" and 'Viewable by me" should be 0.  It seems the backend gives the right counts for each of these facets. Needs fixing JS code. 

![image](https://cloud.githubusercontent.com/assets/2523434/22044258/05b4682e-dcd1-11e6-8564-e85d994c8984.png)

**Comment by hyi** [comment]
@pkdash I am thinking perhaps "Editable by me" should include those "Owned by me" after all since "Owned by me" is also "Editable by me," hence I think logically it may work as it should.

**Comment by pkdash** [comment]
@hyi Only for this facet requirements we had to implement a very specific method ```user.uaccess.get_resources_with_explicit_access()``` - which is very complex.  We call this method 3 times in the view to generate the counts for each of the facets. If the requirement is as shown above then we could just use functions - ```user.uaccess.owned_resources(), user.uaccess.edit_resources() and user.uaccess.view_resources()```

**Comment by alvacouch** [comment]
@xuezhaokun Please look at this and see if you can address it. The only function that works correctly is get_resources_with_explicit_access.

**Comment by pkdash** [comment]
@xuezhaokun The problem is in the JS code if that would save time in debugging and fixing.

**Comment by alvacouch** [comment]
Reclassified as "my resources". Does not apply to current discovery interface.

**Comment by Lizabrazil** [comment]
Can we rethink this design? I believe most users want to filter by "Shared with me", "Owned by me," and "Owned by others"  
Google does this: 
![image](https://user-images.githubusercontent.com/13852599/57247425-d1e76780-700d-11e9-8963-ba7489c0dea1.png)
![image](https://user-images.githubusercontent.com/13852599/57247460-e3c90a80-700d-11e9-90db-0e743b544938.png)

**Comment by horsburgh** [comment]
The "Added by me" filter already shows you resources that you have added to your My Resources, but are owned by others. The "Added by me" filter name is consistent with the action that a user takes to click the "Add to my resources" button on the landing page for a resource that they do not own.

Am I missing something?

**Comment by dtarb** [comment]
This is an issue related to facet counts.  I would discourage using it for discussions about redesign.  If there is to be a redesign discussion, it should be opened as a new issue, or as a separate redesign discussion.

With respect to correcting the facet counts, the issue is quite stale as the image for facet categories in the initial has been superseded.  Based on my testing, it seems to me that facet counts on the current My resources page seem correct.  Therefore I am closing.  If there is a separate issue to be raised, or you feel this is incorrect, please feel free to re-open or create a new issue.
