### ISSUE TITLE
Metadata on latitude gives an error- where is the error?

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#1763]
Hi @gantian127  Do you mind taking a look at this resource? When you view the data in the Extent tab, you can see that the coordinate bounding box has an error.  

This is the list of available data is for the 2015 Livneh Colorado ftp site - 1950-2013  VIC and MET - and 1915-2013 MET to be determined link...
[Gridded climatology locations (1/16th degree): North American extent](https://www.hydroshare.org/resource/ef2d82bf960144b4bfb1bae6242bcc7f/)

This was generated in ArcGIS, add Excel Table, View XYdata, Save As a Shapefile. The default is apparently NAD27. 

Thanks!

**Comment by dtarb** [comment]
@ChristinaB Please provide permissions to the HydroShare developers group to see the contents of this file so we can look at it and debug it.  You have made it discoverable, which lets us see the metadata but not the data.

Looking at the metadata it indicates that the spatial coordinate reference system is NAD_1927_UTM_Zone_10N.  This is a UTM projection and the coordinate string indicates that horizontal units are meters.  Latitude of origin is the equator.  The extent coordinates given in the metadata are North 52.9, South 14.6.  These would according to the projection string information be interpreted as meters north of the latitude of origin.  52 m north of the equator is practically on the equator so the coverage map is plotting this in the right place.

The numerical values of 52.9 and 14.65 suggest degrees rather than meters.  Looking at the original file may help figure out whether the original file is wrong, or the harvesting of metadata did a conversion on extent that is incorrect.

**Comment by dtarb** [comment]
@ChristinaB the ftp link in the abstract of the resource you mention is malformed, hampering access to it.

**Comment by dtarb** [comment]
Closing as appears to be due to user error and without access to the resource cannot replicate.  @ChristinaB enable access to the resource and re-open if you want this looked at.
