### ISSUE TITLE
Copy resource improve language

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1769]
Please add the word "**License**" to the end of license statements for resource page and copy pop up message, so we get a complete sentence such as:
This resource is shared under the Creative Commons Attribution CC BY **License**.

**Comment by hyi** [comment]
@dtarb Just to confirm: do you want the word "License" bolded as shown in your comment above? It appears to me the answer is yes, but want to confirm with you just in case.

**Comment by hyi** [comment]
@dtarb @pkdash Also, since the license statement is stored in our metadata, hence in Django database and metadata xml file, to simplify things, I don't want to modify the metadata just to add the word "License" to the end of license statement, but only want to add the word "License" to the page and message display without updating metadata. Let me know if you see any issues with this approach.

**Comment by hyi** [comment]
@dtarb @pkdash Have created a PR for this issue and requested @pkdash to review.

**Comment by hyi** [comment]
@dtarb I have merged the PR after getting a +1 from @pkdash that added the bolded **License** wording as you commented above. If any further changes were requested, I'd create new PR to address.

**Comment by dtarb** [comment]
I did not actually want the word bolded.  I had shown it bolded to indicate it was an addition.

I am OK with the word appearing on the display and not in the metadata, since in the metadata it is probably inside a "rights" metadata field.

**Comment by hyi** [comment]
@dtarb Have created a new PR just to unbold the word **License**. I will merge it after Jenkins give a green check.

**Comment by dtarb** [comment]
Sorry it is so much trouble just to change style.

**Comment by pkdash** [comment]
@dtarb I assume this has been fixed. See if you can close it.

**Comment by hyi** [comment]
@dtarb See if the language change is to your satisfaction on www and close it if it does.

**Comment by dtarb** [comment]
This change does not seem to have made it into www yet (nor any staging machine I can find).  Below is what I am suggesting, to just make the sentences complete.
![image](https://cloud.githubusercontent.com/assets/3456833/22516659/b4ac9084-e863-11e6-9b22-ef55b96923bb.png)
![image](https://cloud.githubusercontent.com/assets/3456833/22516707/e8714112-e863-11e6-8d83-484c7aeceaed.png)

**Comment by hyi** [comment]
@dtarb Sorry, I thought it had made into deploy, but apparently did not. You can test it on https://dev.hydroshare.org on which I have just tested and verified this language fix made it into dev. You do have to register for a new account on dev, though, since dev does not use production database for deploy. See if you can test on dev and close this issue if it works on dev to your satisfaction. Thanks.

**Comment by dtarb** [comment]
tested on dev
