### ISSUE TITLE
Attempt to copy an app resource results in the following error

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1779]
![image](https://cloud.githubusercontent.com/assets/3456833/22186896/937661de-e0ba-11e6-85c5-482f24d63f50.png)

**Comment by hyi** [comment]
@dtarb @jsadler2 @zhiyuli This PR can be treated as a duplication of this issue: https://github.com/hydroshare/hydroshare/issues/1601 since copying and versioning are using the same underlying code/method for metadata copying, and the exact same error message for apps resource is documented in that versioning issue as well. This issue is caused by the way the resource handles metadata update for multiple-choice checklist in many-to-many relation in the model. Specifically, Django's ```model_to_dict``` method returns a list of pks for ManyToManyField, which is not accounted for in app resources and model instance resources. There is a PR https://github.com/hydroshare/hydroshare/pull/1757 created by @mohamedmorsy for SWAT model instances to account for the list of pks returned for ManyToManyField when adding metadata elements, which should be followed to fix issues for apps resource as well. @zhiyuli I assume you are in charge of apps resource, so I am reassigning this PR to you. Feel free to reassign if needed and let me know if you have questions.

**Comment by zhiyuli** [comment]
@dtarb @hyi @mohamedmorsy 
OK, I was able to duplicate this error on my local VM. Will look into this today.
@mohamedmorsy Is your fix for model res type merged or not?

**Comment by mohamedmorsy** [comment]
@zhiyuli I did merge it yesterday. This fix was done for both SWAT and MODFLOW model instance resource types.

**Comment by zhiyuli** [comment]
@mohamedmorsy thanks. Will research your changes.

**Comment by mohamedmorsy** [comment]
@zhiyuli you can find the changes here https://github.com/hydroshare/hydroshare/pull/1757/files

**Comment by dtarb** [comment]
Tested OK on www
