### ISSUE TITLE
Integrate RHESSys model resource instance with new resource metadata model

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hydroshare#178]
Re-implementation of #60 on top of version of develop with new resource metadata model.

**Comment by selimnairb** [comment]
This is phase one, including the resource data model including support for model outputs.

**Comment by hyi** [comment]
@dtarb I am assigning it to you for re-delegating this now that Brian does not work on HydroShare.

**Comment by goodalljl** [comment]
@Castronova I see this is assigned to you. Should it be? I'm not sure who else on the team. I'm thinking this one should be put on the back burner. Thoughts?

**Comment by Castronova** [comment]
@goodalljl I don't think it should be assigned to me.  I agree that this should be on the back burner.

**Comment by dtarb** [comment]
@goodalljl can you chat to Larry Band about this and decide a path forward.  We have RHESSys as part of our JupyterHub platform, but I am uncertain about how this saves its output in HydroShare.  It would be more sustainable for RHESSys (and other models) if model instances could be saved using the generic model instance resource, just with a name attribute RHESSys.

**Comment by goodalljl** [comment]
@dtarb Yes, I'll talk with Larry about this. Talking with his student Charles, they are hoping RHESSys  in JupyterHub could be fixed soon. 
@Castronova I think this falls onto your plate. I believe the JupyterHub changes you made to get LandLab working broke RHESSys in JupyterHub. Talking to Dave, he said the plan was to roll back JupyterHub after the LandLab workshop so that RHESSys would work. What do you think?

**Comment by goodalljl** [comment]
Moving to backburner. We don't resource at the moment to address this.

**Comment by dtarb** [comment]
@goodalljl @Castronova RHESSys is one of the models supported on JupyterHub (JH), and we should plan for this to continue.  Instead of putting this on Backburner, I would prefer to see a simpler solution where we do not have a separate RHESSys model instance type, but rather just use the generic model instance resource to hold RHESSys model instances, and have JH facilitate to saving to this.  This may change the work from one of developing new resource type (which is a heavy lift) to one of documenting how to use an existing resource type with any model (in this case RHESSys).  I think this may be a more sustainable solution.

**Comment by goodalljl** [comment]
@dtarb @Castronova We don't currently have a RHESSys model instance resource type. Users can now use a generic model instance resource type to store a RHESSys model instance. I believe we already have documentation in JH on how to work with RHESSyS model instances. The current issue is that RHESSys in JH is currently broken and we need @Castronova to fix it. Our thought is the changes to JH from the LandLab workshop may have broken RHESSys. So what you are describing @dtarb may be close to ready. I put the development of a RHESSys specific model instance resource type (this specific issue) on the back burner because this is something we don't currently have support to do. We may never want to do this if we start to promote more the use of generic model instances rather than specific model instances ... we'll see.

**Comment by dtarb** [comment]
@goodalljl agreed.  If (WHEN) we get RHESSys working in JH (and @Castronova is aware of this and https://github.com/hydroshare/hydroshare-jupyterhub/issues/97 may in part address this) and we can save RHESSys model instances using the generic model instance resource type, then we can, I think, avoid the need for making a separate RHESSys specific model instance type.

**Comment by dtarb** [comment]
No longer applicable
