### ISSUE TITLE
Publishing Gives Error

### ISSUE THREAD

**Issue by AmberSJones** [hydroshare/hydroshare#1792]
I just attempted to publish a new version of a previously published resource. I created a new version, made some edits, and proceeded through the screens for formal publication. The result was an error:
![image](https://cloud.githubusercontent.com/assets/5023186/22314872/ae7e808e-e320-11e6-8922-2b5fa4dbd671.png)

**Comment by horsburgh** [comment]
Hmmm... Super informative error message... 

@hyi - any suspicions about what happened?

**Comment by hyi** [comment]
@AmberSJones @horsburgh After some investigation, I found the issue and have just created a PR https://github.com/hydroshare/hydroshare/pull/1793 to fix this regression error. I have also manually applied the change as a hot fix on www production server since without the fix, resource publication will no longer work. Not sure how this happened. My speculation is that can_be_published used to be a method but somehow was changed to a property in some recent PR merges without changing the calling method, hence causing an TypeError, which prevents resource publication to work. @AmberSJones Can you try to publish this resource again and see if you can publish this resource without the issue now?

**Comment by hyi** [comment]
@mjstealey I have manually applied the fix on www as a hot fix since it is a regression issue which causes resource publication no longer to work. After @pkdash give a +1 to that PR, I will merge it to close the loop for this issue.

**Comment by horsburgh** [comment]
@hyi - thanks for working on this so quickly. @AmberSJones can report back after testing.

**Comment by AmberSJones** [comment]
I published successfully. Thanks for the quick response. I'll close the issue.
