### ISSUE TITLE
Organization not required to register, but to update profile

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#180]

**Comment by dtarb** [comment]
This issue is the tip of the iceberg of a bigger problem.  We have to implement use tracking as specified in the use tracking document written in 2013 - see https://my.alfresco.com/share/s/qg6hiagfQpuNnYW34Dyvng.  This requires knowing the following for each user
* Type (from a list University Faculty, Student etc - see doc)
* Institution
* State (e.g. Utah, Texas)
* Country (e.g. US, France)
* Date user was created (should be automatically filled in by system)

The current profile page does not hold this content and is also ambiguous about what is public and what is not public.  My suggestion is that all user information except the email address should be public.  Users should be warned not to include information that they do not want to be public.  I do not think it is a violation of privacy to have type, institution, state and country of a user publicly known in HydroShare.  Things like Phone number, CV, Photo, Description that are optional should not be filled out if a user does not want them to be public.  

I think that type, institution, state and country should be required for each user.  I am ambivalent as to whether this information should be required on the first form requesting an account, or later when they follow the link used to validate their email.  

I would like this issue to be holistically designed by @horsburgh (drawing on experience from ODM2) and then implemented as part of interface improvements by @mauriel133.  But this is not possible for NFIE deployment so I am removing the NFIE label.  Until this is done, we just have to live with this as it is.

**Comment by mauriel133** [comment]
Can be tested at https://park.hydroshare.org

**Comment by mauriel133** [comment]
Fixed with revamp of profile page. Please confirm and close.

**Comment by horsburgh** [comment]
Tested on www. Organization is still not required to register, but it is a required field when you first edit your profile. So, this issue was solved by adding application logic to require organization upon editing the profile. 

Closing.
