### ISSUE TITLE
Mail from developer setups

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#181]
Developer set ups should **not** be allowed to or configured by default to send outgoing mail. This is dangerous, especially as you gain real world users and run into problems that require tests on local versions of the database. Recommend disabling this and using a test email server locally when outgoing mail has to be captured.

**Comment by dtarb** [comment]
I am not sure I understand the danger here.  It seems that we need developer instances to send email so that developers can create accounts and test functionality.  It also seems better to have developer deployments exactly the same as the intended production deployment so that testing is as close to the same as the real thing as possible.  The databases and resource files on developer and production deployments are supposed to be completely separate with the developer ones transient and are disposable if they get corrupted.  Am I missing something?

**Comment by ironfroggy** [comment]
I am just documenting a general practice. There are lots of ways to handle testing mail. We either use the test server (a SMTP server that comes with Python and outputs outgoing mail to the terminal for inspection) or a developer-only enabled middleware that reroutes all outgoing mail to the developers own address or a mailing list (this one is also used on staging environments).

If you never use a copy of the real world database on staging or developer environments, this is less of a concern, but doing so down the road may well come in handy for debugging a problem and if you ever decide to debug something like that it would pose a risk. This is why it is so common to just err on the side of caution and not let staging or developer environments send mail out to the real world unchecked.

**Comment by dtarb** [comment]
Thanks.  At present I think that outgoing email is only used to validate account requests.  We should use it in the future to validate email change requests and may use it to send system triggered notifications.  Certainly I can see that for these we do not want emails from development instances to go to users who registered on the deployment instance, so that erring on the side of caution is good.  I think that we should use a test server for personal development environments and a mailing list for staging environments because multiple developers/testers will need to see email from the staging environment.

**Comment by mjstealey** [comment]
Documentation on how to configure email for developer setup on wiki.
https://github.com/hydroshare/hydroshare/wiki/hydroshare_email_using_gmail
