### ISSUE TITLE
Renew HydroShare SSL certificate - expires on 5/12/2017

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#1826]
@dtarb - Our existing HydroShare SSL cert will expire on May 12, 2017.

![screen shot 2017-02-03 at 8 03 34 am](https://cloud.githubusercontent.com/assets/5332509/22592357/702b8c82-e9e7-11e6-90b6-2b9dcc229047.png)

**Comment by dtarb** [comment]
Should I renew this exactly as it is now or is there any reason for any changes (e.g. consolidate with domain name hosting at namecheap or something else) @rayi113

**Comment by alexlemann** [comment]
Have yall looked at using [Letsencrypt](https://letsencrypt.org/)? With it, renewals can be handled by a cronjob. It looks like HS is using a wildcard cert which [letsencrypt does not support](https://letsencrypt.org/docs/faq/#will-lets-encrypt-issue-wildcard-certificates), but like they say is not always the best option.

**Comment by rayi113** [comment]
From Kelsey@RENCI: From: Kelsey Urgo 
Sent: Monday, February 6, 2017 8:22 AM
Subject: Re: [hydroshare/hydroshare] Renew HydroShare SSL certificate - expires on 5/12/2017 (#1826)

As it stands, the domain is now registered at Namecheap, but is still pointing to Digital Ocean for hosting. Once I actually flip to hosting and DNS records also existing at Namecheap it looks like the GoDaddy SSL cert will need to be rekeyed (because hydroshare will exist on a new server):

https://www.godaddy.com/help/rekey-certificate-4976

I was planning completing this move today or tomorrow. I can send out an email right before I make the switch and then right after it is done.

**Comment by kelseyurgorenci** [comment]
I just realized that the actual host (along with it the key) will not change with the Namecheap move. So this will actually not be a problem. SSL cert can just be renewed as usual on 5/12/2017.

**Comment by mjstealey** [comment]
New cert has been issued and is being migrated to all VMs
