### ISSUE TITLE
Improve formatting of reset password page.

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1835]
When requesting a password reset the update profile page that you go to when clicking the reset email should be better formatted.  It should at least have margins so the fields do not bump into the sides.  Also I would prefer a reset password page not to show all profile update information - just reset the password.

**Comment by pkdash** [comment]
@mauriel133 Can you work on this?

**Comment by mauriel133** [comment]
Yes, I'll take care of it.

**Comment by mauriel133** [comment]
@pkdash, do we have a template for this now?

**Comment by pkdash** [comment]
@mauriel133 I have tried to create a template but was not able to test it since the only way to get to this template is through an email link. On the local development machine, Hydroshare can't send emails. Once the Jenkins deployment work I may be able to deploy this work and see if the new template gets displayed as part of password reset workflow.

**Comment by Maurier** [comment]
@pkdash, is there a template for this I can look at now?

**Comment by pkdash** [comment]
@Maurier You can refer to the branch 1835-password-reset-page and see there is a new page under /theme/templates/accounts/account_update_profile.html. I was not able to test this new page when I was working on this branch. I believe this is the page mezzanine uses which I tried to override here by creating this new html page.

**Comment by aphelionz** [comment]
@Maurier @dtarb We can close this after 1.14 goes out

**Comment by dtarb** [comment]
Looks good on beta
