### ISSUE TITLE
Access control broken/leaking on beta.

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1852]
If I go to the URL of a private resource in HydroShare without logging in the correct behavior is the "The resource you have attempted to access is private" as occurs on www
![image](https://cloud.githubusercontent.com/assets/3456833/22832020/abea9e8e-ef69-11e6-9033-2ac60f2ddcd6.png)

However in the beta test deploy the full landing page is shown with message that you do not have access to the files
![image](https://cloud.githubusercontent.com/assets/3456833/22832072/d421aa6e-ef69-11e6-88ce-9c75646ad132.png)

This should be the behavior for a discoverable resource, not a private resource.

**Comment by hyi** [comment]
@dtarb @pkdash @mjstealey My preliminary investigation revealed that can_view() method on BaseResource class is never called automatically by Mezzanine any more. I suspect it might be caused by removal of ga_resources and ga_ows apps. @pkdash Can you take a look at this also since it looks like a deeper issue related to interplay of components, and the more people to investigate, the faster this issue could be resolved.

**Comment by pkdash** [comment]
@hyi Looking into this. Yes, I am also seeing the can_view() is not called anymore.

**Comment by hyi** [comment]
@pkdash I found the reason why can_view() is not called. I believe can_view() was removed in Mezzanine version 4.1.0 which we are using now and can_move() was added into Mezzanine instead. So that can_view() code has not been called for some time since Mezzanine version was bumped up. However, can_add(), can_change(), can_delete() are all called when visiting a resource page from my resources page, but never called when visiting the same page directly by typing in the resource page url. I believe that was the culprit. Why those page permission functions were called before but not called now when typing in the direct url for resource page? I don't have a clue on this now and suspect there might be some code that got removed from ga_resources are actually needed. Any idea?

**Comment by pkdash** [comment]
@hyi I think now I have single line fix. Testing now. Will be creating a PR soon.

**Comment by alvacouch** [comment]
@pkdash @hyi Yes, it should be fairly simple to fix. Remember that we actually override mezzanine in the ResourcePermissionsMixin.

**Comment by pkdash** [comment]
@dtarb Test on beta to see if got fixed.

**Comment by dtarb** [comment]
It works.  Thanks.
