### ISSUE TITLE
Unable to load file greater than 1 GB from iRODS on beta

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1858]
I received the following error trying to load a file from iRODS into beta.hydroshare.org

![image](https://cloud.githubusercontent.com/assets/3456833/22859530/1f53a2ca-f09c-11e6-8cc7-1cc333c76252.png)

**Comment by dtarb** [comment]
This same error occurs on www.  I am testing with the following file in iRODS nfie.hydroshare.org
/nfiehydroZone/home/public/HAND/HUC6/030203.zip which is 1.2 GB.

**Comment by mjstealey** [comment]
@dtarb - This is expected behavior based on the requirements @hyi had implemented from. The only area from which files greater than 1 GB could be loaded from was the hydroshareuserZone. Anything else was limited to 1 GB, be it http/https/non-federated iRODS zones.

Based on this issue it would appear that you'd like files greater than 1 GB to be available from all iRODS zones, federated or otherwise.

**Comment by hyi** [comment]
@dtarb As @mjstealey explained above, this is working as expected although the error handling could be made better. Let me know if you want to make this issue specifically targeted at better error handling, otherwise, this is working by design and could be probably closed.

**Comment by dtarb** [comment]
If this is desired expected behavior then we can relegate this to a documentation issue.  However is there a good technical reason why we limit file sizes incoming from other iRODS systems.  I can see advantages in using other systems such as Cyverse, where a partnership with them would alleviate some of the burden on us and can also avoid the use of CyberDuck that is sometimes clumsy.  Further, it seems like we work closely enough with NFIE and many NFIE files are bigger than 1 GB, that we should enable this.

**Comment by hyi** [comment]
@dtarb @mjstealey @rayi113 Only files from a federated iRODS zone with HydroShare zone can be leveraged for resource creation with files larger than 1GB, currently only hydroshare user zone is federated with hydroshare zone to handle large files larger than 1GB. Also, our design is that the federated zone will hold the hydroshare resources created from files coming from that federated zone, so that federated zone will become part of hydroshare resource storage iRODS ecosystem.

**Comment by hyi** [comment]
@dtarb @rayi113 @mjstealey This is working as expected at this point based on my further investigation. Since NFIE irods zone is not federated with beta, so the size limit exception is expected on beta when loading files from nfie zone or cyberse. Although NFIE irods zone is indeed federated with hydroshare zone, the localHydroProxy irods account, which is a counterpart of hydroshare zone proxy irods account for holding HydroShare resources, does not exist on nfie zone, which explains why you cannot create resources with files coming from NFIE zone on www now. However, if we want to enable it, we can create localHydroProxy irods account on NFIE zone, then NFIE zone will be treated in the same way as hydroshare user zone on www.

**Comment by dtarb** [comment]
@hyi I understand your comments that the way the system is built now you have the 1 GB limit.  However you did not give any technical reason why we can not have bigger than 1GB files be transferred between iRODS zones, even for non federated systems.  It seems that one of the reasons for iRODS is that these sort of file transfers are supposed to be possible.  I am OK if you want to close this issue and pursue the discussion elsewhere, but I think that 1 GB transfers from non federated iRODS systems should be a supportable.

**Comment by hyi** [comment]
@dtarb You comments make me think more about loading files from non-federated iRODS zone, and I agree we may not need to put 1GB file size limit on it. Although the files transferred to Django server from a non-federated iRODS zone are wrapped into UploadedFile() object in Django for creating resources including metadata extraction, it is not subject to browser client limitation. Let's leave this PR open and I will do some tests and if it turns out there is no technical reasons for the 1GB size limit on file uploads from a non-federated iRODS zone, I will create a PR to remove the 1GB size limit for this so that 1GB size limit only applied to files uploaded from local disk via browser.

**Comment by dtarb** [comment]
Verified that I was able to load a 1.3 GB file from iplant into beta.hydroshare.org, so closing.
