### ISSUE TITLE
Comments and Ratings

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#186]
Simplify the comments and ratings part of the resource landing page.  See resource details mockup in Alfresco release 1 mockups from 10 months ago.  This was developed by @horsburgh.  Comments should be identified by the first and last name of the person who made them followed by the comment. The commenter has to be a hydroshare user so the functionality to add a comment should only appear if the user is a hydroshare user.  The commenter name should be a link to the users profile.  There should also be the ability to +1 a comment and +1 the resource itself.  To +1 you also have to be a hydroshare user.  The commenting system should not require a user to enter their name, username or URL as these should be part of the user profile.  The only thing to fill in should be the text box that holds the comment. 

Some additional rules I suggest 
* A user who makes a comment can delete or edit it later.  No one else can edit a comment, except system administrator who can delete an inappropriate comment.
* A user can comment on a comment (i.e. comments may be nested).  Don’t restrict nesting depth - this will happen naturally.
* If a resource is deleted, the comments associated with it are also deleted.
* If a comment is deleted, comments that are nested on it are also deleted.
* An email with the comment in it is sent to the owners of the resource, indicating that a user has commented on it.
* When a comment is commented on, an email with the comment in it is sent to the original commenter
* A user can turn off receiving emails about comments in their user profile
The first implementation does not need to implement email notifications, however any data structures established should not preclude this.

Assigned to @hyi for initial implementation, to @ironfroggy for comment as to good web practices and @horsburgh for suggestions on layout related to the original mockups and formatting of resource landing pages

**Comment by hyi** [comment]
First phase of implementation for this issue is pushed to github and a pull request has been created to merge it into develop. The following items have been implemented/fixed:
* Only logged-in users can make comments and ratings. Although anonymous users can see comments and ratings section, when they submit their comments, they will be asked to log in first. After they log in, their comments and ratings will show up in the resource landing page associated with the resource. If they don't log in, their comments and ratings will be discarded and will not become part of the resource.
* The commenting system does not require a user to enter their name, email or URL/website and the only thing to fill in is the text box that holds the comment.
* The commenter name is a link to the user's profile in resource landing page.
* Commenters can rate the resource or comments. Instead of +1, now commenters can rate at a scale of 1 to 10, where the scale range can be customized.
* A user can comment on a comment by clicking on "Reply" button. This is managed by threaded comments in Mezzanine. 
* If a resource is deleted, the comments associated with it are also deleted. 

The following items are not yet working/implemented and need further investigation:
* A user who makes a comment can delete or edit it later. No one else can edit a comment, except system administrator who can delete an inappropriate comment. 
Current implementation only allows system admin to delete comments from admin interface.
* If a comment is deleted, comments that are nested on it are also deleted. 
This is associated with the item above, needs to become part of comment deletion workflow.
* An email with the comment in it is sent to the owners of the resource, indicating that a user has commented on it. 
* When a comment is commented on, an email with the comment in it is sent to the original commenter 
* A user can turn off receiving emails about comments in their user profile The first implementation does not need to implement email notifications, however any data structures established should not preclude this. 

Suggest all items above to go into second phase into release 1.5 after the next immediate release 1.4.

**Comment by dtarb** [comment]
We want +1.  We do not want a 1-10 scale.

**Comment by hyi** [comment]
OK. Will revert it to +1 then.

**Comment by hyi** [comment]
Have reverted it back to +1. Also added functionality for email notifications. In summary, only comment deletion by commenter and email notification customization in user profile are yet to be implemented. Others have been implemented for the first phase with further improvements to be done in the second phase when needed. See updated list above for details regarding what have been implemented and what needs further investigation.

**Comment by hyi** [comment]
Further fixed email notification to ensure the email is sent to the resource owners, and if a comment is for another comment, the email is also sent to the original commenter this comment replies to. Also fixed a couple of formatting and styling issues so the nesting comment hierarchy should be displayed on resource landing page. The fix has been pushed to github with a pull request created to merge into develop and deploy to dev or alpha.

**Comment by dtarb** [comment]
Tested and works well enough to close.  Commenter ability to delete their comments to be made a separate issue.
