### ISSUE TITLE
Email All Email Addresses in HydroShare User Profiles

### ISSUE THREAD

**Issue by rayi113** [hydroshare/hydroshare#1867]
Per @dtarb , implement mechanism to email all email addresses in HydroShare User Profiles e.g. for when there is scheduled downtime.

**Comment by dtarb** [comment]
This could be as simple as extracting a list of the emails of all users from the admin page and sending email from a regular email client.

**Comment by mjstealey** [comment]
> This could be as simple as extracting a list of the emails of all users from the admin page and sending email from a regular email client.

In the short term this will be the easiest route.

Longer term would want to look at a couple of options.
1. mass email package to manage this type of thing locally. Needs to be restricted to admin level accounts.
2. Sign up with a mailing service and use their APIs to maintain our email list. Advantages being the handling of unsubscribe requests, exclusion lists, etc. as well being less likely to get flagged as spam.

**Comment by aphelionz** [comment]
@mjstealey I vote #2. Let's use mailchimp or something. It's not Hydroshare's job to send email newsletters to people.

**Comment by mjstealey** [comment]
02/15/2017 at 3 pm ET: Mass email has been sent to all users where "is_active" = true.
This implies they had logged into the HydroShare site at least once after signing up.

<img width="895" alt="screen shot 2017-02-15 at 3 09 57 pm" src="https://cloud.githubusercontent.com/assets/5332509/22993406/de0cbb74-f390-11e6-8ae0-90ebe440e890.png">

**Comment by dtarb** [comment]
Removed priority and milestone as it was done for 1.9.5, but retaining as an issue to formalize the process.

**Comment by dtarb** [comment]
@aphelionz can you be champion of finding a simple solution.  We do not need any email newsletters, but we do need functionality for a HydroShare admin to go some place and type in text to send announcements to all active users, such as announcements of system maintenance.  We may need two tiers of messages (1) that all users get that users cannot opt out of that are system critical level messages and (2) that are informational that users can opt out of on their profile page.  The HydroShare admin sending the message should be able to indicate whether it is system critical or informational, and system critical should only be used for real system critical things such as planned or unanticipated extended down time.

**Comment by aphelionz** [comment]
@dtarb copy that. I'll discuss some options on the call today.

**Comment by dtarb** [comment]
I would like to resuscitate discussion and work on this, so am bumping to high priority.   We need to establish capability to email users about planned downtime and have a way to inform users about the status and progress towards recovery if (when) we have a failure, or failure of a supported component (e.g. Jupyter or another supported App).  I believe that email is the best way to inform users of planned downtime and recovery progress.  The website itself should also provide notifications (but this may not be possible with all  types of failures).  The email list to use for this should be held and kept current outside of HydroShare itself so that we have access to it if HydroShare is down.  We need to have a way to identify users on the list who have been recently active, because depending on the situation (e.g. system down) may elect to only notify users who have logged in during the last 30 (or 15 or 90) days about an unplanned failure, so as not to spread alarm too widely to users who are inactive and may not notice.  Outgoing emails that notify users about upgrades or problems should ideally come from a cuahsi.org email address.

**Comment by dtarb** [comment]
Adding implementation suggestions based on the email thread I think we need 
- [ ] A function that exports the user database that can be run periodically or on demand, and runs automatically daily.
- [ ] A place outside the system (e.g. in a sysops Google Drive) where the database is written.
- [ ] An additional field on a user's profile page that provides a check box for users to opt out of receiving system announcement emails.  This field should result in an opt out column being populated in the table of users that is written out.  The check box should be unchecked by default.  The message next to the check box should state: "Opt out of receiving system announcement emails such as announcements of planned downtime for system upgrades."
- [ ] A way to select a subset from the list.  (A spreadsheet operation on the sheet may suffice)
- [ ] A way to import a subset from the list into a CUAHSI mail system (e.g. Mailchimp) and send email with CUAHSI from address an email.
 
@sblack-usu please do the top 3.  We need to leave 4 and 5 above to CUAHSI (@aphelionz) to figure out.  I am suggesting the simple export option so that the list is accessible to us in case the system is down (one of the points of doing this).

**Comment by martinseul** [comment]
in order to minimize manual work and enable a reliable workflow I think we need to look into a more automated workflow. I asked Phuong to check out the mailchimp API https://developer.mailchimp.com/documentation/mailchimp/guides/get-started-with-mailchimp-api-3/ as we have an account and it looks like we can dynamically create mailing list. If we have a correct mailing list Liza or any other authorized user can send emails via the portal, You can create templates so they emails will have a unified look and feel. This would mean we would not need 1 & 2 
biggest problem is the synchronization of accounts across the 2 systems HS and mailchimp. As i understand it we are required by law to allow users to unsubscribe so we are investigating options.

**Comment by dtarb** [comment]
@martinseul see item 3 in the check boxes above where I suggested an approach for a check box to opt out.  Also, I think you are missing the point.  We need a list of members outside of HydroShare so that if HydroShare is down we have a way to get the list and send email to users about how long it will be down and when it will be back.  I think you may not want to send such an email to all users, only to recent users, hence you need to be able to filter based on last login in the table.  If you can do all that automatically in Mailchimp, then I will leave it to you to do that.

**Comment by martinseul** [comment]
the actual list for sending out emails lives in Mailchimp outside of HS, as Liza would send out the emails from Mailchimp, so I think this covers your use case. Phuong is looking into writing a jenkins job to synchronize the lists between HS and mailchimp either on demand or on a regular basis this could include all users or only the recent ones if this is a requirement e.g. ignore users who have not logged in in the previous year. So if HS is down you can still use Mailchimp to send an email to the current list. Being able to unsubscribe at HS is not sufficient as a unsubscribe mechanism. we need to be able to capture if a user clicks the required unsubscribe link in the notification email  and remove this email from the list of recipients and remember that choice for any upcoming emails. Possibly this could propagate into the HS user db as well setting the opt-out flag.
We can report on progress on Monday or Wednesday.

**Comment by martinseul** [comment]
Phuong completed a jenkins script that synchronizes emails from HS to Mailchimp: http://ci.hydroshare.org:8080/view/03.%20Housekeeping/job/update-MailChimp-emails-list/ 
it currently selects all active accounts and creates mailing list on Mailchimp. the list of selected accounts  can be adapted easily if we want to subset or have multiple lists for different purposes. We still need the additional field in the profile page to allow users to opt out from HS. We now should develop templates for different purposes e.g scheduled downtown, new feature announcements, Jupyter hub or apps downtime, etc.

**Comment by aphelionz** [comment]
Closing this as we have this functionality now. Reopen if necessary.
