### ISSUE TITLE
GeoTrust REST Endpoint Requests

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1871]
@aphelionz @pkdash The following REST endpoints are requested from GeoTrust (and incidentally, other users and app developers as well): 

- [x] Unzip file (@aphelionz is working on it)
- [x] Upload file to a specific folder (@aphelionz is working on it)
- [x] Zip folder
- [x] Move file/folder
- [x] Add key/value resource level metadata
- [x] Set other resource flags, e.g. @alvacouch will discuss) 
- [x] Create resource version 
- [x] Create resource copy
- [ ] Pass in bounding box
- [x] Pass in keyword

**Comment by pkdash** [comment]
@alvacouch and @aphelionz If we can implement in the order it is listed that would be great.

**Comment by horsburgh** [comment]
@alvacouch - also see issue #1869 for additional discovery based REST API endpoint requests.

* Pass in bounding box
* Pass in keyword

**Comment by aphelionz** [comment]
@pkdash @horsburgh @alvacouch roger that

**Comment by aphelionz** [comment]
Gonna start knocking items off this list starting tomorrow @pkdash @alvacouch

**Comment by pkdash** [comment]
@aphelionz Sounds good. Thanks.

**Comment by Castronova** [comment]
In regards to the `Publish resource` API endpoint:

How automated do we want publishing to be? In December there was a discussion about publishing RHESSys models paraphrased below:

**Lorne Leonard**
How would I upload 100s of zip files (huc-12s) to hydroshare at one time?
Who is the best person to contact about automating the "publish with DOI"?

**Tony Castronova**
As long as the files aren't huge, the accessing the API should work fine using the `hs_restclient`.  

I have not used the HydroShare API to publish a resource and I’m not sure that this functionality was made possible via the hs_restclient. I’m sure that there is an internal API function that you can leverage, however publishing resources in bulk is problematic because it is an action that cannot be undone. I see no problem in automating the creation of 100’s of resources, but I suggest that you talk with Pabitra Dash and Dave Tarboton (CC’d) about your plans before you attempt a mass publish. 

@dtarb 
Publication is FINAL and IRREVERSIBLE.  This is publication in a formal sense with a DOI.  I am not sure how automated we want this to be.

If you want the resources to have DOI’s and be formally published and citable, there is probably a manual quality control check you want on these.

**Comment by pkdash** [comment]
@aphelionz Have we already implemented an endpoint for adding key/value metadata at the resource level?

**Comment by aphelionz** [comment]
No... the check means I'm working on it :)

**Comment by pkdash** [comment]
Got it.

**Comment by aphelionz** [comment]
@pkdash @alvacouch gonna need some guidance on how to update resource flags and where the code is. My fear is that it's all scattered around everywhere with no central function to call like the other endpoints. Am I wrong?

**Comment by pkdash** [comment]
@aphelionz This is the view function used by the UI for setting resource flags.
https://github.com/hydroshare/hydroshare/blob/develop/hs_core/views/__init__.py#L601

The only flag that it does not set is the 'publish' which is set by the system when the resource gets published. 

This view function probably can be refactored to server both rest endpoint and UI.

**Comment by aphelionz** [comment]
@pkdash thank you

**Comment by aphelionz** [comment]
@horsburgh @pkdash for the discovery endpoints... should I add those options to the resourceList endpoint??

**Comment by aphelionz** [comment]
@pkdash nevermind, I see it now

**Comment by aphelionz** [comment]
@alvacouch @horsburgh How should I implement the discovery endpoint for bounding box? Anything WITHIN the bounding box? anything TOUCHING the bounding box?  Is there existing code for this already?

**Comment by horsburgh** [comment]
Initially - I would do anything intersecting the bounding box (within or touching). I'll let Alva answer the question about code because the current user interface (the Discover page) does have a Map Interface and presumably some filter on bounding box because it filters the list of resources at the bottom of the page.

**Comment by aphelionz** [comment]
@horsburgh That's fine. I was able to get the code help I need as well. Thanks!

**Comment by mohamedmorsy** [comment]
@aphelionz We would like to update the model instance, SWAT model instance, and MODFLOW model instances resource specific metadata element "includes_output" using REST api. This is a part of what we are doing in GeoTrust. This specific metadata element is important as its default value is "False" so once the model runs  and pushes back the output to the HydroShare we would like to update the "includes_output" element to be "True." Can we do that?

Here is the call we were using and expected it is going to work:

metadata = {
   "title": "Metadata",
       "modeloutput": [
       {"includes_output": True}
       ]
   }
   science_metadata_json = hs.updateScienceMetadata(
       str(id), metadata=metadata)
   return json.dumps(science_metadata_json)

**Comment by aphelionz** [comment]
@mohamedmorsy is `hs` in that code an instance of hs_restclient? If so then probably you will need to wait for the API updates I did to propagate down to the restclient. I haven't implemented them there yet.

**Comment by pkdash** [comment]
@aphelionz The existing endpoint for updating metadata supports only Dublin core metadata.  @mohamedmorsy is asking for updating resource specific metadata which is not part of the Dublin core. For this I don't think there is any thing needs to be changed in hs_restclient.

**Comment by aphelionz** [comment]
Well, the endpoint I modified should cover that, then?

`set_metadata = "/hsapi/resource/%s/scimeta/custom/" % self.pid

        response = self.client.post(set_metadata, {
            "foo": "bar",
            "foo2": "bar2"
        }, format='json')
        self.assertEqual(response.status_code, status.HTTP_200_OK)`

**Comment by pkdash** [comment]
No. That only updates key/value metadata.
