### ISSUE TITLE
Do we need coverage map for web app resource type?

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#1887]
Currently we see the coverage map (with no coverage information) for any web app resource on the resource landing page. Is coverage map relevant to web resources? Otherwise, it would be good not to display it.

**Comment by dtarb** [comment]
I think the functionality as it is is correct.  If I go to a web app landing page in default (view) mode I do not see coverage.  This is because the resource does not have coverage.  For example see https://www.hydroshare.org/resource/9674a0af9f30410e9e02397c91284f54/

If I edit the web app instance I see coverage.  This allows an editor to set coverage.

Since web apps are a generic mechanism for linking to apps, and it may be possible to have an app that is coverage limited (e.g. national water model apps have coverage only for the US), I think that the coverage metadata element should be kept for apps and that the current behavior that does not show it unless it is populated should be retained.

**Comment by pkdash** [comment]
Seems not an issue as per @dtarb . So closing.
