### ISSUE TITLE
Develop capability for resources to be stored in iRODS using a non proxy user account

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#19]
6.  [x]  1. Set up development HydroShare iRODS server and datagrid

6.  [x]  2. Set up development Django instance to participate in this datagrid

6.  [ ]  3. Modify account creation capability to create account in iRODS

6.  [ ]  4. Modify resource creation capability to store resources under the originators account

**Comment by hyi** [comment]
This enhanced functionality is completed and the enhancement is pushed to github feature branch 19-res-proxy-user-irods branch. When a user signs up, a corresponding iRODS account is created. When a user changes password, the password for the corresponding iRODS account is changed accordingly. When a user signs in and creates a resource, the resource will be stored under the corresponding iRODS account. Tested the various workflow and it also works as expected. Since we don't have reflector from iRODS to Django, Ray will work on turning off password changes to any iRODS client other than HydroShare Django so that only HydroShare Django web interface can change password for corresponding iRODS HydroShare accounts.

**Comment by hyi** [comment]
@dtarb @rayi113 Do you think we need to close this issue since it is no longer in our to-do list?  I will  create a new issue for implementing irods user space in Hydroshare as @rayi113 presented once I have specific sequence of steps worked out.

**Comment by rayi113** [comment]
@hyi @dtarb Yes, I think it's okay to close it after the new GitHub issue is created that supersedes this one.
