### ISSUE TITLE
Replicate Resoure Bag to iRODS User Zone isn't working

### ISSUE THREAD

**Issue by rayi113** [hydroshare/hydroshare#1920]
The Replicate Resoure Bag to iRODS User Zone button and function isn't working on the HydroShare Resource landing page.  Both @dtarb and I @rayi113 verified this when trying to work with a shared file.

**Comment by hyi** [comment]
@rayi113 @dtarb Thanks for reporting this. I have hotfixed this issue by directly applying the one-line change on www since this issue is a regression caused by recent change of removing pickle from allowed format for celery tasks, which introduced change to create_bag_by_irods() celery task method signature. I will create a PR to fix this as well as adding an unit test to capture this since apparently this is not covered by the current irods user zone unit test set. @rayi113 @dtarb Can you test on www to verify this issue is now fixed by the hotfix I just applied?

**Comment by hyi** [comment]
@rayi113 @dtarb @mjstealey A PR https://github.com/hydroshare/hydroshare/pull/1923 has been created to fix this regression issue as well as add unit test case to cover this so this kind of regression will be captured by unit tests in the future. Have asked @pkdash to code review that PR. So you can close this issue after you verify the hotfix does work on www.

**Comment by hyi** [comment]
@rayi113 @dtarb The fix to this issue along with added unit test case has been merged, so you can close this issue after you verify it works on www now with the same hotfix applied.

**Comment by rayi113** [comment]
@hyi It didn't work for this HydroShare resource https://www.hydroshare.org/resource/42a3edd700a749f1890b84d9f1a74fd2/ .  I added you as owner to the resource so you can replicate.  Basically it creates a bagit of metadata only, but not the 1.3GB data file itself.

**Comment by rayi113** [comment]
It was discovered that the problem only existed for https://www.hydroshare.org/resource/42a3edd700a749f1890b84d9f1a74fd2/ so this HydroShare resource was deleted and a new verison created here: https://www.hydroshare.org/resource/2a5df6a9310c49a1abcd45fa9fa981b7/

**Comment by hyi** [comment]
@rayi113 I just tried with this new version, and found the same issue still persists. Have to look into what is special with this specific content zip file in this resource.

**Comment by hyi** [comment]
@rayi113 I have done various experiments and it appears the word "zip" in the file name is not an issue. Specifically, for this troublesome resource https://www.hydroshare.org/resource/2a5df6a9310c49a1abcd45fa9fa981b7/, I renamed the file to remove "zip" word from the file name, but still the same problem, i.e., no content file is included in the zipped bag. For the other resource counterpart with same content file but different file name, I added '.zip' in the file name, and it still gives me a valid zipped bag with 1.3GB content file included. I used django shell and executed step by step, and confirmed the ibun call produced the zipped bag in both cases, so for the troublesome resource, the zipped bag with no content file included is indeed generated by ibun irods command. So the issue is on iRODS side, not on Django side. I'll email irods support to see whether they can find anything specific that caused this issue.

**Comment by dtarb** [comment]
I tested this on candidate release and found that I am still unable to replicate to iRODS, but that in addition the file content display shows the data folder and does not show the content file, as below.  Most resources show contents folder only.  This seems to be another case of confusion between Django and iRODS
![image](https://cloud.githubusercontent.com/assets/3456833/25881050/0c672178-34f8-11e7-8a37-66afbd9d8080.png)

**Comment by dtarb** [comment]
This resource is sufficiently corrupt that it crashes @alvacouch debug script
![image](https://cloud.githubusercontent.com/assets/3456833/25881103/52d1e97c-34f8-11e7-99b8-f3e4b5f6332e.png)

**Comment by hyi** [comment]
@dtarb @alvacouch If you are looking at an existing resource synced from www to beta, you will not be able to copy the resource to your user zone because the hardcoded user zone path in the www database that is not accessible on beta. I will try to run @alvacouch's management command to see if the hardcoded user zone path on the db on beta can be replaced with the right path from configuration in local_settings.py.

**Comment by hyi** [comment]
@alvacouch I cannot find the management command you wrote to replace the hardcoded user zone path in www db with the right path from configuration in local_settings.py although I remember I saw that when I did code review. Please advise on this and if I somehow missed the command, let me know the command I need to run to fix the hardcoded path so that I can fire it up on beta to allow user zone related functionality to be tested on beta.

**Comment by dtarb** [comment]
@hyi I am getting inconsistent behavior.  I am able to on beta copy some resources to iRODS.  Notably 
https://beta.hydroshare.org/resource/9990bc18925b429aae35c142bea235da/, but for some I get an error and for some just nothing happens.  This may be due to the date they were created and who owns them (whether I own them or they are shared with me).

The fact that some work suggests that a hardcoded user zone path may not be the problem.  Rather I am worried that iRODS destination paths are a property of resources (and they should not be).  We need to clarify and make transparent to users what is going on with iRODS.  If resources have iRODS properties (e.g. are in a different zone) it should be indicated to users somehow.  I am not sure if this is related to the problems, but we need to sort this out.  Confusion and disfunctionality over iRODS has gone on too long.

**Comment by hyi** [comment]
@dtarb The reason you can copy this resource https://beta.hydroshare.org/resource/9990bc18925b429aae35c142bea235da/ is because this resource is stored in the main zone, i.e., not in the user zone. You will only run into issues when you are dealing with resources stored in the user zone because of the hardcoded user zone path which only applies to www federation in the www database which is copied to beta for deployment, but not apply to the beta federation. I believe running the management command @alvacouch wrote that replace the hardcoded path to each individual deployment environment would resolve this test environment setup related issue. I agree we should indicate where the resource is stored on resource landing page. Will create an issue to show where the resource is stored for release 1.11 when the quota script drafted by @mjstealey should also be integrated to make quota fully functional.

**Comment by hyi** [comment]
@dtarb @alvacouch I have run the command ```fix_irods_user_paths``` on beta. @dtarb Try that 1.3GB private resource again to see if you can replicate it to your user zone on beta now.

**Comment by rayi113** [comment]
@hyi tested on beta and fixed.
