### ISSUE TITLE
Replicate bag to iRODS does not work on RC 1.9.6

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1927]
In testing release candidate 1.9.6 on beta.hydroshare.org I get the following error if I attempt to replicate a resource to iRODS
![image](https://cloud.githubusercontent.com/assets/3456833/23823583/a6848674-0622-11e7-9df3-acd9ba7fdec3.png)

**Comment by mjstealey** [comment]
@dtarb - Can't tell by your screenshot, but am guessing that you are using an existing account that was originally from www. There is going to be a disconnect between what beta / usersdev understands as linked iRODS user space as compared to what www / users does.

We presently do not attempt to replicate the iRODS hydroshareuserZone users across to the hydroshareusersdevZone due to password and salt issues between environments.

Would suggest creating a new account and then creating an iRODS user account for the new account and retrying the test.

**Comment by dtarb** [comment]
Yes I was using an existing account.  I was able to create a new account and the replicate completes without giving an error, however I am unable to get into iRODS to verify that the files were put there due to confusion over the right combinations of username, password, host and zone that beta is connected to.

**Comment by mjstealey** [comment]
> I am unable to get into iRODS to verify that the files were put there due to confusion over the right combinations of username, password, host and zone

@dtarb - The users zone for beta is as follows
- irods_host: **usersdev.hydroshare.org**
- irods_port: **1247**
- irods_zone: **hydroshareuserdevZone**
- irods_user: **YOUR_USER**
- irods_auth: **YOUR_AUTH**

That should land you in your home: **/hydroshareuserdevZone/home/YOUR_USER**

**Comment by dtarb** [comment]
Thanks.  I was able to get in and verify that these bags were copied, so will close this issue.

I was not getting the right combination of usersdev.hydroshare.org (users plural) and hydrohareuserdevZone (user singular) in my login attempts.
