### ISSUE TITLE
Improving interoperability between Hydroservers and HydroShare

### ISSUE THREAD

**Issue by Lizabrazil** [hydroshare/hydroshare#1984]
A user wanted to move her data sitting privately on her HydroServer over to HydroShare, while still keeping it private. The attachment goes into more details about the progress of this design strategy.

**Comment by Lizabrazil** [comment]
[RE discussion with HydroShare team about interoperability.txt](https://github.com/hydroshare/hydroshare/files/900622/RE.discussion.with.HydroShare.team.about.interoperability.txt)

**Comment by alvacouch** [comment]
See issue #1987 for a possible long-term fix to address this kind of pain.

**Comment by horsburgh** [comment]
@alvacouch - #1987 doesn't address this use case because this particular HydroServer is not registered or cataloged with HIS Central. Also - this user wants to move the actual data to HydroShare and not just have references and metadata. So - we need a tool for moving data from an "unpublished/unshared" HydroServer (or really any other HydroServer) to HydroShare to meet this need.

I've put forth the following plan:
1. We (my group at USU) will build a user interface for our existing code that should run on any environment (but most specifically on an existing HydroServer). It will be Python based because all of the existing code is in Python.
2. The tool will run as a desktop tool that requires the ability to make a SQL connection to the ODM database and must have an internet connection so it can create resources in HydroShare via HydroShare’s API.
3. The user interface will be very simple. Functionality will include:
a. The user will see a list of all time series in an ODM database (the tool will get them from the SeriesCatalog Table in the ODM database).
b. The user will then select a group of time series to convert to a HydroShare generic or composite resource (whichever is the default).
c. The user will be able to add the minimum required metadata for the HydroShare resource to be created.
d. The user will be able to configure as many HydroShare resources from their time series list as they want (e.g., one per time series, one per site, one per variable, or however the user wants to combine time series).
e. Configurations and metadata will be stored in a config file that can be changed later on via the user interface (e.g., define new resources, modify existing resources)
f. The user can execute the tool to create the resources
g. We can consider a scheduled execution (in the case where a user wants to regularly update resources in HydroShare)
4. Right now, the tool creates resources containing annotated CSV files (e.g., CSV file with a metadata header). As a first option that uses our existing functionality, users will be able to choose between creating a single CSV file with a column for each selected time series, or creating a single CSV file with separate header for each time series.
5. Later on, we can decide if we want to switch all of this over to use the time series resource type.

For examples of the CSV file formats see:
 
Single CSV file, multiple data columns:
 
https://www.hydroshare.org/resource/94bcad20fbfb4c44ac7f98a0fdfa5e79/
 
Multiple CSV files, one for each time series:
 
https://www.hydroshare.org/resource/5057577e8573433d8045b59db91b2550/

**Comment by danames** [comment]
Jeff, so the idea here is that your desktop python tool will extract data
from a HydroServer into a CSV file and upload the CSV file to HydroShare as
a new resource? If this is right, then it does open several questions. But
I'll hold the questions till I make sure I've correctly characterized the
workflow you are proposing... - Dan

**Comment by horsburgh** [comment]
@danames - effectively yes. The use case @Lizabrazil has described has a couple of characteristics that make it challenging.  The HydroServer is private and not registered with HIS Central and, therefore, not available to the HydroClient.  I'm not sure whether they have a WaterOneFlow web service or not, but they don't want it to be public. They also want the resources created in HydroShare to be private. 

Why CSV in a composite or generic resource? Mostly because we already have code for this that we are using for the iUTAH project. In another iteration of this tool we could potentially add an option to create time series resources instead. The iUTAH users specifically asked for CSV files.

We have code that is doing this already for iUTAH, but it has no user interface. So, development work would just involve adding a configuration interface to make it usable by others.

**Comment by danames** [comment]
@horsburgh  OK I understand. Optimally these would go into a time series resource in an ODM file. Maybe this is a good time to propose something we've been thinking about here at BYU for a while.... expanding the time series resource to allow a few different file formats, namely: SQLite/ODM2, WaterML 1.1/2, TimeseriesML, CSV...  Though this should probably be saved for HydroShare 2.0.  @dtarb what do you think?

**Comment by dtarb** [comment]
@danames we need to be careful of scope creep with HydroShare 1.x.  We are at month 58 of a 60 month project and unless this is hardening, or you have additional resource you can use to do this it should wait to HydroShare 2.0.  Even at HydroShare 2.0 you would need to motivate that this is fundamentally required for advancing the objectives in our proposal.  Another thing to consider, is that we adopted the resource type and file type paradigm, to have a single standard type for each data class (raster, vector, time series, multidimensional etc).  That way apps can be built to rely on that format.  Other formats should be accommodated through tools (also apps) that import into the std format.  This is why we put so much effort up front into the design and selection of these formats.  The proliferation of formats for the same thing is counter to this and makes it much more of a challenge for app developers.  This concept is illustrated in this figure
![image](https://cloud.githubusercontent.com/assets/3456833/25057588/6ffc3c06-212e-11e7-8985-1e6a9b4bf284.png)

So, I think it is better to build translators of all the formats you want to support into our std format, rather than store a bunch of formats.

**Comment by danames** [comment]
@dtarb, I guess we need to reconcile this design philosophy with the a real world use case that @horsburgh has described where it seems that our approach doesn't work, so he is going to put time series data sets as CSV files in generic resources...

**Comment by horsburgh** [comment]
@danames - We developed the generic resource CSV functionality on the iUTAH project because users specifically asked for it.  They even specified to some degree the format of the CSV files they wanted. But, they are generic resources and so have no specific time series functionality. So - we have code now that can create generic resources containing formatted CSV files, and we could eventually add the option to *either* create a generic resource (with data stored internally as CSV and no special functionality) *or* create a TimeSeries resource (with data stored internally as ODM2 SQLite and with special functionality). iUTAH is supporting the development of the tool, so meeting their use case first is important.

With respect to Time Series Resources - users can already upload SQLite and CSV.  I've given Matthew code for creating ODM2 SQLite from WaterML 1.1, so we could automate that import from say a WaterOneFlow web service.   All of these would be stored internally as ODM2 SQLite (consistent with Dave's diagram above). I don't know of any users (people) who are working with WaterML 2.0 or TimeSeriesML files, so the use case that a person is going to upload these files through the user interface is not that important yet. There will likely be a growing number of services that use these formats though and so automating transfer of data into and out of HydroShare is a future consideration.

**Comment by ChristinaB** [comment]
How I am designing my work to incorporate HydroShare and HydroServer is to use JupyterNotebooks and working with @Castronova to install packages that can grab data from the HIS and use the Rest Client to get data from HydroShare, and 'interoperate' on data in one Notebook.  This may not be the best solution for all cases, but one that @martinseul and @Castronova and I are going to be working on as a low cost alternative. FYI.

**Comment by eclark-cuahsi** [comment]
closing per backlog review meeting on 6/9/22. a work around is downloading the data and uploading it to hydroshare.
