### ISSUE TITLE
Discover interface shows older versions of resources

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1998]
The discover interface shows two versions of the same published resource
![image](https://cloud.githubusercontent.com/assets/3456833/25074675/62202390-22be-11e7-8a88-ab1b09599d9b.png)

The second is https://www.hydroshare.org/resource/03714a41e4594bb78b9d3f5c50ec8dec/ which has a new version as indicated.

![image](https://cloud.githubusercontent.com/assets/3456833/25074678/815d497c-22be-11e7-87c6-6952a9126255.png)

Our design https://docs.google.com/document/d/1tNFStpEmbB_AC2ICppVSw-024-iTrnqGK9Np7Elw2OM/edit states that "Only the most recent version of a resource in an obsolescence chain will be “active” and discoverable using HydroShare search services, but linkage to previous versions will be maintained and provided via the HydroShare web user interface."

**Comment by hyi** [comment]
@dtarb @alvacouch @xuezhaokun This issue is a duplicate of this issue https://github.com/hydroshare/hydroshare/issues/1047 which I created when I initially implemented resource versioning. It is currently on my plate, but I think it is better for @alvacouch and @xuezhaokun to work on. It is most likely a simple fix, just need to remove the old versioned resource from solr indexing. You can check metadata Relation element isReplacedBy to see if a resource is an old versioned resource. Let me know if you have questions on how to filter out old versioned resources from solr indexing. I am going to close the other duplicate issue and assign this issue to you both to work on then.

**Comment by aphelionz** [comment]
@dtarb We were just confirming this at the CUAHSI offices. It seems to be fixed, is it?

https://www.hydroshare.org/search/?q=iUTAH&NElat=&NElng=&SWlat=&SWlng=&start_date=&end_date=&page=3

**Comment by dtarb** [comment]
Yes I can no longer reproduce it.  Closing.
