### ISSUE TITLE
Fix Large File Subsetting in HydroShare Hyrax

### ISSUE THREAD

**Issue by rayi113** [hydroshare/hydroshare#2024]
Large file subsetting in http://hyrax.hydroshare.org/opendap/  does not work.  Recommend:

- [x] Restore previous HydroShare Hyrax to its limited operation
- [ ] Check for large files and preclude processing them in limited operational Hyrax
- [ ] Recreate problematic HydroShare Hyrax in Beta environment
- [ ] Replace iRODS Fuse mount of public HydroShare NetCDF resources with [NFS-RODS](https://github.com/modcs/NFSRODS), along with OpenDAP-recommened changes
- [ ] Verify problem resolved and Hyrax operational in Beta environment
- [ ] Move operational Hyrax from Beta environment to HydroShare production

See also #2023.

**Comment by cbcunc** [comment]
@rayi113 and I just talked. We agreed on a revised plan:

- [ ] Restore current HydroShare Hyrax to its limited operation immediately (@cbcunc)
- [ ] *Temporarily* remove mechanisms for accessing Hyrax from production Hydroshare (@gantian127)
- [ ] Create NFS or DAV mount on current Hydroshare Hyrax (@cbcunc) (lower priority than previous steps)
- [ ] Revise cron scripts which select NetCDF resources for symbolic linking (@hyi)
- [ ] Point Hyrax at new mount (@cbcunc)
- [ ] *Restore* mechanisms for accessing Hyrax to production Hydroshare (@gantian127)
- [ ] Profit

**Comment by cbcunc** [comment]
First to-do item accomplished. http://hyrax.hydroshare.org:8080/opendap/ @gantian127 up next.

**Comment by cbcunc** [comment]
Added @gantian127 and @hyi as co-assignees. Responsibilities in check list above.

**Comment by cbcunc** [comment]
[NFS-RODS](https://github.com/modcs/NFSRODS) contains the following disclaimer:
> It does not support:
> 
>     Handling iRODS metadata
>     NFS symbolic links
Not sure if `NFS symbolic links` means client-side or server-side. Will need to clarify with iRODS support. The cron scripts which select NetCDF resources work via symbolic links.

**Comment by dtarb** [comment]
With current capability restored I have re-enabled the Open With as "OPeNDAP (smallish files only)".  I think this is better than nothing.  I also revised abstract.  If we can better determine the actual limit we should state it more precisely.

**Comment by dtarb** [comment]
Another suggestion.  Since we are only doing this for public netCDF files can we save them some place outside of iRODS and have Hyrax access that outside location.  Possibilities are
- copy public netCDF files to outside location.  Retain a copy.  Wasteful in space but could  be immediately implemented (I think)
- move public netCDF files to outside location.  Have Hyrax act on these.  Register these as iRODS files.  This (as I understand it) makes the files accessible to iRODS, but keeps them outside.  This may require a bit of work and more careful design, but may be a more efficient long term solution.

Thoughts?

**Comment by dtarb** [comment]
There was a comment from @hyi in https://github.com/hydroshare/infrastructure-support/issues/12 about reusing bag_modified.  I am responding here because that issue is closed in favor of this one.  I suggest to be careful using bag modified.  Because if you copy a file whenever the flag is true and no one has created a bag, you may repeatedly copy the file unnecessarily.

**Comment by hyi** [comment]
@dtarb That is true, thanks for pointing it out. Agreed ```bag_modified``` flag is too broad for this specific case. I will see if I can use modified time stamp or manifest file for the netCDF file itself to determine whether there is a need for recopy to refresh the file. If that did not work, I would probably just add a new flag which I have been trying to avoid since the more flags we have, the more potential confusion they would cause.

**Comment by aphelionz** [comment]
@hyi Is this bug ticket still relevant given the recent Hyrax work?

**Comment by hyi** [comment]
@aphelionz I'd say this has been addressed and can be closed. I'll defer to @dtarb to close it though just in case.

**Comment by aphelionz** [comment]
I'll close and he can re-open or make a new issue if need be :)
