### ISSUE TITLE
Natural use of versions and copies creates dangling inter-resource relations

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#2035]
Use case: 
1. user creates a resource V1.
2. over time the user creates two more versions V2, V1. 
3. then the original is copied to C1
3. then the user deletes the original. 

At this point, 
1. the backlink "isVersionOf" is now broken for the versions. 
2. the backlink "isCopyOf" is broken for C1. 

This comes up when we try to resolve the latest version for discovery!

**Comment by hyi** [comment]
@alvacouch The use case you outlined above is not possible. I just checked on beta to make sure about this. After V2 is created which is a new version of V1, no action can be done to V1 any more, i.e., no copy can be performed at least from the UI side. Not sure about the REST API, but if isReplacedBy relationship exists for a resource which indicates this resource is obsoleted by a newer version, no action can be done to that obsoleted resource any more (i.e., no buttons are visible from that resource's landing page on the top right except for access control button). Can you explain where and how you make the use case you outlined above happen since I cannot make it happen?

**Comment by alvacouch** [comment]
@hyi The REST API imposes no such limits.

**Comment by hyi** [comment]
@alvacouch OK. Got it. Then REST API needs to be fixed to be consistent with UI.

**Comment by alvacouch** [comment]
@hyi 

* Does this mean that the original version of a resource cannot be deleted from the UI? 
* Does this mean that once a copy is made, the source cannot be deleted from the UI? 

There is another sensible option, which is to update the relationship links appropriately when these operations occur.
* When you delete a version, is "isVersionOf" links are collapsed. 
* When you delete the source of a copy, the "isCopyOf" relation is deleted.

**Comment by hyi** [comment]
@alvacouch Yes, the original version of a resource cannout be deleted from the UI directly according to design since it is in part of obsolence chain. Only the latest version can be deleted. Then after the latest version is deleted, the previous version in the chain becomes the latest, which can be deleted or acted upon. The older obsoleted versions cannot be deleted or acted upon in any way to keep the chain intact and simple.

However, copy action is different. A copied resource is detached from the original resource except a isCopyOf relation metadata exists to denote its origin. Both original and copied version can be acted up independently subject to access control.

**Comment by alvacouch** [comment]
@hyi By _obsolence_, I assume you mean _provenance_...

**Comment by hyi** [comment]
@alvacouch Sorry for the typo, it is actually obsolescence. Have updated my earlier comment to correct the typo.

**Comment by alvacouch** [comment]
Looping in @aphelionz because he's responsible for the REST API and @martinseul . 

Mark, this is yet another skew between the UI and the REST API as far as semantics. This one is subtle; the UI doesn't show a button when something can't be deleted, but the REST API has no such distinction.

**Comment by dtarb** [comment]
There is not a policy decision to not allow old versions to be deleted documented in our design document (https://docs.google.com/document/d/1tNFStpEmbB_AC2ICppVSw-024-iTrnqGK9Np7Elw2OM/edit) and I see this as a limitation.  I am looping in @horsburgh as he was the author of the design document.  I suggest the following policy and implementation enhancements.

For versioning, implement consistency between API and UI and maintain proper provenance in the isVersionOf links.  I.e. suppose there are three versions
```v3 -> v2 -> v1```
Any version may be deleted from the API or UI subject to access control settings (only an owner can delete a resource).  If v2 is deleted the relationships are adjusted to
```v3 -> v1```
If v1 is deleted we end up with
```v3 -> v2```
and if v3 is deleted
```v2 -> v1```

For copies do not attempt to maintain provenance.  When a copy is created the isDerivedFrom relationship is created on the copy  (note that the relationship created is isDerivedFrom, not isCopyOf), which may have a different owner, if the copier is a different user.  The new owner can do anything they like, including delete the relationship.  This is appropriate if they are using the resource as the starting point for something essentially new and different in which case retaining the original reference does not make sense.  If the resource that the copy was derived from is deleted, the copy retains the isDerivedFrom relationship to record where it originally came from.  This becomes a broken link (which is undesirable).  A way to make this less undesirable is to extend the isDerivedFrom relationship to include the title, creators, owner and date within the isDerivedFrom element.  This notes that the copy was made from such a resource on such a date, and if the resource disappears or is changed after this fact, the record of this copy still stands (unless an editor chooses to delete it).

**Comment by hyi** [comment]
@dtarb @horsburgh @alvacouch Although the design document does not explicitly mention not allowing to delete the obsoleted resources, I believe we discussed this in that versioning issue when I started to implement it. I believe the decision is for not introducing too much complexities in the initial implementation since deleting an intermediate obsoleted resource in a versioning chain involves fixing the versioning chain. If needed, a future enhancement can be made to allow deletion of intermediate obsoleted version, but we decided for initial implementation, we just don't allow that and see how people are using it first.

**Comment by dtarb** [comment]
I am OK going with @hyi s suggestion of not allowing older versions to be deleted, but if that is the rule, then both the UI and API should do this.  In other words, I want to avoid the skew that @alvacouch identified.  If an API user tries to delete an older version it should be blocked and they should get an informative error (however informative errors are returned by the API).

**Comment by hyi** [comment]
@dtarb UI has already been doing this from the beginning. The issue is with the API. Agreed we need to keep the UI and API consistent, so for now, API needs to be fixed not to allow deletion or edit of obsoleted resources to be consistent with UI.

**Comment by pkdash** [comment]
If we are referring to REST API, then I would say REST API can only do things that the internal API allows to do. For example, if  the internal api ```hydroshare.delete_resource(res_id)``` does not allow deleting an older version of a resource then REST API can't delete that resource.

**Comment by hyi** [comment]
@pkdash Yes, the internal api ```hydroshare.delete_resource()``` does not allow deleting an obsoleted resource, it raises validation error as shown here: https://github.com/hydroshare/hydroshare/blob/develop/hs_core/hydroshare/resource.py#L718-L720
So do you think REST API then does not allow to delete obsoleted resource as well? @alvacouch What do you think?

**Comment by pkdash** [comment]
@hyi Since REST API just a wrapper for ```hydroshare.delete_resource()``` it is not possible to delete a obsoleted resource using REST API.

**Comment by alvacouch** [comment]
I found several dangling relations during integrity checking.

**Comment by dtarb** [comment]
@horsburgh in issue grooming have question if this is still an issue.  Can you please assess/test and if still a problem bring to forefront for addressing, otherwise close.
