### ISSUE TITLE
Geographic feature file type

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#2036]
This will be implemented as a new file type within Composite resource.

**Comment by dtarb** [comment]
I tested the implementation on riverdev.hydroshare.org and noted the following

 - [ ] Place/Area Name is blank but not editable.  It should be.
 - [ ] Showing Box and Point as radio buttons is misleading since they cannot be changed
 - [ ] If spatial coverage internally to a file type has place/area name, how is the overall resource place/area name set.  I suggest it should  be set based on the first one then as more are added using name1 + name2 in the field and allowing the field to be editable if the user wants.

**Comment by zhiyuli** [comment]
@pkdash 
I just tested it on riverdev and its works pretty well. 
One thing: I find I have to open the file-type folder and click a file to view its metadata. If metadata can be shown by clicking file-type folder, that would be great.

**Comment by aphelionz** [comment]
@pkdash can this be closed?

**Comment by pkdash** [comment]
@aphelionz Closing.
