### ISSUE TITLE
Bags don't download properly for selected resources

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#2056]
@ChristinaB reports that many resources -- on a per resource basis -- are unreliable to download as bags. Christina, could you list the resource ID's here? Thanks!

**Comment by ChristinaB** [comment]
Starter list of resources (Tony will work on code) when I  click on 'Download All Content as Zipped Bagit Archive. with the error "Please wait for the resource bag to be created....." , but never progresses or completes.  
- [ ] 0183ec4000f644fa9378cf28cfe5c2e2   Sauk River Basin Observatory 
- [ ] d0885da51fda4ec99f6f0a59295c3d7c   Hydro-Meterology Data Download for NOCA Observatory

**Comment by dtarb** [comment]
I also found a problem with Sauk, but then tested it on the candidate release on beta and found it to work, so perhaps the changes on beta have fixed it.

I tried the Hydro-Meteorology and on www it started a download that said it would take 58 min, then before that time, timed out.  I tried on beta and it seemed to hang creating the bag (... forever)

**Comment by Castronova** [comment]
I wrote a little script to help @ChristinaB test her resources.  It uses a slightly modified `hs_restclient` to perform resource downloads and log errors that are encountered.  Here are the results as of this morning:

|URL|Error|
|---|---|
http://www.hydroshare.org/resource/06c1c412dabc435f97415f9dac072fd0/|	int() argument must be a string, a bytes-like object or a number, not 'NoneType'|
http://www.hydroshare.org/resource/bc41b169dffb4cacbf3e9bedf4f5848e/|	int() argument must be a string, a bytes-like object or a number, not 'NoneType'|
http://www.hydroshare.org/resource/05a52f8d84474053a8ba5ae760331b38/	|int() argument must be a string, a bytes-like object or a number, not 'NoneType'|
http://www.hydroshare.org/resource/fd4ee203de444df39c4f9c01623b41b2/	|int() argument must be a string, a bytes-like object or a number, not 'NoneType'|
http://www.hydroshare.org/resource/e0568ef7089b46049fa463dbb524ad2b/|	int() argument must be a string, a bytes-like object or a number, not 'NoneType'|
http://www.hydroshare.org/resource/d15b9934f34e4c57913b3cb53966d5c7/	|int() argument must be a string, a bytes-like object or a number, not 'NoneType'|
http://www.hydroshare.org/resource/2d58ac373e4f4174a3050a046aaf121e/	|int() argument must be a string, a bytes-like object or a number, not 'NoneType'|
http://www.hydroshare.org/resource/479ae9daeec34b48885f7645ea0966b4/|	int() argument must be a string, a bytes-like object or a number, not 'NoneType'|
http://www.hydroshare.org/resource/fb17642c00bc4c3489878a672322caa4/|	int() argument must be a string, a bytes-like object or a number, not 'NoneType'|
http://www.hydroshare.org/resource/286e23da15f146c18adf2400f17e4a4c/	|int() argument must be a string, a bytes-like object or a number, not 'NoneType'|
http://www.hydroshare.org/resource/d5c5b4038e47488c86dc62db73f0a08d/	|int() argument must be a string, a bytes-like object or a number, not 'NoneType'|
http://www.hydroshare.org/resource/3b59c90bd8104ea99a2c84fe5b361306/	|int() argument must be a string, a bytes-like object or a number, not 'NoneType'|
http://www.hydroshare.org/resource/7cd2b6d7b3494dfb84a1707228b79b20/|	int() argument must be a string, a bytes-like object or a number, not 'NoneType'|
http://www.hydroshare.org/resource/9be3a8c8473f4c88a8f9ec5b1662afef/	|int() argument must be a string, a bytes-like object or a number, not 'NoneType'|
http://www.hydroshare.org/resource/a166f8e121b7496397ae05367d48a1f3/	|int() argument must be a string, a bytes-like object or a number, not 'NoneType'|
http://www.hydroshare.org/resource/2889fcae78cb40059deaf3ce53c7f8d7/	|int() argument must be a string, a bytes-like object or a number, not 'NoneType'|
http://www.hydroshare.org/resource/ca717dcd11a14398b2e0df6deef87722/|	int() argument must be a string, a bytes-like object or a number, not 'NoneType'|
http://www.hydroshare.org/resource/b7643610141945c0a3af84a03e0d175c/	|int() argument must be a string, a bytes-like object or a number, not 'NoneType'|
http://www.hydroshare.org/resource/4a33d8abc8d54b58b6624eda42138d4a/	|int() argument must be a string, a bytes-like object or a number, not 'NoneType'|
http://www.hydroshare.org/resource/ea41dd1b1239478aae68b7ecebc7d93f/	|int() argument must be a string, a bytes-like object or a number, not 'NoneType'|
http://www.hydroshare.org/resource/3a3819de85e14fd2bb5ee9e05e616258/	|int() argument must be a string, a bytes-like object or a number, not 'NoneType'|
http://www.hydroshare.org/resource/65893e1ed2dd4990b26db982d530fef6/|	int() argument must be a string, a bytes-like object or a number, not 'NoneType'|
http://www.hydroshare.org/resource/d26b1f8cf4304b529bdd342d55733310/	|int() argument must be a string, a bytes-like object or a number, not 'NoneType'|
http://www.hydroshare.org/resource/cdc6292fbee24dfd9810da7696a40dcf/	|Timeout waiting for bag creation: 60 sec|
http://www.hydroshare.org/resource/278691f0a3574a86abb3adf0543a0df8/	|Not authorized to perform GET on https://www.hydroshare.org/hsapi/resource/278691f0a3574a86abb3adf0543a0df8/.|
http://www.hydroshare.org/resource/4b7f19774f5442e8b17c38d2f72df49b/	|Timeout waiting for bag creation: 60 sec|
http://www.hydroshare.org/resource/d0885da51fda4ec99f6f0a59295c3d7c/	|[Errno 2] No such file or directory: 'tmp/d0885da51fda4ec99f6f0a59295c3d7c'|
http://www.hydroshare.org/resource/0183ec4000f644fa9378cf28cfe5c2e2/	|Timeout waiting for bag creation: 60 sec|
http://www.hydroshare.org/resource/d6c8649901634a24bb89facfd852f8be/	|Not authorized to perform GET on https://www.hydroshare.org/hsapi/resource/d6c8649901634a24bb89facfd852f8be/.|
http://www.hydroshare.org/resource/ef2d82bf960144b4bfb1bae6242bcc7f/	|Not authorized to perform GET on https://www.hydroshare.org/hsapi/resource/ef2d82bf960144b4bfb1bae6242bcc7f/.|
http://www.hydroshare.org/resource/14f0a6619c6b45cc90d1f8cabc4129af/	|Not authorized to perform GET on https://www.hydroshare.org/hsapi/resource/14f0a6619c6b45cc90d1f8cabc4129af/.|
http://www.hydroshare.org/resource/b363b853561147ffa0d7c7372dd18191/|	[Errno 2] No such file or directory: 'tmp/b363b853561147ffa0d7c7372dd18191'|
http://www.hydroshare.org/resource/1a8e0a50990d4543adb5edc5219740d3/|	Not authorized to perform GET on https://www.hydroshare.org/hsapi/resource/1a8e0a50990d4543adb5edc5219740d3/.|

A few things to note:
1. some of these errors are legitimate, for example `Not authorized to perform GET...` because my user account does not have access to all of Christina's resources.  
2. it seems that the restclient has issues downloading `CollectionResources`
3. I set a bag creation timeout of 60 seconds.  Resources that "timeout" should be tested using the HydroShare interface directly.

Here is the full speadsheet of results: [broken-resources-20170501-095816.xlsx](https://github.com/hydroshare/hydroshare/files/968082/broken-resources-20170501-095816.xlsx)

Here is the code that was used to generate the results: [test-resource-download.zip](https://github.com/hydroshare/hydroshare/files/968084/test-resource-download.zip)

```
python3 test-resource-download.py
```

**Comment by dtarb** [comment]
The sauk observatory resource is broken on the release candidate beta that is currently deployed.  It was OK on the one 2 days ago when I tested.

**Comment by Castronova** [comment]
As requested by @hyi and @dtarb I've re-tested the resources that failed to bag creation timeout with a new timeout of 5min on beta.hydroshare.org.  Below are the resources that failed to download:

|resource-url|error-message|
|---|---|
|http://beta.hydroshare.org/resource/cdc6292fbee24dfd9810da7696a40dcf/|Timeout waiting for bag creation: 300 sec|
|http://beta.hydroshare.org/resource/d0885da51fda4ec99f6f0a59295c3d7c/|Timeout waiting for bag creation: 300 sec|
|http://beta.hydroshare.org/resource/0183ec4000f644fa9378cf28cfe5c2e2/|Timeout waiting for bag creation: 300 sec|


Here is the full spreadsheet of results: [broken-resources-20170508-143313.xlsx](https://github.com/hydroshare/hydroshare/files/984563/broken-resources-20170508-143313.xlsx)

Here is the code used to generate the results
[test-resource-download.zip](https://github.com/hydroshare/hydroshare/files/984566/test-resource-download.zip)

**Comment by hyi** [comment]
@Castronova @ChristinaB @dtarb @alvacouch @mjstealey I took a look at these three resources on beta and here are what happens: For the first two resources, the resource bag actually downloads correctly on www, but fails on beta with the following error:
```
ERROR [django:253] ERROR: bunUtil: opr error for /hydrotestZone/home/betaDataProxy/cdc6292fbee24dfd9810da7696a40dcf, status = -77000 status = -77000 SYS_COPY_NOT_EXIST_IN_RESC
```
Then I found all files under sub-folders are stored under the iRODS resource ```hydrotestResc``` while all files in ```data/contents``` top folder are stored under ```betaReplResc``` which is what is set up as the default iRODS resource in local_settings.py. As a result, ibun cannot find data objects under sub-folders, hence raising the error above. So I think this is an irsync issue when syncing www resources to beta on iRODS side or somehow this resource was modified on beta after syncing, I am not sure how it happened, but it is not right to store into a different iRODS resource than the default iRODS resource. @mjstealey may know the reason on why it happens, but since it works on www, I don't think we need to worry about these two resources. 

For the last resource out of the three, the bag fails to be downloaded on www, and the error I got is:
```
ERROR: bunUtil: opr error for /hydroshareZone/home/wwwHydroProxy/0183ec4000f644fa9378cf28cfe5c2e2, status = -530039 status = -530039 UNIX_FILE_LINK_ERR, Directory not empty
```
which is the same error I got for another @ChristinaB's resource (https://www.hydroshare.org/resource/1de72928f573433290f6c8bb393523df/) and I have emailed iRODS support about, which I just cannot explain why ibun raises this error when bagit.txt exists. I think we need to find out how these two resources are created to see whether we can have some clue on why we run into this ibun issue only on these couple of resources but not for majority of other resources.

**Comment by dtarb** [comment]
https://cuahsi-dev-1.hydroshare.org/resource/0183ec4000f644fa9378cf28cfe5c2e2/ fails to create bag.
https://cuahsi-dev-1.hydroshare.org/resource/d0885da51fda4ec99f6f0a59295c3d7c/ also fails to create bag.  Both hang for too long.

**Comment by alvacouch** [comment]
@dtarb @hyi @mjstealey 
These are the errors I received in the system log. bunUtil is an irods function. 
```
[15/May/2017 11:36:49] ERROR ERROR: bunUtil: opr error for /hydroshareZone/home/cuahsi1DataProxy/3941d5cd22dd4a248655ca2b4654d85d, status = -77000 status = -77000 SYS_COPY_NOT_EXIST_IN_RESC
[15/May/2017 11:45:30] ERROR ERROR: bunUtil: opr error for /hydroshareZone/home/cuahsi1DataProxy/0183ec4000f644fa9378cf28cfe5c2e2, status = -77000 status = -77000 SYS_COPY_NOT_EXIST_IN_RESC
[15/May/2017 11:51:35] ERROR ERROR: bunUtil: opr error for /hydroshareZone/home/cuahsi1DataProxy/d0885da51fda4ec99f6f0a59295c3d7c, status = -77000 status = -77000 SYS_COPY_NOT_EXIST_IN_RESC
[15/May/2017 12:43:16] ERROR ERROR: bunUtil: opr error for /hydroshareZone/home/cuahsi1DataProxy/0183ec4000f644fa9378cf28cfe5c2e2, status = -77000 status = -77000 SYS_COPY_NOT_EXIST_IN_RESC
```

**Comment by hyi** [comment]
@alvacouch Looks like there are some issues with these resource collections. Look for SYS_COPY_NOT_EXIST_IN_RESC in https://docs.irods.org/4.1.6/doxygen/rsChkObjPermAndStat_8cpp_source.html for an example of three different cases this operation error could be raised. I think it'd be helpful to see an ```ils -rL``` for the troublesome resource and see if it can provide some clue for us. @mjstealey may have some additional insight on this issue, though.

**Comment by alvacouch** [comment]
@hyi Already looked at the code and couldn't understand what it does.  :(

**Comment by ChristinaB** [comment]
For a few of the broken resources, we are downloading the files and making new resources.  These resources operate correctly,.  Thanks for all your work!

**Comment by dtarb** [comment]
https://beta.hydroshare.org/resource/d0885da51fda4ec99f6f0a59295c3d7c/ still fails to download bag.  It also fails to copy to iRODS zone, which is supposed to be the fail over for large resources.

**Comment by dtarb** [comment]
This is the iRODS error ERROR: resolveRodsTarget: srcPath /hydrotestZone/home/betaDataProxy/bags/d0885da51fda4ec99f6f0a59295c3d7c.zip does not exist ERROR: cpUtil: resolveRodsTarget error, status = -317000 status = -317000 USER_INPUT_PATH_ERR

**Comment by dtarb** [comment]
@Castronova provided the attached dump of problem resources.  I worked through these and note the following problems that I think need to be fixed before we deploy 1.10.  I added a column DGT assessment where I put notes.  Yellow highlighting indicates critical to fix.  Brown highlighting we could skip as it may just be best to recreate these resources from scratch.

[hs-beta-test-download-results.xlsx](https://github.com/hydroshare/hydroshare/files/1024275/hs-beta-test-download-results.xlsx)

There are 3 categories of problems

A. For several resources there are files present on www, missing on beta UI and the beta debug program fails.  Examples of these are
3f354dd111f24998b37099ebdf478441
6e9285751aeb496a8678ed07d9a3b53d
The first of these is a published resource with DOI, so pretty critical not to break.

B. For one resource 094da7d9400f493fb1e412df015e17a4 WWW shows repeated files.  Beta does not show repeated files.  Debug on beta shows files in iRODS not in Django.  Downloads of repeated files from WWW UI give htm page, not contents.

C.  Bag creation fails.  This one 1b9d7cad559e4a69ae7d4d955c895024 may be a good one to try debug as it is only 10 MB.  The bag is created in www, but not in beta.

@alvacouch, @hyi, @mjstealey, @Castronova, @aphelionz, @alexlemann, @maurier, could we please have a full court press attempt to get to the root of these problems.  I am uncomfortable going ahead with a deploy where files disappear or bags that download on www do not on the beta candidate release.

**Comment by ChristinaB** [comment]
I think that this is almost ready to close, correct?  My understanding is that Tony's program would be run on all users, and we would inform them about broken resources they have.  If so, I can create a new issue for that next step.

**Comment by alvacouch** [comment]
These were affected by running `fix_irods_user_paths`: 
`3f354dd111f24998b37099ebdf478441`
`6e9285751aeb496a8678ed07d9a3b53d`

There are still missing files. 

These have something else going wrong with them: 
`094da7d9400f493fb1e412df015e17a4`
`1b9d7cad559e4a69ae7d4d955c895024`

**Comment by alvacouch** [comment]
Note that the release candidate differs quite strongly from `www` in what it does with errors: 

www | release candidate
-------|------------
files in iRODS appear even if not in Django | files not in Django are not shown, even if in iRODS

For example, in `www`, `094da7d9400f493fb1e412df015e17a4` seems to have files that it doesn't have on the release candidate `beta`. These files are present in iRODS but not in Django. Thus, in the new version, since they are disconnected from Django, they are not shown.

**Comment by alvacouch** [comment]
094da7d9400f493fb1e412df015e17a4 Delete files in iRODS that are not in Django (duplicates)
aff4e6dfc09a4070ac15a6ec0741fd02 Delete files in Django that are not in Irods (failed upload)
5e80dd7cbaf04a5e98d850609c7e534b Delete files in Django that are not in Irods (failed upload)
325b21d55b2c49658a91944fabd896cf Delete files in Django that are not in Irods (failed upload)
9e5e99125d1646c69dde9fc43e137667 Delete files in Django that are not in Irods (failed upload)
3ebf244bd2084cfaa68b83b7f91e9587 Delete files in Django that are not in Irods (failed upload)
6aa75450ee2744cdb34ed8dde929a84a Delete files in Django that are not in Irods (failed upload)
887180409e4545018c8372f0bd6f8ff3 Delete files in Django that are not in Irods (failed upload)
4a5bb3a976004f0ea63991323335b170 Delete files in Django that are not in Irods (failed upload)
ecb77926c2484e068f28acda434f8772 Delete files in Django that are not in Irods (failed upload)
40655b4fc21142d090a5a4b835c14220 Delete files in Django that are not in Irods (failed upload)
1846b79a648a4088aad987cc7241656f Delete files in Django that are not in Irods (failed upload)
94bcad20fbfb4c44ac7f98a0fdfa5e79 Delete files in Django that are not in Irods (failed upload)
a22bbdfb431c44a68959534c94e96392 Delete files in Django that are not in Irods (failed upload)
bc16655330b64bcaa366d464b00e45f0 Delete files in Django that are not in Irods (failed upload)
2e9db97be020401c9aa03017cb7ee505 Delete files in Django that are not in Irods (failed upload)
c3ecee31a0c64490bf6a2fcb4841cee4 Delete files in Django that are not in Irods (failed upload)
a56608d8948c43fdb302e1438cf09169 Delete files in Django that are not in Irods (failed upload)
878093a81b284ac8a4f65948b1c597a2 Delete files in Django that are not in Irods (failed upload)
e81b1fb3cb5a49538d6c2ad3077b7b71 Delete unreferenced files on both sides.
cdc6292fbee24dfd9810da7696a40dcf Delete unreferenced files on both sides.

**Comment by alvacouch** [comment]
These are the NefCDF headers: 

LOOKING FOR FILE ERRORS FOR RESOURCE 3f354dd111f24998b37099ebdf478441
check_irods_files: django file /hydroshareuserdevZone/home/betaUserProxy/3f354dd111f24998b37099ebdf478441/data/contents/SurfaceRunoff_monthly_header_info.txt does not exist in iRODS
check_irods_files: file /hydroshareuserdevZone/home/betaUserProxy/3f354dd111f24998b37099ebdf478441/data/contents/NLDAS_NOAH0125_M_002_SSRUNsfc_CONUS_header_info.txt in iRODs does not exist in Django
check_irods_files: affected resource 3f354dd111f24998b37099ebdf478441 type is NetcdfResource, title is 'Spatial-temporal statistics of monthly surface runoff data from the NLDAS model (1979-2013)'
LOOKING FOR FILE ERRORS FOR RESOURCE ba64d962eb6c460abc9a8628946df116
check_irods_files: django file /hydroshareuserdevZone/home/betaUserProxy/ba64d962eb6c460abc9a8628946df116/data/contents/Temperature_monthly_header_info.txt does not exist in iRODS
check_irods_files: file /hydroshareuserdevZone/home/betaUserProxy/ba64d962eb6c460abc9a8628946df116/data/contents/NLDAS_NOAH0125_M_002_TMP2m_CONUS_header_info.txt in iRODs does not exist in Django
check_irods_files: affected resource ba64d962eb6c460abc9a8628946df116 type is NetcdfResource, title is 'Spatial-temporal statistics of monthly temperature data from the NLDAS model (1979-2013)'
LOOKING FOR FILE ERRORS FOR RESOURCE c9fb977bae21432b8b202f13b62285b1
check_irods_files: django file /hydroshareuserdevZone/home/betaUserProxy/c9fb977bae21432b8b202f13b62285b1/data/contents/SoilMoisture_daily_header_info.txt does not exist in iRODS
check_irods_files: file /hydroshareuserdevZone/home/betaUserProxy/c9fb977bae21432b8b202f13b62285b1/data/contents/NLDAS_NOAH0125_D_002_SOILM0-100cm_CONUS_header_info.txt in iRODs does not exist in Django
check_irods_files: affected resource c9fb977bae21432b8b202f13b62285b1 type is NetcdfResource, title is 'Spatial-temporal statistics of daily soil moisture data from the NLDAS model (1979-2013)'
LOOKING FOR FILE ERRORS FOR RESOURCE f42f1387d7d54d7a9228888381d7c30e
check_irods_files: django file /hydroshareuserdevZone/home/betaUserProxy/f42f1387d7d54d7a9228888381d7c30e/data/contents/Precipitation_daily_header_info.txt does not exist in iRODS
check_irods_files: file /hydroshareuserdevZone/home/betaUserProxy/f42f1387d7d54d7a9228888381d7c30e/data/contents/NLDAS_NOAH0125_D_002_APCPsfc_CONUS_header_info.txt in iRODs does not exist in Django
check_irods_files: affected resource f42f1387d7d54d7a9228888381d7c30e type is NetcdfResource, title is 'Spatial-temporal statistics of daily precipitation data from the NLDAS model (1979-2013)'
LOOKING FOR FILE ERRORS FOR RESOURCE fbc7af608a324a7a9cbbdd415d0a9499
check_irods_files: django file /hydroshareuserdevZone/home/betaUserProxy/fbc7af608a324a7a9cbbdd415d0a9499/data/contents/SurfaceRunoff_daily_header_info.txt does not exist in iRODS
check_irods_files: file /hydroshareuserdevZone/home/betaUserProxy/fbc7af608a324a7a9cbbdd415d0a9499/data/contents/NLDAS_NOAH0125_D_002_SSRUNsfc_CONUS_header_info.txt in iRODs does not exist in Django
check_irods_files: affected resource fbc7af608a324a7a9cbbdd415d0a9499 type is NetcdfResource, title is 'Spatial-temporal statistics of daily surface runoff data from the NLDAS model (1979-2013)'
LOOKING FOR FILE ERRORS FOR RESOURCE fc00c8eaa0944a4a98ea2ddbfe54320e
check_irods_files: django file /hydroshareuserdevZone/home/betaUserProxy/fc00c8eaa0944a4a98ea2ddbfe54320e/data/contents/Precipitation_monthly_header_info.txt does not exist in iRODS
check_irods_files: file /hydroshareuserdevZone/home/betaUserProxy/fc00c8eaa0944a4a98ea2ddbfe54320e/data/contents/NLDAS_NOAH0125_M_002_APCPsfc_CONUS_header_info.txt in iRODs does not exist in Django
check_irods_files: affected resource fc00c8eaa0944a4a98ea2ddbfe54320e type is NetcdfResource, title is 'Spatial-temporal statistics of monthly precipitation data from the NLDAS model (1979-2013)'
LOOKING FOR FILE ERRORS FOR RESOURCE fef58369046c4a64a2d7564c4e7e1fd0
check_irods_files: django file /hydroshareuserdevZone/home/betaUserProxy/fef58369046c4a64a2d7564c4e7e1fd0/data/contents/Evapotranspiration_monthly_header_info.txt does not exist in iRODS
check_irods_files: file /hydroshareuserdevZone/home/betaUserProxy/fef58369046c4a64a2d7564c4e7e1fd0/data/contents/NLDAS_NOAH0125_M_002_EVPsfc_CONUS_header_info.txt in iRODs does not exist in Django
check_irods_files: affected resource fef58369046c4a64a2d7564c4e7e1fd0 type is NetcdfResource, title is 'Spatial-temporal statistics of monthly evapotranspiration data from the NLDAS model (1979-2013)'
LOOKING FOR FILE ERRORS FOR RESOURCE ff2a6f87817544a08c82ebcf119bae80
LOOKING FOR FILE ERRORS FOR RESOURCE ff2e648104254ee4bcf8db925170ea91
check_irods_files: django file /hydroshareuserdevZone/home/betaUserProxy/ff2e648104254ee4bcf8db925170ea91/data/contents/Temperature_daily_header_info.txt does not exist in iRODS
check_irods_files: file /hydroshareuserdevZone/home/betaUserProxy/ff2e648104254ee4bcf8db925170ea91/data/contents/NLDAS_NOAH0125_D_002_TMP2m_CONUS_header_info.txt in iRODs does not exist in Django
check_irods_files: affected resource ff2e648104254ee4bcf8db925170ea91 type is NetcdfResource, title is 'Spatial-temporal statistics of daily temperature data from the NLDAS model (1979-2013)'

**Comment by dtarb** [comment]
Spreadsheet of problem resources is https://docs.google.com/spreadsheets/d/1Dsjf3sTAE2IR6Iof0_34Ltffhq60OU8KgzTlbDaaokA/edit#gid=1690358350.

Two that we did not determine cause of problem are
b9d7cad559e4a69ae7d4d955c895024
d0885da51fda4ec99f6f0a59295c3d7c

**Comment by dtarb** [comment]
The student who created 1b9d7cad559e4a69ae7d4d955c895024 reported that the folder structure was flattened on www when the resource was created.  This may have something to do with the problem.

**Comment by dtarb** [comment]
I did some further testing with files from the problem resource.  I made a subset test.zip that I uploaded to 
https://beta.hydroshare.org/resource/cb1de7d3705c42f4aa72005ef3931302/.  Bag download for this works.

I then uploaded the same zip file to https://beta.hydroshare.org/resource/914291a92bb6409c9395608f34962ea8/.  I unzipped here, and deleted the original zip file.  Bag download fails (hangs forever).  The zip file has a folder in it, unpacked correctly from the original zip file.

I then uploaded the same zip file to www https://www.hydroshare.org/resource/9b3d3f83ef2a4a6fb243ae0fa75a3787/ and unzipped and deleted the original zip file.  Bag download works and the folder is preserved in the downloaded bag.  

Thus this is a repeatable way to create resources that cannot be bagged in beta but work properly in www. @alvacouch @hyi @mjstealey

**Comment by dtarb** [comment]
Promising signs based on new candidate release based on iRODS 4.1.8 6/6/17.

1b9d7cad559e4a69ae7d4d955c895024 bags and downloads properly.
Also 9b3d3f83ef2a4a6fb243ae0fa75a3787 dowloads properly.

I eagerly await @Castronova testing.

**Comment by dtarb** [comment]
I did notice when comparing old (www) and new (beta candidate release) bags that manifest-md5.txt and tagmanifest-md5.txt files are different.  They have the letters sha2: at the beginning of most lines and the code is different.  Is this intentional or desired.  Is this consistent with our resource data model.  Could @horsburgh and @hyi please comment.

**Comment by mjstealey** [comment]
@dtarb - likely due to a setting that wasn't made on the repaved iRODS servers. Needed an update to `/etc/irods/server_config.json` on each server.

```
"default_hash_scheme": "SHA256",
```

to

```
"default_hash_scheme": "MD5",
```

**Comment by hyi** [comment]
@dtarb @horsburgh @mjstealey gets to the bottom of this - yes, the default_hash_scheme needs to be set to MD5 on the server side in order for MD5 hash scheme to work properly. Currently, we set it to MD5 on the irods client side, to make it work properly, the same MD5 hash scheme needs to be set on the server as well. @mjstealey could you set default hash scheme to MD5 on the server, then restart the server whenever you get a chance? Then we can test it again and it should work as expected after this is done.

**Comment by mjstealey** [comment]
> set default hash scheme to MD5 on the server, then restart the server whenever you get a chance

Have done this on both servers and set `bag_modified=true` for all resources to force new bag generation on next download.

**Comment by horsburgh** [comment]
Sounds like I don't need to comment further.  Looks like you all got to the bottom of it.

**Comment by hyi** [comment]
@mjstealey Thanks. I have tested it out and it appears to work as expected now. @dtarb You can test again when you get a chance and let us know if you see any further issues.

**Comment by ChristinaB** [comment]
I have a new broken resource that had all the files deletes from it when I tried to upload a new version of a file, but a file with the same name already existed.   https://www.hydroshare.org/resource/7a77f525667b42f69cdc3f8db18e1280/
The data has disappeared and even in edit mode, there is no way to attempt to add in new files except to drag and drop.  

I tried to recreate this issue with a new composite resource, and the system worked as expected by giving an error, but no other files were deleted/removed.  

1.  Create new composite resource - add multiple files with similar version names
![image](https://user-images.githubusercontent.com/4108369/28132722-7eaa9874-66f2-11e7-8706-525244469d24.png)

2. Edit Resource and Add a file with the same name (by accident!).  File Upload Failed Error Received.
![image](https://user-images.githubusercontent.com/4108369/28132777-af290ae4-66f2-11e7-8996-d31da88ff69f.png)

What is the difference between this resource that is now broken https://www.hydroshare.org/resource/7a77f525667b42f69cdc3f8db18e1280/
and this resource https://www.hydroshare.org/resource/9c564489f08b48efa1851d796d426b6f/ that gives an error but does not delete the rest of the files?
