### ISSUE TITLE
Add file from iRODS fails on beta release candidate

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2059]
Testing the composite resource type I receive "Validation Error: folder" when attempting to add a file from iRODS (after the resource has been created).  Note that this works on www (1.9.6) and that I am testing using a small file from data.iplantcollaborative.org.  Note that adding a file from iRODS works during the create process, but not when a resource already exists and a file is being added.

**Comment by mauriel133** [comment]
@hyi, could you take a look at this one? I'm unable to test iRODS at the moment.

**Comment by hyi** [comment]
@dtarb @mauriel133 I tested on beta and found this error only happens with composite resource, and works fine with generic resource. @pkdash You may take a look first to see if you can fix this issue first, since it appears to be a composite resource specific issue. Let me know if you cannot find a quick fix.Then  I can take a look tomorrow.

**Comment by pkdash** [comment]
@dtarb Were you trying to add the file to a specific folder when you got this error?

**Comment by hyi** [comment]
@pkdash I tried on beta, and this happens when adding files from irods to a composite resource, not within a folder. What I did is to create a composite resource without uploading any files, then from resource landing page, login to irods and add a file to this empty composite resource, then I got an error. This does not happen to other resource types such as generic resource type. You can use hsproxy irods user account credential in local_settings.py to test and debug, should be easily reproducible.

**Comment by pkdash** [comment]
@hyi I added some unit tests to reproduce this error. But unit tests do not fail. I am running local irods. But I don't know how to reproduce this locally using the UI. Can you give me some instructions?

**Comment by hyi** [comment]
@pkdash I think you can just create an empty composite resource, then login to irods using hsproxy irods account credential (if you don't already have other irods accounts) or use your irods account if you have created a corresponding iRODS account in user zone from your profile page, and browse and select any file under that irods account to add to this empty composite resource, and you should be able to reproduce this error. Have you tried this?

**Comment by pkdash** [comment]
@hyi I tried using the information from the local_settings.py file to login into iRODS. Login failed. Then I tried to create iRODS account in my profile page. The account got created. Then when I tried to use that account to login to iRODS login failed. I am not doing something right I guess.

**Comment by pkdash** [comment]
@hyi I was able to login using the info from settings file.

**Comment by pkdash** [comment]
@hyi I am able to reproduce the error. Thanks for your help.

**Comment by pkdash** [comment]
@hyi I am looking at this function. 

https://github.com/hydroshare/hydroshare/blob/develop/irods_browser_app/views.py#L150

Is it not possible to upload a file from IRODS to a specific folder? I need to pass a folder parameter to the file pre_add and post_add signal call.  The file add view function that we have in hs_core allows a folder to be specified.

**Comment by hyi** [comment]
@pkdash I believe iRODS browser has not been updated to allow users to add a file from iRODS to a specific folder. I know the file add view function allows to do that, but we need front end UI change to specify the folder to add files from iRODS to in order to allow adding files from iRODS to a specific folder. Perhaps @mauriel133 can work with you to help with front end changes to make this happen? I don't think this can be done for release 1.10 though, so it'd be good just to fix this error and worry about adding files to specific folder later? I'll leave it up to you on what you can do for release 1.10 regarding this.

**Comment by pkdash** [comment]
@hyi Sounds good. I will just fix the error.

**Comment by dtarb** [comment]
tested on beta and found fixed loading files from iplant.
