### ISSUE TITLE
Metadata editing button not present for raster resource types for new landing page layout

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#209]
Testing on alpha I am unable to edit a raster resource type due to the edit button not being present on the landing page

**Comment by hyi** [comment]
@dtarb Do you mean you tested it on dev since raster resource type is not present on alpha yet? I am able to see edit button for raster resource type and able to edit it as expected. Can you elaborate a bit on how I can reproduce the issue you are seeing as I cannot reproduce the problem?

**Comment by hyi** [comment]
@dtarb Just realized you might have tested it on sandbox since the permissions for raster resource type have not been added for HydroShare Author group on sandbox yet. If this is indeed the case, you can test on sandbox again. It should work now after I assigned these raster resource type specific permissions to the group.

**Comment by dtarb** [comment]
Yes I tested on sandbox (sorry for the slip).  It is working on sandbox now.

**Comment by yirugi** [comment]
We are still waiting for  a REST API to set resource-specific metadata, SWATModel Instance for us. Is it possible to know the current status?
