### ISSUE TITLE
Active users as default view in Kibana

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#2094]
@Castronova and @martinseul 
Could we update the what the user sees first in the portal so that they first see the Active users, and then bury the total users a bit further down the page. Since 50% of the total users have only visited once, it is a bit unintentionally misleading.  

From there we can also drill down into who is really using HydroShare (at least more than once) and develop metrics that help us be strategic from there.

**Comment by Castronova** [comment]
@ChristinaB  
This page was designed to show all users, both active and inactive.  I can apply a filter to omit everything but **active** users, but this would mean that won't be able to view total users at all.  Is this what we want to do?  I'm not worried about what "users" see since this is mostly a website for developers to use.  For users we should expose only very specific visualizations, not the entire kibana site.
