### ISSUE TITLE
Incorrect user logged as making automatic changes

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#2103]
@dtarb @pkdash @hyi @aphelionz There are many situations in which a state change is made automatically as a result of internal rules, rather than by a user. Repairs are just one case. Another case is when a resource is made private due to violating some requirement for being public.
 
Repairs are currently being attributed to `resource.creator`, because no one else makes sense as the person repairing something. It certainly isn't `admin` -- that's a person, too. 

The typical way of handling these changes in computing systems is to make up a special user `Daemon` to which these changes are attributed. I would like to make up a user `Daemon` and attribute all automatic repairs to that user.

**Comment by hyi** [comment]
@alvacouch My two cents: I think it'd be better to use admin for this rather than creating a new user Daemon. I think the repair work being done is like a daemon process that works behind the scenes and in the background, however, from access control perspective, I think this daemon repair/cleanup work probably should be triggered by admin when needed or just be set up to run nightly as a job or task in which case we probably do not need to care about attribution or access control for it?

**Comment by dtarb** [comment]
I would like what a user sees in the Last Updated entry on a resource landing page and the Dublin Core Date Modified entry in resourcemetadata.xml to be clear and reflect meaningful changes.  I think Daemon is counter intuitive.  I would be OK with "System".  I see three cases
1. Repairs.  Something about the resource was broken, and the system changed the resource to attempt to fix it.  These should be logged as "System" and owners should be informed (sent an email).  Change of last updated metadata and message to owner should only occur if this repair is something a user could see.  If this is a repair to our internal representations (e.g. inconsistent Django database and files on disk, or inconsistent AVU's) then it is not a change that should reflect in the metadata a user can see on the landing page or in resourcemetadta.xml file.
2. Change in access due to the rules for a resource to be public.  The switch to private is directly triggered by a use with edit permissions changing something.  So the user logged for making that action is the user doing the editing.  
3.  Changes to the resource as a result of being migrated during a system upgrade.  Typically these involve changes to the bagit files or xml metadata files as the data model is changed.  I do not think these should be regarded as changes for the purpose of metadata that I user can see and I would prefer the Last Updated indicator on the resource landing page and modified indicator in resourcemetadata.xml to not be changed.  I think that these metadata elements should reflect tangible changes to the content of the resource, not system changes.

**Comment by alvacouch** [comment]
@dtarb For (2), the calls that actually make that happen don't know who the user is. This will require adding "user" as a parameter to a long chain of calls. Right this second, they attribute the change to "creator".

**Comment by alvacouch** [comment]
@hyi Many of these changes aren't the result of administrative commands. In that case, 'admin' -- which is a person -- doesn't make sense.

**Comment by alvacouch** [comment]
Actually there are many places in the code where the "last modified by" field is set to resource.creator because of no better option.

**Comment by dtarb** [comment]
I agree that what, and to whom automatic changes are attributed needs sorting out as part of clean up.  In my prioritization, this is a misleading, as opposed to a breaking of functionality problem, so a bit lower priority, but nevertheless important.

**Comment by alvacouch** [comment]
@dtarb @hyi @pkdash @aphelionz I propose a very simple solution to this that will be more functional to users and more easily understandable.  First, I agree that the user who initiated the change should be attributed as making it, even if that change is an implied change to `private`. 

**I propose as well to store the provenance of the last change to `public` or `private`, and _display this provenance on the resource landing page._**

So, on the resource landing page, after the initial setting to `public` ,it would not just allow one to set `public` or `private`. It would also say, beside this, either: 
* Set to `public` on {date} by {username} 
* Set to `private` on (date) by {username} **as a result of resource changes**  (if the change was automatic) 
* Set to `private` on {date} by {username}   (if the change was manual) 

Thus, this simple thing would not just show that it changed to private, but who made the change that made it private, and when. **This is the only way we could know that a non-owner made the change.**

**Comment by pkdash** [comment]
If we want the provenance of the last change to resource flag, I think it is better to do this for all flags - public/private, discoverable, published.

**Comment by dtarb** [comment]
I support recording and displaying set to public, set to private etc as @alvacouch suggests and adding
* Set to `discoverable` on {date} by {username} 
* `Published` on {date} by {username} 

as @pkdash suggested.

**Comment by eclark-cuahsi** [comment]
@martinseul please test to confirm this is still an issue or not.

**Comment by dtarb** [comment]
Closing as was an issue with usage tracking and may have been fixed.  In any event no longer an issue.
