### ISSUE TITLE
Space-time resource step 1 Net CDF Services

### ISSUE THREAD

**Issue by valentinedwv** [hydroshare/hydroshare#211]
Task (make NetCDF available via services):
* Expose NetCDF via Irods: 
  * replicate to an irods server and implement a software stack to publish as a WCS for a raster
* On to a landing page, add publish as a web coverage service
* only public data

Iterations:
* check against vocabulary for netcf or CSDMS terms
* my file uses CF concentions, CSDMS conventions\. 
* Checks to see if netcdf follows appropriate profile

**Comment by valentinedwv** [comment]
Resources to look at:
* https://github.com/irods/irods_netcdf 
* https://wiki.irods.org/index.php/NETCDF
   * not in irods 4.x, but is an example of what might be done

**Comment by zhiyuli** [comment]
I think this is not an Apps issue?!

**Comment by dtarb** [comment]
@rayi113 I am putting this in Data Management as the work you have done on THREDDS using FUSE is pertinent here.

I think that an approach to achieving what we need is
1.  Establish a THREDDS server running as part of our infrastructure
2.  Have this THREDDS server mount hydroshare iRODS resources through FUSE
3.  Establish button on Multidimensional space time resource editing page to expose using THREDDS.  This button puts this file or a symbolic link to it in the directory mounted for the THREDDS server so that the resource data files become available through THREDDS

I am removing the release 1.7 milestone as we need to further think through and prototype before being ready to place in a milestone.  I encourage @gantian127 @rayi113 @hyi and @danames to discuss and work out the details.  @danames to what extent is this related to the netCDF browser functionality you showed.

**Comment by rayi113** [comment]
See picture below for a summary of the plan forward discussed at the 09/16/2015 weekly HydroShare team mtg:

![hydroshare_thredds](https://cloud.githubusercontent.com/assets/2846017/9917535/2f9b55f2-5c90-11e5-9d8a-49b950bfd04a.png)
