### ISSUE TITLE
Resource bag cannot be created due to download poll errors

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2111]
For the resource https://beta.hydroshare.org/resource/93f49ab913fd4c639c98ab4a070d20e0/ on current release candidate, when I try to download bag, I get the following error

![image](https://cloud.githubusercontent.com/assets/3456833/25851964/065602d6-3485-11e7-8c55-c2a879c321cd.png)

I checked the debug information on this resource and note no issues reported but that quotaUserName is None and bagmodified is true.  Not sure if one of these could be the problem as bag_modified should be false for a resource where we have created a bag.
![image](https://cloud.githubusercontent.com/assets/3456833/25852232/ea24bce6-3485-11e7-9660-fa2b4e269ec9.png)

This is not a problem unique to this resource.  It also occurs for https://beta.hydroshare.org/resource/7ca4a9c95d344825b68e868ec446c8ca/, another older geographic feature.

And an older Geographic raster
https://beta.hydroshare.org/resource/3941d5cd22dd4a248655ca2b4654d85d/

There is a systemic problem here.

**Comment by alvacouch** [comment]
This probably has nothing to do with files, because there's no ambiguity there according to the checker. The file redo didn't do anything to bag handling. Bags are handled by a different part of the code.

This is more likely a clearer expression of a long-standing, intermittent problem with downloading bags, including the inherently asynchronous nature of bag creation and the possibility of encountering timeouts of several kinds in creating and downloading bags...

There was previously a skew between `isPublic` in iRODS and `public` in `BaseResource.raccess` for older resources that could also come into play. I discovered that `isPublic` was largely left blank for older resources, and **in the current 1.10.0 release candidate, I explicitly set `isPublic` for all older resources to either "true" or "false".** This is something that is different for older resources in this particular version. However, I always set them to the string "true" and not "True", which indicates that this particular resource was **already set to public in iRODS before the migration.**

**Comment by alvacouch** [comment]
Hmm. I looked at the code for this last week. I remember three parts to the bag download: 

1. Start a celery task to build the bag.
2. Wait in a polling loop for that specific task to finish. 
3. When the poll returns "done", send the bag. 

It is complaining that the polling loop itself crashed. In other words, **the poll _command_ failed**. This might indicate a problem with starting up the job in celery, or that the job crashed in celery. Just a thought. 

My suggestion is to instrument the polling loop and print its errors to the error log.

**Comment by alvacouch** [comment]
What happens when one downloads a bag:

* Click on return value of resource.bag_url 
    * This generates the path bags/{resource-id}.zip
    * Which is passed to `istorage.url(name)` (in django_irods/storage.py) 
    * And results in the iRODS path for the bag. 
    * Which is `reverse(‘django_irods.views.download’, kwargs={‘path’: name})` 
    * Which resolves to `download/{name}` 
    * Which calls `django_irods/views.py:download`
* `django_irods/views.py:download` has separate use cases for resource files and bags. In the bag section, this calls back (in the HydroShare tree)
    * pre_check_bag_flag.send(sender=resource_cls, resource=res)
         * Which activates rules for hs_collection_resource/receivers.py
    * task = create_bag_by_irods.apply_async((res_id,), countdown=3)
         * Which calls hs_core/tasks.py:create_bag_by_irods
         * Which calls hs_core/hydroshare/hs_bagit/create_bag_files 
     * pre_download_file.send(sender=resource_cls, resource=res, 
       download_file_name=download_file_name,    request=request)
         * Which activates rules for hs_collection_resource/receivers.py
     * An iget to stdout of the direct response from iRODS

Note that these activate procedures in `hs_core` based upon `django_irods`. **These are separate repositories.** Thus it is possible that something updated in one was not updated in the other.

**Comment by alvacouch** [comment]
Simply turning off `use_async` yielded the following: 
```
'NoneType' object has no attribute 'lower'
Request Method:
GET
Request URL:
https://cuahsi-dev-1.hydroshare.org/django_irods/download/bags/7ca4a9c95d344825b68e868ec446c8ca.zip
Django Version:
1.8.14
Exception Type:
AttributeError
Exception Value:
'NoneType' object has no attribute 'lower'
Exception Location:
/hydroshare/hs_core/tasks.py in create_bag_by_irods, line 178
Python Executable:
/usr/local/bin/python2
Python Version:
2.7.11
Python Path:
['/hydroshare',
 '/usr/local/bin',
 '/src/python-irodsclient',
 '/hydroshare',
 '/usr/local/lib/python27.zip',
 '/usr/local/lib/python2.7',
 '/usr/local/lib/python2.7/plat-linux2',
 '/usr/local/lib/python2.7/lib-tk',
 '/usr/local/lib/python2.7/lib-old',
 '/usr/local/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/site-packages',
 '/hydroshare']
Server time:
Wed, 10 May 2017 14:21:59 +0000
```

**Comment by hyi** [comment]
@dtarb @alvacouch @mauriel133 I debugged this issue and it appears to be a systematic issue resulting from recent front end javascript refactoring. Specifically, the ```task_id``` and ```download_path``` are all ```undefined``` in https://github.com/hydroshare/hydroshare/blob/develop/theme/static/js/generic-resource.js#L387-L388 when downloading a bag being regenerated. Will have to look into it a bit more and make a fix. This fix has to go into a hotfix.

**Comment by hyi** [comment]
@dtarb @alvacouch @mauriel133 I build release-candidate-1.10 branch locally but cannot reproduce this issue, so not sure what is going on. Have to look into beta specifically to see why the task_id and download_path are all undefined in https://github.com/hydroshare/hydroshare/blob/develop/theme/static/js/generic-resource.js#L387-L388 when downloading a bag being regenerated on beta but somehow it works in my local environment.

**Comment by pkdash** [comment]
@hyi I assume this is happening with only specific resources on beta. Locally I think you are testing with new resources you created. I did not see this problem on beta when I created a new resource.

**Comment by hyi** [comment]
@dtarb After I add 'metadata_dirty' AVU manually to these three resources you listed here, all bags can download successfully. You can try to verify them. This confirmed @alvacouch 's fix should fix this issue. I deleted my previous comments since they are not applicable any more.

**Comment by dtarb** [comment]
I tested using the following https://beta.hydroshare.org/resource/3941d5cd22dd4a248655ca2b4654d85d/ https://cuahsi-dev-1.hydroshare.org/resource/3941d5cd22dd4a248655ca2b4654d85d/ resource that was one of the ones I reported the problem for and both resulted in hanging with ....... forever, rather than downloading the bag.

**Comment by alvacouch** [comment]
See issue #2056 for cause. It is the same behavior now. iRODS fails with misconfiguration errors.

**Comment by dtarb** [comment]
Appears to be sorted out on beta.  The 3 resources above downloaded properly.  Closing.
