### ISSUE TITLE
Beta 1.10:  Initial My Resources Page View Needs to Change

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2116]
The current implementation of release 1.10 has changed the way resources are listed on the My Resources page. When the page loads, I can now see all of the resources that I own/created, things that I have added to my resources, and anything that has been shared with me - including via a group. This adds a huge amount of potential clutter and may eventually affect performance as the number of resources grows.  

The default view should change. When the page loads, I should see only those resources that are owned by me or that I have specifically added to My Resources using the "Add to My Resources" button. The filters on the left part of the page should then change to:

1. Editable by me
2. Shared with me
3. Favorites

Numbers 1 and 3 should behave as before. Number 2 would only list things that I am not an owner of that have been shared with me (either personally or via a group).

I think the "Viewable by Me" facet is no longer needed. It's confusing anyway because I can "View" any public resource in HydroShare but I don't expect a list of all public resources to show up on the "My Resources" page. That's what the "Discover" page is for.

**Comment by dtarb** [comment]
There is a design document.  See https://docs.google.com/document/d/1gclvwj76lVnxKFHyov3R3VgDVGr65agaU7fywMFLM_E/edit.

Interesting to note that it has the Filter "Shared with me".  I think that the current implementation Viewable by me was an attempt to make a clearer distinction between resources shared with me at edit permissions and shared with me at view permissions.  Just saying "Shared with me" does not convey this. 

The document and current implementation does not address the circumstance we face now which is whether resources shared with me explicitly as a user, or shared with me by virtue of being a member of a group with which a resource is shared should be listed by default.

The current implementation also suffers from not defining the sets clearly and including Owned by me and Editable by me in the Viewable by me set which is confusing and does not provide a way to filter only to the resources shared with a user.    It also is unclear what to list when multiple filters are selected.  Should resources shown be an intersection or union of the sets selected.  I think that we should use a union rule.  With this mutually exclusive sets are better, because they enable finer filtering.  I therefore suggest the following filters, rules and definitions

- [x] Owned by me
- [x] Following (Added to my resources)
- [ ] Editable by me
- [ ] Viewable by me
- [ ] Favorites

Rules and definitions
1. By default (when the page is opened) the top two boxes are checked
2. If no boxes are checked then no resources are shown.  This may be counter intuitive, but as long as two boxes are checked when the page opens, I think the functionality will be quickly learned.
3. Editable by me includes resources not owned by the user, but that have been shared with the user as an individual or with a group that the user is a member of.
4. Viewable by me includes resources not owned by the user, but that have been shared with the user as an individual or with a group that the user is a member of.
5.  By virtue of rules 3 and 4 Owned by me, Editable by me and Viewable by me are strictly mutually exclusive.  This differs from the current implementation which includes Editable within Viewable and provides no way to filter to resource only Viewable.
6. "Following" are resources that the user has specifically selected with the "Add to my resources" button.  Introducing this adds the capability to identify the resources added in this way.  Right now there is no way to filter to the resources a user as added to my resources.

**Comment by horsburgh** [comment]
@dtarb - if we want to follow the design document that's fine. It was written by a particularly inspired individual. If you want to check "Owned by me" and "Following" as defaults, that's fine. I wouldn't add the "Added to my resources" text because it will make the label too long. There's an opportunity here for simplification as I suggested above, but if you don't want to do that, we can stick with the design document.

Now, as to implementation, the fact that we are using check boxes that allow multiple facet selections instead of mutually exclusive radio buttons or the like means that we intended to allow multiple selections. We don't have to do it this way, we could switch the selection dialog to be mutually exclusive (i.e., you could only select one of the browse facets at a time). We are currently using the intersection rule, and, yes, resources "owned by me" and "editable by me" are included in the "viewable by me" set because they are, in fact, viewable by me. So, if you want different behavior, we need to change the rule and potentially define a different category.

I would be OK if the union rule was followed. For example, if I check "Owned by me" and "Editable by me" at the same time, I get back the list of resources for which I am the owner *OR* for which I have been granted specific edit permissions. I don't believe this is the typical way for faceted browsing to work thought. Usually when you check two boxes it's an *AND* selection.

I am also mostly OK with your definitions above with the following exceptions:

* Number 3 is not specific enough (as written above, it is the same as number 4) - it needs to be resources not owned by the user, but that have been shared with the user as an individual or with a group that the user is a member of **with explicit Edit permissions**.
* I do not like the label "Viewable by me". It's confusing. Is it things that have been shared with me at the view only level, or is it everything in HydroShare that I can view (e.g., all public resources included)?  It should definitely *NOT* be the latter. I can't think of a better label that is shorter than "Shared with me at view level".

As a simpler alternative  - do we need the "Editable by me" and "Viewable by me" facets at all?  Could we get by with only:
1. Owned by me
2. Shared with me
3. Following
4. Favorites

That's still one more than Google Drive has if you don't count their "Recent" filter.

**Comment by dtarb** [comment]
How will you inform users that Following = Added to my resources, or is there a different term you want to suggest.

I do not want to switch the selection dialog to be mutually exclusive.  I like that multiple check boxes can be picked and if a user picks multiple check boxes I think the only logic that makes sense is a union of the sets selected by a single check box.  Otherwise selecting Owned by me and Shared with me would result in 0 because it is impossible for a resource you own to be shared with you.

Google Drive has folders.  If we had folders we could do a lot more organization, but we do not.

I clarified my comment above to separate 3 and 4 to be with explicit Edit permissions and with explicit view permissions.

If you insist on combining "Editable by me" and "Viewable by me" into one "Shared with me" I am OK with that.

**Comment by dtarb** [comment]
Let's go with the 4 above that @horsburgh suggests

Let's use the definitions (which are not strictly mutually exclusive)
1. Owned by me.  The user is the owner.  This can overlap with favorites as a user can favorite resources they own.
2. Shared with me.  The user is not the owner, but the user has access at either edit or view level by virtue of the resource being directly shared with the user, or by virtue of the resource being shared with a group that the user is a member of.  This can overlap with favorites as a user can favorite any resource they have access to.
3. Added by me.  The user has added this resource.  These should not overlap with Owned by me or Shared with me as you can only add a resource that is not already part of My Resources, but is public, published or discoverable.  If a resource a user has added, is later shared with the user or they are made an owner, then there is potential for overlap with (1) or (2), and in these cases we should remove the Added by me flag to avoid this overlap, noting that the interface for resources shared with a user does not have the Add to my resources button.  
4.  Favorites.  These are resources where the user has specifically set the "Favorite" flag.  They can overlap with others.

Each of the above should be regarded as sets.  The first 3 are mutually exclusive, but there is overlap with Favorite.  We should retain check boxes in the interface, and if multiple items are selected the list shown should be the union of the sets.  If no boxes are checked, or all boxes are checked the result should be the union of all the resources.  By default when the page opens, the boxes Owned by be, Added by me, and Favorites should be checked, but not Shared with me. I am open to changes to this initial setting which was the "problem" that opened this issue in the first place.

**Comment by horsburgh** [comment]
@dtarb - this seems like a reasonable plan.

**Comment by Maurier** [comment]
I've implemented these changes at https://park.hydroshare.org/my-resources/

Please test it out and let me know if you have any feedback.

**Comment by horsburgh** [comment]
@Maurier - I think these look good. One issue from @dtarb 's comment above:

> By default when the page opens, the boxes Owned by be, Added by me, and Favorites should be checked, but not Shared with me.

Your default is that "Favorites" is not checked, but it should be.

Also - just to be clear - what is the set of resources that is shown when there are no boxes checked?

**Comment by dtarb** [comment]
The functionality looks good to me.  Great work.

I did find the system slow on some things, like when I mistakenly selected all resource I had and clicked Favorite.  It took a few minutes to apply favorite to the 138 resources I have and my computer was sluggish while this was going on.

**Comment by horsburgh** [comment]
@dtarb - I agree. There's still some slowness here on loading the page in particular. I think we should make that a separate issue (there may already be one) so @Maurier can close this issue.

**Comment by Maurier** [comment]
> Your default is that "Favorites" is not checked, but it should be.

Noted. I'll make this change.

> I did find the system slow on some things, like when I mistakenly selected all resource I had and clicked Favorite.

Indeed. This happens because we make a request for each instance. We will need an endpoint that can handle multiple instances in one request. This is complex on it's own and would need another ticket.

Some changes I can make for consideration:

- Add a paginator to the table. 
- Save the state of the filters in the browser's local storage to allow users to use their own defaults.

**Comment by aphelionz** [comment]
@Maurier @horsburgh @dtarb This may be able to be closed after 1.14 goes out

**Comment by dtarb** [comment]
I checked this out and noticed that the layout changes as you toggle on and off filters.  

E.g. With shared with me on, I get the privacy and shareable icons below the Type icon
![image](https://user-images.githubusercontent.com/3456833/33520319-139e65de-d776-11e7-87e0-7fd18060a15a.png)

but when I turn shared with me off, they flip to the right.
![image](https://user-images.githubusercontent.com/3456833/33520324-320077f6-d776-11e7-88c4-7ef4746a6772.png)

This is not a show stopper, but seemed a bit odd.  Also I think we should indicate what Recent is (e.g. 1 week, one month, or what.

I am happy to leave to @Maurier and @horsburgh to resolve or not.

**Comment by aphelionz** [comment]
@Maurier @horsburgh close? or close and create a new issue?

**Comment by Maurier** [comment]
I think we can leave it open for a few more days. This week I'll work on that alignment issue pointed above and then we can close it.

**Comment by horsburgh** [comment]
@Maurier - I was about to close this. Are you still working on it?

**Comment by Maurier** [comment]
@horsburgh This issue can be closed. I submitted one last PR that solves the minor alignment issue described above. 

We could discuss how to add a description to the Recently Updated later on. This should be a minor change.

**Comment by horsburgh** [comment]
Closing since @Maurier has taken care of the last minor alignment change.
