### ISSUE TITLE
Multiple folder drop resource crash

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#2119]
@alvacouch 
I have broken another resource for you which may help amplify the canary in the coal mine.  
I have made you an owner of 
https://www.hydroshare.org/resource/636878cd2380443b907d25aa51a7043a/

These are the steps that led to the demise of this resource:
1. Create resource
2. Drag and drop one folder.
3. While the folder was still uploading, drag and drop another folder
4.  The uploading messages looked like it was busy doing something, and would start uploading with messages about the size and progress, but it was not clear what was being uploaded... each file in the folder? with a restarting upload message for each one?  
5. Eventually the uploading stopped but the data and content folder gave a message that they are empty.  
6. The next day I revisited it and the data and content just gave me a blue spinning wheel.  

When we do an operation on our computer such as unzipping from the same program, we can do parallel operations, so users may try to drop additional folders, while one folder is still uploading.    I am not sure about parallel uploading into places like Google and Dropbox.  

One solution is that HydroShare should prevent the user from attempting a parallel upload with a message box.   We may need to add more uploading messages in the next release.

**Comment by ChristinaB** [comment]
I also made you an owner of this resource 
https://www.hydroshare.org/resource/e621db2061b648668d3b4ad80d4ce525/

I specifically was careful not to attempt folder drops while other folders were uploading.  In this case,

1. Drop 300mb zipped file into resource.  This appeared fine. 
2. Simulaneously drop multiple folders.  This now shows no content.  

@Castronova  -- I'm trying to get the DHSVM test data to you ! Really trying...

**Comment by dtarb** [comment]
@ChristinaB one of the causes for these problems that Alva tracked down was dots in file/folder names.  If you want this to work to get a job done, avoid dots for now.  This is hopefully to be fixed in the near future.

You could also try do this sequence on http://beta.hydroshare.org.  However be aware, that beta is a separate and transient virtual universe, so nothing will persist there.  It is good for debugging, and for perhaps getting stuff to Tony temporarily, but it may go "poof" at random.  If this works on beta, it is good news as it means the improvements already implemented have fixed these problems.  If this fails on beta, you can type /debug/ after the resource GUID in its landing page and get a debugging report that would be informative to Alva.

**Comment by alvacouch** [comment]
@ChristinaB Dots in folder names are fixed in PR #2118 and up for testing on [https://CUAHSI-dev-1.hydroshare.org](https://CUAHSI-dev-1.hydroshare.org) as noted elsewhere. They are not pushed to beta yet. This is my personal development server at RENCI. 

@dtarb The more difficult problem of dealing with concurrent operations I am just starting to address. For now, concurrent operations aren't going to work reliably. 

Anyway, I am trying to get people to bang on CUAHSI-dev-1.hydroshare.org and see if at least the '.' problem is fixed. I am aware now, however, of other bugs that cause file corruption.

**Comment by alvacouch** [comment]
@ChristinaB  @dtarb See #2122 for further discussion on this issue. I have done my best to prevent file corruption for 1.10.0, but have not been able to come up with a simple and consistent way to prevent concurrency botches of the kind you describe. Will take this on for 1.11.0. So for now, caveat emptor.

**Comment by ChristinaB** [comment]
I think this is concurrent with other issues so am closing
