### ISSUE TITLE
Display a warning when user removes himself as owner

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#2127]
I was setting permission for a resource I owned. I accidentally removed myself as owner. The changes took effect immediately once the dropdown closed. It left no time to regret as I have no permission to change it back any longer....
It is better to show a warning and let user confirm this kind of change.  
![image](https://cloud.githubusercontent.com/assets/10070599/26179754/bab87eb8-3b22-11e7-9747-45e67b95f230.png)

**Comment by dtarb** [comment]
The system has this warning 
![image](https://cloud.githubusercontent.com/assets/3456833/26385531/9830251e-3ffd-11e7-907e-eb87f37cf7ae.png)
What more do you want.

**Comment by dtarb** [comment]
OK.  I see the problem.  If an owner by mistake switches themselves to view, then they do not have permissions to set themselves back to owner, and even on beta the new undo functionality does not address this.  We should add a warning similar to the above to any action that lowers the permissions of the active user.

**Comment by engineSound** [comment]
@zhiyuli I reproduced this one on dev-hs-5.cuahsi.org.  It has the latest code from develop with @Maurier resource landing page redesign.

@martinseul Here is how I reproduced:

1. Have the owner of a resource added me as an owner of the resource. Now there are two owners, the one who created the resource (quota holder), and me. 
2. Login hyrdoshare as me and access the resource. Verified I am an owner.
3. Go to the sharing panel, change my privilege from "Is owner" to "view". **There is no warning message.** 

@dtarb The source code says there is such a warning message box. But I didn't see it popping up.

**Comment by dtarb** [comment]
Yes I agree there is a bug in dev-hs-5.cuahsi.org

The correct behavior (I just verified this on www) is
1. Create resource
2. Assign a different user as owner
3. Transfer quota to that different owner
4. Remove original owner from manage access.  A warning pops up and if acknowledged the original owner is removed.

On dev-hs-5 the behavior I am getting now is
1. Create resource
2. Assign a different user as owner
3. Transfer quota to that different owner
4. Click X to remove original owner from manage access.  No warning pops up and the resource reverts back to the state where the original owner is the quota holder, so the change made at step 3 did not persist.

**Comment by dtarb** [comment]
Part of the problem may be the warning message coming up behind a modal window.

Another problem is that the new landing page does not show who the quota holder is without going into manage access.

There is also a problem on www - the problem that @zhiyuli reported and I commented on 5/23/17.  If an owner reduces their permission level to view, there is no warning and they are unable to retrieve their permission level back to owner.

**Comment by dtarb** [comment]
Note that when a quota holder is changed, an email gets sent to the new quota holder.  I did not get any email messages from dev-hs-5 with my quota hold change attempts, but then none took effect, and emails go some place else on these dev servers.  Just another thing to look out f you work on this.

**Comment by engineSound** [comment]
@dtarb Thank you for the detailed comments. 

I was able to see the warning message on www after following your procedures. I also found the quota hold change in the sharing panel in the edit mode on dev-hs5. It is moved.  @Lizabrazil I feel we need something like a youtube video to capture users attention so they know the changes. When a new release is out, do we send emails to the users? We can attach a youtube link to the email. 

The Zhiyu's concern needs to be fixed which is this Github issue. I can add a warning dialog when an owner reduces its permission level to view and also make sure it doesn't go underneath the sharing panel.

**Comment by engineSound** [comment]
![image](https://user-images.githubusercontent.com/35352595/52147977-57860080-2636-11e9-9813-0e81961711b1.png)

Issue is fixed and tested on dev-hs-5. You are welcome to verify the result over there. I've asked Mauriel to review and approve the code. PR #3118

@dtarb @Lizabrazil Please give feedback on the wordings. I know it needs to be modified.

**Comment by dtarb** [comment]
Please spell Confirm that is bolded correctly.  Please cross check the wording with the similar message on www when an owner is deleted.

**Comment by dtarb** [comment]
Here is refined wording I suggest based on comparing this with the owner deletion warning: "This action will remove your owner access to this resource.  This removal is not reversible.  Owner access can only be retrieved by another owner later granting you owner access.  **Remove** with caution."  Then name the red action button "Remove"

**Comment by engineSound** [comment]
@Maurier found another place that has the identical impact: When the current user with an owner privilege was invited again with a lower access right, we got into the identical situation.

**Comment by engineSound** [comment]
I recommended giving the user a notification popup when the user has been already on the invited list. So the accidental-reinvite won't kick in.

**Comment by engineSound** [comment]
During the code review, @Maurier pointed an existing hidden bug: The sharing panel can invite a user who already has access. This leads to two consequences. One is we have to unnecessarily check the owner's privilege in case the user (owner) accidently demotes. The other is user experience: This leaves the user guessing.

@Maurier  reviewed my code and I am inline with his recommended way to display an error message when a user to be invited actually already has access. We want to run the error message by @dtarb and @horsburgh .

![2019-02-06_09-30-35](https://user-images.githubusercontent.com/35352595/52349003-98de2d80-29f3-11e9-87c9-8bb7f7650cb1.png)

**Comment by dtarb** [comment]
I would suggest a bit more in the wording
"Error: The user selected already has access.  To change, adjust the setting next to the user in the who has access panel"

A better alternative, if feasible, would be to exclude users who already have access from the list that can be invited.

I also suggest changing the word "Invite" to "Give access" as invite implies an offer or need to accept, and this is not what happens.  Access is immediately enables.
![image](https://user-images.githubusercontent.com/3456833/52351235-91b12280-29e7-11e9-93d2-752da43db730.png)

**Comment by engineSound** [comment]
@dtarb The alternative is better. It is the ideal behavior. Below is my feedback at the level of implementation.

@Maurier @pkdash What I have seen during the code surfing, the autocomplete form with all user list is a generic form and is generated by backend. The front end can certainly do a fitlering. But this will lead messy UI code, hard to debug in the future when autocomplete list doesn't show the right users then we would have to both debugging front end and backend. With this understanding, I am still leaning towards showing an error message which is still a good double-check. I can create an github issue for backend to track this discussion.

@dtarb This is what I am going to do:
* Replacing the panel title "Invite" with "Give Access" makes it consistent with the top panel "Who has access". 
* Use the error message you provided.

**Comment by Maurier** [comment]
@engineSound I think it's better not to filter the list since this might confuse users into thinking the person they are searching for are not in the system.

**Comment by horsburgh** [comment]
@engineSound - your two points above seem reasonable to fix this. I +1 on the suggestion from @Maurier to leave people in the list. I've had some recent experience with another application where I am not showing up in the list of users and it's causing all sorts of confusion.

**Comment by engineSound** [comment]
I concurred with @Maurier. Waiting for final review. Not a regression, no rush.

**Comment by engineSound** [comment]
Merging to develop will be after 1.19 roll out.

**Comment by dtarb** [comment]
@engineSound merging to develop should be as soon as the PR is approved.  It does not have to wait for 1.19 roll out as 1.19 candidate release has a separate branch.

**Comment by engineSound** [comment]
@dtarb I got my confusion of branching strategy cleared. I am going to merge all my open PR to develop as soon as all Jenkins build pass.

**Comment by dtarb** [comment]
@engineSound it is not only passing jenkins tests that are needed.  It also needs approval of code by another developer and documentation requirements if applicable.

**Comment by engineSound** [comment]
Got that. Need to notify @Lizabrazil for documentation. @dtarb What's the recommended practice for documentation? Just discussed with @Lizabrazil We think this need to be separately and fully tracked. So the help/documention go synced with UI.

This is especially essential to me and @Maurier.

**Comment by Lizabrazil** [comment]
Sorry, i messed with my github notifications and missed a lot of comments this past week. I am sifting through these in the next hour.

**Comment by dtarb** [comment]
@engineSound when this was discussed previously with Mark Henderson he set up a PR checklist that included a check for sufficient user and developer documentation.  This was intended to serve as a reminder that before code was merged, documentation needed to be addressed.  However the way that documentation should be addressed is left flexible.  I think responsibilities are
1. The code reviewer should make an assessment as to whether the feature will require new documentation (many bug fixes do not).  
2. If documentation is required then the initial developer/designer should develop a documentation plan and coordinate with @Lizabrazil on preparing documentation.
3.  Generally the designer should write the first draft based on functionality in initial design documents
4.  Documentation drafts go in https://drive.google.com/drive/u/0/folders/0B8FGrdqHDtsDRy14Y3JIWW94RkE.   
5.  Once content, including screen shots from a development platform, is complete in Google document, @Lizabrazil responsible for getting into pages.hydroshare.org (documentation staging machine) and (help.hydroshare.org)

I would ask that @Lizabrazil review these steps, elaborate as needed, and then put them in a document in Policies and Procedures, so they do not get lost when this issue is closed.

**Comment by Lizabrazil** [comment]
@dtarb We do not have policies in place for keeping track of documentation in the form of messages and tool tips in HydroShare. I'm not sure if or how we should do this, but eventually we want all of our language to be the same throughout.

**Comment by Lizabrazil** [comment]
@dtarb In this case, which developer would be responsible for providing me documentation on this functionality/error message handling?

**Comment by dtarb** [comment]
@Lizabrazil I brought up the point of documentation in this thread to clarify for @engineSound that it was not simply code review that was required for merging, but that documentation needed to be addressed too.  In general I think that tool tip text and messages should be self explanatory and self standing and not require documentation in help.  For example if we add a tool tip text that explains what a button does, I think it is redundant to add specific help to explain it.  But if there is already a screen shot in help showing this, I think that you need to update the help.

I do not think there can be a rule that works for everything.  I think that each case needs somewhat specific handling.

More generally though, and to your point of who is responsible for providing documentation the sequence should be:
1. Code reviewer determines whether documentation is likely needed.  
2. If in doubt, he/she asks you or the developer.  
3. If you or the developer are in doubt you ask the designer of the functionality.  The designer is the person who wrote the issue or functional specification for what has been coded.  
4. If it is determined that documentation is needed, you make the determination whether you know enough from the issue and functional specification to write the documentation.  
5. For simple changes, I think you will easily be able to write and update documents.  
6. If you determine that you do not know enough to write the documentation you request the designer to write a draft of the documentation.  In these cases a documentation issue should be put on the release checklist for you to check off in the process of checking the release prior to deployment.

In the specific case for the error messages being introduced here we should strive for the error messages to be self sufficient and not require specific documentation.  However, once the functionality is available to test on a staging machine you should experiment with it, because it involves access control and you need to know how access control works to be able to respond to user questions.  If you determine in this testing that changes are needed to access control documentation then you start with step 4 above.

**Comment by zhiyuli** [comment]
fixed already
