### ISSUE TITLE
Add check to make sure new quota holder has enough quota

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#2160]
Add check to make sure new quota holder has enough quota before being changed to a new quota holder for a resource by another owner.

**Comment by hyi** [comment]
@dtarb I remember you mentioned somewhere only owners should see who is the quota holder from the resource landing page. Can you confirm whether this is indeed what we need? Currently, anyone who can view a resource can see who is the quota holder of a resource from the resource landing page. If you want to make a change to make it only visible to the owners, I can get it done as part of this issue. Looping in @alvacouch as well to get his thought as well.

**Comment by dtarb** [comment]
See #2115 where I made the suggestion about owners.  The motivation is that users do not need to and should not see information that they can not act on and is irrelevant to them.  It clutters the interface.  However at this point I would like to be (1) planned, (2) practical and (3) efficient.  If it is inefficient to not show this information for other users then it is OK.  With respect to planned, you have pushed back on the time taken to plan these things.  I worry that it takes more time not to plan these things, because then we end up iterating and undoing code that went in a wrong direction, whereas planning in advance what something should do and getting agreement can result in properly scoping and designing the code.

**Comment by hyi** [comment]
@dtarb I can easily add this additional check to only show this quota holder info to owners without issues. I'll do it as part of this issue rather than creating a separate issue since it just involves addition of a couple of lines in code.

**Comment by dtarb** [comment]
Thanks

**Comment by hyi** [comment]
Merged into develop. Closing.
