### ISSUE TITLE
Request that Discover be enhanced to search private resources

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#2214]
When I search for a resource that's private, it does not appear in the results.  To reproduce this issue:

1. create a new private issue
2. go to the discover page and search the exact title of the resource
3. the resource is not shown in the search results.

**Comment by Castronova** [comment]
@horsburgh Even my own resources?

**Comment by horsburgh** [comment]
Yes. I'm pretty sure that the design decision was that private resources aren't even in the search index. @alvacouch can set us straight if that is not the case.  If you need to "find" a private resource in your list, you should do a search from your My Resources page. The purpose of the "Discover" page is for other people to find your resources - which they shouldn't be able to do if they are private.

**Comment by ChristinaB** [comment]
If I want to find your resource, ( I don't remember if it's private or not), I automatically go to Discover to find it.   When I don't find it, I assume hydroshare is broken.  I don't assume that I should search for your resource under My Resources.

**Comment by Castronova** [comment]
Ok, I understand.  However, this doesn't seem intuitive to me.  If I want to find a resource that was shared with me, I would probably go to the Discover page first.  If this resource is private, it will not be listed.  At this point, is a user really going to look at the "my resources" page to find a private resource that was shared with them?  Maybe we should reconsider this design consideration.

**Comment by horsburgh** [comment]
@ChristinaB - I'm not sure how you would know about the existence of my resource or why you would try to find it via the Discover page if it is private. Such a resource should only show up on your My Resources page (and you would only know about it) if I have specifically shared it with you.

@Castronova - OK, sure. @alvacouch will have to tell us how feasible it is to customize discovery results based on what has been shared with a user (i.e., should private resources be included in search results on the discover page if they have been shared with the user doing the searching).

As an aside - I rarely use the Discover page. I almost exclusively use the My Resources page. So, for at least some users (and maybe there aren't very many like me), this isn't an issue. We have two choices here: 1) keep the simplicity of not listing private resources in the Discover page and explain to people that they should not expect to "discover" private resources because they are private (which I think is the current functionality), or 2) add complexity to the search index and the user interface to customize search results to users. Again - @alvacouch can tell us if any of this exists already.

**Comment by Castronova** [comment]
After a discussion on the HydroShare call, we've decided to make this a longer term goal since it requires non-trivial modification to the Solr search algorithm and indexing.  In the meantime, I created issue #2215 to clarify the purpose of Discover and My Resources searches.

**Comment by ChristinaB** [comment]
Thanks for the stimulating discovery conversation! See you on #2215

**Comment by Castronova** [comment]
Reopening the issue since it hasn't been resolved.  Issue #2215 was created to clarify the functionality of the `My Resources` and `Discover` searches.   Below is a summary of what remains to resolve the current issue:

**Current Functionality**
1. Discover searches all public resources

**Desired Functionality**
1. Discover searches all public resources
2. Discover searches all public and private resources that the current user has access to

**Comment by dtarb** [comment]
I changed the title to reflect fact that this is not "broken" but that it is a feature request.  Given the difficulty @alvacouch indicated implementation would involve I do not think this is high priority.

**Comment by cuahsimarko** [comment]
@Castronova @danames Tony, Dan Ames recently came across this design decision. Can you please work with PIs to get a concensus and close the Issue or refine/confirm the functionality change?

**Comment by danames** [comment]
I'm OK with a decision to keep Discover only for public/discoverable resources since we have "My Resources" tab where people can find their own private resources. In other words, I propose closing this issue and not making this change.
