### ISSUE TITLE
Clarify the purpose of Discover search

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#2215]
The discover search bar is used to find public resources that are owned by others, whereas the My Resources search bar is used to find all private and public resources that you have access to.  

1. The text on the Discover page needs to better reflect this:

![image](https://user-images.githubusercontent.com/4822372/27881709-bbe2c456-6197-11e7-9906-35e8f01087d3.png)

2. Similar text should be added to the My Resources page too:

![image](https://user-images.githubusercontent.com/4822372/27881747-da87eee0-6197-11e7-8942-8e4a0825e89b.png)

**Comment by ChristinaB** [comment]
The main point to clarify is that searching on HydroShare is more nuanced than searching using Google.  We really need to communicate to users when to use Discover, and when to use My Resources and how this is value-added for research collaboration compared to Google (one search box to rule them all).

**Comment by ChristinaB** [comment]
- [ ] Change title tagline from "DISCOVER find content shared by your colleagues and other users"  to "DISCOVER public resources shared with the community"

- [ ] Change 'Show All' button to 'Show All Public and Discoverable Resources'

- [ ] Change search bar default text from 'Search...' to 'Search All Public and Discoverable Resources'

- [ ] Change i information box to 'Search here to find all public and discoverable resources.   This search box supports SOLR Query syntax.

- [ ] Add text to white space or in i information box that says something like "Not finding what you are looking for? Private resources owned by you or shared with you by colleagues are searchable from the My Resources tab".  

- [ ] Add text to white space or in i information box that says something like "Not finding what you are looking for? Public resources not owned are searchable from the Discover tab".

**Comment by Maurier** [comment]
Here is how the above looks like after implementation

Show All button:
note: this text was added as tooltip because otherwise it would occupy too much space.
![ss](https://user-images.githubusercontent.com/2448568/28036090-33e0bc58-6574-11e7-94e2-62881392c55a.png)


Title tagline and information box:
![image](https://user-images.githubusercontent.com/2448568/28035910-8695e528-6573-11e7-91f1-30ff8a94a87a.png)

Search bar default text:
![image](https://user-images.githubusercontent.com/2448568/28035924-8e7ed84e-6573-11e7-9f68-6e7c89fffa61.png)

Help text added to white space below results table in Discover page:
![image](https://user-images.githubusercontent.com/2448568/28035939-9b060236-6573-11e7-8b59-3eb0ca103257.png)

Help text added to white space below results table in My Resources page:
![image](https://user-images.githubusercontent.com/2448568/28035880-6d41e734-6573-11e7-82f7-f2763202003b.png)

TODO:

- [ ] tagline text needed for My Resources, Find Groups and My Groups pages

Let me know your suggestions

**Comment by horsburgh** [comment]
@Maurier - these look good to me.  Do we need tagline text for the pages in your TODO?

**Comment by Maurier** [comment]
@horsburgh, it was suggested by @Castronova in the issue description above. Based on the discussion I'd say we need a tagline text for My Resources, but not necessarily for the other pages.

**Comment by horsburgh** [comment]
@Maurier - How about "Interact with your HydroShare Content"

**Comment by Maurier** [comment]
@horsburgh, I like that one. I'll add it. We can update it later if we decide so.

**Comment by Castronova** [comment]
@Maurier This looks good.  Have you deployed it onto one of the development servers for testing yet?

**Comment by Maurier** [comment]
@Castronova, No. But this can be tested directly from the branch in your local environment.

**Comment by dtarb** [comment]
This was implemented in 1.12
