### ISSUE TITLE
Human in the loop for formal publication

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2229]
I do not think we should be formally publishing resources like this
https://www.hydroshare.org/resource/8bfac173675a4fc9a0a57530d82df70b/
https://www.hydroshare.org/resource/f86234ac40324af291f10aec35c56535/

The abstracts are insufficient and one appears a test resource.  We avoided manual review for requesting DOI's due to the human in the loop scalability burden, but I think we need to revisit this.  I suggest that all DOI requests need vetting by a staff person (I suggest CUAHSI user support person @Lizabrazil or Jon Pollak) just to quickly see that resources are complete in the sense of having basic descriptive material.  If not, formal publication is declined and a message sent to user.  

@horsburgh @hyi @rayi113 @ChristinaB @Castronova

**Comment by Lizabrazil** [comment]
I agree that we need to vet the DOI requests. If we can set up an automatic email with DOI requests, I can take on the responsibility of vetting.

Liza

**Comment by hyi** [comment]
@dtarb @Lizabrazil The main issue with vetting is that we cannot send DOI request to crossref when user clicks publish button to publish a resource, as we do now, but instead, we should email admin like @Lizabrazil to vet the publish request for a resource, and allow admin to trigger the rest of publish action, mainly to send DOI request to crossref for DOI approval and assignment, when vetted, and reset state and notify users when not vetted. This definitely takes some discussion, work, and investigation, and most likely requires system admin to trigger the vet or not-vet actions from Django admin panel. I will start investigation when I have time, but we can use this thread for ideas, thoughts, and discussions regarding this issue.

**Comment by ChristinaB** [comment]
Both of these examples look to me like the DOI was made by mistake. 

Perhaps we add an automatic email into the process where we send them a message like (forgive the shortcuts in language) --
"You have requested a DOI.  
A DOI is forever.  
Is this resource sufficiently reviewed and developed to live forever in the Library of Congress?  
If so, click here and we will send the resource to our review team.  
If not, click here and you can continue developing the resource on HydroShare.  "

**Comment by dtarb** [comment]
Got another DOI submission today that I think should not be issued.  Bumping to High Priority.

**Comment by Lizabrazil** [comment]
We might want to think of this as a short-term solution. As Hydroshare grows, I will not be able to keep with manually checking DOIs. Tony and I propose these longterm solutions: #2274

**Comment by dtarb** [comment]
Here is my outline of the human in the loop solution.
1. We create a resource in HydroShare that holds as a CSV list users who are authorized to approve resources for formal publication.  I have created such a resource at https://www.hydroshare.org/resource/8b0f1122242b41a4a1762be4dfb59b14/.
2. When a resource is submitted for publication (user goes through the full process they do now) an email is sent to all users on this list requesting they review the resource for formal publication.  The email to include a link to the resource.  The resource to be set to a status "Publication pending"
3. For resources for which the status is publication pending the landing page shows two buttons "Publish" and "Deny" only to users on the Authorized to approve publication list.
4. For resources for which the status is publication pending the landing page shows a notification only to resource owner that "This resource is pending formal publication" and provides a button "Withdraw formal publication request" that when clicked sets the status back to public.
5. A reviewer clicking the "Publish" button gives them one "Are you sure" warning then sets in motion the process of getting a DOI from crossref.
6. A reviewer clicking the "Deny" button rejects the resource for publication, setting its status back to "Public" and triggers opening of a mailto reference that opens the reviewers default email client to send mail to the user to explain what is deficient about the resource and why publication is rejected.

Additional considerations
1. The formal "Publish this resource" button should only be enabled for resources that are already public.  This will require users to make them public first and avoid the temptation to click the button for non-public resources.  It will also ensure that the reviewer has access to the resource. 
2. The coder implementing this should investigate whether https://github.com/javrasya/django-river that @pkdash suggested could achieve the spirit of the above functionality efficiently. 

The above is a bare minimum solution that I think could and should be implemented quickly.  I think that it should be possible to recognize within about 1 minute whether a resource is up to standards for publication.  Criteria should be:  
(1) The abstract is complete and self explanatory
(2) The keywords seem relevant
(3) It seems to be a resource worthy of publication, not one generated from one of our tutorials or training exercises as many of the mistakes seem to be.
(4) The subject matter is broadly in the area of Hydrology/geosciences that CUAHSI works with.

Following are additional refinements to consider as volume grows.
1. Rather than send to all reviewers at step 2, rotate through the reviewers on the list sharing the load.
2. If after 24 hours a resource has not been reviewed send a reminder email.
3. If after 48 hours a resource has not been reviewed send an email to the next reviewer on the list.  Keep going to a new reviewer with a new reminder every 24 hr.
4. For "Publication pending" resources that have been pending for more than 24 hours display a message when an owner opens the landing page giving them a list of reviewers from whom they can request approval (with email links).
5. Devise a system whereby users can go through training and upon passing the training be automatically added to the list of users who can approve publication.  This could be online training similar to what we (at USU) have to do for use of purchasing cards, or to be authorized to drive university vehicles.  They could then approve their own resources for publication.

I think that many of these additional refinements are quite a way down the road as our publishing load is quite small right now.  As the publishing burden increases we could consider some of these.

**Comment by dtarb** [comment]
See also #1649 that suggested an embargo/recision period.  That would be a softer solution, but if implementing #2229 is for any reason not possible, we could go back to #1649.

**Comment by hyi** [comment]
@dtarb @aphelionz I can take a stab at implementing this human in the loop for formal publication as outlined by Dave. I took a look at django-river lib suggested by @pkdash and don't think we need that lib to implement this workflow. The outlined steps can be implemented without too much difficulty, but takes some thinking-through on implementation details, e.g., storing and updating authorized publication approval users from the CSV list in the database for quick retrieval in different request sessions, whether to add a new resource status "Publication Pending" to be managed by access control or not, etc. Also, unit tests need to be written for the added functionalities as well. It will take more work than it seems. Also, this presents some hassle for people who really want to publish and got everything right. Now they have to wait for approval process. We have to strike a balance between ease of publication process and minimizing publication errors. I remember in my initial implementation, a resource can only be published after it is made public, as the first additional consideration suggested by @dtarb, then we decided that would be an extra step for users who want to publish directly from a private status for a resource that is ready to be published. In other words, the number of wrongly published resources is still pretty small compared to the correctly published resources, so going through approval process would present some hassle for those people who read publication terms and conditions carefully. I think there are pros and cons to implement these extra approval process and I am not yet completely convinced adding this extra approval process is a good thing.

**Comment by aphelionz** [comment]
@hyi You've got it! 💯

**Comment by horsburgh** [comment]
If we need a human in the loop, do we need the complicated moderation system functionality with extra buttons and permissions described above, or can we just embargo the resource for a period of a week as described in #1649, add functionality that sends notifications to the resource publication reviewers when a resource is published, and then make the reviewers super users who can move a published/embargoed dataset back to public status if it doesn't meet our minimum criteria? 

If the reviewers look at the resource and everything looks OK, they do nothing and the resource gets published with a DOI after the embargo period.

If the reviewers look at the resource and there's something wrong, they use their super-user privilege to move the resource back to public status and they email the resource owner with the reasons for rejection.

A more complicated system would be needed if we are suggesting peer review of content, but I think that's beyond the scope of what we can do right now isn't it?

**Comment by dtarb** [comment]
I would submit that the steps 1 to 6 I outlined above are about as simple as it gets.

Making reviewers super users is essentially the same as putting them on the list I suggest in (1). (1) provides a way to manage the list using infrastructure we already have.  If we make them system administrators, we have to be careful because then they have the ability to do absolutely anything in HydroShare (like delete all resources) and we do not have any admin interface for them to change status so would still be building something like the buttons.  I am totally open to simplifications.  Just work out the complete steps of any alternative.

**Comment by hyi** [comment]
@dtarb @horsburgh @Lizabrazil @aphelionz @Castronova Implementing human in the loop DOI publication would put extra burdens on the reviewers to approve each publication request before the DOI request is sent to crossref for deposition, so if all reviewers were not available, the requested resources would not be published until a reviewer were available to approve the publication. The publication errors/mistakes usually have been made by students who learned of HydroShare in a workshop/lecture/class, and wanted to try it out, but did not pay attention when clicking publication buttons even we added an extra protection dialog to ask them "are you really sure you are sure". When more and more users get over the learning curve, the mistakes would become less and less. At that time, when 99% and above users know to use publication with caution, would this human in the loop implementation presents hurdle to them and to the reviewers? In other words, this human-in-the-loop implementation may have repercussion down the road. If you think regardless we need to go with human-in-the-loop implementation, I can help implement this, but wants to bring this up so this can be given a bit of more thought.

**Comment by dtarb** [comment]
I am OK with just following @horsburgh suggestion and having a week embargo period for a user to withdraw the DOI request, or for an administrator to identify the DOI request as inappropriate and to withdraw it and send the user an email.  If this is simpler than the steps I outlined above I am OK to go with it.  But this does require
-	Some functionality for a user to withdraw the request.
-	Some functionality to identify and manage who the administrators are to identify inappropriate DOI requests and some functionality to notify them.  Perhaps the emailing of DOI notifications to support@hydroshare.org as happens now is sufficient, but as I understand it, this happens at the time the request is sent to crossref, which is too late.
-	Some functionality for the authorized administrators to withdraw DOI requests and get the email address of the requesting user to notify them.  This must not be logging into the site as an administrator, as we may want to delegate this functionality beyond users we want to give full power over logging in as administrator.

I think that if we do all this, it will be pretty close to the steps I outlined above.  It also carries the disadvantage that everyone has to wait the week embargo period to get a DOI.

Whether to do this, or live with the current system and “mistake” DOI’s is a policy decision that I think should be left to CUAHSI.  I think that the issues have been well debated above.  If there is to be more “thought” put into this I would ask that we avoid new opinion comments that really just restate what is already said do not add new information.

We also need to limit/prevent API publication of a resource as at least two of the "mistakes" are due to that.  It does not make sense to have a whole series of confirmations for the manual process that can be circumvented by the API.  (And yes, sorry for repeating information above, but on this issue we seem to have a penchant for debating back and forth instead if implementing).

**Comment by horsburgh** [comment]
@dtarb - the more I think about this, the more I think we need a publication queue. First, I think we should try to minimize changes to the existing resource landing page. If we could avoid doing additional conditional functionality on that page, I think it would be cleaner. And, we need to be serious about publication, so we can't afford for email notifications to get lost or for miscommunication about who is going to handle which email. This happens a lot with emails.

Based on all of this, I want to throw out a suggestion that we develop a new HydroShare page that is accessible only to HydroShare users having a role of "publisher". This page would be a listing of all of the resources that have been submitted for publication - essentially the publication queue. When a resource is submitted for publication, it would get added to the queue. For each resource submitted for publication, it should have a link to the resource landing page (so the publisher can quickly review for completeness), and it should have a "Publish" button and a "Reject" button. If the Publisher clicks the "Publish" button, the resource is immediately published with a DOI. If the resource is rejected, the Publisher should get a pop up that allows them to type a message that will be sent to the resource owner(s) indicating why publication was rejected. A rejected resource would be removed from the queue and set back to its state prior to submission for publication. Since this page would only be available to HydroShare publishers, there would be no need for fancy styling of any kind, so development should be pretty quick. 

We would still need the notifications - to the submitting user letting them know that their resource has been submitted to the queue and is awaiting approval by a publisher and to the publishers letting them know that new resources have been added to the queue and they need to act.

I suggest that the role of "Publisher" be a formal role in HydroShare's access control system. That way, we could designate multiple publishers, and any of them could respond to requests at any time. We wouldn't need a mandatory week embargo period because we would have a more formal review process - and with multiple publishers, the waiting time for review should be pretty short. And - a publisher could log in and respond to any number of publication requests in the queue - all at the same time - rather than doing them one-by-one when emails come in.

I'm not married to this plan, but it just seems cleaner, more modular (because it separates moderation and approvals of requests from the resource landing page), and it might set us up better in the future to have a more formal review process that is beyond someone just looking at the metadata for completeness (if we ever choose to go that direction).

**Comment by hyi** [comment]
@horsburgh agreed your suggested approach seems cleaner and more modular. My thoughts:

- This does not cover the functionality for resource owner to retract resource publication as detailed by @dtarb in his outlined approach. We could add that, but I think that probably would not add much value since based on what happened in the past with mistaken publication instances, the owners who published resources were not aware of the mistakes they made at all, and it was always @dtarb who pointed out the mistakes, so at least for the first pass of implementation, I think we don't have to worry about this.

- Instead of creating a new "Publisher" role in HydroShare's access control system, I think a much simpler approach would be to create either a Publisher group or a Publisher user. For a Publisher group, admin can add users into the group so that they can access the publisher page to approve or reject publications in the queue. For a Publisher user, the publisher page would be only accessible by the publisher user, and whoever is authorized to access the publisher page can become the publisher user by knowing the username and password to be able to log in as the authorized publisher user. The Publisher user implementation would be the simplest. The justification for not creating a new "Publisher" role in access control system is that the current access control module is tied to each resource, kind of what kinds of access control each user has over each resource model, and this publisher page is not tied to an individual resource, but to a publication queue that contains a list of pending resources to be published.

**Comment by horsburgh** [comment]
@hyi - your first point is valid, but with a person reviewing resources before they are formally published, any resources carelessly submitted for publication should be caught. There may still be instances where someone submits something for publication, it gets published, and then later (maybe even much later) they realize an error. This happens with papers and other types of publications. We have a mechanism for "fixing" this - and that is to publish a revised resource that is a new version. At some point, we simply have to say - "Our publication policy is clear. You accepted it when you published your resource. Here are the options you have moving forward."

On the "publisher" role or user - we need more than one user with the "publisher" role. So, if a group in our current access control model works for this and is easier to implement, great. But a single user with "publisher" privileges will not work.

**Comment by dtarb** [comment]
See #1607 for an example of where users made a mistake and wanted to undo it.  This issue got us started in this discussion 8 months ago.  (And I am sorry if my frustration at our inability to address something like this in 8 months is coming through.  It seems we, as a team, need to figure out a more efficient way of deciding what to do and doing it.)

**Comment by ChristinaB** [comment]
Jumping in from the side here since @dtarb brought in #1607 as an example.  

Surely this is not a unique problem. Has anyone looked into the policies and interface processes that all the other DOI providers use?  

Could we disable the DOI publication button until the user has done an online training course? This could be a 5 min video and a form where they click a few buttons that verify they understand the process of getting a DOI from HydroShare.  After that, their button is enabled and they are on their own to publish.  This way, no human is needed in the loop and no annoying 1 week delay would be artificially inserted into the process.

**Comment by ChristinaB** [comment]
My suggestion is an iteration of 
@dtarb  suggestion above 
5. Devise a system whereby users can go through training and upon passing the training be automatically added to the list of users who can approve publication. This could be online training similar to what we (at USU) have to do for use of purchasing cards, or to be authorized to drive university vehicles. They could then approve their own resources for publication.

But I am not suggesting we develop and train reviewers, just train users directly to manage their own DOI process, before they are given access control to do so.

**Comment by horsburgh** [comment]
@dtarb - No automated process or a person in the loop doing a quick review of resources submitted for publication is going to solve #1607. Do you want the person in the loop to call each person who submits a resource for publication and ask them if they read the agreement and if they were sure they were sure when they clicked through the warnings and agreements? 

I suggested a one-week delay before DOI issuing, but then someone said that was too long. Also - this wouldn't have solved #1607, it would have just delayed the user's realization by a week that there was a problem. 

This is a **policy** question before it is a functionality question. Until a policy about publication has been FIRMLY set, we can't fix the functionality. The policy MUST state:

1. What action by a user submits a resource for publication?
2. What metadata MUST be complete for a resource to be published and who is the judge of completeness (e.g., machine or person?)?
3. How long should the review of resources submitted for publication take, and who will do it (e.g., machine or person)?
4. Can a user withdraw a resource submitted for publication, and for how long after it has been submitted?
5. Who reviews submissions (if a person is in the loop) and what actions can they take? And, under what circumstances do they take each action (e.g., publish, reject, etc.)?
6. Can a resource be "unpublished" once a DOI has been issued? If so, by whom? And, what happens to a resource that has been "unpublished" and it's DOI?

I thought we had agreed upon a policy and implementation for these, but it doesn't look like that is the case as we are unwilling to enforce the policy that we have coded. So, can we settle on the policy and then we can fix the publication workflow in the software.

Something that might make it less likely for publication errors would be to add an additional (yes, another) verification in the process. Something like this:

1. User submits resource for publication
2. Resource goes into the publication queue and and the publishers are notified that they need to review it
3. A publisher reviews the submission for completeness and approves it for publication
4. A notification is sent to the user that their submission has been approved for publication, that publication is permanent, and that they must give the final approval
5. The user clicks a link in the email to approve publication
6. The resource is published, receives a DOI, and is made immutable.

The only issue with this process - nobody reads their emails...

**Comment by ChristinaB** [comment]
@horsburgh  - I agree this is a policy issue, and in theory 1-6 could work, however, we don't have a process to support volunteer or paid 'publishers' and whether or not we really want to do that goes beyond HS team policy to  CUAHSI policy, because once in place, they will have to support it.

**Comment by ChristinaB** [comment]
From a user point of view,  I would assume that using HS is more attractive as a streamlined self-publishing tool than imposing extra layers of publication management. We could do that with a self-publishing training process that enables access to formal publishing.

**Comment by hyi** [comment]
The idea from @ChristinaB sounds more attractive to me than a human-in-the-loop approval process we are proposing to implement since the publication mistakes come from users' ignorance on what resource publication really meant in HydroShare. We could probably embed a self-publishing short training process that has to be clicked through and acknowledged before Publish button is enabled. I am sure this will reduce users' publication mistakes, however, I am not sure whether this will completely remove the mistakes since we currently do require user to check a checkbox that they have read the publication agreement and agree with the agreement before publish button is enabled, and we then have another pop up to restate the seriousness of resource publication with a DOI, and ask users to confirm before we really start the publication process. I think if the self-publishing training process is clear and to the point, the users should get it and they should treat that publish button seriously.

**Comment by dtarb** [comment]
Closing as this is superceded by manual review process outlined in #2298 and CUAHSI policy decisions for a manual review process.
