### ISSUE TITLE
BagIt creation failure

### ISSUE THREAD

**Issue by yirugi** [hydroshare/hydroshare#2253]
We just found that one of our resource had an error for creating BagIt file.
When we click the "Download all content as Zipped bagIt Archive" button, the BagIt file should be created, then download starts, but it just wait and nothing happened.

Other resources are fine. Just this has the problem.

Here is the link for the resource:
https://www.hydroshare.org/resource/c65bce3e4459476f9950c6510728695e/

And here is the screenshot.

![2017-07-25 3 35 59](https://user-images.githubusercontent.com/5661304/28590120-ff47c748-714e-11e7-824f-9c6f44becf69.png)

**Comment by dtarb** [comment]
Just tested and this is still a problem.  @alvacouch @hyi any suggestions as to how to fix.  On www bag generation gives a long line of ......  On beta the bag downloads in a few seconds.

**Comment by cuahsimarko** [comment]
@Maurier @pkdash do recent updates to the UI handle this now?

**Comment by dtarb** [comment]
I just tested.  Behavior is exactly the same as Jan 8 report above.  Beta gives a bag download in a few seconds, but www gives a long line of .... that never ends.  These sort of problems make me worry about resource integrity and make me think that we perhaps need some of the debug scripts we used to have from @alvacouch .  It also makes me think of the script we used to have from @Castronova to test downloads of all resources to detect these sort of problems.  Tony's script was set aside because it was time consuming and a more efficient check resources script was written.  But we still evidently have problems with some resources, and we do not, at least in the case of this one, know why, and this worries me.  I am going to bump this up to high priority, because something like this that raises concerns about resource integrity, without an explanation, should get high priority intention.

**Comment by cuahsimarko** [comment]
I just tried and can download the bag for this problematic resource in the issue successfully. Perhaps the cleanup I did fixed this bag download issue. You can close this issue now that the bag can be downloaded successfully for this resource.
 
Thanks,
Hong
