### ISSUE TITLE
Bounding Box Filter Not Working in REST API

### ISSUE THREAD

**Issue by rajadain** [hydroshare/hydroshare#2257]
Looking at the current implementation of the bounding box filter here: https://github.com/hydroshare/hydroshare/blob/c861f97af96dbdbe4d9e61c27fd1c48175e2d9aa/hs_core/hydroshare/users.py#L316-L344, it seems like we need to specify a `coverage_type` value of either `box` or `point` before the bounding box parameters of `north`, `east`, `west`, and `south` are taken into account. Running a query without specifying `coverage_type` but only the bounding box params results in no filtering, for example see:

 * [hydroshare-philadelphia-20170728.json.txt](https://github.com/hydroshare/hydroshare/files/1184197/hydroshare-philadelphia-20170728.json.txt)
 * [hydroshare-seattle-20170728.json.txt](https://github.com/hydroshare/hydroshare/files/1184196/hydroshare-seattle-20170728.json.txt)

Both are queries for a 1 sq km box in Philadelphia, PA and Seattle, WA and have identical results.

However, if a `coverage_type` is specified, the server crashes and returns an `500 INTERNAL SERVER ERROR`:

```http
$ http --print Hh https://www.hydroshare.org/hsapi/resource/ full_text_search==water north==47.599816005559326 west==-122.32020458774991 east==-122.30687060756253 south==47.608806399331975 coverage_type==box

GET /hsapi/resource/?full_text_search=water&north=47.599816005559326&west=-122.32020458774991&east=-122.30687060756253&south=47.608806399331975&coverage_type=box HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: www.hydroshare.org
User-Agent: HTTPie/0.9.9

HTTP/1.1 500 INTERNAL SERVER ERROR
Connection: keep-alive
Content-Language: en
Content-Type: text/html; charset=utf-8
Date: Fri, 28 Jul 2017 20:40:32 GMT
Server: nginx/1.11.10
Set-Cookie: csrftoken=pCK7rkhd7eQc9iB8RoBuVbSnhu4rumui; expires=Fri, 27-Jul-2018 20:40:32 GMT; Max-Age=31449600; Path=/
Transfer-Encoding: chunked
Vary: Cookie, Accept-Language
```

Also try this URL: https://www.hydroshare.org/hsapi/resource/?full_text_search=water&north=47.599816005559326&west=-122.32020458774991&east=-122.30687060756253&south=47.608806399331975&coverage_type=box

**Comment by aphelionz** [comment]
@rajadain @aufdenkampe

This error was due to some of the resources on production having malformed coverage metadata. For example "north" might have been set to 5555, which is neither below 90 or above -90. I added some error trapping so that the system simply passes over those and does not add them to the search results to unblock you, with the intent of writing a cleanup maintenance task at a later date. 

We are looking at releasing this in 1.12, but in the meantime you can test here, with a copy of the production resources: https://playground.hydroshare.org/hsapi/resource/?full_text_search=water&north=47.599816005559326&west=-122.32020458774991&east=-122.30687060756253&south=47.608806399331975&coverage_type=box

**Comment by rajadain** [comment]
That's working well. Thanks for looking in to this!
