### ISSUE TITLE
[DOI Registration] "Publish This Resource" Button Updates

### ISSUE THREAD

**Issue by aphelionz** [hydroshare/hydroshare#2291]
- [x] The formal "Publish this resource" button should only be enabled for resources that are already public. This will require users to make them public first and avoid the temptation to click the button for non-public resources. It will also eliminate some of the confusion between public and formally published.
- [x] The formal “Publish a resource” button should be greyed out for users with incomplete profile metadata and a hover over message that indicates that they need to complete their profile before they can formally publish using HydroShare

**Comment by Maurier** [comment]
How about "Your profile information must be complete before you can formally publish resources." for the hover message?

**Comment by aphelionz** [comment]
Looks good to me. @dtarb ?

**Comment by aphelionz** [comment]
@Maurier Further more, while the button is in the disabled/hover message state, can you either add a link to the profile edit page or make the publish button link to the profile edit page?

**Comment by dtarb** [comment]
The hover over message looks good.  I think that a link to the profile page would be good.  Is it possible to have a link in a hover over message.  I think it would be odd to click on the publish button and be linked to the profile page.  A button should do what it should do.  Unless clicking on the button took a user to the profile page also with a message that said that to publish a resource your profile needs to be complete.

**Comment by Maurier** [comment]
> Is it possible to have a link in a hover over message.

Yes, but the tooltip would behave like a popover (Triggers on click rather than on hover). Similar to what we have in the Discover page.
![image](https://user-images.githubusercontent.com/2448568/32130820-97b7e326-bb5c-11e7-9d8f-fce931b69a6a.png)


> While the button is in the disabled/hover message state, can you either add a link to the profile edit page or make the publish button link to the profile edit page?

Yes, but we would need to make the tooltip behave as a popover. It would look the same but behave a little different. Popovers are triggered and dismissed by click events.

Notice that we already have a message with links that shows up on page load prompting incomplete profiles to fill out the information.

**Comment by aphelionz** [comment]
@dtarb @horsburgh @Maurier We should be able to close this after 1.14 goes out
