### ISSUE TITLE
[DOI Registration] User-side Updates and Appeals via Email 

### ISSUE THREAD

**Issue by aphelionz** [hydroshare/hydroshare#2295]
- [ ] Implement functionality for the owner of a resource that has been submitted for formal publication to remove the resource from the publication queue.  I suggest a button on the landing page visible only to owners, when a resource is on the pending list. This button will only be available when the resource is pending publication. Once a resource has been approved for publication by a CUAHSI reviewer, this button would no longer appear.
- [ ] Resources in the publication pending queue are not editable (this is currently the case and should be preserved).  The only things that can be done to them are that a reviewer can approve or decline publication, or an owner can withdraw it from publication (enabling further work and possible resubmittal).
- [ ] Resources denied formal publication by a CUAHSI-approved reviewer may be appealed via email to ??????

**Comment by aphelionz** [comment]
@dtarb @Lizabrazil  I need the text for these emails as well, or for the UI notifications

1. The UI notification on the resource landing page
2. The Email sent to the user when their resource enters the queue
3. The "your appeal has been received" email and the appeal email sent to admins

Alternatively, we can point them to the support@cuahsi.org flow

**Comment by dtarb** [comment]
1. For UI notification on the resource landing page I suggest "Your resource has been submitted for publication.  It will be checked for completeness by a CUAHSI staff member and once they approve it, it will receive a digital object identifier (DOI)."
2.  It is unclear what you are asking here.  What does "enters the queue" mean.  I think that the next step after a resource being submitted for publication is that the CUAHSI staff person either approves it or declines it.  If the CUAHSI staff person approves it an email should go to the user that reads.  "Congratulations! Your resource <insert DOI> that you submitted for publication in HydroShare has been published."  I think that this email should only go out after the DOI has been registered, so that whey they click on the link it works.
3. If a resource is denied, the CUAHSI staff person should write a short explanation why.  This should say what is missing.  I do not think a general email can be crafted, because it will vary on a case by case basis.  It would be simple if the system for approving/denying publication included a text box for the staff person to write this message.  The from address in the email sent to the user should be one to which they can reply if they disagree and want to appeal.  Then any discussion continues from there.

support@cuahsi.org does not currently exist on the CUAHSI email server.  I believe that CUAHSI support uses help@cuahsi.org.

**Comment by engineSound** [comment]
When a resource enters the satte of under-review, will it still discoverable?

**Comment by dtarb** [comment]
@engineSound Yes, because it is already public.

**Comment by cuahsimarko** [comment]
This has been indexed alongside 25 related GH Issues, and relevant information extracted into a growing design document, and reorganized beneath major topics. Areas for meeting/presentation/async viewing by stakeholders, meetings and discussion/action items are also designated.
