### ISSUE TITLE
Composite Resource not autopopulating shapefile metadata

### ISSUE THREAD

**Issue by Lizabrazil** [hydroshare/hydroshare#2325]
I just worked with a CZO data manager that was attempted to use the composite resource. He uploaded a few different files, one of them being a shapefile . I thought that shapefiles were supposed to autopopulate the spatial coverage? If so, it is not working. 
Also,  the HydroShare GIS app should be able to open a composite resource that contains a shapefile....was this ever worked on? 
We should really try to provide the CZO Data Manager with a solution, as he is potential user that is still testing out the utility of the system.

**Comment by dtarb** [comment]
With composite resources you have to tell it that the files are a geographic feature.  The procedure is
1. load zip file with all parts of shapefile into composite resource
2. switch to edit mode
3. right click and set geographic feature type

The 3rd step above will harvest and autopopulate the metadata.

This is so far "by design" because when a zip file is uploaded into a composite resource it is unknown whether it contains the pieces of a shapefile, the pieces of a geographic raster, the pieces of something else, or a group of files the user wants to just keep in a zip file.

Also at this stage HydroShare GIS is disfunctional.  There are 4 high priority issues waiting for the HydroShare GIS team to address #2320, #2185, #2270, #2144 that @danames is aware of.

**Comment by dtarb** [comment]
@Lizabrazil does the explanation above suffice.  I believe that this issue is one of user education and fixing bugs in HydroShare GIS.  HydroShare GIS has these bugs itemized separately so fixes do not need to be tracked here.  If this explanation is OK, then could you adjust documentation to clarify use of composite resources and close this issue.  I am removing the bug label and labeling documentation.

**Comment by dtarb** [comment]
Are all the files zipped together?  Are one of the files in the zip file not supposed to be there?  Can you let me see that resource.  I would try take the message literally "one of more files are not of shape file type", so look for an extra or a missing file in the zip file.

**Comment by Lizabrazil** [comment]
Hi Dave, I'll make a copy of the resource and share it with you. It is to remain private, as the publisher has requested. Thanks.

**Comment by Lizabrazil** [comment]
@dtarb it should be in your resources now as Cross-CZO Soil Chemistry Dataset

**Comment by dtarb** [comment]
@Lizabrazil a proper shapefile has to have at least 3 files *.shp, *.dbf, *.shx.  See the documentation for shapefiles at http://doc.arcgis.com/en/arcgis-online/reference/shapefiles.htm which is linked in https://help.hydroshare.org/hydroshare-resource-types/geographic-feature/.  Just one *.shp file will not work, not even for ArcGIS.    For HydroShare it is required for composite resources to zip together all the parts of a shapefile in one zip file.  For a geographic feature resource, you can load the unzipped files together, but still have to have a sufficient number of them.

**Comment by Lizabrazil** [comment]
Makes sense. Once I figure out how to get credentials for the new mezzanine instance, I'll add to the page. Thanks
