### ISSUE TITLE
Can't set coverage for composite resource

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2351]
Maybe I'm just not understanding how this works, but when I try to set the spatial or temporal coverage for a composite resource it is just greyed out when I am in edit mode. Is this by design?

I have a resource: https://www.hydroshare.org/resource/be41963c348d401f94252fd25af00b45/

It consists of a bunch of data files that are not specifically typed - e.g., CSV files, readme files, etc.

This dataset does apply to a specific geographic area, but none of the datasets in the resource contain that geographic area. I want to set it using the map control.

**Comment by dtarb** [comment]
See #2330.  This behavior is sort of by design.  Coverage, both spatial and temporal for a composite resource is derived as the superset from the member files.  So to change coverage you need to click on a file (even a generic one) and edit the file specific metadata.  Then when you save changes the information propagates up to the resource level metadata.  The issue #2330 is to add the map control to the file spatial metadata editing functionality.

**Comment by horsburgh** [comment]
I'm not sure this is my desired behavior. Why shouldn't I be able to set the coverage for the resource as a whole, independent of any of the files? It seems like metadata automatically extracted from files might pre-populate the coverage information for a composite resource, but shouldn't I be able to override it by setting it myself if I want to?

It certainly isn't intuitive from the user interface what one should do to set the coverage for a composite resource.

**Comment by pkdash** [comment]
If that is the case I guess the same argument can be made for time series resource where we don't allow the user to update the resource level coverage.  Currently the resource level coverage is auto populated from site(s) level coverage data.

**Comment by dtarb** [comment]
@horsburgh we debated some of these issues in the design.  We considered allowing the resource level coverage to be edited to be bigger than file level coverage, but not smaller, because that did not make sense.  We found complexities related to what to do with an edited coverage when a file is later added or a file that had coverage removed, and decided in the end that it was simplest that coverage be something that is held as a property of files, with the resource level coverage purely derived from the member files.  You can still edit member file coverage to be anything you want to have that propagate consistently up to the resource level.

With all that said, you are in charge of the data model design in HydroShare now so if you want to work through a redesign that is better you are empowered to do so.

**Comment by horsburgh** [comment]
@dtarb - where do I find the latest documentation of the file type design? You and Pabitra (and perhaps others) have done a lot of work since the original resource data model design, and obviously I'm not up to speed on all of it. And when you say "we debated" do you you mean you and Pabitra? Sorry - I'm going to have to get my head around what's been done with file types so we can move forward.

@pkdash - are there separate coverage elements in the metadata for the resource as a whole and for each of the files? So, the implementation is that a resource can't have a coverage unless a file within it has a coverage? And then, the resource level coverage is a superset of the file level coverages?

**Comment by dtarb** [comment]
It may be more efficient just to meet to discuss, rather than go back through the documents, as they have not kept up with implementation.  The documents are in https://drive.google.com/drive/u/1/folders/0B0l1a655y5oTNTFZSFhxQ1ZNMVE and #965, #1034, #1126 

And yes the implementation is that the resource as a whole cannot have a coverage unless a file within it has a coverage and the resource level coverage is the superset of file level coverages.

**Comment by horsburgh** [comment]
@dtarb - I just created #2366 as a new issue with a description of how to handle this. I tried adding coverage information to an individual file within my resource so it would propagate to the resource-level metadata. When I tried this, I was unable to do so and got an error saying that there was no associated logical file. So, it looks like you can't add coverage information to any file, it has to be a "logical file." This is too deep and convoluted for users to get (even I'm struggling), and I think needs to be simplified - hence #2366. Also - I think there are some cases where a user might want the coverage for a resource to be something different than the superset of the coverage for individual "logical files" within a resource AND there will be times when there are no logical files within a resource with coverage information (but the user may still want resource-level coverage information).

I'm closing this issue in favor of #2366.
