### ISSUE TITLE
My Resources Page: Performance Enhancements Needed

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2368]
Currently it takes several seconds for the My Resources page to load. This is tedious for frequent users of HydroShare who are switching between the My Resources page and the landing pages for individual resources. It's gotten to the point that it is affecting the usability of the system. I suggest that it's time to take a critical look at the My Resources page to see if we can speed up the initial page load. The following are potential options @Maurier and I have discussed, although not in depth:

1. Add a paginator to the table of resources on the My Resources page
2. Create a different or modify the existing API call that is returning information for this page. Right now it returns way more information than is really needed to populate the table on the page.
3. Save the state of the filters in the browser's local storage to allow users to use their own defaults for the filter states.

Other strategies for speeding up this page may be needed. An additional performance consideration is the "Favoriting" functionality that is very slow if a large number of resources are selected for favoriting at the same time.

**Comment by Maurier** [comment]
@pkdash see https://github.com/hydroshare/hydroshare/blob/develop/hs_core/views/__init__.py#L1057
A good start would be to replace this method with a more specific one designed for the My Resources page. Ideally it would pass only the information needed. The one used right now passes way too much information to the view making it very slow.

**Comment by Maurier** [comment]
Here is the network analysis to load the page:
![image](https://user-images.githubusercontent.com/2448568/32747895-930ec966-c877-11e7-8559-35cc8f87fc1c.png)
Notice how must of the time spent is on the time to first byte. This is an indication that processing the data before transfer is taking too long.

**Comment by cuahsimarko** [comment]
![callgraph](https://user-images.githubusercontent.com/45397838/53127464-80f8c480-3530-11e9-9609-fc4b206935b7.png)

**Comment by cuahsimarko** [comment]
I am blocked from profiling the /my-resources/ View-Template, due to Mezzanine-managed URLs for that endpoint. I will now go learn Mezzanine and its interactions with Django, so I can complete the Profiling. I am able to properly gather information about /collaborate/ and other Django native URLs in hydroshare/urls.py

This is the start of the trail I'm tracing: https://github.com/hydroshare/hydroshare/blob/76d3697828954ab4028dc6aaafd871282c115a4f/hydroshare/urls.py#L176

**Comment by cuahsimarko** [comment]
@sblack-usu I git blamed you on this. Can you explain this comment? https://github.com/hydroshare/hydroshare/blob/76d3697828954ab4028dc6aaafd871282c115a4f/hydroshare/settings.py#L157

**Comment by cuahsimarko** [comment]
Can Mezzanine be completely removed from HydroShare or is this just a small aspect?

**Comment by sblack-usu** [comment]
the TODO should've been removed.  There was a period of time we were using two authentication backends (the mezzanine one that was removed and the caseinsensitive one).  We're only using the case insensitive one now.

**Comment by sblack-usu** [comment]
> 
> 
> Can Mezzanine be completely removed from HydroShare or is this just a small aspect?
It's just the authentication backend.

**Comment by cuahsimarko** [comment]
With more common use-case listings of 40 resources, load time is closer to 6 seconds. Unpinning issue, but leaving priority at medium to cover edge-case users with hundreds of items.

**Comment by cuahsimarko** [comment]
@Maurier do you want to remove yourself as assignee as this is likely a backend issue?

**Comment by horsburgh** [comment]
With recent enhancements, performance of the My Resources page is now workable for me. 

However, it still takes over 10 seconds to load the page for me. I own 27 resources, but 241 are shared with me, so I guess I may have more resources in the system than many users would. However, even at the 6-second load time reported above, I think for frequent users of the system, this might be tedious. There may be larger fish to fry at the moment, and to get the load time down, a different approach may be needed for getting the information needed to render this page. I would be OK with demoting this high priority issue to lower priority (but still important).

**Comment by Lizabrazil** [comment]
I just tested and found it still to be extremely slow (16 seconds timed), however I have something like 300 resources, 169 shared with me. The common user will not encounter this problem.

**Comment by cuahsimarko** [comment]
Related or duplicated
https://github.com/hydroshare/hydroshare/issues/2405

**Comment by Castronova** [comment]
I just tested this in my account and it takes 12.71 seconds to load "My Resources". Below are some details about the content that was loaded:

Owned resources: 151
Shared with me: 209
Added by me: 5
Favorites: 15

**Comment by cuahsimarko** [comment]
Limitations here are shared by the Communities resources page, which are being fixed with ongoing Communities/Indexing work. At a future date, the option for My Resources to reuse patterns in Communities work will be a solid option.

**Comment by eclark-cuahsi** [comment]
Options should be investigated for how to resolve this, per issue review meeting on 4/28.

**Comment by devincowan** [comment]
Related to @pkdash work on #4091

**Comment by horsburgh** [comment]
@devincowan - I don't think making the search work only on the 40 resources on the current page makes sense. So, I wouldn't vote for that. 

The Search box on the My resources page should search within the set of resources that appear on the My Resources page (if paginated, search should work within all of the pages). If there are filters set, then the search should work within the filtered resources. In other words, it would be great to speed up the functionality we have now. 

Yes, I like having cake and eating it!

**Comment by devincowan** [comment]
Discussed today on Dev call, some other options for My Resources page.

1. Current draft https://github.com/hydroshare/hydroshare/pull/4713 uses DataTables.js existing My Resources implementation and improves performance by returning resources by filter.
2. @martinseul suggested modifying My Resources to use same tooling as Discover. Right now, Discover is a Vue app that uses axios to get from `/discoverapi`. That python view uses haystack/Solr. Looking at the endpoint, it seems to have what we would need for the My Resources page, except:
    - [Discovered Resources](https://github.com/hydroshare/hydroshare/blob/1.57.1/hs_core/views/utils.py#L592)
    - [Favorite Resources](https://github.com/hydroshare/hydroshare/blob/1.57.1/hs_core/views/utils.py#L602)
    - [Other Labels](https://github.com/hydroshare/hydroshare/blob/1.57.1/hs_core/views/utils.py#L601)

#1 is almost ready to go.
#2 I would imagine will further improve performance during searching/load. But would entail a full revamp of the My Resources front and back end. @Maurier might have an opinion about how difficult that would be. Might be as simple as porting most of [Search.vue](https://github.com/hydroshare/hydroshare/blob/1.57.1/hs_discover/src/components/Search.vue) over and adding the above 3 items to `/discoverapi` or getting them from another endpoint. But if we want the frontend to be styled like it has up to this point, that will take some work. And this would essentially require nesting [another npm project](https://github.com/hydroshare/hydroshare/blob/1.57.1/hs_discover/package.json) within hs_core. That has implications for our entire build/deploy process and I think we would have to figure out things like staticfiles etc. What do you think Mauriel? I'm inclined to keep the progress that @pkdash made on My Resources queries and the work that I've done on the filters rather than moving to Vue+haystack but open to opinions

**Comment by pkdash** [comment]
I agree with @devincowan's evaluation. Unless we index  all resources including those that are private, I am not sure how we could make my resources page load like discover page.

**Comment by devincowan** [comment]
Many thanks to Pabitra for helping me with some of these queries!
I have a PR ready https://github.com/hydroshare/hydroshare/pull/4717 and plan to stage it somewhere with enough data that it can be adequately tested. I think users who have lots of resources shared with them, will be mighty happy with the load time!

**Comment by devincowan** [comment]
@pkdash has helped extensively reviewing my PR and deploying to dev-2.
@horsburgh and @Castronova please feel free to test at [https://cuahsi-dev-2.hydroshare.org/my-resources](https://cuahsi-dev-2.hydroshare.org/my-resources/) and let us know what you think! In particular, be sure to try different filter combinations and note filter is now stored in the URL so you can bookmark a desired configuration

**Comment by devincowan** [comment]
@horsburgh @Castronova sounds like we might have to deploy another PR for some other testing this afternoon. So you can delay your My Resources testing until tomorrow thanks

**Comment by devincowan** [comment]
@horsburgh and @Castronova not sure if you had a chance to test the [updated My Resources Page](https://cuahsi-dev-2.hydroshare.org/my-resources/). @pkdash will need to use the dev-2 machine for another deploy tomorrow afternoon, so that is the deadline for testing ;)

**Comment by Castronova** [comment]
@devincowan I just tested and below are my results:

|url|page|load time|
|---|---|---|
| cuahsi-dev-2.hydroshare.org|my-resources|~2 sec|sec|
|hydroshare.org|my-resources|~9 sec|

Enabling and disabling the filters for the first time appears to be slower than `www` but this is probably because these data need to be queried. 

This is great work and a real improvement to the `my-resources` page.

**Comment by pkdash** [comment]
@Castronova Just curious how many resources you see on initial page load? I think 99% of users will see my-resources page load in < 2 sec.

**Comment by Castronova** [comment]
I probably have more content on my `my-resources` page than most users:

![image](https://user-images.githubusercontent.com/4822372/185502836-b8113a09-677e-414a-b32f-2d92bbfb8c77.png)

**Comment by devincowan** [comment]
thanks for taking a look @Castronova

**Comment by horsburgh** [comment]
Thanks guys - I got to this too late to make a difference testing, but it looks like you have it covered. I will look forward to the My Resources page being faster!!!!!
