### ISSUE TITLE
Unit Testing takes 3 hours

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#2421]
I dont think it is normal... I ran the test cases on my locally VM using command 
docker-compose run hydroshare ./run-pylint 
It hasn't finished after 2 hours...but no error so far

![image](https://user-images.githubusercontent.com/10070599/32679209-ca6812a2-c622-11e7-8424-d8ca1777bf2d.png)

**Comment by cuahsimarko** [comment]
Tests take 3 hours to run. Consider updating the title on this issue to "Tests take 3 hours to run". Task is to identify which tests are the long-running tests (there are python packages that make this easy to do), find which ones are easiest to refactor and pull into pytest or otherwise better way of code re-use and any other necessary refactoring.

**Comment by cuahsimarko** [comment]
Note that tests now show run times per test. It seems to be pointing to an iRODS or storage class issue.

**Comment by martinseul** [comment]
closing as it does  ot apply anymore
