### ISSUE TITLE
Discovery page: "show all" button label is misleading

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#2430]
The "show all" actually just recomputes the facets according to the current search term. It should probably be labeled "update facets". 

There has been a bit of discussion about how facets should actually work. Currently they are updated only when one enters a new search term in the text box. This was to avoid confusion when facets change a lot. However, now it seems that even that is undesirable. 

There is some thought that: 

1. Facets should only change when explicitly requested.
2. When changing facets, the result should incorporate information from other facet choices.
3. Selected facets should stay selected when facets are recomputed (unless they become invisible due to zero matches).

**Comment by dtarb** [comment]
To clarify current behavior (based on testing on www 11/14/17) the resources listed on the Discover page list view are updated according to the selected facets as soon as a facet is checked or unchecked in the facet list.  "Show All" does not appear to do anything or have any effect, because the resources listed are already filtered according to the facets. Thus the problem is only in part the label.  The problem is also that right now "Show all" has no effect.

With respect to the suggestions
1. _Facets should only change when explicitly requested._  I am not sure what "explicitly requested" means in this comment.  Is checking a facet equivalent to explicitly requesting. The current behavior that changes the list of resources listed as soon as a facet is checked or unchecked seems good. 
2.  _When changing facets, the result should incorporate information from other facet choices._  This is already the case (unless you are saying something else).  The moment a facet is checked, the listed resources update to show resources that are filtered by the facet checked and other facets already checked.  This behavior I also think is good.
3. _Selected facets should stay selected when facets are recomputed_.  I do not know what you mean by "facets are recomputed". Do you mean recomputing of the listed resources.  I think that having facet selections persist (as they do) while one changes other facets is good.

Perhaps what this issue is getting at is that
"Show all" could be renamed "Clear selections" and have the effect of unchecking all selected facets and updating the resources listed.

**Comment by alvacouch** [comment]
The natural behavior of SOLR is to update the facets themselves when a facet is checked. Checking one facet often means that others have no matches and disappear. Numbers of matches are updated. This behavior has largely been disabled in our system.
