### ISSUE TITLE
"add to my resource" button doesn't work for Discoverable resources 

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#2435]
Not sure it is expected or a bug. The "add to my resource" button doesn't work for Discoverable resources. 
An example:
https://www.hydroshare.org/resource/d7139a2a819048e1a10ec5bddc33ac90/

**Comment by Maurier** [comment]
I can confirm it doesn't work for Discoverable resources. The ajax call is sending the correct information, but error 500 is returned.

**Comment by zhiyuli** [comment]
@Maurier @pkdash @dtarb 

I am reviewing hs_lablel code and trying to reuse it for WebApp's OpenWith functionality.

I can see the backend code requires users to have View_RESOURCE permission when doing "add to my resources". But users only have View_Metadata permission over Discoverable resources, which causes the failure we saw.

So this is a policy question for @dtarb, do we allow "add to my resources" button to work for Discoverable resources?

**Comment by dtarb** [comment]
This is a policy nuance that I do not think has arisen.  I think that Discoverable (and Public) resources should be able to have Add to my resources activated.  However it is quite a small subtle consideration of little consequence, so I would not object to leaving as is (Discoverable resource can not be added to My resources).

That said, the interface for whatever is done, should be clear, and if clicking on a button does nothing and there is no message, then it is not clear.  If it is easier to fix the interface than enable a Discoverable resource to have Add to my resources activated, then I am OK if the fix is just to the interface.

**Comment by Maurier** [comment]
I can fix this in the interface easily.

**Comment by Maurier** [comment]
If I'm not mistaken, Public resources are flagged as Discoverable internally, but not vice versa. Solving this would be equivalent to only displaying the button for Public resources.

**Comment by aphelionz** [comment]
@dtarb @Maurier We can close this after 1.14 goes out

**Comment by dtarb** [comment]
Tested on beta CR.  Closing.
