### ISSUE TITLE
NWM Forecaster Viewer Suggestions

### ISSUE THREAD

**Issue by rphooper** [hydroshare/hydroshare#2437]
In my use of this app, the greatest difficulty is getting sufficient information to locate the reaches of interest because the base map is not terribly informative and is inconsistent with the base maps used in HydroClient. My suggestions are

- [ ] Change basemap to be consistent with HydroClient (replace bing map with google map)
- [ ] Add river name to COMID (including "unnamed tributary to river x")
- [ ] Add point coverage of USGS gages for which unit value and indicate which of those gages are used by NWM for assimilation (where NWM predictions are the same as the USGS gage data)
- [ ] Add polygons for those reservoirs that are modeled in NWM
- [ ] In addition to uploading a polygon (which I think I had trouble with) to add a click-and-drag and CTRL-click to select multiple reaches
- [ ] Add a csv export option for data
- [ ] Add a subscription service so that users can subscribe to a set of reaches of interest and get on-going forecasts or assimilation runs through a push or pull service so users can develop a local repository of data

**Comment by rphooper** [comment]
It would be helpful if COMID could include the river name and/or if basemap included river names. I don't think Google base map is particularly good with river names, but most of those maps aren't. It is a problem.

**Comment by zhiyuli** [comment]
@rphooper @danames @dtarb @martinseul 

I made some comments on @rphooper 's suggestions 

**Change basemap to be consistent with HydroClient (replace bing map with google map)**
We have some technical difficulties in doing this. The NWM View App uses OpenLayer3 (a javascript lib) to build web mapping interface. It does not support Google Map as Google sets some restrictions on purpose to promote its own GoogleMap API lib. 
There is an open source project on Github called "ol3-google-maps" (https://github.com/mapgears/ol3-google-maps), which tries to combine OpenLayer3 API and GoogleMap API. It is in very early stage (ver. 0.14) and buggy. I played with it yesterday. Indeed, it is able to provide a google map basemap for openlayer3 app, but it caused performance issue as well as other weird issues in our app.

 **Add river name to COMID (including "unnamed tributary to river x")**
Do you want river name to be shown on the popup after user clicks a river, or to be shown on map as annotations/labels? 
Technically either can be done. However we have a data source issue here. Currently the NWM Viewer app uses a NHDplus stream database NWC gave us in 2016. This version has 2,699,225 reaches with only "comid" on attribute table, no river name or other attributes. 
I downloaded the original NHD data from EPA website @ https://www.epa.gov/waterdata/nhdplus-national-data (I went to USGS first but it redirected me to EPA for downloading). It is a 7GB compressed file "NHDPlusV21_NationalData_CONUS_Seamless_Geodatabase_05.7z". It does have river name on attribute table, but it only has 2,691,339 reaches.
This inconsistency in data might be related to some pre-processing NWC performed on original NHD data as I heard NWC corrected some geometric errors. Do you have a contact to confirm this?
Anyway, we dont have a NWC version NHD data with river name attributes.

 **Add point coverage of USGS gages for which unit value and indicate which of those gages are used by NWM for assimilation (where NWM predictions are the same as the USGS gage data)**
The NWM outputs contains a usgs_timeslices data which is not being used in our app. I checked that data yesterday, it contains 15-min discharge time series for 3,862 gauges. It only has gauge id without locations (lat/lon). So I went to EPA website (redirected from USGS) and downloaded gauge location database -- "NHDPlusV21_NationalData_GageLoc_05.7z", which has records for 28,164 gauges. I tried to match it with the 3,862 gauges NWM uses. Surprisingly, only 3,417 gauges can be matched. That means there are 445 gauges NWM uses are not in USGS database...So this is another data inconsistency issue.

 **Add polygons for those reservoirs that are modeled in NWM**
NWM outputs contain data for 1,260 reservoirs. I was able to match them with the NHDWaterbody database. So technically this can be done. 

 **In addition to uploading a polygon (which I think I had trouble with) to add a click-and-drag and CTRL-click to select multiple reaches**
Technically doable. But it may takes time as this needs some major revisions on existing code logic.

 **Add a csv export option for data**
Subsetting feature returns netcdf files. Conversion netcdf to csv is task the CAUHSI Time Series Viewer is working on.

 **Add a subscription service so that users can subscribe to a set of reaches of interest and get on-going forecasts or assimilation runs through a push or pull service so users can develop a local repository of data**
We have implemented a “latest” parameter in our rest api. By using it, users don’t need to provide a specific date range. Instead the app will detect what the latest data is and perform subsetting. This is kind of “subscription” but definitely needs to be refined.

**Comment by zhiyuli** [comment]
@rphooper @danames @dtarb @martinseul 
I just found the usgs_timeslices data contains discharge observations for different gauge stations in different netcdf files (time steps).

I checked outputs for Oct 10, 2017
The 1st netcdf file "2017-10-10_00_00_00.15min.usgsTimeSlice.nc" has 3,862 gauges.
The 2nd: 2017-10-10_00_15_00.15min.usgsTimeSlice.nc has 1,759 gauges.
The 3rd: 2017-10-10_00_30_00.15min.usgsTimeSlice.nc 74 gauges.
....
So I dont know how USGS gauge observations are being assimilated.
Any idea?

**Comment by rphooper** [comment]
@zhiyuli @danames @dtarb @martinseul @Castronova 
Let me organize my response by topic.

1. Basemap. The user needs better orientation to figure out what reach is of interest. By the time you zoom in to see the reach network, there are few landmarks. Can some more detail be added in Bing maps or whatever is compatible. See screenshot to see what I mean. This is from the Oregon coast.
![image](https://user-images.githubusercontent.com/6717493/33030297-f89b4108-cde8-11e7-9f57-95e7575dea08.png)

2. USGS stations. Just adding the unit value stations (whether or not they are used in the assimilation) would be helpful, again as an orientation as well as a likely question will be to compare the USGS data with the model predictions. If we can later indicate which of those stations are being assimilated, so much the better. 

3.River Names/COMID. My initial thought was that both the COMID and the reach name would be displayed on the left side of the screen (i.e., not on map). Ideally, the user could type in a river name and get a list of COMIDs that contain that name, but that would likely have to be limited to current map extent. As to inconsistencies between NWM and NHD+, we have to get that from NCAR or NWC. Perhaps @Castronova could suggest who to talk to?

These are the three biggest issues that impact usability of the app. The other issues are lower priority.

Let me know if you want to discuss.

**Comment by zhiyuli** [comment]
@rphooper 
I changed imagery map to a road map (still Bing map). 
It is on https://appsdev.hydroshare.org/apps/nwm-forecasts/
This basemap looks very similar to the Google Map HydroClient uses.
Let me know if this improves or not. If you keep zooming in, it can show street names.
![image](https://user-images.githubusercontent.com/10070599/33047648-139915f4-ce14-11e7-9fd3-a558335606de.png)

**Comment by rphooper** [comment]
@zhiyuli Much better! Thanks.

**Comment by zhiyuli** [comment]
@rphooper 
Thanks for the feedback.
USGS gauge layer has been added on appsdev (green triangle with station id). Currently they are just static icons/images (not clickable)
![image](https://user-images.githubusercontent.com/10070599/33089397-b38b4a84-cead-11e7-9c7e-00aaac143b16.png)

**Comment by rphooper** [comment]
Thanks.

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/nwm-forecast-viewer#14
