### ISSUE TITLE
SciDas interoperability

### ISSUE THREAD

**Issue by goodalljl** [hydroshare/hydroshare#2471]
1.       A user uses Open With from HydroShare to Launch.  The contents of the resource become the files in the JH workspace. 
2.       The user does their work – perhaps using one or more notebooks that were in the resource.
3.       At the end the user “saves” and the updated files from the workspace are written back to the resource in HydroShare.  We should support concepts of “save” which updates the initial resource, and “Save As” which creates a new resource.

This loose integration model is desirable also to keep the cost of storage in the cloud low. 
In the next 2-3 months we (Claris and team) will be integrating SciDAS compute nodes with the webDAV iRODS client plugin which will allow the user's data in the HydroShare iRODS backend to be presented to the Jupyter notebook via POSIX interface. 

We (Claris and team) should be able to launch a SciDAS instance to support HydroShare in the next 2 weeks.

**Comment by rayi113** [comment]
Adding mention of @clarisca @hyi @dcvan24  re: implementation of this.

**Comment by goodalljl** [comment]
@clarisca @hyi @dcvan24 Any updates on the implementation of this?

**Comment by rayi113** [comment]
@goodalljl , @clarisca and @dcvan24 are both travelling this week, and with @hyi did make some progress on generalizing it to work more with Hydroshare earlier this week.  @hyi can explain, i.e. putting a .json cloud config file with the resource.

**Comment by hyi** [comment]
@goodalljl @dtarb As @rayi113 mentioned, I did some further work related to this SciDAS and HydroShare integration to enable flexibility with ```Open With a jupyter server appliance in SciDAS```. Specifically,  different configurations for SciDAS provision can be bundled with the resource in a json file if desired. If there is no JSON configuration file in the resource, a default SciDAS configuration will be used. This allows SciDAS to provision an appliance with different configurations specific to a resource if desired, e.g., cpus, memory, disk space, different docker image id to pull to create the appliance, etc. Once @clarisca and @dcvan24 have tightened up the backend, e.g., to integrate SciDAS compute nodes with webDAV iRODS client plugin, to have a SciDAS instance ready for supporting HydroShare, I will do work needed in my branch and then create a PR to get it merged in.

**Comment by dtarb** [comment]
@hyi regarding "I will do work needed in my branch then create a PR to get it merged in".  We need some clear description of the plan - at a high level.  There was a flurry of activity prior to SC17 for a demo, but before merging in, or before even more work, I think we need a clear description of what the capability will be.  If this is clear and written somewhere, I apologize for asking, and you can just point me to it.

**Comment by hyi** [comment]
@dtarb I will document this and point you to it after SciDAS and HydroShare integration work moves along from demo/prototype phase to production delivery phase to get input/feedback from the team first, then I will incorporate team feedback into the code before creating a PR for code review. Right now it is still in demo/prototype phase with many changing pieces, but once we have a clear plan toward production delivery, I will start to document this. Looping in @rayi113 @clarisca to keep them informed.

**Comment by dtarb** [comment]
@hyi I worry that this is the wrong order.  I understand that the demo/prototype was some sort of proof of concept.  With that now done, I think we need to state (write down) what the plan is.  What is the objective and what would we like the outcome to be.  I do not think that this writing has to be long, but it should be clear, so that we know that the work being done is actually directed at a needed purpose, and that it could be sustained as part of the deployed version of HydroShare.  It should be done in a way, and using CI that is stable, persistent and maintainable.   Coding, testing, and PR work without the objectives and outcomes clear, is at risk of being in the wrong direction and wasting time.  It is for these reasons I am pushing for some writing about objectives and outcomes to guide the coding and prototyping work.

**Comment by hyi** [comment]
@dtarb I understand your concern. I can draft this after touching base with @rayi113 and @clarisca to align HydroShare and SciDAS objectives to have a clear high level plan before doing so. SciDAS has an all hands meeting next week where I expect this would come up as a discussion item.  I will keep this in mind and start to draft it when the plan becomes clearer to me regarding this SciDAS and HydroShare integration work. Looping in @rayi113 @clarisca to chime in as needed.

**Comment by goodalljl** [comment]
@rayi113 Any updates on this issue? Things have been quiet so I wanted to check on where we are now with SciDAS/HydroShare integration. Thanks!

**Comment by clarisca** [comment]
@goodalljl : Stealey is currently working on integrating webdav (DevRods) with the Jupyter appliance so that the jupiter notebook can be presented with a POSIX interface into the remote userspace in iRODS. Fan is out of the country but back on Tuesday. We will touch basis next week.

**Comment by hyi** [comment]
@goodalljl @Castronova @dtarb @rayi113 The discussion threads on this issue #2533 prompted me with the similar "Open With" button for specific resource types for SciDAS integration, so want to get this  "Open With" button sorted out for this issue as well. In the prototype I did, "Open With" button is available for all resource types since I think any resource type can leverage this jupyter appliance automatically provisioned by SciDAS. What do you all think? Should we make this SciDAS Jupyter App consistent with HS JH app in terms of resource type the app supports?

**Comment by dtarb** [comment]
@hyi following are the general steps to follow.  
1. Establish the SciDAS functionality on a stable platform accessible to all hydroshare users.  This should rely only on functionality deployed operationally on www, so if there is iRODS functionality involved, it needs to be part of www (and be consistent with our access control model - no back door security use of proxy account)
2. Create a web app resource in HydroShare that provides the launching pattern from the supported resource types.
3.  With 2 done, a button to launch the app should appear on the apps tab for all resources that the app is configured for.  
4.  Users that want to use the app on a regular basis can go to the web app resource page and click "add web app to open resource list".
5.  If the app becomes popular and is demonstrated to be stable and documented and passes CUAHSI's standards CUAHSI can approve it to be on the open with page for all users.

@aphelionz could elaborate on the requirements for step 5, but at a minimum it is stability, accessibility to all users and documentation.

**Comment by hyi** [comment]
@dtarb Thanks for listing the general steps which are in line with what I have in mind. Step No. 1 is in the works by @mjstealey and @clarisca, and I think we will have to use OAuth for user login and authentication as well. My specific question, though, is on what resource types I should allow/designate to use this SciDAS app when creating a SciDAS web app resource. I am thinking I should all all resource types, but since JH web app resource only allow specific set of resource types, I am wondering whether SciDAS web app should do the same?

**Comment by dtarb** [comment]
@hyi it depends on what SciDAS does and what the pattern is that you set up for SciDAS to return its results.  Without knowing this, I do not know what to suggest.  The resource types allowed can be easily changed using a check box in the web app resource, so I suggest for now starting with Generic and Composite, and then seeing what is needed.

**Comment by hyi** [comment]
@dtarb Makes sense. For the SciDAS Jupyter appliance provision use case, I'd say it applies to all resource types since I don't see any constraints that prevent any resource type from leveraging this. The reason I brought this question up is that I saw JH app actually is configured to constrain it to a set of limited resource types, so I thought I might have missed something and want to clear things up if any.

**Comment by Castronova** [comment]
@hong  That was the original thought for the JH app too.  However, while any resource can be manipulated in JH, some don't make much sense...yet.  The general idea is to not confuse or mislead users, i.e. support for MODFLOW model instance may imply that MODLFOW is installed in the JH app when it actually isn't.  This is why the "supported resource types" have become more restricted for the JH app.

**Comment by hyi** [comment]
@Castronova Thanks for the info. I'll keep this in mind along the way while getting SciDAS app integrated into HydroShare production. At this point, I think SciDAS app is more generally applicable than JH app, and can be exposed to all resource types, but this may change as it moves along.

**Comment by cuahsimarko** [comment]
@Castronova are we moving forward with this?

**Comment by dtarb** [comment]
Stale.  Scidas team left RENCI.
