### ISSUE TITLE
SUMMA in HS Jupyter

### ISSUE THREAD

**Issue by goodalljl** [hydroshare/hydroshare#2472]
Allow user to launch a Jupyter notebook from HS that has SUMMA installed and configured to run.

Demonstrate this by 
1. Writing a notebook in HS for executing a SUMMA model 
2. Upload a SUMMA model instance into HS
3. Use "Open With" to launch the notebook and pull in the SUMMA model instance 
4. Update SUMMA model instance in HS with results from model execution

**Comment by goodalljl** [comment]
@Castronova can you please provide a status update on this issue? I think you said at AGU you have something close to (if not already) working. Thanks!

**Comment by Castronova** [comment]
@goodalljl I'm working on this issue this week.  I should have something to report in the next few days.

**Comment by rayi113** [comment]
@Castronova if not too much additional work, could you please create the Jupyter notebook for running Summa so that all dependencies are resolved within the notebook itself and not dependent on JupyterHub for any of the dependencies?  This would enable us to explore leveraging additional approaches such as @clarisca 's SciDAS work while still being interoperable with JupyterHub.  Thanks.

**Comment by cuahsimarko** [comment]
@Castronova can you update or close this?

**Comment by dtarb** [comment]
Essentially implemented.
