### ISSUE TITLE
Automatically delete never activated account requests older than 7 days

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2477]
At present if a user signs up, but never clicks on the link in confirmation email to activate their account, the record as an inactive account persists.  This prevents the user from using that email address again to create an account.  I suggest we delete these inactive accounts older than a set period (e.g. 7 days).  I suggest a period such as 7 days to allow time for activation, and resolution of problems possibly related to emails to some domains that bounce.

There is no risk in deleting such inactive accounts because they represent instances where a user has never been able to log in or perform any actions in HydroShare.

**Comment by dtarb** [comment]
The problem, and this may be related to #2478 is that as long as a remnant of an account is there, that email is blocked from the user trying again to create an account.

**Comment by aphelionz** [comment]
Soft delete can be added on later, then.

**Comment by sblack-usu** [comment]
I believe we can get a soft delete to work, we just need to account for the soft delete in the query of the account creation.  I'll move forward with the soft delete for now.

**Comment by dtarb** [comment]
I worry that working on soft delete is creating extra work.  What is it that we are trying to preserve.  The scenario that this is for is that an individual attempted to create an account, and entered their name, email, and organization, but never clicked the confirmation email, so never got in to HydroShare, so was never able to do anything.  All we lose by deleting is their name and an email that they do not respond to.  If this information needs to be entered again, it is easy just to re-enter in the sign up.  Striving for simplicity.

**Comment by sblack-usu** [comment]
I'm in the thick of 2478 right now and now I'm wondering if we even need to have a job to delete inactive accounts.  A user that hasn't verified their email has a user entry with is_active = False.  I'm making it so if a user tries to login with an inactive account, they can resend the verification email.  

So if a user with an unauthenticated account tries to login, they can just click the resend email link and get the email resent to their account.

If the unauthenticated user forgot their password, they would be presented with a message saying their user/password is incorrect and then they could click reset password and get a new password reset verification email sent.  If we update the email verify password reset workflow to check for inactive users and set them active, then we're done.  No need for the verification email because the password reset accomplished our email verification objective.

Thoughts?

**Comment by aphelionz** [comment]
I would prefer the process improvement over the repeated management task

**Comment by sblack-usu** [comment]
This issue is no longer relevant with the process improvements coming in #2478.
