### ISSUE TITLE
Evaluate handling of folder drag and drop operations

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2513]
When creating a resource dragging and dropping a folder either at the create resource step, or into resource contents when editing, results in the folder structure being flattened.  Only files are uploaded.  Folder paths are not retained.  This can result in name conflicts if separate folders had files with identical names, and incomplete uploading.

**Comment by Maurier** [comment]
This was a limitation at the time this functionality was implemented. @hyi @pkdash Could you give an update on whether we can pass a folder structure when uploading files at this point?

**Comment by hyi** [comment]
@Maurier I think the backend can support passing a folder path when uploading files now due to the work by @alvacouch, specifically see the ```folder``` input parameter in ```get_path``` here: https://github.com/hydroshare/hydroshare/blob/develop/hs_core/models.py#L2504. Which view function(s) do you call to add a collection of files in a folder hierarchy into HydroShare? There may be additional work needed to support this, but I think it can be done now without too much work.

**Comment by dtarb** [comment]
Closing as duplicate of #2456 and done in 1.16
