### ISSUE TITLE
OAuth support for third party websites/applications?

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2522]
**Background:** One of my developers @darksinge is working on linking another web application (http://data.envirodiy.org) to HydroShare to enable data from that website to be shared in HydroShare via the REST API. It is not a HydroShare App, rather it is a third party website with no real affiliation to HydroShare that wants to use HydroShare as a target for sharing data. Users of this other website will have to have a HydroShare account before they can publish their data in HydroShare. 

**Issue:** it appears that our only option currently is for the user to provide their HydroShare credentials to the EnviroDIY website, which then uses them to authenticate with HydroShare. Instead, we want to use the OAth workflow that enables users to be redirected to HydroShare to log in and then EnviroDIY never knows their HydroShare credentials. **This may already be possible, and if so, we just need to know how to do it**, so please point us at the right documentation or an example. If it is not currently possible, see below for details (with screen shots taken from Internet sources).

What we think we can do now:

![image](https://user-images.githubusercontent.com/3485902/33789865-d16ed8a2-dc38-11e7-984d-8e3792a7577b.png)

What we want to do instead:

![oauth-sequence-diagram](https://user-images.githubusercontent.com/3485902/33789874-ddd4aef0-dc38-11e7-8a38-91cbfbd9db60.png)

**Comment by zhiyuli** [comment]
@horsburgh 

This is the doc I wrote for the OAuth link between Model-My-Water project and HydroShare. It describes the basic HTTP handshakes OAuth needs, which can be implemented in any language or platform. 
https://docs.google.com/document/d/1UbZjr-f0Kvq27-jdPzFMjEcBcgWxn-M0UDi7cZ4GFe8/edit?usp=sharing

Is http://data.envirodiy.org/ website a Django application?  If yes, there are many ready-to-use libraries for OAuth client (Tethys uses python-social-auth.)

**Comment by horsburgh** [comment]
Thanks a ton @zhiyuli. I’ll have @darksinge take a look and hopefully it will meet our needs. It is a Django app so I’m glad to hear there’s good tools.

**Comment by cuahsimarko** [comment]
@hyi Hong, is this related to or helpful for the OAuth research you've been doing?

**Comment by hyi** [comment]
@cuahsimarko it is not directly related in that this issue was about having third party websites/applications as OAuth client to authenticate user against HydroShare OAuth server which has already been done such as HydroShare Apps Store, so only documentation is needed for third party applications to implement OAuth client to authenticate against HydroShare OAuth server. What I am trying to do is more complicated in that it involves another server, i.e., iRODS server, so there are three parties being involved, iRODS client, iRODS server, and HydroShare server, in which case the simple OAuth client-server direct interaction supported by OAuth would not be sufficient. Instead, an separate service, HydroShare Auth service, need to be set up to direct iRODS server to HydroShare OAuth server or Openid provider for user authentication. That would also involve iRODS server configuration, iRODS client OAuth support in addition to a Auth service that would mediate OAuth token management and handshaking.

**Comment by horsburgh** [comment]
Given that I posted this and that we've since completed the work on integrating the website in question with HydroShare via the REST API, I'm closing this issue.
