### ISSUE TITLE
discovery: author should match any creator

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#2553]
@dtarb @Lizabrazil @Castronova 
I'm reviewing the discovery code and the current definition of "author" is that "the author is the first creator in human-specified order". This is somewhat misleading. "Creator" is multi-valued, and entered by the person who creates the resource. Thus, anyone listed as creator by this person should be considered an author for purposes of discovery and faceting. 

I propose that **all creators should be treated as authors for purposes of discovery.** 

(only the first creator is shown in the list, but all should be faceted; currently all creators after the first are ignored)

**Comment by dtarb** [comment]
I agree that all creators should be treated as authors for the purposes of Discovery.  There should also however be somewhat special treatment of the First Author, as the Discover page list them in the listing and provides an option to sort by first author.

**Comment by alvacouch** [comment]
@Castronova @Lizabrazil @dtarb So let's just call first authors "first author" and then make the facet "author" and the query author:"someone" refer to all authors.

**Comment by dtarb** [comment]
Perfect.

**Comment by Lizabrazil** [comment]
I’m not sure I agree with this (if I’m understanding it correctly). Why should the creator automatically be considered an author? Where is “creator” exposed in the interface, do you mean “owner”?

**Comment by horsburgh** [comment]
@Lizabrazil - the Dublin Core Metadata standard does not have an "Author" element. They use "Creator." The definition they use is -  "An entity primarily responsible for making the resource." "Creator" is a bit more generic than "Author" because "Author" implies writing, which isn't really applicable to many web resources (like data). So, HydroShare uses the Dublin Core term "Creator" as a more inclusive form of the term "Author". 

The confusion is that at some point the decision was made to change the term "Creator" to "Author" in the label on the resource landing page - even though the term "Creator" is used in the metadata files. I see the confusion, and would be happy if "Author" was changed to "Creator" on the resource landing page. 

A resource's "Creator" may not be the person that uploads the content to HydroShare. That is why we have a separate "Owner" element.

**Comment by alvacouch** [comment]
Addressed by #2578
