### ISSUE TITLE
P2 Composite Res: Enable Editing of Resource-Level Coverage for Composite Resources

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2577]
Enable editing of resource-level coverage so that a user can specify any coverage they want for a composite resource.
* Disable automatic overriding of coverage from the Aggregations contained within the resource (unless they are blank when an Aggregation is created)
* Add two buttons to the resource-level coverage editing area for composite resource only that allows the user to set the coverage based on the content files of the resource. "Set spatial coverage from content files" and "Set temporal coverage from content files"

**Comment by dtarb** [comment]
I would prefer a check box to a button on the setting of coverages.  The checkbox should be labeled “Use coverage from member aggregations”.  The check box would be set to be on by default.  With the check box on, any time a new aggregation is added, or removed, the resource level coverage would update.  With the check box off the resource level aggregation would be user editable.  

This would avoid the need for users who want the coverage to inherit from member aggregations to repeatedly have to click the button.  It would also remove the peculiarity that we have now that coverage is set with the first file set as an aggregation, but then when later files are set as aggregations the coverage is not adjusted unless one pushes the button.

Users who want to edit coverage information and have it different from member aggregations would still be able to uncheck the box (coverage information would not change when the box is unchecked, retaining any existing coverage information as a start for editing) and then adjust the coverage.

If the box was unchecked, and a user checks it, coverage would be recomputed from existing member aggregations and any manual edits dropped.

**Comment by horsburgh** [comment]
For what it is worth – I prefer the buttons. That way, it is an explicit action by the user to set the coverage based on the content of the resource rather than ticking a box, forgetting that its checked, and then wondering why the coverage has changed later on.

**Comment by aphelionz** [comment]
@pkdash Can you please add a 1,2,3 point estimate label to these tickets?

**Comment by horsburgh** [comment]
This is complete in the phase 2 composite resource implementation.

**Comment by dtarb** [comment]
@pkdash @horsburgh  I found in working with the current deployment that the set coverage button is sometimes not there.  E.g. I just created a resource, added a nc file with coverage and it was automatically converted to multidimensional contents and coverage set (this is good and expected).  I then added a geographic raster and it was automatically converted to geographic raster content.  But the spatial coverage remains the same, and the set coverage button is not there. If I reload the resource, then the set coverage button appears.  But I should not have to reload.  (Also the netcdf file I tested with had title and metadata.  This did not appear on the landing page until I reloaded.  This may be an issue for @sblack-usu)

If I then click on the set coverage button it disappears (This could be OK - as coverage is now set from member content files).  However if I drag the coverage box in the map and save changes, the button does not come back.  The resource is in a state where it is valid to set coverage from member files, so the button should be there.  If I reload, the set coverage from content files button appears again..  

If I then again set the coverage from the content files, the button disappears.  But if I reload the page it is back again.  I find the appearance and disappearance of the button confusing.  It is also inconsistent for it to go away, then reappear when the page is refreshed.

**Comment by pkdash** [comment]
@dtarb and @horsburgh Here how the coverage update button works currently. The button appears if there is coverage data in any of the aggregations. The system currently does not track changes in aggregation level coverage data and resource level coverage data to decide if the button should be displayed or not. If we want the button to appear only if there is a need (resource and aggregations coverages are different) to update resource coverage, then the system needs to track coverage changes in resource and aggregations. Let me know If this needs to be fixed for release 1.16. Since it is not going to be a quick fix, I need to know if we have a scheduled date for 1.16 release.

**Comment by horsburgh** [comment]
Would it be easier to just make those buttons visible any time there is coverage information in the aggregations?  In other words, they appear as soon as you have something with a spatial or temporal coverage in the content of the resource and they never disappear unless you remove all content with coverage information.

If we do this, you might want to add a dialog box that appears after the button has been clicked to assure the user that the coverage has been set (e.g., an info box that says "Coverage has been set to the spatial/temporal window that includes all of the data in the resource.") - given that I could click the button multiple times in succession and it would just set the coverage to the same thing. The user might wonder if the button is not doing anything.

**Comment by pkdash** [comment]
@horsburgh Yes that would be much easier.

**Comment by dtarb** [comment]
I am OK with you following @horsburgh suggestions.  I do not think the current functionality is working the way you describe because if you click the button it disappears, but there is still coverage data in the aggregations (i.e. button does not display but aggregations still have coverage data).  The button reappears if the page is refreshed.  So it may just be a page refresh issue.

**Comment by pkdash** [comment]
The button gets hidden after the user clicks it to let the user know that the update has been made. Otherwise, user will be even more confused thinking the button does nothing. Any time the page gets refreshed this button always shows up if there are aggregations with coverage data. As suggested by @horsburgh instead of hiding the button after the user clicks it, will show a message indicating successful resource level coverage update and leave the button displayed. With this change the button to update resource level coverage will always show up (does not disappear)  if there is coverage data in any of the aggregations no matter how many times the user clicks the button.

**Comment by horsburgh** [comment]
@pkdash - I like it. Works for me.

**Comment by dtarb** [comment]
Works for me too.

**Comment by dtarb** [comment]
1.16 deploy
