### ISSUE TITLE
Correct Quota Message

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2605]
Please change the approaching quota to not refer to support@hydroshare.org and to refer to help.hydroshare for help not pages.hydroshare which is the development help site.

![image](https://user-images.githubusercontent.com/3456833/35931059-dbd14e28-0bf0-11e8-809d-1e023e46edb3.png)

It may also be possible to shorten the text to

> Your quota for HydroShare resources is 20.0GB in HydroShare zone. You currently use is 16.4088GB, (82.04%). Once your quota reaches 100% you will no longer be able to create new resources in HydroShare. To request additional quota, please contact **help@cuahsi.org**.   See https://help.hydroshare.org/about-hydroshare/policies/quota/ for more information about the quota policy. 

Can @Lizabrazil and @martinseul please review this.  I am trying to strike the right welcoming messaging and not be too verbose.

**Comment by dtarb** [comment]
The over quota message below also needs updating.  It is confusing to refer to hydroshare_internal zone when the earlier message referred to HydroShare zone.  Also please make sure that what is written is actually consistent with what we are going to be doing about enforcement.

![image](https://user-images.githubusercontent.com/3456833/35931996-b59011c4-0bf3-11e8-98df-870da4893685.png)

**Comment by dtarb** [comment]
Refer to Quota Rollout Plan https://docs.google.com/document/d/1oiAJ6cMCA2HlYsrAvGn7os4ftRGq1RzJLIVS5Vzl5AM/edit

**Comment by hyi** [comment]
@dtarb All the proposed quota messaging changes can be made directly from the admin page. The quota messages you are currently seeing are just default placeholder messages and can all be customized to what we really need from admin panel without code changes. If you think we need to change the default messages as well, I can change the code to reflect that after the default messages are finalized. I will change hydroshare_internal default zone name to hydroshare so that it makes its way to quota messages as hydroshare zone rather than the current hydroshare_internal zone.

**Comment by dtarb** [comment]
Done at 1.15.1
