### ISSUE TITLE
Quota system sending too many warning emails

### ISSUE THREAD

**Issue by aphelionz** [hydroshare/hydroshare#2608]
Just received a complaint that the quota system sent out a burst of 20 emails in about 1 minute. This was from beta

![image](https://user-images.githubusercontent.com/106148/36034103-f84fa716-0d80-11e8-9ed7-95c0bc58c8bd.png)

**Comment by hyi** [comment]
@aphelionz I will have to move sending quota warning email out of the async running celery task when being invoked to update quota usage. I can move it to the nightly run celery task. Is it OK to send this quota warning message each night to the users who are over quota or over quota soft-limit? If the answer is yes, I'll update the code to do so. Let me know.

**Comment by aphelionz** [comment]
@hyi Yes, I think that's fine for now.

**Comment by hyi** [comment]
@aphelionz I have pushed the updated code to my quota branch and updated beta as well. As a result, it is supposed to send out quota warning emails once each mid-night at the defined UTC time zone. Could you monitor the emails from CUAHSI email server to make sure this issue is fixed and now works as it should?

**Comment by aphelionz** [comment]
Thanks @hyi!
