### ISSUE TITLE
Sign up problems with controlled vocabulary in organization

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#2673]
@aphelionz  Here is the error I get 

![image](https://user-images.githubusercontent.com/4108369/37101019-5d652bc8-21d9-11e8-83ad-d2b6546852c1.png)

**Comment by ChristinaB** [comment]
I was able to sign up with the option that excludes, San German as below. It gives an error message, but then does submit the form. 

![image](https://user-images.githubusercontent.com/4108369/37101140-b345ee60-21d9-11e8-876f-cdeb5ae4a47e.png)

**Comment by ChristinaB** [comment]
What happens if I do not activate this test account?

**Comment by dtarb** [comment]
@ChristinaB If you leave an account inactivated it will just sit there.  You can request an admin (like me) to delete it.  In functionality that is in prototype and soon to be released you will be able to resend the activation email if you try create an account with the same email later.

**Comment by sblack-usu** [comment]
I looked into this a bit.  The jquery library we are using a tags library, built for comma delimited tags.  You're not able to select a result with a comma in it because the javascript is currently looking for commas in the string and creates a new tag at each comma.  I was able to turn this off the comma delimiter locally and add "Universidad Interamicana de Puerto Rico, San German" as an organization.

Because the organization field currently allows multiple organizations, we'll have to choose a safe delimiter to use (e.g. ";" or "-", something that's not in an organization name).  Please note that this delimiter will also show up on the user profile page if there is more than one organization.

**Comment by sblack-usu** [comment]
I did some more investigating and it looks like a semicolon won't work because of "US EPA; Purdue University,Purdue University,United States Environmental Protection Agency"

Here is the list of known organizations.  https://github.com/hydroshare/hydroshare/blob/develop/hs_dictionary/management/commands/normalize_universities.csv

**Comment by sblack-usu** [comment]
The other file I linked is used for normalizing organizations.  This file is the full organization list as far as I can tell.
https://github.com/hydroshare/hydroshare/blob/develop/hs_dictionary/migrations/world-universities.csv

**Comment by sblack-usu** [comment]
I've got some work done on this, but it's going to be a little more complicated than just changing the delimiter.  It looks like some of the python code is looking for the commas as well and we should probably make an effort to properly serialize the organizations.  I'll talk to @aphelionz about possible solutions when he is back.

**Comment by aphelionz** [comment]
Hey @sblack-usu Thanks for taking a closer look at this. Do you have time next week so that I can go over the overall context that this work fits into? I feel like once you understand that all the stars should properly align and this will be a go.

**Comment by sblack-usu** [comment]
yeah, do you just want to talk Monday sometime after the developer call?

**Comment by dtarb** [comment]
Fixed 1.15
