### ISSUE TITLE
Hyperlink DOIs against preferred resolver

### ISSUE THREAD

**Issue by katrinleinweber** [hydroshare/hydroshare#2689]
Hello :-)

The DOI foundation recommends [this new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). Would a PR that updates all static links & the code that generates new ones, plus the test cases be welcome?

Cheers!

**Comment by katrinleinweber** [comment]
PS: Also in the sister repos.

**Comment by horsburgh** [comment]
@katrinleinweber - thanks for the suggestion. What would be the benefit of using your suggested resolver over just using http://dx.doi.org or even just http://doi.org in our URL-encoded DOIs?

**Comment by aphelionz** [comment]
@horsburgh The benefit is that it is encrypted + securt https instead of http.

@katrinleinweber yes PRs are welcome :)

**Comment by hyi** [comment]
@dtarb @horsburgh Took a quick look at the code change, and found the only change involved is to change ```http://dx.doi.org/``` to ```https://doi.org```.  The ```https``` version is preferred and secured URL, but``` http``` version is also supported by DOI server. The XML metadata file will be updated accordingly for new published resources since it retrieves URL-encoded DOI from our identifier metadata element. But for old published resources, DOI URL will not be updated unless we do a data migration. However, the old ```http``` URL still works, so we may not need to do a data migration since both versions of DOI URLs work. I guess this PR can make the new published resources to use the new preferred secure https DOI URL version going forward, which probably is a good thing.

**Comment by katrinleinweber** [comment]
#2690 is the PR.
