### ISSUE TITLE
Owner in bag-info.txt needs to be updated when owner in HydroShare resource is changed

### ISSUE THREAD

**Issue by rayi113** [hydroshare/hydroshare#269]
When a user changes the owner of a HydroShare resource in Django, the corresponding owner information in the bag-info.txt information within the HydroShare resource bag is not updated, but should be.

**Comment by dtarb** [comment]
@hyi can you please address this as part of your being in charge of users/groups/entities.  This issue may be a bit deeper than just this bug as some of the owner changing functionality does not work right and I think you need to review this holistically starting from the data structures used for users.  It may be easier to address this using @alvacouch access control functionality than trying to fix the functionality in Django.

**Comment by hyi** [comment]
@dtarb Does this issue need to be addressed for release 1.5? If so, it is not possible to tie this with Alva's access control functionality since the access control will not be available for release 1.5. I can look at this issue trying to address it in Django if it is important to include this fix in 1.5. Otherwise, I'd suggest to address this for release 1.6 together with access control revamp. Let me know.

**Comment by dtarb** [comment]
I would prefer doing this right (once) in a structured way, to band aid fixes.  It seems to me that @alvacouch database and API are the right way to do this.  Is it possible to do this using Alva's database to hold and manage ownership content, but not enforce it in iRODS yet.  This would actually exercise the implementation and useability of this database before building a strong dependency on it, so may be a good incremental way to test this.  If we can do this for version 1.5 I would prefer that.  Also a question is, can we afford to go to version 1.5 without proper management of ownership and access control.

**Comment by hyi** [comment]
It is possible to use Alva's database and API for Django access control without iRODs backend support, but the following has to be decided/done to get it into production:
1. Where to put Alva's Access control database? locally together with Django server or remotely on iRODS server? It is designed to put together with iCAT on iRODS server, so latter might be preferable. If we go with latter, we have to configure database and firewall to allow external connection from Django server. Also, we have to tie this into irods dev vm which development team will use for further development. All this has to be done and well-tested, which I anticipate will go through some bumps along the road.
2. I have to write a script to migrate existing data on beta to the new HSAccess database, which will take some investigation also.
3. Do holistic testing to make sure replacement of current access control with the new HSAccess database API will work in all workflows without breaking anything.

If we target this for 1.5, I am afraid I will not have time to work on the new bagit workflow revamp, since both tasks will be pretty involved to get them into production. 

Also, could you list some specific issues with the current access control management? I believe it supports multiple ownership, read-write, read-only access control management. Is there something important on access control that is broken and we need to fix for version 1.5?

**Comment by hyi** [comment]
While looking at bag-info.txt generation to fix this issue, I have two questions to get confirmation from the team:

1. Currently, only the first owner is written to bag-info.txt. We can write all owners with no problem. Want to confirm the format for multiple owner case. Should we write multiple owners in the following format:

author: user1
author: user2
...

just to list all owners, or we should distinguish the creator (i.e., the first owner) by labelling it with something like "creator: user1" followed by "owner: user2" etc.?

2. Currently, the title is included in bag-info.txt. However, when a title includes special character beyond ASCII range, library of congress bagit.py lib raises an error when writing the title into bag-info.txt, which creates the problem for us. I am suggesting to remove title from bag-info.txt to avoid modification to an external library code.

**Comment by dtarb** [comment]
@horsburgh can you please provide input on what is right to do for DataOne OAI-ORE consistency, and given our model of multiple owners and creators.  We also need a solution that is consistent with the semantics of owner and creator being different.  Please resolve whether this bagit-info.txt file is supposed to contain Owners or Creators.

Owners are HydroShare users who "own", in the permissions sense, the resource in HydroShare and can control who can change and have access to the resource.
Creators are people or organizations in the Dublin core sense who are responsible for the intellectual content of the resource.  They may or may not be HydroShare users.  Creators in the Dublin core sense are equivalent to authors in the sense of writing a paper.

**Comment by horsburgh** [comment]
In the resource packaging document (https://my.alfresco.com/share/hydroshare.org/page/site/HydroShare/document-details?nodeRef=workspace://SpacesStore/d197689a-338e-4cb2-8a99-5b489ed83a33) it states:

"HydroShare will not use optional elements of the BagIt specification.  BagIt optional elements include:
1. Tag Manifest: tagmanifest-<algorithm>.txt
2. Bag Metadata: bag-info.txt
3. Fetch File: fetch.txt
4. Other Tag files"

I took a hard look at the BagIt specification when I wrote that document and at the time I didn't think that we needed the optional elements.  The "bag-info.txt" file is not required by BagIt.  Do we need it at all?  Can we suppress it's creation using the BagIt library we are already using?

**Comment by rayi113** [comment]
Since bag-info.txt is not necessary, it will be omitted from the bagit workflow and thus this issue will be fixed by the NFIE Release.

**Comment by dtarb** [comment]
This is not quite done.  If old resources are downloaded the bag-info.txt still contains incorrect owner information.  This is not NFIE-Required so I am deferring to deployment 1.6.  When bagit restructuring is complete all bag-info.txt files should be deleted to resolve this issue.

**Comment by hyi** [comment]
@dtarb Since we don't maintain the old resources before NFIE bagit restructuring, this issue does not exist any more, correct? If so, we can close this issue.

**Comment by dtarb** [comment]
Tested on dev and closing.
