### ISSUE TITLE
Web App resource metadata to XML doc

### ISSUE THREAD

**Issue by jsadler2** [hydroshare/hydroshare#2705]
Currently the resource specific metadata elements for Web App resources are not serialized and included in the `resourcemetadata.xml` file. 

Check HS GIS app resource for example : https://www.hydroshare.org/hsapi/scimeta/9674a0af9f30410e9e02397c91284f54/

**Comment by dtarb** [comment]
@horsburgh what is the recommendation here from a resource data model perspective.  Do we need this.

**Comment by horsburgh** [comment]
I don't think a web app resource has any context outside of HydroShare. If we are worried about the integrity of the web app resource metadata, which I presume is stored in the Django database, then we might want to consider working on this so that the metadata is also stored in the resourcemetadata.xml file.  However, there is no download functionality for a web app resource and so the only way to even get the metadata file is to know it's direct URL or I suppose retrieving it through the API. I think this can be closed with no action.

@jsadler2 - if there was a reason why you thought this was important, let us know and we can consider this further.
