### ISSUE TITLE
HydroShare Python API returning Internal Server Error

### ISSUE THREAD

**Issue by mmbayles** [hydroshare/hydroshare#2713]
I am using the hs_rest client (version 1.2.12). I am getting an 500 internal server error when trying to discover resources by certain parameters such as 'group' and 'creator'. I can access resources via resource type and I can download resources normally. 

Example call:
hs.resources(creator='Matthew Bayles') fails while hs.resources(type='TimeSeriesResource') succeeds.

**Comment by sblack-usu** [comment]
hs.resources(creator='Matthew Bayles') produces a 400 Bad Request, not a 500 internal server error.  

It produces the 400 Bad Request because 'Matthew Bayles' does not match as a username.  You can find usernames in the about section of the user profile.

**Comment by mmbayles** [comment]
The documentation states name or email as parameters. It probably should be changed to username to avoid confusion. The username works but have you tried email? I get a 400 error when I use creator or owner but my email in HydroShare and the one I'm using for the request are the same. However, when 
I use email on Author it appears to list every resource in HydroShare. Also, I'm still having a problem with the group parameter.  I created a group named 'Script Group' which has an ID of 54 which is public. I have tried numerous combinations and I always receive a 400 or 500 error. Can you explain why I am receiving these errors?

**Comment by sblack-usu** [comment]
I agree the documentation is misleading with the use of name instead of username.  It looks like the documentation was updated back in Feb, but never pushed out.  We'll get it pushed out.

I've tried email with mixed results.  Email works for the author keyword, but not for the creator keyword.  I'm looking into what is going on there.

For groups, I'm getting  a 500 with the group name and a 400 with a group id.  I'm looking into it, but the 500 indicates to me that the query is making a match, but somehow mishandling the data, while the 400 results are not matching at all (maybe id isn't actually supported in the query currently).

**Comment by sblack-usu** [comment]
These issues appears to be an issue with the rest api rather than the rest client.  I'm still troubleshooting, but generally the emails queries against users aren't working due to the ResourceListRequestValidator having a validator that only checks the username.  This blocks emails from being passed even though the query supports emails.  https://github.com/hydroshare/hydroshare/blob/develop/hs_core/views/serializers.py#L70

As for groups, it looks like the query is failing because it's trying to put a group into a resource object.  I'm still looking into this.  But group queries also have the same problems with the validator only checking the group name, rather than both name and ids (which the query code aims to support).

**Comment by aphelionz** [comment]
Closing as 1.15.1 has been deployed. @mmbayles please confirm
