### ISSUE TITLE
Change HydroShare iRODS to do soft delete

### ISSUE THREAD

**Issue by rayi113** [hydroshare/hydroshare#2717]
In HydroShare code, change all occurances of iRODS iCommand "irm -rf" to "irm -r"; and "irm -f" to "irm"

Confirm this works first on usersdev for hydroshareuserdevZone on beta, then on hydroshareuserZone to implement in production.

This is only one interim step towards implementing a comprehensive consideration of how deleted resources in HydroShare are handled from the UI to django to iRODS.

This issue is related to: https://github.com/hydroshare/hydroshare/issues/2712

**Comment by hyi** [comment]
@rayi113 @aphelionz I can implement this pretty easily. However, I think this has to be accompanied with a periodic job to call irmtrash to purge files as needed. irmtrash has a parameter ```--age``` that seems to allow to specify age in minutes which I assume would only delete collection over the specified age in the user's trash can. Should we do this periodic trash purge as a Jenkins job or as a periodic celery task? What is the ```age``` we should use to purge trashed collections? A month? Looping in @phuongdm and @cbcunc as well in case we want to go with the Jenkins route for trash purge.

**Comment by rayi113** [comment]
I propose setting the age at 2 months so we can manually visit any user deletion patterns on HydroShare dev calls by manually looking at the iRODS trash area, and also see if we can infer HydoShare user deletion patterns from Kibana.

**Comment by hyi** [comment]
@phuongdm I also thought about what you suggested here as an alternative, however, this will have implications on quota since setting isDeleted flag in Django db will not really delete the files in iRODS, which will not reduce user's quota as a result of resource deletion. Also, users could only delete a file without deleting the whole resource, which may require to add isDeleted and purgeData on ResourceFile field as well if we want to support restoring accidentally deleted files from HS UI. Unless we resolve these two implications, I don't think this alternative approach would be viable. Thanks for bringing up this alternative approach on the table, though.

**Comment by phuongdm** [comment]
@hyi,

+ About files restore, I think you have your solution with isDeleted on ResourceFile
+ About quota, the usage should be: the real usage (get from iRODS) - sum of size of files in ResourceFile which has isDeleted on

**Comment by hyi** [comment]
@phuongdm What you suggested involves making changes to Django DB models to add the needed fields to mark resources or resource files for deletion, which will involve code changes on most if not all resource or resource file related functions to exclude marked-for-deletion resources and files. We also need periodic job to purge deleted resources and files. So basically this approach involves making changes only on Django side without touching iRODS by marking resources and files for deletion without really deleting them. This does make deleted file restore easier since we just need to set isDeleted flag in Django db accordingly.
