### ISSUE TITLE
Tool icon in web app resource

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2758]
I entered an Icon URL in a web app resource.  The image appears to be captured, but when I click save changes I get the error message below and am unable to make the icon persist.  

![image](https://user-images.githubusercontent.com/3456833/40571799-933f608a-605c-11e8-94d1-8542d240d228.png)

![image](https://user-images.githubusercontent.com/3456833/40571813-c153eac2-605c-11e8-8dc8-066e60a15595.png)

I tried first with https://avatars3.githubusercontent.com/u/8520008?s=200&v=4, then putting the icon in a HydroShare resource to have a URL ending in .jpg and .jpeg, but none worked https://www.hydroshare.org/resource/7da3501f2de2461b9a8c4e593400d019/.

In addition to having the icon at a URL, I think there should be an ability to add a file to the web app resource to store the icon.

**Comment by dtarb** [comment]
I was able to resolve this by copying the file from https://avatars3.githubusercontent.com/u/8520008?s=200&v=4 into paint and saving as a new paint file and pointing to that.  So somehow the file format coming from github is not compatible with HydroShare.  Thus I am removing the bug label, and leaving this as an enhancement suggestion to be able to add the file to the web app resource avoiding the need for a separate resource to hold an icon file, and to if possible generalize the files accepted.

**Comment by sblack-usu** [comment]
I'm looking into this and the githubusercontent image is failing to work because the python library imghdr isn't able to determine the image type from the images byte stream.  Perhaps the jpg format of that file is incompatible with the imghdr library.  I don't have much experience in image libraries and will have to investigate.

@zhiyuli wrote this code initially, so perhaps he could chime in.  Also, after looking at that code I learned that we are indeed storing the image file in the database and not linking to the original source on display.

**Comment by sblack-usu** [comment]
@aphelionz - what specifically are you confused about?

**Comment by sblack-usu** [comment]
So this issue is documented and from reading the forums, a patch for this is not coming out for python 2.7.  https://bugs.python.org/issue16512

So without upgrading our python version, we're stuck with this library.  However, there is no reason why we can't wrap imghdr with this patch in our own code.  I did a quick test and was successful.  I'll clean it up and submit a PR.

**Comment by aphelionz** [comment]
@sblack-usu are we storing the binary image in the db and not a string filename pointer?

**Comment by sblack-usu** [comment]
@aphelionz - https://github.com/hydroshare/hydroshare/issues/1933

As far as I can tell it's storing the image as a base64 string.  I'm not sure what you mean by a string filename pointer.
