### ISSUE TITLE
Geospatial Services 

### ISSUE THREAD

**Issue by valentinedwv** [hydroshare/hydroshare#278]
Use geoserver to expose geospatial data types

Phase 1:
* use gsconfig to push data files onto a geoserver via a task

Phase 2:
* option 1: Write resource driver to read directly from irods
* option 2: Use new fuse being developed to directly access files

Phase 3:
* access control: make geoserver use irods as the access control source

Phase 1 task:
* install geoserver (done)
* write tasks for (raster) files to push to geserver
* hook up raster
* repeat for shape files

**Comment by zhiyuli** [comment]
I think this issue is not related to this Reference Time Series

**Comment by dtarb** [comment]
OK.  Relabeling this as Apps.  Geospatial services really refers to establishing the capability to publish web services for data stored in HydroShare

 * Web feature services for features
 * Web coverage services for rasters

I hope that sofware in the Tethys stack can be used to achieve this which is why it is an App.

However, note that the label reference resources, is not limited to time series.  It includes a range of data types that need to be supported by reference, including web map services, web coverage services, web feature services, that we may want to register and share in HydroShare.

**Comment by hyi** [comment]
@dtarb I am assigning this to @zhiyuli for further investigation, but you may want to take a second look on this issue.

**Comment by pkdash** [comment]
@dtarb Is this still an issue?

**Comment by dtarb** [comment]
@danames and @zhiyuli please make sure this is considered together with #1450 and then prioritize or close as appropriate

**Comment by danames** [comment]
This issue is a bit out of date and has been replaced by an approach described in issue #1450. I'm also adding a comment to #1450 to make sure we refer to any useful issues - for example, the idea of pointing the geoserver directly at the iRODS data set via fuse or some other method.
