### ISSUE TITLE
Downloading file via URL fails if it isn't public

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#2793]
## Steps to Reproduce
1. create hs resource, keep sharing status private
2. right click on file --> `Get file URL`
3. in local terminal download with `wget`: wget <file url>

This gives a 403 forbidden error, which is expected since HS cannot verify who is downloading the resource.  

## Suggested Fix

1. Deactivate `Get file URL` button for non-public resources
2. Tell user that resource must be public to access via file url

**Comment by horsburgh** [comment]
@Castronova - another way to look at this is that the current behavior is the desired behavior. I don't think the "bug" label applies here.

If a user tries to request a URL and is not authorized to do so, they should get a 403 forbidden error - as they do now. There may be some instances where a user wants to exercise private file URLs - e.g., they are writing a script for analysis on a private resource and don't want to publish or make the whole thing public until they are finished. So, rather than disabling the functionality to get the URL, maybe we should just add a message to the modal window that pops up when they right click and select "Get file URL" that warns them that their resource is private and only users that have been given access will be able to access the URL. So the text would be something like:

>You have requested the URL for a file that is within a private resource. Only you and other HydroShare users who have been granted at least "view" permission will be able to access this URL. If you want this URL to be publicly available, change the sharing status of your resource to "public".

This message would appear on this modal window that pops up (but only for private resources):

![image](https://user-images.githubusercontent.com/3485902/41728169-58f054a2-7533-11e8-8800-b6fbddffd47a.png)

**Comment by aphelionz** [comment]
can you authenticate via wget using wget authentication?

` wget --http-user=USERNAME --http-password=PASSWORD http://SOMETURLTOFILE`

**Comment by aphelionz** [comment]
I will test this soon - assigning to myself.

**Comment by Castronova** [comment]
Passing basic authentication through `wget` does not currently work. 

```
--2021-01-12 14:06:19--  https://www.hydroshare.org/resource/80b1a8474f954c9ca2c9df449df6e306/data/contents/screenshot_button_pressed.vrt?zipped=true
Resolving www.hydroshare.org (www.hydroshare.org)... 152.54.2.89
Connecting to www.hydroshare.org (www.hydroshare.org)|152.54.2.89|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /resource/80b1a8474f954c9ca2c9df449df6e306/data/contents/screenshot_button_pressed.vrt/?zipped=true [following]
--2021-01-12 14:06:19--  https://www.hydroshare.org/resource/80b1a8474f954c9ca2c9df449df6e306/data/contents/screenshot_button_pressed.vrt/?zipped=true
Reusing existing connection to www.hydroshare.org:443.
HTTP request sent, awaiting response... 302 Found
Location: /django_irods/rest_download/80b1a8474f954c9ca2c9df449df6e306/data/contents/screenshot_button_pressed.vrt/?url_download=False&zipped=True&aggregation=False [following]
--2021-01-12 14:06:19--  https://www.hydroshare.org/django_irods/rest_download/80b1a8474f954c9ca2c9df449df6e306/data/contents/screenshot_button_pressed.vrt/?url_download=False&zipped=True&aggregation=False
Reusing existing connection to www.hydroshare.org:443.
HTTP request sent, awaiting response... 401 Unauthorized
Unknown authentication scheme.

Username/Password Authentication Failed.
```

**Comment by cuahsimarko** [comment]
This worked for me on macOS

`wget https://www.hydroshare.org/resource/db867dfcdd7d43b79e4ff4b8bd012800/data/contents/requirements.txt --http-user=mobrien@cuahsi.org --http-password=$ENV_HS_PASSWD --keep-session-cookies --auth-no-challenge`

**Comment by cuahsimarko** [comment]
Note that if you enter your password in the command line it will appear in your OS history. Environment variables are a slightly better practice for this, though use your judgement, none of it is a secure approach.

**Comment by Castronova** [comment]
Thanks @cuahsimarko, I'll test this.

**Comment by dtarb** [comment]
@Castronova check this out and provide documentation information to @ClaraCogswell if you arrive at the solution being documentation

**Comment by devincowan** [comment]
related to #4491 2313

**Comment by devincowan** [comment]
@Castronova apologies I thought I had pinged you on this one but didn't. No code review required, just make sure the above messages are accurate for your request? Thanks
