### ISSUE TITLE
Variables appear multiple times refts

### ISSUE THREAD

**Issue by jsadler2** [hydroshare/hydroshare#280]
With http://icewater.usu.edu/littlebearriver/cuahsi_1_1.asmx?WSDL URL variables show up multiple times:
![image](https://cloud.githubusercontent.com/assets/6943441/6954893/1a5b35de-d894-11e4-9f31-c66c7f7b5afd.png)

**Comment by horsburgh** [comment]
Jeff - how are you populating the list of variables?  FYI - in the Little Bear River Database, there are multiple versions of some time series with the same variable (e.g., QualityControlLevel 0 versus 1) and some variables are measured at multiple depths (each depth has a different Method).  Since the "normal" WaterOneFlow calls include only a SiteCode and VariableCode, for some WaterOneFlow web services like the Little Bear River, you need to add the Method an QualityControlLevel to the web service call to isolate a single time series.  Otherwise, you will get multiple time series in your WaterML response.

Not sure this is the issue you are having, but something to keep in mind.

**Comment by dtarb** [comment]
@danames can you please test this in HydroShare 1.5 release candidate on alpha.hydroshare.org, and if agreed close.

**Comment by mjstealey** [comment]
Deferred to later release cycle

**Comment by zhiyuli** [comment]
tested on alpha (1.5.3). closed
