### ISSUE TITLE
Resource Landing Page: Reorganize Elements For Clarity and Easier Access

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2810]
After quite a bit of discussion, the following reorganization of the resource landing page needs to be done. The following tasks need to be completed. Refer to the mockup at:

https://app.moqups.com/jeff.horsburgh@usu.edu/UNcFub9Dcj/view 

* [x] Reorganize the page to follow the following outline:
* Title
* Author information and header information
* Abstract
* Subject Keywords
* Resource Level Coverage (only if coverage is present)
* Readme Viewer (only if a readme file exists - covered in a separate issue)
* Content
* Additional Resource Metadata
* References
* Credits
* How to Cite
* Storage
* Comments

* [x] Remove tabbed interface near the bottom of the page entirely.
* [x] The "Web Apps" tab will no long appear on the resource landing page
* [x] Modify edit page so that author editing happens at the top of the page where authors are listed. This can be done with the same modal window that is used now, just move "Add Author" button to the top in edit mode. In edit view use the tabular author view from the "Authorship" tab so that author order can be set as it is now.
* [x] Modify Author display/view so that a modal pops up showing author organization with a link to the author's profile. Or make the author view expandable/contractable in some way to show organizational affiliations and links to profiles.
* [x] Move display of sharing status to the header at the top of the page. Move setting/editing of sharing status to the "Manage Access" modal window and combine with adding access for individual users.
* [x] Add "Content Types" to the header with a listing of the content types that have been added to the resource (only relevant for Composite Resource).
* [x] Add number of views and downloads to the header.
* [x] Add number of +1 votes and all rating functionality to the header (e.g., +1 voting occurs in the header). Remove +1 voting from bottom of the page.
* [x] Add number of comments to header with a link to "Discuss this Resource" which takes the user to the Comments section at the bottom of the page.
* [x] Add a "Cite this Resource" link in the header that takes the user to the "How to Cite" section at the bottom of the page.
* [x] Add a link to "Show More" or "Show Less" to expand and contract header information. When more is selected, the whole header is shown, when less is selected, only Authors and sharing status are displayed.
* [x] Make individual subject keywords links to the discover page that shows a search result for that keyword. Open in a new tab.
* [x] Remove "Extended Metadata" tab and instead expose the same functionality as a section called "Additional Resource Level Metadata" on the page. This section will only display if key-value metadata have been added. 
* [x] Remove "Related Resources" tab and expose the same functionality as a section called "References" on the page.  See additional text/message/styling changes that need to be made in issue #2763. 
* [x] Remove the Authorship tab. Editing of Authors needs to be in the header where Authors are displayed. Create a new section on the page called "Credits" and combine "Contributors" and "Funding Agencies" under that section.
* [x] Under "How to Cite" make the option to require agreement to rights statement before downloading appear only in edit mode.
* [x] Under "Storage" modify so that the statement about Quota holder only appears for resource owners. Add a statement that reports the size of the resource: "The size of this resource is XXX MB."

These changes are related to two other major issues #2812 for adding readme support to the resource landing page and #2813 for modifying the content area to display as split file view and metadata view.

**Comment by pkdash** [comment]
@horsburgh 

> Add number of views and downloads to the header.

Is the number of downloads account for both bag downloads and resource file downloads?

**Comment by Castronova** [comment]
We're storing a "download" for each `pre_download_file` event. I'm not sure if the file download is triggering this event, but I know that the bagit download is.  See line 37 in the following link:

https://github.com/hydroshare/hydroshare/blob/master/hs_tracking/signals.py

**Comment by hyi** [comment]
@Castronova @pkdash @horsburgh ```pre_download_file``` signal is only sent when a regular file is downloaded as shown here: https://github.com/hydroshare/hydroshare/blob/a6a20809d28fe5baf83957166af9d71540038c88/django_irods/views.py#L288
This appears to be the only place this signal is sent, so it appears only file download triggers this event. In other words, it appears bag download and zip download do not send this signal, hence not tracked.

**Comment by dtarb** [comment]
I agree we should count all.

**Comment by pkdash** [comment]
@hyi  You are correct. Before asking my question above I had looked at the same code as you pointed out and noticed that we are tracking only the resource file downloads. Anyway, I think tracking other type of downloads should not be hard.

**Comment by horsburgh** [comment]
If we have the capability to aggregate in that way, then yes, I think that makes sense. Then each "view" has a little more meaning and we aren't double counting.

**Comment by pkdash** [comment]
@horsburgh Let me know if you would also like to show how many users with whom the resource has been shared. Basically it would show number of users who have at least view permission on the resource.

**Comment by horsburgh** [comment]
@Maurier - do you think Pabitra's suggestion would be a useful statistic to display? I sometimes wish that I had this kind of "at-a-glance" type information so I wouldn't have to go into the "manage access" panel and check the settings. If it's easy enough to add it, then I think we should add it to the view.

**Comment by Maurier** [comment]
I think this would fit nicely in the highlight section we just added. It could be something like "Shared with: 19 participants".

**Comment by horsburgh** [comment]
After an initial round of testing, I found the following things that need to be fixed to complete this work:

* [ ] 1. I don't like the small button used to collapse sections and then the elipsis button that expands them back out (e.g., on the collapse header and in the manage access panel). They are not intuitive. Can we just use a link to "Show More" or "Show Less" or a button that is more obvious what it does (e.g., the button is labeled "Show More" or "Show Less"?
* [ ] 2. When you expand the file metadata view to the left by dragging the bar, the columns of the file content view get compressed into the space available. This makes the file names disappear. Could we set a minimum size for the file content view that shows the file names, file types, content type, and size and then make that area horizontally scrollable? 
* [ ] 3. There's a little too much space between the content area and the "Download all content" label. I think you can tighten that up.
* [ ] 4. When I check the box to require users agree to the rights statement, it boots me out of edit mode. It shouldn't.
* [ ] 5. When I am logged out, it is not requiring me to agree to the rights statement before downloading individual files by double clicking on them. It is working correctly when I click the button to download the bag or right click on a file and select download. I believe this is also an issue on www at the moment.
* [ ] 6. Clicking on the sharing status and setting it as public boots me out of the manage access panel. It shouldn't.
* [ ] 7. The Sharing status in the header should appear as "Sharing Status: Public" and not just "Public" so people know what it is.
* [ ] 8. The header is missing the "Cite this Resource" link that will take them to the bottom of the page to the citation section.
* [ ] 9. The "Relations" label under the "References" section should be changed to "Related Resources"
* [ ] 10. Under the Credits section, reverse the order of Contributors and Funding Agencies
* [ ] 11. Change the "How to cite" section label to "How to Cite"
* [ ] 12. I found myself dragging the content area to make it vertically bigger a lot. Can we expand the default vertical size just a bit?
* [ ] 13. When a user clicks on a subject keyword, it takes them to the discover page and leaves the current page. This should open a new tab instead.

Additional things to consider:

* [ ] 1. Created and updated dates are still showing in UTC time. Can't these be displayed in my local time zone?

**Comment by dtarb** [comment]
Bug:
1. If I select multiple objects in the content area (e.g. multiple aggregations) then click the download button, I do not get all downloaded.

Additional suggestions from testing on playground and looking at the video that @Lizabrazil sent.

While I am offering these, I am sensitive to increasing scope.  It is important to have functionality rolled out in as small increments as possible.  These could be left to a later round of upgrades.  None of these are essential for the first incremental release of this new landing page.  

1.  I agree with the video suggestion that the top block is not necessary in editing mode.
2.  I think that the top block is probably essential in view mode.  Thus I would get rid altogether of the expanding/collapsing that @horsburgh commented on pt 1 above, and just have the content visible in view mode and not shown in edit mode.
3.  There was a comment in the video about the References, relations, credits etc taking a lot of space.  I think space could be saved by instead of having big green buttons +Add New Entry, + Add New Source, just having these as smaller + buttons next to the corresponding header.  I suggest using this as a general concept throughout the edit page like the below
![image](https://user-images.githubusercontent.com/3456833/48867980-4a76a680-ed95-11e8-82ce-fc137ee0f969.png)
also for adding authors at the top
![image](https://user-images.githubusercontent.com/3456833/48868034-7b56db80-ed95-11e8-922e-75dc5d914e2c.png)
4. I like the video suggestions to move the add files and add files from iRODS buttons up into the row of tools above the contents area.  This puts all the tools in one place.  Icons similar to a + for adding other content could be used making this similar in style to point 3 above.
5. I suggest putting the download as zipped bagit archive and and copy to irods functionality as buttons at the very top (perhaps below content types).  This would have the effect of hiding them in edit mode, but that is OK.  This would get them out of the space immediately below the content area where they were pushing apart content and additional resource level metadata. 
6. I think that information on storage.  "The size of this resource is 22 MB" should also be put in the top area.
7. It would be good if the sizes of individual files as well as dates they were added or last changed could be part of the interface too.
8.  I disagree with the video suggestion to get rid of some of the tools buttons (cut and paste).  Sometimes the right click cannot achieve what is needed.  E.g. there is no way with right click to paste (move) a file into the top level of the resource.  It is common on interfaces (see e.g. Word) to have cut and paste on buttons in the ribbon at the top, and in right click menus.  It is good to follow established design paradigms.
9.  Consider having quota holder management also part of the manage access control, rather than way down at the bottom of the resource under storage where it is hard to find.

**Comment by horsburgh** [comment]
I agree with @dtarb that we should limit scope of releases here. I think we should release what @Maurier has currently done with the resource landing page and then do these upgrades as part of another incremental release. Here's my thoughts on Dave's suggestions above after looking at the video Liza sent:

* While viewing the top block is not necessary in editing mode, we did have multiple discussions early in the project and agreed that page editing should be done in a view that looks as much like the regular display of the page as possible. I believe that this is a web best practice. The idea is that we don't want to present a completely different edit view to users who may get disoriented and not find what they wanted to edit. I personally don't find it to be an issue that the top panel is displayed in edit mode, but I guess we can hide those elements if needed.
* I also agree with @dtarb that we don't buy much space by collapsing the top panel. I don't like the button anyway, so I agree that we should just drop the button and make it show full size all of the time.
* Dave's suggestions for collapsing space in edit mode by using "add" buttons next to the labels rather than the full size buttons below each section seems reasonable and should be simple to implement. I don't think we really need to be overly sensitive about vertical spacing in edit mode because users only see that view when they are editing content. In regular view mode, those sections don't even appear on the page unless they have content.
* I like Liza's suggestions for moving the Download a Zipped Bagit Archive button up to the toolbar in the content area and moving the Add Files From iRODS server up to the bottom of of the text label that is now at the bottom of the file content area. 
* I *don't* think we should move the download buttons all the way up to the top of the page. Or, at least they should appear in both places if we do. These buttons are specifically about content files and should remain near the content files on the page.
* Putting resource size in the top header seems reasonable
* Displaying individual fie sizes should be done via a column in the file browser. We would have to check on whether the dates are even available from the backend for Mauriel to display. Putting all of this in the file list display would almost certainly require that we move the content level metadata to the bottom of the panel instead of the right side of the panel (because the tabular information about files would need horizontal room for display).
* We can't get rid of the cut and paste buttons on the toolbar because there are no right click options for doing this. I use these buttons all the time. Cut and paste have long been part of toolbars in many software packages.
* I don't feel strongly about quota information. I'm not sure it's even necessary to display this on the resource landing page, and moving the option to change quota holder to the manage access panel seems like a reasonable approach.

**Comment by horsburgh** [comment]
I believe this is complete and deployed to www with 1.19. Closing.
