### ISSUE TITLE
Resource Landing Page: File Metadata View

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2813]
Display of file-level metadata via the tabbed interface near the bottom of the resource landing page was problematic because it wasn't clear that users needed to click on the content file, then click on the "File Metadata" tab to view metadata for that file. This work will move file/aggregation-level metadata directly to the content viewer right next to the file view. This will make it much more clear that the metadata that appears on the right side of the dialog is associated with the file/aggregation selected on the left hand side.

This work will move everything from the "File Metadata" tab on the resource landing page to the right hand side of a new split view on the file browser interface under the Content area.  This includes both viewing and editing of file metadata.  Initially, none of the file metadata content will change, only the location of where it is viewed and edited.

![image](https://user-images.githubusercontent.com/3485902/42230682-d454665c-7ea6-11e8-8e4b-8e963c2c10d2.png)

The metadata content on the right side of the viewer is associated with whatever is selected on the left size of the viewer. 

Some considerations that might be nice:
* Make the vertical divider between the file view and metadata view draggable/resizable
* Include a toggle to collapse the metadata view so that only the file view is shown

**Comment by Maurier** [comment]
This has been implemented and can be tested at https://riverdev.hydroshare.org/

Further work is recommended for the metadata content to use the available space efficiently.

**Comment by engineSound** [comment]
Good work! I tested. The UI looks much better than before.

**Comment by Lizabrazil** [comment]
Reviewed the riverdev version, looking great. I have a few suggestions:
1. Right click on the unsupported file, the dropdown option currently includes Add Metadata and Set Content Type but all the content types are greyed out. Seems like Set Content Type should only appear if action can be taken. 
![image](https://user-images.githubusercontent.com/13852599/50358028-f42c8d00-0525-11e9-9c0d-7028cd2fc732.png)
2. Once the user clicks Add metadata, the right-side panel should automatically open the template to fill in the metadata
3. The Add Metadata green icon should also appear in the right side panel so it is less hidden behind a right click

**Comment by dtarb** [comment]
@Lizabrazil @horsburgh 
I wanted to comment on the first suggestion above and the philosophy of greying out or hiding functionality that is inactive.  I think we should throughout HydroShare adopt the style of greying out as opposed to hiding.  We should avoid going back and forth on this.  There is an example of where we went back and forth recently with the publish button.  Initially (months ago) it was inactive unless a resource was ready to be published.  Then at Mark Henderson's suggestion, it was hidden.  Then more recently at the request of users it was slated for reinstatement as greyed out, because users could not find how to publish.

I would submit that these greyed out right click menu items are similar.  They serve to educate users what functionality is there for appropriate file types, and hiding them thwarts this.  A user may load a file that they want to make a certain type of content type (e.g. geographic raster).  But perhaps they misname it (e.g. .tf rather than .tif).  The functionality would be greyed out, but upon correcting the naming, it would be enabled, and this would help a user get what they want, rather than think it is just not possible.

Also I want to note that my vote (preference) is for the set content type menu to be expanded into a longer single drop down menu.  I think a longer menu is better than one with a lot of nesting.

**Comment by horsburgh** [comment]
@dtarb - I generally agree with your comments here about disabling functionality rather than hiding it entirely. I actually think what @Maurier has implemented is a nice middle ground between what you and @Lizabrazil have suggested. 

I personally don't want to see a whole bunch of greyed out functionality every time I right click on something. At the same time, I understand your case where someone might misname a file and then go to set the content type and the option is not just greyed out, but hidden because the file extension is incorrect. Putting the content types in a fly-out menu keeps the main right-click context menu clean, but exposes all of the content types (with only the ones enabled for the specific file you right clicked on). It isn't a lot of nesting. It is one level on one item.

**Comment by Lizabrazil** [comment]
@dtarb @horsburgh I see your argument for the greyed out options appearing to be consistent, so I'm fine with keeping as is.

Do you agree with my #2 and #3 suggestions? These are coming directly from seeing users struggling to complete the task of adding file-metadata to unsupported file types. 

2. Once the user clicks Add metadata, the right-side panel should automatically open the template to fill in the metadata
3. By default when an unsupported file-type has been highlighted, the Add Metadata green icon should also appear in the right side panel so it is less hidden behind a right click.

**Comment by dtarb** [comment]
Yes I agree with items 2 and 3.

**Comment by horsburgh** [comment]
Agreed on items 2 and 3. @Maurier - can you have a look at these and get back to us on what it will take to add these to the upcoming release? Do we want to add them to this release, or do we want to make these a separate issue?

**Comment by Maurier** [comment]
I can get these items in for next release, but I will implement them after
the current code is merged into develop. This way we don't slow down the
code review.

**Comment by engineSound** [comment]
> Then more recently at the request of users it was slated for reinstatement as greyed out, because users could not find how to publish.
> 
> I would submit that these greyed out right click menu items are similar. They serve to educate users what functionality is there for appropriate file types, and hiding them thwarts this. A user may load a file that they want to make a certain type of content type (e.g. geographic raster).

@dtarb totally agreed with your points. They should be greyed out instead of hidden. I witnessed this type of scenarios before. People in their design teams chose to grey out inactive items with the exact same reason as you described.

**Comment by horsburgh** [comment]
Closing this as it is deployed with the 1.19 release. Created a new issue #3177 to handle the remaining items in the discussion above.
