### ISSUE TITLE
HTML Injection in Extended Metadata

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2820]
HTML tags are not immediately escaped for resource Extended Metadata.  Rather, the injected HTML is immediately rendered for the "Name" field.  The injected HTML is seemingly ignored for the "Value" field.  Refreshing the page results in an escaping of the HTML, and the HTML is no longer rendered.

[180709-test-files-004v.zip](https://github.com/hydroshare/hydroshare/files/2177831/180709-test-files-004v.zip)

**Comment by ndebuhr** [comment]
Note related ticket #2806 in that both deal with HTML inject.  Unlike this ticket, the HTML injection in #2806 persists beyond refresh.

**Comment by engineSound** [comment]
@Lizabrazil @Maurier @aphelionz Do we have a design spec to document the correct behavior?

**Comment by engineSound** [comment]
From specification perspective @Lizabrazil , the meta data name/value pair are intended for plain text by design. The dialog and table for extended metadata aren't robust to handle out-of-spec data input.   

One fix might be adding text tips to inform users only plain text is allowed. This clutters GUI and appears redundant. The users of hydroshare are the scientists and researchers who know well what this means to them. 

I am adding a fix to strip off HTML tags when saving the changes. As Neal pointed out, the value doesn't have the HTML tag issue, only the name. I will experiment a little bit more and create a PR.
