### ISSUE TITLE
Setting resource file type always allows feature and raster options

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#2878]
When setting the file type in a composite resource, `Geographic Raster` and `Geographic Feature` options are always enabled but fail. I propose that these options are only available at the file and folder level, not on zip directories.

**Comment by Castronova** [comment]
<img width="820" alt="screen shot 2018-08-16 at 3 37 13 pm" src="https://user-images.githubusercontent.com/4822372/44230847-55a0b180-a16a-11e8-9be6-4fe78b0b684c.png">

**Comment by aphelionz** [comment]
@horsburgh Can you recount your expectations around ZIP files in this context?

**Comment by aphelionz** [comment]
@datb suggests that the recognize action takes place upon unzip.

**Comment by horsburgh** [comment]
I think that automated detection of aggregations should happen on unzipping the file. I'm not 100% sure that's consistent with what is in the documents we wrote, but it makes sense since a ZIP file might contain anything. Actually, I think I remember having this conversation with Pabitra about automatic detection of aggregations upon upload and that we would NOT interrogate the contents of a zip file until and unless it was unzipped.
