### ISSUE TITLE
Different name for same userid

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2913]
https://beta.hydroshare.org/resource/68313c40c7ff48cd9e065ceada3c8426/

The author and owner are the same user.  Why the different names?

[004.zip](https://github.com/hydroshare/hydroshare/files/2421229/004.zip)

**Comment by horsburgh** [comment]
This is by design. When a resource is created, a snapshot of the user's profile information is created as the Author information. After initial creation, the author information should only be changed if an editor of the resource decides to do so. If Tony changed his profile information (i.e., his first name) after this resource was created, that change wouldn't be reflected in the Author information unless Tony specifically updates that for the resource. This is to enable the use case that a user publishes a resource with one set of Author information, but then changes affiliation later on - or to support Authors that are not HydroShare users. This is consistent with how academic journals handle author information.

Owners, on the other hand, must be HydroShare users and so owners are tied directly to the user's HydroShare profile.
