### ISSUE TITLE
Gotcha in time series content aggregation

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2942]
If I do the following:
1. Add a csv file to a composite resource [ODM2_One_Site_One_Series.csv](https://github.com/hydroshare/hydroshare/files/2485859/ODM2_One_Site_One_Series.zip)
2. In edit mode convert to time series.  This results in a time series content aggregation comprising two files, the original csv file and an ODM2.sqlite file.
3. Right click to remove content type.  This results in the two files as plain files in the resource.
4. Delete the .csv file (not strictly necessary).
5. Right click on ODM2.sqlite file and convert to time series.  
The following error results
![image](https://user-images.githubusercontent.com/3456833/47062491-9ed5a780-d193-11e8-94e7-3c9808a2df7e.png)

It seems that if I create an ODM2.sqlite file in HydroShare, I should be able to use it as the basis for creating a resource in HydroShare.  The rules for the metadata to expect coming in a .sqlite file are more stringent than coming from a .csv file.  This may be a "feature" or a "bug"

@horsburgh please evaluate.

**Comment by pkdash** [comment]
@dtarb When a csv file is uploaded, system creates an ODM2 SQLite file with mostly empty that it expects the user to populate. So if the user tries to create a time series content type from such a SQLite file it is expected to fail. The same failure happens when a user uploads a SQLite file that does not meet the minimum data it expects in that file.

**Comment by horsburgh** [comment]
As @pkdash describes - the SQLite file is blank and will fail if you remove the aggregation and then try to recreate it from the SQLite file. The content of the SQLite file is not actually created until the minimum time series metadata have been entered - even though the blank SQLite database is created in the folder. The uploaded CSV file contains no metadata.

@pkdash - would it be possible to delay the initial creation of the SQLite file until the minimum metadata requirements have been met by the user? In other words, the folder would only contain the CSV file until the minimum metadata requirements have been met and then the SQLite file would be generated.

@dtarb - the issue here is that we are allowing users to create time series content, which has a bunch of required metadata - from a CSV file that contains no metadata. We could also decide to force the user to input all required metadata when they upload a CSV file before the resource is created. This option would require more effort from users up front, but would prevent creation of resources that are in this "interim" state.

**Comment by pkdash** [comment]
We may consider system deleting the SQLite file if it lacks minimum data when the user removes the time series content type.

**Comment by horsburgh** [comment]
@pkdash - That would be an easier fix. We would obviously only want to do that only for SQLite files that we know were created by the system.

**Comment by dtarb** [comment]
I am happy for you guys to do what you think is best.  Certainly making public or publication of resources should not be allowed for resources holding incomplete .sqlite files.  However working with .sqlite files that are incomplete should be flexible as the HS interface is actually quite an effective interface for adding the needed metadata.  The question is, if a user has an incomplete .sqlite file, should they be able to add it to HydroShare and then use the HS interface to fill in the missing data.  This may actually be the case for some .sqlite files that come out of the CUAHSI data client that Dan tried to demo today and were non compliant.

This does not need to be a show stopper on 1.16 deploy (I deliberately did not put on 1.16 milestone), as it is probably inherited from similar behavior in current time series file type functionality, but does warrant thinking through.

**Comment by dtarb** [comment]
@horsburgh Please comment or follow up as needed.

**Comment by horsburgh** [comment]
To resolve this issue, I suggest a check on the SQLite file when the Time Series content type is removed to see if the SQLite file would validate as a Time Series content type aggregation. If the answer is yes, remove the content type aggregation as the user has requested. If the answer is no, we should alert the user that they are removing the Time Series content type aggregation and that their SQLite file lacks the necessary metadata for that content type aggregation to be added back. The message should be something like this:

> You have chosen to remove the Time Series Content Type from this file. Your file currently lacks the necessary metadata to convert it back to a Time Series Content Type aggregation. Are you sure you want to remove the content type from this file?

I don't think we should delete the SQLite file if it fails the content type validation check because the user may have a good reason for wanting to remove the aggregation and keep the file.

**Comment by pkdash** [comment]
@horsburgh I am working on this issue. I came across another related issue. After removing the timeseries content type (which was originally created from an uploaded CSV file), if the user tries to again create a timeseries aggregation from the  CSV file, it will fail since there is already a SQLite file in the same directory.

![image](https://user-images.githubusercontent.com/2523434/133504970-7570f9ff-d6df-47f7-b781-e6c8998d29ae.png)

I think may be we should consider deleting the SQLite file at the time of content type removal, if the SQLite file was system created - that should resolve the original issue as well this related issue.

**Comment by horsburgh** [comment]
@pkdash - If there's a way to know whether the SQLite file was created by the system, I think your suggestion works here. Is this only an issue if the SQLite file and the CSV file share the same name? In other words - how does adding the content type after removing it know to fail if there is an existing SQLite file? Is it based on file name?

I think there needs to be a warning (perhaps there is already?) when the user chooses to remove the content type aggregation that any metadata they have added to the aggregation will be destroyed.

**Comment by pkdash** [comment]
@horsburgh This related issue is not due to the shared file name for CSV and SQLite. Since there is already a SQLIte.sqlite file created by the system when originally the timeseries aggregation was created, at the time of recreation of the content type from CSV system tries to create another SQLite.sqlite file in the same directory which obviously fails. 

At the time of content type removal we would know if the SQLite file was created by the system or not. If the content type contains the CSV file then the SQLite file is system created.

**Comment by horsburgh** [comment]
@pkdash - OK. I think your approach seems fine. My concern about the SQLite file was that if there are other SQLite files hanging about they might get deleted by mistake, but from your explanation that would not be an issue. The message on the "Remove content type" dialog is what I wanted, so I think that covers my concerns.

**Comment by pkdash** [comment]
@horsburgh This has been fixed as part of next release 1.48. You can test it on beta.

**Comment by pkdash** [comment]
This has been fixed as per testing on prod.
