### ISSUE TITLE
Evolving model resources with new composite

### ISSUE THREAD

**Issue by jsadler2** [hydroshare/hydroshare#2959]
A subticket of https://github.com/hydroshare/hydroshare/issues/2858.
We need to evolve the Model Instance and Model Program resource types to conform with the new composite resource supporting content types. The main difference will that when the "executed_by" relation will need to be made at the *content type* level instead at the *resource* level. I've tried to illustrate this difference in the diagrams below.

**Comment by jsadler2** [comment]
![evolving mp 2fmi](https://user-images.githubusercontent.com/6943441/47435439-a0463780-d772-11e8-9cb8-31ef2dec729b.png)

**Comment by jsadler2** [comment]
![evolving mp 2fmi 1](https://user-images.githubusercontent.com/6943441/47435458-a9370900-d772-11e8-9f20-27e4013b1c05.png)

**Comment by jsadler2** [comment]
![evolving mp 2fmi 2](https://user-images.githubusercontent.com/6943441/47435473-af2cea00-d772-11e8-98b2-e45af5c607ef.png)

**Comment by jsadler2** [comment]
By having the "executed_by" relation at the *content type* level, we'd be supporting both Case 1 and Case 2 above.

**Comment by jsadler2** [comment]
In looking over the code for the other file types, I've come across a couple questions. 

1. I've noticed that they all have a "*Mixin" that the filetype metadata class inherits from. For example the `TimeSeriesFileMetadata` class inherits from the `TimeSeriesMetadataMixin`. Do I need to make a `ModelInstanceMetadataMixin` class in the `hs_model_instance/models.py`? And if so, is there a specific structure that it has to follow? I can pattern it off of what others have done, but if there's some spec that I could look at, that would help.
2. Does the `*Metadata` class in the file_types model replace the original `*Metadata` classes? For example, does the `TimeSeriesFileMetadata` class in `hs_filetypes/models/timeseries.py` replace `hs_app_timeseries/models.py`?

@pkdash, do you think you could help me out with these questions? Or is there someone better? I just assumed you Pabitra, cuz I am thinking you have done all the file_type stuff, but maybe I'm wrong.

**Comment by dtarb** [comment]
@jsadler2 I am happy to have @pkdash help with this.  I think you need a design document that writes out the strategy for this work.  I do not want writing the document to be onerous or to cause delay.  Rather I would like it to be a device for you to, at a conceptual planning level, work through the details before getting into code so that the coding is done with a good direction and purpose.  Look at https://docs.google.com/document/d/1Hb18tUZyG7PHSwrclRHOmcYcEJvD0i9dQSmNdVckBUc/edit for where @horsburgh and I worked on overall design for the composite resource, though I do not think what you write needs to be as long as this one.  In fact, I hope it is a lot shorter.  Once you have made a start on this, I think it would be good to have @pkdash @horsburgh and @goodalljl comment on it.  While one strategy is to just make these resources new content aggregation types with very few changes, I would encourage you to review the experience we have had so far with model resources and take this as an opportunity to identify where there may have been shortcomings that can be addressed.  From my perspective I worry a bit about having too many specific metadata requirements that may not be natural for all models, and would encourage you (but only as a preliminary suggestion - you are empowered to work out the details) to consider simplification and using extended metadata rather than content aggregation specific metadata to simplify where possible.

**Comment by jsadler2** [comment]
A design document sounds like a good idea to me, @dtarb. Here's a link to the doc where I'll be working on that: https://docs.google.com/document/d/1DZgjLzhe40JkI9EA8OrTCDf1uFAnsSAQyqJ0rxkhBc8/edit. Initially, I had thought of just translating all the current functionality as is to file types. I think your right though, that we need to think about whether that is the best thing and use this as an opportunity to possibly make improvements/simplifications. I will give this some thought and get input from Mohamed and others in the modeling group. When our ideas are in the doc, I'll plan on reaching out to Pabitra, Jeff, and Jon as you suggested.

**Comment by pkdash** [comment]
@jsadler2 

> I've noticed that they all have a "*Mixin" that the filetype metadata class inherits from. For example the TimeSeriesFileMetadata class inherits from the TimeSeriesMetadataMixin. Do I need to make a ModelInstanceMetadataMixin class in the hs_model_instance/models.py? And if so, is there a specific structure that it has to follow? I can pattern it off of what others have done, but if there's some spec that I could look at, that would help.

The purpose of all the "Mixin" classes related to metadata is to avoid duplicate code. Since the resource specific metadata and the corresponding file type/aggregation metadata are exactly the same, such a "Mixin" class allows us to define metadata elements once which can then be used both for a resource type as well as a file type. Once we are done with migrating all the non-composite resources to composite resources, we won't need these metadata mixin classes. If you want to store the metadata in the same format both for the model instance file type and model instance resource type then you would need a 'mixin' metadata class. However, you may want to consider storing metadata for model instance file type as a JSON document using the JSON model field (https://docs.djangoproject.com/en/1.11/ref/contrib/postgres/fields/#jsonfield) which may help in creating different model instance file types (e.g MODFLOW, SWAT ). If you decide to use JSONField for model instance file type then you don't need to create a 'mixin' class.   

> Does the *Metadata class in the file_types model replace the original *Metadata classes? For example, does the TimeSeriesFileMetadata class in hs_filetypes/models/timeseries.py replace hs_app_timeseries/models.py?

It doesn't replace. However, once we migrate existing time series resources to composite resources, then we should be able remove hs_app_timeseries app.

**Comment by jsadler2** [comment]
As I've been doing this redesign, there are a few changes to the DB for Model Instance and Model Program that I suggest. Table 1 and 2 (these are from the design document). 
![image](https://user-images.githubusercontent.com/6943441/61655979-492fad80-ac85-11e9-9fef-9308a0898ff6.png)

This may (probably will) cause some headache when converting existing MP and MI resources. For example, what if someone put in something that is not a URL in the "modelWebsite" field. How do we treat that?

**Comment by pkdash** [comment]
@jsadler2 

> what if someone put in something that is not a URL in the modelWebsite field of a MP. How do we treat that if the DB field now is a URLField?

If you make this change, I think the resulting migration file will fail to migrate data for the modelWebsite field if the data does not look like url.

**Comment by imanmaghami** [comment]
I believe this issue should be closed as we implemented the changes discussed above in release 1.45. 

One considerable change from the originally proposed design is that in the deployed design, we only let model instance aggregation(s) to be linked to a model program aggregation if only if they live in the same composite resource.
