### ISSUE TITLE
Folder zipping not allowed for folder containing aggregation

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2979]
If I attempt to zip a folder that contains an aggregation, I get the following error message
![image](https://user-images.githubusercontent.com/3456833/47876078-f4d65c00-dddd-11e8-8d49-4f8328ce88f5.png)

Is this by design?  Why?

**Comment by dtarb** [comment]
@horsburgh @pkdash

**Comment by pkdash** [comment]
@dtarb This is by design for now. The reason I put such a restriction is that I did not know what should happen when unzipping such a zip file. If the folder contains an aggregation, a default zip functionality would zip the two aggregation related xml files along with other resource files inside the folder. That means the default unzip action on such a zip file would make the two xml files as resource files and user would be able to see those xml files in UI.

**Comment by dtarb** [comment]
@horsburgh can you please as part of landing pages categories lead discussion to decide what functionality should be related to zipping and unzipping of files in aggregations and what should be expected with auto aggregation or not behavior.
