### ISSUE TITLE
Unzip of bag from iRODS results unzipped files not being added to Django

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2984]
If I copy a bag from iRODS into a resource and try to unzip it, it is empty.  Following is the sequence to reproduce
1. Create a composite resource with "logan.tif" (from disk)
2. Copy Resource Bag to iRODS User Zone.
3. In the same resource log in to iRODS to add files from an iRODS server and log in to the usersdev.hydroshare.org server (testing on beta)
5. Add files from iRODS and select the zip file created at step 2.
6. Unzip here on the zip file.

The result is a set of bag file folders that in Django appear to have no files in them.  However if the resource bag is downloaded the files are in the bag, indicating that this seems to be a Django/iRODs sync issue.

**Comment by dtarb** [comment]
This is still a problem.  I just did the sequence above with the logan.tif file in the following zip file.
[logan.zip](https://github.com/hydroshare/hydroshare/files/3518564/logan.zip)

Here is what results when the bag is unzipped.
![image](https://user-images.githubusercontent.com/3456833/63315082-1fd76100-c2c7-11e9-8c8a-de661a481c01.png)

**Comment by hyi** [comment]
@dtarb I have verified this issue still occurs on beta with upgraded iRODS, but this issue is not caused by iRODS, but rather by Django aggregation backend or frontend display. This problem will not occur if you delete the initial logan aggregation from the composite resource. Alternatively, if you create a new composite resource without adding the "logan.tif" into the resource, then add the same bag zip file from your userzone, do "unzip here" on the bag zip file, then the content directory will not be empty but contain the logan tif and vrt files correctly. As a result, I am removing file system and irods labels from this issue since it is a data display related issue that is likely caused by Django aggregation backend logic.

**Comment by dtarb** [comment]
@hyi can you work with whoever is involved in the Django aggregation logic (@sblack-usu perhaps) to get this fixed, or give it the right label to get it fixed (rather than worrying too much whether it needs an iRODS and System label or not).

**Comment by Castronova** [comment]
This has been resolved.
