### ISSUE TITLE
Composite Res Type auto file-type detection -- an option to avoid creating new folder for each file?

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#3023]
I have multiple netcdf files.  After uploading to HS, Composite Res is able to successfully detect the file-type, extract metadata, and wrap each netcdf with its metadata xml files in one new folder. The res bag also reflects this folder structure, which is working as designed.  

But when we share some NWM netcdf files on HS, we want to preserve the original folder structure (multiple netcdf files in one folder as they collectively compose time series data for one region). I know I can zip them up and put the zip file on HS, but this would prevent the file-type detection and metadata harvesting feature.

Can we add a new option to avoid creating new folder for each file?

![image](https://user-images.githubusercontent.com/10070599/48855279-feb20600-ed70-11e8-951a-0da817ac165a.png)
![image](https://user-images.githubusercontent.com/10070599/48855739-ec849780-ed71-11e8-80a1-91a375287fc2.png)

**Comment by dtarb** [comment]
@zhiyuli This is a fairly deep question/request.  I'll put this for discussion among the resource model team that @horsburgh leads.  

Here are some options that could solve this for you right now.
1. Put the multidimensional content aggregation objects in their own folder.  
```
TopFolder->
   Multidimensional content folder 1 ->
      file1.nc
      file1_header_info.txt
      file1_meta.xml (hidden in UI but in bag)
      file1_resmap.xml (hidden in UI but in bag)
   Multidimensional content folder 2 ->
      file2.nc
      file2_header_info.txt
      file2_meta.xml (hidden in UI but in bag)
      file2_resmap.xml (hidden in UI but in bag)
```
With this option you can add metadata to the top folder once the file set work that is near completion gets deployed.  If you do this you will get in the bag at the top folder level
```
    TopFolder_meta.xml
    TopFolder_resmap.xml
```

2. Put the files in a folder, but not as multidimensional types.

```
Folder->
    file1.nc
    file2.nc
    Folder_meta.xml (hidden in UI but in bag)
    Folder_resmap.xml (hidden in UI but in bag)
```
This option would exploit the file set content aggregation (soon to be deployed). You would need to set the metadata manually rather than use the automatic harvest.  But you do not need zipping for this. 

I suggest you see if either of these would work for you, rather than trying to change the data model.

**Comment by martinseul** [comment]
Fixed, closing
