### ISSUE TITLE
Discover not working in 1.17

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3029]
Resource discovery is not working following the 1.17 deploy today.
I have the following public collection resource https://www.hydroshare.org/resource/2adee16a5b0d4df0b5e687046be8515e/
I used to be able to find it (in demos) using "logan" as keyword (which is part of the title) and filter by owner on my name.  However now it is not returned.  
Further a search on the full title either out or in quotes "Logan River Geography" fails to return this resource.

This worked prior to the 1.17 deploy.  Concern this is related to SOLR re indexing done on deploy today.  But that was 8+ hours ago.
@alvacouch @phuongdm @sblack-usu

**Comment by sblack-usu** [comment]
@alvacouch - Is this something you can check easily?  I imagine there are tools to check what indexes exist for a resource directly from solr, I'm just currently not familiar with any.

**Comment by alvacouch** [comment]
@sblack-usu @dtarb I have tools in the management commands that check SOLR indexing. The likelihood -- however -- is that some indexing content is now not accepted by SOLR for unknown reasons. I need to check the logs on www.hydroshare.org. I have privileges to do so.

**Comment by alvacouch** [comment]
Notes for others studying this problem at this moment in time: 
* active worker www2-hydroshare.edc.renci.org
* docker container for solr instance: db1-hydroshare.edc.renci.org

**Comment by alvacouch** [comment]
@phuongdm @dtarb @martinseul 
I've studied logs on the active worker as documented above. The following entries are cause for concern: 
```
[29/Nov/2018 15:25:37] ERROR [django.security.DisallowedHost:80] Invalid HTTP_HOST header: '152.54.2.89'. You may need to add u'152.54.2.89' to ALLOWED_HOSTS.
```
Investigating further, 
```
dig -x 152.54.2.89
...
;; ANSWER SECTION:
89.2.54.152.in-addr.arpa. 3600  IN      PTR     nginx1.hydroshare.org.
```
Similarly
```
[29/Nov/2018 15:25:37] ERROR [django.request:135] Internal Server Error: /admin/assets/js/views/login.js
```
I am not seeing SOLR problems. I am seeing problems at other levels.

**Comment by alvacouch** [comment]
SOLR errors from a day ago might be relevant: 

```
[27/Nov/2018 14:19:03] DEBUG [requests.packages.urllib3.connectionpool:387] "GET /solr/select/?q=replaced%3A%28false%29&fq=django_ct%3A%28hs_core.baseresource%29&rows=1&facet.field=subject_exact&facet.field=contributor_exact&facet.field=creator_exact&facet.field=owner_exact&facet.field=content_type_exact&facet.field=availability_exact&wt=json&start=0&fl=%2A+score&facet=on HTTP/1.1" 404 244
[27/Nov/2018 14:19:03] INFO [pysolr:386] Finished 'http://db1-hydroshare.edc.renci.org:8983/solr/select/?q=replaced%3A%28false%29&fq=django_ct%3A%28hs_core.baseresource%29&rows=1&facet.field=subject_exact&facet.field=contributor_exact&facet.field=creator_exact&facet.field=owner_exact&facet.field=content_type_exact&facet.field=availability_exact&wt=json&start=0&fl=%2A+score&facet=on' (get) with body '' in 0.008 seconds.
[27/Nov/2018 14:19:03] ERROR [pysolr:393] Solr responded with an error (HTTP 404): [Reason: Error 404 Not Found]
[27/Nov/2018 14:19:03] ERROR [haystack:139] Failed to query Solr using 'replaced:(false)': Solr responded with an error (HTTP 404): [Reason: Error 404 Not Found]
[27/Nov/2018 14:19:03] ERROR [haystack:139] Failed to query Solr using 'replaced:(false)': Solr responded with an error (HTTP 404): [Reason: Error 404 Not Found]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/haystack/backends/solr_backend.py", line 134, in search
    raw_results = self.conn.search(query_string, **search_kwargs)
  File "/usr/local/lib/python2.7/site-packages/pysolr.py", line 699, in search
    response = self._select(params)
  File "/usr/local/lib/python2.7/site-packages/pysolr.py", line 406, in _select
    return self._send_request('get', path)
  File "/usr/local/lib/python2.7/site-packages/pysolr.py", line 394, in _send_request
    raise SolrError(error_message % (resp.status_code, solr_message))
SolrError: Solr responded with an error (HTTP 404): [Reason: Error 404 Not Found]
```

This says that the `replaced` keyword isn't being indexed in SOLR. So the index is wrong.

**Comment by alvacouch** [comment]
@dtarb @martinseul @sblack-usu 
See notes above for possible cause of missing discovery records. This is likely a configuration file botch. I am not seeing ingestion errors. What I am seeing is that the keyword `replaced` is not valid in SOLR, and I seem to remember it is the last keyword.  So, it is not being ingested (without errors), and the discover page is asking for it. 

I am out of time for today.

**Comment by dtarb** [comment]
Here are additional examples of discover problems in the hopes that they help get to the problem.  Some of these problems are also occurring on beta, which means things could be experimented with there to fix them.

On www (at 5:00 MT 12/1/18).  Search on Logan.  Filter by Author Tarboton, David in facet on left.  5 resources are discovered.  However the following that I know that I have, and that all have Logan as the first word in the title are not found:
https://www.hydroshare.org/resource/2adee16a5b0d4df0b5e687046be8515e/  (collection)
Members of the collection
https://www.hydroshare.org/resource/93f49ab913fd4c639c98ab4a070d20e0/  (geographic feature)
https://www.hydroshare.org/resource/877bf9ed9e66468cadddb229838a9ced/ (raster)
https://www.hydroshare.org/resource/b7822782896143ca8712395f6814c44b/ (raster)
The last two are actually published.

There is also a copy of the collection above made by Liza that does not show up.
https://www.hydroshare.org/resource/dc8a31ef4741441ea5e7e837492fc3aa/  (collection owned by Liza)

On Beta (at 5:00 MT 12/1/18) Search on Logan.  Filter by Author Tarboton, David in facet on left.  4 resources are indicated in the facet, but 5 are discovered.  

Again the collection that I created is not discovered.
https://beta.hydroshare.org/resource/2adee16a5b0d4df0b5e687046be8515e/  (collection)

And the following three resources that are members of the collection and have Logan in their title as the first word are not discovered
https://beta.hydroshare.org/resource/93f49ab913fd4c639c98ab4a070d20e0/  (geographic feature)
https://beta.hydroshare.org/resource/877bf9ed9e66468cadddb229838a9ced/ (Raster)
https://beta.hydroshare.org/resource/b7822782896143ca8712395f6814c44b/  (Raster)

But the collection that is owned by Liza that is the copy of the collection above is discovered.
https://beta.hydroshare.org/resource/dc8a31ef4741441ea5e7e837492fc3aa/  
This resource was not discovered on www.

**Comment by alvacouch** [comment]
@dtarb @martinseul @sblack-usu I have studied what is happening on www in detail, using the existing SOLR management commands installed on www, notably, `solr_queries`. This management command factors out the user interface and provides output from SOLR queries in text mode. From this, I conclude that: 

1.	**The records in question are not in SOLR.** I have used my SOLR debugging management commands and factored out the user interface. Search commands are being processed correctly and the records are not being returned. They’re not there.  
2.	This means – since ingestion has been run and no errors have been encountered – that these records were either rejected from the SOLR database for some reason, or overwritten for some reason. 
3.	Since SOLR itself shows no errors in ingestion, my best guess is that **ingestion is crashing on the Django side for some reason.** 
4.	It is also possible – though unlikely – that **the new SOLR is using the wrong primary key** for its database and these records are getting written over during ingestion.  

Either of these causes is consistent with contents of current log files. 

My next step is to test whether it's (3) or (4). The best way to do this is to write a management command that forces SOLR ingestion of a resource. This will both expose any Django execution errors and potentially rule out -- or validate -- theory (3).

**Comment by alvacouch** [comment]
@dtarb @sblack-usu @martinseul Update: Was able to run main harvest routines for affected resources (without calling SOLR) on www, using short management command `solr_test` that I added. So, harvesting is not crashing when building the SOLR record.

**Comment by alvacouch** [comment]
Update: contacted SOLR console via RENCI VPN and confirmed that records are simply not present in SOLR. SOLR console shows two "reload errors" on 11/27 that might be related. 

11‎/‎27‎/‎2018‎ ‎8‎:‎31‎:‎31‎ ‎AM | ERROR false |   | RequestHandlerBase | org.apache.solr.common.SolrException: Error handling 'reload' action
-- | -- | -- | -- | --
‎11‎/‎27‎/‎2018‎ ‎8‎:‎31‎:‎31‎ ‎AM | ERROR false |   | HttpSolrCall | null:org.apache.solr.common.SolrException: Error handling 'reload' action

**Comment by alvacouch** [comment]
@dtarb @martinseul @sblack-usu Status report
I have not determined the cause of the missing records. I have determined, however, what the cause is not: 

1. Indexing is proceeding properly with proper primary keys. 
2. Some index records are being rejected and do not appear in SOLR. Others are normal. 
3. This seems not to be an error, but instead, a policy decision in SOLR. It's not being flagged as an error. 
4. Thus, there is some requirement in SOLR that is not being met for these records. 
5. Accordingly, there is some requirement in the Haystack configuration that is false, and needs to be corrected. 
6. Accordingly, this is due to some change either in SOLR or in Haystack in the current versions. **Something in the configuration that did not lead to record rejection under SOLR 4 is leading to record rejection in SOLR 6.** 


I still have no idea what this configuration problem actually is.

**Comment by alvacouch** [comment]
@dtarb @sblack-usu @martinseul 
Upon careful thought, the most plausible theory that I can think of is that faceted fields might be required to have a value now. In the prior implementation, it was possible for their values to be NONE. 
Will test this theory now.

**Comment by alvacouch** [comment]
@dtarb @sblack-usu @martinseul 
cuahsi-dev-1:hydroshare/hs_core/management/commands/solr_recover.py now has the code to regenerate indexes for all resources. It is running on cuahsi-dev-1 on all resources. So far, prognosis is that this will work for the affected resources. It may also crash on a specific resource, locating the problem. It will take about 1 hour to run.

**Comment by alvacouch** [comment]
See PR #3033 for a Band-Aid fix.

**Comment by alvacouch** [comment]
@dtarb @martinseul @sblack-usu  My evidence so far is that the harvesting of resources occurs too soon in the build phase and -- specifically -- indexing records are lost.

**Comment by alvacouch** [comment]
@dtarb @sblack-usu @martinseul I also noticed during this analysis that certain parts of `CompositeResource` -- that are only visible if one casts the resource to the type `CompositeResource` -- are missing from the harvest, because the harvest currently looks at everything as if it were a `BaseResource`.

**Comment by dtarb** [comment]
I assume this does not relate to the fix up script you wrote and that we should still deploy the fix up script #3033

**Comment by dtarb** [comment]
Tested on www after fix up script deploy.

**Comment by alvacouch** [comment]
@dtarb Yes, the bug I found means that I need to harvest composite resources slightly differently from other types. It is not related to the fix.

**Comment by pkdash** [comment]
@alvacouch Would like to know one example of what's not getting harvested for Composite Resource?
