### ISSUE TITLE
Same file name handling

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#3050]
Upload multiple files, with different contents but the same name.  The interface makes it ook likt his is totally fine, with the "Add your files" showing different entries, with the correct file sizes, etc..  However, the files are then later rejected during resource creation.  

Two things which would seemingly really improve UX here:
1) Let users know about the duplication issue when they are uploading files.  The error arising after all the uploads are done could be annoying to users - particularly if they do a lot of file uploading work.
2) Enable file renaming in the upload interface.  It seems likely that users may be uploading the same named file (e.g. results.csv) from multiple project directories.  Enabling on renaming while uploading would circumvent the need for users to modify their own file system to accomodate HydroShare application upload needs.

[005.zip](https://github.com/hydroshare/hydroshare/files/2683201/005.zip)

**Comment by keatingr** [comment]
Attached zip file expired token or something.

**Comment by dtarb** [comment]
This whole create resource page is slated to go away with resource creation resulting in opening an empty landing page in edit mode for adding content, so I would not put high priority on working on this.

**Comment by keatingr** [comment]
Understood. I'll review with folks and re-write, reprioritize or remove. Right now I don't fully understand the issue or the upcoming change so will need a quick chat.

**Comment by dtarb** [comment]
This issue is mentioned briefly in #2975 and perhaps other issues, but the real impetus for removing the create resource page is the Olin report https://www.hydroshare.org/resource/9e888ababe6648ad95d07b6ec5ed7cb0/.  The section "Creating a resource and editing" that is on PDF page 134 of the concatenated single file PDF addresses this most comprehensively making the case for eliminating the intermediate create resource page.  The resource landing page team that @horsburgh is leading is coordinating this work.

**Comment by cuahsimarko** [comment]
@martinseul I think this can be closed after a second opinion.

**Comment by martinseul** [comment]
@ndebuhr. This seems to be fixed or NA as the implementation has changed. Closing, please reopen if still needed
