### ISSUE TITLE
iRODS does not properly connect to 3rd party iRODS system

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3069]
When I attempt to add a file from a 3rd party iRODS system (iplant) I do not get a file listing, so am unable to add files.  

See below
On the left is the listing of files in the HydroShare add from iRODS dialog.
On the right is the listing of my files in iplant at the same location
![image](https://user-images.githubusercontent.com/3456833/50384776-cad74280-0686-11e9-94d6-0400ecec176c.png)

This used to work so is a regression.

**Comment by hyi** [comment]
@dtarb I tested it out and tried my two iRODS accounts on two totally separate iRODS servers set up for other projects, and files are listed properly in iRODS browser. Can you please test it again and see if you still run into issues with your iplant iRODS account?

**Comment by dtarb** [comment]
I still have a problem with iplant iRODS.

**Comment by hyi** [comment]
@dtarb After much debugging and trial and error with this, I got your iplant iRODS file browsing to work as expected on park.hydroshare.org which I deployed for @horsburgh to test the fix for this issue #2276. However, I applied the same procedure on the new beta, but your iplant iRODS file browsing does not work on the new beta. I may need to restart the new beta worker, but given that people are testing things out on beta for release 1.19 candidate, I don't want to introduce server restart to disrupt people's testing. Here is a summary of what I found with your iplant irods account:
-  You iplant irods file browsing works just fine in my local development environment with the same code base I deployed to park. However, it did not work on park initially. The error we got on park is ```unclosed token``` error when parsing xml element tree from python irods client which is used by HydroShare iRODS browser for file browsing. What I did to fix this issue on park was to go to the docker container, uninstalled the old python irods client version we are using in HydroShare, and installed the latest version of python irods client. This fixed the issue on park, so it looks like the latest version of python irods client fixed this issue on park. However, I upgraded python irods client version on new beta active worker as well, and it does not seem to work there on beta although it works on park. That said, the old python irods client works in my local development environment regardless.

The conclusion we can get is that the error comes from python irods client, and upgrading python irods client version appears to fix the issue on park. I can create a PR to update python irods client version to the latest version for HydroShare base image, but beyond that, I don't think I should spend any more time on this. Let me know your thoughts.

**Comment by dtarb** [comment]
Agreed.

**Comment by hyi** [comment]
@dtarb I checked with @sblack-usu that the updated hs docker base image that includes my updated irods python client library version has been included in the latest deploy, so can you check on www or beta to see whether this issue has been resolved? I cannot check it myself since the password I have does not work at more.

**Comment by dtarb** [comment]
I did not change the password, but I will check.

**Comment by dtarb** [comment]
Thanks @hyi.  I verified that this is fixed on beta.  I'll verify on www once 1.20 deploys then close.

**Comment by dtarb** [comment]
Fixed with 1.20.1
