### ISSUE TITLE
User page redirection - poor handling for missing users

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#3077]
Spam resource https://www.hydroshare.org/resource/bca4099bfffa4b659448b13404fe3c8b/ user link redirects to https://www.hydroshare.org/user/2226/.  Presumably we deleted that user - is there a better way we can handle the old user page links, than just a generic error?

**Comment by dtarb** [comment]
Interesting.  I thought that when a user was deleted that the resources they owned were deleted too.  I am curious as to how this came about.

I just went to beta where I am comfortable experimenting as admin and deleted the user Jerry Matt responsible for a number of the spam resources, and the resources appear to have been deleted too.

**Comment by dtarb** [comment]
I figured out what is going on with user 2226.  The account was not deleted, it was just made inactive.  It is still there if you look in the Mezzanine listing of users.  This has a positive side effect that the email address is used, so blocked from trying to create an account again.  I am not sure if this is totally fool proof.  If the user attempts to resend the link to activate their account they may still get in.  @sblack-usu could confirm whether this is the case.  

But just deactivating a user does not delete their resources.  If you delete the account (from Mezzanine listing of users), the resources are deleted too.  I just tested this on beta.  I do not know if there are consequences for the SOLR discovery database, of such deletions.  @alvacouch should comment.

I'll leave it to CUAHSI (@Lizabrazil) to approve and coordinate deletions on www.

**Comment by eclark-cuahsi** [comment]
@Castronova does this fall under Pages and General HS Components? If so can you please add the Pages label and review the Bug/Cosmetic labeling? I don't think an issue can be both a bug and a cosmetic per our discussions.

**Comment by devincowan** [comment]
@martinseul do we want to delete resources when a user account is made inactive (but not deleted)?
As it stands now, anyone attempting to access a resource that is owned by an inactive user sees our `PermissionDenied` page (below). This is true even for public and even published resources. You can see that the "owners" don't populate even though the owner still technically exists...

![image](https://user-images.githubusercontent.com/17934193/156783104-3a5d09dd-4fb3-4bc4-ac36-eb2ca735fe85.png)

As I see it, our options are to delete or inactivate resources when their owners are inactivated, or to allow public resources with inactive owners to still be viewed and discovered by getting rid of this PermissionDenied page... Other thoughts?

**Comment by devincowan** [comment]
@dtarb current production shows the following when someone navigates to a resource (be it private, discoverable, or public, or even published) that is owned by a user that has been inactivated:
![image](https://user-images.githubusercontent.com/17934193/157540774-32b52db8-22f2-488e-940d-0af334771e24.png)

I have pushed some proposed changes so that the page no longer shows a blank "owners" field and so that it no longer says all inactivated resources are private:
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/17934193/157541089-5d32647a-07c6-4aaa-8f5b-06563e62bf9e.png">

Does that seem appropriate or is there a preferred behavior?

**Comment by dtarb** [comment]
@devincowan In general, accounts for SPAM users should be deleted, not made inactive.  Inactive accounts can be re-activated by the user through the password reset process but a deleted account is gone.  When an account is deleted, all its associated resources are deleted, resolving the problem as to what to do with them.  This is the preferred action for accounts we have definitively determined to be SPAM.  The arguments against deleting are that this is a non recoverable action, and that the user can then use the same email address to create an account again, while retaining an inactive account blocks use of the email address for another account.  The question of non recoverability can be addressed with backups, we should backup and retain offline resources of accounts being deleted.  The question of email blocking is weak because the user can (if they know how) re-activate the account and it would be better to maintain a blacklist of email addresses we do not want to let create accounts.

There is no concept of a resource being inactive.  Avoid words like “resource is not currently active”.  User accounts for users who own resources are what can be inactive.

For resources that do not have an owner that is an active user (note that if there are multiple owners any active owner should be shown in the list of owners and inactive owners just not shown)
If resource is private and the accessing user is anonymous (authenticated user not logged in)  or does not have permissions
-	Show the resource title
-	For owner write: This resource does not have an owner who is an active HydroShare user.  Contact CUAHSI ([help@cuahsi.org](mailto:help@cuahsi.org)) to determine if accessing this resource is possible.
If a resource is discoverable show the resource landing page without content files, but for Owners show a similar statement to the above:  This resource does not have an owner who is an active HydroShare user.  Contact CUAHSI ([help@cuahsi.org](mailto:help@cuahsi.org)) to determine if accessing this resource is possible.

If a resource is public or published, show the full resource landing page.  In the owners field write: This resource does not have an owner who is an active HydroShare user.  Contact CUAHSI ([help@cuahsi.org](mailto:help@cuahsi.org)) for information on this resource.

An objection to this solution may be that a practice has been to deactivate and not delete SPAM users, and this would facilitate access to the SPAM resources they have added to HydroShare.  For me the correct solution is deleting the SPAM users that then deletes their resources permanently.  This would diminish the use case for inactive users to only those that may have requested they be de-activated or where the consideration of them being SPAM is still being evaluated.

**Comment by devincowan** [comment]
@dtarb I am supportive of your solution and appreciate your detailed explanation. Planning on revising accordingly...
