### ISSUE TITLE
Gracefully try and retry to connect to iRODS

### ISSUE THREAD

**Issue by cuahsimarko** [hydroshare/hydroshare#3081]
Currently defaultworker and hydroshare roles will crash with raw debug information when iRODS is not reachable or reachable but service not ready. Spirit of this work is to enhance logging and modify the core services in defaultworker/hydroshare to attempt and retry with configurable number of attempts and timeouts and enhanced logging to let console and log files know additional detail on failure. Finally, consider a default behavior to disable iRODS and load the server, despite loss of iRODS functionality and log as well as provide a user toast.

**Comment by cuahsimarko** [comment]
@hyi @cbcunc @sblack-usu @phuongdm @martinseul

**Comment by hyi** [comment]
@cuahsimarko As a large set of HydroShare functionalities depend on iRODS services, I don't see the utility to disable iRODS and load the web server as a default behavior. As for retry, I feel the effort taking to implement retry in HydroShare codebase (in fact, I don't have an idea where to plug in this retry since the FileField modal is tied to iRODS storage, so if iRODS is not reachable, Django server would fail) is much larger than resolving the dependency on the development environment set up side, either by resolving container and service dependency on docker/docker-compose level or via a script, something similar to what we do currently.

**Comment by cuahsimarko** [comment]
@hyi I wasn't intending to disable iRODS, simply retry after failing. Currently it just tries once and crashes, right?

**Comment by cuahsimarko** [comment]
I'll investigate and see if I can find where the calls go out to iRODS at server setup and see if I can at least enhance logging/debug info. If possible to delay and try again I'll do that.

**Comment by sblack-usu** [comment]
to bring up django and serve some type of messaging you'll have to disable iRODS in some way, otherwise there is no way to serve a message, right?

There isn't much you can do with HydroShare if iRODS isn't available, I think it say let it retry indefinitely with a configurable timeout.

**Comment by cuahsimarko** [comment]
Seems legit.
