### ISSUE TITLE
Migrate all generice resources to composite resource

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#3100]

**Comment by zhiyuli** [comment]
[Copied from PR #3101]

@danames @martinseul @dtarb @kjlippold 
Concerns regarding WebApp Res Type and Apps
1) WebApp Res Type: Remove option "Generic" from "SupportedResType" checkbox list (thanks @hyi )
![image](https://user-images.githubusercontent.com/10070599/53523030-f583b400-3a98-11e9-84b3-74e19fbb0725.png)
2) Existing WebApp resources: Replace checked "Generic" with "Composite Resource Type"

3) Existing Tethys Apps and 3rd Apps: May break Creation/Listing/Filtering/Retrieval of Generic resources
@pkdash @sblack-usu 
Instead of removing support for Generic in REST APIs, is it possible to "treat" all requests made to Generic resources just as they were made to Composite resources in all operations?

**Comment by pkdash** [comment]
@dtarb Let me know if I should address @zhiyuli suggested change items 1 and 2 above as part of the current PR #3101. It probably be better to address these 2 issues in a follow up PR.  

On item 3, it should be possible to make that change in REST API, but I am not sure if we should.

**Comment by dtarb** [comment]
@zhiyuli I do not think that items 1 -2 should be handled as part of the PR.   I do not think it is practical to handle them automatically, and in any event I think a separate process is needed to sort out web apps.  There are only about 60 web apps and many are obsolete, so a manual audit is necessary in any event.

For item 3 I would like @sblack-usu (as product owner for the REST API) to address how practical it is to retain deprecated API arguments through the transition.    

I think the issues associated with sequencing the roll out of all migrations are more complex than can be in one issue so I've started https://docs.google.com/document/d/1NP3fAjR8PC2_eO2CvXNvl3HmvRN5LvbzhiOl1nUzpYE/edit# as a strategy document to discuss this.  Please all edit, comment and add to this, especially @Lizabrazil @martinseul @jsadler2 @horsburgh

**Comment by pkdash** [comment]
@dtarb Though we have not migrated the generic resources yet, I am thinking of closing this issue for now as the code to migrate has been implemented and meregd.

**Comment by sblack-usu** [comment]
let's leave it to track testing/running the migration

**Comment by pkdash** [comment]
Sounds good.
