### ISSUE TITLE
Automatic metadata extraction breaks filepaths

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#3127]
I created a resource consisting of 2 python scripts and 4 raster tifs. The python scripts simply load the rasters and create a plot. https://beta.hydroshare.org/resource/3867d7662ea34974a8bb12faf5d84ed6/ 

1. Upload these data to HydroShare. Metadata from the rasters are extracted and their resource type is set to "Geographic Raster"

![image](https://user-images.githubusercontent.com/4822372/52374874-613fa780-2a2c-11e9-96fb-476717d73326.png)

2. Download the content as a zipped bagit archive and notice that each raster is in its own directory, unlike when the data was uploaded.

![image](https://user-images.githubusercontent.com/4822372/52374983-951acd00-2a2c-11e9-9767-1d1a7efc8fe6.png)

3. Running the script produces an error because uploading the data to HydroShare has changed the paths to the rasters. This could cause problems with users, because they will not notice that their files have been moved into folders. Additionally, they won't find out that things are broken until someone else tries to user their data.

I tried to fix this by  "Removing Content Type" for each raster in HydroShare. This removes the content type association but keeps each raster file in separate directories.  There is currently no way to move a file into its parent directory, which is one way to fix this broken paths. 

The issue is that the automatic metadata extraction changes file paths without asking the user, which breaks things.

Currently to work around this, a user would need to:

1. upload all data
2. remove content type for each file
3. cut each file and paste into the parent directory
4. delete unnecessary folders.

**Comment by dtarb** [comment]
This behavior is by design - not a bug.  During composite resource design we decided that aggregations comprised of multiple files should be contained in a folder.  This was debated a fair bit.  You can see the design in https://docs.google.com/document/d/1Hb18tUZyG7PHSwrclRHOmcYcEJvD0i9dQSmNdVckBUc/edit.

Options are
1.  Write the scripts to expect the files in the folder.  Probably the preferred option
2.  Remove the content type aggregation and cut and paste the files back to the top level.  You have to use cut and paste to move files out of a folder.  This loses the recognition as content aggregations.
3.  Write the script to move files out of the folder before its execution (a variant on 1.)

**Comment by Castronova** [comment]
While option 1 is the easiest for us, I don't think it's a good idea to require users to adhere to the HS folder pattern, especially when it's not very obvious/predictable. For example:

1. adding aggregations for new file types requires users to adopt a new pattern. 
2. from the UI interface aggregations don't appear to be folders (which is intentional), as a result it will not be obvious to users that their data has been restructured. This will cause problems days/months/years later when someone downloads the data and realizes that it doesn't work.

I think that we should either:

1. only perform aggregations if the user explicitly asks for this to be done, so that there aren't any surprises.
2. create the aggregations automatically (as is done now) but revert the data back into its original state when it's downloaded, i.e. give them back exactly what they put in.
3. figure out how to remove folders from aggregations and let the UI display/hide files as necessary, e.g. show *.shp and hide *prj, *shx, etc.

In our current implementation is seems like most JH/modeling applications will need to upload their data as a ZIP file.

**Comment by pkdash** [comment]
I would vote for the case where the system creates auto aggregation by default. We give the user option to override that.

**Comment by horsburgh** [comment]
As I thought about this yesterday afternoon, I also thought that the most reasonable option given the functionality we now have would be to allow users to turn off auto-aggregation for uploaded files. As @pkdash suggests - auto aggregation would be default, but we should probably consider allowing users to turn it off (likely on a resource specific basis).

**Comment by danames** [comment]
I think the "proven" solution is actually the Esri solution that they've
been doing for 20 years and which seems to work well: let the files always
live in their original folder, BUT dispaly them as aggregations. I can't
find any place where we have a documented reason why we didn't follow this
approach. Is there a discussion about this in our notes somewhere? Jeff, I
have a faint memory of some issue with this but I can't find it in our
notes or in my memory banks.


**********************************************************************
Daniel P. Ames, Ph.D., P.E.
Professor, Civil & Environmental Engineering,Brigham Young University,
Provo, Utah, USA
President, International Environmental Modelling & Software Society
Editor-in-Chief, Environmental Modelling & Software
http://ceen.et.byu.edu/content/dan-ames
http://www.researchgate.net/profile/Daniel_Ames
http://scholar.google.com/citations?user=S0GUCeUAAAAJ

**********************************************************************

**Comment by horsburgh** [comment]
@danames and @Castronova - ESRI's "proven" solution does not fully support all of the use cases or content types in HydroShare that we have now implemented for composite resource. Also - interesting that you point to ESRI's solution because their data model(s) actually require multiple data/content types (e.g., coverages, rasters, file geodatabases, etc.) to be stored in folders. You don't have a choice. 

We need to maintain a solution that works across all HydroShare functionality and across all of our content types.

HydroShare's resource data model has a much broader context than just GIS data. For example: How should HydroShare tell the difference between a tiff file that is Figure1.tiff from my most recent paper versus a tiff file that is a geographic raster dataset? ArcCatalog doesn't know the difference. Should I be able to send Figure1.tiff to the HydroShare GIS App? 

These decisions were long debated, discussed multiple times on calls, encoded in our design document, implemented, and demonstrated multiple times by multiple people for the team on teleconferences. We implemented auto-aggregation at the specific request of @danames because he didn't want users to have to right click on files and convert them to aggregations. 

The approach we have now consistently works across all content types in HydroShare for metadata description/encoding, file storage, packaging for transport, cataloging, access control, download, etc.

Details of the composite resource design are in the Google Doc here:

https://docs.google.com/document/d/1Hb18tUZyG7PHSwrclRHOmcYcEJvD0i9dQSmNdVckBUc/edit 

Suggestions for alternatives that still support all of HydroShare's use cases and functionality are welcome. Perhaps we should have a breakout discussion on an upcoming call? There would be an opportunity cost associated with making big changes at this point, but we would just have to evaluate whether it's worth it.

**Comment by Castronova** [comment]
@horsburgh I know there have been lots of discussion around this in the past and there is justification for the approach that was taken. I'll read through the document you've linked to. I think this would be a good breakout, but it would conflict with the modeling and app breakouts that happen almost every week. Maybe we can schedule something outside the Wednesday.

**Comment by dtarb** [comment]
As you guys open this up for further discussion, please consider the cost in terms of other opportunities involved and what we are diverting attention and effort from, if we put attention and effort onto this.  We know that as programmers it is possible to do almost anything and should be possible to not put some of the content aggregation types in folders.  This will involve changes to what is there, and re-designing, re-coding, re-testing, and re-documenting.  We have limited coder resources.  If we work on this it takes away from effort that could be put on other functionality.  While, as a team we certainly should be open to discussion, we do need to consider the cost.

**Comment by pkdash** [comment]
> As you guys open this up for further discussion, please consider the cost in terms of other opportunities involved and what we are diverting attention and effort from, if we put attention and effort onto this. We know that as programmers it is possible to do almost anything and should be possible to not put some of the content aggregation types in folders. This will involve changes to what is there, and re-designing, re-coding, re-testing, and re-documenting. We have limited coder resources. If we work on this it takes away from effort that could be put on other functionality. While, as a team we certainly should be open to discussion, we do need to consider the cost.

It is going to be a big cost.

**Comment by Castronova** [comment]
Verified that this is working properly on WWW.
