### ISSUE TITLE
NEW UI - Adjustable column width in Content section on resource landing page

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#3147]
We got quite a few files with long filenames in the czo project, which got cut off in the Content section.
Hover-over a single file icon can show its full name in a popup. But it would be more convenient to make the column width adjustable.

![image](https://user-images.githubusercontent.com/10070599/52727381-5330e000-2f72-11e9-847e-95d7de7b00c7.png)

**Comment by cuahsimarko** [comment]
Try to keep communications like this actionable. that's a huge mailing list and nobody will take any action, because it's not clear who the intended audience is. Slack or a GH issue would have ensured this eventually gets picked up by someone

On Feb 13, 2019, at 11:39 AM, Zhiyu(Drew) Li <notifications@github.com<mailto:notifications@github.com>> wrote:


We got quite a few files with long filenames in the czo project, which got cut off in the Content section.
Hover-over a single file icon can show its full name in a popup. But it would be more convenient to make the column width adjustable.

[image]<https://user-images.githubusercontent.com/10070599/52727381-5330e000-2f72-11e9-847e-95d7de7b00c7.png>

**Comment by cuahsimarko** [comment]
Whoops, I made the same mistake. Meant to send that just to Drew as we work through the CZO stuff and who's doing what.

Mark

On Feb 13, 2019, at 11:43 AM, Mark O'Brien <mobrien@cuahsi.org<mailto:mobrien@cuahsi.org>> wrote:

Try to keep communications like this actionable. that's a huge mailing list and nobody will take any action, because it's not clear who the intended audience is. Slack or a GH issue would have ensured this eventually gets picked up by someone

On Feb 13, 2019, at 11:39 AM, Zhiyu(Drew) Li <notifications@github.com<mailto:notifications@github.com>> wrote:


We got quite a few files with long filenames in the czo project, which got cut off in the Content section.
Hover-over a single file icon can show its full name in a popup. But it would be more convenient to make the column width adjustable.

[image]<https://user-images.githubusercontent.com/10070599/52727381-5330e000-2f72-11e9-847e-95d7de7b00c7.png>

**Comment by cuahsimarko** [comment]
Looks like CZOs manually adapted this data, so this GH Issue is pretty low priority.

**Comment by Castronova** [comment]
One way to do this is by wrapping the "fb-file-name" span in an expandable div:

```
div.expandable {
    overflow: hidden;
    resize: horizontal;
    text-overflow: ellipsis;
    margin: 0px 10px;
    min-width: 300px;
    max-width: 5000px;
    direction: ltr;
    width: 972px;
}

<div class="expandable">
    <span class="fb-file-name">This-is-a-very-very-...-very-long-filename.zip</span>
</div>

```

**Comment by ClaraCogswell** [comment]
Closing: cosmetic, low priority
