### ISSUE TITLE
Gateway timeout for specific resource on 1.19 beta

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3154]
The following resource opens correctly on www
https://www.hydroshare.org/resource/665dfa6aee8d4689ab59def52b3b1179/

On the 1.19 candidate release on beta I get a gateway timeout
https://beta.hydroshare.org/resource/665dfa6aee8d4689ab59def52b3b1179/

![image](https://user-images.githubusercontent.com/3456833/52900467-418a4b00-31b3-11e9-9aab-5355b280c313.png)

**Comment by dtarb** [comment]
Reproducibility of this bug is troublesome.  I get the time out logged in as dtarb, but not logged in as demo (my test account) or not logged in at all (the resource is public).

This is an 8.5 GB resource.  Attempts to download the bag on beta fail with a 504 gateway timeout (after the resource has been opened not logged in).  Attempts to download the bag on www fail with a 504 gateway timeout.  Attempts to copy the bag to iRODS on www also fail (without any error message).  The bag is just not copied.

**Comment by kjlippold** [comment]
I'm posting this here since it seems to be related to this issue. Trying to view this resource results in a 504 gateway time-out error since the 1.19 update:

https://www.hydroshare.org/resource/ceab9b8fccae452fac62d8d3ecbf8e78/

I've also been unable to access the resource file list using the REST API. This resource is maintained by Jorge-Luis Sanchez at BYU and he said the resource contains over 1,000 CSV files, but only 70 mb of data.

**Comment by cuahsimarko** [comment]
Is this fixed?

**Comment by cuahsimarko** [comment]
Beta properly loads 16apr2019 6pm EST
