### ISSUE TITLE
Support special case in creation of ReferencedFile with a "not-resolving" url

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#3156]
ReferenceFile logic checks if a user-provided URL is resolving before it creates the ReferencedFile entry, which works as desired in most cases.

In CZO project, however, there is a special case that a URL points to an external resource/page protected by 3rd-party authentications outside of HS. An example is here, which opens a popup for CZO-managed username/password.
http://www.czo.arizona.edu/PrivateData/Catalina/MtB_CO2O2/BGZOB2_co2o2_2018.csv
![image](https://user-images.githubusercontent.com/10070599/52904495-8bdaee80-31ea-11e9-9f8f-8321ae90d28d.png)

Currently, ReferenceFile does not support the creation of this kind of URL through either UI or REST API (hs_client) as HS might think the url is "not working" or "not resolving"

**Comment by zhiyuli** [comment]
including @martinseul @cuahsimarko

**Comment by horsburgh** [comment]
@zhiyuli - I'm curious what the desired behavior is for these files. The URL you listed has "PrivateData" in the path. What's the purpose of posting a URL this this private file to HydroShare, when only those with a password can access it?

**Comment by zhiyuli** [comment]
Czo people wanted files level access control, which is not available in HS.
That private CSV is stored in one composite res with other public CSVs. It
is private probably because the data is not verified or approved yet, and
only for CZO internal use for now.

**Comment by dtarb** [comment]
Files level access control is available in HS.  Put one file per resource.

**Comment by cuahsimarko** [comment]
In the UI and API, attempts to create a resource that is protected by authentication, the resource creation fails. The desired behavior is to for the url to be linked/created; upon accessing that resource, the user would be challenged for authentication.

**Comment by martinseul** [comment]
I would also challenge the need to require the URL to resolve on creation, yes it looks as if it would prevent broken links but if the URL resolves at creation time then the user moves the file, the URL is broken, so we don't actually prevent broken url's, maybe a warning to the user at creation time would be sufficient but still allow the creation.

**Comment by horsburgh** [comment]
@martinseul - fair enough. This may be the only sensible way to address this as we can't get past third party authentication systems and I don't think we want to bar users from creating their references to content. I like the validation step that @hyi has created and your suggestion that we convert this to a warning, but don't prevent the creation of the reference.

**Comment by hyi** [comment]
@horsburgh @martinseul @zhiyuli I think we need to add some basic url validation to catch non-resolving URLs initially, e.g., there might be a typo or copy and paste error in the input url. While working on fixing another related issue #3175, I was thinking we may need to relax the URL validation a bit. For example, for a 403 forbidden HTTPError raised from url validation, we should probably pass this one as success to allow users to proceed to create the referenced URL content type. This way, even if a URL is protected by authentication, we would allow users to create the reference content type with that protected URL. When a user tried to open the protected URL, I'd assume the user would be taken to a login page. The content creator may inform users that the referenced URL is protected and the user may contact someone to gain a guest login or something. Just a thought.

**Comment by martinseul** [comment]
OK so we agree on removing the mandatory requirement and have a warning instead @zhiyuli is this something you can take on?

**Comment by zhiyuli** [comment]
@martinseul 
@hyi already fixed #3175 and a PR is under review. I would leave this ticket to @hyi as well.  Just one thing: this issue was initially found out on REST API. I assume loose the restrictions on RefFileType backend would fix both REST API and UI in one shoot, is that right? @hyi  Thanks

**Comment by hyi** [comment]
@zhiyuli I believe so. That fix should work for both UI and REST API.
@martinseul I am only suggesting to relax url validation a bit to accommodate 403 forbidden URLs. Non-resolving URLs will still be blocked which I believe is a good thing.

**Comment by martinseul** [comment]
as expressed above a warning seems sufficient for me, we don't have restrictive enforcement in other places, also @zhiyuli mentioned the HS_restApi does not report a meaningful error message it just fails, so we have a restrictive API but no way to communicate this back to a user. As i'm all for improving the metadata for resources, in this case my vote would be a warning and not adding special cases that fail  but will be accepted and that we need to track. I assume this would also simplify the implementation.@horsburgh your thoughts?

**Comment by hyi** [comment]
@martinseul I am not really sure how a warning would work. Do you mean just popping up a warning box indicating to users that the URL is not resolvable, and do you want to continue to create this resource with a non-resolving URL, then if the user chooses yes, the system just create the resource with this non-resolving URL, and if no is chosen, the system bails out without creating the resource? If the resource is created with a non-resolving URL, and if open reference URL action is requested, the user would just get a server error due to non-resolving URL. I don't understand what value-add this would give us. Of course, if a URL were validated at the time when a resource were created, but then the server were taken down later so the URL were not resolvable any more in the future, we would run into the same scenario with this non-resolving URL, but that should be an exception and edge case which makes sense, though. So my vote is that we should validate URL initially to make sure it resolves. REST API would return a error message that the URL is not valid, which would be the case for a non-resolving URL.

**Comment by zhiyuli** [comment]
I just talked to @hyi  on this issue. Since we still haven't reached an agreement on how to deal with all different kinds of "non-resolving urls" cases,  I would like to propose to add support to the "private url" case first-- a url requires for user authentication, which is currently needed by the CZO project.

We will keep this ticket open for further discussions on how to deal with other "non-resolving url" cases.

@martinseul @horsburgh What do you think? Thanks

**Comment by martinseul** [comment]
We do need a solution for this to support the CZO migration and it should go out with 1.21, if possible, so we can scope it to just that for now and use the mechanism @hyi  suggested above. How much effort is it to add the support for private urls to the validation?

**Comment by hyi** [comment]
@martinseul It'd be an easy fix if we decide to go with what I suggested above, i.e., relax URL validator a bit to allow private URLs to pass through. So I assume the answer is yes and I can go ahead to create a PR to take care of this private URL issue?

**Comment by zhiyuli** [comment]
@hyi 
Great! Let's fix it. Thanks!

**Comment by horsburgh** [comment]
We can of course do whatever is needed to support the CZO people, but I still have to ask why we are creating references to content that nobody can access. I guess I still don't really understand the use case. If the files are only for internal CZO use, does a reference to them belong in a public resource in HydroShare?

In any case, our design document said that we would not preclude users from creating links to content that requires third party authentication, but that HydroShare would not do anything to try and negotiate that authentication. So, @hyi - according to our design docs, we should allow these links.

**Comment by dtarb** [comment]
Following the principle of putting the user in control, but keeping them informed and helping them as much as possible, I would be happy to accept the following solution
1. User enters a URL
2. HydroShare attempts to validate the URL.  If the URL validates, all is OK
3. If the URL can not be validated, HydroShare displays a message that says "Unable to validate URL Link.  This may be due to an error in the URL or password or automated bot protection at the hosting site.  If you still want to create this link, check the box 'Agree' below and then click 'Proceed'.  Otherwise click 'Cancel' to enter a correct the link."  
4. Then below this there should be a check box that is by default unchecked, that says "I agree to create a link to an unvalidated URL."  Only when this check box is checked, does the 'Proceed' button become enabled.

**Comment by dtarb** [comment]
We would also need to address invalid URL's in the API.  I suggest an API argument (also not a default) that allows a script to bypass the URL validation associated with API reference link creation.

**Comment by hyi** [comment]
@dtarb I agree with the principle of putting the user in control, but in this case I don't see any point in allowing users to create a non-resolving URL, i.e., a URL that will not resolve even from a web browser. What happens when a user requests to open this non-resolving URL? A server error would resolve. Although we should put users in control, we should also recognize potential user errors and HydroShare should strive to prevent any user errors from the start. So I don't think putting out this warning message that allows users to decide whether to go with the non-validated url or not is the desired behavior. If I relax URL validator a bit to treat private URLs as valid URLs, I don't think there are any exceptions any more in URL validator meaning if URL fails to validate, the URL cannot be resolved. Currently, an error message would be displayed informing users that the URLs they enter are not valid, and they have to enter a valid URL. I think it'd be sufficient once we put in fix to allow private URLs. I'll wait for your approval before I implement the fix, though.

**Comment by zhiyuli** [comment]
@dtarb 
I agree with your suggestion as it is a comprehensive solution for long term. However, I am concerned this would complicate the development and delay the fix for "private url" case. For this stage, I would like to have @hyi  fix "private url case" as simple and quick as possible.

**Comment by dtarb** [comment]
There could be cases where the URL is a DOI.  The user knows what the DOI is but it has not been registered yet (e.g. paper not published yet).  This would allow a user to create the reference.  There could also be URL's that really do work (like were reported in #3175, but for some reason HydroShare validator does not recognize that.  This provides the user a way to get around imperfections in the HydroShare validator.  

I object a bit to the concept of simple and quick, which I would characterize as quick and dirty, that @zhiyuli.  We have had a bit too much of that in the project and really need to start doing things properly and reduce, not add to technical debt.  I also do not think a dialog box that implemented the suggestion is overly complicated.

**Comment by dtarb** [comment]
I think it would be hard for @hyi to guarantee that our URL validator has addressed all possible URL behaviors and exceptions.  We did not anticipate #3175.  There may be other things we do not know.  We need to give the user an out, so that next time a tricky problem occurs we do not have to scramble to "fix" it, because the user can "fix" it.

**Comment by hyi** [comment]
@dtarb DOI example is a valid example I haven't thought of. However, issue #3175 has been fixed and the PR has been merged into develop. URL validator may still have flaws we need to fix along the way on a case by case basis, but it is always good to catch non-resolving URL from the start in my opinion. If the decision is to not validate URL at all and left it all to users with a warning, which is justified by the DOI example, I could implement that, which would take a bit of more effort especially considering supporting REST API, but manageable. I think there is a trade-off here and it is a policy decision. I'd need input from @horsburgh and @martinseul before going with not enforcing URL validation at all approach.

**Comment by horsburgh** [comment]
@hyi - I don't think @dtarb is suggesting that we not validate the URL. He is suggesting that we try to validate the URL and if it fails, we let the user decide what they want to do. I am OK with this approach.

**Comment by hyi** [comment]
@horsburgh OK. Sorry for the confusion, but what I meant was that we would not be enforcing URL validation any more, and the user would be in control, meaning if they want to create an invalid URL, they could. On second thought, I guess the warning would be sufficient for users to take a second look at the URL, and in DOI case @dtarb brought up, they would choose just go ahead to create the resource, otherwise, they would most likely cancel the action and fix the URL. Even though they made a mistake, they could always correct the URL by validating it. If I remember correctly, we don't allow a composite resource that include referenced URL aggregation to be published, right? If that is the case, we should be good on this. Otherwise, we need to validate URL when the resource is being published at that time to make sure only resolving URLs can be included in a published resource. @zhiyuli @martinseul I will implement this as suggested by @dtarb above then.

**Comment by martinseul** [comment]
Thanks that approach works for me.

**Comment by dtarb** [comment]
Because @hyi asked the question, I would like to allow publication of resources that have a reference that is a validated DOI, and that meet all other metadata requirements for publication.  This can be put as a separate issue for future implementation (I just filed #3209), but I would not like to let a link preclude the publication of a resource that has otherwise publishable stuff in it.   The effect of precluding this publication would be to have users who want to publish, reduce information by deleting the references, while if it is a validated stable persistent reference (and here we are taking DOI as the operational definition of stable and persistent) we should allow publication.  We have already seen CZO examples where there are DOI references.  We should encourage these.

**Comment by hyi** [comment]
@dtarb @sblack-usu @zhiyuli While working on not enforcing URL validation when creating referenced content, I will make url validation as a separate internal view function for UI to call via ajax to see whether a url is valid or not so as to show a warning dialog or not on the UI side, and make two view functions (also exposed to REST API), add reference url and edit reference url, to do what they are supposed to do without validating URL at all. This will work well on the UI side to implement the workflow as @dtarb suggested above, but on the REST API side, there would be no URL validation as there used to be. The rationale is that the REST API coder will determine whether they want to validate their URLs before calling our REST API endpoints to add URL as reference contents or not, in a sense, it is like whether they clicked on "Agree to proceed" or "Cancel" on the URL validation warning dialog, which is consistent with our principle to leave URL validation to users.

**Comment by sblack-usu** [comment]
I'm comfortable placing url validation on the rest api user.  The rest api is used for automated tasks, so it's less likely to receive an invalid url anyways.  The other option is to add a flag to skip url validation in the rest api.

**Comment by hyi** [comment]
@sblack-usu This will create inconsistency between REST API and UI since we will not enforce URL validation on UI as detailed above. In the example @dtarb brought up above, a DOI URL to be published but not yet published is treated as a non-resolving URL, so we should allow users to create a referenced content using this URL even though it is non-resolving and invalid at the time the reference content is being created using this URL. I think we need to keep REST API and UI consistent, so if we don't enforce URL validation on UI, we should not enforce it on REST API as well. Adding a flag may be a better alternative. I could add a ```validate_url``` flag with a default value being True meaning to enforce URL validation, and the user can set it to False if they want to create reference content with a non-resolving URL at the time. I'll go with this option unless others disagree.

**Comment by hyi** [comment]
@zhiyuli Thanks for the input. Yes, I'll go with that option as stated above.

**Comment by hyi** [comment]
@dtarb @horsburgh @martinseul @zhiyuli @sblack-usu I got this new workflow working for adding referenced content with a non-resolving URL. Do we need to support non-resolving URLs for editing referenced URL? I am leaning toward keeping the current behavior, i.e., always validate URL when editing an existing referenced URL, so if you try to put in a non-resolving URL when editing an existing URL, you will not be able to do so due to URL validation enforcement. The only potential drawback for this I can think of is the potential inconsistency between adding a referenced URL and editing a referenced URL, but I think the inconsistency can be justified. What do you think?

**Comment by sblack-usu** [comment]
I think create/edit should be consistent with validation.  If we have a reason to bypass validation with creation, that same reason is applicable for editing.

**Comment by hyi** [comment]
@sblack-usu Fair enough, I agree consistency is always a good thing. I'll just modify edit referenced url behavior to not enforce url validation then to be consistent with create referenced url.

**Comment by zhiyuli** [comment]
Tested on park. Both UI and REST api worked as expected. Thanks @hyi

**Comment by dtarb** [comment]
@hyi I am happy to leave the testing of this to others.

**Comment by hyi** [comment]
@dtarb OK. You may want to take a look at the implemented warning dialog, though, since it is not implemented exactly as you suggested above. See the screen capture below. Let me know if you have any further suggestion on this.
![invalid_url](https://user-images.githubusercontent.com/476302/53913253-ea94ca80-4028-11e9-82e0-6dff52e3009a.PNG)

**Comment by dtarb** [comment]
If you can make it harder for them to "proceed", please do.  At a minimum, make Cancel the default, so they actually need to move mouse to proceed.  Also if (without making this too much work) it was possible to force clicking on a check box "I agree to proceeding to create a link that has not been validated" before enabling proceed, then that would help ensure that the choice is deliberate.

**Comment by hyi** [comment]
@dtarb Good idea. I have made Cancel the default action button and updated park with it. See the screen capture below. Since creating a referenced content with an invalid URL is not that critical, the user can later edit/update it as needed, and we don't allow resource with referenced content to be published as of now, and even if we allow such publication later, we would ensure URL is valid before allowing publication, I think it is OK not to add a check box before enabling proceed for this specific case, unless you think this checkbox is really needed. 
![invalid_url](https://user-images.githubusercontent.com/476302/53914410-8fb0a280-402b-11e9-862f-934954f14cfe.PNG)

**Comment by dtarb** [comment]
OK.

**Comment by hyi** [comment]
The work has been deployed on www. Closing.
