### ISSUE TITLE
Text in multidimensional resource truncated

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3165]
See this problem, evidently introduced with 1.19
https://www.hydroshare.org/resource/13eb6f4034fd44db87b0a1eef3ee3826/

Previously this content was in a tab

![image](https://user-images.githubusercontent.com/3456833/53052337-a8319200-345b-11e9-9432-42e33292c5ea.png)

**Comment by dtarb** [comment]
In looking at this - it may be best to just delete this text.  It is a bit too type specific and the functionality is available other ways via Open With connectors.

**Comment by Maurier** [comment]
@dtarb Could you confirm and specify which part of this section should be deleted? Or should I remove the entire section "THREDDS Data Service"?

**Comment by dtarb** [comment]
I think remove the entire THREDDS data service section.  As a design principle I think we should avoid having code for specific apps associated with specific resource or aggregation types hard coded in the repository code base.  Rather, where there are apps that can act on resource or aggregation types, we should use web app connector resources to set up the open with connections for them.  This is so that if the web app changes, then the user responsible for the app just needs to change the web app connector resource, rather than HydroShare code being changed, as I think would be the case here.  Mentioning   @horsburgh @gantian127 @rayi113 @hyi @sblack-usu @cuahsimarko @danames so they are aware of this general approach suggestion.

**Comment by sblack-usu** [comment]
The code for this THREDDS Data Service message is in hs_app_netCDF.  It's probably appropriate to leave it in because we're using THREDDS for netCDF files.

**Comment by danames** [comment]
I agree with Dave that this needs to be refactored so that we don't have
code for specific apps as part of HydroShare, but rather use the open with
capabilities...
**********************************************************************
Daniel P. Ames, Ph.D., P.E.
Professor, Civil & Environmental Engineering,Brigham Young University,
Provo, Utah, USA
President, International Environmental Modelling & Software Society
Editor-in-Chief, Environmental Modelling & Software
http://ceen.et.byu.edu/content/dan-ames
http://www.researchgate.net/profile/Daniel_Ames
http://scholar.google.com/citations?user=S0GUCeUAAAAJ

**********************************************************************

**Comment by Maurier** [comment]
@dtarb This change has been deploye to www. However, I don't think the Web App connector is in place. Could you confirm?

**Comment by Maurier** [comment]
Nevermind, I do see the connection now. Closing...
