### ISSUE TITLE
New Field for Citing Associated Journal Publication 

### ISSUE THREAD

**Issue by Lizabrazil** [hydroshare/hydroshare#3187]
let's discuss adding a more explicit field that allows the user to cite an associated Journal Publication. We can still keep the Relations field as well for the other relation types, but lets elevate the Journal publication field so users are more inclined to fill it out. "Data for associated Journal Publication: Citation/URL/DOI..." or "Cite associated journal publication: ...."

**Comment by horsburgh** [comment]
@Lizabrazil - I don't think we need a new field. I think we just need clear directions on how to do this. We already have this capability in the existing relations. 

The following show links to published documents, one is a paper, and one is a dissertation. The full citation is given for both in a section on the page called "References". What's missing?

![image](https://user-images.githubusercontent.com/3485902/53260880-e57e6580-368f-11e9-9993-6a5ed3b2fe91.png)

**Comment by Lizabrazil** [comment]
I'm referring to only edit mode of a user adding info. Even after seeing the section that says References, I would know to go to related resources but then I wouldn't know which to select, this content serves as the data for, described by, cites, part of. I would have to think and guess or maybe try to find the examples in the Help Page. 

I would say the banner information is enough but I've often seen users immediately close out the very informative banners on the page without reading them. There is that little gray text that says:
![image](https://user-images.githubusercontent.com/13852599/53261613-78c09680-36a2-11e9-9beb-6cf938e7ba54.png)
Instead, we can improve that text to say "Add associated journal publications, dissertations, etc. here. Select "Data For" to cite an associated Journal Publication." So if the user closes out of the banner, the information is still there directing them. 

Thoughts?

**Comment by horsburgh** [comment]
@Lizabrazil - we've already updated the drop downs so the more informative text is now in the drop downs for the user to select and not the base semantic terms - i.e., they can now select "The content of this resource serves as the data for" instead of the base term "isDataFor". See @Maurier 's most recent post on #2763 

I like the text you suggested. @Maurier - one more change, can you change the text that @Lizabrazil suggests:

Instead of "No related resources have been added" change the text to "Add associated journal publications, dissertations, etc. here."

Also, the text in the blue information box needs to be changed to the following:

"If this resource is related to other documents, datasets, websites, etc., you can record those relationships here as references. For example, if this resource is cited by a paper you published, select a relationship type of "The content of this resource serves as the data for" and then provide a full text citation for the paper that used the data, including the paper's DOI encoded as an HTTP URL if available. This records that this resource is the data for the paper that cited it. If you enter a URL as part of the citation, it will be converted to an active link."

**Comment by Lizabrazil** [comment]
Feel free to close this out when text change is completed @Maurier

**Comment by Lizabrazil** [comment]
closing because it can be assessed for #3261
