### ISSUE TITLE
Don't show resource links to visitors who are not logged in

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#320]
1) Don't log in
2) Browse to a user profile page
3) See the list of their resources
4) Click on one of their private resources
5) See an un-informative "403 Forbidden" page (https://www.youtube.com/watch?v=UNyyjf6L1j4)

HydroShare should not show the names/links of private resources to people who do not have access to those resources.

**Comment by ironfroggy** [comment]
Does it matter if they aren't logged in? If the resource is private should *anyone* see it?

**Comment by dtarb** [comment]
Private in this context means not public (not completely private).  It means that the resource should be seen by anyone or any group with which it has been explicitly shared (to view or to change) according to the sharing model.  There is also the concept of discoverable which is a resource sharing attribute that can be set for a resource that enables access to the metadata but not the resource data itself.

**Comment by danames** [comment]
Correct. Links to private resources shouldn't' be visible to anyone.

**Comment by danames** [comment]
David's point is important. Anyone with access to the resource (shared with them or because it's public) should see the links... Anyone else shouldn't.

**Comment by gantian127** [comment]
It may be better to make the "403 Forbidden" page more informative if this is possible to be implemented (e.g providing detailed info why that is "forbidden" to the people who doesn't have the access to the resource). 
The reason is that as long as the link is visible even to a small group of people, there is possibility that  people who are not familiar with the access control of HydroShare  may use that link and share it with other people who probably don't have resource access. And this kind of situation ("403 Forbidden") will happen again. 
Google drive has the function to show the detailed info to the user  who can't access to the shared resource and tell them why (I can't remember clearly under what situation, but I once had that experience and don't know if they have changed that function or not). Probably we can think about following the similar way.

**Comment by ironfroggy** [comment]
My was mostly that it isn't necessarily important if the viewer is logged in or not, but their specific permissions on each individual resource on this list.

That makes caching kind of problematic, of course.

**Comment by horsburgh** [comment]
I'm going to assign this to @mauriel133 because it has to do with the User Profile page.  But, I think we should for the first cut simplify this functionality and only show resources on a user's profile page if they are "Discoverable".  When the access control is all integrated, etc. we can deal with filtering the list based on access control rules.

**Comment by dtarb** [comment]
@mauriel133 @horsburgh can you please decide if this should be part of 1.6.0 release which is intended just to address access control and base class refactoring or should be deferred to 1.6.1 which is more general improvements.

**Comment by horsburgh** [comment]
@mauriel133 thinks this is going to be pretty simple, so I say we do it quickly and get it into 1.6.0. I'll change the associated milestone.

**Comment by dtarb** [comment]
This appears resolved in current 1.6.1 deploy.
