### ISSUE TITLE
My resources page loading time improvement

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#3211]
Optimization of database query that generates the list of resources.

**Comment by cuahsimarko** [comment]
I've added myself as additional "Assignee", because I don't know of any other way to "Watch" this issue and have it in a list of things that interest me.

**Comment by pkdash** [comment]
@cuahsimarko It seems to get a reasonable page load time we have to have pagination. I can add resource sorting to the backend so that it works with pagination. I know some people don't like pagination others may prefer pagination with faster load time. May be we  should allow the user to set that choice in their profile page.

**Comment by cuahsimarko** [comment]
@pkdash The reason why pagination isn't being used right now, is due to the changes needed to support proper sorting. Also, the status of the filtering checkboxes and refresh are not completely documented (existing bugs). The more basic elements of the page should be fixed before adding more features.

**Comment by cuahsimarko** [comment]
@pkdash The urgency for the fix also was downgraded, after splitting the high number of Resources into the proper accounts, reflecting a more realistic/majority use case. Others with performance problems are still outliers.

**Comment by pkdash** [comment]
This improvement has been implemented and works on www. Closing.
