### ISSUE TITLE
A couple issues with new markdown readmes for resources

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3227]
As the defacto open source git repository service, the appearance of README.md files on GitHub would be a good standard to compare our new markdown rendering system.  When doing so, using a example projects https://github.com/chjj/ttystudio/blob/master/README.md and https://github.com/Yoast/wordpress-seo/blob/trunk/README.md, a couple notable differences become evident.
1) Code blocks are not supported in our system (see video 014-1)
2) Multi-level unordered lists are not supported in our system (see video 014-1)
3) New lines don't work the same way in our system (see video 014-2)

[014.zip](https://github.com/hydroshare/hydroshare/files/2929501/014.zip)

**Comment by Maurier** [comment]
Initially we wanted to implement our markdown exactly like GitHub's, but while we were searching for options, the only resources we found for GitHub's was an API (https://developer.github.com/v3/markdown/). We chose our own server side solution instead in the form of a Django package based of daringfireball's (https://daringfireball.net/projects/markdown/basics) in order to avoid making requests to a 3rd party API.

I want to point out that if we want to improve our markdown to that of GitHub's, using GitHub's API is the only way I am familiar with. I am not sure if we can deploy our own version of it, or if there's any sort of quota for using the service.

If someone knows more I'll be happy to read on.

**Comment by cuahsimarko** [comment]
> 3\. New lines don't work the same way in our system (see video 014-2)

The effort to rewrite the open source product incorporated for README capability has an impractical cost/benefit return. At the least, new lines are supported, just via the special methods provided by the library. For example:

```
\n\n
```

or depending on your layout

```
"  \n<br /><br />\n  "
```

**Comment by cuahsimarko** [comment]
Others likely supported or desired visual output possible. I think this GH Issue should be closed with no further action.

**Comment by ClaraCogswell** [comment]
closing: stale, resolved
