### ISSUE TITLE
"Create" should be moved to the top navigation with a dropdown

### ISSUE THREAD

**Issue by Lizabrazil** [hydroshare/hydroshare#3242]
During breakout group in HS meeting on 3/13 we collectively decided to move the Create new button to the top navigation. 
- It should say "Create"
- It should have a dropdown with the Resource, Collection, Web app connector as options
- These will navigate to the Resource Landing Page (either composite, collection, or web app landing page)
- User will then add files on the resource landing page (we may need to rethink where adding files functionality lies on the page so users know to add files...usually it sits toward the top of the page in edit mode)

To declutter the top navigation, we are thinking of combining About and Help into one header with a dropdown. 

@jsadler2 @dtarb @martinseul please comment where Create should be located on the navigation. If we are adding a dropdown to the About/Help then we may may to put it near that but logically it makes more sense to go next to My Resources and Discover I think.
@dtarb @sblack-usu Do we have a project or label to associate all the resource migration work together?

**Comment by Lizabrazil** [comment]
@Maurier let me know if this is confusing and we chat further about it. Thanks!

**Comment by Maurier** [comment]
@Lizabrazil - Thanks. I will be contacting you later on for more details.

**Comment by horsburgh** [comment]
@Maurier - this is part of work we want to do to streamline the resource creation process. We also plan to remove the "Create Resource" page entirely and instead just take the user to a blank resource landing page for the thing they have selected and allow them to build/edit their content there.

@dtarb and @Lizabrazil and @sblack-usu - did we decide today to move up the removal of the Create Resource page? Liza's description above of the new top navigation menu implies that the user would be taken directly to the blank landing pages for editing. Should we edit this issue to combine the new navigation with removal of the Create Resource page?

**Comment by dtarb** [comment]
Here are my suggestions
1. Change to top menu
![image](https://user-images.githubusercontent.com/3456833/54312670-1e2da280-459d-11e9-9177-c9083c05e86a.png)

There are actually 7 items, not just 3.  As model resource types get deprecated, they will be removed, but we still need them at the moment.  I also suggest the words Resource and Web App Connector to start introducing users to these terms. 

The action on selecting any one of these should be the same as the action that would have occurred if this item had been clicked on the Create Resources page without any information added or any files loaded.  The result should be an empty resource of the type selected in edit mode.

2. Remove CREATE from My Resources Page as it will be redundant with the top menu item.  This will effectively deprecate the Create Resource page.  I think leave deletion of the create resource page code to later, in case we have to roll back.  It will just not be active.

3.  With About HydroShare disappearing from the top menu, I suggest putting it in the footer
![image](https://user-images.githubusercontent.com/3456833/54312804-706ec380-459d-11e9-8646-f83ecadf07d0.png)

Items 1 and 3 will have to be done on www.hydroshare.org and pages/help.hydroshare.org

**Comment by Lizabrazil** [comment]
1. We need to fix the reroute so that it does not go to My Resources 
2. Decision needs to be made for whether or not to show the dropdown. When 
3. The menu nav bar should stay the same when on Help pages
4. The dropdown looks funky in the middle of the nav bar

**Comment by dtarb** [comment]
I suggest the following

1. Create menu item does not have triangle next to it.  This is so that all menus look the same.  This addresses point 3 above.  I think it would also address 4 above in that without the triangle it would look OK where it is, though where these items are on the top menu is a lesser consideration for me.

2. When not logged in Create menu item does not have dropdown.  It behaves the same as My Resources menu item.  It takes you to login, then after login you are on My Resources page.  This addresses the cumbersome reroute of 1 above.  

3. When logged in clicking Create (positive click, not mouse over) results in the drop down appearing at which point a user selects resource type to create.

4. On the help pages, recognizing that help is a separate site, the behavior is the same as not logged in.  Clicking on Create would log you in (or if already logged in) take you to the My Resources page which has an active Create menu.  This is the least likable item in this suggestion, but short of spending a whole lot of work to integrate Help with HydroShare, I think it is workable.  There are also other differences between help and HydroShare - see #3271, that I do not feel are worth spending effort on.

As item 4 needs to be implemented on the help system, once agreed, it would need to be implemented in a different PR.

**Comment by Lizabrazil** [comment]
@Maurier can you comment on the status of fixing #4 in Dave's comment above?

**Comment by Maurier** [comment]
@Lizabrazil The work on the Help pages is still pending. Assuming that the bullet points you mention are our final decision on the design, I will be making the corresponding changes tomorrow to the Help pages so that it can be reviewed.

**Comment by dtarb** [comment]
On the programmer coordination call this morning there was discussion of what should go in the next release (1.23).  I am in favor of this change going in, though the concern was expressed that it may not be ready.  The code freeze deadline is 5/10/19 so @Maurier if you could work to get #3308 completed and reviewed by then, I would appreciate it.

**Comment by Maurier** [comment]
@dtarb The PR with this changes has been approved. I will now implement the navigation bar changes in the help pages. Once this is ready I will merge the work so that it is included in the next release.

**Comment by dtarb** [comment]
On the team call two concerns were raised 
1. The "Create" menu felt wrong and was inconsistent in that it had a drop down while other menu items opened pages 
2. Resources were immediately created with the potential for users to end up with many unintentional untitled resources.

@sblack-usu was assigned to investigate solutions.
The following solution is proposed and mocked up on  https://dev-hs-1.cuahsi.org/
1. Move create to the right (immediately next to and to the left of the users profile picture or icon) and make it a button
2. Implement an intervening pop up that has the user enter a resource title.

This captures a title for the resource and serves as a spurious creation gatekeeper.

The following improvements to the initial mock up are needed
1. Styling of the button @Maurier 
2. Have the pop up indicate the type of resource being created e.g.

Here is the wording I suggest for pop up title and text respectively for each resource type
“Create a Resource” No change.
“Create a Collection” and “Enter the title for the new collection of HydroShare resources”
“Create a Web App Connector” and “Enter the name for the new Web App Connector”
“Create a Model Program Resource” and “Enter the name for the new Model Program Resource”
“Create a Model Instance Resource” and “Enter the name for the new Model Instance Resource”
“Create a SWAT Model Instance Resource” and “Enter the name for the new SWAT Model Instance Resource”
“Create a MODFLOW Model Instance Resource” and “Enter the name for the new MODFLOW Model Instance Resource”

This is so that users looking at the pop up can see what type of resource is about to be created in case they clicked the wrong menu item.

**Comment by sblack-usu** [comment]
@Maurier - I've pushed the changes to a new branch with proper commit messaging.  Could you clean up the styling of the create button and the title popup prompt with proper messaging?  We're moving forward with this approach.

**Comment by Maurier** [comment]
@sblack-usu - Understood, I'll get to it.

**Comment by Maurier** [comment]
@sblack-usu I have cleaned up the styling now. Let me know if this is what we are going for:

For large screens:
-----------------
The button:
![image](https://user-images.githubusercontent.com/2448568/57956543-958df400-78b6-11e9-8002-8aaba9811156.png)


The menu:
![image](https://user-images.githubusercontent.com/2448568/57956448-3203c680-78b6-11e9-9bc4-5ed445de88d4.png)


**For mobile devices:**
-----------------
![image](https://user-images.githubusercontent.com/2448568/57956594-beae8480-78b6-11e9-8f29-7c543e523a5c.png)

**Comment by dtarb** [comment]
That looks great.  Create it.

**Comment by horsburgh** [comment]
@Maurier - don't forget the messaging on the modal window(s) that pop up when you make a selection.

**Comment by Maurier** [comment]
@horsburgh, good catch. I had assumed it was already implemented. I will take care of it and then proceed with a PR.
