### ISSUE TITLE
"Old Version Of" has hardcoded production url

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3265]
Use the "create a new version of this resource" button on the resource landing page.  Even if on beta, the link will use the production url.  Naturally, clicking this link results in a 404 since the resource is on beta.

[006.zip](https://github.com/hydroshare/hydroshare/files/3000656/006.zip)

**Comment by Maurier** [comment]
This needs to be looked at in the backend. It seems the issue occurs because of the way we construct the URL after the request is submitted.

**Comment by hyi** [comment]
@dtarb @martinseul @ndebuhr @Maurier This is not a code issue, i.e., no url is hardcoded in the code base, but a beta configuration issue. Since beta is deployed using www database, the Site URL refers to www by default. After I change the site URL from beta admin panel to correspond to beta, i.e., beta.hydroshare.org, it works correctly. By working correctly, I meant if you create a new resource on beta, then create a new version of that resource, that resource will correctly point to the resource on beta with the right URL. However, if you are creating a new version of a resource copied from www over to beta, since the original resource has an identifier URL pointing to www, the new versioned resource based off that would point to the one at www since that is what is stored in database. Hope my clarification/explaination makes sense, but let me know if it is still not clear. I think this issue can be closed. In the meantime, for beta deployment, a manual step is needed to go to admin panel and change ```Site``` to the right one corresponding to the deployed VM from the carried-over www.hydroshare.org. Looping in @sblack-usu @phuongdm and @cbcunc for their reference to take into account next time when they deploy beta.

**Comment by phuongdm** [comment]
@hyi, the beta deployment code did the change on every times.

1. Create json file (site_url.json) has with this content:
`[{"fields": {"domain": "beta.hydroshare.org", "name": "Default"}, "model": "sites.site", "pk": 1}]`
2. Run the `Site` change by this command:
`docker exec hydroshare python manage.py loaddata site_url.json`

You can check it by go to beta's admin page

**Comment by hyi** [comment]
@phuongdm Yes, I checked on beta admin panel and it showed www.hydroshare.org in Site element, so apparently that process did not work for this beta deployment, which was why versioned resource points to www. I manually updated the Site element from beta admin panel, so now it points to beta.hydroshare.org.

**Comment by dtarb** [comment]
This makes perfect sense.  I think that this should be closed when there is a procedure in place to have this be part of beta deployment, preferably automatically, but if not on a manual checklist.  I'll leave it for  @sblack-usu @phuongdm or @cbcunc to close when they are happy that this is part of the beta deployment routine.

**Comment by phuongdm** [comment]
@hyi, I only know one place which has "Sites" menu on the Admin page, is that image correct? if No, please let me know where we should update. Thanks!

![image](https://user-images.githubusercontent.com/24579275/54965897-da497e80-4f48-11e9-94e8-c9b194c49478.png)

**Comment by hyi** [comment]
@phuongdm Yes, that 'Sites" menu on the Admin page was what I edited. It used to be www.hydroshare.org, and I updated it to be beta.hydroshare.org. After my update, versioning a resource created on beta is pointing to the obsoleted resource on beta, not on www anymore. That is what I meant by this issue being a configuration issue rather than a code issue.

**Comment by phuongdm** [comment]
@@ it should be the error of the deployment number #45, when the whole deploy process did not run correctly because the node connection problem :(

**Comment by hyi** [comment]
@phuongdm It is good to identify the cause of this deployment issue. I'd suggest to add an item in the release check off or beta deployment check off just to confirm the Site element is updated correctly or make sure the whole deployment process has run through successfully, just to prevent this from happening again in the future. Then I think this issue can be closed.

**Comment by dtarb** [comment]
It would be good to have an automated test (Selenium?) that only works if this is right.  Neal @hydrocheck is doing tests on beta.  Perhaps one for this can be added.

**Comment by hydrocheck** [comment]
Added to automated test queue
