### ISSUE TITLE
"Is Version Of" incorrectly rendered in resource landing page

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3266]
In the References section of resource landing pages, "Derived From" is correctly rendered as human-friendly English, while "Is Version Of" is rendered in variable-like way "isVersionOf".

[007.zip](https://github.com/hydroshare/hydroshare/files/3000657/007.zip)

**Comment by Maurier** [comment]
@dtarb Could you provide the human friendly string to use in this case?

**Comment by Maurier** [comment]
While testing this I found another issue: 
1. Make a copy of the resource.
2. Try to edit the relation "isVersionOf" that was automatically created.
3. The dropdown to select the relation type does not show an option for "isVersionOf"

![image](https://user-images.githubusercontent.com/2448568/54891594-8f116c00-4e73-11e9-8c47-8d64aa338db3.png)

It seems to me that this type of relation is not meant to be edited or added manually. If this is the case then adjustments need to be made to both backend and frontend.

**Comment by dtarb** [comment]
Wording I suggest for "isVersionOf" is: "This resource updates and replaces previous version"
Wording I suggest for "isReplacedBy" is "This resource has been replaced by newer version"

As to the question of editing and setting these relationships the intention at design was that they would be automatically set when a new version was created (e.g. using the "create new version of this resource" button and hopefully also possible using the API) and would not be editable.  However I think that review of this functionality is needed (by @horsburgh ) as part of addressing #3261 and #3276.

An immediate action that is needed is to prohibit editing or deleting the relationship "isVersionOf".

**Comment by dtarb** [comment]
@Maurier The improved terminology suggested in this issue did not make it into #3281 PR.

**Comment by Maurier** [comment]
@dtarb, this work is in another PR pending review. https://github.com/hydroshare/hydroshare/pull/3277

**Comment by horsburgh** [comment]
@Maurier - any work on this needs to done in the context of #3261. As part of the discussion for that issue I have revised the list of relationship types, including adding some new ones and deprecating some that we should not be using. I have also revised the human-readable text for each relationship type that should be included in the drop down when selecting the relationship type and displayed on the resource landing page for related resources that have been added.

I'm going to close this one because it is superseded by #3261.
