### ISSUE TITLE
Creating a resource copying a file from iRODs results in an incomplete geographic raster aggregation

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3351]
The following resource was created using copy from iRODS on the Create Resource page.

https://www.hydroshare.org/resource/abba182072cc48b691ca61509019e9f8/

It holds a geographic raster file.  The .vrt file was created and it was placed in a folder, both steps in automatic aggregation.  However the folder that results does not appear on the UI as an aggregation and aggregation metadata is not displayed in the metadata panel.

![image](https://user-images.githubusercontent.com/3456833/56807819-15abc700-67ed-11e9-9917-5ddbb3529cb6.png)

**Comment by dtarb** [comment]
I am unable to make this illustrative resource public due to 
![image](https://user-images.githubusercontent.com/3456833/56807950-7cc97b80-67ed-11e9-893a-7056b1056927.png)

This is part of the problem of metadata not being set up right.  The resource is shared with HydroShare developers group so if you are a member of that group you should be able to access this.

**Comment by dtarb** [comment]
The inability to make the above resource public may be due to the nedgridb.tif file not having spatial reference information.  But it is still a problem, as it should be possible to add this information using HydroShare if it was converted fully to an aggregation.

The following resource with a different file is public, but does not have the aggregation folder properly formed
https://www.hydroshare.org/resource/2af8df74fc6344f4a13ed9c56c09fa40/
![image](https://user-images.githubusercontent.com/3456833/56808801-966bc280-67ef-11e9-9c9c-828f0fb485ce.png)

**Comment by dtarb** [comment]
If the create page is bypassed and the file is loaded from iRODS after the resource is created, the aggregation is properly established
Examples with the files above are
https://www.hydroshare.org/resource/ee5ac2b6e529479a97b469d21e681038/
https://www.hydroshare.org/resource/e9da177f87fd42e8922b2e4bb2ceb60d/

This appears to isolate this problem to the iRODS functionality in the Create Resource page, which means that once Create Resource is deprecated with #3242 this will be resolved.

**Comment by hyi** [comment]
@dtarb The only difference between loading iRODS file to create resource and adding iRODS file to an existing resource from resource landing page is where the resource is stored. In the former, the resource is stored in the user zone, hence the path is absolute that contains iRODS user zone info. I suspect the aggregation code did not account for the federation path properly, hence the folder path were not properly formed.

**Comment by dtarb** [comment]
This is similar to #2970

**Comment by dtarb** [comment]
@hyi that seems like a likely explanation.  But it is a case where iRODS complexity and federation complexity has bitten us and is costing us.  We need to structure and simplify our work to avoid these occurrences.

**Comment by hyi** [comment]
@dtarb I looked into this resource and confirmed this resource did get migrated from user zone to data zone on beta. You can check it out on beta here: https://beta.hydroshare.org/resource/abba182072cc48b691ca61509019e9f8/

I ran into bad gateway on beta initially and had to restart beta containers to get the server back up, and you can check on the migrated resource on beta above now beta is back up. As you can see, the aggregation is not created for this resource and the resource landing page looks exactly like that on www. This is expected since migration script only migrate resources from user zone to data zone without any extra aggregation checking. However, now that we have removed creating resources from user zone by copy or move action, you would not be able to create such a problematic resource in the first place on the current production server. So I suggest to delete this resource and close this issue unless you see any potential issues in doing so.

**Comment by dtarb** [comment]
@hyi please think from a users perspective.  I am happy to delete and fix this resource.  But there are multiple other resources from other users for whom this may be a problem.  I think that the process of migrating resources to userzone should audit and check all the resources migrated and if there are problems, then address them.  

And by the way - this resource is still broken on beta
![image](https://user-images.githubusercontent.com/3456833/58891076-1c114680-86a9-11e9-92b5-09ef86c66a55.png)

**Comment by hyi** [comment]
@dtarb I don't understand why you are getting AttributeError on this resource since it works for me. See the screen capture below
![HS](https://user-images.githubusercontent.com/476302/58892205-cd20dc80-86bb-11e9-9ce8-c15557f9b2b8.JPG)
It looks like the AttributeError you run into is related to your login user object being None, but I don't know how you can login in the first place if the user object is None, so I have no idea why you run into this issue but it works for me just fine. Do you run into this Attribute error for other resources on beta?

I could write a separate management command to fix the aggregation issues in composite resources like this one rather than put the logic in the user zone to data zone migration command since this aggregation problem may not be isolated to only resources in the user zone. If you think we need to do this, you can assign this issue to me or close this one and create a new issue for addressing this potential issues in all composite resources.

**Comment by dtarb** [comment]
@hyi before you write a separate management command we need to get to the root of what is going on.  It is curious that this file shows as an aggregation in your display, but on www with me it does not.  I do not have time right now to debug this particular issue, so will need to leave it to you, perhaps interacting with @sblack-usu to try figure out.

**Comment by hyi** [comment]
@dtarb good observation and it is interesting to see this migrated resource actually shows the geographic raster aggregation and all aggregation metadata also displays correctly on beta. I'll look into it and try to figure out what is going on since apparently fixing file path as a result of resource migration from user zone to data zone fixed this aggregation issue. In the meanwhile, beta user login seems to have a bit of issue which may be related to two workers being active and me manually deploying my code to one active worker, since I ran into csrf cross-site error if I click on this resource link directly on beta without logging in to beta first. However, if I login to beta first, then click on this resource link, the resource appears to display correctly for me. So you may try to login to beta first, then click on this resource link to see whether the resource landing page would show for you without AttributeError.

**Comment by hyi** [comment]
@dtarb I checked production Django database for this specific resource and verified this resource does have GeoRasterLogicalFile type relation linked to it. This explains why the folder shows as raster aggregation on beta after resource migration from user zone to data zone. I don't know the exact reason why this raster aggregation does not show for this resource on www, but I can confirm the resource data in Django database on www for this resource is correct, so the problem for this resource display on www might be caused by the server side view function which returns aggregation type not handling resources in user zone properly or by the client javascript code that somehow does not parse it properly. In any case, this display problem will be fixed in the next release after resource migration from user zone to data zone. As a result, I will not spend any more time investigating this further.

**Comment by dtarb** [comment]
@hyi I am happy for you proceed with the update that fixes this once you are confident it is right.  Will this be part of a regular code update, or a migrate script that runs separately.

**Comment by hyi** [comment]
@dtarb My PR including this migration command script has been merged into develop branch, so will be included in the next regular release. The migration script has to be run separately just one time as the last step of the next release and I can help with that if needed. Looping in @sblack-usu @phuongdm @cbcunc to keep them informed of this extra step only for the next release.

**Comment by sblack-usu** [comment]
@hyi, please add the migration command to the deployment notes when we cut the next release.

**Comment by hyi** [comment]
@sblack-usu Will do.

**Comment by dtarb** [comment]
@hyi @sblack-usu please consider whether it is best to run this migration command as part of the deploy or separately (e.g. 2 days later not during a deploy).  Our thinking with composite resource migrations has been that they should be separate.  Perhaps the same idea applies here too.  The reason for having them separate is to be able to do checks of resources before and after a deploy and if there are problems to know whether it is the deploy or the migration that has caused the problem.

I think that with this migration we also need a bit of extra manual cross checking that these resources do actually migrate properly, especially sensitive ones like large published resources from our users (Rushforth 100 GB resource).  Please coordinate all this.

**Comment by hyi** [comment]
@dtarb doing the migration in a couple of days after the deploy may be a good idea. @sblack-usu I'll add migration command in the next release deployment notes and leave it to you when you will run it. I'll check those migrated resources to make sure they look correct after migration is done on production server.

**Comment by dtarb** [comment]
This appears fixed with iRODS and zone changes
