### ISSUE TITLE
Anomaly in community resource listing

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#3382]
@cuahsimarko @martinseul @dtarb I recently discovered a dumb anomaly in the community listing. 

To reproduce this, do the following:
1. Make up a resource outside the community. 
2. Share with the community by some means. E.g., 
    a. Share with a member of the community, who then 
    b. Shares with the community as a whole. 
3. Make it public. 

It's then treated as a community resource, even though members of the community didn't create it!

I think the simple fix is to omit any public resource not owned by some community member, i.e., a member of some group in the community.

**Comment by alvacouch** [comment]
I might add that this applies also to the public listings of group resources, which are based upon the same query.

**Comment by dtarb** [comment]
I feel like I am missing some of the context and not grasping the concepts you are advancing here.  If a resource has been shared with the community does it not make it a community resource.  Or are community resources only resources owned by community members.  Part of my not getting this is that I have not taken time to play with a deployment of these concepts.  I worry that these concepts are being evolved by a small group with insufficient socialization and thus will not benefit from the perspectives that the team has to bring.

**Comment by alvacouch** [comment]
@dtarb The way communities are written now, sharing a public resource with a group in the community makes it a community resource. That is the way that public resources are associated with a community.  Likewise for a group. The problem with that is that there are more use cases for sharing with a community than just publishing.

**Comment by alvacouch** [comment]
@cuahsimarko @martinseul @dtarb It seems to me that the permanent solution to this problem is that `GroupResourcePrivilege` contains an `exhibit` flag that determines whether a resource is shown on the group's public home page (along with being shared with the group). Then, the group owner can modify which resources get "exhibited".  This, in turn, will `exhibit` these same resources on the public pages of the communities in which that group is a member. 

This takes a UI modification, so it will have to be part of a later release.

**Comment by alvacouch** [comment]
@dtarb A general comment: @cuahsimarko comments that we are conflating the issues of "making groups publicly accessible" (#2854)  with the "community landing pages", and that is quite true. The reason that I have opposed simply making the "my groups" pages public is that they are not written to be public. It is better to craft a different -- and much simpler -- public group page instead that is written for consumers of group output rather than members of the group. This is exactly parallel to what I have proposed for communities: a page for consumers of community products, and another page for members of said community.  The justification for this is that any member of the group should be able to browse and check the public image everyone sees for that group. Thus, these should be different pages. 

The path of least resistance is to create a "public group page" that is actually separate from the "my groups management page", just like we'll have a "public community page" that lists the community's activities, along with a private "my communities management page" that allows members to change things. In this process, the "my groups management page" is the existing "my groups" page.

**Comment by dtarb** [comment]
@alvacouch I am struggling a bit with the vision and the direction this work is going in.  We have at least 5 planning documents on this
- Groups of Groups in HydroShare https://docs.google.com/document/d/1qGh8bbTefetAbhd77ltr5dU_F2hYw69cDZBfVtsF9ds/edit
- HydroShare access control overview https://docs.google.com/document/d/1qGh8bbTefetAbhd77ltr5dU_F2hYw69cDZBfVtsF9ds/edit
- Communities of groups https://docs.google.com/document/d/1Rvb2Z4vTAGKEh5QXdRm3V035FLItfwA-ANOluT2g0ts/edit
- Projects in HydroShare https://docs.google.com/document/d/1IVy1HXGNH3UpBXAgL7Jg7OlynZI9grpWa7ffIp11o98/edit
- CollaborationCZO https://docs.google.com/document/d/1ePcqskJftLIcbWoeTOYzqLJGWy-FbCf6IkN2c34dWAQ/edit

These tend to jump quickly into technical implementation details, as does this issue writing about details of GroupResourcePrivilege and exhibit flag.  I find myself objecting to taking "the path of least resistance" as the most recent comment offers.  Rather we should be doing what is right, and not building in complexity or technical debt.

Even given all the documents above (or perhaps because of them) I struggle with grasping what the big picture goal of this work is, in terms of the problem being addressed and the design to address it.  I understand broadly that it is to provide for better organization and presentation of work from CZO projects, but there has been a lot of code development and prototyping that has not really been socialized.  The documents say things like "In discussions at CUAHSI, we have decided ...".  I can respect that CUAHSI is driving the CZO process, but I struggle with responding in issues like this where I am mentioned (and thus presumably invited to comment) in a meaningful way on a technical detail, when the big picture is not clear to me. Thus I find myself adopting a wait and see approach.  I will evaluate what gets deployed at the time it is deployed to beta (or on a staging machine if I am given access to that) and go from there.  If there are any top down designs or mockups/wireframes, I will also be happy to comment.  But I am not sure what to say about this specific anomaly in resource listing on a page that I have not seen or do not really know what its purpose is.

**Comment by cuahsimarko** [comment]
@alvacouch do you need me to update the Django template or frontend/JavaScript for the communities code to put this into effect?

**Comment by cuahsimarko** [comment]
@alvacouch is this impacted by the recent code in hs_access_control/models/group.py? I will soon consume the new Q query

**Comment by alvacouch** [comment]
This anomaly has already been addressed in the community code. The fix is to only list products owned by a member of the community.
