### ISSUE TITLE
Download sizes and resource size are inconsistent

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#34]
This is based on testing of alpha.hydroshare.org version 1.2.1. 

See image below for inconsistencies in sizes displayed for the same resource.
![p2](https://cloud.githubusercontent.com/assets/3456833/5604018/33f9e2a2-9360-11e4-9dac-cea672b45c00.JPG)

**Comment by mjstealey** [comment]
This may simply be due to a difference in how the files are stored by different OS platforms. UNIX uses a single Line Feed (LF) to signify a new line, Windows uses a Carriage Return/Line Feed (CRLF) and Mac uses just a CR. This would apply to text based files only, not binary files.

The calculations are as they should be at the file source on CentOS (Linux)

The single file
`-rw-------  1 irods irods 52215505 Dec 29 15:07 opt2_geotiff.tif`

B: 52215505
KB: 50991.7
MB: 49.8

The .zip bagit file
`-rw-------  1 irods irods 43117107 Dec 29 15:09 40928f3106b143a2bf5ce575cb28275b.zip`

B: 43117107
KB: 42106.5
MB: 41.1

**Comment by mjstealey** [comment]
Resolved via discussion
