### ISSUE TITLE
Broken links on hydroshare site

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3413]
"[Paper]"
Page: https://help.hydroshare.org/introduction-to-hydroshare/hydroshare-youtube-videos/ 
**FIXED 9/1/2021 SS, link was broken, but updated in pages**

Link in _How do I set the spatial extent for a composite resource?_ section
Page: https://help.hydroshare.org/introduction-to-hydroshare/frequently-asked-questions/
Link broken: https://help.hydroshare.org/hydroshare-resource-types/composite-resource/
**https://help.hydroshare.org/hydroshare-resource-types/ does not exist**
**However _How do I set the spatial extent for a composite resource?_ section on https://help.hydroshare.org/introduction-to-hydroshare/frequently-asked-questions/ was updated with a better answer for setting spatial extent. Link was removed.**

https://hydroshare.org/resource/fbaadd419941400e9d5d88d1d85f62fa/ link at the bottom
Page: https://help.hydroshare.org/hydroshare-resource-types/web-app/
**https://help.hydroshare.org/hydroshare-resource-types/ is not a page, nor does the resource mentioned above exist.**
**This item will be ignored**

http://dx.doi.org/10.4211/hs.877bf9ed9e66468cadddb229838a9ced link
Page: https://help.hydroshare.org/creating-and-managing-resources/connecting-your-resource-data-with-your-publication/ 
**FIXED link made active 9/9/2021 SS, DOI link above was mentioned in text a few times, but not all were hyperlinked**

"Basic Time Series Analysis - Time Series Resource"
Page: https://help.hydroshare.org/apps/jupyter-python-notebook/
****this APPS page does not exist, but I believe the question is on the MODELING page, this question is also addressed down below in CyberGIS TauDEM. Basic Time Series links are broken** 

https://www.crwr.utexas.edu/reports/2016/rpt16-1.shtml link
Page: https://help.hydroshare.org/apps/data-rods-explorer/ 
**FIXED new link added 9/10/2021 SS, link to Katie Born's report was broken, but found a link that works, same report**

https://apps.hydroshare.org/apps/hydroshare-gis/ link
Page: https://help.hydroshare.org/apps/hydroshare-gis/
**Hydroshare-GIS is not a page, nor is HydroShare-GIS an app listed on the apps page, this was ignored**

CyberGIS TauDEM App
Page: https://help.hydroshare.org/modeling/
**maybe meant https://help.hydroshare.org/modeling/jupyter-python-notebook/
-TauDEM Hydrologic Terrain Analysis toolset
-Basic Time Series Analysis - Generic Resource
-Basic Time Series Analysis - Time Series Resource
need help finding links
Tony Castronova has been emailed 9/14/2021**

Reference Time Series
https://help.hydroshare.org/about-hydroshare/usage-metrics/
****This link does not exist: https://help.hydroshare.org/about-hydroshare/usage-metrics/
However, if "Reference Time Series" is the issue, this seems the more appropriate page, however no links are broken
https://help.hydroshare.org/hydroshare-resources/content-types/referenced-time-series/**

http://irods.org/wp-content/uploads/2015/09/UMG2015_P.pdf link (found an updated link)
http://www.iemss.org/sites/iemss2014/papers/iemss2014_submission_316.pdf link (no scholarsarchive.byu.edu link, but added Research Gate DOI link)
http://www.iemss.org/sites/iemss2014/papers/iemss2014_submission_243.pdf link (found a scholarsarchive.byu.edu link)
http://www.iemss.org/sites/iemss2014/papers/iemss2014_submission_259.pdf link (found a scholarsarchive.byu.edu link)
Page: https://help.hydroshare.org/about-hydroshare/publish/papers/
**FIXED Updated with all new links 9/10/2021 SS**

2014 and click on links
https://help.hydroshare.org/about-hydroshare/publish/presentations/
**https://irods.org/wp-content/uploads/2015/06/Tarboton-HydroShare.pdf **FIXED 9/13/2021 SS****
**http://www.awra.org/meetings/SnowBird2014/ deleted because not available**

https://ceen.et.byu.edu/sites/default/files/snrprojects/project_6.pdf link **MS report, no longer online**
**http://gradworks.umi.com/36/68/3668521.html link FIXED with new link 9/13/2021 SS**
Page: https://help.hydroshare.org/about-hydroshare/publish/theses/

http://www.hydroshare.org/resource/19b6d368956b443ca3f6539c01ea17aa link
Page: https://help.hydroshare.org/about-hydroshare/publish/proposals/
**FIXED with new link 9/13/2021 SS**

**Comment by eclark-cuahsi** [comment]
@jtpollak please address as part of your review user documentation review and close when finished. Thanks!

**Comment by dtarb** [comment]
@srclemens I started checking the fixes you indicated above, but started running into quite a few problems and was not seeing what you were referring to in some cases.  Here is how far I got, but lets work through this together.

On https://help.hydroshare.org/introduction-to-hydroshare/frequently-asked-questions/ 
![image](https://user-images.githubusercontent.com/3456833/134185953-b00d01a4-4d5d-4ad1-8e1a-cfaf0a33ec4c.png)

Link to https://help.hydroshare.org/hydroshare-resource-types/ needs to be fixed to https://help.hydroshare.org/hydroshare-resources/.  Also strive to use relative html links so that on pages the links are to pages and on help they are to help.

Also update the wording to avoid the term “resource types”

On https://help.hydroshare.org/apps/web-app/ 
Correct the link at the bottom to (current GABBs App)
https://www.hydroshare.org/resource/8e4efd86e06d4bdabd9a56753a6a1a57/ 

On https://pages.hydroshare.org/creating-and-managing-resources/connecting-your-resource-data-with-your-publication/ I am not seeing any differences relative to corresponding help page.  Not sure what was fixed.

I can not find the page that this comment refers to
"Basic Time Series Analysis - Time Series Resource"
Page: https://help.hydroshare.org/apps/jupyter-python-notebook/
jupyter-python-notebook is not a page, same question asked below

**Comment by srclemens** [comment]
@dtarb
On https://help.hydroshare.org/introduction-to-hydroshare/frequently-asked-questions/
Link to https://help.hydroshare.org/hydroshare-resource-types/ needs to be fixed to https://help.hydroshare.org/hydroshare-resources/. Also strive to use relative html links so that on pages the links are to pages and on help they are to help.


Also update the wording to avoid the term “resource types”
**Jeff suggested: For terms – you should use the term “resource” to refer to the resource container, “content files” to refer to files within a resource, and for specifically typed content files you can use “content types” which include geographic feature, geographic raster, etc.**

On https://help.hydroshare.org/apps/web-app/
Correct the link at the bottom to (current GABBs App)
https://www.hydroshare.org/resource/8e4efd86e06d4bdabd9a56753a6a1a57/
**FIXED 9/20/21 SS**

On https://pages.hydroshare.org/creating-and-managing-resources/connecting-your-resource-data-with-your-publication/ I am not seeing any differences relative to corresponding help page. Not sure what was fixed.
**There were a few DOI links that were not hyperlinked so the reader could not click on them**

I can not find the page that this comment refers to
"Basic Time Series Analysis - Time Series Resource"
Page: https://help.hydroshare.org/apps/jupyter-python-notebook/
jupyter-python-notebook is not a page, same question asked below
****Mentioned above, this is likely the page https://help.hydroshare.org/modeling/jupyter-python-notebook/
Because it is the only place that "Basic Time Series Analysis - Time Series Resource" is mentioned in HydroShare
This item, + the the last 3 links under Jupyter Notebook Examples are the items I emailed @Castronova about**

**Comment by martinseul** [comment]
according to Clara this has been completed, closing this. the page is still outdated and does need updating
