### ISSUE TITLE
‘How to Cite’ section

### ISSUE THREAD

**Issue by martinseul** [hydroshare/hydroshare#3427]
This came out of  discussion with Miguel and the CZO folks
 - Issues with the ‘How to Cite’ section?

 
How to Cite section auto-formats last names in a way where you cannot display two last names for one person, I had to add a hyphen which is not how the researcher would prefer their name to appear.
The year that the dataset is created in Hydroshare appears in the citation so our standardized title format we are translating from criticalzone.org will cause the ‘How to Cite’ section to display two years.
 

Example: https://www.hydroshare.org/resource/c646475a6c224f5d838f450ba0947f01/
 
How to Cite appears as:
Chapela-Lara, M., H. L. Buss, J. C. Pett-Ridge (2019). LCZO- Geology, Regolith Survey, trace and rare earth elements- Bisley and Icacos (2017), HydroShare, http://www.hydroshare.org/resource/c646475a6c224f5d838f450ba0947f01
 
It should be:
Chapela Lara, M., H. L. Buss, J. C. Pett-Ridge (2017). LCZO- Geology, Regolith Survey, trace and rare earth elements- Bisley and Icacos, HydroShare, http://www.hydroshare.org/resource/c646475a6c224f5d838f450ba0947f01

Another example: the person’s name is  Philip A.E. Pogge von Strandmann.  HydroShare shows it as: P. A. P. v. Strandmann
 
Chapela-Lara, M., H. L. Buss, P. A. P. v. Strandmann, J. A.Schuessler, O. W. Moore (2019). LCZO - Nutrient Fluxes -   Magnesium concentrations and isotopic signatures - Bisley (2009-2011), HydroShare, http://www.hydroshare.org/resource/043dccd3fa98474d8cdd15e42231a08d

**Comment by horsburgh** [comment]
@martinseul - there are two issues here, and I'm going to split out the author naming issue into a new issue because it is a legitimate problem.

The reported issue with dates is not an issue and is working as designed. HydroShare is a repository and a publisher of content. The date associated with the citation in HydroShare is associated with when the resource was created and/or published in HydroShare. It does not, and should not reflect when the data or content were originally created. When I submit a paper for publication, the date in the citation for the paper is the date on which the journal publishes the paper - not the date when I actually did the work described in the paper.

If users want years or date periods to appear in the titles of their resources, that is their prerogative to do so. However, HydroShare should not back-date its citation date to try and reflect anything other than when the content was entered into or published in HydroShare. So, the example above should be as follows, reflecting that the content was created in HydroShare in 2019. If the users want to have the 2017 date in the title to reflect that the data are from 2017, that's fine.

Chapela-Lara, M., H. L. Buss, J. C. Pett-Ridge (2019). LCZO- Geology, Regolith Survey, trace and rare earth elements- Bisley and Icacos (2017), HydroShare, http://www.hydroshare.org/resource/c646475a6c224f5d838f450ba0947f01

**Comment by miguelcleon** [comment]
@horsburgh 

> The reported issue with dates is not an issue and is working as designed. HydroShare is a repository and a publisher of content. The date associated with the citation in HydroShare is associated with when the resource was created and/or published in HydroShare. It does not, and should not reflect when the data or content were originally created. When I submit a paper for publication, the date in the citation for the paper is the date on which the journal publishes the paper - not the date when I actually did the work described in the paper.

I agree about the dates. We need to change our title naming convention to not include the years or make it more clear what they mean.
