### ISSUE TITLE
Static whitespace in groups page makes the page long

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3464]
The groups page could be substantially shorter if the whitespace was dynamic.  Currently, there are large blocks of whitespace - no content.

[007.zip](https://github.com/hydroshare/hydroshare/files/3335607/007.zip)

**Comment by devincowan** [comment]
I believe this is fixed as of [1.53](https://github.com/hydroshare/hydroshare/releases/tag/1.53)
![image](https://user-images.githubusercontent.com/17934193/157912440-2c152b1b-b23b-48fc-8a9b-d98ac08afb14.png)

**Comment by devincowan** [comment]
Actually, looking closer it appears this styling hasn't been updated since before this ticket was created. It just appeared that it had been resolved because many of the group profiles have been filled substantially since this ticket creation.

I would suggest that we reduce the height devoted to the the Group Descriptions from 250px to something closer to 100px. Here is a sample of what that change would look like:

BEFORE:
![image](https://user-images.githubusercontent.com/17934193/157921843-9408a3a9-8f3d-4d69-a9c2-423b67a429d8.png)

AFTER:
![image](https://user-images.githubusercontent.com/17934193/157921825-ac2e83ac-0d13-408a-a259-3786d248bfa1.png)
