### ISSUE TITLE
There appears to have been no data migration for LAST, FIRST author naming in resource lists, so there are naming inconsistencies for the same user.

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3469]
A user which has not changed their profile name could have resources published under both LAST, FIRST and FIRST LAST.  

[002.zip](https://github.com/hydroshare/hydroshare/files/3336864/002.zip)

**Comment by alvacouch** [comment]
In what context does this occur? It is not clear what you mean.

**Comment by alvacouch** [comment]
This is not necessarily a migration issue. There is a canonicalization of names in the lists. As I recall, at least for discovery, this is done dynamically. There is perhaps a bug in this.

**Comment by dtarb** [comment]
Here is an example of inconsistencies in resource lists
In my resources
![image](https://user-images.githubusercontent.com/3456833/63654497-21c27980-c738-11e9-8d93-39b0513d38b4.png)
but for both the above the resource landing page gives "David Tarboton"

The same inconsistency appears in home

**Comment by alvacouch** [comment]
@dtarb In discovery, I use a name canonicalization package to correct this in the lists, by computing a canonical "last, first middle" from "first last". That is done dynamically so that how people write names doesn't matter. It uses a publicly available name canonicalization library. 

The problem with migrating names is that to my knowledge, the UI still doesn't enforce a format. Has that been fixed? 

This problem could be fixed at the UI level by using the name canonicalization package installed for discovery.

**Comment by cuahsimarko** [comment]
@alvacouch If you point me to the code where this implemented, I can look into backend/frontend validation

**Comment by cuahsimarko** [comment]
Duplicated by https://github.com/hydroshare/hydroshare/issues/4035
