### ISSUE TITLE
Resource URL handling in science metadata

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hydroshare#347]
At resource creation (and perhaps at other times), we are storing a URL to each resource in that resource's science metadata in prepare_resource_default_metadata(), which can be found at hs_core.hydroshare.utils:308.  In general, we should not be storing URLs to HydroShare resources in the HydroShare database.  When URLs to resources are needed, they should be generated dynamically at request time.  One reason for generating URLs dynamically rather than storing them in the database is that if URLs are stored, then when resources are migrated from say beta.hydroshare.org to www.hydroshare.org, we then have to crawl through the database and update all URLs.

**Comment by horsburgh** [comment]
Or - we should just finally get http://www.hydroshare.org released!

**Comment by selimnairb** [comment]
But in test environments, the hostname will not be www.hydroshare.org ...

**Comment by horsburgh** [comment]
Yeah - but I think we want to get to the point where we are not migrating resources from testing environments to the production environment.  I think we make a bit of a contract with users that we will support what they create in our production system. I don't think we want to make that contract with our testing environments.  We will, of course, have to decide what to do with everything that is in beta.hydroshare.org now, but I think we should only do that one time.

**Comment by selimnairb** [comment]
Ignore what I said about migrating resources.  Always storing URLs to resources as beginning with http://www.hydroshare.org/... will make it impossible to fully test things in development environments.

**Comment by dtarb** [comment]
With respect to generating the resources science metadata XML file I think that the code should generate this based on the platform URL, so in testing on sandbox the URL generated would be sandbox.hydroshare.org.  This is OK since as Jeff noted we should not be moving resources across platforms.

With respect to migration from beta to production when we are ready, I suggest that www.hydroshare.org be initially set up as a separate site with no resources and no users leaving beta.hydroshare.org as it is.  Then we ask users in beta.hydroshare.org to re-create accounts in the new deployment and download any files they want to keep and then upload them in to the new deployment.  We may have to do some manual migration ourselves.  We need to keep beta.hydroshare.org around long enough to allow this to occur and provide plenty of repeated warning before decommissioning, perhaps with a phase where nothing can be added to it, but stuff can only be taken from it to encourage the migration.

**Comment by horsburgh** [comment]
The way @dtarb describes this is what I had in mind.  The URIs in the science metadata (and the Resource Map) should actually be resolvable to what they point at.  This is easiest if the URLs are encoded.

**Comment by danames** [comment]
Let's launch www.hydroshare.org soon.

**Comment by horsburgh** [comment]
Agreed - because the paper about the Resource Data Model we will submit to the JAWRA Open Water Data Initiative special section relies on there being a live www.hydroshare.org with some public resources in it.

**Comment by horsburgh** [comment]
@selimnairb - is this still an issue or can it be closed?

**Comment by selimnairb** [comment]
@horsburgh Issue #637 addresses this for the remaining resource type.  Close.
