### ISSUE TITLE
schema.org citation field fix

### ISSUE THREAD

**Issue by martinseul** [hydroshare/hydroshare#3479]
The Google team dataset also noticed:
that hydroshare.org is using the "citation" field to show citation snippet instead of the identifier of a related scholarly article (see https://developers.google.com/search/docs/data-types/dataset#dataset for more details). It might be worth correcting that to show richer results.

**Comment by horsburgh** [comment]
@martinseul - related to this, we should note that Google uses the *citation* element for "academic articles that are recommended by the data provider be cited in addition to the dataset itself". In their additional guidelines for this element it states that we should not be using this field to provide the citation for the dataset itself.

I believe that our current implementation provides the citation of the dataset. Instead, we should be providing the citation information for any related resources/references that the user has added to the resource. Likely, we will have to keep providing a citation snippet in this field rather than just an identifier because we allow HydroShare users to input whatever they want into the citation for a related resource (e.g., they could past in a URL or a full bibliographic citation for whatever the related resource is).

**Comment by martinseul** [comment]
@horsburgh @hyi Did we address this in our latest update to schema.org if so please close

**Comment by martinseul** [comment]
@horsburgh @hyi Did we address this in our latest update to schema.org if so please close

**Comment by horsburgh** [comment]
@martinseul - I just looked at this and verified that we are using the citation element to list related resources. So, I'm going to close this issue. 

I think another review of our schema.org implementation is probably in order based on the announcement of the latest guidelines from Science-on-schema.org: https://github.com/ESIPFed/science-on-schema.org/. I think we can do that in the context of our work to collaborate with DataONE.

Citation: Matthew B. Jones, Stephen Richard, Dave Vieglais, Adam Shepherd, Ruth Duerr, Doug Fils, Lewis McGibbney. (2021). Science-on-Schema.org v1.2.0 (Version 1.2.0). Zenodo. https://doi.org/10.5281/zenodo.4477164

Contributors: Adam Leadbetter, Dan Brickley, Richard Wallis.
