### ISSUE TITLE
NFIE Filtering

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#350]
For NFIE, Filtering will be moved from 1.6 to 1.5.1 NFIE Release

- It is n​ot​expected to be a problem to get a form of filtering done by NFIE summer camp June 1
- However, completing this by NFIE is only possible if no changes to underlying access control
are made (i.e. must keep single-user iRODS proxy-user approach in order to have filtering done by June 1)

**Comment by alvacouch** [comment]
Note: NFIE principals were quite specific that the ability to filter resources by file name (or part thereof) is important. For us, this becomes the resource title.

Alva L. Couch, Ph.D.
Senior Architect, CUAHSI Water Data Center
http://wdc.cuahsi.org
+1 339 221 5400 x 203

**Comment by rayi113** [comment]
@ironfroggy : @alvacouch , @hyi , @mjstealey , @rayi113  met on this Monday May 11 morning and decided do a simple hack to get this working by June 1, then afterwards we'll address refactoring.

**Comment by alvacouch** [comment]
The simple hack is to filter each resource subtype separately, and make a list of all matching resources of each type on the filtering page, rather than trying for a master list of resources of all types. This'll get us through NFIE and then we can refactor for making polymorphic lists of resources possible.

Alva L. Couch, Ph.D.
Senior Architect, CUAHSI Water Data Center
http://wdc.cuahsi.org
+1 339 221 5400 x 203

**Comment by ironfroggy** [comment]
Combined search, while inefficient, is already implemented. How is breaking them up, which represents additional work to be completed before the deadline on top of the new UI, a solution to any timeline problem posed by NFIE?

**Comment by rayi113** [comment]
@ironfroggy; @alvacouch, @dtarb and @rayi113 discussed and agree you should proceed with combined search as you suggest.

**Comment by alvacouch** [comment]
I am not worried about exactly how we do this, but I am of the opinion that:
a) we need simple filtering before NFIE, and
b) we need to delay the migration that would make filtering more elegant (e.g., resource base class)
until after NFIE. Too much else to handle. So that
c) a temporary fix is indicated.


Alva L. Couch, Ph.D.
Senior Architect, CUAHSI Water Data Center
http://wdc.cuahsi.org
+1 339 221 5400 x 203

**Comment by dtarb** [comment]
See #357 and #376.  I regard #376 as definitive for what Filtering should be.  I think that adding file name to filtering is a "nice to have" feature but a bit of a red herring and I do not understand @alvacouch indicating that the ability to filter by file name is important.  File name can certainly be used as title, but that does not require any change in the system, it is just user choice as to what to enter.

**Comment by alvacouch** [comment]
I mean filter by title, and it is an explicit NFIE request.

Alva L. Couch, Ph.D.
Senior Architect, CUAHSI Water Data Center
http://wdc.cuahsi.org
+1 339 221 5400 x 203

**Comment by dtarb** [comment]
Basic filtering has been deployed with 1.5.1.
