### ISSUE TITLE
Create geographic raster resource without file fails

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#36]
This is from testing alpha.hydroshare.org version 1.2.1

If I click Create Resource then set the resource type to “Geographic Raster Resource” then click Describe Resource without browsing for a file, I get an error.  This does not seem to be a problem with Generic resources or RHESSys resources.  It only occurs with Geographic rasters. We need to be able to support the use case where a resource is created and files added later.

**Comment by hyi** [comment]
I fixed the initial error that requires a file to be browsed initially for geographic rasters. However, since all those raster specific metadata fields such as rows, columns, etc. are all required fields, the final create-resource will raise errors indicating these fields are required for geo-raster resource. What is the best way to handle this case? Need guidance to proceed with further fix to this issue.

**Comment by dtarb** [comment]
Fields that are read and populated from the raster file should not be required to be populated for the existence of a resource, or should be populated with sensible null results.  E.g. rows = 0, columns = 0, CellSizeXValue = Unknown.  Then when a file is loaded these should be read from the file and updated.  If the file is deleted then they should go back to the sensible null results.  If the file is replaced (reloaded) then they get read and updated again.

**Comment by hyi** [comment]
This issue is now fixed and the fix is pushed to my feature 82-raster-resource-new-workflow branch with a pull request already created to be merged into develop. If no file is initially selected when creating raster resource, sensible null results are created for raster extended metadata elements. After a file is added into the resource later, the metadata elements will be extracted from the added file as part of the resource, and when the only file is deleted from the raster resource, the extended metadata elements are reset to sensible null results.

**Comment by dtarb** [comment]
Tested.  Closing
