### ISSUE TITLE
reorder tabs on groups landing page

### ISSUE THREAD

**Issue by martinseul** [hydroshare/hydroshare#3636]
The czo group would like to change the order of the Tabs when opening a groups page, They would like to move the "Resources" tab and switch it with the Overview tab and suggest renaming it to "recent activity" as Overview is unclear. Also the Resources page should be the tab that is active by default when opening the groups page. 
![image](https://user-images.githubusercontent.com/5427742/67515141-158d6680-f66c-11e9-9944-b7e23371922f.png)

It is an important change for the CZO's any thoughts or objections on implementing this @dtarb, @horsburgh, @Maurier, @cuahsimarko 

Thanks
Martin

**Comment by dtarb** [comment]
Looking at these tabs we see

- Under overview a listing of resources from latest to earliest with listing style that shows the person and abstract
- Under Resources there is a listing of resources from latest to earliest with a listing style more like in my resources.

Thus these are redundant.  I think we should pick one consistent listing style across all places where we list resources (home, my resources, discover, groups, ...) and use it under one tab here named resources.  Since the list under resources is closest to the others, the easiest way to achieve this would be to simply delete the overview tab.

I think the overview tab was originally intended to include types of events beyond sharing e.g. members joining or other collaborative activities.  But since we so far are not presenting any of these, it may be time to recognize that "Overview" is not needed and get rid of it.

**Comment by horsburgh** [comment]
I'm generally in agreement with @dtarb that the Overview tab isn't that useful. It isn't just a listing of resources, though, it's a listing of events and something of a feed for the group. If it will never have any more content than we have now (the listing of things that have been shared), I'm OK with letting it go. 

If it is kept, renaming it to "Recent Activity" and moving it over and making the "Resources" tab the active tab when you first visit the group are fine with me.

Part of the reason the "Overview" tab isn't that useful is because it's a feed of activity that nobody ever really sees. You actually have to visit the group's page to see that activity as there are no notifications that get sent to group members when things happen. I'm not saying I really want to get a bunch of emails from HydroShare, but a more effective way to let group members know that something has happened in their group (i.e., so-and-so shared a new resource with the group) would be to send a notification to the group members.

**Comment by cuahsimarko** [comment]
I think we should get rid of the Overview tab. Is this inline with everyone's thinking? @dtarb @horsburgh

**Comment by horsburgh** [comment]
I'm OK with letting the Overview tab go.

**Comment by martinseul** [comment]
OK same here, so we  will go ahead and remove the overview tab and make the resources page the default landing page.

**Comment by cuahsimarko** [comment]
@dtarb @horsburgh in this issue, we discussed removing the Overview tab. One detail that this design discussion failed to capture is that if the logged in user is not a member of the group, then the Overview tab contains an "Ask to join" button.

1. I'm trying to develop better processes for design conversations other than GitHub Issues. I'll reach out with some ideas later. We may be stuck with GitHub Issues as the best possible/realistic team tool for now.
2. Should we revive parts of the Overview tab or simply move the join button to the Members tab, which could get quite busy. Perhpas there are other reasonable options. Please advise. 

![image](https://user-images.githubusercontent.com/45397838/68698522-09037c00-054f-11ea-9c8d-f43807d3eada.png)

**Comment by dtarb** [comment]
There needs to be a product owner for each page whose responsibility is to know and be aware of all ramifications and to make these decisions holistically.

**Comment by cuahsimarko** [comment]
@dtarb @horsburgh @martinseul I recommend we move the Ask to join page to the Resources tab, as that is the place where you would see a message that either no resources are shared or you don't have access to them. Going to the Members tab may be less intuitive.

**Comment by horsburgh** [comment]
Taking a step back - doesn't it make sense that the button to ask to join the membership of a group be on the Members tab? If we are not showing the list of resources to non-group members, couldn't we improve the message on the Resources tab to say something like - "You are not a member of this group. To make a request to become a member of this group, go to the "Members" tab."

**Comment by cuahsimarko** [comment]
Since the Resources tab is the first view, it makes sense to allow a person to take action directly in that pane. Knowing that they are already there and asking them to go somewhere else to click is not best practice. We can put it in both locations if you feel that people will ignore the Join button in the Groups listings, click on the Group and ignore the Join button on the Resources listing and drill down to Members, only to join there...

**Comment by cuahsimarko** [comment]
@horsburgh do you want the Join button in all three locations?

**Comment by cuahsimarko** [comment]
This is what I had in mind for placing the Join button in two spots

![image](https://user-images.githubusercontent.com/45397838/68809493-0d589380-063a-11ea-83a1-125ac5be2e99.png)
![image](https://user-images.githubusercontent.com/45397838/68809519-177a9200-063a-11ea-86ab-c7dd7b923c2e.png)
This is because if the group is private, there is no members tab...

**Comment by cuahsimarko** [comment]
![image](https://user-images.githubusercontent.com/45397838/68809726-82c46400-063a-11ea-8742-5c87389d85af.png)

**Comment by horsburgh** [comment]
@cuahsimarko - I think your proposed solution is fine. If you want code review, you should ask @Maurier He did the original groups work.
