### ISSUE TITLE
"Open with" not working for unapproved apps

### ISSUE THREAD

**Issue by martinseul** [hydroshare/hydroshare#3637]
A user asked about the process to add an unapproved app to the "Open with" dialog. As i understand t would go like this 
1. identify web app resource e.g. Taudem
https://www.hydroshare.org/resource/ecf520160f50423f82d025e140abcc48/
2. To add this unapproved app to OpenWith, user needs to manually click the icon in the upper-right corner. Note this only applies to this logged in user (not a system-wide action)
 <img width="586" alt="Open with" src="https://user-images.githubusercontent.com/5427742/67516488-bd0b9880-f66e-11e9-9458-f39c9b40ccb2.png">
thenit should show up in the open with dialog.

I tried this and the app does not show up. Am I missing something or is this a regression. @dtarb, @horsburgh, @Maurier, @danames

**Comment by danames** [comment]
I think the problem is that the TAUDEM app landing page doesn't show what
resource types it opens. So in order for the "open with" button to work,
then the web app resource needs to indicate what types of resources it can
open. @dtarb can you check this app?
**********************************************************************
Daniel P. Ames, Ph.D., P.E.
Professor, Civil & Environmental Engineering,Brigham Young University,
Provo, Utah, USA
President, International Environmental Modelling & Software Society
Editor-in-Chief, Environmental Modelling & Software
http://ceen.et.byu.edu/faculty/person/Daniel-P.-Ames
<http://ceen.et.byu.edu/content/dan-ames>
http://www.researchgate.net/profile/Daniel_Ames
http://scholar.google.com/citations?user=S0GUCeUAAAAJ

**********************************************************************

**Comment by danames** [comment]
@David Tarboton <dtarb@usu.edu>  @dtarb I think you may need to change the
TAUDEM app to support "composite" resource types.
**********************************************************************
Daniel P. Ames, Ph.D., P.E.
Professor, Civil & Environmental Engineering,Brigham Young University,
Provo, Utah, USA
President, International Environmental Modelling & Software Society
Editor-in-Chief, Environmental Modelling & Software
http://ceen.et.byu.edu/faculty/person/Daniel-P.-Ames
<http://ceen.et.byu.edu/content/dan-ames>
http://www.researchgate.net/profile/Daniel_Ames
http://scholar.google.com/citations?user=S0GUCeUAAAAJ

**********************************************************************

**Comment by dtarb** [comment]
@martinseul I believe the system is working correctly.  The particular app you give does not have any resource type set for it.  

For example.  Go to https://www.hydroshare.org/resource/c477900488744e4a8e1df21326e4789b/.  This is a web app connector from Dandong.  Click the green button.

Go to https://www.hydroshare.org/resource/b6807d9df60a48babbdb18f1f9094830/.  Now CyberGIS Jupyter appears on the open with menu.

I do not want to change the TauDEM app that you picked as an example to work with any resource type, because the app has been decommissioned (as part of the decommissioning of ROGER).  If I was owner of that resource, I would delete it.  @yanliu@ornl.gov if you get this can you please delete the resource https://www.hydroshare.org/resource/ecf520160f50423f82d025e140abcc48/

**Comment by dtarb** [comment]
This is stale and as far as I know not an issue.
