### ISSUE TITLE
Address and homepage do not show in Author details modal

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3652]
Go to a resource and click on the author.  The information shows an address and homepage, but these aren't being pulled from the profile and are incorrectly blank in the author modal.

[004.zip](https://github.com/hydroshare/hydroshare/files/3802544/004.zip)

**Comment by devincowan** [comment]
@horsburgh and @Castronova 

It is true that, if address and homepage are entered on the user profile
![profile](https://user-images.githubusercontent.com/17934193/154343530-e2275689-51c6-4adf-b39b-78da37a97b7d.png)

and that user is added as an author for a resource, then the address, homepage, phone, etc show blank in the modal on the resource page:
![blank_author_resource](https://user-images.githubusercontent.com/17934193/154343579-438e63e9-e951-4fca-a40b-7f184501ed72.png)

However, if author info is added while _editing the RESOURCE_
![edit_author_resource](https://user-images.githubusercontent.com/17934193/154343633-eff303f1-4dea-4618-8fe6-7cd3f2553da3.png)


then that info persists and is shown at the resource level
![populated_author_resource](https://user-images.githubusercontent.com/17934193/154343659-d45cbe20-fc87-4f88-b137-7e3dc6dacdca.png)
but does not update the profile info

### So my question is: What is the desired final behavior? 

- Might there be a case where an author desires different affiliation and contact info to be added on different resources? Authors publish articles under different affiliations and it would be odd to have to create multiple HS users for one person just in order to allow for different affiliations on resources.
- The counter argument: it is tedious to add author info for every author on every resource instead of pulling it from the user's profile.

Perhaps we could initially populate author info from the user profile but then allow for modifications at the resource level? Other ideas? Thanks

**Comment by Castronova** [comment]
My general thought is that the profile information displayed on the resource landing page should directly reflect the metadata stored in the HydroShare user profile. If it doesn't, there are some strange edge cases we may encounter such as a resource displaying contact information that is no longer valid even after the user has updated their profile, e.g. a deactivated student email address. It would be nice to track organizations/affiliations using start and end dates in the profile similar to past work history in LinkedIn, but this would be part of a larger feature design.

On the other hand, if a resource was created and published while the owner was affiliated with one organization and later changes career positions, does the resource now display the incorrect organization? Maybe, but if the resource directly relates to or is the property of a previous organization/affiliation, they can become the new owner of the resource. This is analogous to the student/advisor relationship in which the student graduates and the advisor retains control of the resource.

I think there could be value to "freezing" the authorship for published resources somewhere on the landing page similar to how the Contributors section works. This would capture the organizations and affiliations that participated on a project and would not be lost when user profile metadata is updated. I'm not sure how this is handled for published resources, perhaps @horsburgh can offer some insight here.

I'm not entirely sure what the "correct" answer is, but I lean towards having the authorship/ownership metadata directly reflect the metadata in the user's profile. As you mentioned, it is tedious to add author info on every resource and this would help ensure that resource authorship metadata is both provided and up-to-date.

On a side note, why is the Author metadata displayed differently than the Owner metadata? If anything, I find the latter to be more useful. It also appears to have different metadata displayed, e.g. location, subject areas, contributions, etc.

![image](https://user-images.githubusercontent.com/4822372/154353648-09707e9a-1329-43e9-91ed-87423d06cde8.png)

![image](https://user-images.githubusercontent.com/4822372/154353677-80f0760e-7d00-4a4d-a417-5efb728c32b1.png)

**Comment by horsburgh** [comment]
The current functionality of freezing author information in the resource's metadata at the time it is created was by design. When you publish a journal paper, your contact information is captured at the time of publication, and after that doesn't change. We designed the system to adopt that model. You can edit/change author information all the way up to resource publication. After publication, the author information is set. We don't want to change it after publication because we don't want the citation for a published resource to change.

This means that when a HydroShare user is added to a resource as an author, we copy the metadata from that user's profile into the resource's author metadata. I haven't checked to see if all of the author information is copied with fidelity, but the desired functionality is that if the Author's information is specified in their profile it should get copied to the corresponding Author metadata elements (recognizing that not all profile metadata appears in author metadata). Again - author metadata can be updated at any time prior to publication by removing the author and then adding them again (creates a new copy of the Author metadata from the profile) or by manually editing.

The page views of the Author versus Owner information are different because the Owner MUST be a HydroShare user and, therefore MUST have profile information. The view of Owner information is based on the Owner's profile.

Not every Author is a HydroShare user and so the Author display is whatever metadata has been copied from the user's profile (in the case that the Author is a HydroShare user) or has been input by the resource creator/editor (in the case that the Author is not a HydroShare user or the author is an organization). Author metadata elements are set, and consist of a subset of what is in a HydroShare user's profile. 

The views of Author information versus Owner information could maybe be more standardized, but I don't think we want to change the basic functionality because we need to support both cases where Authors are HydroShare users versus those that are not. Additionally, people can deactivate their HydroShare account, which is another reason to make sure we copy their information into the resource's metadata when they are added as an author because we can't guarantee that a user's profile will be available forever.

**Comment by Castronova** [comment]
@horsburgh Thanks for clarifying the design. I understand that user profile metadata should be frozen when a resource is formally published, but it's not clear to me why that would be the case for non-published, mutable resources. Do we run the risk of this information becoming inaccurate by doing so? I wonder how many people ever edit authorship metadata on non-published resources, and how many users even know that they need to (I wasn't aware).

I agree that Author information must support metadata for non-hydroshare users, but I think that standardizing our UI so that both Authorship and Ownership dialogs are styled consistently and have the same metadata fields would be beneficial. This is beyond the scope of this particular issue though.

**Comment by devincowan** [comment]
Thanks to both of you for the info and background (and sorry if I should be asking elsewhere, I started with you since you were already on this ticket).

I see what @horsburgh is saying re the desired functionality--right now this is indeed broken: the initial sync from the profile metadata into the author info on the resource is broken for address, homepage, and other fields. So I can fix that initial sync.

And it makes sense to me that we want the author info on the resource to be editable up until the resource is published, but importantly those edits are NOT synced back to the profile.

Regarding the UI for authors vs owners, that is beyond this ticket but seems like a reasonable suggestion for a different ticket/issue.

**Comment by devincowan** [comment]
Walking back what I said earlier today. The desired functionality that @horsburgh mentioned actually is functioning. That is to say that, when an author is first added to a resource, said author's profile info is used to populate the resource's author info (to the extent that the added author's profile contains information). So I believe this issue is actually a non-issue...

**Comment by devincowan** [comment]
@Castronova one additional though on this that gets at some of your suggestions:
Like I said, initial population of author info from profile is functional already.
But perhaps we should entertain the following:
- When profile info is added or modified
- All _unpublished_ resources on which the updated profile is an author are updated with the new info, so long as they haven't already been custom edited on that resource
- If the author info has been custom edited at the resource level, that custom author info is retained in preference to the profile update

**Comment by horsburgh** [comment]
@devincowan and @Castronova - I think we should exercise care here to not do something that is going to require sifting through large numbers of resources regularly. For example, if a HydroShare user updates their profile, do we really want to sift through all HydroShare resources and test to see if the user is an author of the resource and check to see whether the Author's information needs to be updated?  Also, what if the user that is the Author updated their profile, but do not want to update the author information in all resources across the board? Just because a resource is unpublished does not necessarily mean that users want Author information in their resources to change automatically.

I think adding authors and their information should be deliberate. I also think updates to author information in a resource should be deliberate. Perhaps rather than an automated update based on a profile update, we should consider a button or something in edit mode for a resource to update an Author's information from their profile (rather than removing and re-adding). Clicking such a button would be a deliberate choice to update an Author's information and would only be available for unpublished resources.

**Comment by devincowan** [comment]
@horsburgh I have little experience but the idea of a button that allows for deliberate update of author info on unpublished resources seems to me a good way to go.
