### ISSUE TITLE
Scripting Error on Page Load

### ISSUE THREAD

**Issue by cuahsimarko** [hydroshare/hydroshare#3675]
When logging into hydroshare, the landing page shows

Production
![image](https://user-images.githubusercontent.com/45397838/68867386-b9928c80-06c3-11ea-89f6-bebf70f2bd3a.png)

Dev7
![image](https://user-images.githubusercontent.com/45397838/68867292-9536b000-06c3-11ea-9901-772917b5532a.png)

This is in beta and all other environments, including local developer setups.

Similar 404 js.1.27 errors appear on every HydroShare page

**Comment by sblack-usu** [comment]
removed with the PR mentioned above.  @cuahsimarko has expressed that he feels django-freshly might present more problems than it solves.  Since he leads the frontend development effort, I'm following his advice and removing it.  I've logged an issue with the django-freshly repo with a test that reproduces this bug at https://github.com/un33k/django-freshly/issues/2.
