### ISSUE TITLE
iframes and other injected html can be used in resource additional metadata

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3685]
For example using '<iframe src="google.com"></iframe>' as for additional metadata actually renders the iframe in the user interface.

[002.zip](https://github.com/hydroshare/hydroshare/files/3867040/002.zip)

**Comment by Castronova** [comment]
related to #3684 and #3683

**Comment by sblack-usu** [comment]
I did some investigation on this and it revealed a couple of things.  The iframe is only showing when in edit mode.  At some point, the javascript removes the html and attempts to save it, even if the sanitized key results in an empty string.  The backend will accept and save the key/value with an empty string key and respond with a 200.  The empty string key doesn't appear to actually be saved in the extra_metadata HStoreField (because of the empty string) and no key/value is ever saved to the database.

1. Update the javascript to either block saving unsafe strings or sanitize the string and show it to the user before saving.
2. Update the backend to not send a 200 response when an empty string key is provided.

**Comment by Castronova** [comment]
![image](https://user-images.githubusercontent.com/4822372/131362270-63e455ac-d7bc-42fe-b70f-746d8b1aef11.png)

**Comment by sblack-usu** [comment]
This is image is relevant to #3684, not this issue.
> ![image](https://user-images.githubusercontent.com/4822372/131362270-63e455ac-d7bc-42fe-b70f-746d8b1aef11.png)
