### ISSUE TITLE
Implement get_modified_time in IrodsStorage

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3766]
Implement the `get_modified_time(self, name)` method of the Storage class that IrodsStorage implements.  

```Return the last modified time (as a datetime) of the file specified by name. The datetime will be timezone-aware if USE_TZ=True.```
        
This will be used in api calls to retrieve the modified times of files.

**Comment by hyi** [comment]
@sblack-usu Do we really need to make file modified time time zone aware? Since all files are stored in iRODS with file modified time managed by iRODS, to compare file modified time, wouldn't it be easier just to use the file modified time uniformly managed by iRODS without the complexity of time zone? In fact, for the purpose of comparing file modified time, I think timezone will only complicate things without adding any benefit unless I misunderstand the intended usage for this method. What do you think?

**Comment by sblack-usu** [comment]
I'm fine with not implementing timezone awareness.  I Just pulled the documentation for the method in the Storage class, which specifies this parameter.  Just throw a Not Implemented error if USE_TZ=True.

**Comment by hyi** [comment]
@sblack-usu Got it. Instead of throwing a Not Implemented error if USE_TZ is set to True, I'll just ignore USE_TZ setting and always return a datetime object in local time, i.e., US/Eastern timezone. The reason for that is USE_TZ is set to True in HydroShare but TIME_ZONE is set to None, so even though USE_TZ is set to True in HydroShare, the time managed by Django is not really time zone aware. I also looked into iRODS code implementation for file modified time and got to know that the time returned from iquest is a unixtimestamp value, and ```ils -l``` returns a local time in US/Eastern timezone. So I will just return a datetime object in US/Eastern timezone, consistent with the time displayed in ```ils -l```.

**Comment by hyi** [comment]
@sblack-usu On second thought, I think it is better to return the time in UTC timezone in get_modified_time() so that the caller can normalize to whatever local time zone as desired.

**Comment by sblack-usu** [comment]
UTC makes sense.  Pretty sure that's the timestamp for resource modified

**Comment by hyi** [comment]
Implemented and deployed. Closing.
