### ISSUE TITLE
"How to cite" 

### ISSUE THREAD

**Issue by martinseul** [hydroshare/hydroshare#3767]
We received this issue from a user from Germany! 

Hello,
I'm a little bit unhappy with the the "How to cite" from this resource
https://www.hydroshare.org/resource/2f2c2fa04e6e417ba0eb7b0fb14b1090/
I wonder if you can help me to change the entry.
Now it reads as:
Büttner, O. (2020). DE-WWTP - collection of Germany's waste water treatment plants (status 2015), http://www.ufz.de/record/dmp/archive/7800/en/, last accessed 2/19/2020.
I don't know how the link was created in this citation, I don't want it there.
I would like to have it as
Büttner, O. (2020). DE-WWTP - collection of Germany's waste water treatment plants (status 2015), HydroShare, https://doi.org/10.4211/hs.2f2c2fa04e6e417ba0eb7b0fb14b1090
Thanks a lot in advance,_
Dr. Olaf Büttner Helmholtz Centre for Environmental Research_ 

and this appears to be a bug.

**Comment by hyi** [comment]
@martinseul @dtarb @horsburgh I investigated this issue and know exactly why the citation for this published resource is dynamically created as ```Büttner, O. (2020). DE-WWTP - collection of Germany's waste water treatment plants (status 2015), http://www.ufz.de/record/dmp/archive/7800/en/, last accessed 2/19/2020.``` rather than ``` Büttner, O. (2020). DE-WWTP - collection of Germany's waste water treatment plants (status 2015), HydroShare, https://doi.org/10.4211/hs.2f2c2fa04e6e417ba0eb7b0fb14b1090```. The reason is that this published resource has a ```isHostedBy``` relation, and the get_citation code create a citation as the user sees currently for this resource to put ```isHostedBy``` URL value into citation, which sounds wrong to me. The get_citation code also checks "isCopiedFrom" relation and if that relation is true, it creates another form of citation indicating this resource is replicated in HydroShare. In short, standard citation format only shows when isHostedBy and isCopiedFrom relations don't exist. I can easily change the logic to not consider these two relations, but thought there might be a design decision behind the current implementation for citation which I am not aware of. So I will need your input before updating get_citation() code to address this issue.

**Comment by dtarb** [comment]
@hyi thanks for investigating.  Now that you have found it out, I do remember this as a design decision.  We worked on this together in 2015 - see #488

The thinking at that time was that if the content was hosted elsewhere, that the other site was the primary source and should receive the citation.  I believe that this principle still holds in this case.  The primary data is held in the Helmholtz center repository.  The content in HydroShare serves the following potential purposes
1. A reference to the data in the Helmholtz center repository.  This can enhance discovery.
2. A description of the procedure used with the Helmholtz center repository data.  

Regarding item 1. I think a proper citation for the data could be
Büttner, O. (2020). DE-WWTP: German waste water treatment plants (2015), location, yearly nutrient loads, http://www.ufz.de/record/dmp/archive/7800/en/, referenced in HydroShare, https://doi.org/10.4211/hs.2f2c2fa04e6e417ba0eb7b0fb14b1090
We should consider amending the formulation of How to Cite in cases where there is a "the content of this resource is hosted by relationship" to the above.  However there are some potential issues and points to note
- if there is more than one "hosted by" relationship - what to do 
- The citation is misleading if the author does not use the same title for the HydroShare resource and the original resource.  We have no way to validate this and at best can encourage as a best practice and check at a time of permanent publication if a DOI is being generated, and we are doing manual content checking.
- HydroShare has no control over what happens at the referenced hosted by URL, thus it is questionable whether a DOI should even be issued for this reference.  The last accessed phrase in the citation seems intended to address this, but seems odd built into a how to cite. 
- We have reference resource aggregation functionality in HydroShare.  Perhaps the reference to the Helmholz center repository should be stored in one of these aggregations, rather than in text in references.  I was unable to come to a decision on what I think is best.  


Regarding item 2.  I think the resource should not present itself as a collection.  Rather it should present itself as the procedure used in preparation of the collection.  This would be done by changing the title and references.  The data object in HydroShare is the "procedure.txt" file which is presented as a procedure to describe and refer to the data collection in the Helmholtz center repository.  A proper citation might be

Büttner, O. (2020). Procedure used in preparing DE-WWTP: German waste water treatment plants (2015), location, yearly nutrient loads data collection, HydroShare, https://doi.org/10.4211/hs.2f2c2fa04e6e417ba0eb7b0fb14b1090 

The contents would then reference the primary source using a "This resource cites" reference 

Suggestions
1.  I think we should amend the automatically formatted how to cite to drop the last accessed phrase and adopt the wording "reference in HydroShare" providing both URL's suggested above (item 1).
2.  In cases where there are more than one hosted by relationships do not include any of them in the how to cite field.  i.e default back to the simple how to cite pattern used in HydroShare.
3.  We should discuss this with Olaf Buttner who initially raised this question.  He is at the Helmholtz center, quite a well known data center in Germany and they may have good ideas for how to handle cases like this that reference their data. 
4.  The title of the resource https://www.hydroshare.org/resource/2f2c2fa04e6e417ba0eb7b0fb14b1090/ should either be changed to exactly the same as the Helmholtz repository archive (following item 1 above) so that the citation is correct, or it should be changed to be descriptive of the content being the procedure (item 2) and the "hosted by" relationship removed.  Since the resource is already permanently published, a CUAHSI administrator will need to make these changes after concurrence from Olaf Buttner.  
5.  These suggestions should be reviewed and agreed to by @horsburgh as he is the product owner of the resource data model, before they are implemented.

**Comment by cuahsimarko** [comment]
@martinseul Will Custom Citations give users like this the desired functionality or is something else at play?

**Comment by horsburgh** [comment]
@cuahsimarko and @martinseul - the new citations work will address this issue. We have purposefully broken the links that existed between related resource metadata and the citation. HydroShare will no longer inject custom text into the citation when a user adds these types of related resources. Citations will only change when referenced content aggregations are added to the content area of the resource AND the user chooses to create a custom citation.

So, the citation for this resource would follow the default policy we have set for citations.
