### ISSUE TITLE
User account creation problems

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3794]
A user reported an inability to create a HydroShare account.  I checked the users admin page and there are dozens of unactivated accounts since March 11, suggesting we have a systemic problem in account email verification.

**Comment by cbcunc** [comment]
I have verified by direct login to outlook.office365.com that the password for hydroshare@cuahsi.org has changed.

I further verified in the Django logs that this change took place on March 11.

Whoever at CUAHSI administers the hydroshare@cuahsi.org needs to perform a password reset, update Phu's document entitled email.txt in our Hydroshare team Keybase folder with the new password, then notify @sblack-usu and myself so that we may update the credentials on production.

**Comment by cbcunc** [comment]
@martinseul reset the password. I installed it in local_settings.py on zdt, w1, and w2, then restarted both workers. Verified working by myself, @martinseul, and @sblack-usu. Jon Pollak has already manually activated the users who didn't receive an email and notified them.
