### ISSUE TITLE
Enhancement to group joining functionality

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3806]
The following is suggested based on discussion of groups and using them to enable app whitelists

1. When a user clicks "Join" to request group membership, a window should open "Please Justify your request" with a text box for a user to fill out.  This text should be included in the email to group owners.  
2. Optionally as one of the properties of a group there be a check box (defaulted on) indicating whether a Justification text is required or not.  If not, the behavior would be unchanged from present.

**Comment by Castronova** [comment]
Pasting a template that we discussed in a separate document:

**Subject:** Request to join HydroShare group: \<group name\>

> Dear \<group owner first name\> \<group owner last name\>,
>
> User \<user first name\> \<user first name\> (\<link to user profile\>) has requested to join your HydroShare group <hydroshare group name>.
>
> \<justification text user entered in membership request\>
>
> User Type: \<user type\>
> User Title: \<user title\>
> Organization: \<user organization\>
> Country: \<user country\>
> State/Province: \<user state\>
> Email: \<email address\>

> Click on the link below to accept this request.
> https://www.hydroshare.org/hsapi/_internal/group_membership/5lmf41e2bc5e5913f494b70/2/2570/?next=/

**Comment by devincowan** [comment]
Discussed today we will add additional UI for group admin: 
checkbox whether justification should be required for requests
Then add associated justification during request submit

**Comment by dtarb** [comment]
@devincowan @Castronova @martinseul sorry to just be bringing this up now while this is in review, but it may have been brought up before.  I would like to discuss setting reply to addresses associated with the emails that are sent from HydroShare.  I was reminded of this need, because I just received an email from someone who had been admitted to the CUAHSI compute group saying thank you.  This email was sent to hydroshare@cuahsi.org.  It would have been better if it had gone to the person who approved the group admission (group owner).  But we need to be careful about this because different from and reply to addresses are sometimes filtered to spam and I think we can only use hydroshare.org or cuahsi.org email addresses in from.  It would be good for someone with email knowledge to carefully look at this.  

My suggestion is the following:

User requests to join a group.  The email should indicate Reply to as the email address of the user.  

User is admitted to a group.  The email notifying the user should have reply to be the group owner (perhaps a primary group owner if there are multiple owners, or the owner that does the admitting).

User is sent an invitation to join a group.  The reply to should be the user initiating the invitation.

Email to group owner when user joins or accepts a group membership request should have reply to be that user.

**Comment by devincowan** [comment]
@dtarb makes sense to me I propose we address as a separate issue? Created one here:
#4546

**Comment by devincowan** [comment]
@ClaraCogswell I'm requesting your help for some messaging related to this issue.
I have an open PR here: #4544 
Right now it requests "JUSTIFICATION" text when a user asks to join a group. The dev team suggested that you might have good suggestions for better messaging. Perhaps "explanation" or similar instead of "justification?"
![image](https://user-images.githubusercontent.com/17934193/158210131-f5ba561e-c2e1-4713-b585-1e8012fac111.png)

**Comment by ClaraCogswell** [comment]
I agree this language is not welcoming/ does not suggest the collaborative environment that the groups functionality tries to promote. Maybe instead of "this group requires you to submit a justification" it could be "This group (requires/requests) an explanation of interest in membership, prior to membership request approval" and instead of "Justification" as the pop-up header, it can say "Explanation of interest" if there is space for that many characters.

**Comment by devincowan** [comment]
thanks @ClaraCogswell that looks great to me!
I updated the wording: https://github.com/hydroshare/hydroshare/pull/4544/commits/fd2c94c60020da911f8e66363736a5b1af423621
