### ISSUE TITLE
Add web service endpoints to content-level metadata for geographic feature and geographic raster content types - GeoServer

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#3825]
For some content types, standards-based web services are automatically created when a content aggregation of those types is created within a resource. Under this issue, we will add links to automatically generated services within the content-level metadata for geographic feature and geographic raster content type aggregations. Details of our discussion and the design are in the following Google Doc:

https://docs.google.com/document/d/1ZFFQMltaM01xlfBusw-TolT5sf5fUulVRU_XLPT3XEQ/edit#

The following are needed for this issue:
- [x] Add links to Web Map Service and Web Feature Service for Geographic Feature Aggregations
- [x] Add links to Web Map Service and Web Coverage Service for Geographic Raster Aggregations
- [x] Create a button for copying the service URLs
- [x] Create a button for launching a preview of the content aggregation using the existing GeoServer OpenLayers implementation
- [x] Display links and buttons in the content-level metadata pane for the aggregation

These additions will not affect the resource or content-level metadata encodings as the needed URLs will be built on the fly according to the rules in the Google Doc.

**Comment by kjlippold** [comment]
@danames @horsburgh @Maurier 

Based on the google doc and commits so far, it looks like the plan is for HydroShare to automatically generate these endpoints for all public resources containing geographic feature or raster content. We need need to be careful about how we go about this.

With the current setup, HydroShare will send a resource registration request to an intermediate service (the web services manager) when certain conditions are met. The web services manager will go through the resource and attempt to register all geographic feature and raster data in that resource on GeoServer. It will then return a response to HydroShare containing the endpoints if it was successful, or an error message if not. However, right now HydroShare doesn’t do anything with this response because there are no metadata fields to store that response in. Initially, we were going to try using additional_metadata, but that is meant to be used by the user, not the HydroShare system. (I discussed this with Alva last year)

With this setup, HydroShare is completely unaware of whether or not services are actually available through GeoServer for a given resource. It can automatically generate what the endpoints should be, and it can know whether or not conditions have been met where the services should be available, but it can’t verify that they are actually available. The most likely scenario would be the web services manager running into an issue and being unable to register the resource on GeoServer. In this case, there needs to be a way for HydroShare to know that the resource isn’t registered so it doesn’t provide broken endpoints to the user.

I think there are two ways to go about this. The first would be to add some metadata fields to HydroShare for storing the status of the services, and maybe the endpoints themselves. At a minimum, at the aggregation level, we’d want wms_service_available, wfs_service_available, and wcs_service_available. Those fields would all be False by default, and be set to True after HydroShare receives a response to the registration request saying it was successful. HydroShare would only generate and display endpoints for resources that have files with any of those flags set to True.

The second way would be to create another web services manager endpoint called verify_registration. HydroShare could use this endpoint to verify GeoServer registration before generating and displaying any endpoints. I don’t like this solution as much as the first one for several reasons, but it would be better than displaying the endpoints without any verification at all, and would probably be quicker to implement since I don’t know how difficult it would be to add the extra metadata fields to HydroShare.

Please let me know your thoughts about which direction to take.

**Comment by horsburgh** [comment]
@kjlippold - If HydroShare gets an error message back from the web services manager that the service endpoint(s) were not created successfully, what should happen? Should the creation of the aggregation fail because the creation of the service endpoint(s) failed? 

I agree that we don't want to expose URLs for service endpoints that do not exist in GeoServer because they were not created. If creation of the service endpoint fails because the data are not valid, then the aggregation should not be valid either. However, if the creation of the service endpoint failed because GeoServer choked, then how can we remedy this to get a valid service?

**Comment by kjlippold** [comment]
@horsburgh The creation of the aggregation shouldn’t fail only because the service endpoint creation fails. In most cases, if it fails it’s either because of an issue with the file name, or a missing CRS definition on GeoServer. It would probably be frustrating for a user to have to change the file name, so that and most other issues should be considered bugs that we’d need to resolve. For unsupported CRS definitions, we can either add it to GeoServer, or just tell the user that it’s unsupported. We’d probably only want to add a new CRS if it’s commonly used by HydroShare users.

Regardless of what causes the error, we could either not show the user anything, or display a message somewhere saying that the services aren’t available and why. I don’t know the best place to put that message, but maybe a banner message on the resource edit screen. We’ll also want to log the error of course.

But before that can happen, I need to know whether we can store that error information in HydroShare, or if HydroShare needs to get it from the web services manager every time the resource is accessed.

**Comment by danames** [comment]
I'd lean toward storing a flag in the resource metadata indicating that the
web service either is or isn't available.
**********************************************************************
Daniel P. Ames, Ph.D., P.E.
Professor, Civil & Environmental Engineering,Brigham Young University,
Provo, Utah, USA
Past-President, International Environmental Modelling & Software Society
Editor-in-Chief, Environmental Modelling & Software
http://ceen.et.byu.edu/faculty/person/Daniel-P.-Ames
<http://ceen.et.byu.edu/content/dan-ames>
http://www.researchgate.net/profile/Daniel_Ames
http://scholar.google.com/citations?user=S0GUCeUAAAAJ

**********************************************************************

**Comment by danames** [comment]
Meeting with the BYU team and CUAHSI today we discussed this. Rather than try to store a flag indicating that the services are there, or having some method to check them every time the landing page loads, we discussed taking this approach:

1) assume that the end points exist and are functioning in GeoServer. 
2) display all data services end points to user (WMS/WMTS/WFS)
3) in our instructions, tell the user that if the data doesn't load, then they should contact us. 
4) if they contact us then we can debug those edge cases that are breaking/not functioning so we can fix them (i.e. new projections strings etc.)

The concern is that we can't afford to try to figure out and account for every edge case in advance. So let's get it working and start getting users to use it and give us feedback and live testing. 

Question for @kjlippold, are there systematic old problems in the data? i.e. old data that we can go through and fix?

**Comment by kjlippold** [comment]
Alright, so I’ll do the following:
1. Finish setting up the endpoint generation and display feature on HydroShare.
2. Update the web services manager to keep a more detailed log of which resources have registered content, and which ones ran into issues.
3. Re sync all resources with the web services manager to make sure registered content is up to date.
4. Review the web services manager log to identify any major or common issues with data services that can be fixed.

**Comment by danames** [comment]
Yes that sounds great. Go for it...
**********************************************************************
Daniel P. Ames, Ph.D., P.E.
Professor, Civil & Environmental Engineering,Brigham Young University,
Provo, Utah, USA
Past-President, International Environmental Modelling & Software Society
Editor-in-Chief, Environmental Modelling & Software
http://ceen.et.byu.edu/faculty/person/Daniel-P.-Ames
<http://ceen.et.byu.edu/content/dan-ames>
http://www.researchgate.net/profile/Daniel_Ames
http://scholar.google.com/citations?user=S0GUCeUAAAAJ

**********************************************************************
