### ISSUE TITLE
README.md sometimes does not display

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3863]
The README.md file is supposed to display below the content area for a resource.  For this resource it does not https://www.hydroshare.org/resource/8161a96a08474d12bba219852409be61/.

I am able to download the README.md file and load into a new resource and have it display properly, so there does not appear to be a problem with the README.md file.  I have not been able to determine the conditions that cause this problem.

**Comment by horsburgh** [comment]
I wondered if this had something to do with the fact that there are two files in the resource with the word "README" in the file name. But, I tried several combinations of adding files with these names to different resource and I was also unable to reproduce the issue of the README.md file not being rendered. I used different files and just tried combinations of file names.

**Comment by sblack-usu** [comment]
After looking into this, I found that this filter looking at files in the root directory doesn't work with this resource because the file_folder on the README.md file is '' instead of None.  https://github.com/hydroshare/hydroshare/blob/develop/hs_core/models.py#L2333

@dtarb, I'm trying to understand how the file_folder is '' instead of None... did you do something like move the README.md file after uploading it?

**Comment by dtarb** [comment]
@sblack-usu this is not a resource I own, so I have no idea what David Arctur did with this.  Could this be because it is published, or a later version of an earlier published resource.

**Comment by sblack-usu** [comment]
When a new version of a resource is created, the root files in the resource are set to an empty string.  I'm considering just constraining non null values to handle this situation consistently across the codebase rather than accomodating both null and empty strings.
