### ISSUE TITLE
Map clusters not expanding - Discover feature parity

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#3996]
I've found several instances where map cluster icons will not expand when clicked to show a marker for each individual resource. 

To replicate:
1. Search for "streamflow"
2. Navigate to eastern Tennessee (Blackoak Gap)
3. Notice that there is a cluster of two resources
4. Click on them and notice that nothing happens

![image](https://user-images.githubusercontent.com/4822372/96141427-003dc780-0ecf-11eb-9c99-fa1c24552e57.png)

The expected behavior is for the cluster to expand into individual markers.

**Comment by cuahsimarko** [comment]
We are using the recommended / approved library as documented by the google maps team. I've opened a bug ticket on their code. If they do not respond in a timely manner, after the Discover Feature Parity+ release, a temporary workaround may be released https://github.com/googlemaps/js-markerclustererplus/issues/31

**Comment by devincowan** [comment]
On production, Firefox v99.0, the map clusters don't even render correctly in the first place, in addition to poor expansion
![image](https://user-images.githubusercontent.com/17934193/165152552-08c60740-126f-4a8d-95a3-4896eb13c7e9.png)

Also I don't see any "streamflow" hits in Tennessee (or anywhere East of Kansas for that matter) but perhaps that due to those resources not being shared with me on prod

**Comment by devincowan** [comment]
I opened a new issue for the Firefox bug #4646

**Comment by devincowan** [comment]
Moving some info over from #4979 
**Description of the bug**
A set of two points on the map interface on the discover page cannot be reached
![Screen Shot 2023-02-02 at 12 01 15 PM](https://user-images.githubusercontent.com/90924476/216657304-c429c6e9-7968-4175-8892-ad0c565bc486.png)
upon trying to drill down to the resource level, the map zooms users to another set of points elsewhere. Some clusters cannot be clicked down to the point level. This was noticed in the Northern Utah point cluster. 
Steps to reproduce the bug:
1. Go to (https://www.hydroshare.org/search/)
2. try to drill down into the point cluster listed, click around to see if any cannot be accessed at the point level. 

**Expected behavior**
should be able to get to the point level and then access the resource. This was noticed by users during a workshop yesterday.

**Additional information**
Add any other context about the problem here such as screenshots, software versions, and browser information.
