### ISSUE TITLE
User type for some users not shown

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#4054]
For some users user type information is not shown.

For User #8104 I see on www https://www.hydroshare.org/user/8104/.  Note user type is missing
![image](https://user-images.githubusercontent.com/3456833/100803936-3edd0200-33e9-11eb-9bc3-aa193d4d01d8.png)

If I look on beta.hydroshare.org, which has code that allows an admin to edit a users profile to address problems, I see
![image](https://user-images.githubusercontent.com/3456833/100804096-7e0b5300-33e9-11eb-8cd5-ae5d180aaad2.png)
Note user type is still missing.

However if I go to edit mode (which I can as an admin with new functionality on beta waiting for deploy) I see
![image](https://user-images.githubusercontent.com/3456833/100804195-b27f0f00-33e9-11eb-916d-87d142d9f001.png)
Note that in edit mode user type is there.

If I were to change the user type and save.  The problem is fixed.  (I tried this on beta for a different user).

**Comment by hyi** [comment]
@dtarb I know this is confusing, but in edit mode, the user type "University Faculty" showing for this user with missing user type does not mean this user has a user type of "University Faculty" but because "University Faculty" happens to be the first entry in the dropdown user type list and since this user does not have a user type, the default entry "University Faculty" shows up. We cannot add a empty or none entry in the dropdown list since user type is a required field and empty/none is not a valid option. Perhaps we should show a prompt message below the user type dropdown list to indicate this user has a none user type to reduce confusion.

**Comment by dtarb** [comment]
The explanation makes sense.  But then this still does not help us find how accounts are getting created without type.  We have to figure out how these accounts are being created.  Note that this was created 11/20/20, i.e. recently.

The issue of having users set their type if it is not set, is secondary.  Our messaging may be OK.  I would prefer to figure out what is going on and prevent this happening before adding new messaging.  If with this user (#8104) I go to 
https://beta.hydroshare.org/user/8104/, I already get this warning
![image](https://user-images.githubusercontent.com/3456833/100806971-b3ff0600-33ee-11eb-8d43-25ac9bb933e1.png)

This encourages entry of the information.  It is misleading, however, because for this user Country and State are filled out, so the warning should only complain about "User Type".

**Comment by hyi** [comment]
@dtarb Agreed we need to figure out first how accounts without user type got created in the first place, which is really a mystery to me. As for the warning, since you logged in as your admin user (not as the user whose profile you are checking), so the warning was against your admin user I believe. Could you check whether the admin user you logged in don't have State, Country, and User Type specified? The code should only show the missing fields in the prompt message as you mentioned. Let me know if you find this is not the case, though.

**Comment by hyi** [comment]
@dtarb a minor html frontend only fix was just applied on production that addresses this confusion as well. Now for users with empty user type, they will see "Select a user type" displayed rather than the first default "University Faculty" option. Feel free to take a look and if it looks good to you, this issue may be closed.

**Comment by dtarb** [comment]
Looks good
