### ISSUE TITLE
Clean up wiki

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#408]
Clean up the wiki addressing the following
1. [ ] Update roadmap
2. [ ] Update policies
3. [ ] Remove deprecated content (rather than label it deprecated)
4. [ ] Remove deprecated hydroshare2 repo and content therein

**Comment by hyi** [comment]
@rayi113 I intend to assign this to Michael, but cannot do so since his username does not appear any more after typing @ (it used to appear, but started to disappear sometime today for reasons I don't understand). I am assigning it to you for bookkeeping, so you can reassign to Michael once his account shows up on github (at least we can talk to Michael next week to see whether he has ideas to make his account reappear on github).
