### ISSUE TITLE
Landing page naming "placeholder-title-n"

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#41]
Testing on alpha.hydroshare.org version 1.2.1.  

The URL's for all resource landing pages seems to now be placeholder-title-n.  This seems odd and undesirable.

**Comment by hyi** [comment]
Moved "title" field from the second resource-description page to the first resource-selection page so that users get a chance to input a title at the beginning as part of the work for the new resource creation workflow as decided in the resource creation workflow working group at all-hands meeting. The default title is "Untitled resource" if users don't input a title for their resource. As a result, this issue is fixed. The updated code is in AGU branch, to be merged into develop branch, and to be rebuilt into alpha for testing.

**Comment by dtarb** [comment]
URLs that end up "Untitled Resource" are just as unclear as "Placeholder".  See issue #63.  Following is how landing page URL's should be done.
 
http://hydroshare.org/resource/{id} ---> Goes to a resource’s landing page
http://hydroshare.org/user/{id} ---> Goes to a user’s profile page
http://hydrohare.org/group/{id} ---> Goes to a group’s profile page

**Comment by rayi113** [comment]
HydroShare Resource Creation URL Issues in GitHub: #41, #63

**Comment by hyi** [comment]
It turns out all resource pages and urls are managed by Mezzanine. All resource pages are Mezzanine pages and Mezzanine's function get_absolute_url() returns url slug for a Mezzanine page object. Will investigate more trying to override Mezzanine's default behavior for our desired resource url mapping, but it may not be as easy to achieve what we want.

**Comment by dtarb** [comment]
Would it be possible to at creation pass the guid as the name of the 
resource.  Then it gets that URL right from the beginning.  The resource 
creation workflow can then change the title to untitled, and allow the 
user to change the title to whatever they want, but the GUID is locked in.

**Comment by hyi** [comment]
Looked into Mezzanine code and fixed this issue by adding one line to call set_slug() function on a resource page. Fix pushed to github and a pull request to merge the fix into develop branch is created. However, not sure whether we need to change user and group URLs to use the IDs rather than names. I guess for consistency, it makes sense to use IDs for user and group URLs as well, but for legibility, user and group names being used in the urls seem better to me. If the team decides to go with user and group ids for URLs, I will make corresponding changes as well. I want to get confirmation from the team before I make the change for user and group URLs since I think they deserve a bit of more consideration.

**Comment by horsburgh** [comment]
For users and groups it's really the same issue as with resources.  If we allow users to change user or group names, either the URLs for users or groups will change (breaking any links to them) or they will stay the same but no longer be consistent with name of the user or group.  

Our discussion at the Logan meeting settled on resources, users, and groups having persistent identifiers that are not tied to their name and that are used in the URL to their respective landing pages.

**Comment by hyi** [comment]
I am seeking input from the team on where user and group urls are displayed from Hydroshare web interface. The only place I can find user url currently is from the user link in Owner column from my-resources page, such as http://beta.hydroshare.org/user/dtarb/, which is managed automatically by a Mezzanine template tag called contact. I cannot find group url anywhere from hydroshare web interface. Any input on where these user and group urls are displayed from hydroshare web interface will be a great help for me to dig into the code, since at this point I cannot find any hydroshare code that deals with user and group urls.

**Comment by dtarb** [comment]
I do not think it has been possible to create groups yet.  Jefferson may 
have started on functionality but it was never finished/operational so I 
do not thing group urls are visible on any current hydroshare pages.

**Comment by hyi** [comment]
Finally found the right place I can make changes to make user url to use user id rather than user name. The template filter "contact" is not a mezzanine or django tag, but a hydroshare tag implemented in hydroshare_tags.py. After I figure this out, the fix is simple. Now both resource and user urls are displayed as decided. Group urls are not implemented in Hydroshare yet, but need to follow the url pattern as well to use group id when we get to implement groups functionality.

**Comment by dtarb** [comment]
Implemented and testec Alpha v 1.3
