### ISSUE TITLE
Errors using REST API with new iRODS BagIt workflow

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hydroshare#415]
In particular, there are at least two problems with the new iRODS BagIt workflow and the REST API.

1. When using the Python client library to download a resource that is not public, the creator/owner of the resource gets a "You do not have permission to download this resource!" error.  Example code is:

    from hs_restclient import HydroShare, HydroShareAuthBasic
    auth = HydroShareAuthBasic(username='myusername', password='mypassword')
    hs = HydroShare('myhostname', port=8000, auth=auth)
    resource = hs.getResource('e62a438bec384087b6c00ddcd1b6475a')
    with open('/tmp/myresource.zip', 'wb') as fd:
        for chunk in resource:
        fd.write(chunk)

The result will be a file containing "You do not have permission to download this resource!" instead of a BagIt zip file.  I'm not sure why this is happening, and it's too late and I'm too tired to debug it now.  Also, you are more expert in the auth and the django_irods code than I am.

2. Adding resource files to an existing resource using the REST API fails.  Example code would be:

    from hs_restclient import HydroShare, HydroShareAuthBasic
    auth = HydroShareAuthBasic(username='myusername', password='mypassword')
    hs = HydroShare('myhostname', port=8000, auth=auth)
    fpath = '/path/to/somefile.txt'
    resource_id = hs.addResourceFile('ID OF RESOURCE GOES HERE', fpath)

**Comment by hyi** [comment]
@selimnairb @pkdash This access control permission issue is not related to the new bagit workflow. The permission check is performed in the download view function, specifically, on line 18 in https://github.com/hydroshare/django_irods/blob/master/views.py, which calls authorize() function in hs_core.views.utils and only allow to download resource when it is authorized. This authorize() function is called multiple times in HydroShare web app as well and checks whether the user has at least view permission to the resource if the resource is not public. The fact that this permission check works for users who has logged in HydroShare web interface but not work for REST API makes me think the requesting user may not be passed in as part of the request correctly since authorize() function retrieve requesting user info from request parameter being passed in. I will have to debug to see what is happening here, but since @selimnairb and @pkdash knows REST API auth much better than me, if you two have some ideas on this issue, let me know. I may not be able to work on this issue until Michael, Ray, and I sort out large file uploading issue with the new bagit workflow.

**Comment by selimnairb** [comment]
@hyi I am confused then, because hs_core.views.resource_rest_api.ResourceReadUpdateDelete.get() calls the same authorize function (though with slightly different arguments, see [here](https://github.com/hydroshare/hydroshare/blob/413-update-rest-api-new-bagit-workflow/hs_core/views/resource_rest_api.py#L215)), which is granting permission.  Could you look at this and advise as to what I may be doing wrong.

**Comment by hyi** [comment]
@selimnairb @pkdash @ironfroggy It looks like it is an issue of get_user() function in hs_core/models.py, which is called by authorize() function. Look at https://github.com/hydroshare/hydroshare/blob/develop/hs_core/models.py line 35 NOTE: The API key portion has been removed with TastyPie and will be restored when the new API is built, and I don't see it restored, and suspect get_user() does not return a valid user, hence authorize() function fails to authorize a user when being called from REST API. Could you three take a look and see whether this get_user() could be the culprit for this permission issue?

**Comment by pkdash** [comment]
I assume the REST API is not using API KEY for authentication at this time. Then I am not sure why the get_user() would fail?

**Comment by pkdash** [comment]
I did some debugging with REST API for downloading a resource file. It seems the authentication passes when the authorize() function is called with the REST API view class. But then with HttpResponseRedirect(file_url) it fails authorization() within the django_irods/views.download() function since the same request object it not passed to the download function.

**Comment by hyi** [comment]
That confirmed my suspicion. request has to be passed to the download function in django_irods for user-resource authentication. @selimnairb, could HttpResponseRedirect() be replaced with something like Render or RenderToReponse so that request can be passed in for authentication purposes?

**Comment by pkdash** [comment]
For the mapping the URLs from the resource map I am currently implementing a new view function that also uses the HttpResponseRedirect(file_url) and I do not see any authorization problem. The authorization passes both in this new hs_core/views/file_download_mapper() function as well as with the django_irods download() view function.

**Comment by selimnairb** [comment]
@pkdash Thanks for debugging this.  I'm looking for a solution.

**Comment by hyi** [comment]
OK. Now that I think of this further, If I remember correctly, I think even with HttpResponseRedirect, the calling request is somehow implicitly passed in to a view function that maps to the redirected URL, which may explain why use of HttpResponseRedirect() also works for @pkdash. @selimnairb, another possibility for authentication failure could be the calling request has a wrong user or does not have user defined somehow, so might be worth checking.

**Comment by selimnairb** [comment]
@pkdash Can you refer me to the code you are talking about.

**Comment by selimnairb** [comment]
@hyi HttpResponseRedirect responds with an HTTP redirect (HTTP 301 or 302).  It is up to the client to follow the redirect.  My guess right now is that the REST client, which uses the Python requests library, is failing to pass the authentication information in on the redirect.  I might not have a solution until tomorrow.

**Comment by pkdash** [comment]
@selimnairb is probably right in saying the request library fails to pass the authentication information on the redirect. When I did the test for my new code that has the redirect I was not using the request module. I did that test using the browser.That's why redirect worked in my case.

**Comment by pkdash** [comment]
@selimnairb and @hyi  it seems using the rest framework decorator ```@api_view(['GET'])``` on the django_irods download() view function resolves the issue. However, I am not sure if it is the right solution.

**Comment by hyi** [comment]
@selimnairb @pkdash I am not familiar with the rest framework, but I think the issue that causes download view function failure is the requesting user not being passed in. Perhaps this @api_view() decorator gets requesting user straightened out, so it works?

**Comment by selimnairb** [comment]
@pkdash Thanks for debugging this.  I will incorporate this for now as it allows the Python client library to work as it did before, and does not seem to have a negative effect for non-API access.

**Comment by hyi** [comment]
@selimnairb I think this issue is fixed on dev, right? If yes, could you close this issue?

**Comment by selimnairb** [comment]
This issues is fixed on dev.  Closing.
