### ISSUE TITLE
Button clickable when should be grayed out

### ISSUE THREAD

**Issue by cuahsimarko** [hydroshare/hydroshare#4170]
In a new resource with no files, bagit should be disabled:

![image](https://user-images.githubusercontent.com/45397838/110019407-6bf5c500-7cf6-11eb-9ea9-0bac04bafec2.png)

**Comment by hyi** [comment]
@cuahsimarko I believe this works by design - the resource bag not only includes content files, but also include metadata files along with other bagit specification files. So even if a resource does not contain any file, download bag button should still be enabled to allow users to download the resource bag. Looping in @horsburgh to confirm about it.

**Comment by horsburgh** [comment]
@hyi is correct. There is no need to disable this. It's working as designed.
