### ISSUE TITLE
Aggregation correctly detects extents but fails to correctly display map

### ISSUE THREAD

**Issue by cbcunc** [hydroshare/hydroshare#4220]
https://www.hydroshare.org/resource/f203458dcdde4cc8982a4a02aec9de8f/

**Comment by martinseul** [comment]
@devincowan would you please take a look.

**Comment by devincowan** [comment]
yes will look into it!

![image](https://user-images.githubusercontent.com/17934193/184223495-6fdae4d0-2db0-40d0-b690-245c9f2f32f6.png)
![image](https://user-images.githubusercontent.com/17934193/184223635-8c7688f2-75c5-4463-927b-5642fc32b578.png)
![image](https://user-images.githubusercontent.com/17934193/184223681-1a56535b-99e1-4d56-8ef5-86e203019078.png)

**Comment by devincowan** [comment]
Seems to me that the spatial coverage box is actually displayed correctly on the map, but it gets confusing because this resource has **North Lat = 90** which extends beyond the Google maps background (google maps tiles are only displayed between 85 and -85 degrees latitude).

My proposed solution to make this less confusing is to add a [restriction](https://developers.google.com/maps/documentation/javascript/interaction#restricting_map_bounds_and_zoom) to the google maps config for Spatial Coverage, that limits the viewable area to +-85 degree latitude.

I added that in https://github.com/hydroshare/hydroshare/commit/9e91284881db929c99fcfd6a29751e284df4ebb0 and deployed an example so others can take a look:
https://new-riverdev.hydroshare.org/resource/98546626a55740c28418ddd0848c4489/

@cbcunc how does that look to you?
