### ISSUE TITLE
Update production Geoserver to latest version

### ISSUE THREAD

**Issue by martinseul** [hydroshare/hydroshare#4399]
The current deployment for Geoserver on production is using an outdated codebase https://github.com/CUAHSI-APPS/his_geoserver. It needs to be updated to use then latest codebase https://github.com/hydroshare/hs_data_services.

This requires an update to the code and a re-ingestion of the current registered public spatial resources.

**Comment by cbcunc** [comment]
Adding myself as an assignee to keep my eyes on it.

**Comment by martinseul** [comment]
adding and update here from the email conversation:
Chris requested a new server from ACIS and worked with Ken to set up a new geoserver instance and configured it to be tied to beta. I went through testing and it behaves correctly (https://geoserver-beta-test.hydroshare.org/geoserver/web/) . Now we need to plan role out, which requires a registration of all spatial resources with the new server, Ken needs to provide input here. as well as configuration changes that Chris can do.

**Comment by cbcunc** [comment]
Migration plan: https://docs.google.com/document/d/1Qn75mYarTEnS_mQolJZci-WRPaQnF9kiqi-AaRhWD0k/edit?usp=sharing

**Comment by devincowan** [comment]
Plan is Aug 2nd at 2pm

**Comment by cbcunc** [comment]
Aug 17 at 3:30 pm EDT

Revised migration plan with the addition of ACIS steps: https://docs.google.com/document/d/1Qn75mYarTEnS_mQolJZci-WRPaQnF9kiqi-AaRhWD0k/edit?usp=sharing

**Comment by cbcunc** [comment]
- [ ] Test bulk registration on beta with new geoserver
- [ ] Bulk register on "old" beta geoserver
- [ ] Restore "old" beta geoserver (which is the same install as the new geoserver) to service
- [ ] Prepare new geoserver to use production iRODS etc.
- [ ] Run bulk registration on new geoserver pointed at production iRODS but with the beta test name (https://geoserver-beta-test.hydroshare.org/geoserver/web/)
- [ ] Revisit changing hostname of the old VM with ACIS because we don't have access to the puppet configuration for geoserver.hydroshare.org

ACIS plan
CR = Chris Rutledge; CC = Chris Calloway
- [ ] CR - Take VM snapshots of both [geosrv-01-hs.renci.org](http://geosrv-01-hs.renci.org/) and [geoserver.hydroshare.org](http://geoserver.hydroshare.org/)
- [ ] CC - Confirm [geosrv-01-hs.renci.org](http://geosrv-01-hs.renci.org/) is ready to assume the role of [geoserver.hydroshare.org](http://geoserver.hydroshare.org/)
- [ ] CC - Delete A record for [geoserver.hydroshare.org](http://geoserver.hydroshare.org/)
- [ ] CC - Create CNAME record pointing [geoserver.hydroshare.org](http://geoserver.hydroshare.org/) to [geosrv-01-hs.renci.org](http://geosrv-01-hs.renci.org/)
- [ ] CC - Confirm functionality
- [ ] CC - Create A record for new [geoserver.hydroshare.org](http://geoserver.hydroshare.org/) hostname
- [ ] CR - Update PTR record for new [geoserver.hydroshare.org](http://geoserver.hydroshare.org/) hostname
- [ ] CR - Update puppet configuration to change hostname of [geoserver.hydroshare.org](http://geoserver.hydroshare.org/)
- [ ] CR - Delete /etc/krb5.keytab and /var/lib/sss/db cache
- [ ] CR - Reboot [geoserver.hydroshare.org](http://geoserver.hydroshare.org/)
- [ ] CR - Confirm hostname change
- [ ] CR - Rejoin domain using puppet
- [ ] CC - Confirm all is well with new [geoserver.hydroshare.org](http://geoserver.hydroshare.org/) name change.
- [ ] CR - Rename host in vSphere and do a storage vmotion

- [ ] Update local_settings.py on prod and in ZDT for the new token
- [ ] Rerun the bulk registration again

**Comment by danames** [comment]
@martinseul does this affect what you want to do with a development
environment at all?
**********************************************************************
Daniel P. Ames, Ph.D., P.E.
Professor, Civil & Environmental Engineering,Brigham Young University,
Provo, Utah, USA
Past-President, International Environmental Modelling & Software Society
Editor-in-Chief, Environmental Modelling & Software
<http://ceen.et.byu.edu/content/dan-ames>
https://ceen.byu.edu/directory/dan-p-ames
http://www.researchgate.net/profile/Daniel_Ames
http://scholar.google.com/citations?user=S0GUCeUAAAAJ

**********************************************************************
