### ISSUE TITLE
Version fixes through management command have changed last updated date.  These need fixing.

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#4473]
**Description of the bug**
The management command developed in #4397 fixed broken versioning chains.  However the last updated date for resources fixed was changed.  This should not have been done, as it changes the how to cite information.

A specific example 
A https://www.hydroshare.org/resource/02cb57b77819407a9ac29c6cc1dd7995/ which has new version
B https://www.hydroshare.org/resource/c29c9afd6d234cb8b5bc468a8f23975a/ which has new version
C https://www.hydroshare.org/resource/13c5d3491e8144bdbf0c16d39f60d597/ which has new version 
D https://www.hydroshare.org/resource/0d212b8577d74bcca018f421fbd765d9/

The fixes did not touch D so its last updated date is 3/5/2019.  However for A, B and C the last updated date is 2/1/22, the date the management command was run.

If possible we need to, from a backup, determine the last updated dates for all resources that had versioning problems fixed by this management command.  Then we need a new management command to set the last updated date back to what it was prior to the versioning management command being run.

In general management commands should not change the last updated date.  Last updated should only be changed when a user takes an action on a resource.

**Comment by hyi** [comment]
@dtarb The database backup snapshot file I initially copied over just before the last release deployment somehow has the same updated time as the current production, so I had to try a one-day-earlier database backup snapshot to get the old updated date for those resources affected by running this management command. I extracted updated date for these resources affected and created a csv file with two columns, resource id and updated timestamp, and wrote a management command to update resource updated time based on this csv file and ran it locally. I spot checked several resources and compared them with beta (which happen to have the old timestamp before running my version fix management command) and they all look correct. So I am uploading the csv file so you can do a spot check also.
[version_res_date.csv](https://github.com/hydroshare/hydroshare/files/8051084/version_res_date.csv)
You can compare the time stamp with beta to make sure the correct time stamp was extracted. I'll create a PR shortly so that we can run the management command on prod next week.

**Comment by hyi** [comment]
@dtarb I used an earlier database dated Jan. 16, 22 and tried to retrieve updated dates for those resources. Although dates looked better, I still see some similar issues for some resources. After looking into the database, I realized I was using ```updated``` field on resource object to retrieve updated date which appears to change more often than the real resource last updated date. So I updated the management command (which was not checked into github repo since I thought I just need to run it once to create the updated date for these resources) to use resource metadata date modified field, i.e., using ```resource.metadata.dates.all().filter(type='modified')[0].start_date``` to get last updated date for the resource, which appears to create correct last updated date for resources. The updated csv file is attached here:
[version_res_date.csv](https://github.com/hydroshare/hydroshare/files/8235773/version_res_date.csv)
I spot checked some resource version chains including those resources you indicated above and all looks correct. I ran the management command on production using the updated resource date file, and those resource last updated dates look correct now. Please take another look when you have a chance to verify and close the issue if everything looks correct and let me know any further issues you find if any. Thanks for the thorough testing!

**Comment by dtarb** [comment]
@hyi I spot checked and the problem resources I was aware of appear to be fixed.  I am closing.  I do find myself wondering why there appear to be separate fields "Updated" and "date modified" with the date modified one evidently being what is displayed on the resource landing page.  I would encourage documenting this and the different purposes for these different fields in the code to avoid this sort of problem in the future, or as a more complete fix, that may be a separate issue, consolidating down on to only one updated date, unless there is a good reason for two.

**Comment by hyi** [comment]
@dtarb I spent some time looking into this "updated" field on HydroShare resource model and found it is defined in a TimeStamped model which was inherited by Displayable model which was linked to Mezzanine pages. Since HydroShare resources are Mezzanine pages, all HydroShare resources have this updated field. For some reason, this updated field is updated more often that when HydroShare was really modified, which could come from Mezzanine.

**Comment by hyi** [comment]
@dtarb OK. I decided to check in the management command for future reference and added detailed comment about the difference between updated field and resource metadata dates to indicate updated field cannot be used to retrieve resource last updated date, and resource metadata dates should be used to retrieve that info instead. Have created a PR #4547 and asked @sblack-usu to code review to get it into the code base.
