### ISSUE TITLE
Unable to access Data Rods Explorer (DRE) web portal 

### ISSUE THREAD

**Issue by shantanubhide** [hydroshare/hydroshare#4533]
https://apps.hydroshare.org/apps/data-rods-explorer/

**Comment by henrichsen** [comment]
DRE is now up and running again. 

The file (enddate_bounds.py) that updates the temporal and spatial bounds of the datasets failed for Grace for a few days. This means that that no values were inputted for Grace. I manually put in the bounds for Grace and the app started working again. There has been no issues with updating the bounds the last few days. I couldn't figure out why the file now runs properly after manually adding the values in once. 

@gespinoza The reason why the app failed to open was reading in the bounds into the app. This occurs in model_objects.py in parse_fences_from_file. Because there was no values, the function errored out because it assumes the data exists and does not verify if the data actually does. This function should be updated to prevent this in the future.
