### ISSUE TITLE
Authenticated user should see content files for private resource that has private link sharing enabled

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#4541]
**Description of the bug**
**TODO**: Update the nature of the bug.

An authenticated user doesn't see resource content files of a private resource if the resource has private link sharing enable and the users don't have access permission for the resource. 

Steps to reproduce the bug:
1. Use the following steps to reproduce this bug.
2. Create a resource. Upload a file to the resource. Enable private link sharing using the Manage Access panel. Make sure the resource status is private. Copy the url of the resource.
3. Create a new user account
4. Use another browser 
    4.1 Login to hydroshare as the user account you created in step 3.
    4.2 Paste the url of the resource in the browser for the hydroshare site.   
    4.3 The landing page of the resource will be displayed without the resource files.

**Expected behavior**
In step 4.3 above the authenticated user should content files.

**Additional information**
Add any other context about the problem here such as screenshots, software versions, and browser information.

**Comment by devincowan** [comment]
related to #3077

**Comment by dtarb** [comment]
@pkdash @devincowan either I misunderstand what you are suggesting or I disagree.  If a resource has private link sharing enabled then anyone with the link, be they anonymous (the browser does not have an authenticated user logged in) or a logged in user, should be able to see the full contents of the resource.  Them having been given the link provides them access.  If we do not do this, it would not be logical, as someone could see a resource if they are not logged in, but if they log in, then the resource contents are hidden from them.

I think expected behavior should be (for a resource that has private link sharing enabled)
The full resource landing page including content files is shown for any user and for anonymous (not authenticated) users.

**Comment by devincowan** [comment]
@dtarb right that is what I was pointing out when I noticed the discrepancy (seeing LESS info when logged in vs not) here:
https://github.com/hydroshare/hydroshare/pull/4491#issuecomment-1062271972
I agree that logged-in users should be able to see _at least as much info_ as anonymous users

**Comment by pkdash** [comment]
@dtarb and @devincowan I have made the changes based on today's comments. Both authenticated user and anonymous user will see the same information for a resource which has private link sharing enabled. This is deployed at new-testservices.hydroshare.org if you would like to test.

**Comment by devincowan** [comment]
@pkdash I just tested and it worked great! No longer a discrepancy between what an anonymous vs logged in user can see on a resource that has link-sharing enabled

**Comment by pkdash** [comment]
This has been fixed in release 1.54 - so closing.
