### ISSUE TITLE
Resource Landing page reports that a DOI is pending for 2 weeks, but the DOI is active.

### ISSUE THREAD

**Issue by ClaraCogswell** [hydroshare/hydroshare#4605]
**Description of the bug**
A user published a resource 2.5 weeks ago, and since then the "Note that the DOI will not be available until it has been registered and activated" message has remained. I have checked the DOI, it is registered and active. The pending publication message also still appears at the end of the generated citation/ 

Steps to reproduce the bug:
1. Go to https://www.hydroshare.org/resource/18db8e1da5354e318b57e9d873fd5e35/

**Expected behavior**
The pending publication notices should disappear when the DOI is minted, this typically does not take more than a few hours if that.  

**Additional information**

<img width="1135" alt="Screen Shot 2022-05-03 at 4 22 11 PM" src="https://user-images.githubusercontent.com/90924476/166559593-a8bb45b0-5e05-4e36-be03-c399b99495f1.png">

**Comment by martinseul** [comment]
@devincowan could you please take a look at it. Please reach out to Hong if you have questions as she did the initial implementation I believe.

**Comment by ClaraCogswell** [comment]
Thank you Hong!

**Comment by devincowan** [comment]
From what I can see, the[ celery task ](https://github.com/hydroshare/hydroshare/blob/develop/hs_core/tasks.py#L97) seems to be functioning. Martin and I were thinking that maybe this particular resource got skipped due to the power outage. But the celery task runs nightly at midnight so I don't see why it wouldnt have resolved the next night...

I thought just to be sure, we could find a pending resource and check back to make sure that it resolves in a couple weeks. I queried our [api endpoint](https://www.hydroshare.org/hsapi/resource/?published=true) for doi containing "pending" and don't find any right now.

I'm okay with closing this if @ClaraCogswell is

**Comment by ClaraCogswell** [comment]
I'm fine with closing!

**Comment by martinseul** [comment]
This issue has reappeared and is now affecting additional resources going back to early May this is critical, @hyi, @devincowan could you please coordinate and look into a solution asap.

**Comment by sblack-usu** [comment]
https://github.com/hydroshare/hydroshare/pull/4628 - addresses the issue and should be deployed as a hotfix today.  There is a nightly job that looks at all pending resources and sets them as published after querying crossref.  The query to crossref fails.  This is NOT a call to publish the resource, it runs a GET to crossref to ensure the resource is published before setting the resource status from pending to published.
