### ISSUE TITLE
(time sensitive) User not able to make resource public despite fulfilling all requirements

### ISSUE THREAD

**Issue by ClaraCogswell** [hydroshare/hydroshare#4611]
**Description of the bug**
This resource https://www.hydroshare.org/resource/6f3386bb4bc945028391cfabf1ea252e/ has all of the needed metadata and files be be made public but the public option is greyed out in the sharing status panel. 

Steps to reproduce the bug:
1. Go to https://www.hydroshare.org/resource/6f3386bb4bc945028391cfabf1ea252e/
2. use the admin account to try to change the sharing status

**Expected behavior**
The public button should be selectable 

**Additional information**
This user needs to make the resource public fairly soon. She mentioned it was semi-urgent.

**Comment by ClaraCogswell** [comment]
I tried disabling private link sharing before submitting the ticket, sorry for not clarifying, and it dod not change the ability to make it public

**Comment by martinseul** [comment]
Thanks @pkdash , what would be an appropriate statement for this license type (@ClaraCogswell please chime in here) and what is the purpose of the "statement" and does it need to be mandatory?

**Comment by pkdash** [comment]
@martinseul Some text from this link may work for the statement.
https://mit-license.org/?msclkid=b18d9718d06e11ecb5c2b5003264ae46

**Comment by horsburgh** [comment]
The purpose of the rights statement is so that people can specify their own license under which the content is released. This is the case when they select "Other" under "Select a license". If they select "Other", it means they don't want to use one of the Creative Commons licenses. When they select "Other", the statement should be mandatory because it is the license statement under which the resource is shared.

**Comment by hyi** [comment]
This all makes sense to me and agreed the statement should be mandatory when "Other" is selected for license. I now remember when I implemented schema.org to expose HydroShare for structured data search, I used statement or url to expose the license since statement could be empty. I remember at the time I looked at the code and found either statement or url is required, but not both. So code change will be needed if statement needs to be required for "Other" license.

**Comment by ClaraCogswell** [comment]
What is the timeline on being able to let the user know what has occured?

**Comment by martinseul** [comment]
As far as I understand the issue: if the user adds a statement e.g. https://mit-license.org/?msclkid=b18d9718d06e11ecb5c2b5003264ae46 it can be made public, this would get the user unstuck, we'll need to add a notification to inform the user that a statement is mandatory if you select "other" as a license to close the ticket

**Comment by dtarb** [comment]
I see that this resource is now public.  For future reference a more direct answer would have been to have the user select one of the creative commons licenses.  The cc-by license is default, so the user likely created the issue by incompletely changing the license.  However how the user did this is still an issue as just trying a bit now I am unable to reproduce.  If I change the license to "other" it will not let me save without text in the statement or URL.  Was this resource perhaps written programmatically via the API.

![image](https://user-images.githubusercontent.com/3456833/168493731-50e983ce-bdab-42a3-b7c6-adcf3d47e699.png)

**Comment by ClaraCogswell** [comment]
Dave, I will ask the user if they created it using the API

**Comment by ClaraCogswell** [comment]
@dtarb the resource was created directly, not through the API

**Comment by pkdash** [comment]
@dtarb 

>  If I change the license to "other" it will not let me save without text in the statement or URL.

You can save the license providing only the url. Once the license is created this way, it won't be possible to make the resource public. This is a bug.  In metadata update logic we check the user has provided a value for either the url or the statement. However, when checking for metadata requirements for making the resource public, it checks that the license has a value for the statement.

**Comment by dtarb** [comment]
@pkdash Thanks for working out.  Can you please work with @ClaraCogswell to fix and settle on clear wording, error messaging and policy.  I suggest that when the license "other" is selected, that the Statement should be required, but URL optional.  The rationale for this is that a user may just want to add a statement giving the license that may not be associated with a URL somewhere, but if it is associated with a URL somewhere, they should be able to give the URL.  The statement is required, because even if a URL is given some text to indicate the name of the license should be given.  The saving of a license (one of those offered in the drop down or "other") should be configured to never result in an incomplete license.  Thus the license should not be a consideration in whether something is made public, because every resource should always have a complete license.  I suggest removing the checking of license from the making public process.  If there are resources with improperly configured other licenses e.g. URL and no statement, I suggest putting the URL link as text in the statement as a stop gap for these that retains whatever intent the user had.
