### ISSUE TITLE
Version messages are incorrect for some published resources

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#4633]
**Description of the bug**
The following resources have incorrect version messages.  I suspect this may relate to the changes/hotfix done to address #4605 

Go to 
https://www.hydroshare.org/resource/24f8275d882e4d40809ba901258c17ad/
At the top it says "An older version of this resource **DOI for this published resource is pending activation. is available**."  This makes no sense.  How can a resource be published, but the older version still have DOI pending.

In related resources it says
This resource updates and replaces a previous version. Rosenberg, D. E. (2022). Colorado River Basin Accounts: Provoke discussion about more flexible and sustainable operations, HydroShare, https://doi.org/10.4211/hs.f085afcf710744898f38b64c00e22a5b, **DOI for this published resource is pending activation.**

On the older resource it is indicated as being published, but at the top 
A newer version of this resource DOI for this published resource **is pending activation. is available that replaces this version.**
An older version of this resource https://doi.org/10.4211/hs.57ad7df425b84da2874e9c19e7b34aad is available.

**Comment by devincowan** [comment]
@dtarb thanks for this. Seems our problem is that the citation for a Related resource (including in this case, copies of a given resource) is set at the time that the resource is copied. So if that resource was pending publication at the time that it was copied/re-versioned, the "DOI pending publication..." string is permanently written into the relation. This isn't ever updated once the DOI is no longer pending. 

So I think this wasn't caused by the hotfix https://github.com/hydroshare/hydroshare/issues/4605 but probably that problem resulted in resources spending longer in "pending" state. And thus there was a higher likelihood that a resource would be pending at the time that it was re-versioned.

**Comment by devincowan** [comment]
@dtarb thanks for checking, yes the [migration](https://github.com/hydroshare/hydroshare/blob/develop/hs_core/migrations/0063_auto_20220601_2014.py) will handle the old resources in the db
