### ISSUE TITLE
Whitespace reduction suggested on Home screen "Featured Apps" and "Additional CUAHSI Water Data Services"

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#4659]
Given the newer wider hydroshare container, the home page is exceptionally sparse around the "Featured Apps" and "Additional CUAHSI Water Data Services".  These could now seemingly be combined into a single row, or otherwise revised to reduce whitespace.  

<img width="1440" alt="Bildschirmfoto 2022-06-12 um 11 37 20 PM" src="https://user-images.githubusercontent.com/43424907/173275072-e6a3c437-1ec4-47cc-ad84-2d45101b454f.png">

**Comment by devincowan** [comment]
Keeping the text and icons the same size:
![image](https://user-images.githubusercontent.com/17934193/173373973-1aabf6a3-f816-41c0-b79c-7b7ed65a9cd6.png)

Shrinking icons so that that everything can populate a single row:
![image](https://user-images.githubusercontent.com/17934193/173374327-c479cd81-526c-4bdc-85cd-e30085e0f233.png)
