### ISSUE TITLE
Add full address as a profile fieldset

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#47]

**Comment by rayi113** [comment]
HydroShare Profile Issues in GitHub: #44, #46, #47, #48, #49, #68

**Comment by dtarb** [comment]
See #180

**Comment by mauriel133** [comment]
I'm assuming we are not going to use a Full Address field anymore. If that's the case this issue can be closed.

**Comment by horsburgh** [comment]
@mauriel133 - I can't remember what you've got in your latest version of the profile.  Where you you have it deployed.  I was going to have a quick look.

**Comment by mauriel133** [comment]
We went with the fields specified in the user tracking document (Country and State). Can be tested at https://park.hydroshare.org

**Comment by dtarb** [comment]
I just tested this.  

1.  I tested changing my email and got an email "you have changed your HydroShare account email" but there was no link to click to confirm and the email did not change.

Here are a few suggestions, to take or leave, not critical.

2.  When edit is clicked and contributions tab is at the front switch to Overview tab otherwise user does not see things on overview tab that are editable and none of the contributions part is editible.

3.  Set the State/Province field so that the Unspecified goes away as soon as a user clicks.  I ended up with state UnspecifiedUtah until I explicitly deleted the unspecified letters.

**Comment by pkdash** [comment]
@dtarb I am aware of this issue with email update. The email update is not ready for testing. For some reason sending confirmation email to the new email address doesn't work. I am working to resolve that. However, I was able to send the confirmation email to the old email address.

**Comment by mauriel133** [comment]
@pkdash, what's the status on the email update?

**Comment by pkdash** [comment]
@mauriel133 Has been implemented and should be part of the master branch by now.

**Comment by mauriel133** [comment]
@ironfroggy or @dtarb please confirm and close.

**Comment by dtarb** [comment]
OK with what we have now.  Closing.
