### ISSUE TITLE
Add help documentation for field-based search

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#4748]
In release 1.58, we enabled field-based search. In order for users to be able to use this search feature effectively, help documentation needs to be developed for field-based search. @alvacouch has written about field-based in the following google doc (see the section '**A proposed documentation page for the query language**'):

https://docs.google.com/document/d/1GXld28UUwFMd6Beq7fMVb4TRdaDImZKb3XWlSQuNai0/edit#heading=h.1tul4sv9bkj5

 Once the help documentation page is developed, we can provide a link to that page from the search page.

**Comment by ClaraCogswell** [comment]
I will begin working on this today

**Comment by ClaraCogswell** [comment]
Can a subject matter expert tell me a name for the title of this help page that is more accessible/less jargon-y or shall I go with "Field based search in Discover"

**Comment by ClaraCogswell** [comment]
I have added the suggested language, it can be reviewed here: https://help.hydroshare.org/discovering-resources/discovering-data-and-models-from-hydroshare-users/field-based-search-in-discover/

**Comment by dtarb** [comment]
@ClaraCogswell in terms of title I would suggest "Advanced search functionality" because it does not appear to be only "field based".  I also think there needs to be some checking that what was in this old 2018 document is correct with what has actually been deployed.  If I enter _tarboton_ in the search bar I find 328 resources.  If I enter _tarboton -couch_ I find only 22 resources so something is happening in terms of the resources being found, but the very first resource on the list found is https://www.hydroshare.org/resource/b6ec3e4d2dc645ba8fcb6af4d2f2f1db/ which has Alva Couch as an author, so this does not appear to be working as described.  We need to describe what the various options do.  Hopefully @pkdash and @alvacouch can help.  To the degree that this is standard SOLR functionality if we could point to SOLR documentation rather than have to maintain our own, it would be better.

**Comment by ClaraCogswell** [comment]
Do you have/are you author on 328 resources? @alvacouch and @pkdash I will ask you to review the document then and let me know which parts are out of date from the implemented version. Please take a look when you have time, I will check back in with you at the end of next week to see if you have any comments or changes.

**Comment by ClaraCogswell** [comment]
@pkdash and @alvacouch How is the review of the documentation going

**Comment by pkdash** [comment]
@ClaraCogswell  I was waiting for @alvacouch to review and update the document.  He may not have time to do this. This afternoon I plan to start manual testing of search based on the documentation and update the documentation as needed. Will let you when I am done.

**Comment by pkdash** [comment]
@ClaraCogswell I have now commented in the google doc what is not working. Alva also have updated the document. I suggest features that are not working we should remove from the help page.

**Comment by pkdash** [comment]
@ClaraCogswell Let me know when you are done with updating the help page.

**Comment by ClaraCogswell** [comment]
I've updated it after removing everything that you indicated was not working, regardless of whether there are plans to fix it. Review here: https://help.hydroshare.org/discovering-resources/discovering-data-and-models-from-hydroshare-users/field-based-search-in-discover/

**Comment by pkdash** [comment]
@ClaraCogswell We need to remove these two search features (crossed in red) as shown in this screenshot. 

![search_help_doc_correction-1](https://user-images.githubusercontent.com/2523434/191965115-dfddde18-9e28-4e62-8609-6c950cb4be38.JPG)

**Comment by ClaraCogswell** [comment]
done
