### ISSUE TITLE
Revamp the user profile page and user model

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#475]

**Comment by ironfroggy** [comment]
How long do we wait for them to verify the e-mail address? We need to expire this, because we have to treat that e-mail as unavailable for use until we validate.

I am a little concerned about the cost versus reward on this one. We will have to return to our own homegrown e-mail validation implementation, because the validation built into Mezzanine only understandands validating an existing pending account's single e-mail address, and now we need to validate both pending accounts and pending changes to active accounts.

What if a user changes their e-mail address to a known alternate for another user's existing account? The other user will receive the validation e-mail, and will likely click the link (people do not always read all the fine print). Do we want to require some additional validation on following the link, like entering the password?

Should we notify the original email address about the change, in case it was fraudulent? Should we allow them to cancel the change? For how long? Can they enter a new address while there is already a change pending?

What does the profile edit form look like, the e-mail field in particular, when they have a currently valid e-mail but another they have already entered and not validated yet?

**Comment by dtarb** [comment]
30 min is OK.

I am happy to relax some of the requirements in the interest of avoiding homegrown email implementation and welcome suggestions in this regard.

In the present implementation it is possible to have multiple accounts with the same email address (I just did it).  We want to enforce only one account per email address.

I would prefer to resolve the issues of email clashes by checking existing emails so that if a user tries to use an email already associated with another account that an error is given.  This should avoid sending email to another user with an account already.

When an email address is changed I would prefer an email to go to the original email address to protect against fraud.  This is addressed in https://github.com/hydroshare/hydroshare/blob/master/docs/DesignDocs/UserNameEmailRules.md.

Cancelling from the original email should be possible for a long time (e.g. a month) 

If a change is pending a new change request should not be allowed.  (30 min wait should not be too onerous - but again I am open to suggestions that may be more practical or easier to implement)

@horsburgh please point to the mockup for what you would like the profile edit form to look like (or develop one if there is not an existing one)

**Comment by dtarb** [comment]
Concern and recommendations from @ironfroggy report that should be addressed with this issue.

There is no way to see your own profile, only to update it. 

Recommendations:

* Show your own profile when you click the “Profile” link on the top right menu
* Show a link to edit your profile from viewing your own profile

**Comment by mauriel133** [comment]
Revamp can be tested at https://park.hydroshare.org

**Comment by mauriel133** [comment]
Revamp has been implemented. Please confirm and close.

**Comment by horsburgh** [comment]
@mauriel133 - the only potential issue is the changing of email address.  Did that whole process get implemented?

**Comment by mauriel133** [comment]
@pkdash was working on that one, I don't know if it has been merged.

**Comment by pkdash** [comment]
@horsburgh Email change has been implemented as part of this issue.

**Comment by horsburgh** [comment]
OK. Closing.
