### ISSUE TITLE
Upgrade to PostgreSQL 14

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#4781]
Currently hydroshare uses a very old version of PostgreSQL (9.4) as well an outdated version of django (1.11). We need to upgrade both Django as well as PostgreSQL. In order to make this upgrade less painful, we will upgrade PostgreSQL to version 14 and make that a release. Then will do the django upgrade as part of another release.

**Comment by cbcunc** [comment]
@pkdash I approved these changes. But it's not enough to merge. Please don't merge yet. We will need more commits. At a minimum, hsctl will need to export PGPASSWORD due to change in Postgres authentication. We can talk about this when you get back. hsctl has  LOADDB section which governs data update in the Jenkins deployment job. It will need testing and the testing is time consuming due to how long it takes to do a full data update on beta.

**Comment by pkdash** [comment]
@cbcunc Glad I waited to merge. I can make the needed changes once I am back. Also, if you let me know what changes are needed I can try to make those changes sometime this week.
