### ISSUE TITLE
Rename resource types for the UI

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#4853]
Creating this issue as suggested by @dtarb.

On Apps page change the “View Resource Page” link to “View Web App Connector Page”
![image](https://user-images.githubusercontent.com/2523434/202730565-004d78f0-4c3c-46f9-8e68-8048c5f91dd8.png)

On Resource landing pages change where it says resource type, to just Type: and change the words that can follow to be one of “Resource”, “Collection”, “Web App Connector” resource type as it is now a deprecated concept.
![image](https://user-images.githubusercontent.com/2523434/202730746-80e48378-e3e9-4e53-8d4d-343074b2434a.png)

**NOTE**: The above does have ramifications throughout the system, for Discovery, My Resources, User Profiles, essentially all places where “objects” are listed.

**Comment by pkdash** [comment]
@horsburgh I am working on this issue to make the UI consistent in the naming of resource types: The proposed renaming are as follows:

**Composite Resource** becomes **Resource**
**Collection Resource** becomes **Collection**
**Web App Resource** becomes **Web App Connector**

I am wondering if this change in renaming resource types at the UI level would also be reflected in metadata and resource map xml files as shown as an example below: 

```
 <dc:type>
      <rdf:Description rdf:about="http://www.hydroshare.org/terms/CompositeResource">
        <rdfs:isDefinedBy rdf:resource="https://www.hydroshare.org/terms/"/>
        <rdfs:label>Composite Resource</rdfs:label>
      </rdf:Description>
  </dc:type>
```
**to**

```
<dc:type>
      <rdf:Description rdf:about="http://www.hydroshare.org/terms/Resource">
        <rdfs:isDefinedBy rdf:resource="https://www.hydroshare.org/terms/"/>
        <rdfs:label>Resource</rdfs:label>
      </rdf:Description>
 </dc:type>
```
I have not looked other places in the xml document where we would have to make similar changes.  
**NOTE**: If we make this change, it will break **hsmodels**. We also have to make changes to **hsmodels**. In addition, we have to mark all existing bag as dirty so that these files can be updated before download of the bag. If we keep the renaming changes limited to only UI, it will be much less work.

**Comment by horsburgh** [comment]
@pkdash - I talked to @dtarb about this briefly this afternoon. For the metadata encoding, I think it's OK to retain the "CompositeResource" term. In some ways, I still like the connotation of this term (that it contains a composite of stuff that might be of multiple types). And, practically speaking - I'm not sure it's worth the effort right this second to dig really deep into this and root it all out. 

Both @dtarb and I agree that we have some work ahead of us related to file-based metadata where we could raise this again and sort it out at a deeper level with the rest of what is going to have to be done to fully support file-based metadata.

So - my recommendation for right now is to NOT change this in the XML documents.

**Comment by horsburgh** [comment]
@pkdash - Given that we now only have 3 resource types (resource, collection, app connector), we may eventually want to consider how useful it is to show the "type" in places like the landing page. But, I think that's a topic for another day. To address your question directly, I suggest the following:

* The "My Resources" page already uses just "Type" instead of "Resource Type" as the column header in the list of resources. Leave as is.
* The "Type Filter" on the Discover page is actually referring to "Content Type" and not "Resource Type", so on the Discover page I suggest changing the name of the filter to "Content Type". And, do we really need "Filter" in the names of the filters? I suggest just calling them "Temporal Coverage", "Author", "Owner", "Subject", "Contributor", "Content Type", and "Availability".
* The listing of resources on the Collection landing page uses "Type". I suggest leaving as is.
* On the user Profile page under the "Contributions" tab, we still have deprecated resource types. Those need to be removed. We should be left with just the following categories of resources - "All", "Collection", "Composite Resource", "App Connector".
* Group resource listing uses "Type" as the column header. Leave as is.
* Community resource listing uses "Type" as the column header. Leave as is.

Am I missing any other places?

**Comment by horsburgh** [comment]
@pkdash - I knew I was likely missing some place where we had used it. Yes - I think that label should be changed to "Type" consistent with the others. So, in most cases it will appear as:

Type:  Composite Resource

**Comment by horsburgh** [comment]
@pkdash - About face. Talking to @dtarb now. Please leave the semantics on the metadata files alone. On the user interface, we should purge the term "Composite Resource" and just use the term "Resource". So, at the top of the Resource landing page it should say "Type:  Resource" and then on the user's profile page under the contributions tab it should have "Resource" as a category and not "Composite Resource".

I realize that we will still have some inconsistency with the XML metadata files, but the user interface will at least be consistent.

Are there any implementation difficulties or issues with this? We don't want to create an implementation mess, but if these are simple changes to make we would like to be consistent. If there is an implementation mess, then we may want to leave things as they are.

**Comment by pkdash** [comment]
@horsburgh I don't think the changes for the UI are going to be messy. Since we are not making changes to XML meta files, implementation is not difficult. I have made most of the changes already. However, there will be still some inconsistencies on landing page for Collection or App Connector. For example, when deleting an App Connector, the delete modal dialog has a title of 'Delete Resource' and in the body section it contains:

`WARNING! DELETING A RESOURCE IS A PERMANENT ACTION!`

In the 'How to Cite' section of the landing page, we have the following line:

`This resource is shared under the Creative Commons Attribution CC BY. `

I am not sure if these are considered inconsistencies. I am fine with not changing these. Otherwise, it would require a lot of similar places to be changed. 

Another question related to the landing page of web app resource (App Connector) as shown below: 

Should we change "Supported Resource Types" to 'Supported Types'?
What about 'Choose Resource Types' and "Supported Resource 'Sharing Status'? 

![image](https://user-images.githubusercontent.com/2523434/206030105-1c641b7d-c805-4f60-9d5a-90f680af527e.png)

**Comment by dtarb** [comment]
@pkdash I am OK not making any changes to the delete warning or how to cite. 

App connector opens a bit of a can of worms.  I suggest that in the spirit of just having UI changes right now you do
1. Change Resource Specific to "Configuration"
2. Change Supported Resource Types, to "Support", "Choose what this app connector supports (can act on)"
3. Change Supported Resource Sharing Status to "Sharing Status", Choose the sharing status required for this connector.  

![image](https://user-images.githubusercontent.com/3456833/206448408-289b4677-fdc3-4fbe-b364-9dcca61ad288.png)

This does open bigger questions related to App connector that I suggest we do not address as part of this issue, but that a separate issue "Revise Web App Connector" be created to evaluate
- Is it meaningful for App Connectors to act on collections.  We already do not have the concept of an App acting on an App Connector, as the resource types do not list app connector.  I would be supportive of not having resource type at all as an App Connector configuration filter, but this would require checking if there are App connectors that meaningfully use collections that we do not want to break.  
- Is Coverage meaningful for an App connector.  I suggest not, and suggest this metadata be removed.
- Are related geospatial features meaningful for app connectors.  Perhaps.  Could an app act on a Geoconnect resource.  I do not know enough about Geoconnex to know.
- Remove the concept of "require agreement to rights statement before downloading" as there is nothing to download.
- Improve the layout

Since the above do not relate to resource type naming, I think they should be worked on separately.

**Comment by pkdash** [comment]
@dtarb I will implement your suggested changes to app connector landing page. Will create another issue for the rest of the changes.

**Comment by pkdash** [comment]
This enhancement is now complete as part of release 2.1
