### ISSUE TITLE
Human in the Loop Feedback

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#4871]
**Describe the feature you'd like and what it will do**
- [x] When attempt to redeem a Approval/Rejection link that has already been used, instead of raw ValidationError, show a cleaner message in the UI
- [x] In approval email, include either a link to the pending DOI, or recommend that the user check the Resource Landing Page for final approval.

- [x] Links to community guidelines etc in modals

- [x] Email: Right now it says “your resource is being reviewed for minimum metadata” and I just wanted to get to match the text in the notice on the resource that says “being reviewed for minimum metadata and adherence to community guidelines”
- [x] If reviewer doesn't respond within 2 days, ~~auto-approve?~~ send a reminder email!
- [x] Rather than email on metadata approval telling them that Crossref should complete soon: metadata approval sends request to Crossref but email isn't sent until DOI is available (check in Celery job)
- [x] Include feedback for recommended fields (Funding agencies, spatial coverage...)
    -   Funding Agency:At least 1 funding agency
    - Readme File: All variables, abbreviations/acronyms, and non-standard file formats should be defined in the ReadMe file. If folder structure within the resource is complicated, it can be described in the ReadMe file as well.
    - Geographic Coverage: Coverage that describes locations that are related to the dataset in whatever capacity the depositor finds most 
  relevant. 
- [x] On initial submission for metadata review, should we use the existing Django Messages implementation (page refresh) or async requests with feedback in the modal? **DECIDED: Make basic assessment of min metadata and add that into the first modal (if inadequate, don't allow them to click "publish")**

**Why is this feature important?**
Improved workflow (and hopefully acceptance) for Human in the Loop modifications

**Additional context**
These changes build on #4726 and #4863

**Comment by devincowan** [comment]
Crossref sandbox
https://www.crossref.org/documentation/register-maintain-records/direct-deposit-xml/testing-your-xml/

**Comment by devincowan** [comment]
discussed this am on dev call, updating modals would like @dtarb and @martinseul to take a quick look before I commit and ask Pabitra for review:

### First modal, insufficient metadata:
![image](https://user-images.githubusercontent.com/17934193/205698312-1aae6df8-67d3-40a0-9c3b-018d71e7bbb9.png)

### First modal, sufficient metadata:
![image](https://user-images.githubusercontent.com/17934193/205698745-ffccbcbc-b20a-427b-a3e3-e019389912d2.png)

### Second modal:
![image](https://user-images.githubusercontent.com/17934193/205698891-dfb29e93-86c1-4be8-a614-1df12699a0ec.png)

**Comment by devincowan** [comment]
And apologies, but did we finalize desire to change this popup? It wasn't clear what our final desire is:
![image](https://user-images.githubusercontent.com/17934193/205700982-1a84e158-150e-4b4c-9aca-481cd0daa31e.png)

@ClaraCogswell please take a look at this and also https://github.com/hydroshare/hydroshare/issues/4871#issuecomment-1337768584 and LMK suggestions thank you!

**Comment by martinseul** [comment]
yes, we suggested to change the second sentence to: We recommend following these minimum metadata requirements before making your resource public or discoverable: 
- Title (at least 30 Char)
- Abstract (at least 150 Char)
- Keywords (at least 3)

**Comment by devincowan** [comment]
thanks @martinseul 
![image](https://user-images.githubusercontent.com/17934193/205729825-c81bdedd-bc66-44da-9490-951c8d42db4e.png)
![image](https://user-images.githubusercontent.com/17934193/205729927-ede2889f-8d23-425c-b692-b5d6a1b48016.png)

**Comment by dtarb** [comment]
I suggest changing the first modal to 
![image](https://user-images.githubusercontent.com/3456833/205933059-16a94f05-1147-4393-bc11-b16850930137.png)

On the second case of the first modal I suggest using the "permanent" publication name instead of formal.

Title: "Submit resource for permanent publication"

Content:
**Are you sure you want to permanently publish this resource?**.  You will **NOT** be able to edit the content, title or authorship once this resource is permanently published.  Limited editing of other metadata will still be possible to add new information, or correct current information. This publication is **permanent** and you should only continue when you are finished adding or modifying the content of this resource. 

Your resource is missing the following recommended metadata items
- Funding agency
...

The bit about :If you want to share ... seems unnecessary as at this step the resource is already public.
![image](https://user-images.githubusercontent.com/3456833/205937945-a7545524-dbc8-4382-9703-2ce02f88d971.png)

In other places where it says "At least one funding agency" I think just say "Funding agency"

**Comment by devincowan** [comment]
got it, made those changes thanks @dtarb
