### ISSUE TITLE
Develop capability to properly cite content for which HydroShare is not the primary source

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#488]
Edited to accommodate discussion below

This issue addresses the problem discussed in writing the resource data model paper where the SWMM model has been included in HydroShare but without direct acquiescence of the original developers.  This model appears to be public domain so this is allowed, but proper attribution and citation is needed.

I suggest the following
- Resources may have an attribute "Replicated from primary source".  If this attribute is set then they need a "primary source" relationship that gives the citation for the primary source. 
- The How to cite display on the landing page should be changed to indicate the primary source citation

An example of what how to cite should look like is:
EPA, (2015), Storm Water Management Model (SWMM), Version 5.1.010 with Low Impact Development (LID) Controls, http://www2.epa.gov/water-research/storm-water-management-model-swmm, accessed 9/17/2015, replicated in HydroShare at: http://www.hydroshare.org/resource/2cddae40e9594c21b947fdbbe4225439

- The rights statement should replicated rights from the primary source (the owner will have to do this)
- The owner should be labeled as: "Replicated by:"  denoting that for these types of resources the owner is really just replicating the resource.  They do not own it in any rights sense.  

With these changes, I think we would avoid the potential misunderstanding from posting a resource from another primary source on HydroShare.

Following is the email discussion related to this for the record.

I think that in the actions with respect to SWMM we should not think of ourselves as system administrators but as system users.  This changes the perspective a bit.  Sure we are developers of the functionality, but when it comes to posting resources we are using the system we developed.  As a user of any publishing system it is awkward to publish someone elses work.  That is the main issue here.  There are both legal, research ethics and social questions.  Legally SWMM is likely a US government work and in the public domain. So publishing it in HydroShare should not be a problem.  But we should fully confirm this and be able to document this.  Ethically and socially I am uncomfortable publishing something like this totally unchanged where the intellectual ownership rests with others, without their knowledge or concurrence. 

The things that worry me are things like
How to Cite
Rossman, L., T.Schade, D.Sullivan, R.Dickinson, C.Chan, E.Burgess (2015). Storm Water Management Model (SWMM), HydroShare, http://www.hydroshare.org/resource/2cddae40e9594c21b947fdbbe4225439

This is currently on our site.  However the primary authoritative source for SWMM seems to be

http://www2.epa.gov/water-research/storm-water-management-model-swmm.

If I was writing a paper that used SWMM to do some research I would likely cite it
US EPA (2015), Storm Water Management Model (SWMM), http://www2.epa.gov/water-research/storm-water-management-model-swmm, accessed 6/6/2015. 

Now I know that you can get to this from HydroShare via the resource specific website link (that is not a link) but that is a bit circuitous. 

HydroShare does have the concept of referencing things outside of HydroShare.  It cannot be a closed system.  So  is there an option is to reference the SWMM model on the EPA site and only publish our model instance which is clearly our  work.

**Comment by horsburgh** [comment]
Just a couple of considerations here.  A user may have put a copy of SWMM in HydroShare as a Model Program resource to reflect the particular version used for an analysis - effectively freezing it in time.  If our citation points back to some other location, we have no guarantee that the other location will always be available or that the content will not change. In this case, the citation needs to be for the frozen content in HydroShare.  Links to other locations/versions of the content frozen in HydroShare should be expressed in the "Source" or "Relations" elements in the metadata.

In the case where the primary source citation for a HydroShare resource is changed to point at another system, this should be considered a "reference" resource where we have no control over what happens on the other end of the referenced URL.  

Users need to know the difference.

**Comment by horsburgh** [comment]
Removed the Access Control label because I don't think this has anything to do with access control. @dtarb - if you disagree, you can add it back, but I'm having a hard time making the connection.

**Comment by dtarb** [comment]
This issue needs a label so that someone is managing it.  I agree that access control was wrong and it seems to fit better into Resource Model.

**Comment by dtarb** [comment]
Email from @goodalljl on hydroshare listserv thread 9/16/15 that pertains to this issue:

Mohamed, Jeff S., and I continued the discussion about what to do about resources where the authors are not (yet) HydroShare users. The use case we were discussing is where Tony uploaded the SWMM model program resource in HydroShare so that Mohamed could link his SWMM model instance resource to it, but Tony is not the author of the SWMM model program.

I see two alternatives.
1. Have a policy where it is not possible to create a resource that you are not the author (or coauthor) of. This greatly simplifies things, but also means we need to work hard to get people to create HydroShare accounts and upload their model programs. This of course should be our top priority for obvious reasons.

2. Allow "power users" (the core development team for now) the rights to create a resource that we are not the author of. Then if one of the authors later becomes a HydroShare user, they will automatically become owners of the resources (through a name matching process).

I lean toward #2 for now as a practical step for seeding the system, but the hope is that #1 becomes the policy long term.

Looking into this led me to a few other conclusions that I'd like to put forward.

1. We need to remove the word "owner" from the HydroShare UI and instead concentrate on "authors."

ResearchGate is a good example for us to follow. If you look at Mohamed's conference paper on ResearchGate, you will notice that "owner" is nowhere to be found on this page. Why should end users care who the "owner" of this resource is? It is system level metadata. Users only care about the "authors" of the resource.

One implication of this is that on a user's landing page in HydroShare, the resources listed should be the resources that they "authored" not the ones that they "own." We are doing the opposite now. Tony did not author SWMM, but it is listed now on his profile page because he owns it.

2. We should have the policy that all authors (with HydroShare user accounts) are also owners of the resource.

ResearchGate seems to take this approach because, while I did not create Mohamed's paper in ResearchGate, I can edit its metadata because I am listed as a co-author.

3. All authors should have a HydroShare landing page.

Notice on Mohamad's paper that Pabrita is listed as a co-author, but he isn't a ResearchGate user. Pabitra still has a ResearchGate landing page because Mohamed listed him as a co-author. If Pabitra joins, then he could add metadata to his page and this would automatically be reflected in Mohamad's conference paper's landing page. I think we should take the same approach in HydroShare.

Jon

**Comment by dtarb** [comment]
Response from me on listserv to comment above

Here is what I think.

1.  We are far enough down the road of treating creators/authors in the Dublin core sense and users with owner/edit/view privileges in the access control sense as separate (orthogonal) concepts that I do not think we should change that. 

2.  We should cite content outside of HydroShare where appropriate.  There may be cases where a proprietary model is used and it is not legal to include the code or executable in a HydroShare resource.  I grant that reproducibility is diminished, but mention of (by reference) using such a model is still right.  In this case SWMM is not proprietary, so can be included in HydroShare but I do not think it is for 3rd party users to decide.  Right now the SWMM developers have decided to publish it on a website and we should use a standard reference to their website to refer to their model.  Such a reference would be

EPA, (2015), Storm Water Management Model (SWMM), http://www2.epa.gov/water-research/storm-water-management-model-swmm, accessed 9/17/2015.

or if you need to mention a specific version

EPA, (2015), Storm Water Management Model (SWMM), Version 5.1.010 with Low Impact Development (LID) Controls, http://www2.epa.gov/water-research/storm-water-management-model-swmm, accessed 9/17/2015.

We should certainly promote and encourage others to use HydroShare, but until the SWMM developers have done so I think it is wrong to have a resource with the following content.
![p1](https://cloud.githubusercontent.com/assets/3456833/10091809/f860c9f0-62fc-11e5-8732-ddc702097883.PNG)

Tony and Mohamed are not Owners of this resource and HydroShare is not the publisher.

3.  The model instance that refers to SWMM should for reproducibility include the executable or source code where allowed.  So rather than have the model program be a separate resource, include swmm.exe and any of the swmm5008 engine files needed in the model instance resource.  The model instance resource Executed By: entry should be changed to something like
![p2](https://cloud.githubusercontent.com/assets/3456833/10091833/261a6bb2-62fd-11e5-865c-ad086c26497f.png)

4.  There may be cases where the model being referenced is not at a stable/persistent URL so we need to preserve it.  I think we need to develop the concept of a replicate resource for this case where we give proper credit to where the content came from and designate the owners in the HydroShare content as "Replicated by".  Something like
Storm Water Management Model (SWMM), Version 5.1.010 with Low Impact Development (LID) Controls
Replicated from: http://www2.epa.gov/water-research/storm-water-management-model-swmm, accessed 9/17/2015.
Authors: L Rossman, T Schade ...
Replicated by:  Tony Castronova

How to cite:
EPA, (2015), Storm Water Management Model (SWMM), Version 5.1.010 with Low Impact Development (LID) Controls, http://www2.epa.gov/water-research/storm-water-management-model-swmm, accessed 9/17/2015, replicated in HydroShare at: http://www.hydroshare.org/resource/2cddae40e9594c21b947fdbbe4225439

This makes the credit clear and does not portray a false sense of ownership, and is still within rights because the model is public domain.

5.  We should avoid the "power user" concept.  System administration capability should really only be used for essential system administration work (e.g fixing an error a user cannot fix, or deleting an account or resource of a user that abuses the system), not management of the content.  Power users inhibit the process from being scalable.

6.  I think we do need to work out some of the ResearchGate like functionality we need.  I am leery about creating a landing page automatically for anyone.  The resources authored by any author can easily be discovered by an author search on Discovery so no need for a specific landing page.  I do think however, that a user that is an author should be able to control what is on their landing page so perhaps in addition to "resources I own" there needs to be "resources I contributed to" with the user being able to add to these lists resources where their name is in the creator or contributor fields.  This does open a fair bit of complexity in terms of name matching and permissions on resources, so we need to be really careful here and keep things simple.  I don't think ResearchGate's approach where you are continually pestered to say whether you are co-author on a paper is right, and I have found cases where I am an author, but the copy of the paper posted is not the latest actual published version and I have wanted to update it but not been able to.

**Comment by goodalljl** [comment]
Dave,

1. Ok, but I still suggest that ownership should not be conveyed to end users on any landing pages. As you suggest in #2, the "Owners" metadata should not be shown on this page. "Owner" is a loaded term because, while it has a specific meaning in Dublin core, it means something else to the layperson (e.g, Tony and Mohamed do not "own" SWMM). 

2. I think when ever possible we should replicate the resources in HydroShare using the approach you described below. This is important for reproducibility. When replication is not possible, we can just point to an external resource, but that resource might change later so someone needs to watch these pointers.

We are in agreement on this point. My proposed solution again is to remove the word "Owner" from this page. I would support the idea of replacing it with "Replicated By" or "Uploaded by." 

I very much like your suggested citation below:
EPA, (2015), Storm Water Management Model (SWMM), Version 5.1.010 with Low Impact Development (LID) Controls, http://www2.epa.gov/water-research/storm-water-management-model-swmm, accessed 9/17/2015, replicated in HydroShare at: http://www.hydroshare.org/resource/2cddae40e9594c21b947fdbbe4225439

I think this is an important feature provided by HydroShare. We are supporting provenance of model results by doing a capture of a model program accessed at a particular time. 

3. Our approach has been to keep model programs and model instances as separate but related resources. We want to have one-to-many relationships between model programs and the model instances used to run those model programs. We won't stop people from including a model program within a model instance resource (and this might make sense in certain use cases), but we want to encourage keeping these resources separate. One reason for this is so that the metadata for a model program can be stored just once in HydroShare and related to all the model instances that use that model program (rather than each model instance having to repeat the model program metadata). 

4. I agree with this. See my comments to #2.

5. Ok, we won't need power users if users are allowed to create "replicated resources" in HydroShare. 

6. Sounds like we generally agree that authors of resources should, by default, be allowed to edit metadata of that resource. I agree ResearchGate has problems, but this isn't easy to do and I think we may face similar challenges as we grow.

**Comment by dtarb** [comment]
@goodalljl owner is not actually a dublin core term (at least I do not find it in http://dublincore.org/documents/dcmi-terms/).  Owner is a concept in our access control that is separate from the Dublin core creator and contributor.  

I think that Owner needs to be on the landing page, but needs to be labeled differently in certain cases.  The reason to display Owner, is so that a user knows who to contact if there are any questions about the resource in HydroShare, or if they want to request access (if it is only discoverable). 

For most resources the Owner label is fine.  However for a resource designated as replicate (which means we have to have an attribute to set a resource as a replicate), then the label should change to "Replicated by".  

The concept of having labels different from the underling variable is not new with this case, as we already have the label "Author" for the Dublin core term "Creator" on the landing pages.

**Comment by goodalljl** [comment]
@mohamedmorsy suggested a simpler solution. Can we just change "owner" to "HydroShare Owner" for all resources? Then we can have a place where we define terms: "HydroShare Owner is the user that manages the resource's metadata and access control within the HydroShare system." This makes it a bit clearer to users what we mean when we say "owner" and avoids the need to distinguish between replicated and non-replicated resources.

**Comment by dtarb** [comment]
I can agree to this, but we still need the how to cite to appear as

EPA, (2015), Storm Water Management Model (SWMM), Version 5.1.010 with Low Impact Development (LID) Controls, http://www2.epa.gov/water-research/storm-water-management-model-swmm, accessed 9/17/2015, replicated in HydroShare at: http://www.hydroshare.org/resource/2cddae40e9594c21b947fdbbe4225439

**Comment by goodalljl** [comment]
I honestly think giving users the ability to input their own citation metadata (override the autogenerated version) is the simplest way to go. Then we can have a page with citation examples for folks to follow with the one you gave being our suggestion for "replicated resources." 

I know Jeff disagrees with this approach. In that case, we could provide the logic for building this citation for a reference resource, but it isn't done in our resource code. I think it is done in the code Jeff touches. Is that correct, @horsburgh?

**Comment by horsburgh** [comment]
@goodalljl - I'm not totally against this.  I'm just against a free-for-all that might result in lots of heterogeneity in citations. We might want to think through some use cases and how we should handle the citation for each:

1. A referenced resource where there is only metadata in HydroShare and the content is stored/hosted somewhere else
2. A resource with content files stored in HydroShare that were copied from an original source hosted somewhere else (e.g., a "replicated" resource).
3. A resource that originated in HydroShare and whose content files are part of the resource in HydroShare.

I suspect that we could still auto-generate a citation for each of these use cases, and each one might look a little different.  Ultimately, I think we want to have a citation for everything, and I also think we want to minimize what we are asking people to create/fill out. 

But, if I am oversimplifying and there's really a bunch more use cases than this, we may still want to consider an override.

**Comment by goodalljl** [comment]
@horsburgh - I think these are the three main use cases. We should just implement citations for these automatically and then cross the bridge of an override if/when we get to it. How can we help with implementing this? Or is it something you think your team can handle as long as the reference formats are defined. 

One question is what metadata term should we use to distinguish between "reference," "replicated," and "original" resource types? This should be a metadata term added to the generic resource type and inherited by specific resource types. Data as well as models might be referenced, replicated, or original.

**Comment by goodalljl** [comment]
Sorry for the close and reopen. I hit the wrong button.

**Comment by horsburgh** [comment]
@goodalljl - I suspect that this is something that @mauriel133 could do with a little help from @pkdash. Mauriel has done the most work on the resource landing page, so it makes sense to have him work on it. For the three use cases, I think we need to decide what the "standard" citation should look like.  What we have right now covers case number 3.  

To distinguish between the 3 cases, do we need another attribute for a resource, or can it be based on resource type?  For example, right now we have "Time Series" and "Referenced Time Series" resource types, but we don't really have equivalent splits for other resource types (and I'm not sure we want to).  So, maybe an attribute that is set at resource creation is the best way to go.

**Comment by goodalljl** [comment]
@horsburgh - Here is @dtarb 's suggestion for no 2 (replicated resource):
[Authors], ([Year]), [Title], [Location], accessed [Update Date], replicated in HydroShare at: [Resource Landing Page URL]

For no 1 (referenced resource), the best example is Referenced Time Series resource. I think @danames  is leading that resource development and maybe he can suggest a citation format. Here's a starting point to work from ...
[Authors], ([Year]), [Title], [Location], accessed [Creation Date].

To distinguish between the three cases, I think we need a new attribute. Otherwise we would be overloading the resource name (Referenced Time Series, Replicated Time Series, Time Series, Referenced Model Program, Replicated Model Program, Model Program, etc.). Could get messy.

**Comment by dtarb** [comment]
I agree that we need a new attribute.  In early versions of HydroShare we had a more extended Dublin core module, that in addition to the required metadata elements allowed users to add optional metadata elements from a drop down.  We lost this as we went to our more structured data model.  I think we need to reinstate some of this functionality for base resources, perhaps using key value pairs to extend the metadata.

**Comment by goodalljl** [comment]
I think we have arrived at a solution for this as summarized below.

All resources can be either a "reference," "replicated," or "original" resource. The default should be "original."

CASE 1: If the resource is "original" then keep the citation structure as is.

CASE 2: If the resource is "reference" then the  citation structure should be:
[Authors], ([Year]), [Title], [Location], last accessed [Creation Date].

CASE 3: If the resource is "replicated" then the citation structure should be:
[Authors], ([Year]), [Title], [Location], accessed [Update Date], replicated in HydroShare at: [Resource Landing Page URL]

If everyone agrees, then we can start implementing this. @dtarb, should Hong (@hyi) be the one responsible for implementing this?

**Comment by dtarb** [comment]
@goodalljl I think this is generally fine.  For replicated and reference resources there may need to be additional fields in the citation, for example organization in addition to location.  We need to figure out how to use extensible metadata to do this in a simple way.

**Comment by horsburgh** [comment]
Because the citations will be automatically generated, it may be difficult to use "extensible" metadata.  I would lean toward metadata elements that **need** to appear in citations being required.

**Comment by goodalljl** [comment]
@dtarb Sounds good. Should Hong start implementing this? We can refine the details of the citation format later as needed to get it just right.

**Comment by dtarb** [comment]
Yes @hyi can start implementing.  I'd like some brief guidance from @ironfroggy for how best to do extensible metadata.  I differ a bit with @horsburgh in wanting to avoid extensible metadata.  I think we need to have the concept that a user can add  a field that may by default not be there and that the automatic citation generator should appropriately parse that conditional on it being present and format a citation.  

In our our publication specification (https://my.alfresco.com/share/s/wqJISdf_TQS5lJs32OoYZw) we suggested using a standard such as RIS (http://refman.com/training/ris-format).  If we follow this we achieve a degree of generality and may even find some code to reuse.  But we also may be limited as I did not see any tags for concepts like replicated, so lets, after some initial exploration to see if there is reusable/adaptable code, see if we can get to a simple implementation quickly, that we can then refine if needed.

**Comment by goodalljl** [comment]
@hyi has agreed to take on this implementation task. She will let us know if there are questions. The milestone target is the AGU release.

**Comment by hyi** [comment]
@goodalljl @horsburgh @dtarb @pkdash  I want to leverage existing metadata element, specifically, Relation element, to indicate whether a resource is reference, replicated, or original, rather than creating a new attribute on the resource. By default, when the resource is created initially, "original" is assumed for the resource and the current citation format applies. Then the resource can be edited to add Relation to the resource to make the resource reference or replicated which will change "How to cite" format accordingly. It looks to me one can pick "Cites" Relation type and fill in "Related to" field to indicate the resource is replicated from "Related to" (e.g.,  http://www2.epa.gov/water-research/storm-water-management-model-swmm) which will then be used to form "How to cite" text. Not sure how to represent "Reference" resources using the current Relation type (i.e., Data For, Part of, Created by, Version of, Cites), but we should always be able to add more options in Relation type to fit our needs. Any thoughts?

**Comment by goodalljl** [comment]
@hyi I agree with leveraging existing metadata elements if possible. This would be my vote for how to do the relations. It would require custom relationship, but I think these are more logical than the existing relation types.
Reference --> use "is hosted by"  give URL when resource is located in an external system
Replicated --> use "is copied from" give URL when resource was copied from

**Comment by hyi** [comment]
@goodalljl I like what you suggested relation types to add to represent reference and replicated cases. To be consistent with the existing relation types such as "Created By" I suggest we use "Hosted By" and "Copied From" for Reference and Replicated cases. @horsburgh @dtarb Could you chime in to let me know what you think? I can start to implement once I get your thumb up on this.

**Comment by horsburgh** [comment]
For display in the "Relation type" drop down, the terms "Hosted By" and "Copied From" seem appropriate, but see below for other suggestions. When encoding these relationships in the Science Metadata XML document, you would want to use the right terms. For example "isVersionOf" is a formal term from the Dublin Core metadata "dcterms" namespace and so it would be encoded in the science metadata like this:

    <dc:relation>
        <rdf:Description>
            <dcterms:isVersionOf rdf:resource="https://www.hydroshare.org/resource/1a25b11fa1354773b6edb9495e754f4e/"/>
        </rdf:Description>
    </dc:relation>

These two new suggested terms are not in the Dublin Core namespace and so if you want to encode them in the science metadata document in the same way, I suggest using the "hsterms" namespace to define "isHostedBy" and "isCopiedFrom". That means that those terms need to be defined there in the same way all of the other terms we have added to that namespace.  

But, if you want to use terms from the Dublin Core namespace, the closest I can find are "references" and "isVersionOf".  Here's the definitions from Dublin Core:

**references**: A related resource that is referenced, cited, or otherwise pointed to by the described resource.
**isVersionOf**: A related resource of which the described resource is a version, edition, or adaptation.

From http://dublincore.org/documents/dcmi-terms/

**Comment by hyi** [comment]
@horsburgh @goodalljl @dtarb It looks to me "references" Dublin Core term fits our "reference" case well, so I think we should go with Dublin Core term rather than a customized term if possible. @goodalljl Let me know if you agree or not, and if you agree, that will be what I implement for "reference" case. isVersionOf could fit our "replicated" case as well but I am not so sure and need @goodalljl input on whether the Dublin Core term isVersionOf can be used to represent our "replicated" case. So @goodalljl please let me know what you think, then I will implement accordingly.

**Comment by goodalljl** [comment]
@horsburgh @hyi @dtarb I generally like to use Dublin Core definitions if we can. I think the two Jeff suggested would work ok, but I feel "hosted by" and "copied from" are more exact relations for these resources. My vote would be to use these custom terms instead of the core Dublin Core terms unless there is a compelling reason not to (interoperability with other systems like DataOne, for example). One potential problem with "isVersionOf" is that hydrologic models and, in some cases, data have their own version numbers. People my be confused by "isVersionOf" for a resource in this case (is it a version of the model, or is it a copy of the model program stored in HydroShare?). I'm adding @mohamedmorsy to the conversation too.

**Comment by hyi** [comment]
@goodalljl agreed "isVersionOf" is confusing to represent replicated case especially considering we will be using it for HydroShare resource versioning as well. I will wait for input from others especially from @horsburgh and @dtarb to get us all on the agreement before I start to implement.

**Comment by horsburgh** [comment]
@goodalljl and @hyi - I think Jon's terms are fine as long as they are defined in our terms namespace.

**Comment by hyi** [comment]
@horsburgh @goodalljl @dtarb OK. I will implement accordingly by defining our own customized terms with our own "hsterms" namespace.

**Comment by hyi** [comment]
@goodalljl @horsburgh @dtarb These two relations "Hosted By" and "Copied From" should be mutually exclusive, right? In other words, we should not allow both relations be present for any single resource since a reference resource (i.e., with Hosted By relation) cannot be a replicated resource (i.e., with Copied From relation). This will ensure citing format will not be ambiguous as well. Want to confirm with you to make sure this validation is in line with what you think.

**Comment by horsburgh** [comment]
@hyi - Yes they are mutually exclusive.  "Copied from" implies that there is actual content in HydroShare. "Hosted by" implies that the content is hosted elsewhere.

**Comment by mohamedmorsy** [comment]
@horsburgh @goodalljl @hyi Could we adjust the format of these two terms to be "copiedFrom", and "hostedBy" rather than "Copied from" and " Hosted by"?

**Comment by hyi** [comment]
@mohamedmorsy the terms stored in the database will be "isCopiedFrom" and "isHostedBy" with human-friendly display names as "Copied From" and "Hosted By" to be consistent with other existing relation terms. I believe this also conforms to Dublin Core term definition formats, @horsburgh correct me if I am wrong on this Dublin Core term definition formats.

**Comment by mohamedmorsy** [comment]
@hyi I got it. Thanks.

**Comment by dtarb** [comment]
I like the terms "Replicated from" and "Reference to".  We also need an attribute on the base resource that can be one of the following 3 values

- original
- reference
- replicate

An original resource is one where the source material is original.  A reference resource is one that points to a source somewhere else (like a model or data source on another web site).  The "Reference to" relationship gives the link to the source and should be a required item for a reference resource.  A reference resource should have no content files in iRODS, but still has the resourcemetadata.xml file in iRODS that holds title, abstract, creators etc.  There is thus still a bag to download.  A replicated resource is where the content held in HydroShare is a copy of content from elsewhere.  The "Replicated from" relationship is required for a replicate resource.

**Comment by hyi** [comment]
@dtarb I don't think we need an attribute on the base resource since for reference and replicate resources, we need to indicate the source from which the described resource is hosted by/reference to or replicated from in order to form the correct citation accordingly, and the current Relation metadata element fit this very well. We don't want the same information stored in two places, i.e., resource's metadata and in resource itself as attribute, since that would add complexity and could result in out-of-sync problem like the out-of-sync issue we experienced with title being stored as a resource attribute and metadata. Unless there is a specific use case that requires us to add such an attribute on base resource,  leveraging current Relation metadata element can address the citation issue outlined here well. I am currently using "Copied From" and "Hosted By" customized HydroShare terms as @goodalljl suggested, do you want to change it to "Replicated From" and "Reference To"? "Reference To" is actually exactly what is defined in Dublin Core term "Reference" so I am not sure whether we use "Replicated From" as a custom Hydroshare term for replicate resources and use "Reference" dublin core term for reference resources. I am copying @horsburgh and @goodalljl to get their input. Unless I hear an agreement, I will proceed with my current implementation with terms as @goodalljl suggested.

**Comment by dtarb** [comment]
OK.  Perhaps I am being too detailed in suggesting how this should be implemented.  So instead I've written what I think should be implemented as [use cases](https://docs.google.com/document/d/15x9QtzdP-ha2ErMeqMTJKzv9lbLhWZMcsNMRtZR4F_s/) and will leave it for you to implement this in the best way.

**Comment by gantian127** [comment]
@hyi would you please close this issue if you think it is fixed? Thanks

**Comment by hyi** [comment]
The implementation for this has been deployed. Closing

**Comment by dtarb** [comment]
In www.hydroshare.org the citation is currently 
![capture](https://cloud.githubusercontent.com/assets/3456833/12050806/7d439b88-aeb7-11e5-8c8f-adc48b966bc6.PNG)

This is not appropriate in my opinion.  I think it should be 
EPA, (2015), Storm Water Management Model (SWMM), Version 5.1.010 with Low Impact Development (LID) Controls, http://www2.epa.gov/water-research/storm-water-management-model-swmm, accessed 9/17/2015, replicated in HydroShare at: http://www.hydroshare.org/resource/2cddae40e9594c21b947fdbbe4225439

See [use case document](https://docs.google.com/document/d/15x9QtzdP-ha2ErMeqMTJKzv9lbLhWZMcsNMRtZR4F_s/edit).

**Comment by dtarb** [comment]
See also the HEC-HMS resource I have created in HydroShare at [GIUD](https://www.hydroshare.org/resource/77c54c01ab99439abb263ea0e11b18c3/).  I am unable to make this public, as it has no resource files (I have added @horsburgh, @hyi, @mohamedmorsy, @mauriel133, as editors so you can see this.  I did not add @goodalljl as I can not find your account in HydroShare).  Issues to address include

1.  Need to devise a way for an institutional author to be displayed properly.  U.S. Army Corps of Engineers gets presented as Engineers, U.A.
2.  Making public and discoverable should be possible without resource files for a referenced model program such as this.

**Comment by hyi** [comment]
@dtarb Check out the citation for the SWMM model on www.hydroshare.org now: https://www.hydroshare.org/resource/2cddae40e9594c21b947fdbbe4225439/ after I added "isCopiedFrom" relation. To change default citation to the desired citation for replicated SWMM model resource, "isCopiedFrom" relation has to be added. I implemented citation format as outlined by @goodalljl as detailed above in this issue thread. Please check the citation for the SWMM model now after I added appropriate relation and I suggest to close this issue if you think it works as expected. As for the follow-up issues you indicated above on the referenced HEC-HMS resource you created, they are separate issues and should be created as separate issues to be addressed. Specifically, for the No. 1, it is an issue of forming citation for authors. Currently, the Authors, in this specific case, U.S. Army Corps of Engineers are interpreted as one single author with last name as Engineers and first name and middle name initials as U.A., which is hard coded as such for authors in the citation. Perhaps we can add an attribute for users to indicate authors should be as is in citation in this special case, and agree we need to devise the best way to do so, but this is a separate issue specifically regarding author citation format. The No. 2 issue I believe is for specific resource type, in this case, Model Program Resource, to extend a function from the core so that it can override the core restriction that requires resource files before the resource can be made public and discoverable. @pkdash can give specific instruction on how to do so. Both issues are separate from this specific issue and I believe they should be created as separate issues to be better addressed.

**Comment by dtarb** [comment]
Thanks.  Closing.
