### ISSUE TITLE
Verification for changed e-mail addresses

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#49]
Verifying a new e-mail address for an existing profile is a very different thing from verifying the initial e-mail when registering that account.

- The first e-mail leaves the account inactive until verification, but new addresses require the account remain active
- The first e-mail can be stored in the profile, but new addresses need to be stored separately and only assigned to the profile when the verification is complete

In addition, there are some general concerns:
- These verifications need a way to cancel them, both from the profile edit page and from the email received by the account
- Changes in e-mail need to handle the case where a previous e-mail change was already pending verification, cancelling the previous request if the e-mail is changed yet again.

Because of these stark differences with the existing verification link, this feature has to be considered out of scope and really *quite* different. It is a separate feature to be worked. It also adds enough requirements that I would suggest considering *temporary* removal of the e-mail field from the profile form, and only allowing the e-mail be change when the verification to do so safely can be implemented.

**Comment by dtarb** [comment]
I agree with the idea of a *temporary* removal (or greying out or locking) of the e-mail field to protect integrity. 

Following are email rules that we established (from UsernameEmailRUles1.8 document in Alfresco) that pertain here.  I believe that 3.7 to 3.9 address some of the concerns about cancelling, although the point of being able cancel/revoke email change requests from the profile page as well as the email received is new and valid. 

3.1.	Each user account should have a separate and unique email address that they specify at the time of account creation.
3.2.	In the case that a user requests to create an account and an account already exists that uses that email address the user is informed that an account with that email address exists.  This message should provide links to retrieve forgotten username and password.
3.3.	Email addresses should be validated by an email being sent to the user and the user being required to click on a link in the email.  An account should not be created until the email address has been validated (Technically this may mean that there is an account that exists but is activated by the clicking).  A time limit should be set for a user to click on the link and validate the email.  This time limit should be adjustable by a HydroShare system administrator via a system administrator interface.  The initial value of this time limit should be 24 hours and conveyed to the user in the email and in the request account landing page.
3.4.	If the user does not validate the account within the time limit any temporary information retained in the system about creating their account should be deleted.
3.5.	If a user attempts to create an account with an email address for which a validation is pending the user should receive a message that indicates that creation of this account is pending validation of the email address.  This message should suggest the user look in their junk mail in case the validation email is there.  This message should provide a button for the validation email to be resent.  
3.6.	A user may change their email address using their profile page.  If when changing an email address the user requests an email address that exists in the system generate a message that an account with that email address already exists.  This message should provide links to retrieve forgotten username and password.
3.7.	The request to change an email should generate validation emails sent to both the new and the old email address.
3.8.	The email change validation email sent to the new email address should include a link for the user to click on to validate the new email address.  Changes in the email address should only be enacted when this is clicked.  This validation should be active for the same time limit as validation of account creation email.
3.9.	The email change validation sent to the old email address should indicate that a user (probably you) have requested to change the email address for your HydroShare account to <give new email address>.  If this is correct no action is needed.  If this is incorrect (which may mean someone is tampering with the account without your permission) provide a link to click on and revoke the email change.  This link to revoke the email change is intended to reduce the chance that someone can hijack a HydroShare account and should never expire.  So while an email change in the profile is made as soon as the new email account is verified, information needs to be retained so that this may be rolled back if the link to revoke the change is ever clicked.

**Comment by rayi113** [comment]
HydroShare Profile Issues in GitHub: #44, #46, #47, #48, #49, #68

**Comment by dtarb** [comment]
Refer to #695 which supercedes this.  Closing.
