### ISSUE TITLE
HydroShare resource timing out b94e2da3b5094cdfa679ad31fe7fb09d

### ISSUE THREAD

**Issue by ClaraCogswell** [hydroshare/hydroshare#5015]
**Description of the bug**
The resource b94e2da3b5094cdfa679ad31fe7fb09d is timing out and giving a 404 error. you can find the listing through discover but can't open the page (or at least I can't).
Steps to reproduce the bug:
1. Go to ['...'](https://www.hydroshare.org/resource/b94e2da3b5094cdfa679ad31fe7fb09d/)

**Comment by devincowan** [comment]
I just tried, didn't time out for me
![image](https://user-images.githubusercontent.com/17934193/226347809-9a247539-ec59-4694-81ba-23a6b3ec2565.png)

**Comment by ClaraCogswell** [comment]
**Wow I guess it is just me** we can just close this issue then.

**Comment by devincowan** [comment]
well hold on, the timings do look really slow
![image](https://user-images.githubusercontent.com/17934193/226348443-3f540cd1-445d-482d-85ad-c57b47e8b7a2.png)
I'm going to check it out

**Comment by sblack-usu** [comment]
I poked around a little bit and noticed that the response time for viewing the resource is much slower than in edit mode.  That should help narrow down the scope to investigate by quite a bit.  Perhaps injecting some timings on beta (it is slow on beta as well) would help determine what part of the request is slow for this resource.

https://github.com/hydroshare/hydroshare/blob/develop/hs_core/page_processors.py#L121-L214

**Comment by sblack-usu** [comment]
The page template might need to be checked too.

**Comment by sblack-usu** [comment]
Still poking around, the update_view_count method is taking about 20 seconds.  https://github.com/hydroshare/hydroshare/blob/develop/hs_core/page_processors.py#L122

**Comment by devincowan** [comment]
Interesting
recent change:
https://github.com/hydroshare/hydroshare/pull/4938/files#diff-3bc7182059367a2c6cf9e96428d08a0ce66f709baec5d00090abd19683582891L2065

**Comment by devincowan** [comment]
so `content_model.save()` is really slow for this resource. It has a lot of .cpg files

**Comment by devincowan** [comment]
Thanks @sblack-usu sounds like we should try a `content_model.update()` as you suggested.

**Comment by pkdash** [comment]
@devincowan and @sblack-usu I did some checking on this issue. The `update_view_count()` could take a while if there are too many aggregations in the resource due to **solr indexing** triggered as a result of `resource.save()`. I think we can change the code for `update_view_count()` to do an update query to increment `view_count` to bypass solr indexing. I don't think we are currently indexing `view_count`.

**Comment by devincowan** [comment]
nice @pkdash I was thinking it might be something in our **signals** but I hadn't yet suspected SOLR -- good sleuthing, thanks!

**Comment by sblack-usu** [comment]
It'd be nice to make the signal processor for solr async... perhaps something like this? https://pypi.org/project/django-haystack-channels/

**Comment by devincowan** [comment]
not a bad idea @sblack-usu 
I just dropped a breakpoint in [handle_save](https://github.com/hydroshare/hydroshare/blob/2.4/hs_core/hydro_realtime_signal_processor.py#L20) and was surprised that **updating the title of a resource**, a simple change, results in 6 calls to `handle_save`!

1. <Title: Untitled Resourceaaaa>
2. <BaseResource: Untitled Resourceaaaa>
3. <CompositeResource: Untitled Resourceaaaaa>
4. <Date: modified 2023-03-21T13:15:33.646070+00:00>
5. <BaseResource: Untitled Resourceaaaaa>
6. <Variable: Variable object (920)>
1 and 4 are sensical enough. I can potentially see why we need 2 to update the resource index even though we update the Title metadata in 1. I don't understand why we need 3, but I can be convinced easily. 5 is perplexing...seems like a duplicate -- for a simple title change we index the BaseResource to  _twice!?_ oh but I do see that `handle_save` calls itself recursively so that prob what's going on. And then 6 I believe this is an hs_tracking Variable which doesn't get indexed so I guess it's okay.

I feel like some of these calls can obviously be async as @sblack-usu suggested. But might we run into race conditions etc if we are saving the updated date (4) and the BaseResource (2, 5)? Think the answer is "NO" because we are just talking about updating the indexes async, so I would think there wouldn't be a problem (vs for instance, actually saving to the Django db).

**Comment by devincowan** [comment]
@pkdash Scott and I took a look just now.
Seems like we might want to revise our signal processor, [custom haystack processor](https://django-haystack.readthedocs.io/en/v2.4.1/signal_processors.html#custom-signalprocessors)
We are thinking there could be significant performance gain if we trigger (async?) indexing not for all saved objects but just for `Raccess` and `Date` metadata objects with `type=modified`

Pabitra, does that approach make sense to you? I haven't actually looked into the particular instance of a res with lots of aggregations but presumably we could make similar changes in that indexing process

**Comment by pkdash** [comment]
@devincowan I agree with the short-term fix idea.
