### ISSUE TITLE
Web App Issues

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#5115]
**Description of the bug**
1. Bug with Resource level Open With:
   - For a resource with an appkey, web apps with appkey are getting listed even when the resource appkey doesn't match with the web app appkey.
   - For a resource that has no appkey, web apps with appkey are getting listed.

2. Bug with Aggregation level Open With:
   - For a resource with an appkey, aggregation level web apps are not getting listed unless the resource appkey matches with the appkey of one of the web apps.
   - For an aggregation with appkey, web apps with appkey are getting listed even when the web appkey don't match with the aggregation appkey. This happens if the resource has an appkey.
   - A web app configured to work with a given content type and file extension, the web app getting listed at the aggregation level only matching with file extension and ignores file content type. For example, a web app configured to work with 'zip' file and single file content type, the web app getting listed on for a zip file that is not part of the single file content. 

Steps to reproduce the bug:

**Expected behavior**
- At the resource level, web apps with appkey should not be listed unless the resource appkey matches with the web app appkey. If the resource doesn't have an appkey, then all web apps matching the resource type and with no appkey are listed.

- At the aggregation level, web apps with appkey should not be listed unless the aggregation appkey matches with the web app key. If the aggregation doesn't have an appkey, then all web apps matching the aggregation type and with no appkey are listed.

- At file level, web apps with matching file extension should be listed. If the file is part of an aggregation, the web app also needs to match the aggregation type unless there is no aggregation type constraint for the web app. 

- For a web app to be available at resource level, the resource type settings of the web app must match. In addition, if the web app has an appkey, then resource must have a matching appkey.

- For a web app to be available at the aggregation level:
   - If the web app has content type restriction, then the aggregation content type must match. 
   - If the web app has an appkey, then the aggregation appkey must match. 
   - If the aggregation is a file-based aggregation and the web app has file extension(s) constraints, then aggregation file extension must match. 
   - If the aggregation is a folder-based aggregation, then a web app with file extension restriction will not be available at the folder level. However, the web app will be available at the file level of the folder-based aggregation provided the file extension matches. 

- For a web app to be available at the file level (file is not part of an aggregation):
   - Web app must not have any content type restrictions
   - If the web app has file extension restriction, then the file extension also must match.

- For a web app to be available at the file level (file is part of an aggregation):
    -  If the web app has content type restrictions, then the file content type must match with the web app content type restrictions. 
    - If the web app has file extension restriction, then the file extension also must match.
 

- The resource appkey should not have any role on listing of web apps at the aggregation or file level. 

**Additional information**
Add any other context about the problem here such as screenshots, software versions, and browser information.

**Comment by pkdash** [comment]
@dtarb and @martinseul Would like to get your inputs on the **Expected behavior** I have documented (above) in this issue.

**Comment by martinseul** [comment]
@pkdash do you know how many resources actually use this functionality and do you have some examples?

**Comment by pkdash** [comment]
@martinseul I don't think there is a way to find out how many resources use web apps. If owner of a web app configured the app to work with composite resource that means all composite resources will be using that web app. Similarly, if a web app is configured to work with any netcdf aggregation, then all composite resource containing at least one netcdf aggregation will be using that web app. 

If we deploy this work to beta, I should be able to setup some example web apps and test resources to test the web app open with functionality.

**Comment by dtarb** [comment]
@pkdash I have checked the expected behavior you list and agree with it.  Nice work documenting this and sorting it out. I also looked up some of our old design work and link that here for the record
- [Design Rules for Open With](https://docs.google.com/document/d/1CjctGQRIdAC0OxY2S6MhpN7ETaEWSmbESMfNdVzujfA/edit)

Based on my reading I think that the following two behaviors introduce a new restriction compared to the original design rules for open with.

- At the resource level, web apps with appkey should not be listed unless the resource appkey matches with the web app appkey. If the resource doesn't have an appkey, then all web apps matching the resource type and with no appkey are listed.

- At the aggregation level, web apps with appkey should not be listed unless the aggregation appkey matches with the web app key. If the aggregation doesn't have an appkey, then all web apps matching the aggregation type and with no appkey are listed.

However I think that this is a good new restriction.  It means that when a web app connector creator sets an appkey that that web app will only act on resources with that appkey. I see this as a desirable behavior (nice additional feature) as the appkey functionality is to specifically match resources or aggregations, with apps set to act on them.  The documentation will need to be modified to explain this.
