### ISSUE TITLE
Update profile doesn't work

### ISSUE THREAD

**Issue by rphooper** [hydroshare/hydroshare#512]
Attempted to update profile (add picture, etc.) when I click "Update Profile", I am told that the email used is already registered. Hence, it seems to be trying to create a new account rather than updating an existing account.

**Comment by dtarb** [comment]
@rphooper I checked and there are two HydroShare accounts for you.  One named rhooper and one named rphooper.  Both have the same email address.  This is a potential for conflict because if you use the email address to log in, the system may not know which account to log you in to.  Update profile attempts to protect against this - but it is a bug as duplicate accounts with the same email address should never  be created in the first place. This is issue #27.  With your permission I would be happy to acting as admin delete the inactive account (rphooper), then at least you could edit your profile.

**Comment by rphooper** [comment]
Thanks, please do so.

Sent from my iPad

On Jul 6, 2015, at 8:19 PM, David Tarboton <notifications@github.com<mailto:notifications@github.com>> wrote:


@rphooper<https://github.com/rphooper> I checked and there are two HydroShare accounts for you. One named rhooper and one named rphooper. Both have the same email address. This is a potential for conflict because if you use the email address to log in, the system may not know which account to log you in to. Update profile attempts to protect against this - but it is a bug as duplicate accounts with the same email address should never be created in the first place. This is issue #27<https://github.com/hydroshare/hydroshare/issues/27>. With your permission I would be happy to acting as admin delete the inactive account (rphooper), then at least you could edit your profile.

-

**Comment by horsburgh** [comment]
This is a duplicate issue that I believe will be addressed when #27 and #49 are taken care of.  So, I'm going to close this one.
