### ISSUE TITLE
Endpoint for resource file listing can cause internal server error

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#5122]
**Description of the bug**
If a file is missing on irods but exists in database, the endpoint **hsapi/resource/{id}/files/** will respond with a 500  error.

Steps to reproduce the bug:
1. This bug was discovered when debugging for a DSP issue related to registration of a hydroshare resource.
2. It is not easy to reproduce because of the nature of the bug.

**Expected behavior**
When using this endpoint the respond should be 200 http status code. 

**Additional information**
Add any other context about the problem here such as screenshots, software versions, and browser information.

**Comment by devincowan** [comment]
I am suspicious that these dangling files (existing in iRods, not in Django) might be caused by an issue in [data_store_remove_folder](https://github.com/hydroshare/hydroshare/blob/2.6.1/hs_core/views/resource_folder_hierarchy.py#L708)

I can see in the `access.log` that the final entry before we started seeing django `file_list` errors was the following:
> 152.54.2.89 - - [29/Jun/2023:20:51:57 +0000] "POST /hsapi/_internal/data-store-delete-folder/ HTTP/1.0" 499 0 "https://www.hydroshare.org/resource/f8199e05ce4f477abebfddc82eb5aa14/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"

Immediately preceding the first errors in the django log
```
$ grep f8199e05ce4f477abebfddc82eb5aa14 django.log
[29/Jun/2023 20:52:06] ERROR [django.request:224] Internal Server Error: /hsapi/resource/f8199e05ce4f477abebfddc82eb5aa14/file_list/
django.core.exceptions.ValidationError: ['f8199e05ce4f477abebfddc82eb5aa14/data/contents/Seismic/Line5/Line 5_08072021/5006.dat cannot be found in iRODS']
[29/Jun/2023 21:15:50] ERROR [django.request:224] Internal Server Error: /hsapi/resource/f8199e05ce4f477abebfddc82eb5aa14/file_list/
django.core.exceptions.ValidationError: ['f8199e05ce4f477abebfddc82eb5aa14/data/contents/Seismic/Line 5/Line 5_08072021/5524.dat cannot be found in iRODS']
```

It's perplexing though because it appears that the iRODS removal occurs _before_ the deletion in Django:
https://github.com/hydroshare/hydroshare/blob/2.6.1/hs_core/views/utils.py#L1458-L1460

But I'm nevertheless suspicious and would love it if @pkdash would be willing to take a gander at [data_store_remove_folder](https://github.com/hydroshare/hydroshare/blob/2.6.1/hs_core/views/resource_folder_hierarchy.py#L708)
