### ISSUE TITLE
Include README file in bag

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#517]
Based on Rick Hoooper's review of HydroShare he was puzzled by what was received when he downloaded all content as a zipped bagit archive.  When the file is unzipped it is not clear what is what.  This could be helped if at the top level in the bag there was a README file explaining the contents.

**Comment by mjstealey** [comment]
Is this not covered by the link on every resource landing page below the "Download All Content as Zipped Bagit Archive" button: [Learn more about the Bagit archive format](http://en.wikipedia.org/wiki/BagIt)

This seems like something that once you read it, you don't need to have it re-explained and attached to every resource. Otherwise the README becomes part of the bag, and ergo part of the resource itself.

**Comment by pkdash** [comment]
Agree with @mjstealey

**Comment by hyi** [comment]
Also agreed with @mjstealey

**Comment by dtarb** [comment]
I think we need to listen to feedback we get from users of the system who are not intimately familiar with what bags are.  Lets face it, bags are a pretty obscure thing.  Let's make it easy for users to know what they have when they have downloaded it @rphooper was contrasting this with portal.lternet.edu, and he found it hard looking at HydroShare resources to know what he was getting.

**Comment by selimnairb** [comment]
I agree with @dtarb.  It is legal, according to the BagIt [draft](https://tools.ietf.org/html/draft-kunze-bagit-05#section-2.2.4) for there to be a top-level README.txt.  The question is, what should the contents be?  We could make an XSLT stylesheet to render the science metadata as plain text stored in /README.txt on bag creation.

**Comment by zhiyuli** [comment]
Another possible use case is a HS user downloads a zip bag and email it to a non-HS user. A brief readme may be helpful

**Comment by hyi** [comment]
@pkdash putting this on your plate for now. I can work with you on this as needed.

**Comment by dtarb** [comment]
It would be good to get @horsburgh input on this.

**Comment by horsburgh** [comment]
I don't have an issue with there being a readme.txt file in the bag.  However, if it is an automatically generated file that is created when the resource bag is created (which I think it should be), it needs to be kept simple and static.  I don't think we want to be doing any sort of dynamic updates on this text file as the contents of the resource change (if they do change).  I think a plain text description of the bag structure would suffice.  We would just need to write some text for this and add the creation of the text file to the code that creates the bag.

If a user wants there to be a much more descriptive readme document that goes with their resource, we should potentially allow this, but as part of the resource content (i.e., the user uploads the text document as a file within the resource).

**Comment by hyi** [comment]
@dtarb @horsburgh Creating a bag readme.txt when the bag is downloaded is easy to implement. The question is what the content in readme.txt would be. If you can outline what the readme.txt would include, or better yet, give me an example of a mock-up readme.txt file for our resource bag, I can get it implemented relatively quickly.

**Comment by horsburgh** [comment]
@dtarb and @hyi - see the Google Doc at the following URL for an example of a potential readme.txt file for resource bags in HydroShare:

https://docs.google.com/document/d/1OMy5kqJhgjXUfX7fjBMtS1Yc4Zx-pGTdQmrNx5nI8Rk/edit

We might want to have several people look this over to see if it is the right content and at the right level of detail.

**Comment by dtarb** [comment]
See some suggested edits in the Google Doc where I think we should cut right to the chase.

**Comment by hyi** [comment]
@horsburgh @dtarb I will use the "cut to the chase" suggested edit version for readme.txt file initially then. I am planning to include this readme.txt file as part of our code repo under ```docs/bagit``` directory named ```readme.txt``` so that people can look this over and make edits as needed without further code changes after this feature is implemented and deployed.  This ```readme.txt``` file will then be included in every downloaded bag. Let me know if you have further suggestions.

**Comment by horsburgh** [comment]
@hyi - just make sure the alignment on the bagit directory structure example comes out OK in the text file you create. Otherwise, it should be fine.

**Comment by hyi** [comment]
@horsburgh Yes, I have made sure the alignment looks OK in the readme.txt file. One thing I need to confirm with you: the new readme.txt file will be included in the <resource_id> directory of the downloaded bag together with bagit.txt and manifest files. Do we need to create a checksum for this new readme.txt file? Currently, manifest-md5.txt includes checksum for each file contained in data and data/content directories. tagmanifest-md5.txt includes checksum for bagit.txt and manifest-md5.txt. Do we need to add checksum for this new readme.txt into tagmanifest-md5.txt or just simply leave it out from manifest files. After I hear from you regarding this, I should be able to create a PR shortly and hope to include it in the next release so that we only need to modify all resource bags one time before next release rather than do it again in the subsequent release.

**Comment by horsburgh** [comment]
@hyi - Looking at the BagIt spec, the readme.txt would be considered an optional tag file. So, it must have a .txt extension and it must be listed in the "tagmanifest-md5.txt" file with a checksum.  

A couple of other items from the spec that I'm assuming are already met in your implementation of the readme.txt file:

`Tag files are line-oriented, and each line MUST be terminated by a newline (LF), a carriage return (CR), or carriage return plus newline (CRLF).  Tag files MUST end in the extension ".txt".`

`In all tag files except for the bag declaration file, text MUST be  encoded in the character encoding specified in the "bagit.txt" bag declaration file. Tag files except for the bag declaration file MAY include a byte-order mark (BOM) only if the specified encoding requires it for proper decoding.  (Note that UTF-8 does not.)`

**Comment by hyi** [comment]
@dtarb The implementation for this has been deployed to www. Can you test it out and close this issue if it works?

**Comment by dtarb** [comment]
When the readme file is opened on a PC using the default PC text editor "Notepad" the lines all run together.  It looks like
![capture](https://cloud.githubusercontent.com/assets/3456833/18384857/435be64a-764a-11e6-8f7b-a5d51d8072c7.JPG)

I know that @horsburgh quoted some CRLF requirements above.  Is it possible to have a file that is still consistent with these and formatted in a readable way in a default text editor such as "Notepad".

**Comment by horsburgh** [comment]
I opened the readme file in Sublime Text, TextWrangler, and the default TextEdit applications on my Mac. It didn't bleed together like @dtarb showed, but it looked slightly different in all three. It looks like the differences are in the line ending characters. 

There are extra line ending characters that have been inserted - perhaps for compliance with coding standards?  This isn't a code file, so I don't think we need those. The text is basically prose, so there should only be one line ending character at the end of each paragraph rather then splitting the paragraph up into individual lines. Also, line ending characters are different for Windows versus Linux/Mac, so we need something that works on both. 

The BagIt spec says use CRLF. When I saved the file from TextWrangler using CRLF as the line ending character it worked in all of the text editors on my Mac and in Windows.

**Comment by mjstealey** [comment]
@horsburgh is correct, this is due to the EOL character being used.
- Unix/Mac as: `\n`
- Windows as: `\r\n`

Regular notepad does not honor Unix line endings and will just keep everything inline if I recall correctly.
Something like notepad-plus-plus however does have the option to, and it's free.

**Comment by alvacouch** [comment]
It is considered best practice in data publication to translate any .txt files included in a publication into a standardized format -- either windoze or Linux -- so that every bag will contain the same kinds of files. Since this translation is rather trivial, I think we should adopt this. The typical choice is \r\n -> \n (Linux standard).

**Comment by horsburgh** [comment]
Adding both carriage return and line feed seemed to work correctly in text editors on both windows and Mac and is allowed by the BagIt spec.

Also - if the text file is being stored in GitHub as part of the code base, I was reading that GitHub does some management of line ending characters, so watch out for that.

**Comment by hyi** [comment]
@dtarb @horsburgh I have updated readme.txt with CRLF as line ending, and @mjstealey has helped me to remove existing readme.txt file from all resources on iRODS side and reset bag_modified to true so that bag can be regenerated with updated readme.txt file. My test shows readme.txt can open up with correct line endings in nodepad now. Can you test on www to see whether readme.txt line endings look good now? It looks like github will not modify the file although they may display it with modified line endings, so we should be good to put this readme.txt file in github.

**Comment by dtarb** [comment]
This is better, but there are still extra line endings in paragraphs.  As @horsburgh noted, The text is basically prose, so there should only be one line ending character at the end of each paragraph rather then splitting the paragraph up into individual lines.

**Comment by hyi** [comment]
@dtarb @horsburgh If I remove extra line endings in paragraphs, nodepad will display the whole paragraph in one line if word wrap is not on, which I believe is default option. Do we really want that or keep the current extra line endings?

**Comment by dtarb** [comment]
I wrote the comment above because my preference is for the extra line endings to be removed and there to only be line endings at the end of paragraphs.  It is a small point, and I am OK for you to do what you think is best, but when I am asked, that is what my answer is.

**Comment by hyi** [comment]
@dtarb Have removed extra line endings within paragraphs. Please test on www.hydroshare.org and see if everything looks good now, and if so, please close this issue.

**Comment by dtarb** [comment]
Perfect.  Thank you.
