### ISSUE TITLE
NULL character after final newline in bagit.txt

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hydroshare#528]
The Bagit rule on iRODS may have a bug causing the bagit.txt tag file to contain a NULL character ('\0') after the final newline.

For example:

    hexdump -c b7822782896143ca8712395f6814c44b/bagit.txt 
    0000000   B   a   g   I   t   -   V   e   r   s   i   o   n   :       0
    0000010   .   9   6  \n   T   a   g   -   F   i   l   e   -   C   h   a
    0000020   r   a   c   t   e   r   -   E   n   c   o   d   i   n   g   :
    0000030       U   T   F   -   8  \n  \0                                
    0000038

This NULL character is causing the bagit library to raise an exception when loading the Bag for validation.  This is part of the work I am doing to teach the API how to consume bags.

This may be due to how we are using the WLEN variable in our rule (which I think is a built-in special variable in the iRODS rule language), which is used [here](https://github.com/hydroshare/hydroshare/blob/master/hydroshare/irods/ruleGenerateBagIt_HS.r#L29).

@hyi and @xu-hao Can you take a look at this and advise?

Once we identify and fix this problem, we'll need to re-make all bags in iRODS as this is causing our bags to fail to load, much less to validate, using the LOC's [bagit library](https://github.com/LibraryOfCongress/bagit-python).

**Comment by hyi** [comment]
@selimnairb WLEN is an output variable that holds the bytes written to the data object returned from msiDataObjWrite() micro-service, which could be a variable of any name, so WLEN developer-defined variable is not an issue here. In fact, that NULL character after new line is the EOF character that indicates the end of line, which is added automatically when writing a text file by a C/C++ function. Which bagit library are you using to validate the bag? I don't understand why this library raises exception for the bagit.txt file with a EOF character at the end of the file. What is the detailed message of the exception?

**Comment by selimnairb** [comment]
@hyi Thanks for clarifying and purpose of the WLEN variable.

As I stated in my original post, I am using the LOC's [bagit library](https://github.com/LibraryOfCongress/bagit-python).  The library chokes on the NULL character, which is not EOF, and can, but should generally not be contained in an ASCII/UTF-8 text file because most code does not expect to find a NULL character in text data.  For example, in a C program, errant NULL characters will wreak havoc as it is used to terminate strings.  Also, Python's built-in strip() function does not strip NULL characters:

    >>> 'foo\0'.strip()
    'foo\x00'
    >>>

This is a bug in our bag implementation.  This raises another issue in that I do not think that we are currently are not validating our bags on creation (please correct me if I am wrong).  This is something I think we should add to the bag creation workflow.

**Comment by hyi** [comment]
@selimnairb I took a look at the source code of the iRODS msiDataObjWrite micro-service used in our bagit rule, and it appears iRODS intentionally allocates one more character than the content to be written and memset the initial write-buffer to be all NULL (i.e., 0). In my mind, it is quite common to write a EOF character (usually NULL) to indicate the end of file, see https://en.wikipedia.org/wiki/End-of-file for some information on EOF. This microservice we are using is a basic service function that is used widely in iRODS, so I doubt that they would change it to remove this EOF null character, but agree it won't hurt to ask to see what they say about it. Since we are creating the bag based on bagit spec (currently the version we conform to is 0.96), we should make sure the bagit rule conform to bagit spec, so I don't think bagit validation is needed during bag creation workflow. However, when we reflect bag to create a HydroShare resource, I agree the bag validation is needed to make sure the bag being ingested is valid. Is it possible to remove the last null EOF character from bagit.txt if there is one before feeding it to bagit validation lib as a workaround? This seems to me a simple solution to this problem given that we are using a base iRODS microservice to generate bagit.txt file.

**Comment by selimnairb** [comment]
It is not common for NULL character (ASCII 0x00) to appear in a plain text file.  Here is how less treats it:
    less bagit.txt
    BagIt-Version: 0.96
    Tag-File-Character-Encoding: UTF-8
    ^@
    bagit.txt (END) 

Emacs:
    BagIt-Version: 0.96
    Tag-File-Character-Encoding: UTF-8
    ^@

    -uu-:---F1  bagit.txt      All L1     (Text)------------------------------------
    Loading image...done

I don't think it is intended or desirable for their to be a "^@" in the bagit.txt.

**Comment by selimnairb** [comment]
@alvacouch @horsburgh @ironfroggy @dtarb Can you help us with this discussion?

**Comment by dtarb** [comment]
I think that the bags that we create should pass validation by the Library of Congress Bagit library that @selimnairb mentioned.  So if this character is causing them to fail then we need to find a way to remove it.  There is of course the possibility that there may be something else causing the failure, but we need to work to get our bags to pass.

**Comment by hyi** [comment]
One way to work around this issue is to generate bagit.txt on Django side and transfer it to iRODS. But the manifest-md5.txt and tagmanifest-md5.txt need to be generated by iRODS rule and the msiDataObjWrite() micro-service still adds an EOF character at the end of the file. Not sure whether they would cause validation failure, so having Django generate bagit.txt may not be sufficient.

**Comment by selimnairb** [comment]
@xu-hao Why are micro services putting NULL characters (ASCII 0x00) into text files?  This seems like a bug to me (off-by-one error).

**Comment by xu-hao** [comment]
Brian,

This does seem like a bug. Would you like to submit a github ticket on the
irods repo?

Thanks,
  Hao

**Comment by hyi** [comment]
@selimnairb When you write the issue, you may refer to the statement here: https://github.com/irods/irods/blob/2d9e340328cc03b883f0f65972909187c305f3ae/iRODS/server/re/src/reDataObjOpr.cpp#L701 which increases the length of the input string buffer by 1 before writing the buffer to the data object file.

**Comment by mjstealey** [comment]
Fix looks to be completed and staged for version 4.1.4: https://github.com/irods/irods/issues/2795

**Comment by hyi** [comment]
I think the fix to this issue involves: (1) upgrade iRODS to version 4.1.4 to have iRODS fix included. (2) set AVU metadata dirty flags (set 'bag_modified' to true) for all existing bags. This is better done automatically with a script. I am setting the milestone to release 1.7 for now.

**Comment by selimnairb** [comment]
@hyi I need this to implement resource creation from entire bags in the REST API.  Having this on a dev. machine soon would be helpful.  Perhaps you could test the steps outlined above.

@mjstealey Which machine can we do this on?

**Comment by hyi** [comment]
@selimnairb Since I will be out for a few weeks starting from next week, and iRODS 4.1.4 is not out yet, so I thought this fix cannot make it into release 1.6 slated for next month. If @mjstealey can designate a VM for this and can have iRODS 4.1.4 installed there, you can test it out by creating new bags, or just modify a bag metadata to tag it dirty so that the bag can be recreated without this NULL character in the end for your testing. I will have to work on the script upon my return from my vacation.

**Comment by dtarb** [comment]
I do not think we should let waiting for an official iRODS 4.1.4 on this hold up development.  Can we implement development iRODS build with this fix on one or more (or all) of our development machines.  Then this can get this API developed and tested.  For the final deploy we will need iRODS 4.1.4, but I think @mjstealey or others ar RENCI can help, so we do not have to delay because @hyi is away.

**Comment by selimnairb** [comment]
@mjstealey Do we/can we get a version of iRODS with this fix up and running in a test environment?

**Comment by mjstealey** [comment]
@selimnairb - Have a preview build of 4.1.4 with the fix running on hydrotest41.

This is the iRODS server that the hsproxy account uses if you're working with the vanilla develop code from github (local_settings.py definition for iRODS user).

**Comment by hyi** [comment]
@selimnairb @mjstealey Since an official irods v4.1.4 is released (ftp://ftp.renci.org/pub/irods/releases/4.1.4/), I guess upgrading irods runtime and icommands to v4.1.4 in Dockerfile in HS dev env will enable testing to make sure this issue is fixed.

**Comment by hyi** [comment]
@selimnairb I tested this on dev and this issue appears to be resolved. Here is the hexdump output for bagit.txt:
hexdump -c bagit.txt
0000000   B   a   g   I   t   -   V   e   r   s   i   o   n   :       0
0000010   .   9   6  \n   T   a   g   -   F   i   l   e   -   C   h   a
0000020   r   a   c   t   e   r   -   E   n   c   o   d   i   n   g   :
0000030       U   T   F   -   8  \n                                    
0000037

Could you test and close this issue if it works now?

**Comment by ironfroggy** [comment]
This has been merged and deployed already. This ticket can be closed, yes? @selimnairb
