### ISSUE TITLE
Integrate coverage testing with Jenkins

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hydroshare#532]

**Comment by selimnairb** [comment]
Integrate coverage testing with Jenkins so that each commit to develop will trigger coverage tests to run, with an HTML coverage test being published to Jenkins.

**Comment by pkdash** [comment]
@selimnairb Do we still need unit test run and coverage reporting on each commit to develop when we are doing this once a day (but not on each commit)?

**Comment by ironfroggy** [comment]
I think it would be important to run on each commit, so that we always know for any branch's most recent state if it passes tests or not. If we have already run them on each branch, then when that branch is merged to develop (and eventually to master) the tests are already run for that commit, since every merge to develop and master should always be a fast-forward (no merge commit).

**Comment by pkdash** [comment]
I assume running test on each commit is a manual process that a developer does on his/her branch and not by Jenkins.

**Comment by ironfroggy** [comment]
Certainly not. If its going to be repeated it should be automated.

**Comment by pkdash** [comment]
Not sure how we automate this.

**Comment by ironfroggy** [comment]
Jenkins has very robust support for triggering a job based on a hook being triggered from GitHub. Travis CI has very complete support for this.

**Comment by pkdash** [comment]
OK. I will try to setup a Jenkins job to do that.

**Comment by hyi** [comment]
@ironfroggy just to clarify, you mean we should run tests on a feature branch when there is a PR to merge this feature branch to develop rather than run tests on a feature branch for any commit, right? Since developers may push commits with intermediate feature implementation which may not be ready for testing yet, I think you must have meant the former to run tests on a feature branch when there is a PR for merge, but want to confirm with you just to be sure.

**Comment by ironfroggy** [comment]
Some project choose to run automated tests on Pull Requests and other choose to run them on every branch, regardless of whether that branch is part of a pull request yet or not. I favor the second option, as it ensures develop and master always have up to date tests run on their latest commits, and allows in-progress branches a quick monitoring of status.

Intermediate branches don't always pass tests, but that isn't a reason never to run tests for intermediate branches, either.

**Comment by selimnairb** [comment]
@pkdash Is there anything more to do on this?

**Comment by dtarb** [comment]
Closing.  We have some level of testing, that needs to be continually improved.
