### ISSUE TITLE
Publication notifications are inadvertently sent during metadata update (re-deposit)

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5406]
**Description of the bug**
Publication email (example below) should only be sent upon initial publication of a resource.
However, they are being sent during metadata update on a previously published resource.

> Dear Resource Owner,
The following resource that you submitted for publication: http://www.hydroshare.org/resource/31f30d14c88748d986842d278d125a5c/ has been reviewed and determined to meet HydroShare's minimum metadata standards and community guidelines.
> The publication request was processed by [Crossref.org](https://www.crossref.org/). The Digital Object Identifier (DOI) for your resource is: https://doi.org/10.4211/hs.31f30d14c88748d986842d278d125a5c
> 
> Thank you,
> 
> The HydroShare Team

Relevant code block:
https://github.com/hydroshare/hydroshare/blob/2.13.3/hs_core/tasks.py#L379-L392

**Additional information**
HS v 2.13.3

**Comment by dtarb** [comment]
Explanation for @horsburgh and @AmberSJones. This was discussed during HydroShare call 3/11/24. The www resource in question is https://www.hydroshare.org/resource/31f30d14c88748d986842d278d125a5c/ and indicates a last updated date of Feb 7, 2024.  The metadata appears to have been updated on this date and this update triggered the email. There happened to be an older snapshot of this resource on beta  https://beta.hydroshare.org/resource/31f30d14c88748d986842d278d125a5c/.   This indicated a last updated date of May 25, 2018.  I downloaded the bags of both versions and used Beyond Compare to look at the metadata differences.  I found that in the beta version there is a problematic character in the abstract 
![image](https://github.com/hydroshare/hydroshare/assets/3456833/4bf3d800-20f4-477f-8898-a46b2ce2a36e)
This is fixed in www, so the inference is that one of the allowed editors edited the abstract to remove this character on Feb 7, 2024 and this triggered the email.  

This appears to support the extent of errant emails being sent only to owners of resources who edited the metadata after publication.

Being explicit about these dates has prompted the suggested enhancement #5410

**Comment by devincowan** [comment]
@dtarb thank you for the thorough digging into this issue. The explanation makes perfect sense. We released an automated fix for invalid XML chars as part of 2.13 addressing the following issue: https://github.com/hydroshare/hydroshare/issues/5306. 2.13 was released on Feb 7th.
So after that release, an automated process removed the invalid character from the abstract. Then, because the resource had been "updated" (the abstract had a control character removed) another downstream automated process submitted the new XML to crossref and due to this issue #5406, email was accidentally sent.

**Comment by dtarb** [comment]
@devincowan Goodness - what a cascade of unintended consequences.  I believe that an automated update done by the system should not change the updated date.  Updated date changes should only be when a user does something.  I think we have discussed this.  Therefore for this resource the last updated should go back to an earlier date - likely May 25.
