### ISSUE TITLE
django or irods will add a random string to filename if users upload a duplicate file

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#544]
![image](https://cloud.githubusercontent.com/assets/10070599/8939589/7806c924-3522-11e5-932a-d2e40548d035.png)
http://dev.hydroshare.org/resource/d788cbc0d1184121bc8a5da5fabb503e/

Users can upload additional res files on a res landing page (if this res type allows). If the new file has a same name as a res file already exists on irods. Django? or IRODS? will rename the new file by adding a random string. The inherent renaming mechanism seems reasonable. However we should handle it properly to prevent unexpected errors. 

This problem may affect all res types which 
1) allow user to upload multiple files;
2) have not implemented callback function pre_add_files_to_resource_handler() in receivers.py

Also this may partially explain what was happening in #478 (see snapshot 5).

**Comment by pkdash** [comment]
Unique file names are created by Django.

**Comment by mjstealey** [comment]
All file systems enforce uniqueness as common practice.
If you are writing two files to the same directory, they must have different names in order to exist within the same level of a directory structure.

Reference: [File Name Uniqueness](https://en.wikipedia.org/wiki/Filename#Uniqueness)

**Comment by dtarb** [comment]
I support option 3.  The current behavior is functionally the same as option 3, just not a simple integer.  I think that the current behavior is thus OK.  However we do need functionality to be able to rename a file, so that a user can delete the old file and remove the appendage of the name on a new file if they want.  Showing dates associated with files would help the user in doing this. A thorough solution might be
 1. If the action is occurring interactively, do what Windows does and offer the user the option to 
    a. Copy and replace (overwrite)
    b. Don't copy
    c. Copy, but keep both (with appendage to name)
 2. If the action is occurring automatically through an API just do the Copy but keep both (with appendage to name).

The paradigm used by Windows is well understood by many users so if we can implement it, it would be good.

I am putting this in the appearance category as an enhancement, as right now the current approach is functional.

**Comment by dtarb** [comment]
Closing this.  I think file name clash handling is OK and this is pretty stale.  If the issue comes up again, we can open.
