### ISSUE TITLE
User changed email address from .edu email on account, can't login

### ISSUE THREAD

**Issue by ClaraCogswell** [hydroshare/hydroshare#5444]
**Description of the bug**
"tried to change my account to a new email ([wyatt.k.reis@usace.army.mil](mailto:wyatt.k.reis@usace.army.mil)) from [wyatt.reis@colostate.edu](mailto:wyatt.reis@colostate.edu) last week but am now having trouble logging into my account. I have tried to reset my account using the @colostate.edu email but I keep getting an error. Can you help me access my account?" 

Is this related to the addition of a non .edu email and keycloak?

**Expected behavior**
I think he should be able to update the email address
**Additional information**
![image](https://github.com/hydroshare/hydroshare/assets/90924476/abfa5046-6ed0-45f4-8ff0-cddc6061768b)

**Comment by martinseul** [comment]
@sblack-usu would you please take a look at this one.

**Comment by sblack-usu** [comment]
This is the first user that has updated their email address since the keycloak deploy. I have a hunch that it has to do with the email being updated in django but not pushed to keycloak and then when the user tries to login, the emails no longer match which results in the error.

**Comment by sblack-usu** [comment]
It looks like there are 2 approaches to solve this. We can either sync profile changes to keycloak or overwrite the OIDCAUthenticationBackend methods to use username instead of email for an id. We will eventually need to sync profile changes to keycloak once the keycloak user profile management supports custom attributes at a later date. I'm leaning towards using the username for the id because usernames do not change. By using the username for identifying a user, we won't see authentication problems from a profile sync fail.

It looks simple enough to just overwrite the user lookup to use username instead of email https://github.com/mozilla/mozilla-django-oidc/blob/main/mozilla_django_oidc/auth.py#L77

**Comment by ClaraCogswell** [comment]
Can we move ahead with the fix scott recommended @martinseul ?

**Comment by martinseul** [comment]
I don't have a strong preference for either so I'm fine with the solution @sblack-usu proposed. Can we update the username manually to get the user unstuck?

**Comment by sblack-usu** [comment]
It is the email that changed, not the username. The username cannot change. I just created a patch that will allow the user to login if the user uses username or the old email. Unfortunately, we will still need to sync the email over to keycloak in order to allow the new email to be used for logging in.  I'm looking into syncing the email.

**Comment by sblack-usu** [comment]
@martinseul - I nearly have a PR ready for this patch. We can fix the user immediately by reverting their email address back to the old one.

**Comment by sblack-usu** [comment]
@ClaraCogswell - @martinseul updated the email address in keycloak and resolved the issue for issue for the user. The user should be able to login without issue now. We'll push out the patch to prevent future users from running into this problem next week.

**Comment by sblack-usu** [comment]
Verified on production
