### ISSUE TITLE
Change content of account registration email

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#565]
Per @mjstealey 

We’ve had some issues with some mail services, google in particular, automatically flagging emails from HydroShare as spam.

At RENCI the SPF portion of the DNS entry for mail.hydroshare.org in Media Temple has been updated to better account for this, but it was advised that we also change the contents of the generated email.

**Comment by hyi** [comment]
We use Mezzanine's email template out-of-the-box as content of our registration signup verify email as shown here: https://github.com/stephenmcd/mezzanine/blob/280642c8d0e7e41b90398c974a15533f6df20049/mezzanine/accounts/templates/email/signup_verify.txt

If we can come up with a better content language for our registration verify email, I can try to override the default mezzanine email content template and direct Mezzanine to use our own email language instead. @dtarb @horsburgh Suggestions on the registration email content to avoid being flagged as spam by email servers?

**Comment by dtarb** [comment]
Please use:
Welcome to HydroShare.  This email address was used to request an account on HydroShare.  If you originated the request, please use the link below to verify your email address and activate your account.  If you did not originate this request you may ignore this email and the account request will expire.

The HydroShare team.

**Comment by ironfroggy** [comment]
The part about the request expiring is likely to be untrue. Unless you have some customization place I have not seen, Mezzanine's registration and account verification has no expiration. An unresponded verification email could remain valid forever.

**Comment by dtarb** [comment]
OK.   Lets delete "and the account request will expire.".  I do think we need an expiry clean up process that runs say every 24 hours and deletes account requests older than 24 hours (so a request could persist 24 to 48 hours) because otherwise if a person makes a legitimate request but does not respond and loses the email that email address is locked out forever.

**Comment by hyi** [comment]
@dtarb @ironfroggy I have override default Mezzanine email verification content with the suggested one and also changed subject of email verification from "Activate your account" to "Activate your account in HydroShare". I also found out the verification link does expire in the same way as the password reset link since the token generated is time stamped and will expire in a time duration set up by PASSWORD_RESET_TIMEOUT_DAYS variable with the default value being 3 days and we can set it to be 1 day to make it expire in 24 hours. My only question related to this issue is how we should clear up the inactive user being created if the user does not click the link in the verification email within 24 hours. I can add clean-up code to delete the inactive user when this email verification link is clicked beyond 24 hours, but not sure whether this is sufficient and whether it is worth the effort since it does not cover the case where the email verification link is never clicked which will leave some inactive users hanging around in our system. In addition, in django documentation https://docs.djangoproject.com/en/1.4/topics/auth/, it states that we recommend that you set this is_active flag to False instead of deleting accounts; that way, if your applications have any foreign keys to users, the foreign keys won’t break. Of course, system admin can always go to admin page to clean up inactive users periodically as needed. So I am not sure what is the common practice for this scenario. @ironfroggy any suggestions/advice?

**Comment by ironfroggy** [comment]
I think if you set the link to expire you should still leave the account. If they want back in they should be able to re-enable the account by a password reset.

**Comment by hyi** [comment]
@ironfroggy OK. Sounds good, then I don't have to do anything extra and can create a PR for code review now.

**Comment by hyi** [comment]
@dtarb @ironfroggy @mjstealey  Tested on dev and everything works as expected. However, this activation email is initially flagged as spam by gmail, and I have to remove the spam label initially to have it moved into inbox onward. Not sure what else we can change to make the email more legitimate without being flagged as spam by different email service providers.

**Comment by ironfroggy** [comment]
That's always a difficult thing and there are not easy answers.

**Comment by hyi** [comment]
@dtarb This has been deployed to www. You can test it out on either www or dev and see whether this issue can be closed. See the comment thread for this issue which provides context for the current implementation.

**Comment by gantian127** [comment]
@hyi @dtarb would you please close this issue if you think it is fixed? Thanks

**Comment by dtarb** [comment]
@hyi please change the email as follows

> Welcome to HydroShare. This email address was used to request an account on ~~HydroShare~~ www.hydroshare.org.

> If you originated the request, please use the link below to verify your email address and activate your account.

> https://www.hydroshare.org/accounts/verify/...

> If you did not originate this request you may ignore this email ~~and the account request will expire in 24 hours~~.

> **The HydroShare Team**

Please check on the last issue.  @ironfroggy noted that the expiring is unlikely to be true. I think we should implement expiring when possible (a separate issue) but not state it in the email in case we are unable to.  Please add "The HydroShare Team" at the end.

**Comment by hyi** [comment]
@dtarb Expiring in 24 hours has already been implemented, so the statement "the account request will expire in 24 hours" is already true in our current implementation. See my detailed info above in this issue thread for details. So I will change email message slightly as you detailed above, i.e., replace HydroShare with www.hydroshare.org and add "The HydroShare Team" at the end while keeping the expiration statement. Will create a PR shortly.

**Comment by mjstealey** [comment]
Using a gmail account the following email was received when creating a new account.
Of note is that it was flagged as **spam**

<img width="1246" alt="screen shot 2016-01-04 at 12 31 08 pm" src="https://cloud.githubusercontent.com/assets/5332509/12095893/ba085820-b2df-11e5-9850-01f39686de16.png">

Still need to verify that the 24 hour timeout expiration is as advertised (will perform this on another VM as dev gets rebuilt frequently).

**Comment by dtarb** [comment]
Even with expiry implemented I think we should delete the words "and the account request will expire in 24 hours." from the email.

With respect to SPAM, I receive emails sent to support@hydroshare.org.  A huge number of these are spam marketing better health and libido products.  I wish there was a way to stop them, but somehow this email address has gotten on a list that attracts these.  I do not know whether this is related to the legitimate emails we send being flagged as spam.

**Comment by hyi** [comment]
@dtarb @mjstealey Could you test to see whether this issue has been addressed adequately for now and close if the answer is yes?

**Comment by dtarb** [comment]
Verified
