### ISSUE TITLE
"Executed by" field for model resource instance needs more models

### ISSUE THREAD

**Issue by vmmerwade** [hydroshare/hydroshare#580]
I wonder how the "executed by" drop box is populated for model instance resource. Right now it show some model types that i am not familiar with. I was hoping to see at least some common models. Eg HEC models. I created a hec-hms model instance resource and lets the "executed by" as unspecified.

**Comment by mohamedmorsy** [comment]
@vmmerwade this is due to Hydroshare has no Model Program resource type called HEC-HMS model and at this point you have two choices: i) Create a new Model Program called HEC-HMS model that includes specific metadata data term for this resource and the model engine (EXE), ii)choose from the drop list "Unspecified" till you create the Model Program resource.

**Comment by Castronova** [comment]
All model programs that exist in HydroShare are populated in the "executed by" drop box.

**Comment by dtarb** [comment]
Some questions to consider that may relate to scalability and usability of this field.  

1. Will we only allow model instances for models that have model programs already in HydroShare. 
2. What if the model program that a model instance wants to refer to is not shared with the user creating the model instance.

**Comment by mohamedmorsy** [comment]
As this is a question, I am closing this issue.
