### ISSUE TITLE
dc:format element(s) in resourcemetadata.xml ambiguous and redundant

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hydroshare#600]
The dc:format element(s) that appear in resourcemetadata.xml are currently not associated with an identifier that specifies the resource file to which they belong.  Also, there is a dc:format element that appears in resourcemap.xml, but as a part of the description of each resource file.

Therefore, I propose we remove the dc:format element(s) from resourcemetadata.xml because they are ambiguous and redundant.  However, as this was part of the original specification I would like to better understand what's going on to make sure I am not missing something.

Would removing the dc:format elements from resourcemetadata.xml cause a problem for anyone?

@horsburgh Could you weigh in?

**Comment by horsburgh** [comment]
@selimnairb - We did this by design. The "Format" element in the resourcemetadata.xml file refers to the resource as a whole. Consider a resource that is a GIS shapefile. The format of the resource is "Shapefile". But, a shapefile is made up of multiple files that may each all have a separate format. So the "Format" elements in the resourcemap.xml file refer to each individual file.

The "Format" element in resourcemetadata.xml is an optional element. So, if it is not relevant for a resource, it doesn't have to be included. I would advocate for keeping the "Format" element in both places.

**Comment by selimnairb** [comment]
@horsburgh I understand.  However, I'm not sure it is being used as intended.  For example, NetCDF resources have two files on creation (the .nc file, and a text file created as part of the automatic metadata extraction).  The resourcemetadata.xml has two dc:format elements, one for each file.  Does this make sense as something we want to enable?

**Comment by horsburgh** [comment]
Agreed that this is problematic in the science metadata for resources that have multiple files of different formats.  The science metadata specifications document states that the "Format" element is optional and repeatable.  So, I'm guessing it was implemented according to the document and there is a "Format" element for each file in the resource (if known).  But, I'm guessing there isn't a specification of which "Format" element goes with which file.  This is solved in the resource map document.  Given that we have the "Type" element that specifies the HydroShare resource type in the science metadata and the resource map document that links a "Format" element to every file, I would be OK with leaving the optional "Format" element out of the resourcemetadata.xml or with only using it where all of the files in a resource make up a "Format" (i.e., like a shapefile).   But, I'm not sure what all the implications would be.

**Comment by pkdash** [comment]
@horsburgh I assume we have decided to remove the 'Format' element from the science metadata document.
