### ISSUE TITLE
+1 rating functionality

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#611]
[ ] When a resource or comment (item) has no +1 ratings the message should say "Be the first to +1 this." Delete the word resource so that the same comment applies to both resources and comments. 

[ ] When an item already has +1 ratings the message should say "nn others +1 this." if there are other ratings, or "You and nn others +1 this." if the user has already rated and there are other ratings, or "You +1 this." if the user is the only to rate the item so far.  Here nn designates the number of other ratings of the item.
  
[ ] When a user clicks +1 the message should change to "You and nn others +1 this." or "You +1 this." according to the rule above.  

[ ] A user can not +1 an item more than once, but should be able to withdraw a +1 rating.  To facilitate this, when a user has already rated an item, the +1 button should change to "Withdraw +1".

**Comment by hyi** [comment]
@dtarb I implemented this rating functionality as you outlined with little variation. Specifically, since the button will change to "Withdraw +1" when a user has already rated, it should not show "You and nn others +1 this." but show "You and nn others Withdraw +1 this" where Withdraw +1 is a button, as shown in this screen capture below: 
![rating](https://cloud.githubusercontent.com/assets/476302/9969899/77d2c6d0-5e1f-11e5-98dc-80ee0bfb0a08.png)
A PR has been created for this issue, once it is merged and deployed to dev, you can test.

**Comment by dtarb** [comment]
@hyi I think that as presented that is confusing.  I think that you should separate the "Withdraw +1" from the statement in cases where the user has already rated the resource as follows.

You and nn others +1 this.  [Withdraw +1]
or
You +1 this.  [Withdraw +1]
with the [Withdraw +1] that follows taking the appearance of a hyperlink, not a button.

**Comment by hyi** [comment]
@dtarb Agreed separating the [Withdraw +1] button from the statement in cases where the user has already rated the resource is clearer. However, I think [Withdraw +1] should be a button, just like [+1] button for other cases where the user has not rated, since an action will be taken, either withdraw +1 or +1, when the user click on it.

**Comment by dtarb** [comment]
OK.  Having something implemented that works is better than debating this.

**Comment by hyi** [comment]
@dtarb Implemented this to clear confusion in presentation. Screen captures for all cases are copied below for your perusal and correction if needed:
![rating_3](https://cloud.githubusercontent.com/assets/476302/9993279/f18eb0b6-6044-11e5-8aba-dbd555158f1e.png)
![rating_4](https://cloud.githubusercontent.com/assets/476302/9993290/fa40cc94-6044-11e5-907a-7598f2d33e1b.png)
![rating_2](https://cloud.githubusercontent.com/assets/476302/9993297/01bb4dd2-6045-11e5-803e-7def21807710.png)
![rating_1](https://cloud.githubusercontent.com/assets/476302/9993307/0af46780-6045-11e5-9c90-4fec697309c2.png)
Let me know if further changes are needed for the presentation. Updated code has been reflected in PR which once merged and deployed to dev, you can test and verify.

**Comment by dtarb** [comment]
@hyi the English writer in me wants to accommodate singular/plural cleanly.  I know this adds cases but it would be better to say
1 other +1 this
n others +1 this   (when n is greater than 1) 
You and 1 other +1 this
You and n others +1 this (when n is greater than 1)

**Comment by hyi** [comment]
@dtarb OK, singular/plural is accommodated. All cases involving singular/plural are summarized by screen captures below:
![rating_1](https://cloud.githubusercontent.com/assets/476302/9995129/7ba53e9c-604e-11e5-868d-6b65738e5656.png)
![rating_2](https://cloud.githubusercontent.com/assets/476302/9995128/7ba3a334-604e-11e5-843f-d3d20e9f8b78.png)
![rating_3](https://cloud.githubusercontent.com/assets/476302/9995130/7ba6318a-604e-11e5-90bf-00a8c77dc53c.png)
![rating_4](https://cloud.githubusercontent.com/assets/476302/9995127/7ba39a24-604e-11e5-8a54-5e79d47582e2.png)
Code is updated in PR as well, so you should be able to test and verify once it is merged and deployed.

**Comment by hyi** [comment]
@dtarb tested on dev and everything works as expected. Could you verify?

**Comment by hyi** [comment]
@dtarb sorry, but please hold off to test this. Just found an issue with anonymous users looking at public resources. Will make a fix shortly and create a PR to be merged in before you test this.

**Comment by hyi** [comment]
@dtarb The type error for anonymous users when clicking on a public resource is resolved on dev, so it is ready for testing on dev. Things all work as outlined here for a logged in user. However, for anonymous users, when a resource is unrated, anonymous users can see "+1" button to +1 a resource, and upon clicking on +1, the anonymous users are taken to login screen to login, which ensures only logged in user can rate a resource. However, when a resource is already rated by a logged in user, anonymous users will not see this +1 button any more. I have a follow-up fix for this and will create a PR shortly, which will ensure anonymous users always see +1 button regardless whether the resource is rated or not, and when anonymous users click on this +1 button, they will be taken to login screen. Let me know if what I described above for anonymous users is the desired behavior or not. If not, I can always amend the PR to make it behave as agreed for anonymous users.

**Comment by hyi** [comment]
@dtarb After further testing, I found there are some inconsistencies with rating numbers if exposing +1 button and allow an anonymous user to rate a resource while taking the user to login screen first. The default rating.html template page only exposes rating button when user is logged in or the resource is never rated, so I think it is a good idea to keep this default logic in Mezzanine code. So I think what is best to do at this point is to make wording better for anonymous users without exposing the +1 button. How about showing "x +1 this" (where x is the total number of +1s for the resource) for anonymous users when x > 0, otherwise, show "be the first one to +1 this" where +1 is not a button so anonymous users will not be able to vote. We may also add something like "Please login to rate this" for anonymous users to inform them. Let me know your thoughts on presentation in rating section for anonymous users and I will code accordingly.

**Comment by dtarb** [comment]
When a user is not logged in (for anonymous users) I think it would be good to have messages
"You need to be logged in to rate this" and "You need to be logged in to comment".  I think that these should be parenthetical comments that appear after the rating and commenting messages. 

![untitled](https://cloud.githubusercontent.com/assets/3456833/10263143/c4bf94a6-699f-11e5-88b4-ebcebdd353c4.png)
 
I think that a button "x+1 this" would be confusing.  I think that when a resource has been rated a user not logged in should still see  the +1 this button.  So for example it should look like.

**Comment by hyi** [comment]
@dtarb after looking into the code more and giving this more thought, I found a confusion caused by exposing +1 button to anonymous users that we may want to avoid. Specifically, if we expose +1 button to anonymous users for a resource which has already been rated by user A and if this anonymous user presses this +1 button which will take the user to login screen, and this anonymous user happens to login as user A, i.e., one of the users who has already rated the resource, this +1 action will be treated at "withdraw +1" since user A has already rated and an anonymous user pressed +1 button then login as user A. This is confusing since we have to show +1 button to an anonymous user and this +1 action is treated as "withdraw +1" since this anonymous user further log in as user A who has already rated the resource. Since we show "+1" or "withdraw +1" to the same button, I don't think it is a good idea to show this button to anonymous users given the confusion described above. I suggest to NOT show "+1" button to anonymous users. Let me know what you think is the desired behavior, I can then modify code to implement desired behavior for rating presentation for anonymous users accordingly.

**Comment by dtarb** [comment]
@hyi to avoid this confusion, I agree not to expose +1 button for users not logged in.  Instead show the messages above and make the words "logged in" in (You need to be logged in to rate this) a link that launches the log in screen and when logged in takes the user to the resource landing page with rating functionality activated.  Then it will be clear that they can +1, or if they have done so already withdraw +1 this.

**Comment by hyi** [comment]
@dtarb While implementing this, found the default behavior in mezzanine ratings template for handling anonymous user is: if the resource has never been rated, the +1 button will show up for anonymous users which will not cause confusion aforementioned since no withdraw+1 is possible for an unrated resource; otherwise, if the resource has been rated, this button will not show up for anonymous users and will only show up for login users. Do we want to keep this default behavior implied in mezzanine template? Although it will not cause confusion, it may create some inconsistency in ratings presentation for anonymous users. I can implement either way without problem, so let me know which way is desired so I can implement accordingly.

**Comment by hyi** [comment]
@dtarb I'll just go with keeping consistent rating presentation for now so +1 button will NOT show up for anonymous users regardless of whether the resource has been rated or not. Let me know if you prefer the other way as described above and I can change code pretty easily, but keeping consistent rating presentation for anonymous users appears preferable to me, so I'll just go with that for now.

**Comment by dtarb** [comment]
@hyi yes, consistency is good.  Since you can not rate a resource without being logged in, it is consistent to not show the button.  We should however still show the information on how many ratings there are, and the statement saying you have to log in to rate the resource with a login link.

**Comment by hyi** [comment]
@dtarb yes, agreed. Will implement this and create a PR to target for release 1.6.

**Comment by hyi** [comment]
@dtarb Just created a PR for this to target for release 1.6. Want to point out one thing, though. I did not change anything on comments for anonymous users, but only addressed ratings reflected in this issue. So comments will behave in the same way as before, i.e., the comment button will show for anonymous users, and once clicked, anonymous users will be taken to login screen. Since the comments don't have the +1 vs withdraw +1 issue as ratings, no confusion would result from exposing comment button to anonymous users. I don't have strong feelings that we need to keep ratings presentation to be consistent with comments presentation for anonymous users, but if you think we need to, you can create a different issue addressing comments presentation for anonymous users specifically after you get a chance to test for the new rating presentation.

**Comment by dtarb** [comment]
@hyi I think it is fine to leave comments as they are, until we get more use and learn from feedback if any changes are needed.

**Comment by hyi** [comment]
@dtarb It is working as expected on dev now. Please test it on dev and raise any further issues if any.

**Comment by dtarb** [comment]
Tested on dev.  Closing.
