### ISSUE TITLE
Remove UserAccess.admin attribute in hs_access_control app

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#631]

**Comment by hyi** [comment]
Adding a bug related to this admin's privilege for access control to this issue so that it will be fixed along with removal of admin attribute. Specifically, the privilege retrieved from get_combined_privilege() for a superuser in hs_access_control/models.py needs to be 1 rather than 4 as is now, so that superuser has full privilege over all resources.

**Comment by pkdash** [comment]
@hyi can you test this and if you think the issue has been addressed then close it?
