### ISSUE TITLE
Refactor read_metadata_from_resource_bag() to use importlib instead of __import__ builtin

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hydroshare#640]
read_metadata_from_resource_bag() uses **import** builtin, but should use importlib instead

**Comment by dtarb** [comment]
@hyi can you please evaluate whether this is still an issue.

**Comment by hyi** [comment]
@dtarb It is still an issue, as shown here: https://github.com/hydroshare/hydroshare/blob/develop/hs_core/serialization.py#L280..L281
I believe this is a best practice issue as @ironfroggy advised when @selimnairb implemented bag ingestion.

**Comment by hyi** [comment]
@jbradberry I am putting this on your plate for now since it is a very specific issue and I believe your expertise can address this quickly. This is low priority since this function has not been used in HydroShare production, but only used in a rush for manual migrations required by a big code refactoring. There is potential utility and use cases for this function to be used to recreate resources from bags. This function needs to be improved when we need to address those use cases when it is time to do so.

**Comment by Castronova** [comment]
Stale
