### ISSUE TITLE
Encode sequences in science metadata as sequences in the RDF+XML representation.

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hydroshare#658]
In science metadata for a resource, subject keywords may appear in the RDF+XML as:

```
<dc:subject>Systems model</dc:subject>
<dc:subject>wetland management</dc:subject>
<dc:subject>water allocation</dc:subject>
<dc:subject>invasive vegetation control</dc:subject>
<dc:subject>Bear River Migratory Bird Refuge</dc:subject>
<dc:subject>Utah</dc:subject>
```

but when querying the RDF graph (using rdflib), the subject elements are returned in arbitrary order, such as:

```
wetland management
water allocation
Utah
Systems model
invasive vegetation control
Bear River Migratory Bird Refuge
```

(I don't believe there is a way to get rdflib to return triples in the order in which they appeared in the serialization, but I am new to the API and could of course be missing something.)

The fundamental problem, in my opinion, is that some metadata elements are parts of collections (e.g. keywords, collaborators, creators), but our serialization does not explicitly represent them as collections (as described in the [spec](http://www.w3.org/TR/rdf-syntax-grammar/#section-Syntax-parsetype-Collection)).  Further, for collections where ordering of the elements is important, there should be an order attribute for each element, so that parsers can reconstruct that order on deserialization.

**Comment by horsburgh** [comment]
@selimnairb - We could add rdf collection containers or sequence containers (for collections where order matters) to the rdf documents.  I'm not sure we need it though.  And, I'm not sure whether the parsers you are using would interpret the sequence ordering correctly.

We already have an order prescribed to the authors - that is super important.  What do others think about this?  Here is an example from the Dublin Core documentation (http://dublincore.org/documents/2002/04/14/dcq-rdf-xml/):

    <?xml version="1.0"?>
    <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
         xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
         xmlns:dc="http://purl.org/dc/elements/1.1/"
         xmlns:dcterms="http://purl.org/dc/terms/">
    <rdf:Description>
    <dc:contributor>   
    <rdf:Seq>
        <rdf:li>Karin Mustermann Inc.</rdf:li>
        <rdf:li>John Doe Inc.</rdf:li>
    </rdf:Seq>
    </dc:contributor>
    </rdf:Description>
    </rdf:RDF>

This results in the following RDF graph, where the order of the elements in the sequence is shown:

![rdfseqexample](https://cloud.githubusercontent.com/assets/3485902/10348268/50854d8e-6cf5-11e5-93d1-bc10d7587c60.png)

**Comment by dtarb** [comment]
@sblack-usu close or act on if needed

**Comment by sblack-usu** [comment]
@horsburgh - I haven't encountered a mechanism for maintaining order in the rdf/xml before.  I think it's worth looking into and ensuring not only the order of a set of elements but also the order the elements are written to the rdf/xml.  This would make committing a hydroshare resource to git cleaner.  If we are not maintaining order, each commit include rearranging elements rather than just the changes.

**Comment by horsburgh** [comment]
@sblack-usu - the rdf sequence that I suggested above can be used to preserve order for elements like Creator where the order actually matters. But, that wouldn't affect the order in which all of the other rdf elements in the metadata files are written. Seems like most of the tools and examples I have seen do not maintain order. I agree that this makes things tricky.

**Comment by horsburgh** [comment]
I think what is suggested in this issue is a technically more correct way of encoding our RDF/XML to give/preserver order to sequences of things. However, I think the only sequence that really matters in our metadata is the order of authors, and we have already handled that via another mechanism. I'm going to close this issue because, while it might be nice to do this, it really won't change any functionality for users so the value proposition is low.
