### ISSUE TITLE
The delete resource button is missing for a geographic raster resource

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#67]
This is in alpha.hydroshare.org on 1/15/15.

**Comment by hyi** [comment]
I believe this problem is caused by raster-related permissions not being added for the HydroShare Author group in the initial database we populate. This can be fixed either by manually adding these specific resource type related permissions to the HydrShare Author group from the admin interface, or adding them into the initial database we populate. This will apply for all specific resource types.

**Comment by mjstealey** [comment]
Hydroshare Author permissions update solves this
