### ISSUE TITLE
REST API not to expose resource contents for resources that are private and discoverable

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#685]
This includes resource content files, bag file, resourcemetadata.xml and resourcemap.xml. A resource that is private and discoverable, these files should not be accessible though the API.

**Comment by horsburgh** [comment]
Should access to the resourcemetadata.xml document be restricted through the API for discoverable resources?  Wouldn't all of the metadata for discoverable resources be exposed anyway?

**Comment by dtarb** [comment]
The metadata for discoverable resources should not be restricted.  Only access to the content files should be restricted.

**Comment by selimnairb** [comment]
@pkdash The system currently works as @dtarb suggests.  Should this be changed?

**Comment by pkdash** [comment]
@selimnairb I was wrong about the access to the content files. Those are already restricted. It looks to me though an anonymous user will not be able to get the metadata file via REST API if the resource is private and discoverable. However, the same user can see the metadata for that resource on the web front-end. This may be another issue. The resource list api returning data for each resource that includes the bag url. Should we be hiding the bag url for resources that are private and discoverable unless the user has at least view permission?

**Comment by selimnairb** [comment]
@pkdash The user is not able to download the bag for discoverable resources, so I don't think it hurts to include it.  I will change permissions so that the metadata documents are downloadable via REST API for users who do not have permissions on the resource.  @pkdash @dtarb Let me know if you want me to remove the bag URL for such users. (I don't have a strong opinion).

**Comment by dtarb** [comment]
I discussed with @pkdash and we decided to leave as is for consistency.

**Comment by pkdash** [comment]
@selimnairb @dtarb should we include the 'discoverable' attribute in returned resource list data?

**Comment by dtarb** [comment]
The access control policy (see https://my.alfresco.com/share/s/WJuMf2ghRlyuty0oXrqe5g) specifies 5 sharing attributes that may be set for each resource: Shareable, Discoverable, Public, Published, Immutable.  If you are considering which should be returned with a resource list, and you are going to include some, why not include all.

**Comment by pkdash** [comment]
Good point. We should include all those 5 attributes in resource data from the REST API. Probably the same should apply to the resource landing page. Currently we are not showing Published and Immutable on the landing page.

**Comment by selimnairb** [comment]
@pkdash @dtarb Just to confirm, I will:

- Keep the science_metadata_url for discoverable resources; and
- Make it so that discoverable resources have world-readible system and science metadata; and
- Add shareable, discoverable, published, and immutable flags in the resource system metadata/resource list.

Anything else that needs doing for this issue?
