### ISSUE TITLE
Home page and sign up revamp

### ISSUE THREAD

**Issue by mauriel133** [hydroshare/hydroshare#686]
I will be revamping the home page and the sign up form.

**Comment by ironfroggy** [comment]
What is your process for doing this? While you are doing this revamp, I'm also preparing an updated UX Recommendations document, and I'll be including homepage and signup recommendations. I'll have this delivered by the end of the week. Will you taking those recommendations into consideration along with @dtarb in your revamp of these pages?

**Comment by mauriel133** [comment]
Jeff and I are still in the process of discussing it. We can wait for your recommendations.

**Comment by dtarb** [comment]
This revamp should address the following concerns in report from @ironfroggy 

* No clear navigation at registration. After registering, the user is still on the signup page with a small and easily ignorable message to check their email. There needs to be a clear navigation as part of registration.

* Registration gives no clear next step. After e-mail verification, the user is dropped back on the homepage with another small message and no clear next actionable step. Drop them on their profile form or the discovery page or some “Introduction to Hydroshare” page.

**Comment by mauriel133** [comment]
@horsburgh, we need to address @dtarb's suggestions above concerning sign up workflow. Have any ideas?

**Comment by horsburgh** [comment]
When a user completes the sign up form, HydroShare takes them back to the home page where a message is displayed at the top of the window that states that they should check their email. This is fine, but I suggest adding some color to the message to make it more noticeable. Right now the message could be missed by the user.

Clicking the verification link in the email currently takes the user to the home page with a message that simply says that they have successfully signed up. I think this should be modified so that the user is taken to the profile page. At the top of the profile page the following message should be displayed in color so it's noticeable:

"Your account has been successfully created. Welcome to HydroShare! Please take a few moments to complete your user profile. Then, visit the My Resources page to begin creating your own resources or the Discover page to see what others have shared."

When we have a user dashboard page (I hope we make it this far), we should consider dumping them on their dashboard immediately after confirming their account so they could immediately start interacting with content in HydroShare. But, since we do not have a dashboard yet, let's take them to their profile page.

**Comment by mauriel133** [comment]
@pkdash, was this also taken care of with the revamp of the account creation workflow?

**Comment by pkdash** [comment]
@mauriel133 No. This has not been implemented.
