### ISSUE TITLE
Improve appearance of forbidden pages

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#697]
From @ironfroggy report.  Forbidden pages are a part of the platform to be expected to hit when some operations happen, like trying to access a resource that has been made private and to which you do not have access. Unfortunately, no information is given to the user about why they are seeing this error. It is likely the user had a typo the name of a resource, or forgot to log into the website first, or has more than one account and is using the wrong one, or that the owner intended to give access to the resource but neglected to do so.

Recommendations:
- Show the normal site template for the 403 pages
- Include helpful message about the name of the resource being accessed
- Include the current account which does not have access and link to login
- Include a brief explanation about why access is denied
- Include a prompt to ask the Resource owner to share access to the resource

**Comment by hyi** [comment]
@dtarb @horsburgh I have created a forbidden 403 page to improve its appearance. Since we don't have page resource context passed in to a forbidden page, this page template does not know anything about the forbidden resource such as its title, its owners, etc., and I don't think it is a good idea to expose resource detailed info to a user who does not have permission to view the resource. So here is what I have right now. If a user is not signed in, the user will see a page like the following:
![notloggedin](https://cloud.githubusercontent.com/assets/476302/20771193/6bce70ae-b716-11e6-9815-0009e7fca6bf.png)
If a user has logged in but does not have proper access permission to this resource, the user will see a page like the following:
![loggedinerror](https://cloud.githubusercontent.com/assets/476302/20771206/7f5d47bc-b716-11e6-836a-908f6d450141.png)

Please correct the wordings as needed and let me know whether this is sufficient for appearance improvement without requiring too much work.

**Comment by horsburgh** [comment]
@dtarb - I'm having vague recollections that you wrote down at one point what you wanted to display is a user is not authorized to view a resource. Am I remembering wrong?

**Comment by dtarb** [comment]
@horsburgh you are remembering right.  I suggested that as a matter of policy the resource title, owners and GUID are public information.  The rest of the information on the resource is subject to access control rules.  This means that anyone hitting a link that has a GUID embedded in it get a small landing page that gives this information.  The owner name (or owners if there are multiple owners) is to be provided with a link to their HydroShare profile so that a registered HydroShare user can send them an email to request access.  Only registered users get to see the mailto link for other users.  I do not know if/where this is written, but the above is the gist of it.

I suggest a page similar to the following if the user is not logged in (most common case if someone has been sent a GUID to a private resource shared with them).  If they are logged in shorten the words to: "The resource you have attempted to access is private.  You can request access from the owner."

![untitled](https://cloud.githubusercontent.com/assets/3456833/20775585/e98d5364-b718-11e6-9495-3d6c9e7f4721.png)

**Comment by hyi** [comment]
@dtarb Can you verify this on beta and close it if it works? If you want that nice-to-have redirect to resource landing page after signing in, you can create a new issue.

**Comment by dtarb** [comment]
Thanks.  Closing.
