### ISSUE TITLE
Resource title does not get updated on profile page when read from resource file

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#721]
If I create a resource (Multidimensional) from a netCDF file that has a title as part of its metadata and I do not specify a title at the create resource page, I end up with a resource that gets the title from the file uploaded (which is correct), but on the listing of resources on my profile page the title is "Untitled".

An example of this is https://www.hydroshare.org/resource/0bfc9ba00fbe400f8e139cdaa83c8511/.  The title "Rapid Result" was read from the netCDF file title entry during upload. 

However if I click on the link to my profile (next to Author or Owners) the listing there shows the resource as "Untitled"

**Comment by pkdash** [comment]
@dtarb This fix can be tested on dev.hydroshare.org

**Comment by dtarb** [comment]
@pkdash @hyi I tried to test this but at this time I am unable to create an account to do so.  The button "Join HydroShare & start collaboration" is non responsive on the sign up page on dev.hydroshare.org.

**Comment by hyi** [comment]
@dtarb @ironfroggy @pkdash dev is working again after I followed @mjstealey's guidance to change http to https for recaptcha URL (yes, @mjstealey has been keeping an eye on hydroshare issues during his special leave and we exchanged a couple of emails for this issue). I will create an issue next to change http to https in https://github.com/hydroshare/hydroshare/blob/develop/theme/templates/accounts/_signup_form.html#L1 so that we will not run into issues again in next dev build. I did verify this change will also work in my local dev env so I don't think we need to keep http in recaptcha url in _signup_form.html.

**Comment by hyi** [comment]
@dtarb @ironfroggy @pkdash @mjstealey Verified the reason it works in my local dev env is because running ./hsctl restart call changes recaptcha url in _signup_form.html from https to http to correspond to my local dev env settings. So I decided not to create an issue to change initial setting for recaptcha url in _signup_form.html after all. Will see whether dev will rebuild correctly on its next automatic build to change recaptcha url accordingly and go from there. Will leave how to best handle this situation to @mjstealey upon his return from leave.

**Comment by dtarb** [comment]
I have now verified that this issue is fixed on the recently deployed beta.hydroshare.org, so closing.  The issue of the capcha and dev from comments above is separate.
