### ISSUE TITLE
Whitespace in resource specific tab

### ISSUE THREAD

**Issue by mauriel133** [hydroshare/hydroshare#734]
There is a lot of white space in the resource specific tab of the resource landing page for some resource types. 

I will be restyling the layout for some resource types to make better use of this space.

**Comment by gantian127** [comment]
@mauriel133 I just tested the netcdf and raster resource. I have the following suggestions and you may implement them if you think they make sense. Thank you.
1) For raster view mode layout, it may just set "spatial reference", 'cell information' 'band information in separate lines. The bandInformation may include multiple repeated elements so they can be managed as the way for netcdf "variable" element which is implemented in this branch.
2) For netcdf editing mode layout, I suggest to make the variable forms in a confined length similar for the variable layout under view mode. Otherwise, the tab is extended to a long form list under editing mode.

**Comment by mauriel133** [comment]
Tian, I will implement both of your suggestions today.

**Comment by zhiyuli** [comment]
@mauriel133 The changes look great. One small suggestion, the attribute header text (like "Coordinate Reference System") shows in multiple lines. Can we give it more space to avoid this? 
The value of the "Coordinate String" are always multiple lines, maybe we could try to align all headers and values to the top, so header-value's one to one relationship is more clear.

![image](https://cloud.githubusercontent.com/assets/10070599/11632524/d047dc18-9cc4-11e5-85ce-16aa33dcaa9e.png)

**Comment by mauriel133** [comment]
Agree with your suggestions. I will implement them with the next changes.

**Comment by mauriel133** [comment]
@zhiyuli, I aligned the headers and values to the top as suggested. This made things much clearer.

However, assigning a minimum width to the headers conflicts with the responsive layout we are trying to maintain. So this one I cannot do.

**Comment by mauriel133** [comment]
All suggestions addressed and confirmed working. Closing...
