### ISSUE TITLE
Gracefully handle user entry of text fields that exceed length limits

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#75]
If a user enters a variable name for a geographic raster resource that is longer than the allowable limit (50 characters) the following error occurs:

![capture](https://cloud.githubusercontent.com/assets/3456833/5793084/fc90e396-9f04-11e4-8c06-e79be81107d4.JPG)

I suggest the following changes:
1.  Increase the limit to 100 characters.  50 characters may  be too small.  We need to consistently across HydroShare decide on what limits are reasonable to accommodate user inputs and apply them in a user friendly way.  For some fields it makes sense to have a limit (variable name is one).  For others we should have flexibility (e.g. abstract), where if a user enters something very long it consumes their quota and may take time in loading.

2.  Where a limit is reached the system should handle it gracefully by for example
a. not allowing entry of characters past the limit in the text box.  A user would then see that they have bumped into the end
b. include on the interface and indication of the limit when editing (e.g. 100 characters next to the field being entered or edited)
c. If too much or invalid content is submitted, bounce back to the entry page with the invalid field in red to allow the user to fix.  If we do (a) we may not need this unless there are other ways that entry can be invalid (such as disallowed special characters).  If there are disallowed special characters, we should also indicate these on the interface.

In doing this, if this content is going into database fields we should be mindful of SQL injection attacks and use best security practices for parsing the content entered that avoids a SQL injection damaging our database.
.

**Comment by hyi** [comment]
I changed this field to be text field rather than char field with a hardcoded length limit so users will not run into this "exceeding limit" error. I think this approach is better for all fields whose hardcoded length could be exceeded rather than adding logic to inform users the limit they have to stick to gracefully. Fix pushed to github to be merged into develop.

**Comment by rayi113** [comment]
HydroShare Generic Resource Issues in GitHub: #3, #57, #75

**Comment by hyi** [comment]
Revert VariableName field max_length to be 100 (rather than text field) and enforce the text box input to be at most 100 characters (i.e., users will not be able to enter any characters after they have already entered 100 characters). This GUI text box input enforcement to comply with model definition works for other fields with a max_length restriction as well.

**Comment by dtarb** [comment]
Appears resolved based on my testing
