### ISSUE TITLE
Duplicate record problem in hs_labels app

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#820]

**Comment by alvacouch** [comment]
This isn't solved. I have a new version of labeling that will expose the issue more directly, by raising an exception at time of request, rather than at time of subsequent request. This will protect the integrity of the labeling system while making discovery of the root cause easier. Will pursue after AGU rush is over.

**Comment by alvacouch** [comment]
It seems like the real solution is to enclose the get_or_create statements in a Django transaction block. If this doesn't work, _there is a bug in Django_. I am surprised that a transaction block might be necessary *for a single statement*, but "that's life". Worth a try for sure.

**Comment by alvacouch** [comment]
This issue was solved in PR #821
