### ISSUE TITLE
Create a new resource type for a MODFLOW model instance resource

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#850]
This should be a new resource type to hold the input and output files for a MODFLOW model. The MODFLOW program itself is stored in a separate resource.

**Comment by dtarb** [comment]
Similar to #849 here we should first try and populate a standard model instance resource with the files for a MODFLOW model instance.  This should be the default whenever a new kind of model program and instance is found.  The standard model program and model instances should only be extended by programming where there are pressing needs for extension due to them not being able to hold the content of the kind of model being used.

**Comment by jsadler2** [comment]
Phase one of this has been completed. Closing issue.
