### ISSUE TITLE
Resource Metadata and Landing Page:  Need a Metadata Item for Funding Agency

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#937]
Users need to be able to enter information about a funding agency associated with their resource, including:

* [x] The name of the funding agency
* [x] Optional - The title of the award
* [x] Optional - The grant number associated with the resource that they have created.
* [x] Optional - A URL link to an abstract on an external website (e.g., a link to the abstract for the project on NSF's website).

When a URL is provided, the grant number and/or funding agency name could be changed to a hyperlink on the landing page when it is displayed so that a user can click on the link and open a new browser tab/window to the external website.

**Comment by pkdash** [comment]
@horsburgh Is this new metadata be part of the science metadata document?

**Comment by horsburgh** [comment]
@pkdash - yes, it should be.  I just glanced through the Dublin Core metadata terms and there are not appropriate terms to capture this information.  So, we are going to have to figure out how to encode it.  

There may be some sentiment that we should make this part of an extensible metadata model using key/value pairs.  But, I think it's emerging in many of the data use cases that people are brining forward and so I think we might want to make it more prominent.  I'm open to ideas about implementation.

**Comment by horsburgh** [comment]
Actually - one could consider the funding agency as a "Contributor", but that might not be specific enough.

**Comment by dtarb** [comment]
I've been advocating for the extensible metadata model, but from a user perspective it needs to be prominent and obvious where a user should enter this information.  At the back end this may be implemented using a key value approach to give a generality to our code structures.

**Comment by pkdash** [comment]
We can easily add this new metadata element similar to how all other metadata elements are currently implemented in hs_core. I assume this will be part of the core metadata. That means different resource types need no code change. Since this element has sub-elements (name, grant number, and URL) I am not sure how it can be implemented as key/value pair. But for other arbitrary metadata elements that fit the key/value structure, it is not hard to add that functionality.

**Comment by horsburgh** [comment]
@pkdash - your assumptions here are correct.  Does someone need to add these on the backend so that Mauriel can expose them on the landing page and the resource metadata editing page?

**Comment by pkdash** [comment]
@horsburgh Yes this new metadata element needs to be added at the backend first. I can do that. I  need to know how big (number of characters) the name and grant number fields have to be and how we should be encoding this element.

**Comment by horsburgh** [comment]
After thinking about this a little more, it would probably be good to encode funding information at the granularity of a research award.  So, for each award I would give them the following:

* 250 characters for the name of the agency that funded the award (required)
* 250 characters for the award title (optional)
* 100 characters for the award number (optional)
* Whatever length we are using for other URLs in the metadata (optional)

I would encode it as follows.  The whole "awardInfo" element needs to be repeatable because there may be multiple funding agencies, awards, etc (such as is the case with the HydroShare award).

    <hsterms:awardInfo>
        <rdf:Description rdf:about="http://www.nsf.gov/awardsearch/showAward?AWD_ID=1148453">
            <hsterms:fundingAgencyName>National Science Foundation</hsterms:fundingAgencyName>
            <hsterms:awardTitle>Collaborative Research: SI2-SSI: An Interactive Software Infrastructure for Sustaining Collaborative Community Innovation in the Hydrologic Sciences</hsterms:awardTitle>
            <hsterms:awardNumber>ACI 1148453</hsterms:awardNumber>
        </rdf:Description> 
    </hsterms:awardInfo>
    <hsterms:awardInfo>
        <rdf:Description rdf:about="http://www.nsf.gov/awardsearch/showAward?AWD_ID=1148090">
            <hsterms:fundingAgencyName>National Science Foundation</hsterms:fundingAgencyName>
            <hsterms:awardTitle>Collaborative Research: SI2-SSI: An Interactive Software Infrastructure for Sustaining Collaborative Community Innovation in the Hydrologic Sciences</hsterms:awardTitle>
            <hsterms:awardNumber>ACI 1148090</hsterms:awardNumber>
        </rdf:Description> 
    </hsterms:awardInfo>

**Comment by pkdash** [comment]
@horsburgh and @mauriel133 I will create a new branch to implement this backend support. Then @mauriel133 can use that branch to add the UI implementation.

**Comment by dtarb** [comment]
Please if at all possible use field types that are flexible in length rather than setting character limits.  Exceptions that exceed character limits commonly come up.  I seem to recall an earlier suggestion from @ironfroggy that was similar to this.

Also, @horsburgh in designing this functionality please consider the text I wrote in the roadmap for enhancements for credit attribution.

USE CASE (From Rick Hooper Email)
A scientist completes an NSF-funded project and comes to the WDC with a request to publish her data, which consists a variety of data types. WDC uses Hydroshare to publish data associated with the project. An NSF program officer can access Hydroshare to ascertain that data for a particular NSF-funded project.
 
Implications: Add “Funding Agency” and “Grant Number” as alphanumeric fields for all resource types; possibly Grant PI (may be different from author/owner of resource). Add the search hydroshare catalog by funding agency AND number so that NSF program officer can easily look up resources associated with grant number (i.e., NSF EAR-XXXXXXX).

Consider additional credit attribution categories.  PLOS (see e.g. (http://dx.doi.org/10.1371/journal.pone.0144111)  supports ability to designate author (creator) and contributor contributions. where at the end of the paper it indicates

- Conceived and designed the experiments
- Analyzed the data
- Contributed reagents/materials/analysis tools
- Wrote the paper

I suggested before, and I suggest again that we need to implement a credit map such as given by Katz on slide 20 in http://www.slideshare.net/danielskatz/metrics-citation-for-software-and-data.

I think that all this funding agency information should be optional.  We may have resources contributed by users that do not have funding.  So I do not think the name of the agency should be required as is indicated above.

**Comment by horsburgh** [comment]
The metadata fields are stored in a database and have to have a length.  We can make them longer if you want.

The funding agency name should be required but ONLY IF the user wants to add award information.  The whole award information block should be optional if there is no funding acknowledgement.

I think adding the PI of a an award is overkill, but we could add that as an additional (optional) field if you want.

If we want the ability to specify author and contributor contributions, that should be a different issue it isn't related to funding agency. Also, I looked at slide 20 in the presentation you link to. It doesn't apply to this specific issue.  If we want to do all of that, we need separate issues. It would potentially enable users to create a rich description of who did what, but would potentially require a lot of development effort and its uncertain whether people would fill all of that metadata out.

**Comment by pkdash** [comment]
We can use ```TextField()``` which doesn't have a length limit.

**Comment by mauriel133** [comment]
@pkdash, is the back end support for this ready?

**Comment by pkdash** [comment]
@mauriel133 Not yet.

**Comment by pkdash** [comment]
@mauriel133 I have now implemented the backend code for this issue in branch 937-metadata-for-funding-agency.

**Comment by pkdash** [comment]
@horsburgh See if this can be closed.

**Comment by horsburgh** [comment]
@pkdash and @dtarb - I am closing this issue because it has been implemented and is live on www.hydroshare.org.  But, it doesn't address the further comments by @dtarb about credit mapping:

> I suggested before, and I suggest again that we need to implement a credit map such as given by Katz on slide 20 in http://www.slideshare.net/danielskatz/metrics-citation-for-software-and-data.

If we still want to do full credit mapping as described by Katz, a separate issue needs to be opened.
