### ISSUE TITLE
Create model program resource - not added to discovery in real-time

### ISSUE THREAD

**Issue by wzell-usgs** [hydroshare/hydroshare#960]
Cannot find newly created model program resource via 'discovery'.
Only discoverable via link.

https://www.hydroshare.org/resource/ba94cc37e8f1409d8bd515bb49bd955e/

**Comment by mjstealey** [comment]
> Cannot find newly created model program resource

At this time our discovery page isn't updated in real-time. 
There is a process that runs periodically to pick up any new or modified resource information and populate the database used to drive the discovery engine.

This is slated to be fixed in future releases, but hasn't been put into our production server just yet.

**Comment by alvacouch** [comment]
Addressed by issue #1164 ... pending approvals.....

**Comment by hyi** [comment]
This should have been addressed by real time solr index update. Closing.
