### ISSUE TITLE
Discover uses incorrect title

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#998]
If you go to Discover and search on "rapid" then click David Tarboton next to filter by author, you get the following.  However if you click on the link "untitled" you see that the resource has a title.
![untitled](https://cloud.githubusercontent.com/assets/3456833/13219497/9fdc1cc4-d92d-11e5-82a9-c273e1cd8221.png)

**Comment by pkdash** [comment]
It is in a sense. For any new resource this should get fixed by PR #1097. For existing resources it is still going to be the issues until that resource get updated. However, once a change in discover page is made to use the title from the metadata (res.metadata.title.value) instead of title from the resource (res.title) it should resolve the issue with the existing resources.

**Comment by hyi** [comment]
@dtarb Can you verify and close if fixed?

**Comment by dtarb** [comment]
This seems fixed.
